// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxlaunch

#include "ui.h"

void ui_screen_init(lv_obj_t * ui_pnlContent)
{
    ui_pnlExplore = lv_obj_create(ui_pnlContent);
    ui_pnlFavourites = lv_obj_create(ui_pnlContent);
    ui_pnlHistory = lv_obj_create(ui_pnlContent);
    ui_pnlApps = lv_obj_create(ui_pnlContent);
    ui_pnlInfo = lv_obj_create(ui_pnlContent);
    ui_pnlConfig = lv_obj_create(ui_pnlContent);
    ui_pnlReboot = lv_obj_create(ui_pnlContent);
    ui_pnlShutdown = lv_obj_create(ui_pnlContent);

    ui_lblContent = lv_label_create(ui_pnlExplore);
    ui_lblFavourites = lv_label_create(ui_pnlFavourites);
    ui_lblHistory = lv_label_create(ui_pnlHistory);
    ui_lblApps = lv_label_create(ui_pnlApps);
    ui_lblInfo = lv_label_create(ui_pnlInfo);
    ui_lblConfig = lv_label_create(ui_pnlConfig);
    ui_lblReboot = lv_label_create(ui_pnlReboot);
    ui_lblShutdown = lv_label_create(ui_pnlShutdown);

    ui_icoContent = lv_img_create(ui_pnlExplore);
    ui_icoFavourites = lv_img_create(ui_pnlFavourites);
    ui_icoHistory = lv_img_create(ui_pnlHistory);
    ui_icoApps = lv_img_create(ui_pnlApps);
    ui_icoInfo = lv_img_create(ui_pnlInfo);
    ui_icoConfig = lv_img_create(ui_pnlConfig);
    ui_icoReboot = lv_img_create(ui_pnlReboot);
    ui_icoShutdown = lv_img_create(ui_pnlShutdown);
}
