#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_t_table[] = {
        {"tacscan",      "Tac-Scan"},
        {"tactcan2",     "Tactician (set 2)"},
        {"tactcian",     "Tactician (set 1)"},
        {"tactcian2",    "Tactician (set 2)"},
        {"tagteam",      "Tag Team Wrestling"},
        {"taiko10",      "Taiko No Tatsujin 10 (T101001-NA-A)"},
        {"taiko9",       "Taiko No Tatsujin 9 (TK91001-NA-A)"},
        {"tail2nos",     "Tail to Nose - Great Championship"},
        {"tail2nosa",    "Tail to Nose - Great Championship"},
        {"tailg",        "Tailgunner"},
        {"taitofx1",     "Taito FX1"},
        {"taitogn",      "Taito GNET"},
        {"taiwanmb",     "Taiwan Mahjong [BET] (Japan 881208)"},
        {"takoron",      "Noukone Puzzle Takoron (Japan) (GDL-0042)"},
        {"talbot",       "Talbot"},
        {"tangtang",     "Tang Tang (ver. 0526, 26-05-2000)"},
        {"tank8",        "Tank 8 (set 1)"},
        {"tank8a",       "Tank 8 (set 2)"},
        {"tank8b",       "Tank 8 (set 3)"},
        {"tank8c",       "Tank 8 (set 4)"},
        {"tank8d",       "Tank 8 (set 5)"},
        {"tankbatl",     "Tank Battle (prototype rev. 4/21/92)"},
        {"tankbatt",     "Tank Battalion"},
        {"tankbattb",    "Tank Battalion (bootleg)"},
        {"tankbust",     "Tank Busters"},
        {"tankfrce",     "Tank Force (US)"},
        {"tankfrce4",    "Tank Force (US, 4 Players)"},
        {"tankfrcej",    "Tank Force (Japan)"},
        {"tankfrcj",     "Tank Force (Japan)"},
        {"tantr",        "Puzzle & Action: Tant-R (Japan)"},
        {"tantrbl",      "Puzzle & Action: Tant-R (Japan) (bootleg set 1)"},
        {"tantrbl2",     "Puzzle & Action: Tant-R (Japan) (bootleg set 2)"},
        {"tantrbl3",     "Puzzle & Action: Tant-R (Japan) (bootleg set 3)"},
        {"tantrbl4",     "Puzzle & Action: Tant-R (Japan) (bootleg set 4)"},
        {"tantrkor",     "Puzzle & Action: Tant-R (Korea)"},
        {"taotaida",     "Tao Taido (set 2)"},
        {"taotaido",     "Tao Taido (set 1)"},
        {"taotaido3",    "Tao Taido (2/3 button version)"},
        {"taotaidoa",    "Tao Taido (6 button version)"},
        {"tapatune",     "Tap a Tune"},
        {"tapper",       "Tapper (Budweiser)"},
        {"tappera",      "Tapper (alternate)"},
        {"tapperb",      "Tapper (Budweiser, 12/9/83)"},
        {"tapperg",      "Tapper (Budweiser, 1/27/84 - Alternate graphics)"},
        {"targ",         "Targ"},
        {"targc",        "Targ (cocktail[Q])"},
        {"targeth",      "Target Hits"},
        {"targeth10",    "Target Hits (ver 1.0, Checksum FBCB)"},
        {"targetha",     "Target Hits (ver 1.1, Checksum 86E1)"},
        {"tattack",      "Time Attacker"},
        {"tattass",      "Tattoo Assassins (US Prototype)"},
        {"tattassa",     "Tattoo Assassins (Asia Prototype)"},
        {"taxidriv",     "Taxi Driver"},
        {"taxidrvr",     "Taxi Driver"},
        {"tazmani2",     "Tazz-Mania (set 2)"},
        {"tazmani3",     "Tazz-Mania (Arfyc / Rodmar bootleg)"},
        {"tazmania",     "Tazz-Mania (set 1)"},
        {"tazzmang",     "Tazz-Mania (bootleg on Galaxian hardware)"},
        {"tazzmang2",    "Tazz-Mania (bootleg on Galaxian hardware with Starfield)"},
        {"tbblue",       "ZX Spectrum Next: TBBlue"},
        {"tbeastw2",     "Transformers Beast Wars II"},
        {"tblkkuzu",     "The Block Kuzushi (Japan)"},
        {"tbowl",        "Tecmo Bowl (World[Q])"},
        {"tbowla",       "Tecmo Bowl (World, set 2)"},
        {"tbowlj",       "Tecmo Bowl (Japan)"},
        {"tbowlp",       "Tecmo Bowl (World, prototype?)"},
        {"tbyahhoo",     "Twin Bee Yahhoo! (ver JAA)"},
        {"tceptor",      "Thunder Ceptor"},
        {"tceptor2",     "Thunder Ceptor II"},
        {"tcl",          "Taiwan Chess Legend"},
        {"tcobra2",      "Twin Cobra II (Ver 2.1O 1995/11/30)"},
        {"tcobra2u",     "Twin Cobra II (Ver 2.1A 1995/11/30)"},
        {"tdfever",      "TouchDown Fever"},
        {"tdfever2",     "TouchDown Fever 2"},
        {"tdfever2b",    "TouchDown Fever 2 (bootleg)"},
        {"tdfeverj",     "TouchDown Fever (Japan)"},
        {"tdragon",      "Thunder Dragon"},
        {"tdragon1",     "Thunder Dragon (4th Jun. 1991, protected)"},
        {"tdragon2",     "Thunder Dragon 2 (9th Nov. 1993)"},
        {"tdragon2a",    "Thunder Dragon 2 (1st Oct. 1993)"},
        {"tdragon3h",    "Thunder Dragon 3 (bootleg of Thunder Dragon 2)"},
        {"tdragonb",     "Thunder Dragon (Bootleg)"},
        {"tdragonb3",    "Thunder Dragon (bootleg with Raiden sounds, unencrypted)"},
        {"tduno",        "Touch de Uno! / Unou Nouryoku Check Machine (Japan)"},
        {"tduno2",       "Touch de Uno! 2 (Japan)"},
        {"teamht",       "Team Hat Trick (11/16/84)"},
        {"teamqb",       "John Elway's Team Quarterback"},
        {"teamqb2",      "John Elway's Team Quarterback (set 2)"},
        {"techbowl",     "Technical Bowling (J 971212 V1.000)"},
        {"technodr",     "Techno Drive (Japan, TH1/VER.B)"},
        {"techromn",     "Tech Romancer (USA 980914)"},
        {"techromnu",    "Tech Romancer (USA 980914)"},
        {"tecmowcm",     "Tecmo World Cup Millennium (Japan)"},
        {"teddybb",      "TeddyBoy Blues (New Ver.)"},
        {"teddybbo",     "TeddyBoy Blues (Old Ver.)"},
        {"teddybboa",    "TeddyBoy Blues (315-5111, Old Ver.)"},
        {"teddybbobl",   "TeddyBoy Blues (Old Ver. bootleg)"},
        {"teedoff",      "Tee'd Off (Japan)"},
        {"teedoffj",     "Tee'd Off (Japan)"},
        {"teetert",      "Teeter Torture (prototype)"},
        {"tehkanwc",     "Tehkan World Cup"},
        {"tehkanwcb",    "Tehkan World Cup (set 2, bootleg?)"},
        {"tehkanwcc",    "Tehkan World Cup (set 3, bootleg)"},
        {"tehkanwcd",    "Tehkan World Cup (set 4, earlier)"},
        {"tehkanwch",    "Tehkan World Cup (1986 year hack)"},
        {"tekipaki",     "Teki Paki"},
        {"tekipakit",    "Teki Paki (location test)"},
        {"tekken",       "Tekken (TE4-VER.C)"},
        {"tekken2",      "Tekken 2 Ver.B (TES3-VER.B)"},
        {"tekken2a",     "Tekken 2 Ver.B (TES2-VER.B)"},
        {"tekken2b",     "Tekken 2 (TES2-VER.A)"},
        {"tekken2jb",    "Tekken 2 Ver.B (Japan, TES1/VER.B)"},
        {"tekken2jc",    "Tekken 2 Ver.B (Japan, TES1/VER.C)"},
        {"tekken2ua",    "Tekken 2 (US, TES3/VER.A)"},
        {"tekken2ub",    "Tekken 2 Ver.B (US, TES3/VER.B)"},
        {"tekken2ud",    "Tekken 2 Ver.B (US, TES3/VER.D)"},
        {"tekken3",      "Tekken 3 (TET1-VER.E)"},
        {"tekken3a",     "Tekken 3 (World, TET2/VER.A)"},
        {"tekken3b",     "Tekken 3 (World, TET2/VER.B)"},
        {"tekken3c",     "Tekken 3 (World, TET2/VER.C)"},
        {"tekken3d",     "Tekken 3 (World, TET2/VER.D)"},
        {"tekken3ja",    "Tekken 3 (Japan, TET1/VER.A)"},
        {"tekken3je1",   "Tekken 3 (Japan, TET1/VER.E1)"},
        {"tekken3ua",    "Tekken 3 (US, TET3/VER.A)"},
        {"tekken3ud",    "Tekken 3 (US, TET3/VER.D)"},
        {"tekken4",      "Tekken 4 (TEF3 Ver. C)"},
        {"tekken4a",     "Tekken 4 (TEF2 Ver. A)"},
        {"tekken4b",     "Tekken 4 (TEF1 Ver. A)"},
        {"tekken51",     "Tekken 5.1 (TE51 Ver. B)"},
        {"tekkena",      "Tekken (TE2-VER.B)"},
        {"tekkenac",     "Tekken (Asia, TE4/VER.C)"},
        {"tekkenb",      "Tekken (TE1-VER.B)"},
        {"tekkenbs",     "Tekken Battle Scratch"},
        {"tekkenc",      "Tekken (Japan, TE1/VER.B)"},
        {"tekkencw",     "Tekken Card World"},
        {"tekkenjb",     "Tekken (Japan, TE1/VER.B)"},
        {"tekkentt",     "Tekken Tag Tournament (TEG3-VER.B)"},
        {"tektagt",      "Tekken Tag Tournament (World, TEG2/VER.C1, set 1)"},
        {"tektagta",     "Tekken Tag Tournament (TEG3/VER.B)"},
        {"tektagtb",     "Tekken Tag Tournament (Japan, TEG1/VER.B)"},
        {"tektagtc",     "Tekken Tag Tournament (Japan, TEG1/VER.A3)"},
        {"tektagtc1",    "Tekken Tag Tournament (World, TEG2/VER.C1, set 2)"},
        {"tektagtjc1",   "Tekken Tag Tournament (Japan, TEG1/VER.C1)"},
        {"tektagtub",    "Tekken Tag Tournament (US, TEG3/VER.B)"},
        {"tektagtuc1",   "Tekken Tag Tournament (US, TEG3/VER.C1)"},
        {"teljan",       "Tel Jan"},
        {"telmahjn",     "Telephone Mahjong (Japan 890111)"},
        {"telpacfl",     "TelePachi Fever Lion (V1.0)"},
        {"tempall",      "Tempest All Levels"},
        {"temped",       "TempEd"},
        {"tempest",      "Tempest (rev 3)"},
        {"tempest1",     "Tempest (rev 1)"},
        {"tempest1r",    "Tempest (rev 1, Revised Hardware)"},
        {"tempest2",     "Tempest (rev 2)"},
        {"tempest3",     "Tempest (rev [Q])"},
        {"temptube",     "Tempest Tubes"},
        {"temptwst",     "Tempest Twisted"},
        {"tengai",       "Tengai - Sengoku Blade - Sengoku Ace Episode II"},
        {"tengaij",      "Sengoku Blade: Sengoku Ace Episode II (Japan) / Tengai (World)"},
        {"tenkai",       "Mahjong Tenkaigen"},
        {"tenkai2b",     "Mahjong Tenkaigen Part 2 (bootleg)"},
        {"tenkaibb",     "Mahjong Tenkaigen (bootleg b)"},
        {"tenkaicb",     "Mahjong Tenkaigen (bootleg c)"},
        {"tenkaid",      "Mahjong Tenkaigen (set 1)"},
        {"tenkaie",      "Mahjong Tenkaigen (set 2)"},
        {"tenkomor",     "Tenkomori Shooting (World, TKM2/VER.A1)"},
        {"tenkomorj",    "Tenkomori Shooting (Japan, TKM1/VER.A1)"},
        {"tenkomorja",   "Tenkomori Shooting (Japan, TKM1/VER.A1)"},
        {"tenspot",      "Ten Spot"},
        {"tenthdeg",     "Tenth Degree (prototype)"},
        {"tenup",        "Ten Up"},
        {"tenup3",       "Ten Up (compendium 3)"},
        {"teot",         "The Eye of Typhoon (Beta 7 Version)"},
        {"teplus2j",     "Tetris Plus 2 (Japan)"},
        {"terabrst",     "Teraburst (1998/07/17 ver UEL)"},
        {"terabrsta",    "Teraburst (1998/02/25 ver AAA)"},
        {"term2",        "Terminator 2 - Judgment Day (rev LA3 03-27-92)"},
        {"term2la1",     "Terminator 2 - Judgment Day (rev LA1 11-01-91)"},
        {"term2la2",     "Terminator 2 - Judgment Day (rev LA2 12-09-91)"},
        {"term2la3",     "Terminator 2 - Judgment Day (rev LA3 03/27/92)"},
        {"term2lg1",     "Terminator 2 - Judgment Day (German, rev LG1 11/04/91)"},
        {"term2pa2",     "Terminator 2 - Judgment Day (prototype, rev PA2 10/18/91)"},
        {"terracra",     "Terra Cresta (YM2203)"},
        {"terracrb",     "Terra Cresta (YM3526 set 2)"},
        {"terracre",     "Terra Cresta (YM3526 set 1)"},
        {"terracrea",    "Terra Cresta (YM3526 set 3)"},
        {"terracren",    "Terra Cresta (YM2203)"},
        {"terracreo",    "Terra Cresta (YM3526 set 2)"},
        {"terraf",       "Terra Force"},
        {"terrafa",      "Terra Force (set 2)"},
        {"terrafb",      "Terra Force (Japan, bootleg set 2)"},
        {"terrafj",      "Terra Force (Japan)"},
        {"terrafjb",     "Terra Force (Japan, bootleg with additional Z80)"},
        {"terrafu",      "Terra Force (US)"},
        {"terrafua",     "Terra Force (US, alternate sound)"},
        {"test240p",     "240p Test Suite (v1.0)"},
        {"tetkiwam",     "Tetris Kiwamemichi (Japan) (GDL-0020)"},
        {"tetrbx",       "Tetris / Bloxeed (Korean System 16 bootleg) (ISG Selection Master Type 2006)"},
        {"tetris",       "Tetris (Sega Set 1)"},
        {"tetris1",      "Tetris (set 1, Japan, System 16B) (FD1094 317-0091)"},
        {"tetris1d",     "Tetris (set 1, Japan, System 16B) (bootleg of FD1094 317-0091 set)"},
        {"tetris2",      "Tetris (set 2, Japan, System 16B) (FD1094 317-0092)"},
        {"tetris2d",     "Tetris (set 2, Japan, System 16B) (bootleg of FD1094 317-0092 set)"},
        {"tetris3",      "Tetris (set 3, Japan, System 16A) (FD1094 317-0093a)"},
        {"tetris3d",     "Tetris (set 3, Japan, System 16A) (bootleg of FD1094 317-0093a set)"},
        {"tetrisa",      "Tetris (Sega Set 2)"},
        {"tetrisbl",     "Tetris (Sega bootleg)"},
        {"tetrisd",      "Tetris (set 4, Japan, System 16A) (bootleg of FD1094 317-0093 set)"},
        {"tetriskr",     "Tetris (Korean bootleg of Mirrorsoft PC-XT Tetris)"},
        {"tetrisp",      "Tetris Plus"},
        {"tetrisp2",     "Tetris Plus 2 (World[Q])"},
        {"tetrisp2a",    "Tetris Plus 2 (World, V2.7)"},
        {"tetrisp2j",    "Tetris Plus 2 (Japan, V2.2)"},
        {"tetrisp2ja",   "Tetris Plus 2 (Japan, V2.1)"},
        {"tetrisse",     "Tetris (Japan, System E)"},
        {"tetrist",      "Tetris (Japan, B-System)"},
        {"tetrista",     "Tetris (Japan, Taito B-System, Master of Weapon Conversion Kit)"},
        {"tetristh",     "Tetris (Japan, rev 1, Taito H-System)"},
        {"tetrsark",     "Tetris (D.R. Korea, set 1, encrypted)"},
        {"tetrsark2",    "Tetris (D.R. Korea, set 2)"},
        {"tfrceac",      "ThunderForce AC"},
        {"tfrceacb",     "ThunderForce AC (bootleg)"},
        {"tfrceacj",     "ThunderForce AC (Japan)"},
        {"tfrceacjpb",   "Thunder Force AC (Japan, prototype, bootleg)"},
        {"tgm2",         "Tetris the Absolute The Grand Master 2"},
        {"tgm2p",        "Tetris the Absolute The Grand Master 2 Plus"},
        {"tgmj",         "Tetris The Grand Master (JAPAN 980710)"},
        {"tgtbal96",     "Target Ball '96"},
        {"tgtball",      "Target Ball (Nude)"},
        {"tgtballa",     "Target Ball"},
        {"tgtballn",     "Target Ball (with nudity)"},
        {"tgtpanic",     "Target Panic"},
        {"tharierj",     "Task Force Harrier (Japan)"},
        {"tharrier",     "Task Force Harrier"},
        {"tharrierb",    "Task Force Harrier (Lettering bootleg)"},
        {"tharrierj",    "Task Force Harrier (Japan)"},
        {"tharrieru",    "Task Force Harrier (US)"},
        {"thayers",      "Thayer's Quest (set 1)"},
        {"thayersa",     "Thayer's Quest (set 2)"},
        {"the26thz",     "The 26th Z (Japan, location test)"},
        {"thedeep",      "The Deep (Japan)"},
        {"theend",       "The End"},
        {"theends",      "The End (Stern)"},
        {"theendss",     "The End (SegaSA / Sonic)"},
        {"theglad",      "The Gladiator / Shenjian Fumo Lu / Shenjian Fengyun (M68k label V101) (ARM label V107, ROM 06/06/03 SHEN JIAN V107)"},
        {"theglad100",   "The Gladiator / Shenjian Fumo Lu / Shenjian Fengyun (M68k label V100) (ARM label V100, ROM 01/16/03 SHEN JIAN)"},
        {"theglad101",   "The Gladiator / Shenjian Fumo Lu / Shenjian Fengyun (M68k label V100) (ARM label V101, ROM 03/13/03 SHEN JIAN)"},
        {"theglad104",   "The Gladiator / Shenjian Fumo Lu / Shenjian Fengyun (M68k label V100) (ARM label V104, ROM 04/02/03 SHEN JIAN V104)"},
        {"theglada",     "The Gladiator (ver. 101)"},
        {"thegladpcb",   "Tougenkyou - Road of the Sword (M68k label V100) (ARM label V101, ROM 03/13/03 SHEN JIAN) (Japan, JAMMA PCB)"},
        {"thegladpcba",  "Tougenkyou - Road of the Sword (M68k label V100) (ARM label V100, ROM 02/25/03 SHEN JIAN) (Japan, JAMMA PCB)"},
        {"theglob",      "The Glob"},
        {"theglob2",     "The Glob (earlier)"},
        {"theglob3",     "The Glob (set 3)"},
        {"theglobme",    "The Glob (Pacman hardware, Magic Electronics Inc. license)"},
        {"theglobp",     "The Glob (Pac-Man hardware)"},
        {"theglobpa",    "The Glob (Pac-Man hardware, set 2)"},
        {"theglobpb",    "The Glob (Pac-Man hardware, bootleg)"},
        {"thegrid",      "The Grid (version 1.2)"},
        {"thegrida",     "The Grid (version 1.1)"},
        {"thehand",      "The Hand"},
        {"thehole",      "The Hole (bootleg of The Pit)"},
        {"thehustj",     "The Hustler (Japan version J)"},
        {"thehustl",     "The Hustler (Japan version M)"},
        {"thehustlj",    "The Hustler (Japan, program code J)"},
        {"themj",        "The Mah-jong (Japan)"},
        {"thepit",       "The Pit"},
        {"thepitb",      "The Pit (bootleg)"},
        {"thepitc",      "The Pit (Centuri)"},
        {"thepitj",      "The Pit (Japan)"},
        {"thepitm",      "The Pit (bootleg on Moon Quasar hardware)"},
        {"thepitu1",     "The Pit (US set 1)"},
        {"thepitu2",     "The Pit (US set 2)"},
        {"thepitu3",     "The Pit (US set 3)"},
        {"theroes",      "Thunder Heroes"},
        {"thetogyu",     "The Togyu (Japan)"},
        {"thief",        "Thief"},
        {"thndblst",     "Thunder Blaster (Japan)"},
        {"thnderxj",     "Thunder Cross (Japan)"},
        {"thndfoxj",     "Thunder Fox (Japan)"},
        {"thndfoxu",     "Thunder Fox (US)"},
        {"thndrbdj",     "Thunder Blade (Japan)"},
        {"thndrbld",     "Thunder Blade"},
        {"thndrbld1",    "Thunder Blade (deluxe/standing) (unprotected)"},
        {"thndrbldd",    "Thunder Blade (upright) (bootleg of FD1094 317-0056 set)"},
        {"thndrx2",      "Thunder Cross II (Japan)"},
        {"thndrx2a",     "Thunder Cross II (Asia)"},
        {"thndrx2j",     "Thunder Cross II (Japan)"},
        {"thndzone",     "Thunder Zone (World)"},
        {"thndzone4",    "Thunder Zone (World 4 Players)"},
        {"thndzonea",    "Thunder Zone (World)"},
        {"thndzonej",    "Thunder Zone (Japan)"},
        {"thoop",        "Thunder Hoop"},
        {"thoop2",       "TH Strikes Back"},
        {"thoop2a",      "TH Strikes Back (Non North America, Version 1.0, Checksum 020EB356)"},
        {"thrild2",      "Thrill Drive 2 (ver EBB)"},
        {"thrild2a",     "Thrill Drive 2 (ver AAA)"},
        {"thrild2c",     "Thrill Drive 2 (ver EAA)"},
        {"thrilld",      "Thrill Drive (JAE)"},
        {"thrilldb",     "Thrill Drive (JAB)"},
        {"thunderh",     "Operation Thunder Hurricane (ver EAA)"},
        {"thunderhu",    "Operation Thunder Hurricane (ver UAA)"},
        {"thunderj",     "ThunderJaws"},
        {"thunderja",    "ThunderJaws (rev 2)"},
        {"thunderl",     "Thunder and Lightning"},
        {"thunderla",    "Thunder & Lightning (set 2)"},
        {"thunderlbl",   "Thunder & Lightning (bootleg with Tetris sound, set 1)"},
        {"thunderlbl2",  "Thunder & Lightning (bootleg with Tetris sound, set 2)"},
        {"thunderx",     "Thunder Cross"},
        {"thunderxa",    "Thunder Cross (set 2)"},
        {"thunderxb",    "Thunder Cross (set 3)"},
        {"thunderxj",    "Thunder Cross (Japan)"},
        {"thundfox",     "Thunder Fox (World)"},
        {"thundfoxj",    "Thunder Fox (Japan, rev 1)"},
        {"thundfoxu",    "Thunder Fox (US, rev 1)"},
        {"thunt",        "Treasure Hunt"},
        {"thuntk",       "Puzzle & Action: BoMulEul Chajara (JUET 970125 V2.00K)"},
        {"tickee",       "Tickee Tickats"},
        {"tictac",       "Tic Tac Trivia (6221-23, U5-0C, 07/07/86)"},
        {"tictaca",      "Tic Tac Trivia (6221-23, U5-0C, 02/11/86)"},
        {"tictacv",      "Tic Tac Trivia (6221-22, U5-0 Vertical)"},
        {"tigerh",       "Tiger Heli (US)"},
        {"tigerh2",      "Tiger Heli (Japan set 1)"},
        {"tigerhb1",     "Tiger Heli (bootleg set 1)"},
        {"tigerhb2",     "Tiger Heli (bootleg set 2)"},
        {"tigerhb3",     "Tiger-Heli (bootleg set 3)"},
        {"tigerhj",      "Tiger Heli (Japan set 2)"},
        {"tigeroad",     "Tiger Road (US)"},
        {"tigeroadb",    "Tiger Road (US bootleg)"},
        {"tigeroadb2",   "Tiger Road (US bootleg, set 2)"},
        {"tigeroadu",    "Tiger Road (US, Romstar license)"},
        {"timber",       "Timber"},
        {"timecris",     "Time Crisis (World, TS2 Ver.B)"},
        {"timecrisa",    "Time Crisis (World, TS2 Ver.A)"},
        {"timecrs2",     "Time Crisis 2 (TSS3 Ver. B)"},
        {"timecrs2b",    "Time Crisis 2 (TSS2 Ver. B)"},
        {"timecrs2c",    "Time Crisis 2 (TSS4 Ver. A)"},
        {"timecrs3",     "Time Crisis 3 (TST1)"},
        {"timecrsa",     "Time Crisis (Rev. TS2 Ver.A)"},
        {"timefgtr",     "Time Fighter (Time Pilot conversion on Galaxian hardware)"},
        {"timek131",     "Time Killers (v1.31)"},
        {"timekill",     "Time Killers (v1.32)"},
        {"timekill100",  "Time Killers (v1.00)"},
        {"timekill120",  "Time Killers (v1.20, alternate ROM board)"},
        {"timekill121",  "Time Killers (v1.21)"},
        {"timekill121a", "Time Killers (v1.21, alternate ROM board)"},
        {"timekill131",  "Time Killers (v1.31)"},
        {"timekill132i", "Time Killers (v1.32I)"},
        {"timelimt",     "Time Limit"},
        {"timemchn",     "Time Machine (v2.0)"},
        {"timeplt",      "Time Pilot"},
        {"timeplta",     "Time Pilot (Atari)"},
        {"timepltc",     "Time Pilot (Centuri)"},
        {"timescan",     "Time Scanner (set 2, System 16B)"},
        {"timescan1",    "Time Scanner (set 1, System 16A, FD1089B 317-0024)"},
        {"timescan3",    "Time Scanner (set 3, Japan, System 16B) (FD1089B 317-0024)"},
        {"timesol1",     "Time Soldiers (US Rev 1)"},
        {"timesold",     "Time Soldiers (US Rev 3)"},
        {"timesold1",    "Time Soldiers (US Rev 1)"},
        {"timesup",      "Time's UP!"},
        {"timesupd",     "Time's UP! (Demo)"},
        {"timetrv",      "Time Traveler"},
        {"timetrv2",     "Time Traveler (Japan)"},
        {"timetunl",     "Time Tunnel"},
        {"timscanr",     "Time Scanner"},
        {"tinklpit",     "Tinkle Pit (Japan)"},
        {"tinstar",      "The Tin Star"},
        {"tinstar2",     "The Tin Star (set 2)"},
        {"tinstara",     "The Tin Star (TS, 5 PCB version)"},
        {"tinv2650",     "The Invaders"},
        {"tiptop",       "Tip Top (3 board stack)"},
        {"tisland",      "Treasure Island"},
        {"titanpac",     "Titan (hack of Pac-Man)"},
        {"titlef",       "Title Fight (World)"},
        {"titlefj",      "Title Fight (Japan)"},
        {"titlefu",      "Title Fight (US)"},
        {"tjsb",         "Mahjong Tian Jiang Shen Bing"},
        {"tjumpman",     "Tobikose! Jumpman"},
        {"tkdensha",     "Toukidenshou - Angel Eyes (VER. 960427)"},
        {"tkdensho",     "Toukidenshou - Angel Eyes (VER. 960614)"},
        {"tkdenshoa",    "Toukidenshou - Angel Eyes (VER. 960427)"},
        {"tkmmpzdm",     "Tokimeki Memorial Taisen Puzzle-dama (ver JAB)"},
        {"tknight",      "Tecmo Knight"},
        {"tkoboxng",     "Vs. TKO Boxing"},
        {"tm",           "Touchmaster (v3.00 Euro)"},
        {"tm2k",         "Touchmaster 2000 Plus (v4.63 Standard)"},
        {"tm2ka",        "Touchmaster 2000 (v4.02 Standard)"},
        {"tm2kb",        "Touchmaster 2000 (v4.00 Standard)"},
        {"tm2kspeval",   "Touchmaster 2000 (v4.XX3 Spanish Evaluation)"},
        {"tm3k",         "Touchmaster 3000 (v5.02 Standard)"},
        {"tm3ka",        "Touchmaster 3000 (v5.01 Standard)"},
        {"tm3keval",     "Touchmaster 3000 (v5.XX Standard AMOA Evaluation)"},
        {"tm3ksp",       "Touchmaster 3000 (v5.02 Spanish)"},
        {"tm4k",         "Touchmaster 4000 (v6.03 Standard)"},
        {"tm4ka",        "Touchmaster 4000 (v6.02 Standard)"},
        {"tm4kb",        "Touchmaster 4000 (v6.01 Standard)"},
        {"tm4kca",       "Touchmaster 4000 (v6.02 California)"},
        {"tm4kmn",       "Touchmaster 4000 (v6.01 Minnesota)"},
        {"tm4knj",       "Touchmaster 4000 (v6.03 New Jersey)"},
        {"tm4kuk",       "Touchmaster 4000 (v6.02 England)"},
        {"tm5k",         "Touchmaster 5000 (v7.10 Standard)"},
        {"tm5ka",        "Touchmaster 5000 (v7.01 Standard)"},
        {"tm5kca",       "Touchmaster 5000 (v7.10 California)"},
        {"tm5kmn",       "Touchmaster 5000 (v7.10 Minnesota)"},
        {"tm5kuk",       "Touchmaster 5000 (v7.11 U.K.)"},
        {"tm7k",         "Touchmaster 7000 (v8.04 Standard)"},
        {"tm7ka",        "Touchmaster 7000 (v8.00 Standard)"},
        {"tm7kde",       "Touchmaster 7000 (v8.04 Germany)"},
        {"tm7keval",     "Touchmaster 7000 (v8.1X ASI Standard Evaluation)"},
        {"tm7kmn",       "Touchmaster 7000 (v8.04 Minnesota)"},
        {"tm7kmna",      "Touchmaster 7000 (v8.00 Minnesota)"},
        {"tm7knj",       "Touchmaster 7000 (v8.05 New Jersey)"},
        {"tm8k",         "Touchmaster 8000 (v9.04 Standard)"},
        {"tm8k902",      "Touchmaster 8000 (v9.02 Standard)"},
        {"tmdo",         "Touchmaster (v2.2-01 Standard)"},
        {"tmek",         "T-MEK"},
        {"tmek20",       "T-MEK (v2.0, prototype)"},
        {"tmek44",       "T-MEK (v4.4)"},
        {"tmek45",       "T-MEK (v4.5)"},
        {"tmek51p",      "T-MEK (v5.1, prototype)"},
        {"tmekprot",     "T-MEK (prototype)"},
        {"tmht",         "Teenage Mutant Hero Turtles (UK 4 Players)"},
        {"tmht22pe",     "Teenage Mutant Hero Turtles - Turtles in Time (2 Players ver EBA)"},
        {"tmht24pe",     "Teenage Mutant Hero Turtles - Turtles in Time (4 Players ver EAA)"},
        {"tmht2p",       "Teenage Mutant Hero Turtles (UK 2 Players)"},
        {"tmht2pa",      "Teenage Mutant Hero Turtles (UK 2 Players, version ?)"},
        {"tmhta",        "Teenage Mutant Hero Turtles (UK 4 Players, version S)"},
        {"tmhtb",        "Teenage Mutant Hero Turtles (UK 4 Players, version ?)"},
        {"tmmjprd",      "Tokimeki Mahjong Paradise - Dear My Love"},
        {"tmnt",         "Teenage Mutant Ninja Turtles (World 4 Players)"},
        {"tmnt2",        "Teenage Mutant Ninja Turtles - Turtles in Time (US 4 Players ver. UAA)"},
        {"tmnt22p",      "Teenage Mutant Ninja Turtles - Turtles in Time (US 2 Players ver. UDA)"},
        {"tmnt22pu",     "Teenage Mutant Ninja Turtles - Turtles in Time (2 Players ver UDA)"},
        {"tmnt24pu",     "Teenage Mutant Ninja Turtles - Turtles in Time (4 Players ver UEA)"},
        {"tmnt2a",       "Teenage Mutant Ninja Turtles - Turtles in Time (Asia 4 Players ver. ADA)"},
        {"tmnt2pj",      "Teenage Mutant Ninja Turtles (Japan 2 Players)"},
        {"tmnt2po",      "Teenage Mutant Ninja Turtles (Oceania 2 Players)"},
        {"tmnta",        "Teenage Mutant Ninja Turtles (Asia 4 Players, version ?)"},
        {"tmnti",        "Teenage Mutant Ninja Turtles (FMV Demo)"},
        {"tmntia",       "Teenage Mutant Ninja Turtles (FMV Demo, alt)"},
        {"tmntj",        "Teenage Mutant Ninja Turtles (Japan 4 Players)"},
        {"tmntmwb",      "Teenage Mutant Ninja Turtles - Mutant Warriors (SNES bootleg)"},
        {"tmntu",        "Teenage Mutant Ninja Turtles (US 4 Players)"},
        {"tmntua",       "Teenage Mutant Ninja Turtles (US 4 Players, version N)"},
        {"tmntub",       "Teenage Mutant Ninja Turtles (US 4 Players, version J)"},
        {"tmntuc",       "Teenage Mutant Ninja Turtles (US 4 Players, version H)"},
        {"tmntucbl",     "Teenage Mutant Ninja Turtles (bootleg, US 4 Players, version H)"},
        {"tmpdoki",      "Tokimeki Mahjong Paradise - Doki Doki Hen"},
        {"tndrcade",     "Thundercade - Twin Formation"},
        {"tndrcadej",    "Tokusyu Butai U.A.G. (Japan)"},
        {"tndrcadj",     "Tokusyu Butai U.A.G. (Japan)"},
        {"tnexspce",     "The Next Space"},
        {"tnextspc",     "The Next Space (set 1)"},
        {"tnextspc2",    "The Next Space (set 2)"},
        {"tnextspcj",    "The Next Space (Japan)"},
        {"tnk3",         "T.N.K. III (US)"},
        {"tnk3b",        "T.A.N.K. (joystick hack bootleg)"},
        {"tnk3j",        "T.A.N.K. (Japan)"},
        {"tnzs",         "The NewZealand Story (Japan, new version) (P0-043A PCB)"},
        {"tnzs2",        "The NewZealand Story (World, old version) (P0-041A PCB)"},
        {"tnzsb",        "The NewZealand Story (World, new version) (P0-043A PCB)"},
        {"tnzsj",        "The NewZealand Story (Japan, new version) (P0-043A PCB)"},
        {"tnzsjo",       "The NewZealand Story (Japan, old version) (P0-041A PCB)"},
        {"tnzso",        "The NewZealand Story (World, old version) (P0-041A PCB)"},
        {"tnzsoa",       "The NewZealand Story (World, unknown version) (P0-041A PCB)"},
        {"tnzsop",       "The NewZealand Story (World, prototype) (P0-041-1 PCB)"},
        {"tnzsuo",       "The NewZealand Story (US, old version) (P0-041A PCB)"},
        {"todruaga",     "Tower of Druaga (New Ver.)"},
        {"todruagao",    "The Tower of Druaga (Old Ver.)"},
        {"todruagas",    "The Tower of Druaga (Sidam)"},
        {"todruagb",     "Tower of Druaga (set 2)"},
        {"todruago",     "Tower of Druaga (Old Ver.)"},
        {"toffy",        "Toffy"},
        {"togenkyo",     "Tougenkyou (Japan 890418)"},
        {"toggle",       "Toggle (prototype)"},
        {"toki",         "Toki (World set 1)"},
        {"toki2",        "Toki (set 2)"},
        {"toki3",        "Toki (set 3)"},
        {"tokia",        "Toki (World set 2)"},
        {"tokib",        "Toki (bootleg)"},
        {"tokij",        "JuJu Densetsu (Japan)"},
        {"tokimbsj",     "Tokimeki Bishoujo [BET] (Japan)"},
        {"tokimosh",     "Tokimeki Memorial Oshiete Your Heart (GE755 JAA)"},
        {"tokimosp",     "Tokimeki Memorial Oshiete Your Heart Seal version PLUS (GE756 JAB)"},
        {"tokims",       "Toki (Modular System)"},
        {"tokio",        "Tokio / Scramble Formation (US)"},
        {"tokiob",       "Tokio / Scramble Formation (bootleg)"},
        {"tokioo",       "Tokio / Scramble Formation (older)"},
        {"tokiou",       "Tokio / Scramble Formation (US)"},
        {"tokip",        "Toki (US, prototype?)"},
        {"tokisens",     "Toki no Senshi - Chrono Soldier"},
        {"tokisensa",    "Toki no Senshi - Chrono Soldier (prototype?)"},
        {"tokiu",        "Toki (US)"},
        {"tokiua",       "Toki (US, set 2)"},
        {"tokkae",       "Taisen Tokkae-dama (ver JAA)"},
        {"tokyobus",     "Tokyo Bus Guide (Japan, Rev A)"},
        {"tokyocop",     "Tokyo Cop (Italy)"},
        {"tokyogal",     "Tokyo Gal Zukan (Japan)"},
        {"tokyowar",     "Tokyo Wars (World, TW2 Ver.A)"},
        {"tokyowarj",    "Tokyo Wars (Japan, TW1 Ver.A)"},
        {"tomagic",      "Tom Tom Magic"},
        {"tomahaw5",     "Tomahawk 777 (Revision 5)"},
        {"tomahawk",     "Tomahawk 777 (Revision 1)"},
        {"tomahawk1",    "Tomahawk 777 (rev 1)"},
        {"tomcat",       "TomCat (prototype)"},
        {"tomcatsw",     "TomCat (Star Wars hardware, prototype)"},
        {"tondemo",      "Tondemo Crisis (JAPAN)"},
        {"tontonb",      "Tonton [BET] (Japan)"},
        {"toobin",       "Toobin' (rev 3)"},
        {"toobin1",      "Toobin' (rev 1)"},
        {"toobin2",      "Toobin' (rev 2)"},
        {"toobin2e",     "Toobin' (Europe, rev 2)"},
        {"toobine",      "Toobin' (Europe, rev 3)"},
        {"toobing",      "Toobin' (German, rev 3)"},
        {"toobinp",      "Toobin' (Prototype)"},
        {"topbladv",     "Top Blade V"},
        {"topdrive",     "Top Driving (version 1.1)"},
        {"topgun",       "Vs. Top Gun"},
        {"topgunbl",     "Top Gunner (bootleg)"},
        {"topgunnr",     "Top Gunner (Exidy)"},
        {"topgunr",      "Top Gunner (US)"},
        {"tophuntr",     "Top Hunter - Roddy and Cathy"},
        {"tophuntrh",    "Top Hunter - Roddy & Cathy (NGH-046)"},
        {"topland",      "Top Landing (World)"},
        {"toplandj",     "Top Landing (Japan)"},
        {"toppyrap",     "Toppy & Rappy"},
        {"topracer",     "Top Racer"},
        {"topracera",    "Top Racer (with MB8841 + MB8842, 1983)"},
        {"topracern",    "Top Racer (no MB8841 + MB8842)"},
        {"toprollr",     "Top Roller"},
        {"topsecex",     "Top Secret (Exidy) (version 1.0)"},
        {"topsecrt",     "Top Secret (Japan)"},
        {"topsecrt2",    "Top Secret (Japan, revision B)"},
        {"topshoot",     "Top Shooter"},
        {"topskatr",     "Top Skater (Export, Revision A)"},
        {"topskatrj",    "Top Skater (Japan)"},
        {"topskatru",    "Top Skater (USA, Revision A)"},
        {"topskatruo",   "Top Skater (USA)"},
        {"topspedu",     "Top Speed (US)"},
        {"topspeed",     "Top Speed (World)"},
        {"topspeedu",    "Top Speed (US)"},
        {"toramich",     "Tora-he no Michi (Japan)"},
        {"toratora",     "Tora Tora"},
        {"toratorab",    "Tora Tora (set 2)"},
        {"toride2g",     "Toride II Adauchi Gaiden"},
        {"toride2gg",    "Toride II Adauchi Gaiden (German)"},
        {"toride2gk",    "Toride II Bok Su Oi Jeon Adauchi Gaiden (Korea)"},
        {"toride2j",     "Toride II (Japan)"},
        {"tornado1",     "Tornado (bootleg of Defender, set 1)"},
        {"tornado2",     "Tornado (bootleg set 2)"},
        {"tornbase",     "Tornado Baseball"},
        {"torus",        "Torus"},
        {"toryumon",     "Toryumon"},
        {"toryumondx",   "Toryumon DX"},
        {"totc",         "Thrash Rally / Touge Densetsu - Saisoku Battle"},
        {"totcarn",      "Total Carnage (rev LA1 03-10-92)"},
        {"totcarnp",     "Total Carnage (prototype, rev 1.0 01-25-92)"},
        {"totcarnp1",    "Total Carnage (prototype, proto v 1.0 01/25/92)"},
        {"totcarnp2",    "Total Carnage (prototype, proto v 2.0 02/10/92)"},
        {"totd",         "The Typing of the Dead (Rev A)"},
        {"totdo",        "The Typing of the Dead"},
        {"totlvice",     "Total Vice (ver EBA)"},
        {"totlvicj",     "Total Vice (ver JAD)"},
        {"totmejan",     "Tottemo E Jong"},
        {"toto",         "Come Back Toto"},
        {"toucheme",     "Touche Me (set 1)"},
        {"touchemea",    "Touche Me (set 2, harder)"},
        {"touchgo",      "Touch and Go"},
        {"touchgoe",     "Touch and Go (earlier revision)"},
        {"touchgok",     "Touch and Go (Korea, unprotected)"},
        {"touchgon",     "Touch and Go (Non North America)"},
        {"toukon3",      "Shin Nihon Pro Wrestling Toukon Retsuden 3 Arcade Edition (Japan, TR1/VER.A)"},
        {"toukon4",      "Shin Nihon Pro Wrestling Toukon Retsuden 4 Arcade Edition (Japan, TRF1 Ver.A)"},
        {"tourtab2",     "Tournament Table (set 2)"},
        {"tourtabl",     "Tournament Table (set 1)"},
        {"toutrun",      "Turbo Out Run (Out Run upgrade) (bootleg of FD1094 317-0118 set)"},
        {"toutrun1",     "Turbo Out Run (deluxe cockpit) (FD1094 317-0109)"},
        {"toutrun2",     "Turbo Out Run (cockpit) (FD1094 317-0106)"},
        {"toutrun2d",    "Turbo Out Run (cockpit) (bootleg of FD1094 317-0106 set)"},
        {"toutrun3",     "Turbo Out Run (cockpit) (bootleg of FD1094 317-0107 set)"},
        {"toutrun3d",    "Turbo Out Run (cockpit) (bootleg of FD1094 317-0107 set)"},
        {"toutrund",     "Turbo Out Run (Out Run upgrade) (bootleg of FD1094 317-0118 set)"},
        {"toutrunj",     "Turbo Out Run (Japan, Out Run upgrade) (FD1094 317-0117)"},
        {"toutrunj1",    "Turbo Out Run (Japan, cockpit) (FD1094 317-0101)"},
        {"toutrunj1d",   "Turbo Out Run (Japan, cockpit) (bootleg of FD1094 317-0101 set)"},
        {"toutrunjd",    "Turbo Out Run (Japan, Out Run upgrade) (bootleg of FD1094 317-0117 set)"},
        {"toyfight",     "Toy Fighter"},
        {"toyland",      "Toy Land Adventure"},
        {"toypop",       "Toypop"},
        {"tp2m32",       "Tetris Plus 2 (MegaSystem 32 Version)"},
        {"tp84",         "Time Pilot '84 (set 1)"},
        {"tp84a",        "Time Pilot '84 (set 2)"},
        {"tp84b",        "Time Pilot '84 (set 3)"},
        {"tpgolf",       "Top Player's Golf"},
        {"tps",          "TPS"},
        {"trackflc",     "Track and Field (Centuri)"},
        {"trackfld",     "Track and Field"},
        {"trackfldc",    "Track & Field (Centuri)"},
        {"trackfldnz",   "Track & Field (NZ bootleg?)"},
        {"trackfldu",    "Track & Field (Centuri, unencrypted)"},
        {"trailblz",     "Trail Blazer"},
        {"trally",       "Thrash Rally"},
        {"tranqgun",     "Tranquilizer Gun"},
        {"transfrm",     "Transformer"},
        {"travrusa",     "Traverse USA - Zippy Race"},
        {"travrusab",    "Traverse USA (bootleg, set 1)"},
        {"travrusab2",   "Traverse USA (bootleg, set 2)"},
        {"trckydoc",     "Tricky Doc"},
        {"trckydoca",    "Tricky Doc (set 2)"},
        {"treahunt",     "Treasure Hunt (Japan[Q])"},
        {"trebltop",     "Treble Top (39-360-070)"},
        {"trgheart",     "Trigger Heart Exelica Ver.A (Japan) (GDL-0036A)"},
        {"trghearto",    "Trigger Heart Exelica (Japan) (GDL-0036)"},
        {"tricktrp",     "Trick Trap (World[Q])"},
        {"trigon",       "Trigon (Japan)"},
        {"trikitri",     "Triki Triki (bootleg of Lover Boy)"},
        {"triothep",     "Trio The Punch - Never Forget Me... (Japan)"},
        {"triothepj",    "Trio The Punch - Never Forget Me... (Japan)"},
        {"triplep",      "Triple Punch"},
        {"triplepa",     "Triple Punch (set 2)"},
        {"triplew1",     "Mahjong Triple Wars (Japan)"},
        {"triplew2",     "Mahjong Triple Wars 2 (Japan)"},
        {"triplfun",     "Triple Fun"},
        {"triplfunk",    "Sum-eoitneun Deongdalireul Chat-ara!"},
        {"triplhnt",     "Triple Hunt"},
        {"tripool",      "Tri-Pool (Casino Tech)"},
        {"tripoola",     "Tri-Pool (Costal Games)"},
        {"trisport",     "Tri-Sports"},
        {"trivia12",     "Trivial Pursuit (Genus I) (set 2)"},
        {"triviabb",     "Trivial Pursuit (Baby Boomer Edition)"},
        {"triviaes",     "Trivial Pursuit (Volumen III, Spanish, Maibesa license)"},
        {"triviaes2",    "Trivial Pursuit (Volumen II, Spanish, Maibesa license)"},
        {"triviag1",     "Trivial Pursuit (Genus I)"},
        {"triviag1a",    "Trivial Pursuit (Think Tank - Genus Edition) (12/14/84)"},
        {"triviag2",     "Trivial Pursuit (Genus II)"},
        {"trivialp",     "Trivial Pursuit (New Edition) (prod. 1D)"},
        {"trivialpd",    "Trivial Pursuit (New Edition) (prod. 1D) (Protocol)"},
        {"trivialpo",    "Trivial Pursuit"},
        {"triviasp",     "Trivial Pursuit (All Star Sports Edition)"},
        {"triviayp",     "Trivial Pursuit (Young Players Edition)"},
        {"trivquiz",     "Triv Quiz"},
        {"trivrus",      "Trivia R Us (v1.07)"},
        {"trizeal",      "Trizeal (Japan) (GDL-0026)"},
        {"troangel",     "Tropical Angel"},
        {"trog",         "Trog (rev LA4 03-11-91)"},
        {"trog3",        "Trog (rev LA3 02-14-91)"},
        {"trog3a",       "Trog (rev LA3 2/10/91)"},
        {"trog4",        "Trog (rev LA4 3/11/91)"},
        {"trogp",        "Trog (prototype, rev 4.00 07-27-90)"},
        {"trogpa4",      "Trog (prototype, rev 4.00 7/27/90)"},
        {"trogpa5",      "Trog (prototype, rev PA5-PAC 8/28/90)"},
        {"trogpa6",      "Trog (rev PA6-PAC 09-09-90)"},
        {"trojan",       "Trojan (US)"},
        {"trojana",      "Trojan (US set 2)"},
        {"trojanb",      "Trojan (bootleg)"},
        {"trojanj",      "Tatakai no Banka (Japan)"},
        {"trojanjo",     "Tatakai no Banka (Japan, old ver.)"},
        {"trojanlt",     "Trojan (location test)"},
        {"trojanr",      "Trojan (Romstar)"},
        {"trojanra",     "Trojan (Romstar, set 2)"},
        {"tron",         "Tron (set 1)"},
        {"tron2",        "Tron (set 2)"},
        {"tron3",        "Tron (6/17)"},
        {"tron4",        "Tron (6/15)"},
        {"tron5",        "Tron (5/12)"},
        {"tronfp",       "Tron (freeplay)"},
        {"tronger",      "Tron (Germany)"},
        {"troopy",       "Troopy (bootleg of Mr. Kougar)"},
        {"trophyh",      "Trophy Hunting - Bear & Moose V1.0"},
        {"trophyht",     "Trophy Hunting - Bear & Moose V1.00 (location test)"},
        {"trstar",       "Top Ranking Stars (World new version)"},
        {"trstarj",      "Top Ranking Stars (Japan new version)"},
        {"trstaro",      "Top Ranking Stars (World old version)"},
        {"trstaroj",     "Top Ranking Stars (Japan old version)"},
        {"truckk",       "Truck Kyosokyoku (Japan, TKK2/VER.A)"},
        {"truco",        "Truco-Tron"},
        {"truxton",      "Truxton - Tatsujin"},
        {"truxton2",     "Truxton II - Tatsujin II - Tatsujin Oh (Japan)"},
        {"trvchlng",     "Trivia Challenge"},
        {"trvgns",       "Trivia Genius"},
        {"trvhang",      "Trivia Hangup (question set 1)"},
        {"trvhanga",     "Trivia Hangup (Question Set 2)"},
        {"trvmadns",     "Trivia Madness - Series A Question set"},
        {"trvmadnsa",    "Trivia Madness - Series B Question set"},
        {"trvmstr",      "Trivia Master (set 1)"},
        {"trvmstra",     "Trivia Master (set 2)"},
        {"trvmstrb",     "Trivia Master (set 3)"},
        {"trvmstrc",     "Trivia Master (set 4)"},
        {"trvmstrd",     "Trivia Master (set 5)"},
        {"trvquest",     "Trivia Quest"},
        {"trvwz",        "Trivia ? Whiz (6221-00)"},
        {"trvwz2",       "Trivia ? Whiz (6221-05, Edition 2)"},
        {"trvwz2a",      "Trivia ? Whiz (6221-05, Edition 2 Alt Sex trivia)"},
        {"trvwz3",       "Trivia ? Whiz (6221-05, U5-0D, Edition 3)"},
        {"trvwz3a",      "Trivia ? Whiz (6221-05, U5-0C, Edition 3)"},
        {"trvwz3b",      "Trivia ? Whiz (6221-05, Edition 3 Sex trivia III)"},
        {"trvwz3h",      "Trivia ? Whiz (Edition 3 - Horizontal) (set 1)"},
        {"trvwz3ha",     "Trivia ? Whiz (Edition 3 - Horizontal) (set 2)"},
        {"trvwz3v",      "Trivia ? Whiz (6221-04, U5-0E, Edition 3 Vertical)"},
        {"trvwz4",       "Trivia ? Whiz (6221-10, U5-0A, Edition 4)"},
        {"trvwz4a",      "Trivia ? Whiz (Edition 4) (question set 2)"},
        {"trvwz4v",      "Trivia ? Whiz (6221-13, U5-0B, Edition 4 Vertical)"},
        {"trvwz4va",     "Trivia ? Whiz (6221-13, U5-0B, Edition 4 Vertical Alt Sex trivia)"},
        {"trvwza",       "Trivia ? Whiz (6221-00, with Sex trivia)"},
        {"trvwzb",       "Trivia ? Whiz (6221-00, Alt Gen trivia)"},
        {"trvwzh",       "Trivia ? Whiz (Horizontal) (question set 1)"},
        {"trvwzha",      "Trivia ? Whiz (Horizontal) (question set 2)"},
        {"trvwzhb",      "Trivia ? Whiz (Horizontal) (question set 3)"},
        {"trvwzv",       "Trivia ? Whiz (6221-02, Vertical)"},
        {"trvwzva",      "Trivia ? Whiz (Vertical) (question set 2)"},
        {"tryout",       "Pro Baseball Skill Tryout (Japan)"},
        {"ts2",          "Battle Arena Toshinden 2 (USA 951124)"},
        {"ts2j",         "Battle Arena Toshinden 2 (JAPAN 951124)"},
        {"tsamura2",     "Samurai Nihon-ichi (set 2)"},
        {"tsamurai",     "Samurai Nihon-ichi (set 1)"},
        {"tsamurai2",    "Samurai Nihon-Ichi (set 2)"},
        {"tsamuraia",    "Samurai Nihon-Ichi"},
        {"tsamuraih",    "Samurai Nihon-Ichi (bootleg, harder)"},
        {"tshingen",     "Takeda Shingen (Japan, Japanese)"},
        {"tshingena",    "Takeda Shingen (Japan, Japanese)"},
        {"tshingna",     "Shingen Samurai-Fighter (Japan, English)"},
        {"tshoot",       "Turkey Shoot"},
        {"tst_galx",     "Galaxian Test ROM"},
        {"tst_invd",     "Space Invaders Test ROM"},
        {"tstrike",      "Thunder Strike"},
        {"tstrikea",     "Thunder Strike (set 2, older)"},
        {"tsukande",     "Tsukande Toru Chicchi"},
        {"tsupenta",     "Tsurikko Penta"},
        {"tsurugi",      "Tsurugi (ver EAB)"},
        {"tsurugij",     "Tsurugi (ver JAC)"},
        {"ttchamp",      "Table Tennis Champions"},
        {"ttchampa",     "Table Tennis Champions (Palencia Elektronik license)"},
        {"ttfitter",     "T.T Fitter (Japan)"},
        {"ttmahjng",     "Mahjong"},
        {"tturf",        "Tough Turf (Japan)"},
        {"tturfbl",      "Tough Turf (bootleg)"},
        {"tturfu",       "Tough Turf (US)"},
        {"tubeit",       "Tube-It"},
        {"tubep",        "Tube Panic"},
        {"tubepb",       "Tube Panic (bootleg)"},
        {"tugboat",      "Tugboat"},
        {"tumbleb",      "Tumble Pop (bootleg)"},
        {"tumbleb2",     "Tumble Pop (bootleg with PIC)"},
        {"tumblep",      "Tumble Pop (World)"},
        {"tumblep2",     "Tumble Pop (bootleg set 2)"},
        {"tumblepb",     "Tumble Pop (bootleg set 1)"},
        {"tumblepj",     "Tumble Pop (Japan)"},
        {"tunhunt",      "Tunnel Hunt"},
        {"tunhuntc",     "Tunnel Hunt (Centuri)"},
        {"turbo",        "Turbo"},
        {"turboa",       "Turbo (encrypted set 1)"},
        {"turbob",       "Turbo (encrypted set 2)"},
        {"turbobl",      "Indianapolis (bootleg of Turbo)"},
        {"turboc",       "Turbo (encrypted, program 1363-1365 rev B)"},
        {"turbod",       "Turbo (encrypted, program 1363-1365 rev A)"},
        {"turboe",       "Turbo (encrypted, program 1363-1365)"},
        {"turbofrc",     "Turbo Force"},
        {"turbofrco",    "Turbo Force (World, set 2)"},
        {"turbofrcu",    "Turbo Force (US, set 1)"},
        {"turbofrcua",   "Turbo Force (US, set 2)"},
        {"turbosub",     "Turbo Sub (prototype rev. TSCA)"},
        {"turbosub6",    "Turbo Sub (prototype rev. TSC6)"},
        {"turbosub7",    "Turbo Sub (prototype rev. TSC7)"},
        {"turbosubb8",   "Turbo Sub (prototype rev. TSB8)"},
        {"turbosubc5",   "Turbo Sub (prototype rev. TSC5)"},
        {"turbosubc5s",  "Turbo Sub (prototype rev. TSC5*)"},
        {"turbosubc6",   "Turbo Sub (prototype rev. TSC6)"},
        {"turbosubc7",   "Turbo Sub (prototype rev. TSC7)"},
        {"turbosubc8",   "Turbo Sub (prototype rev. TSC8)"},
        {"turbotag",     "Turbo Tag (prototype)"},
        {"turfmast",     "Neo Turf Masters / Big Tournament Golf"},
        {"turkhunt",     "Turkey Hunting USA V1.0"},
        {"turnover",     "Turnover (v2.3)"},
        {"turpin",       "Turpin"},
        {"turpins",      "Turpin (bootleg on Super Cobra hardware)"},
        {"turrett",      "Turret Tower"},
        {"turtles",      "Turtles"},
        {"turtship",     "Turtle Ship"},
        {"turtshipj",    "Turtle Ship (Japan)"},
        {"turtshipk",    "Turtle Ship (Korea)"},
        {"turtshipkn",   "Turtle Ship (Korea, 88/9)"},
        {"turtshipko",   "Turtle Ship (Korea, older)"},
        {"tutankhm",     "Tutankham"},
        {"tutankhms",    "Tutankham (Stern Electronics)"},
        {"tutankst",     "Tutankham (Stern)"},
        {"tutstomb",     "Tut's Tomb"},
        {"twcup90",      "Tecmo World Cup '90 (World set 1)"},
        {"twcup90a",     "Tecmo World Cup '90 (Europe set 1)"},
        {"twcup90b",     "Tecmo World Cup '90 (Europe set 2)"},
        {"twcup90b1",    "Euro League (Italian hack of Tecmo World Cup '90, set 1)"},
        {"twcup90b2",    "Worldcup '90 (hack)"},
        {"twcup90b3",    "Euro League (Italian hack of Tecmo World Cup '90, set 3)"},
        {"twcup90ba",    "Euro League (Italian hack of Tecmo World Cup '90, set 2)"},
        {"twcup90bb",    "World Cup '90 (European hack, different title)"},
        {"twcup90c",     "Tecmo World Cup '90 (Europe set 3)"},
        {"twcup90t",     "Tecmo World Cup '90 (trackball set 1)"},
        {"twcup98",      "Tecmo World Cup '98"},
        {"twinactn",     "Twin Action"},
        {"twinadv",      "Twin Adventure (World)"},
        {"twinadvk",     "Twin Adventure (Korea)"},
        {"twinbee",      "TwinBee"},
        {"twinbeeb",     "TwinBee (Bubble System)"},
        {"twinbrat",     "Twin Brats (set 1)"},
        {"twinbrata",    "Twin Brats (set 2)"},
        {"twinbratb",    "Twin Brats (set 3)"},
        {"twincobr",     "Twin Cobra (World)"},
        {"twincobru",    "Twin Cobra (US)"},
        {"twincobu",     "Twin Cobra (US)"},
        {"twineag2",     "Twin Eagle II - The Rescue Mission"},
        {"twineagl",     "Twin Eagle - Revenge Joe's Brother"},
        {"twinfalc",     "Twin Falcons"},
        {"twinhawk",     "Twin Hawk (World)"},
        {"twinhawku",    "Twin Hawk (US)"},
        {"twinhwku",     "Twin Hawk (US)"},
        {"twinkle",      "Twinkle"},
        {"twinklea",     "Twinkle (set 2)"},
        {"twinqix",      "Twin Qix (US Prototype)"},
        {"twins",        "Twins (newer)"},
        {"twinsa",       "Twins (older)"},
        {"twinsed1",     "Twins (Electronic Devices license, older)"},
        {"twinsed2",     "Twins (Electronic Devices license, newer)"},
        {"twinspri",     "Twinkle Star Sprites"},
        {"twinsqua",     "Twin Squash"},
        {"twocrude",     "Two Crude (US)"},
        {"twocrudea",    "Two Crude (US FT version)"},
        {"twotiger",     "Two Tigers"},
        {"twotigerc",    "Two Tigers (Tron conversion)"},
        {"twotigra",     "Two Tigers (dedicated)"},
        {"twrldc94",     "Tecmo World Cup '94 (set 1)"},
        {"twrldc94a",    "Tecmo World Cup '94 (set 2)"},
        {"twrshaft",     "Tower & Shaft"},
        {"tws96",        "Tecmo World Soccer '96"},
        {"twsoc96",      "Tecmo World Soccer '96"},
        {"tx1",          "TX-1 (World)"},
        {"tx1a",         "TX-1 (Atari/Namco/Taito license)"},
        {"tx1jb",        "TX-1 (Japan rev. B)"},
        {"tx1jc",        "TX-1 (Japan rev. C)"},
        {"tylz",         "Tylz (prototype)"},
        {"typhoon",      "Typhoon"},
};

const size_t lookup_t_count = A_SIZE(lookup_t_table);

const char *lookup_t(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strcmp(lookup_t_table[i].name, name) == 0) {
            return lookup_t_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_t(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strstr(lookup_t_table[i].value, value)) {
            return lookup_t_table[i].name;
        }
    }
    return NULL;
}

void lookup_t_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strcasestr(lookup_t_table[i].name, term))
            emit(lookup_t_table[i].name, lookup_t_table[i].value, udata);
    }
}

void r_lookup_t_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strcasestr(lookup_t_table[i].value, term))
            emit(lookup_t_table[i].name, lookup_t_table[i].value, udata);
    }
}
