#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"dacholer",      "Dacholer"},
        {"dadandrn",      "Kyukyoku Sentai Dadandarn (Japan ver JAA)"},
        {"dai2kaku",      "Dai-Dai-Kakumei (Japan)"},
        {"daikaiju",      "Daikaiju no Gyakushu"},
        {"daimakai",      "Dai Makai-Mura (Japan)"},
        {"daimakaib",     "Dai Makai-Mura (bootleg, Japan)"},
        {"daimakair",     "Daimakaimura (Japan Resale Ver.)"},
        {"daimyojn",      "Mahjong Daimyojin (Japan, T017-PB-00)"},
        {"daioh",         "Daioh"},
        {"daioha",        "Daioh (earlier)"},
        {"daiohc",        "Daioh (93111A PCB conversion)"},
        {"daiohp",        "Daioh (prototype)"},
        {"daiohp2",       "Daioh (prototype, earlier)"},
        {"daireika",      "Mahjong Daireikai"},
        {"dairesya",      "Dai Ressya Goutou (Japan)"},
        {"daisenpu",      "Daisenpu (Japan)"},
        {"daiskiss",      "Daisu-Kiss (ver JAA)"},
        {"daisyari",      "Daisyarin [BET] (Japan)"},
        {"daitoa",        "Daitoride (YMF278B version)"},
        {"daitorid",      "Daitoride"},
        {"daitorida",     "Daitoride (YMF278B version)"},
        {"daiyogen",      "Mahjong Daiyogen (Japan)"},
        {"dakkochn",      "DakkoChan Jansoh"},
        {"dambustr",      "Dambusters (US, set 1)"},
        {"dambustra",     "Dambusters (US, set 2)"},
        {"dambustruk",    "Dambusters (UK)"},
        {"danceyes",      "Dancing Eyes (DC1-VER.A)"},
        {"danceyesj",     "Dancing Eyes (Japan, DC1/VER.A)"},
        {"danceyesu",     "Dancing Eyes (US, DC3/VER.C)"},
        {"danchih",       "Danchi de Hanafuda"},
        {"danchiq",       "Danchi de Quiz Okusan Yontaku Desuyo! (J 001128 V1.200)"},
        {"dangar",        "Dangar - Ufo Robo (12-1-1986)"},
        {"dangar2",       "Dangar - Ufo Robo (9-26-1986)"},
        {"dangara",       "Ufo Robo Dangar (12/1/1986)"},
        {"dangarb",       "Dangar - Ufo Robo (bootleg)"},
        {"dangarbt",      "Ufo Robo Dangar (9/26/1986, bootleg set 2)"},
        {"dangarj",       "Ufo Robo Dangar (9/26/1986, Japan)"},
        {"dangcurv",      "Dangerous Curves"},
        {"dangerex",      "Danger Express (prototype)"},
        {"dangerz",       "Danger Zone"},
        {"dangerz0",      "Danger Zone (rev 0)"},
        {"dangseed",      "Dangerous Seed (Japan)"},
        {"dankuga",       "Dan-Ku-Ga (Prototype)"},
        {"daraku",        "Daraku Tenshi - The Fallen Angels"},
        {"darius",        "Darius (World)"},
        {"darius2",       "Darius II (Japan)"},
        {"darius2d",      "Darius II (dual screen) (Japan)"},
        {"darius2do",     "Darius II (dual screen) (Japan, Rev 1)"},
        {"dariuse",       "Darius (Extra) (Japan)"},
        {"dariusg",       "Darius Gaiden - Silver Hawk (World)"},
        {"dariusgj",      "Darius Gaiden - Silver Hawk (Japan)"},
        {"dariusgu",      "Darius Gaiden - Silver Hawk (US)"},
        {"dariusgx",      "Darius Gaiden - Silver Hawk (Extra Version) [Official Hack]"},
        {"dariusj",       "Darius (Japan)"},
        {"dariuso",       "Darius (Japan old version)"},
        {"dariusu",       "Darius (US, rev 2)"},
        {"darkadv",       "Dark Adventure"},
        {"darkedge",      "Dark Edge"},
        {"darkedgej",     "Dark Edge (Japan)"},
        {"darkhleg",      "Dark Horse Legend (GX706 VER. JAA)"},
        {"darkmist",      "The Lost Castle in Darkmist"},
        {"darkplnt",      "Dark Planet"},
        {"darksea1",      "Dark Seal (World revision 1)"},
        {"darkseaj",      "Dark Seal (Japan)"},
        {"darkseal",      "Dark Seal (World revision 3)"},
        {"darkseal1",     "Dark Seal (World revision 1)"},
        {"darkseal2",     "Dark Seal 2 (Japan v2.1)"},
        {"darksealj",     "Dark Seal (Japan revision 4)"},
        {"darksel2",      "Dark Seal 2 (Japan v2.1)"},
        {"darktowr",      "Dark Tower"},
        {"darkwar",       "Dark Warrior"},
        {"darthvdr",      "Darth Vader"},
        {"darwin",        "Darwin 4078 (Japan)"},
        {"dassaul4",      "Desert Assault (US 4 Players)"},
        {"dassault",      "Desert Assault (US)"},
        {"dassault4",     "Desert Assault (US 4 Players)"},
        {"dayto2pe",      "Daytona USA 2: Power Edition (Japan)"},
        {"daytona",       "Daytona USA (Revision A)"},
        {"daytona2",      "Daytona USA 2: Battle on the Edge (Japan, Revision A)"},
        {"daytona93",     "Daytona USA"},
        {"daytonagtx",    "Daytona USA (GTX 2004 Edition)"},
        {"daytonam",      "Daytona USA (To The MAXX)"},
        {"daytonas",      "Daytona USA (With Saturn Adverts)"},
        {"daytonase",     "Daytona USA Special Edition (Revision A)"},
        {"daytonat",      "Daytona USA (Turbo hack, set 1)"},
        {"daytonata",     "Daytona USA (Turbo hack, set 2)"},
        {"dazzler",       "Dazzler"},
        {"dbc",           "Da Ban Cheng (Hong Kong, V027H)"},
        {"dblaxle",       "Double Axle (US)"},
        {"dblaxleu",      "Double Axle (US)"},
        {"dblaxleul",     "Double Axle (US, Rev 1, Linkable)"},
        {"dbldyn",        "The Double Dynamites"},
        {"dbldynf",       "The Double Dynamites (US)"},
        {"dbldynj",       "The Double Dynamites (Japan, 13NOV89)"},
        {"dbldynu",       "The Double Dynamites (US, 13NOV89)"},
        {"dblewing",      "Double Wings"},
        {"dblewinga",     "Double Wings (set 2)"},
        {"dblewingb",     "Double Wings (Asia)"},
        {"dblplay",       "Super Baseball Double Play Home Run Derby"},
        {"dblpoint",      "Double Point"},
        {"dblpointd",     "Double Point (Dong Bang Electron, bootleg?)"},
        {"dbreed",        "Dragon Breed"},
        {"dbreedjm72",    "Dragon Breed (Japan, M72 hardware)"},
        {"dbreedm72",     "Dragon Breed (World, M72 hardware)"},
        {"dbz",           "Dragonball Z"},
        {"dbz2",          "Dragonball Z 2 Super Battle"},
        {"dbza",          "Dragon Ball Z (rev A)"},
        {"dbzvrvs",       "Dragon Ball Z V.R.V.S."},
        {"dcclub",        "Dynamic Country Club"},
        {"dcclubfd",      "Dynamic Country Club (US, Floppy Based, FD1094 317-0058-09d)"},
        {"dcclubj",       "Dynamic Country Club (Japan, ROM Based)"},
        {"dcon",          "D-Con"},
        {"dday",          "D-Day"},
        {"ddayc",         "D-Day (Centuri)"},
        {"ddaydoo",       "Chulgyeok D-Day (Korea)"},
        {"ddayjlc",       "D-Day (Jaleco set 1)"},
        {"ddayjlca",      "D-Day (Jaleco set 2)"},
        {"ddboy",         "Dam Dam Boy (on dedicated PCB)"},
        {"ddboya",        "Dam Dam Boy (on Tsukande Toru Chicchi PCB)"},
        {"ddcrew",        "DD Crew"},
        {"ddcrew1",       "D. D. Crew (World, 4 Players) (FD1094 317-0187)"},
        {"ddcrew1d",      "D. D. Crew (World, 4 Players) (bootleg of FD1094 317-0187 set)"},
        {"ddcrew2",       "D. D. Crew (World, 2 Players) (FD1094 317-0184)"},
        {"ddcrew2d",      "D. D. Crew (World, 2 Players) (bootleg of FD1094 317-0184 set)"},
        {"ddcrewd",       "D. D. Crew (World, 3 Players) (bootleg of FD1094 317-0190 set)"},
        {"ddcrewj",       "D. D. Crew (Japan, 4 Players) (FD1094 317-0185)"},
        {"ddcrewj2",      "D. D. Crew (Japan, 2 Players) (FD1094 317-0182)"},
        {"ddcrewj2d",     "D. D. Crew (Japan, 2 Players) (bootleg of FD1094 317-0182 set)"},
        {"ddcrewjd",      "D. D. Crew (Japan, 4 Players) (bootleg of FD1094 317-0185 set)"},
        {"ddcrewu",       "D. D. Crew (US, 4 Players) (FD1094 317-0186)"},
        {"ddcrewud",      "D. D. Crew (US, 4 Players) (bootleg of FD1094 317-0186 set)"},
        {"ddealer",       "Double Dealer"},
        {"ddenlovj",      "Don Den Lover Vol. 1 - Shiro Kuro Tsukeyo! (Japan)"},
        {"ddenlovr",      "Don Den Lover Vol. 1 (Hong Kong)"},
        {"ddenlovrb",     "Don Den Lover Vol. 1 - Heukbaeg-euro Jeonghaja (Korea, bootleg)"},
        {"ddenlovrk",     "Don Den Lover Vol. 1 - Heukbaeg-euro Jeonghaja (Korea)"},
        {"dderby",        "Death Derby"},
        {"ddonpach",      "DoDonPachi (International)"},
        {"ddonpacha",     "DoDonPachi (Arrange Ver. 1.1) (trap15, hack)"},
        {"ddonpachj",     "DoDonPachi (Japan, 1997 2/ 5 Master Ver.)"},
        {"ddonpchj",      "DoDonPachi (Japan)"},
        {"ddp2",          "DoDonPachi II - Bee Storm (World, ver. 102)"},
        {"ddp2100",       "DoDonPachi II - Bee Storm (World, ver. 100)"},
        {"ddp2100c",      "DoDonPachi - Feng Bao (China, ver. 100)"},
        {"ddp2100hk",     "DoDonPachi II - Fung Bou (Hong Kong, ver. 100)"},
        {"ddp2100j",      "DoDonPachi II (Japan, ver. 100)"},
        {"ddp2100k",      "DoDonPachi II - Bee Storm (Korea, ver. 100)"},
        {"ddp2100t",      "DoDonPachi - Feng Bao (Taiwan, ver. 100)"},
        {"ddp2101",       "DoDonPachi II - Bee Storm (World, ver. 101)"},
        {"ddp2101c",      "DoDonPachi - Feng Bao (China, ver. 101)"},
        {"ddp2101hk",     "DoDonPachi II - Fung Bou (Hong Kong, ver. 101)"},
        {"ddp2101j",      "DoDonPachi II (Japan, ver. 101)"},
        {"ddp2101k",      "DoDonPachi II - Bee Storm (Korea, ver. 101)"},
        {"ddp2101t",      "DoDonPachi - Feng Bao (Taiwan, ver. 101)"},
        {"ddp2a",         "Bee Storm - DoDonPachi II (ver. 102)"},
        {"ddp2c",         "DoDonPachi - Feng Bao (China, ver. 102)"},
        {"ddp2hk",        "DoDonPachi II - Fung Bou (Hong Kong, ver. 102)"},
        {"ddp2j",         "DoDonPachi II (Japan, ver. 102)"},
        {"ddp2k",         "DoDonPachi II - Bee Storm (Korea, ver. 102)"},
        {"ddp2t",         "DoDonPachi - Feng Bao (Taiwan, ver. 102)"},
        {"ddp3",          "DoDonPachi Dai-Ou-Jou"},
        {"ddp3a",         "DoDonPachi Dai-Ou-Jou (V100, second revision)"},
        {"ddp3b",         "DoDonPachi Dai-Ou-Jou (V100, first revision)"},
        {"ddp3blk",       "DoDonPachi Dai-Ou-Jou (Black Label)"},
        {"ddpdfk",        "DoDonPachi Dai-Fukkatsu Ver 1.5 (2008/06/23 MASTER VER 1.5)"},
        {"ddpdfk10",      "DoDonPachi Dai-Fukkatsu Ver 1.0 (2008/05/16 MASTER VER)"},
        {"ddpdoj",        "DoDonPachi Dai-Ou-Jou (Japan, 2002.04.05.Master Ver, 68k Label V101)"},
        {"ddpdoja",       "DoDonPachi Dai-Ou-Jou (Japan, 2002.04.05.Master Ver, 68k Label V100)"},
        {"ddpdojb",       "DoDonPachi Dai-Ou-Jou (Japan, 2002.04.05 Master Ver)"},
        {"ddpdojblk",     "DoDonPachi Dai-Ou-Jou Black Label (Japan, 2002.10.07.Black Ver, newer)"},
        {"ddpdojblka",    "DoDonPachi Dai-Ou-Jou Black Label (Japan, 2002.10.07.Black Ver, older)"},
        {"ddpdojblkb",    "DoDonPachi Dai-Ou-Jou Black Label (Japan, 2002.10.07 Black Ver)"},
        {"ddpdojblkbl",   "DoDonPachi Dai-Ou-Jou Black Label (Japan, 2002.10.07 Black Ver., bootleg Knights of Valour Super Heroes conversion)"},
        {"ddpdojp",       "DoDonPachi Dai-Ou-Jou (Japan, 2002.04.05 Master Ver, location test)"},
        {"ddpdojt",       "DoDonPachi Dai-Ou-Jou Tamashii (V201, China)"},
        {"ddpsdoj",       "DoDonPachi SaiDaiOuJou (2012/ 4/20)"},
        {"ddr2m",         "Dance Dance Revolution 2nd Mix (GN895 VER. JAA)"},
        {"ddr2mc",        "Dance Dance Revolution 2nd Mix with beatmaniaIIDX CLUB VERSiON (GE896 VER. JAA)"},
        {"ddr2mc2",       "Dance Dance Revolution 2nd Mix with beatmaniaIIDX substream CLUB VERSiON 2 (GE984 VER. JAA)"},
        {"ddr2ml",        "Dance Dance Revolution 2nd Mix - Link Ver (GE885 VER. JAA)"},
        {"ddr3ma",        "Dance Dance Revolution 3rd Mix (GN887 VER. AAA)"},
        {"ddr3mj",        "Dance Dance Revolution 3rd Mix (GN887 VER. JAA)"},
        {"ddr3mk",        "Dance Dance Revolution 3rd Mix - Ver.Korea2 (GN887 VER. KBA)"},
        {"ddr3mka",       "Dance Dance Revolution 3rd Mix - Ver.Korea (GN887 VER. KAA)"},
        {"ddr3mp",        "Dance Dance Revolution 3rd Mix Plus (G*A22 VER. JAA)"},
        {"ddr4m",         "Dance Dance Revolution 4th Mix (G*A33 VER. AAA)"},
        {"ddr4mj",        "Dance Dance Revolution 4th Mix (G*A33 VER. JAA)"},
        {"ddr4mp",        "Dance Dance Revolution 4th Mix Plus (G*A34 VER. JAA)"},
        {"ddr4mps",       "Dance Dance Revolution 4th Mix Plus Solo (G*A34 VER. JAA)"},
        {"ddr4ms",        "Dance Dance Revolution 4th Mix Solo (G*A33 VER. ABA)"},
        {"ddr4msj",       "Dance Dance Revolution 4th Mix Solo (G*A33 VER. JBA)"},
        {"ddr5m",         "Dance Dance Revolution 5th Mix (G*A27 VER. JAA)"},
        {"ddra",          "Dance Dance Revolution (GN845 VER. AAA)"},
        {"ddragn2u",      "Double Dragon II - The Revenge (US)"},
        {"ddrago3b",      "Double Dragon 3 - The Rosetta Stone (bootleg)"},
        {"ddragon",       "Double Dragon (Japan)"},
        {"ddragon2",      "Double Dragon II - The Revenge (World)"},
        {"ddragon2b",     "Double Dragon II - The Revenge (US bootleg, set 1) [Bootleg]"},
        {"ddragon2b2",    "Double Dragon II: The Revenge (US, bootleg, set 2)"},
        {"ddragon2bl",    "Double Dragon II: The Revenge (US, bootleg)"},
        {"ddragon2j",     "Double Dragon II: The Revenge (Japan)"},
        {"ddragon2u",     "Double Dragon II: The Revenge (US)"},
        {"ddragon3",      "Double Dragon 3 - The Rosetta Stone (US)"},
        {"ddragon3b",     "Double Dragon 3: The Rosetta Stone (bootleg)"},
        {"ddragon3j",     "Double Dragon 3 - The Rosetta Stone (Japan)"},
        {"ddragon3p",     "Double Dragon 3: The Rosetta Stone (prototype)"},
        {"ddragon6809",   "Double Dragon (bootleg with 3xM6809, set 1)"},
        {"ddragon6809a",  "Double Dragon (bootleg with 3xM6809, set 2)"},
        {"ddragona",      "Double Dragon (World set 2)"},
        {"ddragonb",      "Double Dragon (bootleg)"},
        {"ddragonb2",     "Double Dragon (bootleg)"},
        {"ddragonba",     "Double Dragon (bootleg with M6803)"},
        {"ddragonbl",     "Double Dragon (bootleg with HD6309)"},
        {"ddragonbl2",    "Double Dragon (bootleg)"},
        {"ddragonbla",    "Double Dragon (bootleg with MC6803)"},
        {"ddragonj",      "Double Dragon (Japan set 1)"},
        {"ddragonja",     "Double Dragon (Japan set 2)"},
        {"ddragonu",      "Double Dragon (US)"},
        {"ddragonua",     "Double Dragon (US set 2)"},
        {"ddragonub",     "Double Dragon (US set 3)"},
        {"ddragonw",      "Double Dragon (World)"},
        {"ddragonw1",     "Double Dragon (World Set 2)"},
        {"ddrbocd",       "Dance Dance Revolution Best of Cool Dancers (GE892 VER. JAA)"},
        {"ddream95",      "Dunk Dream '95 (Japan 1.4 EAM)"},
        {"ddrextrm",      "Dance Dance Revolution Extreme (G*C36 VER. JAA)"},
        {"ddribble",      "Double Dribble"},
        {"ddribblep",     "Double Dribble (prototype?)"},
        {"ddrj",          "Dance Dance Revolution - Internet Ranking Ver (GC845 VER. JBA)"},
        {"ddrja",         "Dance Dance Revolution (GC845 VER. JAA)"},
        {"ddrjb",         "Dance Dance Revolution (GC845 VER. JAB)"},
        {"ddrkids",       "Dance Dance Revolution Kids (GQAN4 JAA)"},
        {"ddrmax",        "DDR Max - Dance Dance Revolution 6th Mix (G*B19 VER. JAA)"},
        {"ddrmax2",       "DDR Max 2 - Dance Dance Revolution 7th Mix (G*B20 VER. JAA)"},
        {"ddrs2k",        "Dance Dance Revolution Solo 2000 (GC905 VER. AAA)"},
        {"ddrs2kj",       "Dance Dance Revolution Solo 2000 (GC905 VER. JAA)"},
        {"ddrsbm",        "Dance Dance Revolution Solo Bass Mix (GQ894 VER. JAA)"},
        {"ddru",          "Dance Dance Revolution (GN845 VER. UAA)"},
        {"ddrusa",        "Dance Dance Revolution USA (G*A44 VER. UAA)"},
        {"ddsom",         "Dungeons & Dragons: Shadow over Mystara (Euro 960619)"},
        {"ddsoma",        "Dungeons & Dragons: Shadow over Mystara (Asia 960619)"},
        {"ddsomar1",      "Dungeons & Dragons: Shadow over Mystara (Asia 960208)"},
        {"ddsomb",        "Dungeons & Dragons: Shadow over Mystara (Brazil 960223)"},
        {"ddsomh",        "Dungeons & Dragons: Shadow over Mystara (Hispanic 960223)"},
        {"ddsomj",        "Dungeons & Dragons: Shadow over Mystara (Japan 960619)"},
        {"ddsomjc",       "Dungeons & Dragons: Shadow over Mystara (T-Chi)"},
        {"ddsomjr1",      "Dungeons & Dragons: Shadow over Mystara (Japan 960206)"},
        {"ddsomjr2",      "Dungeons & Dragons: Shadow over Mystara (Japan 960223)"},
        {"ddsomr1",       "Dungeons & Dragons: Shadow over Mystara (Euro 960223)"},
        {"ddsomr2",       "Dungeons & Dragons: Shadow over Mystara (Euro 960209)"},
        {"ddsomr3",       "Dungeons & Dragons: Shadow over Mystara (Euro 960208)"},
        {"ddsomu",        "Dungeons & Dragons: Shadow over Mystara (USA 960619)"},
        {"ddsomud",       "Dungeons & Dragons: Shadow over Mystara (USA 960619 Phoenix Edition) (bootleg)"},
        {"ddsomur1",      "Dungeons & Dragons: Shadow over Mystara (USA 960209)"},
        {"ddtod",         "Dungeons & Dragons: Tower of Doom (Euro 940412)"},
        {"ddtoda",        "Dungeons & Dragons: Tower of Doom (Asia 940412)"},
        {"ddtodar1",      "Dungeons & Dragons: Tower of Doom (Asia 940113)"},
        {"ddtodd",        "Dungeons & Dragons: Tower of Doom (Europe 940412 Phoenix Edition) (bootleg)"},
        {"ddtodh",        "Dungeons & Dragons: Tower of Doom (Hispanic 940412)"},
        {"ddtodhr1",      "Dungeons & Dragons: Tower of Doom (Hispanic 940125)"},
        {"ddtodhr2",      "Dungeons & Dragons: Tower of Doom (Hispanic 940113)"},
        {"ddtodj",        "Dungeons & Dragons: Tower of Doom (Japan 940412)"},
        {"ddtodjr1",      "Dungeons & Dragons: Tower of Doom (Japan 940125)"},
        {"ddtodjr2",      "Dungeons & Dragons: Tower of Doom (Japan 940113)"},
        {"ddtodr1",       "Dungeons & Dragons: Tower of Doom (Euro 940113)"},
        {"ddtodu",        "Dungeons & Dragons: Tower of Doom (USA 940125)"},
        {"ddtodur1",      "Dungeons & Dragons: Tower of Doom (USA 940113)"},
        {"ddungeon",      "Dangerous Dungeons"},
        {"ddungeone",     "Dangerous Dungeons (set 2)"},
        {"ddux",          "Dynamite Dux (set 3, World) (FD1094 317-0096)"},
        {"ddux1",         "Dynamite Dux (set 1, World) (8751 317-0095)"},
        {"dduxbl",        "Dynamite Dux (bootleg)"},
        {"dduxd",         "Dynamite Dux (set 3, World) (bootleg of FD1094 317-0096 set)"},
        {"dduxj",         "Dynamite Dux (set 2, Japan) (FD1094 317-0094)"},
        {"dduxjd",        "Dynamite Dux (set 2, Japan) (bootleg of FD1094 317-0094 set)"},
        {"ddz",           "Dou Di Zhu"},
        {"deadang",       "Dead Angle"},
        {"deadconj",      "Dead Connection (Japan)"},
        {"deadconx",      "Dead Connection (World)"},
        {"deadconxj",     "Dead Connection (Japan)"},
        {"deadeye",       "Dead Eye"},
        {"dealem",        "Deal 'Em (MPU4 Conversion Kit, v7.0)"},
        {"dealer",        "The Dealer"},
        {"deathbrd",      "Death Brade (Japan Rev 2, JM-3)"},
        {"deathcox",      "Death Crimson OX (USA)"},
        {"deathcoxj",     "Death Crimson OX (Japan, Rev A)"},
        {"deathcoxo",     "Death Crimson OX (Japan)"},
        {"deathsml",      "Deathsmiles (2007/10/09 MASTER VER)"},
        {"decathlt",      "Decathlete"},
        {"decathlto",     "Decathlete (JUET 960424 V1.000)"},
        {"decocass",      "Cassette System"},
        {"decodark",      "DECO Cassette System ROM Multigame (Darksoft, v17)"},
        {"decodark15",    "DECO Cassette System ROM Multigame (Darksoft, v15)"},
        {"decodark16",    "DECO Cassette System ROM Multigame (Darksoft, v16)"},
        {"decomult",      "DECO Cassette System ROM Multigame (David Widel)"},
        {"deerhunt",      "Deer Hunting USA V4.3"},
        {"deerhunta",     "Deer Hunting USA V4.2"},
        {"deerhuntb",     "Deer Hunting USA V4.0"},
        {"deerhuntc",     "Deer Hunting USA V3"},
        {"deerhuntd",     "Deer Hunting USA V2"},
        {"deerhunte",     "Deer Hunting USA V1"},
        {"deerhuntj",     "Deer Hunting USA V4.4.1 (Japan)"},
        {"defcmnd",       "Defense Command (set 1)"},
        {"defence",       "Defence Command"},
        {"defender",      "Defender (Red label)"},
        {"defenderb",     "Defender (Blue label)"},
        {"defenderg",     "Defender (Green label)"},
        {"defenderj",     "T.T Defender"},
        {"defenderom",    "Operacion Defender (bootleg of Defender)"},
        {"defenderw",     "Defender (White label)"},
        {"defendg",       "Defender (Green label)"},
        {"defendw",       "Defender (White label)"},
        {"defense",       "Defense (System 16B, FD1089A 317-0028)"},
        {"defenseb",      "Defense (bootleg of Defender)"},
        {"defndjeu",      "Defender [Q] (bootleg)"},
        {"deltrace",      "Delta Race"},
        {"deluxe4u",      "Deluxe 4 U (ver. 0107, 07/01/2000)"},
        {"deluxe5",       "Deluxe 5 (ver. 0107, 07-01-2000)"},
        {"deluxe5a",      "Deluxe 5 (ver. 0107, 07/01/2000, set 2)"},
        {"deluxe5b",      "Deluxe 5 (ver. 0107, 07/01/2000, set 3)"},
        {"demndrgn",      "Demons & Dragons (prototype)"},
        {"demoderb",      "Demolition Derby"},
        {"demoderbc",     "Demolition Derby (cocktail)"},
        {"demoderm",      "Demolition Derby (2-Player Mono Board Version)"},
        {"demofist",      "Demolish Fist"},
        {"demon",         "Demon"},
        {"demoneye",      "Demoneye-X"},
        {"demonwl1",      "Demon's World - Horror Story (Taito license)"},
        {"demonwld",      "Demon's World - Horror Story"},
        {"demonwld1",     "Demon's World / Horror Story (set 2)"},
        {"demonwld2",     "Demon's World / Horror Story (set 3)"},
        {"demonwld3",     "Demon's World / Horror Story (set 4)"},
        {"demonwld4",     "Demon's World / Horror Story (set 5)"},
        {"demonwld5",     "Demon's World / Horror Story (set 6)"},
        {"dendeg",        "Densya De Go (Japan)"},
        {"dendeg2",       "Densya De Go 2 (Japan)"},
        {"dendeg2x",      "Densya De Go 2 Ex (Japan)"},
        {"dendego",       "Densha de GO! (Ver 2.3 J)"},
        {"dendego2",      "Densha de GO! 2 Kousoku-hen (Ver 2.5 J)"},
        {"dendego23k",    "Densha de GO! 2 Kousoku-hen 3000-bandai (Ver 2.20 J)"},
        {"dendegoa",      "Densha de GO! (Ver 2.2 J)"},
        {"dendegox",      "Densha de GO! EX (Ver 2.4 J)"},
        {"dendegx",       "Densya De Go Ex (Japan)"},
        {"denjinmk",      "Denjin Makai"},
        {"denjinmka",     "Denjin Makai (set 2)"},
        {"denseib",       "Ghost Chaser Densei (SNES bootleg, set 1)"},
        {"denseib2",      "Ghost Chaser Densei (SNES bootleg, set 2)"},
        {"depthch",       "Depthcharge"},
        {"depthcho",      "Depthcharge (older)"},
        {"depthv1",       "Depthcharge (older)"},
        {"derbyo2k",      "Derby Owners Club 2000 Ver.2 (Japan, Rev A)"},
        {"derbyoc",       "Derby Owners Club (Japan, Rev B)"},
        {"derbyoc2",      "Derby Owners Club II Ver.2.1 (Japan, Rev B)"},
        {"derbyocw",      "Derby Owners Club World Edition EX (Rev D)"},
        {"deroon",        "Deroon DeroDero"},
        {"deroon2",       "Deroon DeroDero / Tecmo Stackers"},
        {"deroona",       "Deroon DeroDero (earlier, set 2)"},
        {"desert",        "Desert Tank"},
        {"desertbr",      "Desert Breaker (World) (FD1094 317-0196)"},
        {"desertbrd",     "Desert Breaker (World) (bootleg of FD1094 317-0196 set)"},
        {"desertbrj",     "Desert Breaker (Japan) (FD1094 317-0194)"},
        {"desertbrjd",    "Desert Breaker (Japan) (bootleg of FD1094 317-0194 set)"},
        {"desertdn",      "Desert Dan"},
        {"desertgu",      "Desert Gun"},
        {"desertwr",      "Desert War - Wangan Sensou"},
        {"deshoros",      "Destiny Horoscope"},
        {"destderb",      "Demolition Derby"},
        {"destderm",      "Demolition Derby (2-Player Mono Board Version)"},
        {"desterth",      "Destination Earth"},
        {"destroyr",      "Destroyer"},
        {"destroyr1",     "Destroyer (Atari, version O1)"},
        {"destryer",      "Destroyer (Cidelsa, set 1)"},
        {"destryera",     "Destroyer (Cidelsa, set 2)"},
        {"detatwin",      "Detana!! Twin Bee (Japan ver. J)"},
        {"devilfsg",      "Devil Fish (Galaxian hardware, bootleg[Q])"},
        {"devilfsh",      "Devil Fish"},
        {"devilfshg",     "Devil Fish (Galaxian hardware)"},
        {"devilfshgb",    "Devil Fish (Galaxian hardware, bootleg)"},
        {"devilw",        "Devil World"},
        {"devstor2",      "Devastators (ver. X)"},
        {"devstor3",      "Devastators (ver. V)"},
        {"devstors",      "Devastators (ver. Z)"},
        {"devstors2",     "Devastators (ver. 2)"},
        {"devstors3",     "Devastators (ver. V)"},
        {"devstorsv",     "Devastators (ver. V)"},
        {"devstorsx",     "Devastators (ver. X)"},
        {"devzone",       "Devil Zone"},
        {"devzone2",      "Devil Zone (easier)"},
        {"dfeveron",      "Dangun Feveron (Japan)"},
        {"dfjail",        "The Destroyer From Jail (Korea)"},
        {"dfkbl",         "DoDonPachi Dai-Fukkatsu Black Label (2010/1/18 BLACK LABEL)"},
        {"dharma",        "Dharma Doujou"},
        {"dharmag",       "Dharma Doujou (Germany)"},
        {"dharmaj",       "Dharma Doujou (Japan)"},
        {"dharmak",       "Dharma Doujou (Korea)"},
        {"diamond",       "Diamond Run"},
        {"diamrun",       "Diamond Run"},
        {"dicegame",      "Dice - The Dice Game!"},
        {"diehard",       "Die Hard Arcade (US)"},
        {"dietgo",        "Diet Go Go (Euro v1.1)"},
        {"dietgoe",       "Diet Go Go (Euro v1.1,1992.08.04)"},
        {"dietgoea",      "Diet Go Go (Europe v1.1 1992.08.04)"},
        {"dietgoj",       "Diet Go Go (Japan v1.1)"},
        {"dietgou",       "Diet Go Go (USA v1.1)"},
        {"digdug",        "Dig Dug (rev 2)"},
        {"digdug1",       "Dig Dug (rev 1)"},
        {"digdug2",       "Dig Dug II (New Ver.)"},
        {"digdug2a",      "Dig Dug II (set 2)"},
        {"digdug2o",      "Dig Dug II (Old Ver.)"},
        {"digduga1",      "Dig Dug (Atari, rev 1)"},
        {"digdugat",      "Dig Dug (Atari, rev 2)"},
        {"digdugat1",     "Dig Dug (Atari, rev 1)"},
        {"digdugb",       "Dig Dug (rev 1)"},
        {"digger",        "Digger"},
        {"diggerc",       "Digger (CVS)"},
        {"diggerma",      "Digger Man"},
        {"digsid",        "Dig Dug (manufactured by Sidam)"},
        {"dimahoo",       "Dimahoo (Euro 000121)"},
        {"dimahoou",      "Dimahoo (USA 000121)"},
        {"dimahoud",      "Dimahoo (USA 000121 Phoenix Edition) (bootleg)"},
        {"dingo",         "Dingo"},
        {"dingoe",        "Dingo (encrypted)"},
        {"dino",          "Cadillacs and Dinosaurs (World 930201)"},
        {"dinoa",         "Cadillacs and Dinosaurs (Asia TW 930223)"},
        {"dinoh",         "Cadillacs and Dinosaurs (bootleg set 3, 930223 Asia TW)"},
        {"dinohc",        "Cadillacs and Dinosaurs (Chinese bootleg, 930223 Asia TW)"},
        {"dinohunt",      "Dinosaur Hunter (Chinese bootleg of Cadillacs and Dinosaurs)"},
        {"dinoj",         "Cadillacs Kyouryuu-Shinseiki (Japan 930201)"},
        {"dinopic",       "Cadillacs and Dinosaurs (bootleg with PIC16C57, set 1)"},
        {"dinopic2",      "Cadillacs and Dinosaurs (bootleg with PIC16C57, set 2)"},
        {"dinopic3",      "Cadillacs and Dinosaurs (bootleg with PIC16C57, set 3)"},
        {"dinopic4",      "Cadillacs and Dinosaurs (bootleg with PIC16C57, set 4)"},
        {"dinopic5",      "Cadillacs and Dinosaurs (bootleg with PIC16C57, set 5)"},
        {"dinorex",       "Dino Rex (World)"},
        {"dinorexj",      "Dino Rex (Japan)"},
        {"dinorexu",      "Dino Rex (US)"},
        {"dinot",         "Cadillacs and Dinosaurs Turbo (bootleg set 1, 930223 Asia TW)"},
        {"dinotpic",      "Cadillacs and Dinosaurs Turbo (bootleg set 2 (with PIC16c57), 930201 etc)"},
        {"dinou",         "Cadillacs and Dinosaurs (US 930201)"},
        {"dirtdash",      "Dirt Dash (Rev. DT2)"},
        {"dirtdasha",     "Dirt Dash (World, DT2 Ver.A)"},
        {"dirtdashj",     "Dirt Dash (Japan, DT1 Ver.A)"},
        {"dirtdvls",      "Dirt Devils (Export, Revision A)"},
        {"dirtdvlsa",     "Dirt Devils (Australia, Revision A)"},
        {"dirtdvlsau",    "Dirt Devils (Australia, Revision A)"},
        {"dirtdvlsg",     "Dirt Devils (Export, Ver. G?)"},
        {"dirtdvlsj",     "Dirt Devils (Japan, Revision A)"},
        {"dirtdvlsu",     "Dirt Devils (USA, Revision A)"},
        {"dirtfoxj",      "Dirt Fox (Japan)"},
        {"dirtypig",      "Dirty Pigskin Football"},
        {"disco",         "Disco No.1"},
        {"discoboy",      "Disco Boy"},
        {"discoboyp",     "Disco Boy (Promat license)"},
        {"discof",        "Disco No.1 (Rev.F)"},
        {"divebomb",      "Kyuukoukabakugekitai - Dive Bomber Squad (Japan, prototype)"},
        {"diverboy",      "Diver Boy"},
        {"djboy",         "DJ Boy"},
        {"djboya",        "DJ Boy (set 2)"},
        {"djboyj",        "DJ Boy (Japan)"},
        {"djboyja",       "DJ Boy (Japan, set 2)"},
        {"djboyu",        "DJ Boy (US, set 1)"},
        {"djboyua",       "DJ Boy (US, set 2)"},
        {"djgirl",        "DJ Girl (Promat license)"},
        {"dkaccel",       "Donkey Kong Accelerate"},
        {"dkcbarrel",     "Donkey Kong Crazy Barrels Edition"},
        {"dkchrmx",       "Donkey Kong Christmas Remix"},
        {"dkduel",        "Donkey Kong Duel"},
        {"dkfreerun",     "Donkey Kong Freerun Edition"},
        {"dkgenm72",      "Daiku no Gensan (Japan, M72)"},
        {"dkgensan",      "Daiku no Gensan (Japan)"},
        {"dkgensanm72",   "Daiku no Gensan (Japan, M72 hardware)"},
        {"dkgensanm82",   "Daiku no Gensan (Japan, M82 hardware)"},
        {"dkhrthnt",      "Donkey Kong Hearthunt"},
        {"dking",         "Donkey King"},
        {"dkingjr",       "Donkey King Jr. (bootleg of Donkey Kong Jr.)"},
        {"dkjrbl",        "Donkey Kong Junior (bootleg?)"},
        {"dkjrjp",        "Donkey Kong Junior (Japan)"},
        {"dkngjnrb",      "Donkey Kong Junior (bootleg[Q])"},
        {"dkngjnrj",      "Donkey Kong Junior (Japan[Q])"},
        {"dkngjrjp",      "Donkey Kong Jr. (Original Japanese)"},
        {"dkong",         "Donkey Kong (US set 1)"},
        {"dkong3",        "Donkey Kong 3 (US)"},
        {"dkong3abl",     "Donkey Kong 3 (bootleg on Ambush hardware)"},
        {"dkong3b",       "Donkey Kong 3 (bootleg on Donkey Kong Jr. hardware)"},
        {"dkong3hs",      "Donkey Kong High Score Kit (hack,V1.0a)"},
        {"dkong3j",       "Donkey Kong 3 (Japan)"},
        {"dkong40y",      "Donkey Kong Anniversary Edition"},
        {"dkongbp",       "Donkey Kong Barrelpalooza v1.06"},
        {"dkongbp1",      "Donkey Kong Barrelpalooza v1.07"},
        {"dkongchm",      "Donkey Kong League Championship v1.00"},
        {"dkongchm1",     "Donkey Kong Championship Edition v1.01"},
        {"dkongf",        "Donkey Kong Foundry (hack)"},
        {"dkonghrd",      "Donkey Kong (hard kit)"},
        {"dkonghs",       "Donkey Kong High Score Kit (hack,V1.2)"},
        {"dkongike",      "Donkey Kong/DK (Japan) (hack,V1.1 IKE)"},
        {"dkongitd",      "Donkey Kong In the Dark v1.02"},
        {"dkongj",        "Donkey Kong (Japan set 1)"},
        {"dkongjnrj",     "Donkey Kong Junior (Japan set F-1)"},
        {"dkongjo",       "Donkey Kong (Japan set 2)"},
        {"dkongjo1",      "Donkey Kong (Japan set 3) (bad dump[Q])"},
        {"dkongjp",       "Donkey Kong (Japan set 1)"},
        {"dkongjpo",      "Donkey Kong (Japan set 2)"},
        {"dkongjr",       "Donkey Kong Junior (US)"},
        {"dkongjr2",      "Donkey Kong Junior (US, bootleg?)"},
        {"dkongjrb",      "Donkey Kong Jr. (bootleg)"},
        {"dkongjre",      "Donkey Kong Junior (E kit)"},
        {"dkongjrhs",     "Donkey Junior High Score Kit (hack,V1.2)"},
        {"dkongjrj",      "Donkey Kong Jr. (Japan)"},
        {"dkongjrm",      "Donkey Kong Jr. (Moon Cresta hardware)"},
        {"dkongjrpb",     "Donkey Kong Junior (P kit, bootleg)"},
        {"dkongo",        "Donkey Kong (US set 2)"},
        {"dkongotr",      "Donkey Kong On the Run v1.02"},
        {"dkongp",        "Donkey Kong (Patched)"},
        {"dkongpac",      "Donkey Kong (Pacman Graphics)"},
        {"dkongpe",       "Donkey Kong - Pauline Edition"},
        {"dkongran1",     "Donkey Kong Randomized Edition v1.01"},
        {"dkongss",       "Donkey Kong Skip Start v1.00"},
        {"dkongst",       "Donkey Kong Springs Trainer"},
        {"dkongst2",      "Donkey Kong Springs Trainer 2"},
        {"dkongtj",       "Donkey Kong Twisted Jungle v1.05"},
        {"dkongx",        "Donkey Kong II - Jumpman Returns (Hack V1.2)"},
        {"dkongx11",      "Donkey Kong II: Jumpman Returns (hack, V1.1)"},
        {"dkpace",        "Donkey Kong Pace"},
        {"dkpmx",         "Donkey Kong Pac-Man Crossover"},
        {"dkrdemo",       "Donkey Kong Remix (Demo)"},
        {"dkremix",       "Donkey Kong Remix"},
        {"dkrndmzr",      "Donkey Kong RNDMZR"},
        {"dktrainer",     "Donkey Kong Trainer 1.01"},
        {"dkwizardry",    "Donkey Kong Wizardry"},
        {"dlair",         "Dragon's Lair"},
        {"dlaira",        "Dragon's Lair (US Rev. A, Pioneer PR-7820)"},
        {"dlairb",        "Dragon's Lair (US Rev. B, Pioneer PR-7820)"},
        {"dlairc",        "Dragon's Lair (US Rev. C, Pioneer PR-7820)"},
        {"dlaird",        "Dragon's Lair (US Rev. D, Pioneer LD-V1000)"},
        {"dlaire",        "Dragon's Lair (US Rev. E)"},
        {"dlairf",        "Dragon's Lair (US Rev. F)"},
        {"dland",         "Dream Land / Super Dream Land (bootleg of Bubble Bobble)"},
        {"dleague",       "Dynamite League (Japan)"},
        {"dleaguej",      "Dynamite League (Japan)"},
        {"dleuro",        "Dragon's Lair (European)"},
        {"dlital",        "Dragon's Lair (Italian)"},
        {"dmdtouch",      "Diamond Touch (E - 30-06-97, Local)"},
        {"dmnfrnt",       "Demon Front / Moyu Zhanxian (68k label V105, ROM M105XX 08/05/02) (ARM label V105, ROM 08/05/02 S105XX)"},
        {"dmnfrnt102",    "Demon Front / Moyu Zhanxian (68k label V102, ROM M102XX 06/19/02) (ARM label V102, ROM 05/24/02 S101XX)"},
        {"dmnfrnt103",    "Demon Front / Moyu Zhanxian (68k label V103, ROM M103XX 07/05/02) (ARM label V103, ROM 07/05/02 S103XX)"},
        {"dmnfrnta",      "Demon Front (ver. 105)"},
        {"dmnfrntb",      "Demon Front (V103)"},
        {"dmnfrntpcb",    "Demon Front V1.1 / Moyu Zhanxian V1.1 (68k label V107KR, ROM M107KR 11/03/03) (ARM label V106KR, ROM 10/16/03 S106KR) (JAMMA PCB)"},
        {"dmnfrntpcba",   "Demon Front (VM105XX, S105XX, China, Single PCB Version)"},
        {"dmx",           "Dance Maniax (G*874 VER. JAA)"},
        {"dmx2m",         "Dance Maniax 2nd Mix (G*A39 VER. JAA)"},
        {"dmx2majp",      "Dance Maniax 2nd Mix Append J-Paradise (G*A38 VER. JAA)"},
        {"dncfrks",       "Dance Freaks (G*874 VER. KAA)"},
        {"dngrtrck",      "Danger Track (bootleg of Rally X)"},
        {"dnmtdeka",      "Dynamite Deka (Japan)"},
        {"doa",           "Dead or Alive (Model 2B, Revision C)"},
        {"doa2",          "Dead or Alive 2"},
        {"doa2a",         "Dead or Alive 2 (Rev A)"},
        {"doa2m",         "Dead or Alive 2 Millennium"},
        {"doaa",          "Dead or Alive (Model 2A, Revision A)"},
        {"doaab",         "Dead or Alive (Model 2A)"},
        {"doaae",         "Dead or Alive (Export, Model 2A, Revision A)"},
        {"doab",          "Dead or Alive (Model 2B, Revision B)"},
        {"doapp",         "Dead Or Alive ++ (JAPAN)"},
        {"docastl2",      "Mr. Do's Castle (set 2)"},
        {"docastle",      "Mr. Do's Castle (set 1)"},
        {"docastle2",     "Mr. Do's Castle (set 2)"},
        {"docastleo",     "Mr. Do's Castle (older)"},
        {"docastlo",      "Mr. Do's Castle (older)"},
        {"dockman",       "Dock Man"},
        {"dockmanb",      "Dock Man (set 2)"},
        {"dockmanc",      "Dock Man (set 3)"},
        {"dodge",         "Dodge City"},
        {"dodgem",        "Dodgem"},
        {"dodgeman",      "Dodge Man"},
        {"dodghero",      "Minna Atsumare! Dodge Hero"},
        {"dogfgt",        "Acrobatic Dog-Fight"},
        {"dogfgtj",       "Dog-Fight (Japan) "},
        {"dogfgtu",       "Acrobatic Dog-Fight (USA)"},
        {"dogfight",      "Dog Fight (Thunderbolt)"},
        {"dogfightp",     "Dog Fight (Orca, prototype)"},
        {"dogosokb",      "Dogou Souken (Joystick hack bootleg)"},
        {"dogosoke",      "Dogou Souken"},
        {"dogosokj",      "Dogou Souken (joystick hack bootleg)"},
        {"dogpatch",      "Dog Patch"},
        {"dogyuun",       "Dogyuun"},
        {"dogyuuna",      "Dogyuun (older set)"},
        {"dogyuunb",      "Dogyuun (oldest set)"},
        {"dogyuunk",      "Dogyuun (Unite Trading license)"},
        {"dogyuunt",      "Dogyuun (10/9/1992 location test)"},
        {"dogyuunto",     "Dogyuun (8/25/1992 location test)"},
        {"dokaben",       "Dokaben (Japan)"},
        {"dokaben2",      "Dokaben 2 (Japan)"},
        {"dokidoki",      "Doki Doki Penguin Land"},
        {"dokyusei",      "Mahjong Doukyuusei"},
        {"dokyusp",       "Mahjong Doukyuusei Special"},
        {"dolmen",        "Dolmen"},
        {"dolmenk",       "Goindol (Afega)"},
        {"dolphin",       "Dolphin Blue"},
        {"dolphtra",      "Dolphin Treasure (B - 06/12/96, NSW/ACT, Rev 3)"},
        {"domino",        "Domino Man"},
        {"dominoa",       "Domino Man (set 2)"},
        {"dominob",       "Domino Block"},
        {"dominobv2",     "Domino Block ver.2"},
        {"dominos",       "Dominos"},
        {"dominos4",      "Dominos 4 (Cocktail)"},
        {"dommy",         "Dommy"},
        {"doncdoon",      "Donchan no Hanabi de Doon"},
        {"dondenmj",      "Don Den Mahjong [BET] (Japan)"},
        {"dondokdj",      "Don Doko Don (Japan)"},
        {"dondokdu",      "Don Doko Don (US)"},
        {"dondokod",      "Don Doko Don (World)"},
        {"dondokodj",     "Don Doko Don (Japan, rev 1)"},
        {"dondokodu",     "Don Doko Don (US, rev 1)"},
        {"donpachi",      "DonPachi (US)"},
        {"donpachihk",    "DonPachi (Hong Kong)"},
        {"donpachij",     "DonPachi (Japan)"},
        {"donpachijs",    "DonPachi (Japan, Satsuei version)"},
        {"donpachikr",    "DonPachi (Korea)"},
        {"donpachj",      "DonPachi (Japan)"},
        {"donpachk",      "DonPachi (Korea)"},
        {"dorachan",      "Dorachan"},
        {"dorodon",       "Dorodon (set 1)"},
        {"dorodon2",      "Dorodon (set 2)"},
        {"dorunru2",      "Do! Run Run (set 2)"},
        {"dorunruc",      "Do! Run Run (Do's Castle hardware)"},
        {"dorunrun",      "Do! Run Run (set 1)"},
        {"dorunrun2",     "Do! Run Run (set 2)"},
        {"dorunrunc",     "Do! Run Run (Do's Castle hardware, set 1)"},
        {"dorunrunca",    "Do! Run Run (Do's Castle hardware, set 2)"},
        {"dotriku2",      "Dottori Kun (old version)"},
        {"dotrikun",      "Dottori Kun (new version)"},
        {"dotrikun2",     "Dottori Kun (old version)"},
        {"dotriman",      "Dottori-Man Jr."},
        {"dotron",        "Discs of Tron (Upright)"},
        {"dotrona",       "Discs of Tron (Upright alternate)"},
        {"dotrone",       "Discs of Tron (Environmental)"},
        {"doubledr",      "Double Dragon (Neo-Geo)"},
        {"douni",         "Mr. Do vs. Unicorns"},
        {"dowild",        "Mr. Do's Wild Ride"},
        {"downhill",      "Downhill Bikers (DH3 Ver. A)"},
        {"downtowj",      "DownTown (joystick hack)"},
        {"downtown",      "DownTown"},
        {"downtown2",     "DownTown / Mokugeki (set 2)"},
        {"downtownj",     "DownTown / Mokugeki (joystick hack)"},
        {"downtownp",     "DownTown / Mokugeki (prototype)"},
        {"dplay",         "Double Play"},
        {"dquizgo",       "Date Quiz Go Go (Korea)"},
        {"dquizgo2",      "Date Quiz Go Go Episode 2"},
        {"draco",         "Draco"},
        {"dragchrn",      "Dragon Chronicles (DC001 Ver. A)"},
        {"dragnblz",      "Dragon Blaze"},
        {"dragngun",      "Dragon Gun (US)"},
        {"dragngunj",     "Dragon Gun (Japan)"},
        {"dragonsh",      "Dragons Heaven"},
        {"dragoona",      "Dragoon Might (ver AAB)"},
        {"dragoonj",      "Dragoon Might (ver JAA)"},
        {"dragrace",      "Drag Race"},
        {"dragwld2",      "Zhong Guo Long II (ver. 100C, China)"},
        {"drakton",       "Drakton"},
        {"drbyocwa",      "Derby Owners Club World Edition (Rev A)"},
        {"drbyocwb",      "Derby Owners Club World Edition (Rev B)"},
        {"drbyocwc",      "Derby Owners Club World Edition (Rev C)"},
        {"drbyocwt",      "Derby Owners Club World Edition (Rev T)"},
        {"dreamwld",      "Dream World"},
        {"dremshpr",      "Dream Shopper"},
        {"drgnbowl",      "Dragon Bowl"},
        {"drgnbowla",     "Dragon Bowl (set 2, unencrypted program)"},
        {"drgnbstr",      "Dragon Buster"},
        {"drgninja",      "Dragonninja (Japan)"},
        {"drgninjab",     "Dragonninja (bootleg)"},
        {"drgninjab2",    "Dragonninja (bootleg with 68705)"},
        {"drgnmst",       "Dragon Master"},
        {"drgnmst2",      "Dragon Master (set 2)"},
        {"drgnunit",      "Dragon Unit - Castle of Dragon"},
        {"drgnwrld",      "Dragon World (World, V040O)"},
        {"drgnwrldv10c",  "Zhongguo Long (China, V010C)"},
        {"drgnwrldv11h",  "Dung Fong Zi Zyu (Hong Kong, V011H, set 1)"},
        {"drgnwrldv11ha", "Dung Fong Zi Zyu (Hong Kong, V011H, set 2)"},
        {"drgnwrldv20j",  "Chuugokuryuu (Japan, V020J)"},
        {"drgnwrldv21",   "Dragon World (World, V021O)"},
        {"drgnwrldv21j",  "Chuugokuryuu (Japan, V021J)"},
        {"drgnwrldv30",   "Dragon World (World, V030O)"},
        {"drgnwrldv40k",  "Dragon World (Korea, V040K)"},
        {"drgpunch",      "Dragon Punch (Japan)"},
        {"drgw2",         "Dragon World II (ver. 110X, Export)"},
        {"drgw2100c",     "Zhongguo Long II (ver. 100C, China)"},
        {"drgw2100hk",    "Dungfong Zi Zyu II (ver. 100H, Hong Kong)"},
        {"drgw2100j",     "Chuugokuryuu II (ver. 100J, Japan)"},
        {"drgw2100x",     "Dragon World II (ver. 100X, Export)"},
        {"drgw2101c",     "Zhongguo Long II (ver. 101C, China)"},
        {"drgw2101j",     "Chuugokuryuu II (ver. 101J, Japan)"},
        {"drgw2c",        "Zhong Guo Long II (ver. 100C, China)"},
        {"drgw2hk",       "Dragon World II (V100H, Hong Kong)"},
        {"drgw2j",        "Chuugokuryuu II (ver. 100J, Japan)"},
        {"drgw3",         "Dragon World 3 / Zhongguo Long 3 / Dungfong Zi Zyu 3 / Chuugokuryuu 3 Special (ver. 106)"},
        {"drgw3100",      "Chuugokuryuu 3 Special (Japan, ver. 100)"},
        {"drgw3103",      "Chuugokuryuu 3 Special (Japan, ver. 103)"},
        {"drgw3105",      "Dragon World 3 / Zhongguo Long 3 / Dungfong Zi Zyu 3 / Chuugokuryuu 3 Special (ver. 105)"},
        {"dribling",      "Dribbling"},
        {"driblinga",     "Dribbling (set 2)"},
        {"driblingam",    "Dribbling (Automave)"},
        {"driblingbr",    "Dribbling (bootleg, Brazil) [Bootleg, No sound]"},
        {"driblingo",     "Dribbling (Olympia)"},
        {"driblingvm",    "Dribbling (Videomac bootleg, Brazil)"},
        {"driblino",      "Dribbling (Olympia)"},
        {"drifto94",      "Drift Out '94 - The Hard Order (Japan)"},
        {"driftout",      "Drift Out (Japan)"},
        {"driftoutct",    "Drift Out (Europe, Cameltry conversion)"},
        {"driftoutj",     "Drift Out (Japan)"},
        {"drius2do",      "Darius II (dual screen) (Japan old version)"},
        {"drivedge",      "Driver's Edge"},
        {"driveout",      "Drive Out"},
        {"driveyes",      "Driver's Eyes (US)"},
        {"drivfrcb",      "Driving Force (Galaxian conversion bootleg)"},
        {"drivfrcg",      "Driving Force (Galaxian conversion)"},
        {"drivfrcp",      "Driving Force (Pac-Man conversion)"},
        {"drivfrcsg",     "Driving Force (Galaxian conversion, Seatongrove UK, E-0010)"},
        {"drivfrct",      "Top Racer (bootleg of Driving Force)"},
        {"drktnjr",       "Drakton (DKJr conversion)"},
        {"drmario",       "Vs. Dr. Mario"},
        {"drmicro",       "Dr. Micro"},
        {"drmn",          "DrumMania (GQ881 VER. JAD)"},
        {"drmn2m",        "DrumMania 2nd Mix (GE912 VER. JAB)"},
        {"drmn2mpu",      "DrumMania 2nd Mix Session Power Up Kit (GE912 VER. JAB)"},
        {"drmn3m",        "DrumMania 3rd Mix (G*A23 VER. JAA)"},
        {"drtomy",        "Dr. Tomy"},
        {"drtoppel",      "Dr. Toppel's Adventure (World)"},
        {"drtoppela",     "Dr. Toppel's Adventure (World, alt?)"},
        {"drtoppelj",     "Dr. Toppel's Tankentai (Japan)"},
        {"drtoppelu",     "Dr. Toppel's Adventure (US)"},
        {"drtopplj",      "Dr. Toppel's Tankentai (Japan)"},
        {"drtopplu",      "Dr. Toppel's Adventure (US)"},
        {"dsaber",        "Dragon Saber"},
        {"dsabera",       "Dragon Saber (World, older?)"},
        {"dsaberj",       "Dragon Saber (Japan)"},
        {"dsccr94j",      "Dream Soccer '94 (Japan)"},
        {"dsem",          "Dancing Stage Euro Mix (G*936 VER. EAA)"},
        {"dsem2",         "Dancing Stage Euro Mix 2 (G*C23 VER. EAA)"},
        {"dsfdct",        "Dancing Stage featuring Dreams Come True (GC910 VER. JCA)"},
        {"dsfdcta",       "Dancing Stage featuring Dreams Come True (GC910 VER. JAA)"},
        {"dsfdr",         "Dancing Stage Featuring Disney's Rave (GCA37JAA)"},
        {"dsftkd",        "Dancing Stage featuring TRUE KiSS DESTiNATiON (G*884 VER. JAA)"},
        {"dsmbl",         "Deathsmiles MegaBlack Label (2008/10/06 MEGABLACK LABEL VER)"},
        {"dsoccr94",      "Dream Soccer '94"},
        {"dsoccr94j",     "Dream Soccer '94 (Japan, M92 hardware)"},
        {"dsoccr94k",     "Dream Soccer '94 (Korea, M107 hardware)"},
        {"dspirit",       "Dragon Spirit (new version)"},
        {"dspirit1",      "Dragon Spirit (old version (DS1))"},
        {"dspirit2",      "Dragon Spirit (DS2)"},
        {"dspirita",      "Dragon Spirit (Atari license)"},
        {"dspirito",      "Dragon Spirit (old version)"},
        {"dstage",        "Dancing Stage (GN845 VER. EAA)"},
        {"dstlk",         "Darkstalkers: The Night Warriors (Euro 940705)"},
        {"dstlka",        "Darkstalkers: The Night Warriors (Asia 940705)"},
        {"dstlkh",        "Darkstalkers: The Night Warriors (Hispanic 940818)"},
        {"dstlku",        "Darkstalkers: The Night Warriors (USA 940818)"},
        {"dstlku1d",      "Darkstalkers: The Night Warriors (USA 940705 Phoenix Edition) (bootleg)"},
        {"dstlkur1",      "Darkstalkers: The Night Warriors (USA 940705)"},
        {"dtfamily",      "Diet Family"},
        {"dtrvwz5",       "Deluxe Trivia ? Whiz (6221-70, U5-0A Edition 5)"},
        {"dtrvwz5v",      "Deluxe Trivia ? Whiz (6221-75, U5-0 Edition 5 Vertical)"},
        {"dualaslt",      "Dual Assault"},
        {"duckhunt",      "Vs. Duck Hunt"},
        {"ducki",         "Duck Tales (FMV Demo)"},
        {"dumpmtmt",      "Dump Matsumoto (Japan)"},
        {"dungenmu",      "Dungeon Magic (US)"},
        {"dungeonm",      "Dungeon Magic (World)"},
        {"dungeonmu",     "Dungeon Magic (Ver 2.1A 1994/02/18)"},
        {"dunhuang",      "Mahjong Dunhuang"},
        {"dunkmnia",      "Dunk Mania (DM1-VER.C)"},
        {"dunkmniaj",     "Dunk Mania (Japan, DM1/VER.C)"},
        {"dunkmniajc",    "Dunk Mania (Japan, DM1/VER.C)"},
        {"dunkshot",      "Dunk Shot (Rev C, FD1089A 317-0022)"},
        {"dunkshota",     "Dunk Shot (Rev A, FD1089A 317-0022)"},
        {"dunkshoto",     "Dunk Shot (FD1089A 317-0022)"},
        {"dw",            "Dynasty Wars (World)"},
        {"dw2001",        "Chuugokuryuu 2001 [Dragon World 2001] (V100 02/21/01 16:05:16, Japan)"},
        {"dw2v100x",      "Dragon World II (V100X, World)"},
        {"dwex",          "Dragon World 3 EX / Zhongguo Long 3 EX / Dungfong Zi Zyu 3 EX / Chuugokuryuu 3 EX (ver. 100)"},
        {"dwex101cn",     "Dragon World 3 EX / Zhongguo Long 3 EX / Dungfong Zi Zyu 3 EX / Chuugokuryuu 3 EX (ver. 101CN)"},
        {"dwi",           "DarkWing Duck (FMV Demo)"},
        {"dwia",          "DarkWing Duck (FMV Demo, alt)"},
        {"dwj",           "Tenchi wo Kurau (Japan)"},
        {"dwpc",          "Zhongguo Long Pretty Chance [Dragon World Pretty Chance] (V110 03/19/02 11:13:16, China)"},
        {"dwpc101j",      "Chuugokuryuu Pretty Chance [Dragon World Pretty Chance] (V101 09/26/01 10:23:26, Japan)"},
        {"dybb99",        "Dynamite Baseball '99 (Japan, Rev B)"},
        {"dybbnao",       "Dynamite Baseball NAOMI (Japan)"},
        {"dyger",         "Dyger (Korea set 1)"},
        {"dygera",        "Dyger (Korea set 2)"},
        {"dygolf",        "Virtua Golf / Dynamic Golf (Rev A) (GDS-0009A)"},
        {"dygolfp",       "Virtua Golf / Dynamic Golf (prototype)"},
        {"dynabb",        "Dynamite Baseball"},
        {"dynabb97",      "Dynamite Baseball 97 (Revision A)"},
        {"dynablsb",      "Dynablaster (bootleg)"},
        {"dynablst",      "Dynablaster (World)"},
        {"dynablstb",     "Dynablaster / Bomber Man (bootleg, set 1)"},
        {"dynablstb2",    "Dynablaster / Bomber Man (bootleg, set 2)"},
        {"dynablstb3",    "Dynablaster / Bomber Man (bootleg, set 3)"},
        {"dynablstb4",    "Dynablaster / Bomber Man (bootleg, set 4)"},
        {"dynabomb",      "Dynamite Bomber (Korea, Rev 1.5)"},
        {"dynagear",      "Dyna Gears"},
        {"dynamcop",      "Dynamite Cop (Export, Model 2A)"},
        {"dynamcopb",     "Dynamite Cop (Export, Model 2B)"},
        {"dynamcopc",     "Dynamite Cop (USA, Model 2C)"},
        {"dynamski",      "Dynamic Ski"},
        {"dynashot",      "Dynamic Shoot Kyousou"},
        {"dyndeka2",      "Dynamite Deka 2 (Japan, Model 2A)"},
        {"dyndeka2b",     "Dynamite Deka 2 (Japan, Model 2B)"},
        {"dynduke",       "Dynamite Duke"},
        {"dyndukea",      "Dynamite Duke (Europe, 25JUL89)"},
        {"dyndukef",      "Dynamite Duke (US)"},
        {"dyndukej",      "Dynamite Duke (Japan, 03SEP89)"},
        {"dyndukeja",     "Dynamite Duke (Japan, 25JUL89)"},
        {"dyndukeu",      "Dynamite Duke (US, 25JUL89)"},
        {"dynobop",       "Dyno Bop"},
        {"dynwar",        "Dynasty Wars (USA, B-Board 89624B-?)"},
        {"dynwara",       "Dynasty Wars (USA, B-Board 88622B-3)"},
        {"dynwarj",       "Tenchi wo Kurau (Japan)"},
        {"dynwarjr",      "Tenchi wo Kurau (Japan Resale Ver.)"},
        {"dynwaru",       "Dynasty Wars (USA, set 2)"},
        {"dzigzag",       "Zig Zag (Dig Dug hardware)"},
};

const char *lookup_d(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_d(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
