#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"h89_mms",     "H-89 with MMS Equipment"},
        {"hachamf",     "Hacha Mecha Fighter"},
        {"hachamfa",    "Hacha Mecha Fighter (19th Sep. 1991, protected, set 2)"},
        {"hachamfb",    "Hacha Mecha Fighter (unprotected)"},
        {"hachamfp",    "Hacha Mecha Fighter (Location Test Prototype, 19th Sep. 1991)"},
        {"hachoo",      "Hachoo!"},
        {"hachooa",     "Hachoo! (World, set 2)"},
        {"hachooj",     "Hachoo! (Japan)"},
        {"hal21",       "HAL21"},
        {"hal21j",      "HAL21 (Japan)"},
        {"halfway",     "Halfway To Hell: Progear Red Label (2016-1-17 Red label ver)"},
        {"halley87",    "Halley's Comet '87"},
        {"halleycj",    "Halley's Comet (Japan set 2)"},
        {"halleys",     "Halley's Comet (US)"},
        {"halleysc",    "Halley's Comet (Japan set 1)"},
        {"halleysc87",  "Halley's Comet '87"},
        {"halleyscj",   "Halley's Comet (Japan, rev 1)"},
        {"halleyscja",  "Halley's Comet (Japan)"},
        {"halleyscjp",  "Halley's Comet (Japan, prototype)"},
        {"hamaway",     "Hammer Away (Japan, prototype)"},
        {"hamboy",      "Hammer Boy"},
        {"hammer",      "Hammer"},
        {"hanaawas",    "Hana Awase (Flower Matching)"},
        {"hanagumi",    "Hanagumi Taisen Columns - Sakura Wars"},
        {"hanakanz",    "Hanakanzashi (Japan)"},
        {"hanamai",     "Hana no Mai (Japan)"},
        {"hanamomb",    "Mahjong Hana no Momoko gumi (Japan 881125)"},
        {"hanamomo",    "Mahjong Hana no Momoko gumi (Japan 881201)"},
        {"hanaoji",     "Hana to Ojisan [BET] (Japan 911209)"},
        {"hanaroku",    "Hanaroku"},
        {"hanayara",    "Hana wo Yaraneba! (Japan)"},
        {"hangly",      "Hangly-Man (set 1)"},
        {"hangly2",     "Hangly-Man (set 2)"},
        {"hangly3",     "Hangly-Man (set 3)"},
        {"hangman",     "Hangman"},
        {"hangon",      "Hang-On"},
        {"hangon1",     "Hang-On"},
        {"hangon2",     "Hang-On (Rev A, ride-on)"},
        {"hangonjr",    "Hang-On Jr."},
        {"hangonvf",    "VF (bootleg of Hang-On)"},
        {"hangplt",     "Hang Pilot (ver JAB)"},
        {"hangpltu",    "Hang Pilot (ver UAA)"},
        {"hangzo",      "Hangzo (Japan, Prototype)"},
        {"happy6",      "Huanle Liu He Yi (Happy 6-in-1) (M68K ver. V101, ARM ver. V102CN)"},
        {"happy6100cn", "Huanle Liu He Yi (Happy 6-in-1) (M68K ver. V100, ARM ver. V100CN)"},
        {"happy6100hk", "Huanle Liu He Yi (Happy 6-in-1) (M68K ver. V100HK, ARM ver. V100HK)"},
        {"happy6101",   "Huanle Liu He Yi (Happy 6-in-1) (M68K ver. V100, ARM ver. V101CN)"},
        {"hapytour",    "Happy Tour"},
        {"harddrb5",    "Hard Drivin' (cockpit, British, rev 5)"},
        {"harddrb6",    "Hard Drivin' (cockpit, British, rev 6)"},
        {"harddrc1",    "Hard Drivin' (compact, rev 1)"},
        {"harddrcb",    "Hard Drivin' (compact, British, rev 2)"},
        {"harddrcg",    "Hard Drivin' (compact, German, rev 2)"},
        {"harddrg4",    "Hard Drivin' (cockpit, German, rev 4)"},
        {"harddriv",    "Hard Drivin' (cockpit, rev 7)"},
        {"harddriv1",   "Hard Drivin' (cockpit, rev 1)"},
        {"harddriv2",   "Hard Drivin' (cockpit, rev 2)"},
        {"harddriv3",   "Hard Drivin' (cockpit, rev 3)"},
        {"harddrivb",   "Hard Drivin' (cockpit, British, rev 7)"},
        {"harddrivb5",  "Hard Drivin' (cockpit, British, rev 5)"},
        {"harddrivb6",  "Hard Drivin' (cockpit, British, rev 6)"},
        {"harddrivc",   "Hard Drivin' (compact, rev 2)"},
        {"harddrivc1",  "Hard Drivin' (compact, rev 1)"},
        {"harddrivcb",  "Hard Drivin' (compact, British, rev 2)"},
        {"harddrivcbl", "Hard Drivin' (compact, rev 2 bootleg)"},
        {"harddrivcg",  "Hard Drivin' (compact, German, rev 2)"},
        {"harddrivg",   "Hard Drivin' (cockpit, German, rev 7)"},
        {"harddrivg4",  "Hard Drivin' (cockpit, German, rev 4)"},
        {"harddrivj",   "Hard Drivin' (cockpit, Japan, rev 7)"},
        {"harddrivj6",  "Hard Drivin' (cockpit, Japan, rev 6)"},
        {"harddrj6",    "Hard Drivin' (cockpit, Japan, rev 6)"},
        {"harddrv1",    "Hard Drivin' (cockpit, rev 1)"},
        {"harddrv2",    "Hard Drivin' (cockpit, rev 2)"},
        {"harddrv3",    "Hard Drivin' (cockpit, rev 3)"},
        {"harddrvb",    "Hard Drivin' (cockpit, British, rev 7)"},
        {"harddrvc",    "Hard Drivin' (compact, rev 2)"},
        {"harddrvg",    "Hard Drivin' (cockpit, German, rev 7)"},
        {"harddrvj",    "Hard Drivin' (cockpit, Japan, rev 7)"},
        {"harddunj",    "Hard Dunk (Japan)"},
        {"harddunk",    "Hard Dunk (World)"},
        {"harddunkj",   "Hard Dunk (Japan)"},
        {"hardhat",     "Hard Hat"},
        {"hardhea2",    "Hard Head 2 (v2.0)"},
        {"hardhea2a",   "Hard Head 2 (v2.0, Music Program v2.0)"},
        {"hardhead",    "Hard Head"},
        {"hardheadb",   "Hard Head (bootleg, set 1)"},
        {"hardheadb3",  "Hard Head (bootleg, set 3)"},
        {"hardhedb",    "Hard Head (bootleg)"},
        {"hardyard",    "Hard Yardage (v1.20)"},
        {"hardyard10",  "Hard Yardage (v1.00)"},
        {"hardyard11",  "Hard Yardage (v1.10)"},
        {"hardyd10",    "Hard Yardage (v1.00)"},
        {"harem",       "Harem"},
        {"haremchl",    "Harem Challenge"},
        {"harley",      "Harley-Davidson and L.A. Riders (Export, Revision B)"},
        {"harleya",     "Harley-Davidson and L.A. Riders (Export, Revision A)"},
        {"hasamu",      "Hasamu (Japan)"},
        {"hatena",      "Adventure Quiz 2 Hatena Hatena no Dai-Bouken (Japan)"},
        {"hatris",      "Hatris (Japan)"},
        {"hatrisj",     "Hatris (Japan)"},
        {"hatrisp",     "Hatris (show version)"},
        {"hattrick",    "Hat Trick"},
        {"hayaosi1",    "Hayaoshi Quiz Ouza Ketteisen"},
        {"hayaosi2",    "Hayaoshi Quiz Grand Champion Taikai"},
        {"hayaosi3",    "Hayaoshi Quiz Nettou Namahousou (ver 1.5)"},
        {"hayaosi3a",   "Hayaoshi Quiz Nettou Namahousou (ver 1.2)"},
        {"hbarrel",     "Heavy Barrel (US)"},
        {"hbarrelu",    "Heavy Barrel (US)"},
        {"hbarrelw",    "Heavy Barrel (World)"},
        {"hcastle",     "Haunted Castle (version M)"},
        {"hcastlea",    "Haunted Castle (set 2)"},
        {"hcastlee",    "Haunted Castle (version E)"},
        {"hcastlej",    "Akuma-Jou Dracula (Japan version P)"},
        {"hcastlek",    "Haunted Castle (version K)"},
        {"hcastleo",    "Haunted Castle (version K)"},
        {"hcastljo",    "Akuma-Jou Dracula (Japan version N)"},
        {"hcrash",      "Hyper Crash (version D)"},
        {"hcrashc",     "Hyper Crash (version C)"},
        {"hdrivaip",    "Hard Drivin's Airborne (prototype, early rev)"},
        {"hdrivair",    "Hard Drivin's Airborne (prototype)"},
        {"hdrivairp",   "Hard Drivin's Airborne (prototype, early rev)"},
        {"headon",      "Head On (2 players)"},
        {"headon1",     "Head On (1 player)"},
        {"headon2",     "Head On 2"},
        {"headon2s",    "Head On 2 (Sidam bootleg)"},
        {"headonb",     "Head On (1 player)"},
        {"headonch",    "Head On Channel (Japan, prototype)"},
        {"headoni",     "Head On (Irem, M-15 Hardware)"},
        {"headonmz",    "Head On (bootleg, alt maze)"},
        {"headonn",     "Head On N"},
        {"headons",     "Head On (Sidam bootleg, set 1)"},
        {"headonsa",    "Head On (Sidam bootleg, set 2)"},
        {"heartatk",    "Heart Attack"},
        {"heatbrl",     "Heated Barrel (World)"},
        {"heatbrl2",    "Heated Barrel (World version 2)"},
        {"heatbrl3",    "Heated Barrel (World version ?)"},
        {"heatbrle",    "Heated Barrel (Electronic Devices license)"},
        {"heatbrlo",    "Heated Barrel (World old version)"},
        {"heatbrlu",    "Heated Barrel (US)"},
        {"heatof11",    "Heat of Eleven '98 (ver EAA)"},
        {"heberpop",    "Hebereke no Popoon (Japan)"},
        {"hedpanic",    "Head Panic (ver. 0117, 17-01-2000)"},
        {"hedpanica",   "Head Panic (ver. 0702, 02/07/1999)"},
        {"hedpanicf",   "Head Panic (ver. 0315, 15-03-2000)"},
        {"hedpanico",   "Head Panic (ver. 0615, 15-06-1999)"},
        {"heiankyo",    "Heiankyo Alien"},
        {"helifira",    "HeliFire (set 2)"},
        {"helifire",    "HeliFire (set 1)"},
        {"helifirea",   "HeliFire (set 2)"},
        {"hellfir1",    "Hellfire (1P Ver.)"},
        {"hellfire",    "Hellfire"},
        {"hellfire1",   "Hellfire (1P set)"},
        {"hellfire1a",  "Hellfire (1P set, older)"},
        {"hellfire2",   "Hellfire (2P Ver., first edition)"},
        {"hellfire2a",  "Hellfire (2P set, older)"},
        {"hellfire3",   "Hellfire (1P Ver., alt)"},
        {"hellngt",     "Hell Night (ver EAA)"},
        {"herbiedk",    "Herbie at the Olympics (DK conversion)"},
        {"hero",        "Hero"},
        {"herodk",      "Hero in the Castle of Doom (DK conversion)"},
        {"herodku",     "Hero in the Castle of Doom (DK conversion not encrypted)"},
        {"heuksun",     "Heuk Sun Baek Sa (Korea)"},
        {"hexa",        "Hexa"},
        {"hexion",      "Hexion (Japan)"},
        {"hexionb",     "Hexion (Asia ver AAA, bootleg)"},
        {"hexpool",     "Hex Pool (Shinkai)"},
        {"hexpoola",    "Hex Pool (Senko)"},
        {"hginga",      "Hanafuda Hana Ginga"},
        {"hgkairak",    "Taisen Hot Gimmick Kairakuten (Japan)"},
        {"hgokou",      "Hanafuda Hana Gokou (Japan)"},
        {"hharry",      "Hammerin' Harry (World)"},
        {"hharryb",     "Hammerin' Harry (World, M84 hardware bootleg)"},
        {"hharryu",     "Hammerin' Harry (US)"},
        {"hidctch2",    "Hidden Catch 2 (pcb ver 3.03) (Kor/Eng) (AT89c52 protected)"},
        {"hidctch2a",   "Hidden Catch 2 (pcb ver 1.00) (Kor/Eng/Jpn/Chi)"},
        {"hidctch3",    "Hidden Catch 3 (ver 1.00 / pcb ver 3.05)"},
        {"hidnc2k",     "Hidden Catch 2000 (AT89c52 protected)"},
        {"hidnctch",    "Hidden Catch"},
        {"hidnctcha",   "Hidden Catch (World) / Tul Lin Gu Lim Chat Ki '98 (Korea) (pcb ver 3.02)"},
        {"higemaru",    "Pirate Ship Higemaru"},
        {"highspla",    "Space Fever High Splitter (set 2)"},
        {"highsplt",    "Space Fever High Splitter (set 1)"},
        {"highsplta",   "SF-HiSplitter (set 2)"},
        {"highspltb",   "SF-HiSplitter (alt sound)"},
        {"hiimpact",    "High Impact Football (rev LA3 12-27-90)"},
        {"hiimpact1",   "High Impact Football (rev LA1 12/16/90)"},
        {"hiimpact2",   "High Impact Football (rev LA2 12/26/90)"},
        {"hiimpact3",   "High Impact Football (rev LA3 12/27/90)"},
        {"hiimpact4",   "High Impact Football (rev LA4 02/04/91)"},
        {"hiimpactp",   "High Impact Football (prototype, revision0 proto 8.6 12/09/90)"},
        {"himesiki",    "Himeshikibu (Japan)"},
        {"hipai",       "Hi Pai Paradise"},
        {"hipoly",      "Hipoly (bootleg of Hyper Olympic)"},
        {"hippodrm",    "Hippodrome (US)"},
        {"hiryuken",    "Hokuha Syourin Hiryu no Ken"},
        {"hishouza",    "Hishou Zame (Japan)"},
        {"hishouzab",   "Hishou Zame (Japan, bootleg)"},
        {"histryma",    "The History of Martial Arts"},
        {"hitice",      "Hit the Ice (US)"},
        {"hiticej",     "Hit the Ice (Japan)"},
        {"hiticerb",    "Hit the Ice (US, with riser board)"},
        {"hitme",       "Hit Me"},
        {"hitnmis2",    "Hit 'n Miss (version 2.0)"},
        {"hitnmiss",    "Hit 'n Miss (version 3.0)"},
        {"hitnmiss2",   "Hit 'n Miss (version 2.0)"},
        {"hjingi",      "Hana Jingi (Japan, Bet)"},
        {"hkagerou",    "Hana Kagerou [BET] (Japan)"},
        {"hmcompm2",    "hiphopmania complete MIX 2 (ver UA-A)"},
        {"hmcompmx",    "hiphopmania complete MIX (ver UA-B)"},
        {"hmgeo",       "Heavy Metal: Geomatrix (Rev B)"},
        {"hnageman",    "AV Hanafuda Hana no Ageman (Japan 900716)"},
        {"hnayayoi",    "Hana Yayoi (Japan)"},
        {"hncholms",    "Hunchback Olympic (Scramble hardware)"},
        {"hnfubuki",    "Hana Fubuki [BET] (Japan)"},
        {"hngmnjpm",    "Hangman (JPM)"},
        {"hngmnjpmd",   "Hangman (JPM) (Protocol)"},
        {"hnkochou",    "Hana Kochou [BET] (Japan)"},
        {"hnoridur",    "Hana Oriduru (Japan)"},
        {"hnxmasev",    "AV Hanafuda Hana no Christmas Eve (Japan 901204)"},
        {"hoccer",      "Hoccer (set 1)"},
        {"hoccer2",     "Hoccer (set 2)"},
        {"hocrash",     "Crash (bootleg of Head On)"},
        {"hogalley",    "Vs. Hogan's Alley"},
        {"holeland",    "Hole Land"},
        {"holeland2",   "Hole Land (Spain)"},
        {"holo",        "Holosseum"},
        {"homerun",     "Moero Pro Yakyuu Homerun"},
        {"homo",        "Homo"},
        {"honeydol",    "Honey Doll"},
        {"hook",        "Hook (World)"},
        {"hookj",       "Hook (Japan)"},
        {"hooku",       "Hook (US)"},
        {"hoops95",     "Hoops (Europe/Asia 1.7)"},
        {"hoops96",     "Hoops '96 (Europe/Asia 2.0)"},
        {"hopmappy",    "Hopping Mappy"},
        {"hopprobo",    "Hopper Robo"},
        {"horekid",     "Kid no Hore Hore Daisakusen"},
        {"horekidb",    "Kid no Hore Hore Daisakusen (bootleg)"},
        {"horekidb2",   "Kid no Hore Hore Daisakusen (bootleg set 2)"},
        {"horizon",     "Horizon"},
        {"horshoes",    "American Horseshoes (US)"},
        {"hotblock",    "Hot Blocks - Tetrix II (set 1)"},
        {"hotblocka",   "Hot Blocks - Tetrix II (set 2)"},
        {"hotblockb",   "Hot Blocks - Tetrix II (set 3)"},
        {"hotbody",     "Hot Body I"},
        {"hotbubl",     "Hot Bubble (Korea, with adult pictures)"},
        {"hotbubla",    "Hot Bubble (Korea)"},
        {"hotchase",    "Hot Chase"},
        {"hotchasea",   "Hot Chase (set 2)"},
        {"hotd",        "The House of the Dead (Revision A)"},
        {"hotd2",       "The House of the Dead 2 (USA)"},
        {"hotd2e",      "The House of the Dead 2 (Export)"},
        {"hotd2o",      "The House of the Dead 2"},
        {"hotd2p",      "The House of the Dead 2 (prototype)"},
        {"hotd3",       "The House of the Dead III (GDX-0001)"},
        {"hotdebut",    "Quiz de Idol! Hot Debut (Japan)"},
        {"hotdo",       "The House of the Dead"},
        {"hotdogst",    "Hotdog Storm"},
        {"hotdp",       "The House of the Dead (prototype)"},
        {"hotgm4ev",    "Taisen Hot Gimmick 4 Ever (Japan)"},
        {"hotgmck",     "Taisen Hot Gimmick (Japan)"},
        {"hotgmck3",    "Taisen Hot Gimmick 3 Digital Surfing (Japan)"},
        {"hotgmcki",    "Mahjong Hot Gimmick Integral (Japan)"},
        {"hotmemry",    "Hot Memory (V1.2, Germany, 12/28/94)"},
        {"hotmemry11",  "Hot Memory (V1.1, Germany, 11/30/94)"},
        {"hotmind",     "Hot Mind (Hard Times hardware)"},
        {"hotminda",    "Hot Mind (adjustable prize)"},
        {"hotnight",    "Hot Night"},
        {"hotpinbl",    "Hot Pinball"},
        {"hotrod",      "Hot Rod (turbo 3 player)"},
        {"hotroda",     "Hot Rod (World, 3 Players, Turbo set 2, Floppy Based)"},
        {"hotrodj",     "Hot Rod (Japan, 4 Players, Floppy Based, Rev C)"},
        {"hotrodja",    "Hot Rod (Japan, 4 Players, Floppy Based, Rev B)"},
        {"hotshock",    "Hot Shocker"},
        {"hotshockb",   "Hot Shocker (early revision?)"},
        {"hotsmash",    "Hot Smash"},
        {"hourouki",    "Mahjong Hourouki Part 1 - Seisyun Hen (Japan)"},
        {"housemn2",    "House Mannequin Roppongi Live hen (Japan 870418)"},
        {"housemnq",    "House Mannequin (Japan 870217)"},
        {"hp9816a",     "HP 9816A"},
        {"hparadis",    "Super Hana Paradise (Japan)"},
        {"hpolym84",    "Hyper Olympic '84"},
        {"hpuncher",    "Hard Puncher (Japan)"},
        {"hpyagu98",    "Hanguk Pro Yagu 98"},
        {"hrdtimes",    "Hard Times"},
        {"hrdtimesa",   "Hard Times (set 2)"},
        {"hsf2",        "Hyper Street Fighter II: The Anniversary Edition (USA 040202)"},
        {"hsf2a",       "Hyper Street Fighter II: The Anniversary Edition (Asia 040202)"},
        {"hsf2d",       "Hyper Street Fighter II: The Anniversary Edition (Asia 040202 Phoenix Edition) (bootleg)"},
        {"hsf2da",      "Hyper Street Fighter II: The Anniversary Edition (Asia 040202 alt Phoenix Edition) (bootleg)"},
        {"hsf2j",       "Hyper Street Fighter II: The Anniversary Edition (Japan 040202)"},
        {"hsf2j1",      "Hyper Street Fighter II: The Anniversary Edition (Japan 031222)"},
        {"hshavoc",     "High Seas Havoc"},
        {"hstenn10",    "Hot Shots Tennis (V1.0)"},
        {"hstennis",    "Hot Shots Tennis (V1.1)"},
        {"hstennis10",  "Hot Shots Tennis (V1.0)"},
        {"htchctch",    "Hatch Catch"},
        {"htengoku",    "Hanafuda Hana Tengoku (Japan)"},
        {"hthero",      "Hat Trick Hero (Japan)"},
        {"hthero93",    "Hat Trick Hero '93 (Japan)"},
        {"hthero93u",   "Hat Trick Hero '93 (Ver 1.0A 1993/02/28)"},
        {"hthero94",    "Hat Trick Hero '94 (Ver 2.2A 1994/05/26)"},
        {"hthero95",    "Hat Trick Hero '95 (Japan)"},
        {"hthero95a",   "Hat Trick Hero '95 (Ver 2.6Asia 1994/11/17)"},
        {"hthero95u",   "Hat Trick Hero '95 (Ver 2.5A 1994/11/03)"},
        {"htheroj",     "Hat Trick Hero (Japan)"},
        {"htherou",     "Hat Trick Hero (US)"},
        {"hthro95u",    "Hat Trick Hero '95 (US)"},
        {"hunchbak",    "Hunchback"},
        {"hunchbaka",   "Hunchback (set 2)"},
        {"hunchbgb",    "Hunchback (FAR S.A. bootleg on Galaxian hardware)"},
        {"hunchbkd",    "Hunchback (DK conversion)"},
        {"hunchbkg",    "Hunchback (Galaxian hardware)"},
        {"hunchbks",    "Hunchback (Scramble hardware)"},
        {"hunchbks2",   "Hunchback (Scramble hardware, bootleg)"},
        {"huncholy",    "Hunchback Olympic"},
        {"hustle",      "Hustle"},
        {"hustler",     "Video Hustler"},
        {"hustlerb",    "Video Hustler (bootleg)"},
        {"hustlerb2",   "Fatsy Gambler (bootleg of Video Hustler)"},
        {"hustlerb3",   "Video Pool (bootleg of Video Hustler)"},
        {"hustlerb4",   "Video Hustler (bootleg, set 2)"},
        {"hustlerb5",   "Video Hustler (bootleg, set 3)"},
        {"hustlerb6",   "Video Hustler (bootleg, set 4)"},
        {"hustlerb7",   "Video Hustler (bootleg, set 5)"},
        {"hustlerd",    "Video Hustler (Dynamo Games)"},
        {"hvnsgate",    "Heaven's Gate"},
        {"hvoltage",    "High Voltage"},
        {"hvymetal",    "Heavy Metal"},
        {"hvysmsh",     "Heavy Smash (Europe version -2)"},
        {"hvysmsha",    "Heavy Smash (Asia version -4)"},
        {"hvysmshj",    "Heavy Smash (Japan version -2)"},
        {"hvyunit",     "Heavy Unit (World)"},
        {"hvyunitj",    "Heavy Unit (Japan, newer)"},
        {"hvyunitja",   "Heavy Unit (Japan, alternate ROM format)"},
        {"hvyunitjo",   "Heavy Unit (Japan, older)"},
        {"hvyunito",    "Heavy Unit (Japan, Older)"},
        {"hvyunitu",    "Heavy Unit -U.S.A. Version- (US)"},
        {"hwchamp",     "Heavyweight Champ"},
        {"hwchampa",    "Heavyweight Champ (set 2)"},
        {"hwchampj",    "Heavyweight Champ (Japan) (FD1094 317-0046)"},
        {"hwchampjd",   "Heavyweight Champ (Japan) (bootleg of FD1094 317-0046 set)"},
        {"hwrace",      "High Way Race"},
        {"hydra",       "Hydra"},
        {"hydrap",      "Hydra (prototype 5-14-90)"},
        {"hydrap2",     "Hydra (prototype 5-25-90)"},
        {"hyhoo",       "Taisen Quiz HYHOO (Japan)"},
        {"hyhoo2",      "Taisen Quiz HYHOO 2 (Japan)"},
        {"hyouban",     "Mahjong Hyouban Musume [BET] (Japan)"},
        {"hyperath",    "Hyper Athlete (GV021 Japan 1.00)"},
        {"hyperbbc",    "Hyper Bishi Bashi Champ (GX908 1999/08/24 VER. JAA)"},
        {"hyperbbck",   "Hyper Bishi Bashi Champ (GX908 1999/08/24 VER. KAA)"},
        {"hypernoid",   "Hypernoid (2021-11-28)"},
        {"hyperpac",    "Hyper Pacman"},
        {"hyperpacb",   "Hyper Pacman (bootleg)"},
        {"hyperpcb",    "Hyper Pacman (bootleg)"},
        {"hyperspc",    "Hyperspace (bootleg of Asteroids)"},
        {"hyperspt",    "Hyper Sports"},
        {"hypersptb",   "Hyper Sports (bootleg)"},
        {"hyprdelj",    "Hyper Duel (Japan)"},
        {"hyprdriv",    "Hyperdrive (ver 1.40, Oct 23 1998)"},
        {"hyprduel",    "Hyper Duel (World)"},
        {"hyprduel2",   "Hyper Duel (Japan set 2)"},
        {"hypreac2",    "Mahjong Hyper Reaction 2 (Japan)"},
        {"hypreact",    "Mahjong Hyper Reaction (Japan)"},
        {"hyprnoid",    "Hypernoid"},
        {"hyprolyb",    "Hyper Olympic (bootleg)"},
        {"hyprolym",    "Hyper Olympic"},
        {"hyprolyma",   "Hyper Olympic (bugfixed)"},
        {"hyprolymb",   "Hyper Olympic (bootleg, set 1)"},
        {"hyprolymba",  "Hyper Olympic (bootleg, set 2)"},
        {"hypsptsp",    "Hyper Sports Special (Japan)"},
};

const char *lookup_h(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_h(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
