#include "lookup.h"
#include <string.h>

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"f15se",       "F-15 Strike Eagle (rev. 2.2 02/25/91, 29K ver. 3.1f)"},
        {"f15se21",     "F-15 Strike Eagle (rev. 2.1 02/04/91)"},
        {"f15se22",     "F-15 Strike Eagle (rev. 2.2 02/25/91, 29K ver. 2.2a)"},
        {"f1dream",     "F-1 Dream"},
        {"f1dreamb",    "F-1 Dream (bootleg)"},
        {"f1dreamba",   "F-1 Dream (bootleg, set 2)"},
        {"f1en",        "F1 Exhaust Note"},
        {"f1enj",       "F1 Exhaust Note (Japan, Rev A)"},
        {"f1enu",       "F1 Exhaust Note (US, Rev A)"},
        {"f1gp",        "F-1 Grand Prix"},
        {"f1gp2",       "F-1 Grand Prix Part II"},
        {"f1gpa",       "F-1 Grand Prix (set 2)"},
        {"f1gpstar",    "Grand Prix Star"},
        {"f1gpstar2",   "Grand Prix Star (ver 2.0)"},
        {"f1gpstar3",   "Grand Prix Star (ver 3.0)"},
        {"f1gpstr2",    "F-1 Grand Prix Star II"},
        {"f1lap",       "F1 Super Lap (World)"},
        {"f1lapj",      "F1 Super Lap (Japan)"},
        {"f1lapt",      "F1 Super Lap (World, Unprotected)"},
        {"f1superb",    "F1 Super Battle"},
        {"f355",        "Ferrari F355 Challenge (deluxe, no link)"},
        {"f355p",       "Ferrari F355 Challenge (private show version)"},
        {"f355twin",    "Ferrari F355 Challenge (twin/deluxe)"},
        {"f355twinp",   "Ferrari F355 Challenge (twin/deluxe, preview)"},
        {"f355twn2",    "Ferrari F355 Challenge 2 - International Course Edition (twin/deluxe)"},
        {"fa",          "F-A (Japan)"},
        {"faceoff",     "Face Off (Japan)"},
        {"failgate",    "Fail Gate"},
        {"falcon",      "Falcon"},
        {"falconz",     "Falcon (bootleg of Phoenix) (Z80 CPU)"},
        {"famibox",     "FamicomBox"},
        {"famistat",    "FamicomStation"},
        {"fantasia",    "Fantasia"},
        {"fantasiaa",   "Fantasia (940307 PCB)"},
        {"fantasiab",   "Fantasia (940429 PCB, set 2)"},
        {"fantasian",   "Fantasia (940803 PCB)"},
        {"fantastc",    "Fantastic (Galaga conversion on Galaxian hardware)"},
        {"fantasy",     "Fantasy (US)"},
        {"fantasyj",    "Fantasy (Japan)"},
        {"fantazia",    "Fantazia"},
        {"fantjour",    "Fantastic Journey"},
        {"fantland",    "Fantasy Land"},
        {"fantlanda",   "Fantasy Land (set 2)"},
        {"fantsia2",    "Fantasia II"},
        {"fantsia2a",   "Fantasia II (Less Explicit)"},
        {"fantsia2n",   "Fantasia II (1998)"},
        {"fantsy95",    "Fantasy '95"},
        {"fantzn2",     "Fantasy Zone 2"},
        {"fantzn2x",    "Fantasy Zone II - The Tears of Opa-Opa (System 16C version)"},
        {"fantzn2xp",   "Fantasy Zone II - The Tears of Opa-Opa (System 16C version, prototype)"},
        {"fantzone",    "Fantasy Zone (Japan New Ver.)"},
        {"fantzone1",   "Fantasy Zone (unprotected)"},
        {"fantzonee",   "Fantasy Zone (FD1089B 317-0016)"},
        {"fantzonep",   "Fantasy Zone (317-5000)"},
        {"fantzonepr",  "Fantasy Zone (prototype)"},
        {"fantzoneta",  "Fantasy Zone (Time Attack, bootleg)"},
        {"fantzono",    "Fantasy Zone (Old Ver.)"},
        {"farmer",      "Farmers Rebellion"},
        {"farwest",     "Far West"},
        {"fastfred",    "Fast Freddie"},
        {"fastlane",    "Fast Lane"},
        {"fatfursa",    "Fatal Fury Special / Garou Densetsu Special (set 2)"},
        {"fatfursp",    "Fatal Fury Special / Garou Densetsu Special (set 1)"},
        {"fatfurspa",   "Fatal Fury Special / Garou Densetsu Special (NGM-058 ~ NGH-058, set 2)"},
        {"fatfury1",    "Fatal Fury - King of Fighters / Garou Densetsu - Shukumei no Tatakai"},
        {"fatfury2",    "Fatal Fury 2 / Garou Densetsu 2 - Arata-naru Tatakai"},
        {"fatfury3",    "Fatal Fury 3 - Road to the Final Victory / Garou Densetsu 3 - Haruka-naru Tatakai"},
        {"fax",         "Fax"},
        {"fax2",        "FAX 2"},
        {"fball",       "Fire Ball (FM Work)"},
        {"fbcrazy",     "Football Crazy (Video Quiz)"},
        {"fbfrenzy",    "Football Frenzy"},
        {"fcombat",     "Field Combat"},
        {"fcrash",      "Final Crash (bootleg of Final Fight)"},
        {"fenixn",      "Fenix (Niemer bootleg of Phoenix)"},
        {"feversos",    "Fever SOS (World, 98/09/25 VER)"},
        {"ffantasa",    "Fighting Fantasy (Japan)"},
        {"ffantasy",    "Fighting Fantasy (Japan revision 2)"},
        {"ffantasya",   "Fighting Fantasy (Japan)"},
        {"ffantasyb",   "Fighting Fantasy (Japan revision ?)"},
        {"ffantasyj",   "Fighting Fantasy (Japan, revision 2)"},
        {"ffight",      "Final Fight (World)"},
        {"ffight2b",    "Final Fight 2 (SNES bootleg)"},
        {"ffighta",     "Final Fight (World, set 2)"},
        {"ffightae",    "Final Fight 30th Anniversary Edition"},
        {"ffightbl",    "Final Fight (bootleg)"},
        {"ffightbla",   "Final Fight (bootleg on Final Crash PCB)"},
        {"ffightblb",   "Final Fight (bootleg with single OKI)"},
        {"ffightj",     "Final Fight (Japan set 1)"},
        {"ffightj1",    "Final Fight (Japan set 2)"},
        {"ffightj2",    "Final Fight (Japan 900305)"},
        {"ffightj3",    "Final Fight (Japan 900405)"},
        {"ffightj4",    "Final Fight (Japan 900613)"},
        {"ffightjh",    "Street Smart / Final Fight (Japan, hack)"},
        {"ffightu",     "Final Fight (US 900112)"},
        {"ffightu1",    "Final Fight (USA, set 2)"},
        {"ffightua",    "Final Fight (USA 900112)"},
        {"ffightub",    "Final Fight (USA 900424)"},
        {"ffightuc",    "Final Fight (USA 900613)"},
        {"ffreveng",    "Final Fight Revenge"},
        {"fghtatck",    "Fighter and Attacker (US)"},
        {"fghtbskt",    "Fighting Basketball"},
        {"fghtfeva",    "Fight Fever (set 2)"},
        {"fghthist",    "Fighters History (World ver 43-07)"},
        {"fghthista",   "Fighters History (US ver 42-05, alternate hardware)"},
        {"fghthistb",   "Fighter's History (World ver 43-05, DE-0380-2 PCB)"},
        {"fghthistj",   "Fighters History (Japan ver 42-03)"},
        {"fghthistja",  "Fighter's History (Japan ver 41-05, DE-0380-2 PCB)"},
        {"fghthistjb",  "Fighter's History (Japan ver 41-04, DE-0380-1 PCB)"},
        {"fghthistu",   "Fighters History (US ver 42-03)"},
        {"fghthistua",  "Fighter's History (US ver 42-06, DE-0395-1 PCB)"},
        {"fghthistub",  "Fighter's History (US ver 42-05, DE-0395-1 PCB)"},
        {"fghthistuc",  "Fighter's History (US ver 42-03, DE-0380-2 PCB)"},
        {"fgtlayer",    "Fighting Layer (FTL1-VER.A)"},
        {"fgtlayerj",   "Fighting Layer (Japan, FTL0/VER.A)"},
        {"fhawk",       "Fighting Hawk (World)"},
        {"fhawkj",      "Fighting Hawk (Japan)"},
        {"fhboxers",    "Funky Head Boxers"},
        {"fieldday",    "Field Day"},
        {"fightfev",    "Fight Fever (set 1)"},
        {"fightfeva",   "Fight Fever / Wang Jung Wang (set 2)"},
        {"fightfva",    "Fight Fever (set 2)"},
        {"fightrol",    "Fighting Roller"},
        {"filetto",     "Filetto (v1.05 901009)"},
        {"finalap2",    "Final Lap 2"},
        {"finalap2j",   "Final Lap 2 (Japan)"},
        {"finalap3",    "Final Lap 3 (Japan set 1)"},
        {"finalap3a",   "Final Lap 3 (World, set 2)"},
        {"finalap3bl",  "Final Lap 3 (bootleg)"},
        {"finalap3j",   "Final Lap 3 (Japan)"},
        {"finalap3jc",  "Final Lap 3 (Japan, Rev C)"},
        {"finalapc",    "Final Lap (Rev C)"},
        {"finalapd",    "Final Lap (Rev D)"},
        {"finalapr",    "Final Lap R (Rev. B)"},
        {"finalapr1",   "Final Lap R"},
        {"finalaprj",   "Final Lap R (Japan Rev. C)"},
        {"finalaprj1",  "Final Lap R (Japan Rev. B)"},
        {"finalb",      "Final Blow (World)"},
        {"finalbj",     "Final Blow (Japan)"},
        {"finalbny",    "Mahjong Final Bunny [BET] (Japan)"},
        {"finalbu",     "Final Blow (US, rev 1)"},
        {"finalizb",    "Finalizer - Super Transformation (bootleg)"},
        {"finalizr",    "Finalizer - Super Transformation"},
        {"finalizra",   "Finalizer - Super Transformation (set 2)"},
        {"finalizrb",   "Finalizer - Super Transformation (bootleg)"},
        {"finallap",    "Final Lap (Rev E)"},
        {"finallapc",   "Final Lap (Rev C)"},
        {"finallapd",   "Final Lap (Rev D)"},
        {"finallapjb",  "Final Lap (Japan, Rev B)"},
        {"finallapjc",  "Final Lap (Japan, Rev C)"},
        {"finalp2j",    "Final Lap 2 (Japan)"},
        {"finalp3a",    "Final Lap 3 (World)"},
        {"finalttr",    "Final Tetris"},
        {"findlove",    "Find Love"},
        {"findout",     "Find Out"},
        {"findouta",    "Find Out (Version 4.04, set 2)"},
        {"finehour",    "Finest Hour (Japan)"},
        {"finger",      "Finger (bootleg of Stinger)"},
        {"finlapjb",    "Final Lap (Japan - Rev B)"},
        {"finlapjc",    "Final Lap (Japan - Rev C)"},
        {"finlarch",    "Final Arch (Japan)"},
        {"firebarr",    "Fire Barrel (Japan)"},
        {"firebatl",    "Fire Battle"},
        {"firebeas",    "Firebeast (prototype)"},
        {"firefox",     "Fire Fox (set 1)"},
        {"firefoxa",    "Fire Fox (set 2)"},
        {"firehawk",    "Fire Hawk"},
        {"fireone",     "Fire One"},
        {"fireshrk",    "Fire Shark"},
        {"fireshrka",   "Fire Shark (earlier)"},
        {"fireshrkd",   "Fire Shark (Korea, set 1, easier)"},
        {"fireshrkdh",  "Fire Shark (Korea, set 2, harder)"},
        {"firetpbl",    "Fire Trap (Japan bootleg)"},
        {"firetrap",    "Fire Trap (US)"},
        {"firetrapa",   "Fire Trap (US)"},
        {"firetrapbl",  "Fire Trap (Japan bootleg)"},
        {"firetrapj",   "Fire Trap (Japan)"},
        {"firetrk",     "Fire Truck"},
        {"firetrka",    "Fire Truck / Smokey Joe (ROM version)"},
        {"fishfren",    "Fishin' Frenzy (prototype)"},
        {"fitegol2",    "Fighting Golf (US)"},
        {"fitegolf",    "Fighting Golf (World[Q])"},
        {"fitegolfu",   "Lee Trevino's Fighting Golf (US, Ver 2, set 1)"},
        {"fitegolfua",  "Lee Trevino's Fighting Golf (US, Ver 2, set 2)"},
        {"fitfight",    "Fit of Fighting"},
        {"fitter",      "Fitter"},
        {"fitterbl",    "Fitter (bootleg of Round-Up)"},
        {"fiveside",    "Five a Side Soccer (ver UAA)"},
        {"fixeighb",    "FixEight (Bootleg)"},
        {"fixeight",    "FixEight"},
        {"fixeighta",   "FixEight (Southeast Asia)"},
        {"fixeightat",  "FixEight (Southeast Asia, Taito license)"},
        {"fixeightbl",  "FixEight (Korea, bootleg)"},
        {"fixeighth",   "FixEight (Hong Kong)"},
        {"fixeightht",  "FixEight (Hong Kong, Taito license)"},
        {"fixeightj",   "FixEight - Jigoku no Eiyuu Densetsu (Japan)"},
        {"fixeightjt",  "FixEight - Jigoku no Eiyuu Densetsu (Japan, Taito license)"},
        {"fixeightk",   "FixEight (Korea)"},
        {"fixeightkt",  "FixEight (Korea, Taito license)"},
        {"fixeightt",   "FixEight (Europe, Taito license)"},
        {"fixeighttw",  "FixEight (Taiwan)"},
        {"fixeighttwt", "FixEight (Taiwan, Taito license)"},
        {"fixeightu",   "FixEight (USA)"},
        {"fixeightut",  "FixEight (USA, Taito license)"},
        {"fjbuster",    "Fujiyama Buster (Japan)"},
        {"flagrall",    "'96 Flag Rally"},
        {"flashgal",    "Flashgal"},
        {"flashgala",   "Flashgal (set 2)"},
        {"flashgalk",   "Flashgal (set 1, Kyugo logo)"},
        {"flicky",      "Flicky (128k Ver.)"},
        {"flickya",     "Flicky (128k Version, 315-5051, larger ROMs)"},
        {"flickyb",     "Flicky (128k Version, 315-5051, larger ROMs, newer)"},
        {"flickyo",     "Flicky (64k Ver.)"},
        {"flickys1",    "Flicky (64k Version, 315-5051, set 2)"},
        {"flickys2",    "Flicky (128k Version, not encrypted)"},
        {"flickyup",    "Flicky (64k Version, on Up'n Down boardset, set 1)"},
        {"flickyupa",   "Flicky (64k Version, on Up'n Down boardset, set 2)"},
        {"flipjack",    "Flipper Jack"},
        {"flipshot",    "Battle Flip Shot"},
        {"flipull",     "Flipull (Japan)"},
        {"flkatck",     "Flak Attack (Japan)"},
        {"flkatcka",    "Flak Attack (Japan, PWB 450593 sub-board)"},
        {"floritas",    "Floritas (bootleg of Moon Cresta)"},
        {"floritasm",   "Floritas (Multivideo Spanish bootleg of Moon Cresta)"},
        {"flower",      "Flower"},
        {"flowerbl",    "Flower (bootleg)"},
        {"flowerj",     "Flower (Japan)"},
        {"flstory",     "The FairyLand Story"},
        {"flstoryj",    "The FairyLand Story (Japan)"},
        {"flstoryo",    "The FairyLand Story (earlier)"},
        {"flyball",     "Flyball"},
        {"flyball1",    "Flyball (rev 1)"},
        {"flyboy",      "Fly-Boy"},
        {"flyboyb",     "Fly-Boy (bootleg)"},
        {"flytiger",    "Flying Tiger"},
        {"flytigera",   "Flying Tiger (set 2)"},
        {"fmaniac2p",   "Fishing Maniac 2+"},
        {"fmaniac3",    "Fishing Maniac 3"},
        {"fncywld",     "Fancy World - Earth of Crisis"},
        {"fnkyfish",    "Funky Fish"},
        {"fnshark",     "Flyin' Shark (bootleg of Hishou Zame)"},
        {"foodf",       "Food Fight (rev 3)"},
        {"foodf1",      "Food Fight (rev 1)"},
        {"foodf2",      "Food Fight (rev 2)"},
        {"foodfc",      "Food Fight (cocktail)"},
        {"footbpow",    "Football Power (version 1.2)"},
        {"footbpow11",  "Football Power (version 1.1)"},
        {"footchmp",    "Football Champ (World)"},
        {"forcebrk",    "Force Break (bootleg)"},
        {"forgottn",    "Forgotten Worlds (US)"},
        {"forgottna",   "Forgotten Worlds (World)"},
        {"forgottnj",   "Forgotten Worlds (Japan) (English prototype)"},
        {"forgottnu",   "Forgotten Worlds (USA, B-Board 88621B-2, Rev. C)"},
        {"forgottnua",  "Forgotten Worlds (USA, B-Board 88618B-2, Rev. A)"},
        {"forgottnuaa", "Forgotten Worlds (USA, B-Board 88618B-2, Rev. AA)"},
        {"forgottnuc",  "Forgotten Worlds (USA, B-Board 88618B-2, Rev. C)"},
        {"forgottnue",  "Forgotten Worlds (USA, B-Board 88618B-2, Rev. E)"},
        {"formatz",     "Formation Z"},
        {"fort2b",      "Fortress 2 Blue Arcade (World) (ver 1.01 / pcb ver 3.05)"},
        {"fort2ba",     "Fortress 2 Blue Arcade (Korea) (ver 1.00 / pcb ver 3.05)"},
        {"fotns",       "Fist Of The North Star / Hokuto no Ken"},
        {"fourplay",    "Four Play"},
        {"fourtrax",    "Four Trax"},
        {"fourtraxa",   "Four Trax (US?, censored banners)"},
        {"fourtraxj",   "Four Trax (Japan)"},
        {"fpoint",      "Flash Point"},
        {"fpoint1",     "Flash Point (set 1, Japan) (FD1094 317-0127A)"},
        {"fpoint1d",    "Flash Point (set 1, Japan) (bootleg of FD1094 317-0127A set)"},
        {"fpointbj",    "Flash Point (Japan, bootleg)"},
        {"fpointbl",    "Flash Point (World, bootleg)"},
        {"fpointd",     "Flash Point (set 2, Japan) (bootleg of FD1094 317-0127A set)"},
        {"fredmem",     "Fred Flintstone's Memory Match (World?, Ticket version, 3/17/95)"},
        {"fredmemc",    "Fred Flintstone's Memory Match (Mandarin Chinese, 3/17/95)"},
        {"fredmemj",    "Fred Flintstone's Memory Match (Japan, High Score version, 3/20/95)"},
        {"fredmemuk",   "Fred Flintstone's Memory Match (UK, 3/17/95)"},
        {"fredmemus",   "Fred Flintstone's Memory Match (US, High Score version, 3/10/95)"},
        {"fredmesp",    "Fred Flintstone's Memory Match (Spanish, 3/17/95)"},
        {"freekckb",    "Free Kick (bootleg)"},
        {"freekick",    "Free Kick"},
        {"freekicka",   "Free Kick (NS6201-A 1987.9)"},
        {"freekickb1",  "Free Kick (bootleg set 1)"},
        {"freekickb2",  "Free Kick (bootleg set 2)"},
        {"freekickb3",  "Free Kick (bootleg set 3)"},
        {"freeze",      "Freeze"},
        {"freezeat",    "Freeze (Atari) (prototype, English voice, 96/10/25)"},
        {"freezeat2",   "Freeze (Atari) (prototype, 96/10/18)"},
        {"freezeat3",   "Freeze (Atari) (prototype, 96/10/07)"},
        {"freezeat4",   "Freeze (Atari) (prototype, 96/10/03)"},
        {"freezeat5",   "Freeze (Atari) (prototype, 96/09/20, AMOA-96)"},
        {"freezeat6",   "Freeze (Atari) (prototype, 96/09/07, Jamma-96)"},
        {"freezeatjp",  "Freeze (Atari) (prototype, Japanese voice, 96/10/25)"},
        {"frenzy",      "Frenzy"},
        {"friskyt",     "Frisky Tom (set 1)"},
        {"friskyta",    "Frisky Tom (set 2)"},
        {"friskytb",    "Frisky Tom (set 3)"},
        {"frogf",       "Frog (Falcon bootleg)"},
        {"frogfest",    "Frog Feast"},
        {"frogg",       "Frog (Galaxian hardware)"},
        {"froggeg",     "Frog (Hermatic, bootleg on Galaxian hardware from Electro Game)"},
        {"frogger",     "Frogger"},
        {"froggeram",   "Frogger (bootleg on Amigo? hardware)"},
        {"froggereb",   "Frogger - New Serie 92 (bootleg)"},
        {"froggermc",   "Frogger (Moon Cresta hardware)"},
        {"froggers",    "Frog"},
        {"froggers1",   "Frogger (Sega, set 1)"},
        {"froggers2",   "Frogger (Sega, set 2)"},
        {"froggers3",   "Frogger (Sega, set 3)"},
        {"froggert",    "Frogger (Turtles hardware)"},
        {"froggerv",    "Frogger (Videotron bootleg)"},
        {"froggervd",   "Frogger (Hermatic, bootleg on Scramble hardware from Video Dens)"},
        {"froggrmc",    "Frogger (Moon Cresta hardware)"},
        {"froggrs",     "Frogger (Coin Music, bootleg on Scramble hardware)"},
        {"frogs",       "Frogs"},
        {"frogseg1",    "Frogger (Sega set 1)"},
        {"frogseg2",    "Frogger (Sega set 2)"},
        {"froman2b",    "Idol Mahjong Final Romance 2 (CD conv)"},
        {"fromanc2",    "Taisen Idol-Mahjong Final Romance 2 (Japan)"},
        {"fromanc4",    "Taisen Mahjong FinalRomance 4 (Japan)"},
        {"fromance",    "Idol-Mahjong Final Romance (Japan)"},
        {"fromancr",    "Taisen Mahjong FinalRomance R (Japan)"},
        {"frontlin",    "Front Line"},
        {"frontlina",   "Front Line (FL, 5 PCB version)"},
        {"fround",      "The Final Round (version M)"},
        {"froundl",     "The Final Round (version L)"},
        {"fshark",      "Flying Shark (World)"},
        {"fsharkb",     "Flying Shark (World, bootleg)"},
        {"fsharkbt",    "Flying Shark (bootleg)"},
        {"fsoccer",     "Fighting Soccer (version 4)"},
        {"fsoccerb",    "Fighting Soccer (Joystick hack bootleg)"},
        {"fsoccerba",   "Fighting Soccer (Joystick hack bootleg, alt)"},
        {"fsoccerj",    "Fighting Soccer (Japan)"},
        {"fspiderb",    "Frog & Spiders (bootleg?)"},
        {"fstarfrc",    "Final Star Force (US)"},
        {"fstarfrcj",   "Final Star Force (Japan, set 1)"},
        {"fstarfrcja",  "Final Star Force (Japan, set 2)"},
        {"fstarfrcw",   "Final Star Force (World?)"},
        {"fswords",     "Fighters Swords"},
        {"ftfurspa",    "Fatal Fury Special (NGM-058)"},
        {"ftimpcta",    "Fighter's Impact Ace (JAPAN)"},
        {"ftsoccer",    "Fighting Soccer"},
        {"ftspeed",     "Faster Than Speed"},
        {"fullthrl",    "Full Throttle (Japan)"},
        {"funcube",     "Funcube (v1.5)"},
        {"funcube2",    "Funcube 2 (v1.1)"},
        {"funcube3",    "Funcube 3 (v1.1)"},
        {"funcube4",    "Funcube 4 (v1.0)"},
        {"funcube5",    "Funcube 5 (v1.0)"},
        {"funkybee",    "Funky Bee"},
        {"funkybeeb",   "Funky Bee (bootleg, harder)"},
        {"funkyfig",    "The First Funky Fighter (USA, Canada, Mexico / Japan, set 1)"},
        {"funkyfiga",   "The First Funky Fighter (USA, Canada, Mexico / Japan, set 2)"},
        {"funkyjet",    "Funky Jet"},
        {"funkyjeta",   "Funky Jet (World)"},
        {"funkyjeta2",  "Funky Jet (Korea, prototype?)"},
        {"funkyjetj",   "Funky Jet (Japan, rev 2)"},
        {"funnymou",    "Funny Mouse"},
        {"funquiz",     "Fun World Quiz (German)"},
        {"funquiza",    "Fun World Quiz (German, 12-11-1990)"},
        {"funquizb",    "Fun World Quiz (German, 27-04-1990)"},
        {"funybubl",    "Funny Bubble"},
        {"funybublc",   "Funny Bubble (Comad version)"},
        {"futari10",    "Mushihime-Sama Futari Ver 1.0 (2006/10/23 MASTER VER.)"},
        {"futari15",    "Mushihime-Sama Futari Ver 1.5 (2006/12/8.MASTER VER. 1.54.)"},
        {"futari15a",   "Mushihime-Sama Futari Ver 1.5 (2006/12/8 MASTER VER 1.54)"},
        {"futaribl",    "Mushihime-Sama Futari Black Label - Another Ver (2009/11/27 INTERNATIONAL BL)"},
        {"futariblj",   "Mushihime-Sama Futari Black Label (2007/12/11 BLACK LABEL VER)"},
        {"futflash",    "Future Flash"},
        {"futspy",      "Future Spy"},
        {"fuusenpn",    "Fuusen Pentai"},
        {"fvipers",     "Fighting Vipers (Revision D)"},
        {"fvipers2",    "Fighting Vipers 2 (Japan, Revision A)"},
        {"fvipers2o",   "Fighting Vipers 2 (Japan)"},
        {"fvipersb",    "Fighting Vipers (Revision B)"},
        {"fx",          "F-X (bootleg of S.R.D. Mission)"},
};

const char *lookup_f(const char *name) {
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_f(const char *value) {
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].value, value) == 0) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
