#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"wacko",      "Wacko"},
        {"waidrive",   "WaiWai Drive"},
        {"wakuwak7",   "Waku Waku 7"},
        {"wallc",      "Wall Crash"},
        {"wallca",     "Wall Crash (set 2)"},
        {"wallst",     "Wall Street"},
        {"wangmid",    "Wangan Midnight Maximum Tune (Rev. B) (Export) (GDX-0009B)"},
        {"wangmid2",   "Wangan Midnight Maximum Tune 2 (Export) (GDX-0015)"},
        {"wanted",     "Wanted"},
        {"warcadia",   "Waga Seishun no Arcadia"},
        {"wardner",    "Wardner (World)"},
        {"wardnerb",   "Wardner (World, bootleg)"},
        {"wardnerj",   "Wardner no Mori (Japan)"},
        {"wardnerjb",  "Wardner no Mori (Japan, bootleg)"},
        {"warfa",      "War: Final Assault (EPROM 1.9 Mar 25 1999, GUTS 1.3 Apr 20 1999, GAME Apr 20 1999)"},
        {"warfaa",     "War: Final Assault (EPROM 1.6 Jan 14 1999, GUTS 1.1 Mar 16 1999, GAME Mar 16 1999)"},
        {"warfab",     "War: Final Assault (EPROM 1.3 Apr 7 1999, GUTS 1.3 Apr 7 1999, GAME Apr 7 1999)"},
        {"warfac",     "War: Final Assault (EPROM 1.91 Apr 13 1999, GUTS 1.3 Apr 7 1999, GAME Apr 7 1999)"},
        {"wargods",    "War Gods"},
        {"wargodsa",   "War Gods (HD 08/15/1996)"},
        {"wargodsb",   "War Gods (HD 12/11/1995)"},
        {"warlord",    "Warlords"},
        {"warlords",   "Warlords"},
        {"warofbug",   "War of the Bugs or Monsterous Manouvers in a Mushroom Maze"},
        {"warofbugg",  "War of the Bugs or Monsterous Manouvers in a Mushroom Maze (German)"},
        {"warofbugu",  "War of the Bugs or Monsterous Manouvers in a Mushroom Maze (US)"},
        {"warpwar2",   "Warp Warp (Rock-ola set 2)"},
        {"warpwarp",   "Warp and Warp"},
        {"warpwarpr",  "Warp Warp (Rock-Ola set 1)"},
        {"warpwarpr2", "Warp Warp (Rock-Ola set 2)"},
        {"warpwarr",   "Warp Warp (Rock-ola set 1)"},
        {"warrior",    "Warrior"},
        {"warriorb",   "Warrior Blade - Rastan Saga Episode III (Japan)"},
        {"warzard",    "Warzard (Japan 961121)"},
        {"warzardr1",  "Warzard (Japan 961023)"},
        {"waterski",   "Water Ski"},
        {"watrball",   "Water Balls"},
        {"waverunr",   "Wave Runner (Japan, Revision A)"},
        {"waveshrk",   "Wave Shark (UAB, USA v1.04)"},
        {"wavybug",    "Wavy Bug"},
        {"wb3",        "Wonder Boy III - Monster Lair (set 1)"},
        {"wb31",       "Wonder Boy III - Monster Lair (set 1, Japan, System 16A) (FD1094 317-0084)"},
        {"wb31d",      "Wonder Boy III - Monster Lair (set 1, Japan, System 16A) (bootleg of FD1094 317-0084 set)"},
        {"wb32",       "Wonder Boy III - Monster Lair (set 2, Japan, System 16B) (FD1094 317-0085)"},
        {"wb32d",      "Wonder Boy III - Monster Lair (set 2, Japan, System 16B) (bootleg of FD1094 317-0085 set)"},
        {"wb33",       "Wonder Boy III - Monster Lair (set 3, World, System 16B) (FD1094 317-0089)"},
        {"wb33d",      "Wonder Boy III - Monster Lair (set 3, World, System 16B) (bootleg of FD1094 317-0089 set)"},
        {"wb34",       "Wonder Boy III - Monster Lair (set 4, Japan, System 16B) (FD1094 317-0087)"},
        {"wb34d",      "Wonder Boy III - Monster Lair (set 4, Japan, System 16B) (bootleg of FD1094 317-0087 set)"},
        {"wb35",       "Wonder Boy III - Monster Lair (set 5, Japan, System 16A) (FD1089A 317-0086)"},
        {"wb35a",      "Wonder Boy III - Monster Lair (set 6, System 16A, FD1089A 317-xxxx)"},
        {"wb35d",      "Wonder Boy III - Monster Lair (set 5, Japan, System 16A) (bootleg of FD1089A 317-0086 set)"},
        {"wb3a",       "Wonder Boy III - Monster Lair (set 2)"},
        {"wb3bbl",     "Wonder Boy III - Monster Lair (bootleg)"},
        {"wb3bl",      "Wonder Boy III - Monster Lair (bootleg)"},
        {"wbbc97",     "Beach Festival World Championship 1997"},
        {"wbdeluxe",   "Wonder Boy Deluxe"},
        {"wbeachvl",   "World Beach Volley"},
        {"wbeachvl2",  "World Beach Volley (set 2)"},
        {"wbeachvl3",  "World Beach Volley (set 3)"},
        {"wbeachvla",  "World Beach Volley (set 1, S87C751 audio CPU)"},
        {"wbml",       "Wonder Boy in Monster Land (Japan New Ver.)"},
        {"wbmlb",      "Wonder Boy in Monster Land"},
        {"wbmlbg",     "Wonder Boy - Monster Land (English bootleg set 2)"},
        {"wbmlbge",    "Wonder Boy - Monster Land (English bootleg set 3)"},
        {"wbmld",      "Wonder Boy - Monster Land (decrypted bootleg of Japan New Ver., MC-8123, 317-0043)"},
        {"wbmlh",      "Wonder Boy - Monster Land (English, difficulty hack)"},
        {"wbmlj",      "Wonder Boy in Monster Land (Japan set 1)"},
        {"wbmlj2",     "Wonder Boy in Monster Land (Japan set 2)"},
        {"wbmljb",     "Wonder Boy in Monster Land (Japan not encrypted)"},
        {"wbmljo",     "Wonder Boy in Monster Land (Japan Old Ver.)"},
        {"wbmljod",    "Wonder Boy - Monster Land (decrypted bootleg of Japan Old Ver., MC-8123, 317-0043)"},
        {"wbmlju",     "Wonder Boy in Monster Land (Japan not encrypted)"},
        {"wbmlvc",     "Wonder Boy in Monster Land (English, Virtual Console)"},
        {"wbmlvcd",    "Wonder Boy - Monster Land (decrypted bootleg of English, Virtual Console release)"},
        {"wboy",       "Wonder Boy (set 1, new encryption)"},
        {"wboy2",      "Wonder Boy (set 2)"},
        {"wboy2u",     "Wonder Boy (set 2 not encrypted)"},
        {"wboy3",      "Wonder Boy (set 3)"},
        {"wboy4",      "Wonder Boy (315-5162, 4-D Warriors Conversion)"},
        {"wboy4u",     "Wonder Boy (set 4 not encrypted)"},
        {"wboy5",      "Wonder Boy (set 5, bootleg)"},
        {"wboy6",      "Wonder Boy (set 6, 315-5179)"},
        {"wboyblt",    "Wonder Boy (Tecfri bootleg)"},
        {"wboyo",      "Wonder Boy (set 1, old encryption)"},
        {"wboysys2",   "Wonder Boy (system 2, set 1, 315-5177)"},
        {"wboysys2a",  "Wonder Boy (system 2, set 2, 315-5176)"},
        {"wboyu",      "Wonder Boy (not encrypted)"},
        {"wboyub",     "Wonder Boy (US bootleg)"},
        {"wc90",       "Tecmo World Cup '90 (set 1)"},
        {"wc90a",      "Tecmo World Cup '90 (set 2)"},
        {"wc90b",      "Euro League"},
        {"wc90b2",     "Worldcup '90"},
        {"wc90t",      "Tecmo World Cup '90 (trackball)"},
        {"wcatcher",   "Mahjong Wakuwaku Catcher (Japan)"},
        {"wcbowl",     "World Class Bowling (v1.66)"},
        {"wcbowl10",   "World Class Bowling (v1.0)"},
        {"wcbowl11",   "World Class Bowling (v1.1)"},
        {"wcbowl12",   "World Class Bowling (v1.2)"},
        {"wcbowl13",   "World Class Bowling (v1.3)"},
        {"wcbowl130",  "World Class Bowling Tournament (v1.30)"},
        {"wcbowl13j",  "World Class Bowling (v1.3J, Japan)"},
        {"wcbowl14",   "World Class Bowling (v1.4)"},
        {"wcbowl140",  "World Class Bowling Tournament (v1.40)"},
        {"wcbowl15",   "World Class Bowling (v1.5)"},
        {"wcbowl16",   "World Class Bowling (v1.6)"},
        {"wcbowl161",  "World Class Bowling (v1.61)"},
        {"wcbowl165",  "World Class Bowling (v1.65)"},
        {"wcbowldx",   "World Class Bowling Deluxe (v2.00)"},
        {"wcbwl12",    "World Class Bowling (v1.2)"},
        {"wcbwl161",   "World Class Bowling (v1.61)"},
        {"wcbwl165",   "World Class Bowling (v1.65)"},
        {"wccf116",    "World Club Champion Football Serie A 2001-2002 Ver.2 (Japan) (CDP-10001C)"},
        {"wccf1dup",   "World Club Champion Football Serie A 2001-2002 DIMM FIRM Ver.3.03 (CDP-10003)"},
        {"wccf212e",   "World Club Champion Football Serie A 2002-2003 Ver.2.12 (Italy) (CDV-10002)"},
        {"wccf234j",   "World Club Champion Football Serie A 2002-2003 Ver.2.34 (Japan) (CDV-10008)"},
        {"wccf2chk",   "World Club Champion Football Serie A 2002-2003 Drive Checker (CDV-10007)"},
        {"wccf310j",   "World Club Champion Football European Clubs 2004-2005 (Asia) (CDV-10013)"},
        {"wccf322e",   "World Club Champion Football European Clubs 2004-2005 Ver.3.22 (Export) (CDV-10015P)"},
        {"wccf331e",   "World Club Champion Football European Clubs 2004-2005 Ver.1.1 (Export) (CDV-10015)"},
        {"wccf331j",   "World Club Champion Football European Clubs 2004-2005 Ver.1.1 (Japan) (CDV-10020)"},
        {"wccf341j",   "World Club Champion Football European Clubs 2004-2005 Ver.1.2 (Japan) (CDV-10021)"},
        {"wccf400j",   "World Club Champion Football European Clubs 2005-2006 (Japan) (CDV-10025)"},
        {"wccf420e",   "World Club Champion Football European Clubs 2005-2006 (Export) (CDV-10027)"},
        {"wcombat",    "World Combat (ver UAA?)"},
        {"wcombatj",   "World Combat (ver JAA)"},
        {"wcombatk",   "World Combat (ver KBC)"},
        {"wcvol95",    "World Cup Volley 95 (Japan v1.0)"},
        {"wcvol95j",   "World Cup Volley '95 (Japan v1.0)"},
        {"wcvol95x",   "World Cup Volley 95 Extra Version (Asia v2.0B)"},
        {"wecleman",   "WEC Le Mans 24"},
        {"weclemana",  "WEC Le Mans 24 (v2.00)"},
        {"weclemanb",  "WEC Le Mans 24 (v2.00, hack)"},
        {"weclemanc",  "WEC Le Mans 24 (v1.26)"},
        {"weddingr",   "Wedding Rhapsody (GX624 JAA)"},
        {"welltris",   "Welltris (Japan, 2 players)"},
        {"welltrisj",  "Welltris (Japan, 2 players)"},
        {"westgun2",   "Western Gun Part II"},
        {"weststry",   "West Story"},
        {"weststrya",  "West Story (bootleg of Blood Bros., set 2)"},
        {"wexpresb",   "Western Express (bootleg set 1)"},
        {"wexpresc",   "Western Express (bootleg set 2)"},
        {"wexpress",   "Western Express (World[Q])"},
        {"wexpressb",  "Western Express (bootleg set 1)"},
        {"wexpressb1", "Western Express (bootleg set 1)"},
        {"wexpressb2", "Western Express (bootleg set 2)"},
        {"wexpressb3", "Western Express (bootleg set 3)"},
        {"wfortuna",   "Wheel Of Fortune (alternate)"},
        {"wfortune",   "Wheel Of Fortune"},
        {"wfortunea",  "Wheel Of Fortune (set 2)"},
        {"wg3dh",      "Wayne Gretzky's 3D Hockey"},
        {"wg3dhfe",    "Wayne Gretzky's 3D Hockey Fatality Edition (prototype)"},
        {"wgp",        "World Grand Prix (US)"},
        {"wgp2",       "World Grand Prix 2 (Japan)"},
        {"wgpj",       "World Grand Prix (Japan)"},
        {"wgpjoy",     "World Grand Prix (joystick version set 1) (Japan)"},
        {"wgpjoya",    "World Grand Prix (joystick version set 2) (Japan)"},
        {"wh1",        "World Heroes (set 1)"},
        {"wh1h",       "World Heroes (set 2)"},
        {"wh1ha",      "World Heroes (set 3)"},
        {"wh2",        "World Heroes 2"},
        {"wh2h",       "World Heroes 2 (ALH-006)"},
        {"wh2j",       "World Heroes 2 Jet"},
        {"wh2ja",      "World Heroes 2 Jet (ADM-007)"},
        {"wh2jh",      "World Heroes 2 Jet (set 2)"},
        {"wheelfir",   "Wheels & Fire"},
        {"wheelrun",   "Wheels Runner"},
        {"whizquiz",   "Whiz Quiz"},
        {"whizz",      "Whizz"},
        {"whodunit",   "Who Dunit (version 8.0)"},
        {"whodunit8",  "Who Dunit (version 8.0)"},
        {"whoopee",    "Whoopee!! - Pipi and Bibis"},
        {"whp",        "World Heroes Perfect"},
        {"wiggie",     "Wiggie Waggie"},
        {"wildfang",   "Wild Fang - Tecmo Knight"},
        {"wildfangh",  "Wild Fang (year hack?)"},
        {"wildfangs",  "Wild Fang"},
        {"wildplt",    "Wild Pilot"},
        {"willow",     "Willow (US)"},
        {"willowj",    "Willow (Japan, Japanese)"},
        {"willowje",   "Willow (Japan, English)"},
        {"willowu",    "Willow (USA)"},
        {"willowuo",   "Willow (USA Old Ver.)"},
        {"wilytowr",   "Wily Tower"},
        {"windheat",   "Winding Heat (EAA, Euro v2.11)"},
        {"windheata",  "Winding Heat (AAA, Asia v2.11)"},
        {"windheatj",  "Winding Heat (JAA, Japan v2.11)"},
        {"windheatu",  "Winding Heat (UBC, USA v2.22)"},
        {"wingforc",   "Wing Force (Japan, prototype)"},
        {"wingwar",    "Wing War (World)"},
        {"wingwar360", "Wing War R360 (US)"},
        {"wingwarj",   "Wing War (Japan)"},
        {"wingwaru",   "Wing War (US)"},
        {"wink",       "Wink (set 1)"},
        {"winka",      "Wink (set 2)"},
        {"winrun",     "Winning Run (World) (89/06/06, Ver.09)"},
        {"winrun91",   "Winning Run 91"},
        {"winrungp",   "Winning Run Suzuka Grand Prix (Japan) (89/12/03, Ver.02)"},
        {"winspike",   "Winning Spike (ver JAA)"},
        {"winspikej",  "Winning Spike (ver JAA)"},
        {"wintbob",    "The Winter Bobble"},
        {"winterht",   "Winter Heat"},
        {"wiping",     "Wiping"},
        {"wiseguy",    "Wise Guy"},
        {"witch",      "Witch"},
        {"witchb",     "Witch (with ranking)"},
        {"witchs",     "Witch (Sega license)"},
        {"witchstar",  "Witch Star"},
        {"wits",       "Wit's (Japan)"},
        {"wivernwg",   "Wivern Wings"},
        {"wiz",        "Wiz"},
        {"wizdfire",   "Wizard Fire (US v1.1)"},
        {"wizdfireu",  "Wizard Fire (US v1.1)"},
        {"wizt",       "Wiz (Taito)"},
        {"wizta",      "Wiz (Taito, set 2)"},
        {"wizwarz",    "Wiz Warz (prototype)"},
        {"wizzquiz",   "Wizz Quiz (Konami version)"},
        {"wizzquiza",  "Wizz Quiz (version 4)"},
        {"wjammers",   "Windjammers / Flying Power Disc"},
        {"wlcc",       "Wan Li Chang Cheng (China, V638C)"},
        {"wldcourt",   "World Court (Japan)"},
        {"wldkicks",   "World Kicks (World, WK2 Ver.A)"},
        {"wldkicksa",  "World Kicks (Asia, WK2 Ver.A)"},
        {"wldkicksb",  "World Kicks PCB (WKC1 Ver. A)"},
        {"wldkicksj",  "World Kicks (Japan, WK1 Ver.A)"},
        {"wldkickspj", "World Kicks PCB (Japan, WKC1 Ver.A)"},
        {"wldkickspw", "World Kicks PCB (World, WKC2 Ver.A)"},
        {"wldkicksu",  "World Kicks (US, WK3 Ver.A)"},
        {"wldrider",   "Wild Riders"},
        {"wlstar",     "Wonder League Star - Sok-Magicball Fighting (Korea)"},
        {"wmatch",     "Water Match"},
        {"wmg",        "Williams Multigame"},
        {"wndrmomo",   "Wonder Momo"},
        {"wndrplnt",   "Wonder Planet (Japan)"},
        {"wof",        "Warriors of Fate (World 921002)"},
        {"wof3js",     "Sangokushi II: San Jian Sheng (Chinese bootleg set 1)"},
        {"wof3jsa",    "Sangokushi II: San Jian Sheng (Chinese bootleg set 2)"},
        {"wof3sj",     "Sangokushi II: San Sheng Jian (Chinese bootleg set 1)"},
        {"wof3sja",    "Sangokushi II: San Sheng Jian (Chinese bootleg set 2)"},
        {"wofa",       "Sangokushi II (Asia 921005)"},
        {"wofabl",     "Sangokushi II (bootleg)"},
        {"wofabla",    "Sangokushi II (Asia, bootleg, set 2)"},
        {"wofb",       "Warriors of Fate (bootleg, 921002 etc) [Bootleg]"},
        {"wofc",       "Sangokushi II (T-Chi)"},
        {"wofch",      "Tenchi wo Kurau II: Sekiheki no Tatakai (CPS Changer, Japan 921031)"},
        {"wofh",       "Sangokushi II: Sanguo Yingxiong Zhuan (Chinese bootleg set 1)"},
        {"wofha",      "Sangokushi II: Sanguo Yingxiong Zhuan (Chinese bootleg set 2)"},
        {"wofhfb",     "Huo Feng Huang (Chinese bootleg of Sangokushi II)"},
        {"wofhfh",     "Huo Feng Huang (Chinese bootleg of Sangokushi II)"},
        {"wofj",       "Tenchi wo Kurau II - Sekiheki no Tatakai (Japan 921031)"},
        {"wofpic",     "Warriors of Fate (bootleg with PIC16C57)"},
        {"wofr1",      "Warriors of Fate (World 921002)"},
        {"wofr1bl",    "Warriors of Fate (bootleg)"},
        {"wofsgzb",    "Sanguo Zhengba (Chinese bootleg of Sangokushi II)"},
        {"wofsj",      "Sangokushi II: Sheng Jian Sanguo (Chinese bootleg set 1)"},
        {"wofsja",     "Sangokushi II: Sheng Jian Sanguo (Chinese bootleg set 2)"},
        {"wofsjb",     "Sangokushi II: Sheng Jian Sanguo (Chinese bootleg set 3)"},
        {"wofsjc",     "Sangokushi II: Sheng Jian Sanguo (Chinese bootleg set 4, 921005 Asia) [Bootleg, Imperfect graphics]"},
        {"wofu",       "Warriors of Fate (US 921031)"},
        {"wolffang",   "Wolf Fang -Kuhga 2001- (Japan)"},
        {"wolfpack",   "Wolf Pack (prototype)"},
        {"wonder3",    "Wonder 3 (Japan 910520)"},
        {"wondl96",    "Wonder League '96 (Korea)"},
        {"wondstck",   "Wonder Stick (set 1)"},
        {"wondstcka",  "Wonder Stick (set 2, censored)"},
        {"woodpeca",   "Woodpecker (set 2)"},
        {"woodpeck",   "Woodpecker (set 1)"},
        {"worldadv",   "World Adventure"},
        {"worldc94",   "World Cup '94"},
        {"worldwar",   "World Wars (World)"},
        {"wotw",       "War of the Worlds"},
        {"wotwc",      "War of the Worlds (color)"},
        {"wow",        "Wizard of Wor"},
        {"wowg",       "Wizard of Wor (with German language ROM)"},
        {"wownfant",   "WOW New Fantasia"},
        {"wownfanta",  "WOW New Fantasia"},
        {"wpksoc",     "World PK Soccer"},
        {"wpksocv2",   "World PK Soccer V2 (ver 1.1)"},
        {"wrally",     "World Rally (set 1)"},
        {"wrally2",    "World Rally 2 - Twin Racing"},
        {"wrally2a",   "World Rally 2: Twin Racing (EPROM version)"},
        {"wrallya",    "World Rally (set 2)"},
        {"wrallyat",   "World Rally (US, 930217)"},
        {"wrallyb",    "World Rally (Version 1.0, Checksum 8AA2)"},
        {"wrallyc",    "World Rally (Version 1.0, Checksum E586)"},
        {"wrecking",   "Vs. Wrecking Crew"},
        {"wrestwar",   "Wrestle War"},
        {"wrestwar1",  "Wrestle War (set 1, Japan) (FD1094 317-0090)"},
        {"wrestwar1d", "Wrestle War (set 1, Japan) (bootleg of FD1094 317-0090 set)"},
        {"wrestwar2",  "Wrestle War (set 2, World) (FD1094 317-0102)"},
        {"wrestwar2d", "Wrestle War (set 2, World) (bootleg of FD1094 317-0102 set)"},
        {"wrofaero",   "War of Aero - Project MEIOU"},
        {"wrungp",     "Wave Runner GP"},
        {"wrungpo",    "Wave Runner GP (USA, Rev A)"},
        {"ws",         "World Stadium (Japan)"},
        {"ws89",       "World Stadium '89 (Japan)"},
        {"ws90",       "World Stadium '90 (Japan)"},
        {"wsbbgd",     "World Series Baseball / Super Major League (GDS-0010)"},
        {"wschamp",    "Wing Shooting Championship V2.0"},
        {"wschampa",   "Wing Shooting Championship V1.01"},
        {"wschampb",   "Wing Shooting Championship V1.00"},
        {"wseries",    "World Series - The Season"},
        {"wseries0",   "World Series: The Season (rev 0)"},
        {"wsf",        "World Soccer Finals"},
        {"wsf3",       "World Soccer Finals (rev 3)"},
        {"wsjr",       "Who Shot Johnny Rock? v1.6"},
        {"wsjr15",     "Who Shot Johnny Rock? v1.5"},
        {"wtennis",    "World Tennis"},
        {"wtrnymph",   "Water-Nymph (Ver. 1.4)"},
        {"ww3",        "WW III"},
        {"wwallyj",    "Wally wo Sagase! (rev B, Japan, 2 players) (FD1094 317-0197B)"},
        {"wwallyja",   "Wally wo Sagase! (rev A, Japan, 2 players) (FD1094 317-0197A)"},
        {"wwallyja3p", "Wally wo Sagase! (rev A, Japan, 3 players) (FD1094 317-0198A)"},
        {"wwallyjad",  "Wally wo Sagase! (rev A, Japan) (bootleg of FD1094 317-0197A set)"},
        {"wwallyjd",   "Wally wo Sagase! (rev B, Japan) (bootleg of FD1094 317-0197B set)"},
        {"wwanpanm",   "Waku Waku Anpanman (Rev A)"},
        {"wwester1",   "Wild Western (set 2)"},
        {"wwestern",   "Wild Western (set 1)"},
        {"wwestern1",  "Wild Western (set 2)"},
        {"wwfmanac",   "WWF: Wrestlemania (Acid Clown Edition 2020.12.02 SP2)"},
        {"wwfmania",   "WWF - Wrestlemania (rev 1.30 08-10-95)"},
        {"wwfmaniab",  "WWF: Wrestlemania (rev 1.20 08/02/95)"},
        {"wwfmaniac",  "WWF: Wrestlemania (rev 1.1 07/11/95)"},
        {"wwfmaniap",  "WWF: Wrestlemania (proto 2.01 06/07/95)"},
        {"wwfroyal",   "WWF Royal Rumble"},
        {"wwfsstar",   "WWF Superstars (US)"},
        {"wwfsstara",  "WWF Superstars (US, Newer)"},
        {"wwfsstarb",  "WWF Superstars (bootleg)"},
        {"wwfsstarb2", "WWF Superstars (bootleg with 2xYM2203)"},
        {"wwfsstarc",  "WWF Superstars (Canada)"},
        {"wwfsstarj",  "WWF Superstars (Japan)"},
        {"wwfsstaru",  "WWF Superstars (US)"},
        {"wwfsstaru4", "WWF Superstars (US revision 4)"},
        {"wwfsstaru6", "WWF Superstars (US revision 6)"},
        {"wwfsstaru7", "WWF Superstars (US revision 7)"},
        {"wwfwfest",   "WWF WrestleFest (US)"},
        {"wwfwfesta",  "WWF WrestleFest (US Tecmo)"},
        {"wwfwfestb",  "WWF WrestleFest (US bootleg)"},
        {"wwfwfestj",  "WWF WrestleFest (Japan)"},
        {"wwfwfestk",  "WWF WrestleFest (Korea)"},
        {"wwfwfestu",  "WWF WrestleFest (US, rev 2)"},
        {"wwfwfestu1", "WWF WrestleFest (US)"},
        {"wwfwfestub", "WWF WrestleFest (US bootleg)"},
        {"wwfwfsta",   "WWF WrestleFest (US Tecmo)"},
        {"wwfwfstj",   "WWF WrestleFest (Japan)"},
        {"wwjgtin",    "Wai Wai Jockey Gate-In!"},
        {"wwmarine",   "Waku Waku Marine"},
        {"wyvernf0",   "Wyvern F-0 (Rev 1)"},
        {"wyvernf0a",  "Wyvern F-0"},
        {"wyvernwg",   "Wyvern Wings (set 1)"},
        {"wyvernwga",  "Wyvern Wings (set 2)"},
};

const char *lookup_w(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_w(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
