#include <string.h>
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"eagle",      "Eagle (set 1)"},
        {"eagle2",     "Eagle (set 2)"},
        {"eagle3",     "Eagle (set 3)"},
        {"eaglshot",   "Eagle Shot Golf"},
        {"eaglshotj",  "Eagle Shot Golf (Japan, bootleg?)"},
        {"eaglshta",   "Eagle Shot Golf (alt)"},
        {"earthinv",   "Super Earth Invasion"},
        {"earthjkr",   "U.N. Defense Force - Earth Joker (Japan)"},
        {"earthjkra",  "U.N. Defense Force: Earth Joker (US / Japan, set 2)"},
        {"earthjkrb",  "U.N. Defense Force: Earth Joker (US / Japan, set 3)"},
        {"earthjkrp",  "U.N. Defense Force: Earth Joker (Japan, prototype?)"},
        {"ebases",     "Extra Bases"},
        {"eca",        "Emergency Call Ambulance (Export)"},
        {"ecaj",       "Emergency Call Ambulance (Japan)"},
        {"ecap",       "Emergency Call Ambulance (US location test?)"},
        {"ecau",       "Emergency Call Ambulance (USA)"},
        {"ecax",       "Emergency Call Ambulance (Export)"},
        {"ecofghtr",   "Eco Fighters (World 931203)"},
        {"ecofghtra",  "Eco Fighters (Asia 931203)"},
        {"ecofghtrd",  "Eco Fighters (World 931203 Phoenix Edition) (bootleg)"},
        {"ecofghtrh",  "Eco Fighters (Hispanic 931203)"},
        {"ecofghtru",  "Eco Fighters (USA 940215)"},
        {"ecofghtru1", "Eco Fighters (USA 931203)"},
        {"edf",        "E.D.F. - Earth Defense Force"},
        {"edfa",       "E.D.F. : Earth Defense Force (set 2)"},
        {"edfp",       "E.D.F. : Earth Defense Force (Japan, prototype)"},
        {"edfu",       "E.D.F. - Earth Defense Force (North America)"},
        {"edrandy",    "The Cliffhanger - Edward Randy (World revision 2)"},
        {"edrandy1",   "The Cliffhanger - Edward Randy (World revision 1)"},
        {"edrandy2",   "The Cliffhanger - Edward Randy (World ver 2)"},
        {"edrandyj",   "The Cliffhanger - Edward Randy (Japan)"},
        {"eeekk",      "Eeekk!"},
        {"eeekkp",     "Eeekk! (Pac-Man conversion)"},
        {"efdt",       "El Fin Del Tiempo"},
        {"egghunt",    "Egg Hunt"},
        {"eggor",      "Eggor"},
        {"eggs",       "Eggs"},
        {"eggsplc",    "Eggs Playing Chicken"},
        {"eggventr",   "Egg Venture"},
        {"eggventr1",  "Egg Venture (Release 1)"},
        {"eggventr2",  "Egg Venture (Release 2)"},
        {"eggventr7",  "Egg Venture (Release 7)"},
        {"eggventr8",  "Egg Venture (Release 8)"},
        {"eggventra",  "Egg Venture (A.L. Release)"},
        {"eggventrd",  "Egg Venture Deluxe"},
        {"eggvntdx",   "Egg Venture Deluxe"},
        {"ehrgeiz",    "Ehrgeiz (EG3-VER.A)"},
        {"ehrgeizja",  "Ehrgeiz (Japan, EG1/VER.A)"},
        {"ehrgeizua",  "Ehrgeiz (US, EG3/VER.A)"},
        {"eightfrc",   "Eight Forces"},
        {"eightman",   "Eight Man"},
        {"einning",    "Extra Inning / Ball Park II"},
        {"einnings",   "Extra Inning"},
        {"ejihon",     "Ejihon Tantei Jimusyo"},
        {"elandore",   "Fighting Dragon Legend Elan Doree"},
        {"elecyoy2",   "The Electric Yo-Yo (set 2)"},
        {"elecyoyo",   "The Electric Yo-Yo (set 1)"},
        {"elecyoyoa",  "The Electric Yo-Yo"},
        {"elevatob",   "Elevator Action (bootleg)"},
        {"elevator",   "Elevator Action"},
        {"elevatora",  "Elevator Action (EA, 5 PCB version, 1.1)"},
        {"elevatorb",  "Elevator Action (bootleg)"},
        {"elfin",      "Elfin"},
        {"elim2",      "Eliminator (2 Players, set 1)"},
        {"elim2a",     "Eliminator (2 Players, set 2)"},
        {"elim2c",     "Eliminator (2 Players, cocktail)"},
        {"elim4",      "Eliminator (4 Players)"},
        {"elim4p",     "Eliminator (4 Players, prototype)"},
        {"elvact2u",   "Elevator Action 2 (US)"},
        {"elvactr",    "Elevator Action Returns (World)"},
        {"elvactrj",   "Elevator Action Returns (Japan)"},
        {"embargo",    "Embargo"},
        {"emeralda",   "Emeraldia (Japan Version B)"},
        {"emeraldaj",  "Emeraldia (Japan Version B)"},
        {"emeraldaja", "Emeraldia (Japan)"},
        {"emerldaa",   "Emeraldia (Japan)"},
        {"empcity",    "Empire City - 1931 (bootleg[Q])"},
        {"empcityfr",  "Empire City: 1931 (France)"},
        {"empcityi",   "Empire City: 1931 (Italy)"},
        {"empcityj",   "Empire City - 1931 (Japan)"},
        {"empcityu",   "Empire City: 1931 (US)"},
        {"endless",    "Gundam Wing: Endless Duel (SNES bootleg, set 1)"},
        {"endlessa",   "Gundam Wing: Endless Duel (SNES bootleg, set 2)"},
        {"endurob2",   "Enduro Racer (bootleg set 2)"},
        {"endurobl",   "Enduro Racer (bootleg set 1)"},
        {"enduror",    "Enduro Racer"},
        {"enduror1",   "Enduro Racer (YM2203, FD1089B 317-0013A)"},
        {"enduror1d",  "Enduro Racer (bootleg of YM2203, FD1089B 317-0013A set)"},
        {"endurora",   "Enduro Racer (Rev A, YM2151, mask ROM sprites, FD1089B 317-0013A)"},
        {"endurorb",   "Enduro Racer (YM2151, FD1089B 317-0013A)"},
        {"endurord",   "Enduro Racer (bootleg of Rev A, YM2151, FD1089B 317-0013A set)"},
        {"enforce",    "Enforce (Japan)"},
        {"enforcej",   "Enforce (Japan)"},
        {"enforceja",  "Enforce (Japan, Analog Controls)"},
        {"enigma2",    "Enigma 2"},
        {"enigma2a",   "Enigma 2 (Space Invaders Hardware)"},
        {"enigma2b",   "Phantoms II (Space Invaders hardware)"},
        {"enmadaio",   "Enma Daio (Japan)"},
        {"eprom",      "Escape from the Planet of the Robot Monsters (set 1)"},
        {"eprom2",     "Escape from the Planet of the Robot Monsters (set 2)"},
        {"equites",    "Equites"},
        {"equitess",   "Equites (Sega)"},
        {"ertictac",   "Erotictac/Tactic"},
        {"ertictaca",  "Erotictac/Tactic (ver 01)"},
        {"ertictacb",  "Erotictac/Tactic (set 2)"},
        {"esb",        "The Empire Strikes Back"},
        {"esckids",    "Escape Kids (Asia 4 Players)"},
        {"esckidsj",   "Escape Kids (Japan 2 Players)"},
        {"escounts",   "Every Second Counts (39-360-053)"},
        {"espgal",     "EspGaluda"},
        {"espgal2",    "Espgaluda II (2005/11/14.MASTER VER.)"},
        {"espgal2a",   "Espgaluda II (2005/11/14 MASTER VER, newer CV1000-B PCB)"},
        {"espgal2b",   "Espgaluda II (2005/11/14 MASTER VER, original CV1000-B PCB)"},
        {"espgalbl",   "Espgaluda (2003/10/15 Master Ver, bootleg cartridge conversion)"},
        {"espial",     "Espial (US[Q])"},
        {"espiale",    "Espial (Europe)"},
        {"espialj",    "Espial (Japan)"},
        {"espialn",    "Espial (Nova Apparate license)"},
        {"espialu",    "Espial (US?)"},
        {"esprade",    "ESP Ra.De. (International Ver 1998 4-22)"},
        {"espradej",   "ESP Ra.De. (Japan Ver 1998 4-21)"},
        {"espradejo",  "ESP Ra.De. (Japan, 1998 4/14 Master Ver.)"},
        {"espradeo",   "ESP Ra.De. (Japan Ver 1998 4-14)"},
        {"eswat",      "E-Swat - Cyber Police"},
        {"eswatbl",    "E-Swat - Cyber Police (bootleg)"},
        {"eswatd",     "E-Swat - Cyber Police (set 4, World) (bootleg of FD1094 317-0130 set)"},
        {"eswatj",     "E-Swat - Cyber Police (set 2, Japan) (FD1094 317-0128)"},
        {"eswatj1",    "E-Swat - Cyber Police (set 1, Japan) (FD1094 317-0131)"},
        {"eswatj1d",   "E-Swat - Cyber Police (set 1, Japan) (bootleg of FD1094 317-0131 set)"},
        {"eswatjd",    "E-Swat - Cyber Police (set 2, Japan) (bootleg of FD1094 317-0128 set)"},
        {"eswatu",     "E-Swat - Cyber Police (set 3, US) (FD1094 317-0129)"},
        {"eswatud",    "E-Swat - Cyber Police (set 3, US) (bootleg of FD1094 317-0129 set)"},
        {"eto",        "Kokontouzai Eto Monogatari (Japan)"},
        {"etoa",       "Kokontouzai Eto Monogatari (Japan, prototype?)"},
        {"euroch92",   "Euro Champ '92 (World)"},
        {"euroch92j",  "Euro Champ '92 (Japan)"},
        {"eurogael",   "Euro League (Gaelco bootleg, Modular System)"},
        {"evilngt",    "Evil Night (ver UBA)"},
        {"evilston",   "Evil Stone"},
        {"excelsr",    "Excelsior (set 1)"},
        {"excelsra",   "Excelsior (set 2)"},
        {"excitbkj",   "Vs. Excitebike (Japan)"},
        {"excitebk",   "Vs. Excitebike"},
        {"excitebkj",  "Vs. Excitebike (set EB4-4 A)"},
        {"excitebko",  "Vs. Excitebike (set EB4-3 ?)"},
        {"excthour",   "Exciting Hour"},
        {"exctleag",   "Excite League"},
        {"exctleagd",  "Excite League (bootleg of FD1094 317-0079 set)"},
        {"exctscc2",   "Exciting Soccer II"},
        {"exctscca",   "Exciting Soccer (alternate music)"},
        {"exctsccb",   "Exciting Soccer (bootleg)"},
        {"exctsccr",   "Exciting Soccer"},
        {"exctsccra",  "Exciting Soccer (alternate music)"},
        {"exctsccrb",  "Exciting Soccer (bootleg)"},
        {"exctsccrj",  "Exciting Soccer (Japan)"},
        {"exctsccrjo", "Exciting Soccer (Japan, older)"},
        {"exctsccru",  "Exciting Soccer (US)"},
        {"exedexes",   "Exed Exes"},
        {"exerion",    "Exerion"},
        {"exerionb",   "Exerion (bootleg)"},
        {"exerionb2",  "Exerion (bootleg, set 2)"},
        {"exerionba",  "Exerion (Assa, bootleg)"},
        {"exeriont",   "Exerion (Taito)"},
        {"exerizer",   "Exerizer (Japan)"},
        {"exerizerb",  "Exerizer (bootleg)"},
        {"exerizrb",   "Exerizer (Japan) (bootleg)"},
        {"exodus",     "Exodus (bootleg[Q])"},
        {"explbrkr",   "Explosive Breaker (World)"},
        {"explbrkrk",  "Explosive Breaker (Korea)"},
        {"explorer",   "Explorer"},
        {"exprraid",   "Express Raider (US)"},
        {"exprraidi",  "Express Raider (Italy)"},
        {"exprraidu",  "Express Raider (US, rev 5)"},
        {"extdwnhl",   "Extreme Downhill (v1.5)"},
        {"exterm",     "Exterminator"},
        {"extrmatn",   "Extermination (US)"},
        {"extrmatnj",  "Extermination (Japan)"},
        {"extrmatnu",  "Extermination (US, World Games)"},
        {"extrmatnur", "Extermination (US, Romstar)"},
        {"exvania",    "Exvania (Japan)"},
        {"exvaniaj",   "Exvania (Japan)"},
        {"exzisus",    "Exzisus (Japan)"},
        {"exzisusa",   "Exzisus (Japan, conversion)"},
        {"exzisust",   "Exzisus (TAD license)"},
        {"eyes",       "Eyes (Digitrex Techstar)"},
        {"eyes2",      "Eyes (Techstar)"},
        {"eyesb",      "Eyes (bootleg set 1)"},
        {"eyeszac",    "Eyes (Italy)"},
        {"eyeszacb",   "Eyes (bootleg set 2, decrypted)"},
};

const char *lookup_e(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_e(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
