#include <string.h>
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"s1945",        "Strikers 1945"},
        {"s1945a",       "Strikers 1945 (Japan / World)"},
        {"s1945bl",      "Strikers 1945 (Hong Kong, bootleg)"},
        {"s1945ii",      "Strikers 1945 II"},
        {"s1945iii",     "Strikers 1945 III (World) - Strikers 1999 (Japan)"},
        {"s1945j",       "Strikers 1945 (Japan)"},
        {"s1945jn",      "Strikers 1945 (Japan, unprotected)"},
        {"s1945k",       "Strikers 1945 (Korea)"},
        {"s1945n",       "Strikers 1945 (World, unprotected)"},
        {"s1945nj",      "Strikers 1945 (Japan, unprotected)"},
        {"s1945p",       "Strikers 1945 Plus"},
        {"sabotenb",     "Saboten Bombers (set 1)"},
        {"sabotenba",    "Saboten Bombers (set 2)"},
        {"sabotnba",     "Saboten Bombers (set 2)"},
        {"sadari",       "Sadari"},
        {"safari",       "Safari"},
        {"safarir",      "Safari Rally (World)"},
        {"safarirj",     "Safari Rally (Japan)"},
        {"sagaia",       "Sagaia (dual screen) (World)"},
        {"sailormn",     "Pretty Soldier Sailor Moon (95-03-22B)"},
        {"sailormnh",    "Bishoujo Senshi Sailor Moon (Version 95/03/22B, Hong Kong)"},
        {"sailormnj",    "Bishoujo Senshi Sailor Moon (Version 95/03/22B, Japan)"},
        {"sailormnk",    "Pretty Soldier Sailor Moon (Version 95/03/22B, Korea)"},
        {"sailormnn",    "Pretty Soldier Sailor Moon (Version 95/03/22, Europe)"},
        {"sailormnnh",   "Bishoujo Senshi Sailor Moon (Version 95/03/22, Hong Kong)"},
        {"sailormnnj",   "Bishoujo Senshi Sailor Moon (Version 95/03/22, Japan)"},
        {"sailormnnk",   "Pretty Soldier Sailor Moon (Version 95/03/22, Korea)"},
        {"sailormnnt",   "Bishoujo Senshi Sailor Moon (Version 95/03/22, Taiwan)"},
        {"sailormnnu",   "Pretty Soldier Sailor Moon (Version 95/03/22, USA)"},
        {"sailormno",    "Pretty Soldier Sailor Moon (Version 95/03/21, Europe)"},
        {"sailormnoh",   "Bishoujo Senshi Sailor Moon (Version 95/03/21, Hong Kong)"},
        {"sailormnoj",   "Bishoujo Senshi Sailor Moon (Version 95/03/21, Japan)"},
        {"sailormnok",   "Pretty Soldier Sailor Moon (Version 95/03/21, Korea)"},
        {"sailormnot",   "Bishoujo Senshi Sailor Moon (Version 95/03/21, Taiwan)"},
        {"sailormnou",   "Pretty Soldier Sailor Moon (Version 95/03/21, USA)"},
        {"sailormnt",    "Bishoujo Senshi Sailor Moon (Version 95/03/22B, Taiwan)"},
        {"sailormnu",    "Pretty Soldier Sailor Moon (Version 95/03/22B, USA)"},
        {"sailormo",     "Pretty Soldier Sailor Moon (95-03-22)"},
        {"sailorwr",     "Mahjong Sailor Wars-R [BET] (Japan)"},
        {"sailorws",     "Mahjong Sailor Wars (Japan)"},
        {"saiyugb1",     "Sai Yu Gou Ma Roku (Japan bootleg 1)"},
        {"saiyugb2",     "Sai Yu Gou Ma Roku (Japan bootleg 2)"},
        {"saiyugou",     "Sai Yu Gou Ma Roku (Japan)"},
        {"saiyugoub1",   "Sai Yu Gou Ma Roku (Japan bootleg 1)"},
        {"saiyugoub2",   "Sai Yu Gou Ma Roku (Japan bootleg 2)"},
        {"salamand",     "Salamander (version D)"},
        {"salamandj",    "Salamander (version J)"},
        {"salamandt",    "Salamander (Tecfri license)"},
        {"salamanj",     "Salamander (version J)"},
        {"salmankt",     "Net@Select: Salaryman Kintaro"},
        {"salmndr2",     "Salamander 2 (ver JAA)"},
        {"samesam2",     "Same! Same! Same! (2P Ver.)"},
        {"samesame",     "Same! Same! Same!"},
        {"samesame2",    "Same! Same! Same! (2P set)"},
        {"samesamecn",   "Jiao! Jiao! Jiao! (China, 2P set)"},
        {"samesamenh",   "Same! Same! Same! (1P set, NEW VER! hack)"},
        {"samsh5sp",     "Samurai Shodown V Special"},
        {"samsh5sph",    "Samurai Shodown V Special / Samurai Spirits Zero Special (NGH-2720, 2nd release, less censored)"},
        {"samsh5spho",   "Samurai Shodown V Special / Samurai Spirits Zero Special (NGH-2720, 1st release, censored)"},
        {"samsho",       "Samurai Shodown / Samurai Spirits"},
        {"samsho2",      "Samurai Shodown II / Shin Samurai Spirits - Haohmaru jigokuhen"},
        {"samsho2k",     "Saulabi Spirits / Jin Saulabi Tu Hon (Korean release of Samurai Shodown II, set 1)"},
        {"samsho2ka",    "Saulabi Spirits / Jin Saulabi Tu Hon (Korean release of Samurai Shodown II, set 2)"},
        {"samsho3",      "Samurai Shodown III / Samurai Spirits - Zankurou Musouken"},
        {"samsho3h",     "Samurai Shodown III / Samurai Spirits - Zankurou Musouken (NGH-087)"},
        {"samsho4",      "Samurai Shodown IV - Amakusa's Revenge / Samurai Spirits - Amakusa Kourin"},
        {"samsho4k",     "Paewang Jeonseol / Legend of a Warrior (Korean censored Samurai Shodown IV)"},
        {"samsho5",      "Samurai Shodown V"},
        {"samsho5a",     "Samurai Shodown V / Samurai Spirits Zero (NGM-2700, set 2)"},
        {"samsho5b",     "Samurai Shodown V / Samurai Spirits Zero (bootleg)"},
        {"samsho5h",     "Samurai Shodown V / Samurai Spirits Zero (NGH-2700)"},
        {"samshoh",      "Samurai Shodown / Samurai Spirits (NGH-045)"},
        {"samsptk",      "Samurai Spirits Tenkaichi Kenkakuden"},
        {"samurai",      "Samurai"},
        {"samuraia",     "Samurai Aces (World)"},
        {"sandor",       "Sando-R"},
        {"sandscrp",     "Sand Scorpion"},
        {"sandscrpa",    "Sand Scorpion (Earlier)"},
        {"sandscrpb",    "Kuai Da Shizi Huangdi (China?, Revised Hardware)"},
        {"sarge",        "Sarge"},
        {"sarukani",     "Saru-Kani-Hamu-Zou (Japan)"},
        {"sassisu",      "Taisen Tanto-R Sashissu!!"},
        {"sasuke",       "Sasuke vs. Commander"},
        {"satansat",     "Satan of Saturn"},
        {"sathena",      "Super Athena (bootleg)"},
        {"saturn",       "Saturn"},
        {"saturnzi",     "Saturn"},
        {"sauro",        "Sauro"},
        {"sauroa",       "Sauro (set 2)"},
        {"saurob",       "Sauro (set 3)"},
        {"saurobl",      "Sauro (bootleg)"},
        {"sauroc",       "Sauro (set 4, easier)"},
        {"saurop",       "Sauro (Philko license)"},
        {"saurorr",      "Sauro (Recreativos Real S.A. license)"},
        {"savagere",     "Savage Reign / Fu'un Mokushiroku - kakutou sousei"},
        {"savanna",      "Savanna (bootleg of Jungler)"},
        {"savgbees",     "Savage Bees"},
        {"sb2003",       "Super Bubble 2003 (World, Ver 1.0)"},
        {"sb2003a",      "Super Bubble 2003 (Asia, Ver 1.0)"},
        {"sbagman",      "Super Bagman"},
        {"sbagman2",     "Super Bagman (version 3?)"},
        {"sbagmans",     "Super Bagman (Stern)"},
        {"sbasebal",     "Super Champion Baseball (US)"},
        {"sbasketb",     "Super Basketball (version G)"},
        {"sbaskete",     "Super Basketball (version E, encrypted)"},
        {"sbasketg",     "Super Basketball (version G, encrypted)"},
        {"sbasketh",     "Super Basketball (version H, unprotected)"},
        {"sbasketo",     "Super Basketball (version E)"},
        {"sbasketu",     "Super Basketball (not encrypted)"},
        {"sbbros",       "Super Buster Bros. (US)"},
        {"sbdk",         "Super Bike (DK conversion)"},
        {"sbhoei",       "Space Battle (Hoei, set 1)"},
        {"sbhoeia",      "Space Battle (Hoei, set 2)"},
        {"sbishi",       "Super Bishi Bashi Championship (ver JAA, 2 Players)"},
        {"sbishik",      "Super Bishi Bashi Championship (ver KAA, 3 Players)"},
        {"sbishika",     "Super Bishi Bashi Champ (ver KAA, 3 Players)"},
        {"sblast2b",     "Sonic Blast Man II Special Turbo (SNES bootleg)"},
        {"sbm",          "Sonic Blast Man (Japan)"},
        {"sboblbob",     "Super Bobble Bobble"},
        {"sboblbobl",    "Super Bobble Bobble (bootleg, set 1)"},
        {"sboblbobla",   "Super Bobble Bobble (bootleg, set 2)"},
        {"sboblboblb",   "Super Bobble Bobble (bootleg, set 3)"},
        {"sboblboblc",   "Super Bubble Bobble (bootleg)"},
        {"sboblbobld",   "Super Bobble Bobble (bootleg, set 4)"},
        {"sboblboble",   "Super Bobble Bobble (bootleg, set 5)"},
        {"sboblboblf",   "Super Bobble Bobble (bootleg, set 6)"},
        {"sbomber",      "Space Bomber (ver. B)"},
        {"sbombera",     "Space Bomber"},
        {"sbomberb",     "Space Bomber (ver. B)"},
        {"sbowling",     "Strike Bowling"},
        {"sbrkout",      "Super Breakout"},
        {"sbrkout3",     "Super Breakout (rev 03)"},
        {"sbrkoutc",     "Super Breakout (Canyon and Vertical Breakout, prototype)"},
        {"sbrkoutct",    "Super Breakout (Cocktail, prototype)"},
        {"sbsgomo",      "Space Battle Ship Gomorrah"},
        {"sbubsm",       "Super Bubble Bobble (Sun Mixing, Megadrive clone hardware)"},
        {"sbugger",      "Space Bugger"},
        {"scandal",      "Scandal Mahjong (Japan 890213)"},
        {"scandalm",     "Scandal Mahjong [BET] (Japan 890217)"},
        {"scessjoe",     "Success Joe (World)"},
        {"scfinals",     "Super Cup Finals (World)"},
        {"scfinalso",    "Super Cup Finals (Ver 2.1O 1993/11/19, single PCB)"},
        {"scfinalsoc",   "Super Cup Finals (Ver 2.1O 1993/11/19, F3 Cartridge)"},
        {"schamp",       "Sonic Championship (USA)"},
        {"schaser",      "Space Chaser"},
        {"schasera",     "Space Chaser (set 2)"},
        {"schaserb",     "Space Chaser (set 3)"},
        {"schaserc",     "Space Chaser (set 4)"},
        {"schaserm",     "Space Chaser (Model Racing bootleg)"},
        {"schasrcv",     "Space Chaser (CV version)"},
        {"schmeisr",     "Schmeiser Robo (Japan)"},
        {"sci",          "Special Criminal Investigation (World set 1)"},
        {"scia",         "Special Criminal Investigation (World set 2)"},
        {"scij",         "Special Criminal Investigation (Japan)"},
        {"scin",         "Super Special Criminal Investigation (Negro Torino hack)"},
        {"scion",        "Scion"},
        {"scionc",       "Scion (Cinematronics)"},
        {"sciu",         "Special Criminal Investigation (US)"},
        {"scobra",       "Super Cobra"},
        {"scobrab",      "Super Cobra (bootleg)"},
        {"scobrae",      "Super Cobra (Stern Electronics) (encrypted, KONATEC XC-103SS CPU)"},
        {"scobrae2",     "Super Cobra (encrypted)"},
        {"scobras",      "Super Cobra (Stern)"},
        {"scobrase",     "Super Cobra (Sega)"},
        {"scontra",      "Super Contra"},
        {"scontraa",     "Super Contra (set 2)"},
        {"scontraj",     "Super Contra (Japan)"},
        {"scorpion",     "Scorpion (set 1)"},
        {"scorpiona",    "Scorpion (set 2)"},
        {"scorpionb",    "Scorpion (set 3)"},
        {"scorpionmc",   "Scorpion (Moon Cresta hardware)"},
        {"scorpnmc",     "Scorpion (Moon Cresta hardware)"},
        {"scotrsht",     "Scooter Shooter"},
        {"scrabble",     "Scrabble (rev. F)"},
        {"scrabbled",    "Scrabble (rev. F) (Protocol)"},
        {"scrabbleo",    "Scrabble (Spanish bootleg of Scramble)"},
        {"scramb2",      "Scramble (bootleg, set 1)"},
        {"scramb3",      "Scramble (bootleg, set 2)"},
        {"scramblb",     "Scramble (Galaxian hardware)"},
        {"scramble",     "Scramble"},
        {"scramblebb",   "Scramble (bootleg?)"},
        {"scramblebf",   "Scramble (Karateco, French bootleg)"},
        {"scrambleo",    "Scramble (Okapi bootleg)"},
        {"scrambler",    "Scramble (Reben S.A. Spanish bootleg)"},
        {"scrambles",    "Scramble (Stern Electronics, set 1)"},
        {"scrambles2",   "Scramble (Stern Electronics, set 2)"},
        {"scrambls",     "Scramble (Stern)"},
        {"scrambp",      "Impacto (Billport S.A., Spanish bootleg of Scramble)"},
        {"scramce",      "Scramble (Centromatic S.A., Spanish bootleg)"},
        {"scrampt",      "Scramble (Petaco S.A., Spanish bootleg)"},
        {"scramrf",      "Scramble (Recreativos Franco, Spanish bootleg)"},
        {"scregg",       "Scrambled Egg"},
        {"screwloo",     "Screw Loose (prototype)"},
        {"scross",       "Stadium Cross (World)"},
        {"scrossa",      "Stadium Cross (World, alt)"},
        {"scrossu",      "Stadium Cross (US)"},
        {"sctionza",     "Section Z (set 2)"},
        {"scud",         "Scud Race / Sega Super GT - Twin/DX (Export)"},
        {"scuda",        "Scud Race Twin"},
        {"scudau",       "Scud Race - Twin/DX (Australia)"},
        {"scuddx",       "Scud Race / Sega Super GT - Deluxe (Export, Revision A)"},
        {"scuddxo",      "Scud Race / Sega Super GT - Deluxe (Export)"},
        {"scudhamm",     "Scud Hammer"},
        {"scudhamma",    "Scud Hammer (older version?)"},
        {"scudj",        "Scud Race Deluxe"},
        {"scudplus",     "Scud Race Plus / Sega Super GT Plus - Twin/DX (Export, Revision A)"},
        {"scudplusa",    "Scud Race Plus / Sega Super GT Plus - Twin/DX (Export)"},
        {"scyclone",     "Space Cyclone"},
        {"sdfight",      "SD Fighter (Korea)"},
        {"sdgndmps",     "SD Gundam Psycho Salamander no Kyoui"},
        {"sdgndmrb",     "SD Gundam Sangokushi Rainbow Tairiku Senki"},
        {"sdi",          "SDI - Strategic Defense Initiative"},
        {"sdia",         "SDI - Strategic Defense Initiative (Japan, old, System 16A, FD1089B 317-0027)"},
        {"sdib",         "SDI - Strategic Defense Initiative (System 16B, FD1089A 317-0028)"},
        {"sdibl",        "SDI - Strategic Defense Initiative (bootleg, original hardware)"},
        {"sdibl2",       "SDI - Strategic Defense Initiative (bootleg, set 1)"},
        {"sdibl3",       "SDI - Strategic Defense Initiative (bootleg, set 2)"},
        {"sdibl4",       "SDI - Strategic Defense Initiative (bootleg, set 3)"},
        {"sdibl5",       "SDI - Strategic Defense Initiative (bootleg, set 4)"},
        {"sdibl6",       "SDI - Strategic Defense Initiative (bootleg, set 5)"},
        {"sdioj",        "SDI - Strategic Defense Initiative (Japan)"},
        {"sdodgeb",      "Super Dodge Ball / Kunio no Nekketsu Toukyuu Densetsu"},
        {"sdtennis",     "Super Doubles Tennis"},
        {"sdungeon",     "Space Dungeon"},
        {"sdungeona",    "Space Dungeon (larger roms)"},
        {"seabass",      "Sea Bass Fishing"},
        {"searchar",     "SAR - Search And Rescue (World)"},
        {"searcharj",    "SAR - Search And Rescue (Japan version 3)"},
        {"searcharu",    "SAR - Search And Rescue (US)"},
        {"searchey",     "Search Eye (English / Korean / Japanese / Italian)"},
        {"searcheya",    "Search Eye (English / Korean)"},
        {"searchp2",     "Search Eye Plus V2.0"},
        {"searthie",     "Super Earth Invasion (set 3)"},
        {"searthin",     "Super Earth Invasion (set 1)"},
        {"searthina",    "Super Earth Invasion (set 2)"},
        {"seawolf",      "Sea Wolf"},
        {"seawolf2",     "Sea Wolf II"},
        {"seawolft",     "Sea Wolf (Tecfri)"},
        {"secolove",     "Second Love (Japan 861201)"},
        {"secretab",     "Secret Agent (bootleg)"},
        {"secretag",     "Secret Agent (World)"},
        {"secretagj",    "Secret Agent (Japan, revision 2)"},
        {"sectionz",     "Section Z (set 1)"},
        {"sectionza",    "Section Z (Japan, rev. A)"},
        {"sectrzon",     "Sector Zone"},
        {"sectrzona",    "Sector Zone (set 3)"},
        {"sectrzont",    "Sector Zone (set 2, Tecfri hardware)"},
        {"seganinj",     "Sega Ninja"},
        {"seganinja",    "Sega Ninja (315-5113)"},
        {"seganinju",    "Sega Ninja (not encrypted)"},
        {"seganinu",     "Sega Ninja (not encrypted)"},
        {"segawski",     "Sega Water Ski (Japan, Revision A)"},
        {"seicross",     "Seicross"},
        {"seicrossa",    "Seicross (set 2)"},
        {"seiha",        "Seiha (Japan 870725)"},
        {"seiham",       "Seiha [BET] (Japan 870723)"},
        {"selfeena",     "Sel Feena"},
        {"semibase",     "MuHanSeungBu (SemiCom Baseball) (Korea)"},
        {"sengekij",     "Sengeki Striker (Japan)"},
        {"sengekis",     "Sengeki Striker (Asia)"},
        {"sengokh",      "Sengoku / Sengoku Denshou (set 2)"},
        {"sengokmj",     "Sengoku Mahjong (Japan)"},
        {"sengoku",      "Sengoku / Sengoku Denshou (set 1)"},
        {"sengoku2",     "Sengoku 2 / Sengoku Denshou 2"},
        {"sengoku3",     "Sengoku 3"},
        {"sengoku3a",    "Sengoku 3 / Sengoku Densho 2001 (set 2)"},
        {"sengokuh",     "Sengoku / Sengoku Denshou (NGH-017, US)"},
        {"senjyo",       "Senjyo"},
        {"senknow",      "Sen-Know (Japan)"},
        {"senko",        "Senko no Ronde (Japan, Rev A) (GDL-0030A)"},
        {"senkoo",       "Senko no Ronde (Japan) (GDL-0030)"},
        {"senkosp",      "Senko no Ronde Special (Export, Japan) (GDL-0038)"},
        {"senkyu",       "Senkyu (Japan, newer)"},
        {"senkyua",      "Senkyu (Japan, earlier)"},
        {"sentetst",     "Sente Diagnostic Cartridge"},
        {"sercharu",     "SAR - Search And Rescue (US)"},
        {"sexappl",      "Sex Appeal (Version 6.02)"},
        {"sextriv",      "Sex Triv"},
        {"sextriv1",     "Sexual Trivia (Version 1.02SB, set 1)"},
        {"sextriv2",     "Sexual Trivia (Version 1.02SB, set 2)"},
        {"sexyboom",     "Sexy Boom"},
        {"sexyparo",     "Sexy Parodius (ver JAA)"},
        {"sexyparoa",    "Sexy Parodius (ver AAA)"},
        {"sf",           "Street Fighter (US, set 1)"},
        {"sf1",          "Street Fighter (World)"},
        {"sf1jp",        "Street Fighter (Japan)"},
        {"sf1p",         "Street Fighter (prototype)"},
        {"sf1us",        "Street Fighter (US)"},
        {"sf2",          "Street Fighter II - The World Warrior (World 910522)"},
        {"sf2049",       "San Francisco Rush 2049"},
        {"sf2049se",     "San Francisco Rush 2049: Special Edition"},
        {"sf2acc",       "Street Fighter II': Champion Edition (Accelerator!, bootleg, set 1)"},
        {"sf2acca",      "Street Fighter II': Champion Edition (Accelerator!, bootleg, set 2)"},
        {"sf2accp2",     "Street Fighter II' - Champion Edition (Accelerator Pt.II)"},
        {"sf2amf2",      "Street Fighter II': Champion Edition (L735 Test Rom, bootleg, set 1)"},
        {"sf2amf3",      "Street Fighter II': Champion Edition (L735 Test Rom, bootleg, set 2)"},
        {"sf2b",         "Street Fighter II: The World Warrior (bootleg, set 1)"},
        {"sf2b2",        "Street Fighter II: The World Warrior (bootleg, set 2)"},
        {"sf2bhh",       "Street Fighter II': Champion Edition (Hung Hsi, bootleg)"},
        {"sf2ce",        "Street Fighter II' - Champion Edition (World 920313)"},
        {"sf2ceb",       "Street Fighter II': Champion Edition (Playmark bootleg, set 1)"},
        {"sf2ceb2",      "Street Fighter II': Champion Edition (bootleg, set 1)"},
        {"sf2ceb3",      "Street Fighter II': Champion Edition (bootleg, set 2)"},
        {"sf2ceb4",      "Street Fighter II': Champion Edition (Playmark bootleg, set 2)"},
        {"sf2ceb5",      "Street Fighter II': Champion Edition (Playmark bootleg, set 3)"},
        {"sf2ceblp",     "Street Fighter II': Champion Edition (protected bootleg on non-dash board)"},
        {"sf2cebltw",    "Street Fighter II': Champion Edition ('Taiwan' bootleg with PAL)"},
        {"sf2ceds6",     "Street Fighter II': Champion Edition (Dstreet-6, bootleg)"},
        {"sf2ceea",      "Street Fighter II': Champion Edition (World 920313)"},
        {"sf2ceec",      "Street Fighter II': Champion Edition (World 920803)"},
        {"sf2cej",       "Street Fighter II' - Champion Edition (Japan 920513)"},
        {"sf2ceja",      "Street Fighter II': Champion Edition (Japan 920322)"},
        {"sf2cejb",      "Street Fighter II': Champion Edition (Japan 920513)"},
        {"sf2cejc",      "Street Fighter II': Champion Edition (Japan 920803)"},
        {"sf2cems6a",    "Street Fighter II': Champion Edition (Mstreet-6, bootleg, set 1)"},
        {"sf2cems6b",    "Street Fighter II': Champion Edition (Mstreet-6, bootleg, set 2)"},
        {"sf2cems6c",    "Street Fighter II': Champion Edition (Mstreet-6, bootleg, set 3)"},
        {"sf2cet",       "Street Fighter II': Champion Edition (Taiwan 920313)"},
        {"sf2ceua",      "Street Fighter II' - Champion Edition (US 920313)"},
        {"sf2ceub",      "Street Fighter II' - Champion Edition (US 920513)"},
        {"sf2ceuc",      "Street Fighter II' - Champion Edition (US 920803)"},
        {"sf2ceupl",     "Street Fighter II': Champion Edition (Japan 920322, UPL bootleg?)"},
        {"sf2dkot2",     "Street Fighter II': Champion Edition (Double K.O. Turbo II, bootleg)"},
        {"sf2dongb",     "Street Fighter II': Champion Edition (Dongfang Bubai protection, bootleg)"},
        {"sf2ea",        "Street Fighter II: The World Warrior (World 910204)"},
        {"sf2eb",        "Street Fighter II - The World Warrior (World 910214)"},
        {"sf2ebbl",      "Street Fighter II: The World Warrior (TAB Austria, bootleg, set 1)"},
        {"sf2ebbl2",     "Street Fighter II: The World Warrior (TAB Austria, bootleg, set 3)"},
        {"sf2ebbl3",     "Street Fighter II: The World Warrior (TAB Austria, bootleg, set 4)"},
        {"sf2ed",        "Street Fighter II: The World Warrior (World 910318)"},
        {"sf2ee",        "Street Fighter II: The World Warrior (World 910228)"},
        {"sf2ef",        "Street Fighter II: The World Warrior (World 910411)"},
        {"sf2em",        "Street Fighter II: The World Warrior (World 910129)"},
        {"sf2en",        "Street Fighter II: The World Warrior (World 910204, conversion)"},
        {"sf2hf",        "Street Fighter II': Hyper Fighting (World 921209)"},
        {"sf2hfj",       "Street Fighter II' Turbo: Hyper Fighting (Japan 921209)"},
        {"sf2hfu",       "Street Fighter II': Hyper Fighting (USA 921209)"},
        {"sf2j",         "Street Fighter II - The World Warrior (Japan 911210)"},
        {"sf2j17",       "Street Fighter II: The World Warrior (Japan 911210, CPS-B-17)"},
        {"sf2ja",        "Street Fighter II - The World Warrior (Japan 910214)"},
        {"sf2jc",        "Street Fighter II - The World Warrior (Japan 910306)"},
        {"sf2jf",        "Street Fighter II: The World Warrior (Japan 910411)"},
        {"sf2jh",        "Street Fighter II: The World Warrior (Japan 910522)"},
        {"sf2jl",        "Street Fighter II: The World Warrior (Japan 920312)"},
        {"sf2koryu",     "Street Fighter II' - Champion Edition (Kouryu)"},
        {"sf2level",     "Street Fighter II': Champion Edition (bootleg with level selection)"},
        {"sf2m1",        "Street Fighter II' - Champion Edition (M1)"},
        {"sf2m10",       "Street Fighter II': Champion Edition (M10, bootleg)"},
        {"sf2m2",        "Street Fighter II' - Champion Edition (M2)"},
        {"sf2m3",        "Street Fighter II' - Champion Edition (M3)"},
        {"sf2m4",        "Street Fighter II' - Champion Edition (M4)"},
        {"sf2m5",        "Street Fighter II' - Champion Edition (M5)"},
        {"sf2m6",        "Street Fighter II' - Champion Edition (M6)"},
        {"sf2m7",        "Street Fighter II' - Champion Edition (M7)"},
        {"sf2m8",        "Street Fighter II': Champion Edition (M8, bootleg)"},
        {"sf2m9",        "Street Fighter II': Champion Edition (M9, bootleg)"},
        {"sf2mdt",       "Street Fighter II': Magic Delta Turbo (bootleg, set 1)"},
        {"sf2mdta",      "Street Fighter II': Magic Delta Turbo (bootleg, set 2)"},
        {"sf2mdtb",      "Street Fighter II': Magic Delta Turbo (bootleg, set 3)"},
        {"sf2mkot",      "Street Fighter II': Magic KO Turbo!! - Nightmare Crack"},
        {"sf2qp1",       "Street Fighter II: The World Warrior (Quicken Pt-I, bootleg)"},
        {"sf2qp2",       "Street Fighter II: The World Warrior (Quicken, bootleg)"},
        {"sf2rb",        "Street Fighter II' - Champion Edition (Rainbow set 1)"},
        {"sf2rb2",       "Street Fighter II' - Champion Edition (Rainbow set 2)"},
        {"sf2rb3",       "Street Fighter II': Champion Edition (Rainbow, bootleg, set 3)"},
        {"sf2re",        "Street Fighter II': Champion Edition (RE, bootleg)"},
        {"sf2red",       "Street Fighter II' - Champion Edition (Red Wave)"},
        {"sf2reda",      "Street Fighter II': Champion Edition (Red Wave, bootleg, set 2)"},
        {"sf2redp2",     "Street Fighter II': Champion Edition (Red Wave PtII, bootleg)"},
        {"sf2rk",        "Street Fighter II: The World Warrior (RK, bootleg)"},
        {"sf2rules",     "Street Fighter II: The World Warrior (bootleg with rules screen)"},
        {"sf2t",         "Street Fighter II' - Hyper Fighting (US 921209)"},
        {"sf2thndr",     "Street Fighter II: The World Warrior (Thunder Edition, bootleg, set 1)"},
        {"sf2thndr2",    "Street Fighter II: The World Warrior (Thunder Edition, bootleg, set 2)"},
        {"sf2tj",        "Street Fighter II' Turbo - Hyper Fighting (Japan 921209)"},
        {"sf2ua",        "Street Fighter II - The World Warrior (US 910206)"},
        {"sf2ub",        "Street Fighter II - The World Warrior (US 910214)"},
        {"sf2uc",        "Street Fighter II: The World Warrior (USA 910306)"},
        {"sf2ud",        "Street Fighter II - The World Warrior (US 910318)"},
        {"sf2ue",        "Street Fighter II - The World Warrior (US 910228)"},
        {"sf2uf",        "Street Fighter II - The World Warrior (US 910411)"},
        {"sf2ug",        "Street Fighter II: The World Warrior (USA 910522, Rev. G)"},
        {"sf2uh",        "Street Fighter II: The World Warrior (USA 910522, Rev. H)"},
        {"sf2ui",        "Street Fighter II - The World Warrior (US 910522)"},
        {"sf2uk",        "Street Fighter II - The World Warrior (US 911101)"},
        {"sf2um",        "Street Fighter II: The World Warrior (USA 920312)"},
        {"sf2v004",      "Street Fighter II! - Champion Edition (V004)"},
        {"sf2yyc",       "Street Fighter II' - Champion Edition (YYC)"},
        {"sfa",          "Street Fighter Alpha: Warriors' Dreams (Euro 950727)"},
        {"sfa2",         "Street Fighter Alpha 2 (Euro 960229)"},
        {"sfa2u",        "Street Fighter Alpha 2 (USA 960430)"},
        {"sfa2ur1",      "Street Fighter Alpha 2 (USA 960306)"},
        {"sfa3",         "Street Fighter Alpha 3 (Euro 980904)"},
        {"sfa3b",        "Street Fighter Alpha 3 (Brazil 980629)"},
        {"sfa3h",        "Street Fighter Alpha 3 (Hispanic 980904)"},
        {"sfa3hr1",      "Street Fighter Alpha 3 (Hispanic 980629)"},
        {"sfa3u",        "Street Fighter Alpha 3 (USA 980904)"},
        {"sfa3ud",       "Street Fighter Alpha 3 (USA 980904 Phoenix Edition) (bootleg)"},
        {"sfa3ur1",      "Street Fighter Alpha 3 (USA 980629)"},
        {"sfa3us",       "Street Fighter Alpha 3 (USA 980616, SAMPLE Version)"},
        {"sfad",         "Street Fighter Alpha: Warriors' Dreams (Europe 950727 Phoenix Edition) (bootleg)"},
        {"sfan",         "Street Fighter (World, pneumatic buttons)"},
        {"sfar1",        "Street Fighter Alpha: Warriors' Dreams (Euro 950718)"},
        {"sfar2",        "Street Fighter Alpha: Warriors' Dreams (Euro 950627)"},
        {"sfar3",        "Street Fighter Alpha: Warriors' Dreams (Euro 950605)"},
        {"sfau",         "Street Fighter Alpha: Warriors' Dreams (USA 950627)"},
        {"sfchamp",      "Super Football Champ (JAPAN)"},
        {"sfex",         "Street Fighter EX (ASIA 961219)"},
        {"sfex2",        "Street Fighter EX 2 (JAPAN 980312)"},
        {"sfex2p",       "Street Fighter EX 2 Plus (JAPAN 990611)"},
        {"sfexj",        "Street Fighter EX (JAPAN 961130)"},
        {"sfexp",        "Street Fighter EX Plus (USA 970311)"},
        {"sfexpj",       "Street Fighter EX Plus (JAPAN 970311)"},
        {"sfight",       "Sonic the Fighters (Japan)"},
        {"sfiii",        "Street Fighter III: New Generation (Europe 970204)"},
        {"sfiii2",       "Street Fighter III 2nd Impact: Giant Attack (USA 970930)"},
        {"sfiii2h",      "Street Fighter III 2nd Impact: Giant Attack (Hispanic 970930)"},
        {"sfiii2j",      "Street Fighter III 2nd Impact: Giant Attack (Japan 970930)"},
        {"sfiii2n",      "Street Fighter III 2nd Impact: Giant Attack (Asia 970930, NO CD)"},
        {"sfiii3",       "Street Fighter III 3rd Strike: Fight for the Future (Europe 990608)"},
        {"sfiii3j",      "Street Fighter III 3rd Strike: Fight for the Future (Japan 990608)"},
        {"sfiii3jr1",    "Street Fighter III 3rd Strike: Fight for the Future (Japan 990512)"},
        {"sfiii3n",      "Street Fighter III 3rd Strike: Fight for the Future (Japan 990608, NO CD)"},
        {"sfiii3nr1",    "Street Fighter III 3rd Strike: Fight for the Future (Japan 990512, NO CD)"},
        {"sfiii3r1",     "Street Fighter III 3rd Strike: Fight for the Future (Europe 990512)"},
        {"sfiii3u",      "Street Fighter III 3rd Strike: Fight for the Future (USA 990608)"},
        {"sfiii3ur1",    "Street Fighter III 3rd Strike: Fight for the Future (USA 990512)"},
        {"sfiiia",       "Street Fighter III: New Generation (Asia 970204)"},
        {"sfiiih",       "Street Fighter III: New Generation (Hispanic 970204)"},
        {"sfiiij",       "Street Fighter III: New Generation (Japan 970204)"},
        {"sfiiin",       "Street Fighter III: New Generation (Asia 970204, NO CD, BIOS set 1)"},
        {"sfiiina",      "Street Fighter III: New Generation (Asia 970204, NO CD, BIOS set 2)"},
        {"sfiiiu",       "Street Fighter III: New Generation (USA 970204)"},
        {"sfish2",       "Sport Fishing 2"},
        {"sfish2j",      "Sport Fishing 2 (Japan)"},
        {"sfj",          "Street Fighter (Japan) (protected)"},
        {"sfjan",        "Street Fighter (Japan, pneumatic buttons)"},
        {"sfjbl",        "Street Fighter (Japan, bootleg)"},
        {"sfkick",       "Super Free Kick (set 1)"},
        {"sfkicka",      "Super Free Kick (set 2)"},
        {"sflush",       "Straight Flush"},
        {"sfootbal",     "Street Football"},
        {"sformula",     "Super Formula (Japan)"},
        {"sformulaa",    "Super Formula (Japan, set 2)"},
        {"sfp",          "Street Fighter (prototype)"},
        {"sfposeid",     "Sea Fighter Poseidon"},
        {"sfrush",       "San Francisco Rush"},
        {"sfrushrk",     "San Francisco Rush: The Rock (boot rom L 1.0, GUTS Oct 6 1997 / MAIN Oct 16 1997)"},
        {"sftm",         "Street Fighter - The Movie (v1.12)"},
        {"sftm110",      "Street Fighter - The Movie (v1.10)"},
        {"sftm111",      "Street Fighter - The Movie (v1.11)"},
        {"sftmj",        "Street Fighter - The Movie (v1.12N, Japan)"},
        {"sftmj112",     "Street Fighter: The Movie (v1.12N, Japan)"},
        {"sftmj114",     "Street Fighter: The Movie (v1.14N, Japan)"},
        {"sftmk112",     "Street Fighter: The Movie (v1.12K, Korea)"},
        {"sfua",         "Street Fighter (US, set 2) (protected)"},
        {"sfw",          "Street Fighter (World) (protected)"},
        {"sfx",          "SF-X"},
        {"sfz2a",        "Street Fighter Zero 2 (Asia 960227)"},
        {"sfz2ad",       "Street Fighter Zero 2 (Asia 960227 Phoenix Edition) (bootleg)"},
        {"sfz2al",       "Street Fighter Zero 2 Alpha (Asia 960826)"},
        {"sfz2alb",      "Street Fighter Zero 2 Alpha (Brazil 960813)"},
        {"sfz2ald",      "Street Fighter Zero 2 Alpha (Asia 960826 Phoenix Edition) (bootleg)"},
        {"sfz2alh",      "Street Fighter Zero 2 Alpha (Hispanic 960813)"},
        {"sfz2alj",      "Street Fighter Zero 2 Alpha (Japan 960805)"},
        {"sfz2alr1",     "Street Fighter Zero 2 Alpha (Asia 960805)"},
        {"sfz2b",        "Street Fighter Zero 2 (Brazil 960531)"},
        {"sfz2br1",      "Street Fighter Zero 2 (Brazil 960304)"},
        {"sfz2h",        "Street Fighter Zero 2 (Hispanic 960304)"},
        {"sfz2j",        "Street Fighter Zero 2 (Japan 960430)"},
        {"sfz2jd",       "Street Fighter Zero 2 (Japan 960227 Phoenix Edition) (bootleg)"},
        {"sfz2jr1",      "Street Fighter Zero 2 (Japan 960227)"},
        {"sfz2n",        "Street Fighter Zero 2 (Oceania 960229)"},
        {"sfz3a",        "Street Fighter Zero 3 (Asia 980904)"},
        {"sfz3ar1",      "Street Fighter Zero 3 (Asia 980701)"},
        {"sfz3j",        "Street Fighter Zero 3 (Japan 980904)"},
        {"sfz3jr1",      "Street Fighter Zero 3 (Japan 980727)"},
        {"sfz3jr2",      "Street Fighter Zero 3 (Japan 980629)"},
        {"sfz3jr2d",     "Street Fighter Zero 3 (Japan 980629 Phoenix Edition) (bootleg)"},
        {"sfz3ugd",      "Street Fighter Zero 3 Upper (Japan) (GDL-0002)"},
        {"sfza",         "Street Fighter Zero (Asia 950627)"},
        {"sfzar1",       "Street Fighter Zero (Asia 950605)"},
        {"sfzb",         "Street Fighter Zero (Brazil 951109)"},
        {"sfzbr1",       "Street Fighter Zero (Brazil 950727)"},
        {"sfzh",         "Street Fighter Zero (Hispanic 950718)"},
        {"sfzhr1",       "Street Fighter Zero (Hispanic 950627)"},
        {"sfzj",         "Street Fighter Zero (Japan 950727)"},
        {"sfzjr1",       "Street Fighter Zero (Japan 950627)"},
        {"sfzjr2",       "Street Fighter Zero (Japan 950605)"},
        {"sg2j",         "Star Gladiator 2 (JAPAN 980316)"},
        {"sgalwars",     "Super Galactic Wars (bootleg of Galaxian)"},
        {"sgdrvsim",     "Driving Simulator"},
        {"sgemf",        "Super Gem Fighter Mini Mix (USA 970904)"},
        {"sgemfa",       "Super Gem Fighter: Mini Mix (Asia 970904)"},
        {"sgemfd",       "Super Gem Fighter: Mini Mix (USA 970904 Phoenix Edition) (bootleg)"},
        {"sgemfh",       "Super Gem Fighter: Mini Mix (Hispanic 970904)"},
        {"sgladiat",     "Gladiator 1984"},
        {"sgmast",       "Super Masters Golf"},
        {"sgmastc",      "Jumbo Ozaki Super Masters Golf (World, Floppy Based, FD1094 317-0058-05c)"},
        {"sgmastj",      "Jumbo Ozaki Super Masters Golf (Japan, Floppy Based, FD1094 317-0058-05b)"},
        {"sgmt1",        "Super Game Mega Type 1"},
        {"sgt24h",       "Super GT 24h"},
        {"sgtetris",     "Sega Tetris"},
        {"sgunner",      "Steel Gunner"},
        {"sgunner2",     "Steel Gunner 2 (US)"},
        {"sgunner2j",    "Steel Gunner 2 (Japan, Rev A)"},
        {"sgunnerj",     "Steel Gunner (Japan)"},
        {"sgunnr2j",     "Steel Gunner 2 (Japan)"},
        {"sgyxz",        "Warriors of Fate ('sgyxz' bootleg)"},
        {"shackled",     "Shackled (US)"},
        {"shadfrce",     "Shadow Force (US Version 2)"},
        {"shadfrcej",    "Shadow Force - Henshin Ninja (Japan, Version 2)"},
        {"shadfrceu",    "Shadow Force (US, Version 2)"},
        {"shadowld",     "Shadow Land"},
        {"shadoww",      "Shadow Warriors (World set 1)"},
        {"shadowwa",     "Shadow Warriors (World set 2)"},
        {"shambros",     "Shamisen Brothers Vol 1 (V1.01K)"},
        {"shangha2",     "Shanghai II (Japan)"},
        {"shangha2a",    "Shanghai II (Japan, set 2)"},
        {"shangha3",     "Shanghai III (Japan)"},
        {"shangha3j",    "Shanghai III (Japan)"},
        {"shangha3u",    "Shanghai III (US)"},
        {"shangha3up",   "Shanghai III (US, prototype)"},
        {"shanghai",     "Shanghai (Japan)"},
        {"shanghaij",    "Shanghai (Japan)"},
        {"shangkid",     "Shanghai Kid"},
        {"shangon",      "Super Hang-On"},
        {"shangon1",     "Super Hang-On (mini ride-on) (FD1089B 317-0034)"},
        {"shangon2",     "Super Hang-On (mini ride-on, Rev A) (FD1089B 317-0034)"},
        {"shangon3",     "Super Hang-On (sitdown/upright) (FD1089B 317-0034)"},
        {"shangon3d",    "Super Hang-On (sitdown/upright) (bootleg of FD1089B 317-0034 set)"},
        {"shangonb",     "Super Hang-On (bootleg)"},
        {"shangonho",    "Super Hang-On (Hang-On conversion, Japan, FD1094 317-0039)"},
        {"shangonle",    "Limited Edition Hang-On"},
        {"shangonrb",    "Super Hang-On (Hang-On conversion, bootleg)"},
        {"shangonrb2",   "Super Hang-On (Hang-On conversion, Beta bootleg)"},
        {"shangonro",    "Super Hang-On (Hang-On conversion, ride-on, Japan, FD1094 317-0038)"},
        {"shanhigw",     "Shanghai - The Great Wall - Shanghai Triple Threat"},
        {"shaolinb",     "Shao-lin's Road (set 2)"},
        {"shaolins",     "Shao-Lin's Road"},
        {"sharkatt",     "Shark Attack"},
        {"sharrier",     "Space Harrier"},
        {"sharrier1",    "Space Harrier (8751 315-5163)"},
        {"shdancbl",     "Shadow Dancer (bootleg)"},
        {"shdancer",     "Shadow Dancer (US)"},
        {"shdancer1",    "Shadow Dancer (US)"},
        {"shdancerj",    "Shadow Dancer (Japan)"},
        {"shdancrb",     "Shadow Dancer (Rev.B)"},
        {"shdancrj",     "Shadow Dancer (Japan)"},
        {"sheriff",      "Sheriff"},
        {"shienryu",     "Shienryu"},
        {"shikgam2",     "Shikigami no Shiro II / The Castle of Shikigami II (GDL-0021)"},
        {"shimpacp",     "Super High Impact (prototype, rev 5.0 09-15-91)"},
        {"shimpact",     "Super High Impact (rev LA1 09-30-91)"},
        {"shimpactp4",   "Super High Impact (prototype, proto 4.0 09/10/91)"},
        {"shimpactp5",   "Super High Impact (prototype, proto 5.0 09/15/91)"},
        {"shimpactp6",   "Super High Impact (prototype, proto 6.0 09/23/91)"},
        {"shinfz",       "Shinobi / FZ-2006 (Korean System 16 bootleg) (ISG Selection Master Type 2006)"},
        {"shinobi",      "Shinobi (set 1)"},
        {"shinobi1",     "Shinobi (set 1, System 16A) (FD1094 317-0050)"},
        {"shinobi1d",    "Shinobi (set 1, System 16A) (bootleg of FD1094 317-0050 set)"},
        {"shinobi2",     "Shinobi (set 2, System 16B) (FD1094 317-0049)"},
        {"shinobi2d",    "Shinobi (set 2, System 16B) (bootleg of FD1094 317-0049 set)"},
        {"shinobi3",     "Shinobi (set 3, System 16B) (MC-8123B 317-0054)"},
        {"shinobi4",     "Shinobi (set 4, System 16B) (MC-8123B 317-0054)"},
        {"shinobi5",     "Shinobi (set 5, System 16B) (unprotected)"},
        {"shinobi6",     "Shinobi (set 6, System 16B) (unprotected)"},
        {"shinobia",     "Shinobi (set 2)"},
        {"shinobib",     "Shinobi (set 3)"},
        {"shinobl",      "Shinobi (bootleg)"},
        {"shinoblb",     "Shinobi (Beta bootleg)"},
        {"shinobls",     "Shinobi (Star bootleg, System 16A)"},
        {"shippumd",     "Shippu Mahou Daisakusen (Japan)"},
        {"shiryu2",      "Strider Hiryu 2 (JAPAN 991213)"},
        {"shisen",       "Shisensho - Joshiryo-Hen (Japan)"},
        {"shisen2",      "Shisensho II"},
        {"shisena",      "Shisensho - Joshiryo-Hen (Japan, set 2)"},
        {"shocking",     "Shocking"},
        {"shockingk",    "Shocking (Korea, set 1)"},
        {"shockingko",   "Shocking (Korea, set 2)"},
        {"shocktr2",     "Shock Troopers - 2nd Squad"},
        {"shocktra",     "Shock Troopers (set 2)"},
        {"shocktro",     "Shock Troopers (set 1)"},
        {"shocktroa",    "Shock Troopers (set 2)"},
        {"shogwarr",     "Shogun Warriors"},
        {"shogwarrk",    "Shogun Warriors (Korea?)"},
        {"shogwarru",    "Shogun Warriors (US)"},
        {"shollow",      "Satan's Hollow (set 1)"},
        {"shollow2",     "Satan's Hollow (set 2)"},
        {"shootbul",     "Shoot the Bull"},
        {"shootgal",     "Shooting Gallery"},
        {"shootopl",     "Shootout Pool"},
        {"shootoub",     "Shoot Out (Korean Bootleg)"},
        {"shootouj",     "Shoot Out (Japan)"},
        {"shootout",     "Shoot Out (US)"},
        {"shootoutb",    "Shoot Out (Korean Bootleg)"},
        {"shootoutj",    "Shoot Out (Japan)"},
        {"shootpl",      "Shootout Pool Prize (Export) / Shootout Pool The Medal (Japan, Rev A)"},
        {"shootplm",     "Shootout Pool Prize (Export) / Shootout Pool The Medal (Japan) Version B"},
        {"shootplmp",    "Shootout Pool Prize (Export) / Shootout Pool The Medal (Japan) Version B (prototype)"},
        {"shoottv",      "Must Shoot TV (prototype)"},
        {"shougi",       "Shougi"},
        {"shougi2",      "Shougi 2"},
        {"showdown",     "Showdown (version 5.0)"},
        {"shrike",       "Shrike Avenger (prototype)"},
        {"shtngmst",     "Shooting Master"},
        {"shtrider",     "Shot Rider"},
        {"shtridera",    "Shot Rider (Sigma license)"},
        {"shtriderb",    "Shot Rider (bootleg)"},
        {"shuffle",      "Shuffleboard"},
        {"shufshot",     "Shuffleshot (v1.39)"},
        {"shufshot135",  "Shuffleshot (v1.35)"},
        {"shufshot137",  "Shuffleshot (v1.37)"},
        {"shufshot138",  "Shuffleshot (v1.38)"},
        {"shufshot139",  "Shuffleshot (v1.39)"},
        {"shuriboy",     "Shuriken Boy"},
        {"shuuz",        "Shuuz (version 8.0)"},
        {"shuuz2",       "Shuuz (version 7.1)"},
        {"sia2650",      "Super Invader Attack"},
        {"sichuan2",     "Sichuan II (hack[Q]) (set 1)"},
        {"sichuan2a",    "Sichuan II (bootleg, set 2)"},
        {"sichuana",     "Sichuan II (hack[Q]) (set 2)"},
        {"sicv",         "Space Invaders (CV Version)"},
        {"sidearjp",     "Side Arms - Hyper Dyne (Japan)"},
        {"sidearmr",     "Side Arms - Hyper Dyne (US)"},
        {"sidearms",     "Side Arms - Hyper Dyne (World)"},
        {"sidearmsj",    "Side Arms - Hyper Dyne (Japan, 861128)"},
        {"sidearmsu",    "Side Arms - Hyper Dyne (US, 861202)"},
        {"sidearmsur1",  "Side Arms - Hyper Dyne (US, 861128)"},
        {"sidebs",       "Side by Side (Ver 3.0 OK)"},
        {"sidebs2",      "Side by Side 2 (Ver 2.6 OK)"},
        {"sidebs2j",     "Side by Side 2 Evoluzione RR (Ver 3.1 J)"},
        {"sidebs2ja",    "Side by Side 2 Evoluzione (Ver 2.4 J)"},
        {"sidebs2u",     "Side by Side 2 (Ver 2.6 A)"},
        {"sidebsj",      "Side by Side (Ver 2.7 J)"},
        {"sidebsja",     "Side by Side (Ver 2.6 J)"},
        {"sidebsjb",     "Side by Side (Ver 2.5 J)"},
        {"sidepckt",     "Side Pocket (World)"},
        {"sidepcktb",    "Side Pocket (bootleg)"},
        {"sidepcktj",    "Side Pocket (Japan, Cocktail)"},
        {"sidepctb",     "Side Pocket (bootleg)"},
        {"sidepctj",     "Side Pocket (Japan)"},
        {"sidetrac",     "Side Track"},
        {"silentd",      "Silent Dragon (World)"},
        {"silentdj",     "Silent Dragon (Japan)"},
        {"silentdu",     "Silent Dragon (US)"},
        {"silkroad",     "The Legend of Silkroad"},
        {"silkroada",    "The Legend of Silkroad (larger ROMs)"},
        {"silkworm",     "Silk Worm (set 1)"},
        {"silkwormb",    "Silk Worm (bootleg, set 1)"},
        {"silkwormb2",   "Silk Worm (bootleg, set 2)"},
        {"silkwormj",    "Silk Worm (Japan)"},
        {"silkwormp",    "Silk Worm (prototype)"},
        {"silkwrm2",     "Silk Worm (set 2)"},
        {"silvland",     "Silver Land"},
        {"silvmil",      "Silver Millennium"},
        {"simldv1000",   "Pioneer LDV-1000 Simulator"},
        {"simpr8210",    "Pioneer PR-8210 Simulator"},
        {"simps2pa",     "The Simpsons (2 Players alt)"},
        {"simps2pj",     "The Simpsons (2 Players Japan)"},
        {"simpsn2p",     "The Simpsons (2 Players)"},
        {"simpsonjr",    "Simpson Junior (bootleg of J. J. Squawkers)"},
        {"simpsons",     "The Simpsons (4 Players)"},
        {"simpsons2p",   "The Simpsons (2 Players World, set 1)"},
        {"simpsons2p2",  "The Simpsons (2 Players World, set 2)"},
        {"simpsons2p3",  "The Simpsons (2 Players World, set 3)"},
        {"simpsons2pa",  "The Simpsons (2 Players Asia)"},
        {"simpsons2pj",  "The Simpsons (2 Players Japan)"},
        {"simpsons4pa",  "The Simpsons (4 Players Asia)"},
        {"simpsons4pe",  "The Simpsons (4 Players World, set 2)"},
        {"simpsons4pe2", "The Simpsons (4 Players World, set 3)"},
        {"sindbadm",     "Sindbad Mystery"},
        {"sinista1",     "Sinistar (prototype version)"},
        {"sinista2",     "Sinistar (revision 2)"},
        {"sinistar",     "Sinistar (revision 3)"},
        {"sinistar2",    "Sinistar (revision 2, upright)"},
        {"sinistarc",    "Sinistar (revision 3, cockpit)"},
        {"sinistarc2",   "Sinistar (revision 2, cockpit)"},
        {"sinistarp",    "Sinistar (AMOA-82 prototype)"},
        {"sinvasn",      "Space Invasion (Europe)"},
        {"sinvasnb",     "Space Invasion (bootleg)"},
        {"sinvemag",     "Super Invaders (EMAG)"},
        {"sinvemag2",    "Super Invaders (Emag bootleg set 2)"},
        {"sinvzen",      "Super Invaders (Zenitone-Microsec)"},
        {"sirio2",       "Sirio II (Calfesa S.L. Spanish bootleg of Moon Cresta)"},
        {"sisv",         "Space Invaders (SV Version)"},
        {"sisv2",        "Space Invaders (SV Version 2)"},
        {"sisv3",        "Space Invaders (SV Version rev 3)"},
        {"sitv",         "Space Invaders (TV Version)"},
        {"sitv1",        "Space Invaders (TV Version rev 1)"},
        {"sjryuko",      "Sukeban Jansi Ryuko (set 2, System 16B, FD1089B 317-5021)"},
        {"skatekds",     "Vs. Skate Kids. (Graphic hack of Super Mario Bros.)"},
        {"skelagon",     "Skelagon"},
        {"skichamp",     "Ski Champ (Japan)"},
        {"skilldrp",     "Skill Drop Georgia (Ver. G1.01S, Oct 1 2002)"},
        {"skilldrpa",    "Skill Drop Georgia (Ver. G1.0S, Sep 13 2002)"},
        {"skimaxx",      "Skimaxx"},
        {"skingam2",     "The Irem Skins Game (US set 2)"},
        {"skingame",     "The Irem Skins Game (US set 1)"},
        {"skingame2",    "The Irem Skins Game (US set 2)"},
        {"skisuprg",     "Sega Ski Super G"},
        {"skns",         "Super Kaneko Nova System BIOS"},
        {"skullfng",     "Skull Fang (Europe 1.13)"},
        {"skullfngj",    "Skull Fang (Japan 1.09)"},
        {"skullxb1",     "Skull and Crossbones (rev 1)"},
        {"skullxb2",     "Skull and Crossbones (rev 2)"},
        {"skullxb3",     "Skull and Crossbones (rev 3)"},
        {"skullxb4",     "Skull and Crossbones (rev 4)"},
        {"skullxbo",     "Skull and Crossbones (rev 5)"},
        {"skullxbo1",    "Skull & Crossbones (rev 1)"},
        {"skullxbo2",    "Skull & Crossbones (rev 2)"},
        {"skullxbo3",    "Skull & Crossbones (rev 3)"},
        {"skullxbo4",    "Skull & Crossbones (rev 4)"},
        {"skyadvnj",     "Sky Adventure (Japan)"},
        {"skyadvnt",     "Sky Adventure (World)"},
        {"skyadvntj",    "Sky Adventure (Japan)"},
        {"skyadvntu",    "Sky Adventure (US)"},
        {"skyadvnu",     "Sky Adventure (US)"},
        {"skyalert",     "Sky Alert"},
        {"skyarmy",      "Sky Army"},
        {"skybase",      "Sky Base"},
        {"skybump",      "Sky Bumper"},
        {"skychut",      "Sky Chuter"},
        {"skydest",      "Sky Destroyer (Japan)"},
        {"skydiver",     "Sky Diver"},
        {"skyfire",      "Sky Fire"},
        {"skyfox",       "Sky Fox"},
        {"skykid",       "Sky Kid (New Ver.)"},
        {"skykidd",      "Sky Kid (60A1 Ver.)"},
        {"skykiddo",     "Sky Kid Deluxe (set 2)"},
        {"skykiddx",     "Sky Kid Deluxe (set 1)"},
        {"skykiddxo",    "Sky Kid Deluxe (set 2)"},
        {"skykido",      "Sky Kid (Old Ver.)"},
        {"skykids",      "Sky Kid (Sipem)"},
        {"skylancr",     "Sky Lancer"},
        {"skylancre",    "Sky Lancer (Esco Trading Co license)"},
        {"skyraid",      "Sky Raider"},
        {"skyraidr",     "Sky Raiders"},
        {"skyrobo",      "Sky Robo"},
        {"skyshark",     "Sky Shark (US)"},
        {"skysharka",    "Sky Shark (US, set 2)"},
        {"skysharkb",    "Sky Shark (bootleg)"},
        {"skyskipr",     "Sky Skipper"},
        {"skysmash",     "Sky Smasher"},
        {"skysoldr",     "Sky Soldiers (US)"},
        {"skytargt",     "Sky Target"},
        {"skywolf",      "Sky Wolf (set 1)"},
        {"skywolf2",     "Sky Wolf (set 2)"},
        {"skywolf3",     "Sky Wolf (set 3)"},
        {"sl2007",       "Shooting Love 2007 (Japan)"},
        {"slamdnk2",     "Slam Dunk 2 (ver JAA)"},
        {"slammast",     "Saturday Night Slam Masters (World 930713)"},
        {"slammastu",    "Saturday Night Slam Masters (USA 930713)"},
        {"slammasu",     "Saturday Night Slam Masters (US 930713)"},
        {"slapbtjp",     "Slap Fight (Japan bootleg)"},
        {"slapbtuk",     "Slap Fight (English bootleg)"},
        {"slapfigh",     "Slap Fight"},
        {"slapfigha",    "Slap Fight (A76 set, GX-006-A PCB)"},
        {"slapfighb1",   "Slap Fight (bootleg set 1)"},
        {"slapfighb2",   "Slap Fight (bootleg set 2)"},
        {"slapfighb3",   "Slap Fight (bootleg set 3)"},
        {"slapshot",     "Slap Shot (Japan)"},
        {"slapshotj",    "Slap Shot (Ver 2.2 J)"},
        {"slapshtr",     "Slap Shooter"},
        {"slasho",       "Slashout"},
        {"slashout",     "Slashout (GDS-0004)"},
        {"sleague",      "Super Major League (US)"},
        {"sliksh17",     "Slick Shot (V1.7)"},
        {"slikshot",     "Slick Shot (V2.2)"},
        {"slipstrm",     "Slipstream"},
        {"slipstrmh",    "Slip Stream (Hispanic 950515)"},
        {"slither",      "Slither (set 1)"},
        {"slithera",     "Slither (set 2)"},
        {"sliver",       "Sliver (set 1)"},
        {"slivera",      "Sliver (set 2)"},
        {"slmdunkj",     "Slam Dunk (Japan ver. JAA))"},
        {"slmdunkjd",    "Slam Dunk (ver JAA 1993 10.8) (dual screen with demux adapter)"},
        {"slrasslt",     "Solar Assault (ver UAA)"},
        {"slrassltj",    "Solar Assault Revised (ver JAA)"},
        {"slrassltj1",   "Solar Assault (ver JAA)"},
        {"slspirit",     "Solite Spirits"},
        {"sltpcycl",     "Pro Cycle Tele Cardioline (Salter Fitness Bike V.1.0, Checksum 02AB)"},
        {"sltpstep",     "Pro Stepper Tele Cardioline (Salter Fitness Stepper V.1.0, Checksum F208)"},
        {"slyspy",       "Sly Spy (US revision 3)"},
        {"slyspy2",      "Sly Spy (US revision 2)"},
        {"slyspy3",      "Sly Spy (US, revision 3)"},
        {"smarinef",     "Sega Marine Fishing"},
        {"smashtv",      "Smash T.V. (rev 8.00)"},
        {"smashtv3",     "Smash T.V. (rev 3.01)"},
        {"smashtv4",     "Smash T.V. (rev 4.00)"},
        {"smashtv5",     "Smash T.V. (rev 5.00)"},
        {"smashtv6",     "Smash T.V. (rev 6.00)"},
        {"smbomb",       "Super Muscle Bomber: The International Blowout (Japan 940831)"},
        {"smbombr1",     "Super Muscle Bomber: The International Blowout (Japan 940808)"},
        {"smgolf",       "Vs. Stroke and Match Golf (Men Version)"},
        {"smgolfb",      "Vs. Stroke and Match Golf (Men set 2)"},
        {"smgolfj",      "Vs. Stroke and Match Golf (Men Version) (Japan)"},
        {"smgp",         "Super Monaco GP (World, Rev B) (FD1094 317-0126a)"},
        {"smgp5",        "Super Monaco GP (World) (FD1094 317-0126)"},
        {"smgp5d",       "Super Monaco GP (World) (bootleg of FD1094 317-0126 set)"},
        {"smgp6",        "Super Monaco GP (World, Rev A) (FD1094 317-0126a)"},
        {"smgp6d",       "Super Monaco GP (World, Rev A) (bootleg of FD1094 317-0126a set)"},
        {"smgpd",        "Super Monaco GP (World, Rev B) (bootleg of FD1094 317-0126a set)"},
        {"smgpj",        "Super Monaco GP (Japan, Rev B) (FD1094 317-0124a)"},
        {"smgpja",       "Super Monaco GP (Japan, Rev A) (FD1094 317-0124a)"},
        {"smgpjd",       "Super Monaco GP (Japan, Rev B) (bootleg of FD1094 317-0124a set)"},
        {"smgpu",        "Super Monaco GP (US, Rev C) (FD1094 317-0125a)"},
        {"smgpu1",       "Super Monaco GP (US, Rev B) (FD1094 317-0125a)"},
        {"smgpu1d",      "Super Monaco GP (US, Rev B) (bootleg of FD1094 317-0125a set)"},
        {"smgpu2",       "Super Monaco GP (US, Rev A) (FD1094 317-0125a)"},
        {"smgpu2d",      "Super Monaco GP (US, Rev A) (bootleg of FD1094 317-0125a set)"},
        {"smgpud",       "Super Monaco GP (US, Rev C) (bootleg of FD1094 317-0125a set)"},
        {"smiconk",      "Space Micon Kit"},
        {"smissw",       "Super Miss World"},
        {"smlg99",       "World Series 99 / Super Major League 99"},
        {"smooncrs",     "Super Moon Cresta"},
        {"smotor",       "Super Motor (prototype)"},
        {"snakepit",     "Snake Pit"},
        {"snakepita",    "Snake Pit (9/14/84)"},
        {"snakjack",     "Snacks'n Jaxson"},
        {"snapjack",     "Snap Jack"},
        {"snapper",      "Snapper (Korea)"},
        {"sncwgltd",     "Sonic Wings Limited (JAPAN)"},
        {"sngkace",      "Sengoku Ace (Japan)"},
        {"sngkacea",     "Sengoku Ace (Japan, set 2)"},
        {"snowbalt",     "Snow Board Championship (set 2)"},
        {"snowboar",     "Snow Board Championship (set 1)"},
        {"snowboara",    "Snow Board Championship (Version 2.0)"},
        {"snowbro2",     "Snow Bros. 2 - With New Elves - Otenki Paradise"},
        {"snowbro2b",    "Snow Bros. 2 - With New Elves / Otenki Paradise (bootleg, set 1)"},
        {"snowbro2b2",   "Snow Bros. 2 - With New Elves / Otenki Paradise (bootleg, set 2)"},
        {"snowbro2b3",   "Snow Bros. 2 - With New Elves / Otenki Paradise (bootleg, set 3)"},
        {"snowbro2ny",   "Snow Bros. 2 - With New Elves / Otenki Paradise (Nyanko)"},
        {"snowbro3",     "Snow Brothers 3 - Magical Adventure"},
        {"snowbroa",     "Snow Bros. - Nick & Tom (set 2)"},
        {"snowbrob",     "Snow Bros. - Nick & Tom (set 3)"},
        {"snowbroj",     "Snow Bros. - Nick & Tom (Japan)"},
        {"snowbros",     "Snow Bros. - Nick & Tom (set 1)"},
        {"snowbrosa",    "Snow Bros. - Nick & Tom (set 2)"},
        {"snowbrosb",    "Snow Bros. - Nick & Tom (set 3)"},
        {"snowbrosc",    "Snow Bros. - Nick & Tom (set 4)"},
        {"snowbrosd",    "Snow Bros. - Nick & Tom (Dooyong license)"},
        {"snowbrosj",    "Snow Bros. - Nick & Tom (Japan)"},
        {"snowbroswb",   "Snow Bros. - Nick & Tom (The Winter Bobble hardware bootleg)"},
        {"socbrawl",     "Soccer Brawl"},
        {"socbrawlh",    "Soccer Brawl (NGH-031)"},
        {"soccer",       "Atari Soccer"},
        {"soccerss",     "Soccer Superstars (ver JAA)"},
        {"sokonuke",     "Sokonuke Taisen Game (Japan)"},
        {"sokyugrt",     "Soukyugurentai - Terra Diver"},
        {"solarfox",     "Solar Fox"},
        {"solarq",       "Solar Quest"},
        {"solarwar",     "Solar-Warrior"},
        {"soldam",       "Soldam"},
        {"soldamj",      "Soldam (Japan)"},
        {"soldivid",     "Sol Divide - The Sword Of Darkness"},
        {"soldividk",    "Sol Divide - The Sword Of Darkness (Korea)"},
        {"solfight",     "Solar Fight"},
        {"solfigtr",     "Solitary Fighter (World)"},
        {"solitaire",    "Solitaire (version 2.5)"},
        {"solomon",      "Solomon's Key (Japan)"},
        {"solomonj",     "Solomon no Kagi (Japan)"},
        {"solrwarr",     "Solar-Warrior (US)"},
        {"solvalou",     "Solvalou (Japan)"},
        {"sonic",        "Segasonic the Hedgehog (Japan rev. C)"},
        {"sonic2mb",     "Sonic The Hedgehog 2 (bootleg of Megadrive version)"},
        {"sonicbom",     "Sonic Boom"},
        {"sonicbomd",    "Sonic Boom (bootleg of FD1094 317-0053 set)"},
        {"soniccar",     "Waku Waku Sonic Patrol Car"},
        {"sonicfgt",     "SegaSonic Cosmo Fighter (World)"},
        {"sonicfgtj",    "SegaSonic Cosmo Fighter (Japan)"},
        {"sonicp",       "Segasonic the Hedgehog (Japan prototype)"},
        {"sonicwi",      "Sonic Wings (Japan)"},
        {"sonicwi2",     "Aero Fighters 2 / Sonic Wings 2"},
        {"sonicwi3",     "Aero Fighters 3 / Sonic Wings 3"},
        {"sonofphx",     "Son of Phoenix"},
        {"sonson",       "Son Son"},
        {"sonsonj",      "Son Son (Japan)"},
        {"sos",          "SOS"},
        {"sosterm",      "S.O.S."},
        {"sothello",     "Super Othello"},
        {"sotsugyo",     "Sotsugyo Shousho"},
        {"sotsugyok",    "Jor-eop Jeungmyeongseo (Korea)"},
        {"soukobdx",     "Souko Ban Deluxe (Japan)"},
        {"soulclbr",     "Soul Calibur (SOC1-VER.A)"},
        {"soulclbra",    "Soul Calibur (World, SOC12/VER.A2)"},
        {"soulclbrab",   "Soul Calibur (Asia, SOC14/VER.B)"},
        {"soulclbrja",   "Soul Calibur (Japan, SOC11/VER.A2)"},
        {"soulclbrjb",   "Soul Calibur (Japan, SOC11/VER.B)"},
        {"soulclbrjc",   "Soul Calibur (Japan, SOC11/VER.C)"},
        {"soulclbrub",   "Soul Calibur (US, SOC13/VER.B)"},
        {"soulclbruc",   "Soul Calibur (US, SOC13/VER.C)"},
        {"souledga",     "Soul Edge (SO3-VER.A)"},
        {"souledgb",     "Soul Edge (SO1-VER.A)"},
        {"souledge",     "Soul Edge Ver. II (SO4-VER.C)"},
        {"souledgea",    "Soul Edge (World, SO2/VER.A)"},
        {"souledgeja",   "Soul Edge (Japan, SO1/VER.A)"},
        {"souledgeua",   "Soul Edge (US, SO3/VER.A)"},
        {"souledgeuc",   "Soul Edge Ver. II (US, SO3/VER.C)"},
        {"soulsurf",     "Soul Surfer (Rev A)"},
        {"spacbat2",     "Space Battle (bootleg set 2)"},
        {"spacbatt",     "Space Battle"},
        {"spacbeam",     "Space Beam"},
        {"spacduel",     "Space Duel"},
        {"spacduel0",    "Space Duel (prototype)"},
        {"spacduel1",    "Space Duel (version 1)"},
        {"spaceat2",     "Space Attack II"},
        {"spaceatt",     "Space Attack"},
        {"spaceatt2k",   "Space Attack (bootleg of Space Invaders, 2k roms)"},
        {"spaceattbp",   "Space Attack (bootleg of Space Invaders, bproms)"},
        {"spacebrd",     "Space Bird (bootleg)"},
        {"spacecho",     "Space Echo"},
        {"spacecho2",    "Space Echo (set 2)"},
        {"spacecom",     "Space Combat (bootleg of Space Invaders)"},
        {"spacecr",      "Space Cruiser"},
        {"spacedem",     "Space Demon"},
        {"spacedx",      "Space Invaders DX (US) v2.1"},
        {"spacedxj",     "Space Invaders DX (Japan) v2.1"},
        {"spacedxo",     "Space Invaders DX (Japan) v2.0"},
        {"spacefb",      "Space Firebird (Nintendo)"},
        {"spacefbb",     "Space Firebird (bootleg)"},
        {"spacefbg",     "Space Firebird (Gremlin)"},
        {"spacefev",     "Space Fever (New Ver)"},
        {"spacefevo",    "Space Fever (Old Ver)"},
        {"spacefevo2",   "Space Fever (older version)"},
        {"spacefrt",     "Space Fortress"},
        {"spaceftr",     "Space Fortress (Zaccaria)"},
        {"spacegun",     "Space Gun (World)"},
        {"spacegunj",    "Space Gun (Japan)"},
        {"spacegunu",    "Space Gun (US)"},
        {"spaceint",     "Space Intruder"},
        {"spacelnc",     "Space Launcher"},
        {"spacempr",     "Space Empire (bootleg)"},
        {"spaceod",      "Space Odyssey"},
        {"spaceph",      "Space Phantoms"},
        {"spaceplt",     "Space Pilot"},
        {"spaceplta",    "Space Pilot (set 2)"},
        {"spaceshp",     "Space Ship"},
        {"spaceskr",     "Space Seeker"},
        {"spacetrk",     "Space Trek (upright)"},
        {"spacewar",     "Space Wars"},
        {"spacewr3",     "Space War Part 3"},
        {"spacezap",     "Space Zap"},
        {"spacfura",     "Space Fury (revision A)"},
        {"spacfury",     "Space Fury (revision C)"},
        {"spacfurya",    "Space Fury (revision A)"},
        {"spacfuryb",    "Space Fury (revision B)"},
        {"spacfurybl",   "Advisor (Italian bootleg of Space Fury)"},
        {"spacian2",     "T.T Spacian Part-2"},
        {"spacmiss",     "Space Missile - Space Fighting Game"},
        {"spactrai",     "Space Train"},
        {"spacwalk",     "Space Walk"},
        {"spang",        "Super Pang (World)"},
        {"spangbl",      "Super Pang (World 900914, bootleg, set 1)"},
        {"spangj",       "Super Pang (Japan 901023)"},
        {"sparkman",     "Spark Man (v 2.0)"},
        {"sparkmana",    "Spark Man (v2.0, set 2)"},
        {"sparkz",       "Sparkz (prototype)"},
        {"spartanx",     "Spartan X (Japan)"},
        {"spartanxtec",  "Spartan X (Tecfri hardware bootleg)"},
        {"spatter",      "Spatter"},
        {"spattera",     "Spatter (315-5099)"},
        {"spawn",        "Spawn: In the Demon's Hand (Rev B)"},
        {"spbactn",      "Super Pinball Action (US)"},
        {"spbactnj",     "Super Pinball Action (Japan)"},
        {"spbactnp",     "Super Pinball Action (US, prototype, dual screen)"},
        {"spcdrag",      "Space Dragon (bootleg of Moon Cresta)"},
        {"spcebttl",     "Space Battle (Space Invaders bootleg)"},
        {"spceking",     "Space King"},
        {"spcenctr",     "Space Encounters"},
        {"spcewarl",     "Space War (Leijac)"},
        {"spcewars",     "Space War (Sanritsu)"},
        {"spcforc2",     "Space Force (set 2)"},
        {"spcforce",     "Space Force"},
        {"spcfrcii",     "Special Forces II"},
        {"spcinv95",     "Space Invaders '95 - Attack Of The Lunar Loonies (World)"},
        {"spcinv95u",    "Space Invaders '95: The Attack Of Lunar Loonies (Ver 2.5A 1995/06/14)"},
        {"spcinvdj",     "Space Invaders DX (Japan F3 version)"},
        {"spcking2",     "Space King 2"},
        {"spclaser",     "Space Laser"},
        {"spclforc",     "Special Forces"},
        {"spclorda",     "Space Lords (alternate)"},
        {"spclords",     "Space Lords"},
        {"spclordsa",    "Space Lords (rev A)"},
        {"spclordsb",    "Space Lords (rev B)"},
        {"spclordsg",    "Space Lords (rev A, German)"},
        {"spcmission",   "Space Mission (SegaSA / Sonic, Spanish bootleg of Scramble)"},
        {"spcnv95u",     "Space Invaders '95 - Attack Of The Lunar Loonies (US)"},
        {"spcpostn",     "Space Position (Japan)"},
        {"spcrocks",     "Space Rocks (Spanish clone of Asteroids)"},
        {"spctbird",     "Space Thunderbird"},
        {"spctrek",      "Space Trek (Video Game S.A., Spanish bootleg of Scramble)"},
        {"spdball",      "Speed Ball (prototype)"},
        {"spdbuggy",     "Speed Buggy"},
        {"spdcoin",      "Speed Coin (prototype)"},
        {"spdheat",      "Super Dead Heat (World)"},
        {"spdheatj",     "Super Dead Heat (Japan)"},
        {"spdodgeb",     "Super Dodge Ball (US)"},
        {"speakhlp",     "Speak & Help"},
        {"speakres",     "Speak and Rescue"},
        {"speakresb",    "Speak & Rescue (bootleg)"},
        {"spec2k",       "Spectrum 2000 (Euro)"},
        {"spec2kh",      "Spectrum 2000 (horizontal, buggy) (Europe)"},
        {"spectar",      "Spectar (revision 3)"},
        {"spectar1",     "Spectar (revision 1[Q])"},
        {"speedatk",     "Speed Attack!"},
        {"speedbal",     "Speed Ball"},
        {"speedbala",    "Speed Ball (set 2)"},
        {"speedfrk",     "Speed Freak"},
        {"speedrcr",     "Speed Racer"},
        {"speedspn",     "Speed Spin"},
        {"speedup",      "Speed Up (version 2.20)"},
        {"speedup10",    "Speed Up (version 1.00)"},
        {"speedup12",    "Speed Up (version 1.20)"},
        {"speglsht",     "Super Eagle Shot"},
        {"spelnkrj",     "Spelunker (Japan)"},
        {"spelunk2",     "Spelunker II"},
        {"spelunkr",     "Spelunker"},
        {"spelunkrj",    "Spelunker (Japan)"},
        {"spf2t",        "Super Puzzle Fighter II Turbo (Euro 960529)"},
        {"spf2ta",       "Super Puzzle Fighter II Turbo (Asia 960529)"},
        {"spf2td",       "Super Puzzle Fighter II Turbo (USA 960620 Phoenix Edition) (bootleg)"},
        {"spf2th",       "Super Puzzle Fighter II Turbo (Hispanic 960531)"},
        {"spf2tu",       "Super Puzzle Fighter II Turbo (USA 960620)"},
        {"spf2xj",       "Super Puzzle Fighter II X (Japan 960531)"},
        {"spf2xjd",      "Super Puzzle Fighter II X (Japan 960531 Phoenix Edition) (bootleg)"},
        {"spider",       "Spider (Buena Vision, without nudity)"},
        {"spidern",      "Spider (Buena Vision, with nudity)"},
        {"spiders",      "Spiders (set 1)"},
        {"spiders2",     "Spiders (set 2)"},
        {"spiders3",     "Spiders (set 3)"},
        {"spidey",       "Spider-Man: The Videogame (US)"},
        {"spideyj",      "Spider-Man: The Videogame (World)"},
        {"spidman",      "Spider-Man: The Videogame (World)"},
        {"spidmanj",     "Spider-Man: The Videogame (Japan)"},
        {"spidmanu",     "Spider-Man: The Videogame (US, Rev A)"},
        {"spiero",       "Super Pierrot (Japan)"},
        {"spikeofe",     "Spikeout Final Edition (Export)"},
        {"spikeout",     "Spikeout (Export, Revision C)"},
        {"spiker",       "Spiker"},
        {"spikera",      "Spiker (5/5/86)"},
        {"spikerb",      "Spiker (earliest?)"},
        {"spikes91",     "1991 Spikes (Italian bootleg, set 1)"},
        {"spikes91b",    "1991 Spikes (Italian bootleg, set 2)"},
        {"spinkick",     "Hec's Spinkick"},
        {"spinlbrj",     "Spinal Breakers (Japan)"},
        {"spinlbrk",     "Spinal Breakers (World)"},
        {"spinlbrkj",    "Spinal Breakers (Japan)"},
        {"spinlbrku",    "Spinal Breakers (US)"},
        {"spinlbrkup",   "Spinal Breakers (US, prototype)"},
        {"spinlbru",     "Spinal Breakers (US)"},
        {"spinmast",     "Spin Master / Miracle Adventure"},
        {"spinner",      "Spinner"},
        {"spitboss",     "Super Pit Boss (9221-02A)"},
        {"spkrbtl",      "Spikers Battle (GDS-0005)"},
        {"splash",       "Splash! (Ver. 1.2 World)"},
        {"splash10",     "Splash! (Ver. 1.0 World)"},
        {"splashms",     "Splash (Modular System)"},
        {"splat",        "Splat!"},
        {"splatter",     "Splatter House (Japan)"},
        {"splatter2",    "Splatter House (World, old version (SH2))"},
        {"splatterj",    "Splatter House (Japan, SH1)"},
        {"splndrbt",     "Splendor Blast"},
        {"spnchotj",     "Super Punch-Out!! (Japan)"},
        {"spnchout",     "Super Punch-Out!!"},
        {"spnchouta",    "Super Punch-Out!! (Rev A)"},
        {"spnchoutj",    "Super Punch-Out!! (Japan)"},
        {"spool3",       "Super Pool III (World[Q])"},
        {"spool3i",      "Super Pool III (I-Vics)"},
        {"sprcros2",     "Super Cross 2 (Japan)"},
        {"sprcros2a",    "Super Cross II (Japan, set 2)"},
        {"sprglbpg",     "Super Glob (Pac-Man hardware) (German bootleg)"},
        {"sprglobp",     "Super Glob (Pac-Man hardware)"},
        {"springer",     "Springer"},
        {"sprint1",      "Sprint 1"},
        {"sprint2",      "Sprint 2 (set 1)"},
        {"sprint2a",     "Sprint 2 (set 2)"},
        {"sprint4",      "Sprint 4 (set 1)"},
        {"sprint4a",     "Sprint 4 (set 2)"},
        {"sprint4b",     "Sprint 4 (Rev 02, set 2)"},
        {"sprint8",      "Sprint 8"},
        {"sprint8a",     "Sprint 8 (play tag and chase)"},
        {"sprpuzzle",    "Super Puzzle (Sang Ho Soft)"},
        {"sprtauth",     "Sports Authority Challenge (Rev 3)"},
        {"sprtauth1",    "Sports Authority (Rev 1)"},
        {"sprtjam",      "Sports Jam (GDS-0003)"},
        {"sprtmtch",     "Sports Match"},
        {"sprtshot",     "Sports Shooting USA"},
        {"sptrekct",     "Space Trek (cocktail)"},
        {"spy",          "S.P.Y. - Special Project Y (World ver. N)"},
        {"spyhnt2a",     "Spy Hunter 2 (rev 1)"},
        {"spyhunt",      "Spy Hunter"},
        {"spyhunt2",     "Spy Hunter 2 (rev 2)"},
        {"spyhunt2a",    "Spy Hunter II (rev 1)"},
        {"spyhuntp",     "Spy Hunter (Playtronic license)"},
        {"spyhuntsp",    "Spy Hunter (Spain, Recreativos Franco S.A., Bally Midway license)"},
        {"spyu",         "S.P.Y. - Special Project Y (US ver. M)"},
        {"sqbert",       "Faster, Harder, More Challenging Q*bert (prototype)"},
        {"sqix",         "Super Qix (World/Japan, V1.2)"},
        {"sqixb1",       "Super Qix (bootleg of V1.0, 8031 MCU)"},
        {"sqixb2",       "Super Qix (bootleg, No MCU)"},
        {"sqixbl",       "Super Qix (bootleg)"},
        {"sqixr0",       "Super Qix (World/Japan, V1.0)"},
        {"sqixr1",       "Super Qix (World/Japan, V1.1)"},
        {"sqixu",        "Super Qix (US)"},
        {"squaitsa",     "Squash (Itisa)"},
        {"squash",       "Squash"},
        {"squizchs",     "Seishun-Quiz Colorful High School (CHS1 Ver.A)"},
        {"sraider",      "Space Raider"},
        {"srally2",      "Sega Rally 2 (Export)"},
        {"srally2dx",    "Sega Rally 2 Deluxe (Export)"},
        {"srally2p",     "Sega Rally 2 (prototype, 29 Dec 1997)"},
        {"srally2pa",    "Sega Rally 2 (prototype, 8 Dec 1997)"},
        {"srally2x",     "Sega Rally 2 DX"},
        {"srallyc",      "Sega Rally Championship - Twin/DX (Revision C)"},
        {"srallyca",     "Sega Rally Championship - DX (Revision A)"},
        {"srallycb",     "Sega Rally Championship - Twin/DX (Revision B)"},
        {"srallycc",     "Sega Rally Championship - Twin/DX (Revision A)"},
        {"srallycdx",    "Sega Rally Championship - DX (Revision A)"},
        {"srallycdxa",   "Sega Rally Championship - DX"},
        {"sranger",      "Super Ranger (v2.0)"},
        {"srangerb",     "Super Ranger (bootleg)"},
        {"srangern",     "Super Ranger (older, NOVA license)"},
        {"srangero",     "Super Ranger (older)"},
        {"srangerw",     "Super Ranger (WDK)"},
        {"srdarwin",     "Super Real Darwin (World)"},
        {"srdarwinj",    "Super Real Darwin (Japan)"},
        {"srdarwnj",     "Super Real Darwin (Japan)"},
        {"srdmissn",     "S.R.D. Mission"},
        {"srmdb",        "Sunset Riders (bootleg of Mega Drive version)"},
        {"srmp2",        "Super Real Mahjong Part 2 (Japan)"},
        {"srmp3",        "Super Real Mahjong Part 3 (Japan)"},
        {"srmp4",        "Super Real Mahjong PIV (Japan)"},
        {"srmp4o",       "Super Real Mahjong PIV (Japan, older set)"},
        {"srmp7",        "Super Real Mahjong P7 (Japan)"},
        {"srumbler",     "The Speed Rumbler (set 1)"},
        {"srumbler2",    "The Speed Rumbler (set 2)"},
        {"srumbler3",    "The Speed Rumbler (set 3)"},
        {"srumblr2",     "The Speed Rumbler (set 2)"},
        {"ss2005a",      "Super Shanghai 2005 (Rev A) (GDL-0031A)"},
        {"ssanchan",     "Sanrin San Chan (Japan)"},
        {"sscandal",     "Seishun Scandal (Japan)"},
        {"ssf2",         "Super Street Fighter II: The New Challengers (World 931005)"},
        {"ssf2a",        "Super Street Fighter II: The New Challengers (Asia 931005)"},
        {"ssf2ar1",      "Super Street Fighter II: The New Challengers (Asia 930914)"},
        {"ssf2h",        "Super Street Fighter II: The New Challengers (Hispanic 930911)"},
        {"ssf2j",        "Super Street Fighter II: The New Challengers (Japan 931005)"},
        {"ssf2jr1",      "Super Street Fighter II: The New Challengers (Japan 930911)"},
        {"ssf2jr2",      "Super Street Fighter II: The New Challengers (Japan 930910)"},
        {"ssf2mdb",      "Super Street Fighter II - The New Challengers (bootleg of Japanese Mega Drive version)"},
        {"ssf2r1",       "Super Street Fighter II: The New Challengers (World 930911)"},
        {"ssf2t",        "Super Street Fighter II Turbo (World 940223)"},
        {"ssf2ta",       "Super Street Fighter II Turbo (Asia 940223)"},
        {"ssf2tad",      "Super Street Fighter II Turbo (Asia 940223 Phoenix Edition) (bootleg)"},
        {"ssf2tb",       "Super Street Fighter II: The Tournament Battle (World 931119)"},
        {"ssf2tba",      "Super Street Fighter II: The Tournament Battle (Asia 931005)"},
        {"ssf2tbd",      "Super Street Fighter II: The Tournament Battle (World 931119 Phoenix Edition) (bootleg)"},
        {"ssf2tbh",      "Super Street Fighter II: The Tournament Battle (Hispanic 931005)"},
        {"ssf2tbj",      "Super Street Fighter II: The Tournament Battle (Japan 931005)"},
        {"ssf2tbj1",     "Super Street Fighter II: The Tournament Battle (Japan 930911)"},
        {"ssf2tbr1",     "Super Street Fighter II: The Tournament Battle (World 930911)"},
        {"ssf2tbu",      "Super Street Fighter II: The Tournament Battle (USA 930911)"},
        {"ssf2th",       "Super Street Fighter II Turbo (Hispanic 940223)"},
        {"ssf2tu",       "Super Street Fighter II Turbo (USA 940323)"},
        {"ssf2tur1",     "Super Street Fighter II Turbo (USA 940223)"},
        {"ssf2u",        "Super Street Fighter II: The New Challengers (USA 930911)"},
        {"ssf2ud",       "Super Street Fighter II: The New Challengers (USA 930911 Phoenix Edition) (bootleg)"},
        {"ssf2us2",      "Super Street Fighter II: The New Challengers Super 2 (USA 930911)"},
        {"ssf2xj",       "Super Street Fighter II X: Grand Master Challenge (Japan 940311)"},
        {"ssf2xjr1",     "Super Street Fighter II X: Grand Master Challenge (Japan 940223)"},
        {"ssf2xjr1d",    "Super Street Fighter II X: Grand Master Challenge (Japan 940223 Phoenix Edition) (bootleg)"},
        {"ssf2xjr1r",    "Super Street Fighter II X: Grand Master Challenge (Japan 940223 rent version)"},
        {"ssfindo",      "See See Find Out"},
        {"sshangha",     "Super Shanghai Dragon's Eye (Japan)"},
        {"sshanghab",    "Super Shanghai Dragon's Eye (World, bootleg)"},
        {"sshanghaj",    "Super Shanghai Dragon's Eye (Japan)"},
        {"sshanghak",    "Super Shanghai Dragon's Eye (Korea)"},
        {"sshanghb",     "Super Shanghai Dragon's Eye (World, bootleg)"},
        {"sshooter",     "Sharpshooter (Rev 1.7)"},
        {"sshooter11",   "Sharpshooter (Rev 1.1)"},
        {"sshooter12",   "Sharpshooter (Rev 1.2)"},
        {"sshooter17",   "Sharpshooter (Rev 1.7)"},
        {"sshot137",     "Shuffleshot (v1.37)"},
        {"ssi",          "Super Space Invaders '91 (World)"},
        {"ssia",         "Super Space Invaders '91 (World, revised code)"},
        {"ssib",         "Super Space Invaders '91 (World, earlier code base)"},
        {"ssideki",      "Super Sidekicks / Tokuten Ou"},
        {"ssideki2",     "Super Sidekicks 2 - The World Championship / Tokuten Ou 2 - Real Fight Football"},
        {"ssideki3",     "Super Sidekicks 3 - The Next Glory / Tokuten Ou 3 - eikoue no michi"},
        {"ssideki4",     "Ultimate 11 - The SNK Football Championship / Tokuten Ou - Honoo no Libero, The"},
        {"sslam",        "Super Slam (set 1)"},
        {"sslama",       "Super Slam (set 2)"},
        {"sslamb",       "Super Slam (set 3)"},
        {"ssmissin",     "S.S. Mission"},
        {"ssoldier",     "Superior Soldiers (US)"},
        {"ssonicbr",     "SegaSonic Bros (Japan, prototype)"},
        {"ssozumo",      "Syusse Oozumou (Japan)"},
        {"sspacaho",     "Space Attack - Head On"},
        {"sspacat2",     "Space Attack (upright, older)"},
        {"sspacatc",     "Space Attack (cocktail)"},
        {"sspaceat",     "Space Attack (upright)"},
        {"sspeedr",      "Super Speed Race"},
        {"sspiritj",     "Scramble Spirits (Japan, Floppy DS3-5000-02-REV-A Based)"},
        {"sspirits",     "Scramble Spirits"},
        {"sspring1",     "Super Sprint (German, rev 1)"},
        {"ssprint",      "Super Sprint (rev 4)"},
        {"ssprint1",     "Super Sprint (rev 1)"},
        {"ssprint3",     "Super Sprint (rev 3)"},
        {"ssprintf",     "Super Sprint (French)"},
        {"ssprintg",     "Super Sprint (German, rev 2)"},
        {"ssprintg1",    "Super Sprint (German, rev 1)"},
        {"ssprints",     "Super Sprint (Spanish)"},
        {"ssrdrabd",     "Sunset Riders (Asia 2 Players ver. ABD)"},
        {"ssrdrebc",     "Sunset Riders (World 2 Players ver. EBC)"},
        {"ssrdrebd",     "Sunset Riders (World 2 Players ver. EBD)"},
        {"ssrdrjbd",     "Sunset Riders (Japan 2 Players ver. JBD)"},
        {"ssrdruac",     "Sunset Riders (US 4 Players ver. UAC)"},
        {"ssrdrubc",     "Sunset Riders (US 2 Players ver. UBC)"},
        {"ssrdruda",     "Sunset Riders (US 4 Players ver. UDA)"},
        {"ssriders",     "Sunset Riders (World 4 Players ver. EAC)"},
        {"ssridersabd",  "Sunset Riders (2 Players ver ABD)"},
        {"ssridersadd",  "Sunset Riders (4 Players ver ADD)"},
        {"ssriderseaa",  "Sunset Riders (4 Players ver EAA)"},
        {"ssridersebc",  "Sunset Riders (2 Players ver EBC)"},
        {"ssridersebd",  "Sunset Riders (2 Players ver EBD)"},
        {"ssridersjac",  "Sunset Riders (4 Players ver JAC)"},
        {"ssridersjad",  "Sunset Riders (4 Players ver JAD)"},
        {"ssridersjbd",  "Sunset Riders (2 Players ver JBD)"},
        {"ssridersuab",  "Sunset Riders (4 Players ver UAB)"},
        {"ssridersuac",  "Sunset Riders (4 Players ver UAC)"},
        {"ssridersubc",  "Sunset Riders (2 Players ver UBC)"},
        {"ssridersuda",  "Sunset Riders (4 Players ver UDA)"},
        {"ssrj",         "Super Speed Race Junior (Japan)"},
        {"sss",          "Steep Slope Sliders"},
        {"sstarcrs",     "Super Star Crest"},
        {"sstingry",     "Super Stingray"},
        {"sstrangr",     "Space Stranger"},
        {"sstrike",      "Super Strike Bowling"},
        {"sstriker",     "Sorcer Striker (World)"},
        {"sstrikerk",    "Sorcer Striker (Korea)"},
        {"sstrkfgt",     "Sega Strike Fighter (Rev A)"},
        {"sstrkfgta",    "Sega Strike Fighter (Rev A, no training mode)"},
        {"sstrngr2",     "Space Stranger 2"},
        {"stactics",     "Space Tactics"},
        {"stadhero",     "Stadium Hero (Japan)"},
        {"stadhr96",     "Stadium Hero '96 (Europe, EAJ, Tuning license)"},
        {"stadhr96j",    "Stadium Hero '96 (Japan, EAD)"},
        {"stadhr96k",    "Stadium Hero '96 (Korea, Dream Island license)"},
        {"stadhr96u",    "Stadium Hero '96 (USA, EAH)"},
        {"stagger1",     "Stagger I (Japan)"},
        {"stakwin",      "Stakes Winner / Stakes Winner - GI kinzen seihae no michi"},
        {"stakwin2",     "Stakes Winner 2"},
        {"stankatk",     "Super Tank Attack (prototype rev. 1.12)"},
        {"starblad",     "Starblade"},
        {"starbladj",    "Starblade (ST1, Japan)"},
        {"starcas",      "Star Castle (version 3)"},
        {"starcas1",     "Star Castle (older)"},
        {"starcasc",     "Star Castle (cocktail)"},
        {"starcase",     "Star Castle (Mottoeis)"},
        {"starcasp",     "Star Castle (prototype)"},
        {"starcrus",     "Star Cruiser"},
        {"starfght",     "Star Fighter"},
        {"starfgmc",     "Starfighter (bootleg of Moon Cresta)"},
        {"starfigh",     "Star Fighter (v1)"},
        {"starfir2",     "Star Fire 2"},
        {"starfira",     "Star Fire (set 2)"},
        {"starfire",     "Star Fire (set 1)"},
        {"starfirea",    "Star Fire (set 2)"},
        {"starforc",     "Star Force"},
        {"starforca",    "Star Force (encrypted, set 2)"},
        {"starforcb",    "Star Force (encrypted, bootleg)"},
        {"starforce",    "Star Force (encrypted, set 1)"},
        {"starfore",     "Star Force (encrypted)"},
        {"stargate",     "Stargate"},
        {"starglad",     "Star Gladiator (USA 960627)"},
        {"stargrds",     "Star Guards"},
        {"starhawk",     "Star Hawk"},
        {"starhrcl",     "Star Horse (satellite)"},
        {"starhrct",     "Star Horse (server)"},
        {"starhrpr",     "Star Horse Progress Returns (satellite)"},
        {"starhrse",     "Star Horse (big screens)"},
        {"starhrsp",     "Star Horse Progress (satellite) (Rev A)"},
        {"starjack",     "Star Jacker (Sega)"},
        {"starjacks",    "Star Jacker (Stern Electronics)"},
        {"starjacs",     "Star Jacker (Stern)"},
        {"starlstr",     "Vs. Star Luster"},
        {"starrkr",      "Star Raker"},
        {"starseek",     "Doki Doki Idol Star Seeker (GDL-0005)"},
        {"starshp1",     "Starship 1"},
        {"starshpp",     "Starship 1 (prototype[Q])"},
        {"starswep",     "Star Sweep (STP1-VER.A)"},
        {"starswepj",    "Star Sweep (Japan, STP1/VER.A)"},
        {"startrek",     "Star Trek"},
        {"startrgn",     "Star Trigon (Japan, STT1 Ver.A)"},
        {"startrkd",     "Star Trek (bootleg of Defender)"},
        {"startrks",     "Star Trek (Head On hardware)"},
        {"starw",        "Star Wars"},
        {"starw1",       "Star Wars (bootleg of Galaxy Wars, set 2)"},
        {"starwar1",     "Star Wars (rev 1)"},
        {"starwars",     "Star Wars (rev 2)"},
        {"starwars1",    "Star Wars (set 2)"},
        {"starwarso",    "Star Wars (set 3)"},
        {"statriv2",     "Triv Two"},
        {"statriv2v",    "Triv Two (Vertical)"},
        {"statriv4",     "Triv Four"},
        {"stcc",         "Sega Touring Car Championship (newer)"},
        {"stcca",        "Sega Touring Car Championship (Revision A)"},
        {"stccb",        "Sega Touring Car Championship (Revision B)"},
        {"stcco",        "Sega Touring Car Championship"},
        {"stdragon",     "Saint Dragon"},
        {"stdragona",    "Saint Dragon (set 2)"},
        {"stdragonb",    "Saint Dragon (bootleg)"},
        {"stealsee",     "Steal See"},
        {"steelta1",     "Steel Talons (rev 1)"},
        {"steeltag",     "Steel Talons (German, rev 2)"},
        {"steeltal",     "Steel Talons (rev 2)"},
        {"steeltal1",    "Steel Talons (rev 1)"},
        {"steeltalg",    "Steel Talons (German, rev 2)"},
        {"steeltap",     "Steel Talons (prototype)"},
        {"steelwkr",     "Steel Worker"},
        {"stellcas",     "Stellar Castle (Elettronolo)"},
        {"stera",        "Steraranger (bootleg of Moon Cresta)"},
        {"stfight",      "Street Fight (Germany)"},
        {"stfighta",     "Street Fight (bootleg?)"},
        {"stfightgb",    "Street Fight (Germany - Benelux)"},
        {"stg",          "Strike Gunner S.T.G"},
        {"stinger",      "Stinger"},
        {"stinger2",     "Stinger (prototype[Q])"},
        {"stkclmns",     "Stack Columns (Japan)"},
        {"stkclmnsj",    "Stack Columns (Japan)"},
        {"stlforce",     "Steel Force"},
        {"stmblade",     "Storm Blade (US)"},
        {"stmbladej",    "Storm Blade (Japan)"},
        {"stocker",      "Stocker"},
        {"stoffy",       "Super Toffy"},
        {"stoffyu",      "Super Toffy (Unico license)"},
        {"stompin",      "Stompin'"},
        {"stompina",     "Stompin' (prototype?)"},
        {"stoneage",     "Stoneage"},
        {"stoneba2",     "Stone Ball (2 Players)"},
        {"stonebal",     "Stone Ball (4 Players)"},
        {"stonebal2",    "Stone Ball (2 Players, v1-20 7/11/1994)"},
        {"stonebal2o",   "Stone Ball (2 Players, v1-20 21/10/1994)"},
        {"storming",     "Storming Party - Riku Kai Kuu Saizensen"},
        {"storminga",    "Storming Party / Riku Kai Kuu Saizensen (set 2)"},
        {"strahl",       "Koutetsu Yousai Strahl (Japan set 1)"},
        {"strahla",      "Koutetsu Yousai Strahl (Japan set 2)"},
        {"strahlj",      "Koutetsu Yousai Strahl (Japan set 1)"},
        {"strahlja",     "Koutetsu Yousai Strahl (Japan set 2)"},
        {"strahljbl",    "Koutetsu Yousai Strahl (Japan, bootleg)"},
        {"stratab",      "Strata Bowling (V3)"},
        {"stratab1",     "Strata Bowling (V1)"},
        {"stratgys",     "Strategy X (Stern)"},
        {"stratgyx",     "Strategy X"},
        {"stratof",      "Raiga - Strato Fighter (US)"},
        {"stratvox",     "Stratovox"},
        {"stratvoxa",    "Stratovox (set 2)"},
        {"stratvoxb",    "Stratovox (bootleg)"},
        {"streakng",     "Streaking"},
        {"streaknga",    "Streaking (set 2)"},
        {"streets1",     "Street Smart (US version 1)"},
        {"streetsj",     "Street Smart (Japan version 1)"},
        {"streetsm",     "Street Smart (US version 2)"},
        {"streetsm1",    "Street Smart (US version 1)"},
        {"streetsmj",    "Street Smart (Japan version 1)"},
        {"streetsmw",    "Street Smart (World version 1)"},
        {"streetsw",     "Street Smart (World version 1)"},
        {"strfbomb",     "Strafe Bomb (bootleg of Scramble)"},
        {"strhoop",      "Street Hoop / Street Slam / Dunk Dream"},
        {"strider",      "Strider (US set 1)"},
        {"strider2",     "Strider 2 (USA 991213)"},
        {"striderj",     "Strider Hiryu (Japan set 1)"},
        {"striderjr",    "Strider Hiryu (Japan Resale Ver.)"},
        {"striderua",    "Strider (USA, B-Board 89624B-3)"},
        {"strideruc",    "Strider (USA, B-Board 90629B-3, buggy Street Fighter II conversion)"},
        {"stridr2a",     "Strider 2 (ASIA 991213)"},
        {"stridrja",     "Strider Hiryu (Japan set 2)"},
        {"stridrua",     "Strider (US set 2)"},
        {"striv",        "Super Triv (English questions)"},
        {"strivf",       "Super Triv (French questions)"},
        {"strkfgtr",     "Strike Fighter (World)"},
        {"strkfgtrj",    "Strike Fighter (Japan)"},
        {"strkforc",     "Strike Force (rev 1 02-25-91)"},
        {"strkzone",     "Strike Zone Baseball"},
        {"strnskil",     "Strength and Skill"},
        {"strongx",      "Strong X"},
        {"strtdriv",     "Street Drivin' (prototype)"},
        {"strtheat",     "Street Heat - Cardinal Amusements"},
        {"strtheata",    "Street Heat (set 2, older?)"},
        {"strvmstr",     "Super Trivia Master"},
        {"stunrn2e",     "S.T.U.N. Runner (rev 2, Europe)"},
        {"stunrn3e",     "S.T.U.N. Runner (rev 3, Europe)"},
        {"stunrun",      "S.T.U.N. Runner (rev 6)"},
        {"stunrun0",     "S.T.U.N. Runner (rev 0)"},
        {"stunrun2",     "S.T.U.N. Runner (rev 2)"},
        {"stunrun2e",    "S.T.U.N. Runner (rev 2, Europe)"},
        {"stunrun3",     "S.T.U.N. Runner (rev 3)"},
        {"stunrun3e",    "S.T.U.N. Runner (rev 3, Europe)"},
        {"stunrun4",     "S.T.U.N. Runner (rev 4)"},
        {"stunrun5",     "S.T.U.N. Runner (rev 5)"},
        {"stunrune",     "S.T.U.N. Runner (rev 5, Europe)"},
        {"stunrunj",     "S.T.U.N. Runner (rev 7, Japan)"},
        {"stunrunp",     "S.T.U.N. Runner (upright prototype)"},
        {"stuntair",     "Stunt Air"},
        {"stvbios",      "ST-V Bios"},
        {"sub",          "Submarine (Sigma)"},
        {"subhunt",      "Sub Hunter"},
        {"subroc3d",     "Subroc-3D"},
        {"subs",         "Subs"},
        {"sucasino",     "Super Casino"},
        {"suikoenb",     "Suikoenbu"},
        {"sunaq",        "SunA Quiz 6000 Academy (940620-6)"},
        {"sundance",     "Sundance"},
        {"sunsetbl",     "Sunset Riders (bootleg 4 Players ver. ADD)"},
        {"supbtime",     "Super Burger Time (World)"},
        {"supbtimea",    "Super Burger Time (World, set 2)"},
        {"supbtimej",    "Super Burger Time (Japan)"},
        {"supbtimj",     "Super Burger Time (Japan)"},
        {"supdrapo",     "Super Draw Poker"},
        {"supduck",      "Super Duck"},
        {"superabc",     "Super ABC (Pac-Man multigame kit, Sep. 03 1999)"},
        {"superabco",    "Super ABC (Pac-Man multigame kit, Mar. 08 1999)"},
        {"superbar",     "Super Bar"},
        {"superbik",     "Superbike"},
        {"superbikg",    "Superbike (bootleg on Galaxian hardware)"},
        {"superbon",     "Agent Super Bond (Super Cobra conversion)"},
        {"superbug",     "Super Bug"},
        {"superchs",     "Super Chase - Criminal Termination (US)"},
        {"superchsj",    "Super Chase - Criminal Termination (Japan)"},
        {"superchsp",    "Super Chase - Criminal Termination (1992/10/26 20:24:29 CHASE 3 VER 1.1, prototype)"},
        {"superchsp2",   "Super Chase - Criminal Termination (1992/01/18 18:29:18 CHASE 3 VER 1.3O, prototype)"},
        {"superchsu",    "Super Chase - Criminal Termination (US)"},
        {"superg",       "Super Galaxians"},
        {"supergm3",     "Super Game III"},
        {"supergs",      "Super Galaxians (Silver Systems)"},
        {"superinv",     "Super Invaders"},
        {"superman",     "Superman"},
        {"supermanj",    "Superman (Japan)"},
        {"supermanu",    "Superman (US)"},
        {"superpac",     "Super Pac-Man"},
        {"superpacm",    "Super Pac-Man (Midway)"},
        {"superpcm",     "Super Pac-Man (Midway)"},
        {"superqix",     "Super Qix"},
        {"supershp",     "Super Ship"},
        {"superspy",     "The Super Spy"},
        {"superten",     "Super Ten V8.3"},
        {"supertnk",     "Super Tank"},
        {"supertr2",     "Super Triv II"},
        {"supertr3",     "Super Triv III"},
        {"superx",       "Super-X (NTC)"},
        {"superxm",      "Super-X (Mitchell)"},
        {"supinvsion",   "Super Invasion (Electromar, Spanish)"},
        {"suplup",       "Super Lup Lup Puzzle / Zhuan Zhuan Puzzle (version 4.0 / 990518)"},
        {"supmodel",     "Super Model"},
        {"supmodl2",     "Super Model II"},
        {"suprglob",     "Super Glob"},
        {"suprgolf",     "Super Crowns Golf (World)"},
        {"suprgolfj",    "Super Crowns Golf (Japan)"},
        {"suprheli",     "Super Heli (bootleg of Super Cobra)"},
        {"suprleag",     "Super League"},
        {"suprloco",     "Super Locomotive"},
        {"suprlocoo",    "Super Locomotive"},
        {"suprmatk",     "Super Missile Attack"},
        {"suprmatkd",    "Super Missile Attack (not encrypted)"},
        {"suprmous",     "Super Mouse"},
        {"suprmrio",     "Vs. Super Mario Bros."},
        {"suprmrioa",    "Vs. Super Mario Bros. (set ?, harder)"},
        {"suprmriobl",   "Vs. Super Mario Bros. (bootleg with Z80, set 1)"},
        {"suprmriobl2",  "Vs. Super Mario Bros. (bootleg with Z80, set 2)"},
        {"suprridr",     "Super Rider"},
        {"suprslam",     "Super Slams"},
        {"suprtrio",     "Super Trio"},
        {"supxevs",      "Vs. Super Xevious"},
        {"suratk",       "Surprise Attack (World ver. K)"},
        {"suratka",      "Surprise Attack (Asia ver. L)"},
        {"suratkj",      "Surprise Attack (Japan ver. M)"},
        {"surfplnt",     "Surf Planet (version 4.1)"},
        {"surfplnt20",   "Surf Planet (version 2.0)"},
        {"surfplnt30",   "Surf Planet (version 3.0)"},
        {"surfplnt40",   "Surf Planet (version 4.0)"},
        {"surpratk",     "Surprise Attack (Japan ver. M)"},
        {"survarts",     "Survival Arts (USA)"},
        {"survartsj",    "Survival Arts (Japan)"},
        {"survartsu",    "Survival Arts (USA)"},
        {"survival",     "Survival"},
        {"sushibar",     "Sushi Bar / Toretore! Sushi"},
        {"sutapper",     "Tapper (Suntory)"},
        {"suzuk8h2",     "Suzuka 8 Hours 2 (Japan)"},
        {"suzuk8h2j",    "Suzuka 8 Hours 2 (Japan, Rev B)"},
        {"suzuk8hj",     "Suzuka 8 Hours (Japan)"},
        {"suzuka8h",     "Suzuka 8 Hours (World[Q])"},
        {"suzuka8hj",    "Suzuka 8 Hours (Japan, Rev B)"},
        {"suzume",       "Watashiha Suzumechan (Japan)"},
        {"svc",          "SvC Chaos - SNK vs Capcom (MVS)"},
        {"svcboot",      "SvC Chaos - SNK vs Capcom (Bootleg)"},
        {"svcpcb",       "SvC Chaos - SNK vs Capcom (JAMMA PCB)"},
        {"svcpcba",      "SNK vs. Capcom - SVC Chaos (JAMMA PCB, set 2)"},
        {"svcplus",      "SvC Chaos - SNK vs Capcom Plus (set 1, bootleg)"},
        {"svcplusa",     "SvC Chaos - SNK vs Capcom Plus (set 2, bootleg)"},
        {"svcsplus",     "SvC Chaos - SNK vs Capcom Super Plus (bootleg)"},
        {"svf",          "Super Visual Football - European Sega Cup"},
        {"svfo",         "Super Visual Football: European Sega Cup"},
        {"svolley",      "Super Volleyball (Japan)"},
        {"svolleyk",     "Super Volleyball (Korea)"},
        {"svolleyu",     "Super Volleyball (US)"},
        {"svolleyua",    "Super Volleyball (US)"},
        {"svolly91",     "Super Volley '91 (Japan)"},
        {"svs",          "Super Visual Soccer - Sega Cup (US)"},
        {"swa",          "Star Wars Arcade (US)"},
        {"swaj",         "Star Wars Arcade (Japan)"},
        {"swarm",        "Swarm"},
        {"swat",         "SWAT"},
        {"swatpolc",     "SWAT Police"},
        {"swcourt",      "Super World Court (Japan)"},
        {"swcourtb",     "Super World Court (World, bootleg)"},
        {"swcourtj",     "Super World Court (Japan)"},
        {"swimmer",      "Swimmer (set 1)"},
        {"swimmera",     "Swimmer (set 2)"},
        {"swimmerb",     "Swimmer (set 3)"},
        {"sws",          "Super World Stadium (Japan)"},
        {"sws92",        "Super World Stadium '92 (Japan)"},
        {"sws92g",       "Super World Stadium '92 Gekitouban (Japan)"},
        {"sws93",        "Super World Stadium '93 (Japan)"},
        {"sws95",        "Super World Stadium '95 (Japan)"},
        {"sws96",        "Super World Stadium '96 (Japan)"},
        {"sws97",        "Super World Stadium '97 (Japan)"},
        {"sws98",        "Super World Stadium '98 (Japan, SS81/VER.A)"},
        {"sws99",        "Super World Stadium '99 (SS91-VER.A)"},
        {"swtrilgy",     "Star Wars Trilogy Arcade (Export, Revision A)"},
        {"swtrilgya",    "Star Wars Trilogy Arcade (Export)"},
        {"swtrilgyp",    "Star Wars Trilogy Arcade (location test, 16.09.98)"},
        {"sxevious",     "Super Xevious"},
        {"sxeviousj",    "Super Xevious (Japan)"},
        {"sxyreac2",     "Pachinko Sexy Reaction 2 (Japan)"},
        {"sxyreact",     "Pachinko Sexy Reaction (Japan)"},
        {"syvalion",     "Syvalion (Japan)"},
        {"syvalionp",    "Syvalion (World, prototype)"},
        {"syvalionu",    "Syvalion (US, PS2 Taito Legends 2)"},
        {"syvalionw",    "Syvalion (World, PS2 Taito Legends 2)"},
        {"szaxxon",      "Super Zaxxon"},
};

const char *lookup_s(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_s(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
