#include <string.h>
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"p47",         "P-47 - The Phantom Fighter (World)"},
        {"p47aces",     "P-47 Aces"},
        {"p47acesa",    "P-47 Aces (ver 1.0)"},
        {"p47b",        "P-47 - The Freedom Fighter (World, bootleg)"},
        {"p47j",        "P-47 - The Freedom Fighter (Japan)"},
        {"p47je",       "P-47 - The Freedom Fighter (Japan, Export)"},
        {"pac90",       "Pac-Man (bootleg on World Cup '90 hardware)"},
        {"pacapp",      "Paca Paca Passion (PPP1-VERA)"},
        {"pacapp2",     "Paca Paca Passion 2 (Japan, PKS1/VER.A)"},
        {"pacappsp",    "Paca Paca Passion Special (Japan, PSP1/VER.A)"},
        {"paccarn",     "Pac-Carnival"},
        {"pacgal",      "Pac-Gal"},
        {"pacgal2",     "Pac-Gal (set 2)"},
        {"pacheart",    "Pac-Man (Hearts)"},
        {"pachifev",    "Pachifever"},
        {"pachiten",    "Medal Mahjong Pachi-Slot Tengoku [BET] (Japan)"},
        {"packbang",    "Pack'n Bang Bang"},
        {"packbangp",   "Pack'n Bang Bang (prototype)"},
        {"pacland",     "Pac-Land (set 1)"},
        {"pacland2",    "Pac-Land (set 2)"},
        {"pacland3",    "Pac-Land (set 3)"},
        {"paclandj",    "Pac-Land (Japan new)"},
        {"paclandjo",   "Pac-Land (Japan old)"},
        {"paclandjo2",  "Pac-Land (Japan older)"},
        {"paclandm",    "Pac-Land (Midway)"},
        {"paclandm2",   "Pac-Land (Bally-Midway)"},
        {"paclandp",    "Pac-Land (United Amusements PC Engine)"},
        {"pacman",      "Pac-Man (Midway)"},
        {"pacmanbl",    "Pac-Man (Galaxian hardware)"},
        {"pacmanbla",   "Pac-Man (bootleg on Galaxian hardware, set 2)"},
        {"pacmanblb",   "Pac-Man (bootleg on Moon Alien 'AL-10A1' hardware)"},
        {"pacmanblci",  "Pac-Man (Cirsa, Spanish bootleg on Galaxian hardware)"},
        {"pacmanblv",   "Pac-Man (Video Dens, Spanish bootleg on Galaxian hardware, set 1)"},
        {"pacmanblva",  "Pac-Man (Video Dens, Spanish bootleg on Galaxian hardware, set 2)"},
        {"pacmanf",     "Pac-Man (speedup hack)"},
        {"pacmanfm",    "Pac Man (FAMARE S.A. bootleg of Puck Man)"},
        {"pacmania",    "Pac-Mania"},
        {"pacmaniaj",   "Pac-Mania (Japan)"},
        {"pacmaniao",   "Pac-Mania (111187 sound program)"},
        {"pacmanij",    "Pac-Mania (Japan)"},
        {"pacmanjpm",   "Pac-Man (JPM bootleg)"},
        {"pacmanmr",    "Pac-Man (Model Racing bootleg)"},
        {"pacmanpe",    "Come Come (Petaco SA bootleg of Puck Man)"},
        {"pacmanso",    "Pac-Man (SegaSA / Sonic)"},
        {"pacmansp",    "Puck Man (Spanish, 'Made in Greece' bootleg)"},
        {"pacmanug",    "Pac Man (U.Games bootleg of Puck Man)"},
        {"pacmanvg",    "Pac-Man (Video Game SA bootleg)"},
        {"pacmod",      "Pac-Man (Midway, harder)"},
        {"pacnchmp",    "Pac-Man & Chomp Chomp"},
        {"pacnpal",     "Pac & Pal"},
        {"pacnpal2",    "Pac & Pal (older)"},
        {"pacplus",     "Pac-Man Plus"},
        {"pacuman",     "Pacu-Man (Spanish bootleg of Puck Man)"},
        {"paddle2",     "Paddle 2"},
        {"paddlema",    "Paddle Mania"},
        {"painter",     "Painter (hack of Crush Roller)"},
        {"paintlad",    "Painted Lady (Splash) (Ver. 1.3 US)"},
        {"paintrlr",    "Paint Roller"},
        {"pairlove",    "Pairs Love"},
        {"pairs",       "Pairs (V1.2, 09-30-94)"},
        {"pairsa",      "Pairs (09-07-94)"},
        {"pairsnb",     "Pairs (Nichibutsu) (Japan 890822)"},
        {"pairsred",    "Pairs Redemption (V1.0, 10/25/94)"},
        {"pairsten",    "Pairs (System Ten) (Japan 890826)"},
        {"pajaroes",    "Pajaro del Espacio (Spanish bootleg of UniWar S)"},
        {"palamed",     "Palamedes (Japan)"},
        {"palamedj",    "Palamedes (Japan)"},
        {"pandoras",    "Pandora's Palace"},
        {"pang",        "Pang (World)"},
        {"pang3",       "Pang! 3 (Euro 950511)"},
        {"pang3b",      "Pang! 3 (bootleg, set 1)"},
        {"pang3b2",     "Pang! 3 (bootleg, set 2)"},
        {"pang3b3",     "Pang! 3 (bootleg, set 3)"},
        {"pang3b4",     "Pang! 3 (bootleg, set 4)"},
        {"pang3b5",     "Pang! 3 (bootleg, set 5)"},
        {"pang3j",      "Pang! 3 (Japan 950511)"},
        {"pang3r1",     "Pang! 3 (Europe 950511)"},
        {"pangb",       "Pang (bootleg)"},
        {"pangb2",      "Pang (bootleg, set 4)"},
        {"pangba",      "Pang (bootleg, set 3)"},
        {"pangbb",      "Pang (bootleg, set 5)"},
        {"pangbc",      "Pang (bootleg, set 7)"},
        {"pangbold",    "Pang (bootleg, set 2)"},
        {"pangpang",    "Pang Pang"},
        {"pangpomm",    "Pang Poms (Mitchell)"},
        {"pangpoms",    "Pang Poms"},
        {"pangpomsm",   "Pang Pom's (Mitchell)"},
        {"pangpomsn",   "Pang Pom's (Nova)"},
        {"panic",       "Space Panic (version E)"},
        {"panic2",      "Space Panic (set 2)"},
        {"panic3",      "Space Panic (set 3)"},
        {"panicbom",    "Panic Bomber"},
        {"panicger",    "Space Panic (German)"},
        {"panich",      "Space Panic (harder)"},
        {"panicstr",    "Panic Street (Japan)"},
        {"panikuru",    "Panikuru Panekuru (Japan, PPA1 Ver.A)"},
        {"panther",     "Panther (bootleg?)"},
        {"paperboy",    "Paperboy (rev 3)"},
        {"paperboyr1",  "Paperboy (rev 1)"},
        {"paperboyr2",  "Paperboy (rev 2)"},
        {"paperbr1",    "Paperboy (rev 1)"},
        {"paperbr2",    "Paperboy (rev 2)"},
        {"paprazzi",    "Paparazzi"},
        {"para2dx",     "Paradise 2 Deluxe"},
        {"paradise",    "Paradise"},
        {"paradisea",   "Paradise (set 2)"},
        {"paradisee",   "Paradise (Escape)"},
        {"paradlx",     "Paradise Deluxe"},
        {"parodisj",    "Parodius DA! (Japan)"},
        {"parodius",    "Parodius DA! (World)"},
        {"parodiusa",   "Parodius Da!: Shinwa kara Owarai e (Asia)"},
        {"parodiuse",   "Parodius Da!: Shinwa kara Owarai e (World, set 2)"},
        {"parodiusj",   "Parodius Da!: Shinwa kara Owarai e (Japan)"},
        {"pasha2",      "Pasha Pasha 2"},
        {"pass",        "Pass"},
        {"passht4b",    "Passing Shot (4 Players) (bootleg)"},
        {"passsht",     "Passing Shot (2 Players)"},
        {"passsht16a",  "Passing Shot (Japan, 4 Players, System 16A) (FD1094 317-0071)"},
        {"passshta",    "Passing Shot (World, 4 Players) (FD1094 317-0074)"},
        {"passshtad",   "Passing Shot (World, 4 Players) (bootleg of FD1094 317-0074 set)"},
        {"passshtb",    "Passing Shot (2 Players) (bootleg)"},
        {"passshtd",    "Passing Shot (World, 2 Players) (bootleg of FD1094 317-0080 set)"},
        {"passshtj",    "Passing Shot (Japan, 4 Players) (FD1094 317-0070)"},
        {"passshtjd",   "Passing Shot (Japan, 4 Players) (bootleg of FD1094 317-0070 set)"},
        {"pastelgl",    "Pastel Gal (Japan 851224)"},
        {"pastelis",    "Pastel Island (Japan, prototype)"},
        {"patapata",    "Pata Pata Panic"},
        {"patimono",    "Mahjong Pachinko Monogatari (Japan)"},
        {"pbactio2",    "Pinball Action (set 2)"},
        {"pbaction",    "Pinball Action (set 1)"},
        {"pbaction2",   "Pinball Action (set 2, encrypted)"},
        {"pbaction3",   "Pinball Action (set 3, encrypted)"},
        {"pbaction4",   "Pinball Action (set 4, encrypted)"},
        {"pbactiont",   "Pinball Action (Tecfri license)"},
        {"pballoon",    "Pioneer Balloon"},
        {"pballoonr",   "Pioneer Balloon (Rock-Ola license)"},
        {"pbancho",     "Gyakuten!! Puzzle Bancho (Japan)"},
        {"pbanchoa",    "Gyakuten!! Puzzle Bancho (Japan, set 2)"},
        {"pbchmp95",    "Pinball Champ '95"},
        {"pbillian",    "Prebillian"},
        {"pbillianb",   "Prebillian (bootleg)"},
        {"pbillrd",     "Perfect Billiard"},
        {"pbillrdbl",   "Perfect Billiard (bootleg)"},
        {"pbillrds",    "Perfect Billiard (Sega)"},
        {"pbillrdsa",   "Perfect Billiard (MC-8123, 317-5008)"},
        {"pblbeach",    "Pebble Beach - The Great Shot"},
        {"pbobbl2j",    "Puzzle Bobble 2 (Japan)"},
        {"pbobbl2n",    "Puzzle Bobble 2 / Bust-A-Move Again (Neo-Geo)"},
        {"pbobbl2u",    "Bust-A-Move Again (US)"},
        {"pbobbl2x",    "Puzzle Bobble 2X (Japan)"},
        {"pbobbl3j",    "Puzzle Bobble 3 (Japan)"},
        {"pbobbl3u",    "Puzzle Bobble 3 (US)"},
        {"pbobbl4j",    "Puzzle Bobble 4 (Japan)"},
        {"pbobbl4u",    "Puzzle Bobble 4 (US)"},
        {"pbobble",     "Puzzle Bobble (Japan, B-System)"},
        {"pbobble2",    "Puzzle Bobble 2 (World)"},
        {"pbobble2j",   "Puzzle Bobble 2 (Ver 2.2J 1995/07/20)"},
        {"pbobble2o",   "Puzzle Bobble 2 (Ver 2.2O 1995/07/20)"},
        {"pbobble2u",   "Bust-A-Move Again (Ver 2.3A 1995/07/31)"},
        {"pbobble2x",   "Puzzle Bobble 2X (Ver 2.2J 1995/11/11)"},
        {"pbobble3",    "Puzzle Bobble 3 (World)"},
        {"pbobble3j",   "Puzzle Bobble 3 (Ver 2.1J 1996/09/27)"},
        {"pbobble3u",   "Puzzle Bobble 3 (Ver 2.1A 1996/09/27)"},
        {"pbobble4",    "Puzzle Bobble 4 (World)"},
        {"pbobble4j",   "Puzzle Bobble 4 (Ver 2.04J 1997/12/19)"},
        {"pbobble4u",   "Puzzle Bobble 4 (Ver 2.04A 1997/12/19)"},
        {"pbobblen",    "Puzzle Bobble / Bust-A-Move (Neo-Geo) (set 1)"},
        {"pbobblenb",   "Puzzle Bobble / Bust-A-Move (Neo-Geo, bootleg)"},
        {"pbobblna",    "Puzzle Bobble / Bust-A-Move (Neo-Geo) (set 2)"},
        {"pbss330",     "Pit Boss Superstar III 30 (9233-00-01 R0B, Standard version)"},
        {"pbss330a",    "Pit Boss Superstar III 30 (9233-00-01 R0, Standard version)"},
        {"pbss330ca",   "Pit Boss Superstar III 30 (9233-00-06 R0A, California version)"},
        {"pbst30",      "Pit Boss Supertouch 30 (9234-10-01 R0)"},
        {"pbst30a",     "Pit Boss Supertouch 30 (9234-00-01 R0A)"},
        {"pc_1942",     "PlayChoice-10 - 1942"},
        {"pc_bball",    "PlayChoice-10 - Baseball"},
        {"pc_bfght",    "PlayChoice-10 - Balloon Fight"},
        {"pc_bload",    "Bases Loaded (Prototype, PlayChoice-10)"},
        {"pc_bstar",    "PlayChoice-10 - Baseball Stars"},
        {"pc_cntra",    "PlayChoice-10 - Contra"},
        {"pc_cshwk",    "PlayChoice-10 - Captain Sky Hawk"},
        {"pc_cvnia",    "PlayChoice-10 - Castlevania"},
        {"pc_dbldr",    "PlayChoice-10 - Double Dribble"},
        {"pc_ddrgn",    "PlayChoice-10 - Double Dragon"},
        {"pc_drmro",    "PlayChoice-10 - Dr. Mario"},
        {"pc_duckh",    "PlayChoice-10 - Duck Hunt"},
        {"pc_ebike",    "PlayChoice-10 - Excite Bike"},
        {"pc_ftqst",    "PlayChoice-10 - Uncle Fester's Quest - The Addams Family"},
        {"pc_gntlt",    "PlayChoice-10 - Gauntlet"},
        {"pc_golf",     "PlayChoice-10 - Golf"},
        {"pc_goons",    "PlayChoice-10 - The Goonies"},
        {"pc_grdue",    "PlayChoice-10 - Gradius (older)"},
        {"pc_grdus",    "PlayChoice-10 - Gradius"},
        {"pc_hgaly",    "PlayChoice-10 - Hogan's Alley"},
        {"pc_kngfu",    "PlayChoice-10 - Kung Fu"},
        {"pc_mario",    "PlayChoice-10 - Mario Bros."},
        {"pc_miket",    "PlayChoice-10 - Mike Tyson's Punchout"},
        {"pc_mman3",    "PlayChoice-10 - Mega Man 3"},
        {"pc_moglf",    "PlayChoice-10 - Mario's Open Golf"},
        {"pc_mtoid",    "PlayChoice-10 - Metroid"},
        {"pc_ngai2",    "PlayChoice-10 - Ninja Gaiden 2"},
        {"pc_ngai3",    "PlayChoice-10 - Ninja Gaiden 3"},
        {"pc_ngaid",    "PlayChoice-10 - Ninja Gaiden"},
        {"pc_pinbt",    "PlayChoice-10 - PinBot"},
        {"pc_pwbld",    "PlayChoice-10 - Power Blade"},
        {"pc_pwrst",    "PlayChoice-10 - Pro Wrestling"},
        {"pc_radr2",    "PlayChoice-10 - Rad Racer II"},
        {"pc_radrc",    "PlayChoice-10 - Rad Racer"},
        {"pc_rcpam",    "PlayChoice-10 - RC Pro Am"},
        {"pc_rkats",    "PlayChoice-10 - Rockin' Kats"},
        {"pc_rnatk",    "PlayChoice-10 - Rush N' Attack"},
        {"pc_rrngr",    "PlayChoice-10 - Chip'n Dale - Rescue Rangers"},
        {"pc_rygar",    "PlayChoice-10 - Rygar"},
        {"pc_sjetm",    "PlayChoice-10 - Solar Jetman"},
        {"pc_smb",      "PlayChoice-10 - Super Mario Bros."},
        {"pc_smb2",     "PlayChoice-10 - Super Mario Bros. 2"},
        {"pc_smb3",     "PlayChoice-10 - Super Mario Bros. 3"},
        {"pc_suprc",    "PlayChoice-10 - Super C"},
        {"pc_tbowl",    "PlayChoice-10 - Tecmo Bowl"},
        {"pc_tenis",    "PlayChoice-10 - Tennis"},
        {"pc_tkfld",    "PlayChoice-10 - Track and Field"},
        {"pc_tmnt",     "PlayChoice-10 - Teenage Mutant Ninja Turtles"},
        {"pc_tmnt2",    "PlayChoice-10 - Teenage Mutant Ninja Turtles II"},
        {"pc_trjan",    "PlayChoice-10 - Trojan"},
        {"pc_ttoon",    "Tiny Toon Adventures (prototype) (PlayChoice-10)"},
        {"pc_vball",    "PlayChoice-10 - Volley Ball"},
        {"pc_virus",    "Virus (Dr. Mario prototype, PlayChoice-10)"},
        {"pc_wcup",     "PlayChoice-10 - Nintendo World Cup"},
        {"pc_wgnmn",    "PlayChoice-10 - Wild Gunman"},
        {"pc_ynoid",    "PlayChoice-10 - Yo! Noid"},
        {"pcktgal",     "Pocket Gal (Japan)"},
        {"pcktgal2",    "Pocket Gal 2 (World[Q])"},
        {"pcktgal2j",   "Pocket Gal 2 (Japanese)"},
        {"pcktgalb",    "Pocket Gal (bootleg)"},
        {"pclubj",      "Print Club (Japan Vol.1)"},
        {"pclubjv2",    "Print Club (Japan Vol.2)"},
        {"pclubjv4",    "Print Club (Japan Vol.4)"},
        {"pclubjv5",    "Print Club (Japan Vol.5)"},
        {"pclubys",     "Puzzle Club (Yun Sung, set 1)"},
        {"pclubysa",    "Puzzle Club (Yun Sung, set 2)"},
        {"pdrift",      "Power Drift (World, Rev A)"},
        {"pdrifta",     "Power Drift (World)"},
        {"pdrifte",     "Power Drift (World, Earlier)"},
        {"pdriftj",     "Power Drift (Japan)"},
        {"pdriftl",     "Power Drift - Link Version (Japan, Rev A)"},
        {"peekaboo",    "Peek-a-Boo!"},
        {"peekaboou",   "Peek-a-Boo! (North America, ver 1.0)"},
        {"peepshow",    "Nozokimeguri Mahjong Peep Show (Japan 890404)"},
        {"peggle",      "Peggle (Joystick, v1.0)"},
        {"pegglet",     "Peggle (Trackball, v1.0)"},
        {"peivc006",    "Player's Edge Plus (IVC006) Clear EEPROM Chip"},
        {"penbros",     "Penguin Brothers (Japan)"},
        {"penfan",      "Penfan Girls - Step1. Mild Mind (set 1)"},
        {"penfana",     "Penfan Girls - Step1. Mild Mind (set 2)"},
        {"pengadvb",    "Penguin Adventure (bootleg of MSX version, encrypted)"},
        {"pengadvb2",   "Penguin Adventure (bootleg of MSX version, not encrypted)"},
        {"pengo",       "Pengo (set 1 rev c)"},
        {"pengo2",      "Pengo (set 2)"},
        {"pengo2u",     "Pengo (set 2 not encrypted)"},
        {"pengo3u",     "Pengo (set 3 not encrypted)"},
        {"pengoa",      "Pengo (World, 315-5010 type, set 1)"},
        {"pengob",      "Pengo (bootleg)"},
        {"pengoc",      "Pengo (World, 315-5010 type, set 3)"},
        {"pengoj",      "Pengo (Japan, not encrypted)"},
        {"pengoja",     "Pengo (Japan, 315-5010 type, rev C)"},
        {"pengojb",     "Pengo (Japan, 315-5007 type, rev A)"},
        {"pengojbl",    "Pengo (Japan, bootleg)"},
        {"pengojpm",    "Pengo (bootleg on Pac-Man hardware, set 1)"},
        {"pengomc1",    "Pengo (Marti Colls bootleg on Pac-Man hardware, set 1)"},
        {"pengomc2",    "Pengo (Marti Colls bootleg on Pac-Man hardware, set 2)"},
        {"pengopac",    "Pengo (bootleg on Pac-Man hardware, set 2)"},
        {"penky",       "Penky"},
        {"penkyi",      "Penky (Italian)"},
        {"penta",       "Penta"},
        {"pepper2",     "Pepper II"},
        {"pepper27",    "Pepper II (version 7)"},
        {"percuss",     "The Percussor"},
        {"perestro",    "Perestroika Girls"},
        {"perestrof",   "Perestroika Girls (Fuuki license)"},
        {"perfrman",    "Performan (Japan)"},
        {"perfrmanu",   "Performan (US)"},
        {"perfrmau",    "Performan (US)"},
        {"pesadelo",    "Pesadelo (bootleg of Konami Knightmare)"},
        {"peset001",    "Player's Edge Plus (SET001) Set Chip"},
        {"peset004",    "Player's Edge Plus (SET004) Set Chip"},
        {"peset012",    "Player's Edge Plus (SET012) Set Chip"},
        {"peset022",    "Player's Edge Plus (SET022) Set Chip"},
        {"peset033",    "Player's Edge Plus (SET033) Set Chip"},
        {"peset038",    "Player's Edge Plus (SET038) Set Chip"},
        {"peset100",    "Player's Edge Plus (SET100) Set Chip"},
        {"peset117",    "Player's Edge Plus (SET117) Set Chip"},
        {"pestplce",    "Pest Place"},
        {"peterpak",    "Peter Pack-Rat"},
        {"pettanp",     "Pettan Pyuu (Japan)"},
        {"pfghtj",      "Pocket Fighter (Japan 970904)"},
        {"pgalvip",     "Pocket Gals V.I.P (set 1)"},
        {"pgalvipa",    "Pocket Gals V.I.P (set 2)"},
        {"pgear",       "Powered Gear: Strategic Variant Armor Equipment (Japan 941024)"},
        {"pgearr1",     "Powered Gear: Strategic Variant Armor Equipment (Japan 940916)"},
        {"pgoal",       "Pleasure Goal / Futsal - 5 on 5 Mini Soccer"},
        {"phantasm",    "Phantasm (Japan)"},
        {"phantom2",    "Phantom II"},
        {"phantoma",    "Phantomas"},
        {"phelios",     "Phelios (Japan)"},
        {"pheliosj",    "Phelios (Japan)"},
        {"phklad",      "Klad / Labyrinth (Photon System)"},
        {"phoenix",     "Phoenix (Amstar)"},
        {"phoenix2",    "Phoenix (Amstar, set 2)"},
        {"phoenix3",    "Phoenix (T.P.N.)"},
        {"phoenixa",    "Phoenix (Centuri)"},
        {"phoenixass",  "Phoenix (Assa, Spanish bootleg)"},
        {"phoenixb",    "Phoenix (Centuri, set 2)"},
        {"phoenixbl",   "Phoenix (bootleg)"},
        {"phoenixc",    "Phoenix (IRECSA, G.G.I Corp)"},
        {"phoenixc2",   "Phoenix (G.G.I. Corporation, set 1)"},
        {"phoenixc3",   "Phoenix (G.G.I. Corporation, set 2)"},
        {"phoenixc4",   "Phoenix (G.G.I. Corporation, set 3)"},
        {"phoenixdal",  "Phoenix (D&L bootleg)"},
        {"phoenixgu",   "Phoenix (G. Universal Video bootleg)"},
        {"phoenixha",   "Phoenix (Hellomat Automaten bootleg)"},
        {"phoenixj",    "Phoenix (Taito Japan)"},
        {"phoenixs",    "Phoenix (Sonic, Spanish bootleg)"},
        {"phoenixt",    "Phoenix (Taito)"},
        {"phoenxp2",    "Phoenix Part 2"},
        {"photof",      "Photo Finish (bootleg?)"},
        {"photoy2k",    "Photo Y2K"},
        {"phozon",      "Phozon (Japan)"},
        {"phozons",     "Phozon (Sidam)"},
        {"phpython",    "Python (Photon System)"},
        {"phrcraze",    "Phraze Craze (6221-40, U5-3A Expanded Questions)"},
        {"phrcrazea",   "Phraze Craze (6221-40, U5-3 Expanded Questions)"},
        {"phrcrazeb",   "Phraze Craze (6221-40, U5-0A)"},
        {"phrcrazec",   "Phraze Craze (6221-40, U5-0)"},
        {"phrcrazev",   "Phraze Craze (6221-45, U5-2 Vertical)"},
        {"phtetris",    "Tetris (Photon System)"},
        {"pickin",      "Pickin'"},
        {"pignewt",     "Pig Newton (version C)"},
        {"pignewta",    "Pig Newton (version A)"},
        {"pigout",      "Pigout"},
        {"pigouta",     "Pigout (alternate)"},
        {"pigskin",     "Pigskin 621AD"},
        {"pigskina",    "Pigskin 621AD (rev 2.0 7/06/90)"},
        {"pigskinb",    "Pigskin 621AD (rev 1.1 6/05/90)"},
        {"pikkaric",    "Pikkari Chance"},
        {"pinbo",       "Pinbo"},
        {"pinboa",      "Pinbo (set 2)"},
        {"pinbos",      "Pinbo (Strike)"},
        {"pingpong",    "Ping Pong"},
        {"pinguinos",   "Pinguinos (Spanish bootleg on Pac-Man hardware)"},
        {"pinkswts",    "Pink Sweets: Ibara Sorekara (2006/04/06 MASTER VER....)"},
        {"pinkswtsa",   "Pink Sweets: Ibara Sorekara (2006/04/06 MASTER VER...)"},
        {"pinkswtsb",   "Pink Sweets: Ibara Sorekara (2006/04/06 MASTER VER.)"},
        {"pinkswtssc",  "Pink Sweets: Suicide Club (2017/10/31 SUICIDECLUB VER., bootleg)"},
        {"pinkswtsx",   "Pink Sweets: Ibara Sorekara (2006/xx/xx MASTER VER.)"},
        {"pipedrm",     "Pipe Dream (US)"},
        {"pipedrmj",    "Pipe Dream (Japan)"},
        {"pipedrmt",    "Pipe Dream (Taiwan)"},
        {"pipedrmu",    "Pipe Dream (US)"},
        {"pipeline",    "Pipeline"},
        {"pipibibi",    "Pipi and Bibis - Whoopee!! (bootleg [Q])"},
        {"pipibibs",    "Pipi and Bibis - Whoopee!!"},
        {"pipibibsa",   "Pipi & Bibis / Whoopee!! (Z80 sound cpu, set 2)"},
        {"pipibibsbl",  "Pipi & Bibis / Whoopee!! (Ryouta Kikaku bootleg, encrypted)"},
        {"pipibibsbl3", "Pipi & Bibis / Whoopee!! (Ryouta Kikaku bootleg, decrypted)"},
        {"pipibibsp",   "Pipi & Bibis / Whoopee!! (prototype)"},
        {"piranha",     "Piranha"},
        {"piranhah",    "Piranha (hack)"},
        {"piranhao",    "Piranha (older)"},
        {"pirates",     "Pirates"},
        {"piratesb",    "Pirates (set 2)"},
        {"piratesh",    "Pirate Ship (ver UAA)"},
        {"piratetr",    "Pirate Treasure"},
        {"piratpet",    "Pirate Pete"},
        {"pisces",      "Pisces"},
        {"piscesb",     "Pisces (bootleg)"},
        {"pistoldm",    "Pistol Daimyo no Bouken (Japan)"},
        {"pitapat",     "Pitapat Puzzle (set 1)"},
        {"pitapata",    "Pitapat Puzzle (set 2)"},
        {"pitboss2",    "Pit Boss II (9221-01C)"},
        {"pitbossa",    "The Pit Boss (2214-07, U5-0)"},
        {"pitbossm",    "Pit Boss Megastar (9244-00-01 R0B)"},
        {"pitbossma",   "Pit Boss Megastar (9244-00-01 R0)"},
        {"pitbossmb",   "Pit Boss Megastar (9243-00-01 R0)"},
        {"pitbosss",    "Pit Boss Superstar (9221-10-00B)"},
        {"pitbosssa",   "Pit Boss Superstar (9221-10-00A)"},
        {"pitbosssc",   "Pit Boss Superstar (9221-12-01, California version)"},
        {"pitbosssm",   "Pit Boss Superstar (9221-12-02, Minnesota version)"},
        {"pitfall2",    "Pitfall II"},
        {"pitfall2a",   "Pitfall II (315-5093, Flicky Conversion)"},
        {"pitfall2u",   "Pitfall II (not encrypted)"},
        {"pitfallu",    "Pitfall II (not encrypted)"},
        {"pitfigh3",    "Pit Fighter (rev 3)"},
        {"pitfighb",    "Pit Fighter (bootleg)"},
        {"pitfighj",    "Pit Fighter (Japan, 2 players)"},
        {"pitfight",    "Pit Fighter (rev 4)"},
        {"pitfight1p2", "Pit Fighter (rev 1, 2 players)"},
        {"pitfight2",   "Pit Fighter (rev 2)"},
        {"pitfight3",   "Pit Fighter (rev 3)"},
        {"pitfight4",   "Pit Fighter (rev 4)"},
        {"pitfight5",   "Pit Fighter (rev 5)"},
        {"pitfight6",   "Pit Fighter (rev 6)"},
        {"pitfight7",   "Pit Fighter (rev 7)"},
        {"pitfightb",   "Pit Fighter (bootleg)"},
        {"pitfightj",   "Pit Fighter (Japan rev 3, 2 players)"},
        {"pitnrun",     "Pit and Run"},
        {"pitnruna",    "Pit & Run - F-1 Race"},
        {"pitnrunb",    "Pit & Run - F-1 Race (location test?)"},
        {"pjustic",     "Project Justice / Moero! Justice Gakuen (Rev B)"},
        {"pjustica",    "Project Justice / Moero! Justice Gakuen (Rev A)"},
        {"pkgnsh",      "Pachinko Gindama Shoubu (Japan)"},
        {"pkgnshdx",    "Pachinko Gindama Shoubu DX (Japan)"},
        {"pkladiel",    "Poker Ladies (Leprechaun)"},
        {"pkladies",    "Poker Ladies"},
        {"pkscram",     "PK Scramble"},
        {"pktgaldj",    "Pocket Gal Deluxe (Japan v3.00)"},
        {"pktgaldx",    "Pocket Gal Deluxe (Euro v3.00)"},
        {"pktgaldxa",   "Pocket Gal Deluxe (Asia v3.00)"},
        {"pktgaldxb",   "Pocket Gal Deluxe (Europe v3.00, bootleg)"},
        {"pktgaldxj",   "Pocket Gal Deluxe (Japan v3.00)"},
        {"pkunwar",     "Penguin-Kun Wars (US)"},
        {"pkunwarj",    "Penguin-Kun Wars (Japan)"},
        {"pkunwarja",   "Penguin-Kun Wars (Japan, set 2)"},
        {"platoon",     "Vs. Platoon"},
        {"playball",    "PlayBall! (prototype)"},
        {"playch10",    "PlayChoice-10"},
        {"plctr13b",    "Police Trainer (Rev 1.3B)"},
        {"plegends",    "Power Instinct Legends (USA)"},
        {"plegendsj",   "Gouketsuji Gaiden - Saikyou Densetsu (Japan, Ver. 95.06.20)"},
        {"pleiadbl",    "Pleiads (bootleg)"},
        {"pleiadce",    "Pleiads (Centuri)"},
        {"pleiads",     "Pleiads (Tehkan)"},
        {"pleiadsb2",   "Pleiads (bootleg set 2)"},
        {"pleiadsgmp",  "Pleiads (GMP Games)"},
        {"pleiadsi",    "Pleiads (Irecsa, set 1)"},
        {"pleiadsia",   "Pleiads (Irecsa, set 2)"},
        {"pleiadsn",    "Pleiads (Niemer S.A.)"},
        {"pleiadss",    "Pleiads (Famaresa, Spanish bootleg)"},
        {"plgirls",     "Play Girls"},
        {"plgirls2",    "Play Girls 2"},
        {"plgirls2b",   "Play Girls 2 (bootleg)"},
        {"plotting",    "Plotting (World)"},
        {"plottinga",   "Plotting (World set 2, protected)"},
        {"plottingb",   "Plotting (World set 3, earliest version)"},
        {"plottingu",   "Plotting (US)"},
        {"pltkids",     "Pilot Kids (Model 2B, Revision A)"},
        {"pltkidsa",    "Pilot Kids (Model 2A)"},
        {"plumppop",    "Plump Pop (Japan)"},
        {"plusalph",    "Plus Alpha"},
        {"plygonet",    "Polygonet Commanders (ver UAA)"},
        {"pnickj",      "Pnickies (Japan 940608)"},
        {"pnyaa",       "Pochi and Nyaa"},
        {"pnyaaa",      "Pochi and Nyaa (Ver 2.00)"},
        {"pockchv2",    "Pocket Challenge V2"},
        {"pocketrc",    "Pocket Racer (Japan, PKR1/VER.B)"},
        {"poitto",      "Poitto!"},
        {"poizone",     "Poizone"},
        {"pokasuka",    "Pokasuka Ghost! (Japan)"},
        {"pokechmp",    "Poke Champ (set 1)"},
        {"pokechmpa",   "Poke Champ (set 2)"},
        {"pokerout",    "Potten's Poker stealth with Breakout front game"},
        {"pokonyan",    "Pokonyan! Balloon (Japan 940322)"},
        {"polaris",     "Polaris (set 1)"},
        {"polarisa",    "Polaris (set 2)"},
        {"polarisb",    "Polaris (first revision)"},
        {"polarisbr",   "Polaris (Brazil)"},
        {"polariso",    "Polaris (original version)"},
        {"polepos",     "Pole Position"},
        {"polepos1",    "Pole Position (Atari version 1)"},
        {"polepos2",    "Pole Position II"},
        {"polepos2a",   "Pole Position II (Atari)"},
        {"polepos2b",   "Pole Position II (bootleg)"},
        {"polepos2bi",  "Gran Premio F1 (Italian bootleg of Pole Position II)"},
        {"polepos2bs",  "Gran Premio F1 (Spanish bootleg of Pole Position II)"},
        {"poleposa",    "Pole Position (Atari version 2)"},
        {"poleposa1",   "Pole Position (Atari version 1)"},
        {"poleposa1n",  "Pole Position (Atari version 1 on Namco PCB)"},
        {"poleposa2",   "Pole Position (Atari version 2)"},
        {"poleposj",    "Pole Position (Japan)"},
        {"poleps2a",    "Pole Position II (Atari)"},
        {"poleps2b",    "Pole Position II (bootleg)"},
        {"policeto",    "Police Trainer (Rev 1.1)"},
        {"policetr",    "Police Trainer (Rev 1.3)"},
        {"policetr10",  "Police Trainer (Rev 1.0)"},
        {"policetr11",  "Police Trainer (Rev 1.1)"},
        {"policetr13",  "Police Trainer (Rev 1.3)"},
        {"policetr13a", "Police Trainer (Rev 1.3B Newer, Rev 0.5B PCB)"},
        {"policetr13b", "Police Trainer (Rev 1.3B, Rev 0.5B PCB)"},
        {"pollux",      "Pollux (set 1)"},
        {"polluxa",     "Pollux (set 2)"},
        {"polluxa2",    "Pollux (set 3)"},
        {"polluxn",     "Pollux (Japan, NTC license, distributed by Atlus)"},
        {"polynetw",    "Poly-Net Warriors (ver JAA)"},
        {"polyplay",    "Poly-Play"},
        {"polyplay2",   "Poly-Play (ZRE-PP)"},
        {"polyplay2c",  "Poly-Play (ZRE-PP - Czech)"},
        {"polystar",    "Tobe! Polystars (ver JAA)"},
        {"pompingw",    "Pomping World (Japan)"},
        {"ponchin",     "Mahjong Pon Chin Kan (Japan set 1)"},
        {"ponchina",    "Mahjong Pon Chin Kan (Japan set 2)"},
        {"pong",        "Pong (Rev E)"},
        {"pongd",       "Pong Doubles"},
        {"ponpoko",     "Ponpoko"},
        {"ponpokov",    "Ponpoko (Venture Line)"},
        {"poolshrk",    "Poolshark"},
        {"poosho",      "Poosho Poosho"},
        {"pootan",      "Pootan"},
        {"pooyan",      "Pooyan"},
        {"pooyans",     "Pooyan (Stern)"},
        {"pop_hh",      "Popper (bootleg of Hard Head)"},
        {"popbingo",    "Pop Bingo"},
        {"popbounc",    "Pop 'n Bounce / Gapporin"},
        {"popeye",      "Popeye (revision D)"},
        {"popeyeb2",    "Popeye (bootleg set 2)"},
        {"popeyeb3",    "Popeye (bootleg set 3)"},
        {"popeyebl",    "Popeye (bootleg)"},
        {"popeyef",     "Popeye (revision F)"},
        {"popeyehs",    "Popeye (Braze High Score Kit P1.00D)"},
        {"popeyej",     "Popeye (Japan)"},
        {"popeyejo",    "Popeye (Japan, Older)"},
        {"popeyeman",   "Popeye-Man"},
        {"popeyeu",     "Popeye (revision D not protected)"},
        {"popflama",    "Pop Flamer (not protected)"},
        {"popflamb",    "Pop Flamer (hack[Q])"},
        {"popflame",    "Pop Flamer (protected)"},
        {"popflamea",   "Pop Flamer (not protected)"},
        {"popflameb",   "Pop Flamer (hack?)"},
        {"popflamen",   "Pop Flamer (bootleg on Naughty Boy PCB)"},
        {"popn1",       "Pop'n Music 1 (ver TA-A, HDD 1.01)"},
        {"popn1a",      "Pop'n Music 1 (ver AA-A, HDD 1.00)"},
        {"popn1j",      "Pop'n Music 1 (ver JA-A, HDD 1.00)"},
        {"popn1k",      "Pop'n Music 1 (ver KA-A, HDD 1.01)"},
        {"popn2",       "Pop'n Music 2 (ver JA-A)"},
        {"popn3",       "Pop'n Music 3 (ver JA-A)"},
        {"popn4",       "Pop'n Music 4"},
        {"popn5",       "Pop'n Music 5"},
        {"popn6",       "Pop'n Music 6"},
        {"popn7",       "Pop'n Music 7"},
        {"popn8",       "Pop'n Music 8"},
        {"popnanm",     "Pop'n Music Animelo"},
        {"popnanm2",    "Pop'n Music Animelo 2"},
        {"popnanm2a",   "Pop'n Music Animelo 2 (license expired)"},
        {"popnanma",    "Pop'n Music Animelo (license expired)"},
        {"popnmt",      "Pop'n Music Mickey Tunes"},
        {"popnmt2",     "Pop'n Music Mickey Tunes!"},
        {"popnpop",     "Pop 'N Pop (World)"},
        {"popnpopj",    "Pop 'N Pop (Japan)"},
        {"popnpopu",    "Pop 'N Pop (US)"},
        {"popnstex",    "Pop'n Stage EX (ver JB-A)"},
        {"popobear",    "PoPo Bear"},
        {"popper",      "Popper"},
        {"popspops",    "Pop's Pop's"},
        {"porky",       "Porky"},
        {"porter",      "Port Man (bootleg on Moon Cresta hardware)"},
        {"portera",     "El Estivador (Spanish bootleg of Port Man on Galaxian hardware)"},
        {"portman",     "Port Man"},
        {"portmanj",    "Port Man (Japan)"},
        {"portrait",    "Portraits"},
        {"potogold",    "Pot of Gold"},
        {"potopoto",    "Poto Poto (Japan)"},
        {"poundfor",    "Pound for Pound (World)"},
        {"poundforj",   "Pound for Pound (Japan)"},
        {"poundforu",   "Pound for Pound (US)"},
        {"poundfou",    "Pound for Pound (US)"},
        {"pow",         "P.O.W. - Prisoners of War (US)"},
        {"powa",        "P.O.W. - Prisoners of War (US version 1, mask ROM sprites)"},
        {"powb",        "P.O.W. - Prisoners of War (bootleg of US version 1)"},
        {"powerbal",    "Power Balls"},
        {"powerbals",   "Power Balls (Super Slam conversion)"},
        {"powerdrv",    "Power Drive"},
        {"powerina",    "Power Instinct (USA bootleg) (set 2)"},
        {"powerins",    "Power Instinct (USA bootleg) (set 1)"},
        {"powerinsa",   "Power Instinct (USA, bootleg set 1)"},
        {"powerinsb",   "Power Instinct (USA, bootleg set 2)"},
        {"powerinsj",   "Gouketsuji Ichizoku (Japan)"},
        {"powerinspj",  "Gouketsuji Ichizoku (Japan, prototype)"},
        {"powerinspu",  "Power Instinct (USA, prototype)"},
        {"powj",        "Datsugoku - Prisoners of War (Japan)"},
        {"powrplay",    "Power Play"},
        {"powsled",     "Power Sled (Slave, Revision A)"},
        {"powsledm",    "Power Sled (Main, hack of Relay)"},
        {"powsledr",    "Power Sled (Relay, Revision A)"},
        {"ppan",        "Peter Pan (bootleg of Hook)"},
        {"ppcar",       "Pang Pang Car"},
        {"ppchamp",     "Pasha Pasha Champ Mini Game Festival (Korea, set 1)"},
        {"ppchampa",    "Pasha Pasha Champ Mini Game Festival (Korea, set 2)"},
        {"ppd",         "ParaParaDancing"},
        {"ppj",         "Pyon Pyon Jump (V1.40, Japan)"},
        {"ppking",      "Ping-Pong King"},
        {"ppmast93",    "Ping Pong Masters '93"},
        {"ppp",         "ParaParaParadise"},
        {"ppp11",       "ParaParaParadise v1.1"},
        {"ppp1mp",      "ParaParaParadise 1st Mix Plus"},
        {"pprobe",      "Planet Probe (prototype?)"},
        {"ppsatan",     "Poka Poka Satan (Japan)"},
        {"ppspeed",     "Speed Up (Spanish bootleg of Pole Position)"},
        {"prehisle",    "Prehistoric Isle in 1930 (World)"},
        {"prehisleb",   "Prehistoric Isle in 1930 (World, bootleg)"},
        {"prehislek",   "Wonsido 1930's (Korea)"},
        {"prehisleu",   "Prehistoric Isle in 1930 (US)"},
        {"prehislu",    "Prehistoric Isle in 1930 (US)"},
        {"preisle2",    "Prehistoric Isle 2"},
        {"prikura",     "Princess Clara Daisakusen"},
        {"primella",    "Primella"},
        {"primglex",    "Prime Goal EX (PG1-VER.A)"},
        {"primrag2",    "Primal Rage 2"},
        {"primraga",    "Primal Rage (version 2.0)"},
        {"primrage",    "Primal Rage (version 2.3)"},
        {"prmrsocj",    "Premier Soccer (Japan ver. JAB)"},
        {"prmrsocr",    "Premier Soccer (Europe ver. EAB)"},
        {"prmrsocrj",   "Premier Soccer (ver JAB)"},
        {"prmtmfgo",    "Prime Time Fighter (US old version)"},
        {"prmtmfgt",    "Prime Time Fighter (US new version)"},
        {"prmtmfgto",   "Prime Time Fighter (Ver 2.1A 1993/05/21) (Old Version)"},
        {"profpac",     "Professor PacMan"},
        {"progear",     "Progear (USA 010117)"},
        {"progeara",    "Progear (Asia 010117)"},
        {"progearj",    "Progear no Arashi (Japan 010117)"},
        {"progearjbl",  "Progear no Arashi (Japan 010117) (decrypted bootleg)"},
        {"progearjd",   "Progear no Arashi (Japan 010117 Phoenix Edition) (bootleg)"},
        {"progearud",   "Progear (USA 010117 Phoenix Edition) (bootleg)"},
        {"progolf",     "18 Holes Pro Golf (set 1)"},
        {"progress",    "Progress"},
        {"promutrv",    "Progressive Music Trivia (Question set 1)"},
        {"promutrva",   "Progressive Music Trivia (Question set 2)"},
        {"promutrvb",   "Progressive Music Trivia (Question set 3)"},
        {"promutrvc",   "Progressive Music Trivia (Question set 4)"},
        {"propcycl",    "Prop Cycle (Rev PR2 Ver.A)"},
        {"propcyclj",   "Prop Cycle (Japan, PR1 Ver.A)"},
        {"prosoccr",    "Pro Soccer"},
        {"prosport",    "Prosport"},
        {"prosporta",   "Pro Sports - Bowling, Tennis, and Golf (USA)"},
        {"protenn",     "Pro Tennis (Japan)"},
        {"protennb",    "Tennis (bootleg of Pro Tennis)"},
        {"prtytime",    "Party Time: Gonta the Diver II / Ganbare! Gonta!! 2 (World Release)"},
        {"psailor1",    "Bishoujo Janshi Pretty Sailor 18-kin (Japan)"},
        {"psailor2",    "Bishoujo Janshi Pretty Sailor 2 (Japan)"},
        {"psoldier",    "Perfect Soldiers (Japan)"},
        {"pspikes",     "Power Spikes (World)"},
        {"pspikes2",    "Power Spikes II"},
        {"pspikesb",    "Power Spikes (bootleg)"},
        {"pspikesba",   "Power Spikes (Italian bootleg)"},
        {"pspikesc",    "Power Spikes (China, bootleg)"},
        {"pspikesk",    "Power Spikes (Korea)"},
        {"pspikesu",    "Power Spikes (US)"},
        {"pstadium",    "Mahjong Panic Stadium (Japan)"},
        {"pstone",      "Power Stone"},
        {"pstone2",     "Power Stone 2"},
        {"pstone2b",    "Power Stone 2 (bootleg)"},
        {"psurge",      "Power Surge"},
        {"psychic5",    "Psychic 5"},
        {"psychic5j",   "Psychic 5 (Japan)"},
        {"psychos",     "Psycho Soldier (US)"},
        {"psychosj",    "Psycho Soldier (Japan)"},
        {"psyforce",    "Psychic Force (JAPAN)"},
        {"psyvar2",     "Psyvariar 2 - The Will To Fabricate (Japan) (GDL-0024)"},
        {"ptblank",     "Point Blank"},
        {"ptblank2",    "Point Blank 2 (World, GNB5/VER.A)"},
        {"ptblank2a",   "Point Blank 2 (World, GNB2/VER.A)"},
        {"ptblank2b",   "Point Blank 2 (World, GNB2/VER.A alt)"},
        {"ptblank2c",   "Point Blank 2 (World, unknown version)"},
        {"ptblank2ua",  "Point Blank 2 (US, GNB3/VER.A)"},
        {"ptblanka",    "Point Blank (World, GN2 Rev B, set 2)"},
        {"pturn",       "Parallel Turn"},
        {"pubball",     "Power Up Baseball (V1.5, Prototype)"},
        {"puchicar",    "Puchi Carat (Japan)"},
        {"puchicarj",   "Puchi Carat (Ver 2.02J 1997/10/29)"},
        {"puchicaru",   "Puchi Carat (Ver 2.04A 1997/11/08)"},
        {"puckman",     "PuckMan (Japan set 1)"},
        {"puckmana",    "PuckMan (Japan set 2)"},
        {"puckmanb",    "Puck Man (bootleg set 1)"},
        {"puckmanf",    "Puck Man (speedup hack)"},
        {"puckmanh",    "Puck Man (bootleg set 2)"},
        {"puckmod",     "PuckMan (harder[Q])"},
        {"puckpkmn",    "Puckman Pockimon"},
        {"puckpkmnb",   "Puckman Pockimon Genie 2000 (bootleg)"},
        {"pulirula",    "PuLiRuLa (World)"},
        {"pulirulaa",   "PuLiRuLa (World, earlier?)"},
        {"pulirulaj",   "PuLiRuLa (Japan)"},
        {"pulirulj",    "PuLiRuLa (Japan)"},
        {"pulsar",      "Pulsar"},
        {"pulstar",     "Pulstar"},
        {"punchita",    "Punch-Out!! (Italian bootleg)"},
        {"punchkid",    "Punching Kid (Japan)"},
        {"punchout",    "Punch-Out!!"},
        {"punchouta",   "Punch-Out!! (Rev A)"},
        {"punchoutj",   "Punch-Out!! (Japan)"},
        {"punisher",    "The Punisher (World 930422)"},
        {"punisherbz",  "Biaofeng Zhanjing (Chinese bootleg of The Punisher)"},
        {"punisherh",   "The Punisher (Hispanic 930422)"},
        {"punisherj",   "The Punisher (Japan 930422)"},
        {"punisheru",   "The Punisher (USA 930422)"},
        {"punishrj",    "The Punisher (Japan 930422)"},
        {"punishru",    "The Punisher (US 930422)"},
        {"punkshot",    "Punk Shot (US 4 Players)"},
        {"punkshot2",   "Punk Shot (US 2 Players)"},
        {"punkshot2e",  "Punk Shot (World 2 Players)"},
        {"punkshotj",   "Punk Shot (Japan 2 Players)"},
        {"punksht2",    "Punk Shot (US 2 Players)"},
        {"punkshtj",    "Punk Shot (Japan 2 Players)"},
        {"pururun",     "Pururun"},
        {"pururuna",    "Pururun (set 2)"},
        {"pushman",     "Pushman"},
        {"pushmana",    "Pushman (Korea, set 2)"},
        {"pushmans",    "Pushman (American Sammy license)"},
        {"pushmant",    "Pushman (Top Tronic license)"},
        {"puyo",        "Puyo Puyo (World)"},
        {"puyobl",      "Puyo Puyo (World, bootleg)"},
        {"puyofev",     "Puyo Pop Fever (World) (GDS-0034)"},
        {"puyofevj",    "Puyo Puyo Fever (Japan) (GDS-0031)"},
        {"puyofevp",    "Puyo Puyo Fever (prototype ver 0.01)"},
        {"puyoj",       "Puyo Puyo (Japan, Rev B)"},
        {"puyoja",      "Puyo Puyo (Japan, Rev A)"},
        {"puyopuy2",    "Puyo Puyo 2 (Japan)"},
        {"puyopuya",    "Puyo Puyo (Japan) (Rev A)"},
        {"puyopuyb",    "Puyo Puyo (English) (bootleg)"},
        {"puyopuyo",    "Puyo Puyo (Japan)"},
        {"puyosun",     "Puyo Puyo Sun"},
        {"puzlbang",    "Puzzle Bang Bang (Korea, version 2.9 / 990108)"},
        {"puzlbanga",   "Puzzle Bang Bang (Korea, version 2.8 / 990106)"},
        {"puzlclub",    "Puzzle Club (Japan prototype)"},
        {"puzldama",    "Taisen Puzzle-dama (ver JAA)"},
        {"puzloopj",    "Puzz Loop (Japan)"},
        {"puzloopu",    "Puzz Loop (USA)"},
        {"puzlstar",    "Puzzle Star"},
        {"puzzldpr",    "Puzzle De Pon! R!"},
        {"puzzledp",    "Puzzle De Pon!"},
        {"puzzlekg",    "Puzzle King (Dance & Puzzle)"},
        {"puzzli",      "Puzzli"},
        {"puzzli2",     "Puzzli 2 (ver. 100)"},
        {"puzzli2s",    "Puzzli 2 Super (ver. 200)"},
        {"puzzlia",     "Puzzli (revision A)"},
        {"puzzloop",    "Puzz Loop (Europe)"},
        {"puzzlove",    "PuzzLove"},
        {"puzzlovek",   "PuzzLove (Korea)"},
        {"puzznic",     "Puzznic (Japan)"},
        {"puzznicb",    "Puzznic (bootleg, set 1)"},
        {"puzznicba",   "Puzznic (bootleg, set 2)"},
        {"puzznici",    "Puzznic (Italian bootleg)"},
        {"puzznicj",    "Puzznic (Japan)"},
        {"puzznicu",    "Puzznic (US)"},
        {"pwheelsj",    "Power Wheels (Japan)"},
        {"pwrflip",     "Power Flipper Pinball Shooting (v1.33)"},
        {"pwrgoal",     "Taito Power Goal (World)"},
        {"pwrinst2",    "Power Instinct 2 (USA)"},
        {"pwrinst2a",   "Power Instinct 2 (US, Ver. 94.04.08, set 2)"},
        {"pwrinst2j",   "Gouketsuji Ichizoku 2 (Japan, Ver. 94.04.08)"},
        {"pwrkick",     "Power Kick (Japan)"},
        {"py2k2",       "Photo Y2K 2"},
        {"pyros",       "Pyros (US)"},
        {"pzlbowl",     "Puzzle De Bowling (Japan)"},
        {"pzlbreak",    "Puzzle Break"},
        {"pzlbreaka",   "Puzzle Break (set 2)"},
        {"pzlestar",    "Puzzle Star (Sang Ho Soft)"},
        {"pzletime",    "Puzzle Time (prototype)"},
        {"pzloop2",     "Puzz Loop 2 (Euro 010302)"},
        {"pzloop2j",    "Puzz Loop 2 (Japan 010226)"},
        {"pzloop2jd",   "Puzz Loop 2 (Japan 010226 Phoenix Edition) (bootleg)"},
        {"pzloop2jr1",  "Puzz Loop 2 (Japan 010205)"},
};

const char *lookup_p(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_p(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
