#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"cabal",       "Cabal (World, Joystick version)"},
        {"cabal2",      "Cabal (US set 2)"},
        {"cabala",      "Cabal (Alpha Trading)"},
        {"cabalbl",     "Cabal (bootleg of Joystick version)"},
        {"cabalbl2",    "Cabal (bootleg of Joystick version, set 2)"},
        {"cabalng",     "Cabal (Neo-Geo Conversion)"},
        {"cabaluk",     "Cabal (UK, Trackball)"},
        {"cabalukj",    "Cabal (UK, Joystick)"},
        {"cabalus",     "Cabal (US set 1, Trackball version)"},
        {"cabalus2",    "Cabal (US set 2, Trackball version)"},
        {"cabaret",     "Cabaret"},
        {"cachat",      "Cachat (Japan)"},
        {"cactus",      "Cactus (bootleg of Saboten Bombers)"},
        {"cadanglr",    "Cassette: Angler Dangler"},
        {"cadash",      "Cadash (World)"},
        {"cadashf",     "Cadash (France)"},
        {"cadashg",     "Cadash (Germany, rev 1)"},
        {"cadashgo",    "Cadash (Germany)"},
        {"cadashi",     "Cadash (Italy)"},
        {"cadashj",     "Cadash (Japan)"},
        {"cadashj1",    "Cadash (Japan, rev 1)"},
        {"cadashjo",    "Cadash (Japan)"},
        {"cadashp",     "Cadash (World, prototype)"},
        {"cadashs",     "Cadash (Spain, rev 1)"},
        {"cadashu",     "Cadash (US)"},
        {"cadashu1",    "Cadash (US, rev 1?)"},
        {"cafebrk",     "Mahjong Cafe Break"},
        {"cafedoll",    "Mahjong Cafe Doll (Japan)"},
        {"cafetime",    "Mahjong Cafe Time"},
        {"cairblad",    "Change Air Blade (Japan)"},
        {"calchase",    "California Chase"},
        {"calcune",     "Calcune (Japan, prototype)"},
        {"calibr50",    "Caliber 50"},
        {"calipso",     "Calipso"},
        {"calorie",     "Calorie Kun vs Moguranian"},
        {"calorieb",    "Calorie Kun vs Moguranian (bootleg)"},
        {"calspeed",    "California Speed"},
        {"calspeeda",   "California Speed (Version 1.0r8 Mar 10 1998, GUTS Mar 10 1998 / MAIN Mar 10 1998)"},
        {"calspeedb",   "California Speed (Version 1.0r7a Mar 4 1998, GUTS Mar 3 1998 / MAIN Jan 19 1998)"},
        {"cameltrj",    "Cameltry (Japan)"},
        {"cameltru",    "Camel Try (US)"},
        {"cameltry",    "Cameltry (US)"},
        {"cameltrya",   "Cameltry (World, YM2203 + M6295)"},
        {"cameltryau",  "Cameltry (US, YM2203 + M6295)"},
        {"cameltryj",   "Cameltry (Japan, YM2610)"},
        {"camltrua",    "Cameltry (US, alt sound)"},
        {"canbprot",    "Canyon Bomber (prototype)"},
        {"candance",    "Cannon Dancer (Japan)"},
        {"candory",     "Candory (Ponpoko bootleg with Mario)"},
        {"candy",       "Candy Candy"},
        {"cane",        "Cane (prototype)"},
        {"cannball",    "Cannon Ball"},
        {"cannballv",   "Cannon Ball (Yun Sung, vertical)"},
        {"cannonb",     "Cannon Ball (Crazy Climber hardware)"},
        {"cannonb2",    "Cannon Ball (bootleg on Crazy Kong hardware) (set 2, buggy)"},
        {"cannonb3",    "Cannon Ball (bootleg on Crazy Kong hardware) (set 3, no bonus game)"},
        {"cannonbp",    "Cannon Ball (Pac-Man Hardware)"},
        {"canvas",      "Canvas Croquis"},
        {"canyon",      "Canyon Bomber"},
        {"canyonp",     "Canyon Bomber (prototype)"},
        {"capbowl",     "Capcom Bowling (set 1)"},
        {"capbowl2",    "Capcom Bowling (set 2)"},
        {"capbowl3",    "Capcom Bowling (set 3)"},
        {"capbowl4",    "Capcom Bowling (set 4)"},
        {"capitol",     "Capitol"},
        {"capsnk",      "Capcom Vs. SNK: Millennium Fight 2000 (Rev C)"},
        {"capsnka",     "Capcom Vs. SNK: Millennium Fight 2000 (Rev A)"},
        {"capsnkb",     "Capcom Vs. SNK: Millennium Fight 2000"},
        {"captaven",    "Captain America and The Avengers (Asia Rev 1.9)"},
        {"captavena",   "Captain America and The Avengers (Asia Rev 1.0)"},
        {"captavene",   "Captain America and The Avengers (UK Rev 1.4)"},
        {"captavenj",   "Captain America and The Avengers (Japan Rev 0.2)"},
        {"captavenu",   "Captain America and The Avengers (US Rev 1.9)"},
        {"captavenua",  "Captain America and The Avengers (US Rev 1.4)"},
        {"captavenuu",  "Captain America and The Avengers (US Rev 1.6)"},
        {"captavna",    "Captain America and The Avengers (Asia Rev 1.0)"},
        {"captavne",    "Captain America and The Avengers (UK Rev 1.4)"},
        {"captavnj",    "Captain America and The Avengers (Japan Rev 0.2)"},
        {"captavnu",    "Captain America and The Avengers (US Rev 1.9)"},
        {"captavuu",    "Captain America and The Avengers (US Rev 1.6)"},
        {"captcomj",    "Captain Commando (Japan 911202)"},
        {"captcomm",    "Captain Commando (World 911014)"},
        {"captcommb",   "Captain Commando (bootleg)"},
        {"captcommb2",  "Captain Commando (bootleg with 2xMSM5205)"},
        {"captcommb3",  "Captain Commando (bootleg set 3 (with YM2151 + 2xMSM5205), 911014 other country)"},
        {"captcommj",   "Captain Commando (Japan 911202)"},
        {"captcommjr1", "Captain Commando (Japan 910928)"},
        {"captcommr1",  "Captain Commando (World 911014)"},
        {"captcommu",   "Captain Commando (USA 910928)"},
        {"captcomu",    "Captain Commando (US 910928)"},
        {"captflag",    "Captain Flag (Japan)"},
        {"car2",        "Car 2 (bootleg of Head On 2)"},
        {"caractn",     "Car Action"},
        {"caractn2",    "Car Action (set 2)"},
        {"carjmbre",    "Car Jamboree"},
        {"carket",      "Carket Ball"},
        {"carnevil",    "CarnEvil"},
        {"carnevil1",   "CarnEvil (v1.0.1)"},
        {"carnival",    "Carnival (upright)"},
        {"carnivalc",   "Carnival (cocktail)"},
        {"carnivalh",   "Carnival (Head On hardware, set 1)"},
        {"carnivalha",  "Carnival (Head On hardware, set 2)"},
        {"carnking",    "Carnival King (v1.00.11)"},
        {"carnvckt",    "Carnival (cocktail)"},
        {"carpolo",     "Car Polo"},
        {"carrera",     "Carrera (Version 6.7)"},
        {"cartfury",    "CART Fury Championship Racing (ver 1.00)"},
        {"casanova",    "Casanova"},
        {"cascade",     "Cascade"},
        {"cashquiz",    "Cash Quiz (Type B, Version 5)"},
        {"castfant",    "Cassette: Astro Fantasia"},
        {"catacomb",    "Catacomb"},
        {"catapult",    "Catapult"},
        {"catch22",     "Catch-22 (version 8.0)"},
        {"caterplr",    "Caterpillar (bootleg of Centipede)"},
        {"catnmous",    "Cat and Mouse (type 02 program)"},
        {"catnmousa",   "Cat and Mouse (type 01 program)"},
        {"catt",        "Catt (Japan)"},
        {"cavelon",     "Cavelon"},
        {"cavenger",    "Cosmic Avenger"},
        {"cawing",      "Carrier Air Wing (World 901012)"},
        {"cawingb2",    "Carrier Air Wing (bootleg with 2xYM2203 + 2xMSM5205, set 2)"},
        {"cawingbl",    "Carrier Air Wing (bootleg with 2xYM2203 + 2xMSM5205, set 1)"},
        {"cawingj",     "U.S. Navy (Japan 901012)"},
        {"cawingr1",    "Carrier Air Wing (World 901009)"},
        {"cawingu",     "Carrier Air Wing (US 901012)"},
        {"cawingur1",   "Carrier Air Wing (USA 901012)"},
        {"cbaj",        "Cool Boarders Arcade Jam"},
        {"cball",       "Cannonball (Atari, prototype)"},
        {"cbasebal",    "Capcom Baseball (Japan)"},
        {"cbdash",      "Cassette: Boulder Dash"},
        {"cbnj",        "Cassette: Bump N Jump"},
        {"cbombers",    "Chase Bombers (World)"},
        {"cbombersj",   "Chase Bombers (Japan)"},
        {"cbombersp",   "Chase Bombers (Japan Prototype)"},
        {"cbtime",      "Cassette: Burger Time"},
        {"cburnrb2",    "Cassette: Burnin' Rubber (set 2)"},
        {"cburnrub",    "Cassette: Burnin' Rubber (set 1)"},
        {"cburnrub2",   "Burnin' Rubber (DECO Cassette) (US) (set 2)"},
        {"cburnrubj",   "Burnin' Rubber (DECO Cassette) (Japan)"},
        {"cbuster",     "Crude Buster (World FX version)"},
        {"cbusterj",    "Crude Buster (Japan)"},
        {"cbusterw",    "Crude Buster (World FU version)"},
        {"ccasino",     "Chinese Casino [BET] (Japan)"},
        {"ccastle2",    "Crystal Castles (version 2)"},
        {"ccastle3",    "Crystal Castles (version 3)"},
        {"ccastlej",    "Crystal Castles (joystick version)"},
        {"ccastles",    "Crystal Castles (version 4)"},
        {"ccastles1",   "Crystal Castles (version 1)"},
        {"ccastles2",   "Crystal Castles (version 2)"},
        {"ccastles3",   "Crystal Castles (version 3)"},
        {"ccastlesf",   "Crystal Castles (version 3, French)"},
        {"ccastlesg",   "Crystal Castles (version 3, German)"},
        {"ccastlesj",   "Crystal Castles (joystick version)"},
        {"ccastlesp",   "Crystal Castles (version 3, Spanish)"},
        {"ccboot",      "Crazy Climber (bootleg set 1)"},
        {"ccboot2",     "Crazy Climber (bootleg set 2)"},
        {"ccbootmm",    "Crazy Climber (ManilaMatic bootleg)"},
        {"ccbootmr",    "Crazy Climber (Model Racing bootleg)"},
        {"cchasm",      "Cosmic Chasm (set 1)"},
        {"cchasm1",     "Cosmic Chasm (set 2)"},
        {"cchip",       "C-Chip Internal ROM"},
        {"cclimber",    "Crazy Climber (US)"},
        {"cclimbera",   "Crazy Climber (US set 2)"},
        {"cclimberj",   "Crazy Climber (Japan)"},
        {"cclimbr2",    "Crazy Climber 2 (Japan)"},
        {"cclimbr2a",   "Crazy Climber 2 (Japan, Harder)"},
        {"cclimbrj",    "Crazy Climber (Japan)"},
        {"cclimbroper", "Crazy Climber (Spanish, Operamatic bootleg)"},
        {"cclimbrrod",  "Crazy Climber (Spanish, Rodmar bootleg)"},
        {"cclownz",     "Crazzy Clownz (Version 1.0)"},
        {"cdi",         "CD-i (Mono-I) BIOS"},
        {"cdiscon1",    "Cassette: Disco No.1"},
        {"cdracula",    "Castle Of Dracula"},
        {"cdsteljn",    "DS Telejan (DECO Cassette) (Japan)"},
        {"cecmatch",    "ChuckECheese's Match Game"},
        {"cencourt",    "Center Court (World, 4 Players, prototype) (MC-8123B)"},
        {"centipb2",    "Centipede (bootleg, set 1)"},
        {"centipd2",    "Centipede (revision 2)"},
        {"centipdb",    "Caterpillar (bootleg of Centipede)"},
        {"centipdb2",   "Centipede (bootleg, set 2)"},
        {"centipdd",    "Centipede Dux (hack)"},
        {"centiped",    "Centipede (revision 3)"},
        {"centiped1",   "Centipede (revision 1)"},
        {"centiped2",   "Centipede (revision 2)"},
        {"centiped3",   "Centipede (revision 3)"},
        {"centipedj",   "Centipede (Japan, revision 3)"},
        {"centtime",    "Centipede (revision 4)"},
        {"cerberus",    "Cerberus"},
        {"cexplore",    "Cassette: Explorer"},
        {"cfarm",       "Chicken Farm (Version 2.0)"},
        {"cfboy0a1",    "Flash Boy (vertical) (DECO Cassette MD) (No.12/Ver.0/Set.1,Japan)"},
        {"cfghtice",    "Cassette: Fighting Ice Hockey"},
        {"cfield",      "Chaos Field (Japan) (GDL-0025)"},
        {"cfishing",    "Cassette: Fishing"},
        {"cflyball",    "Cassette: Flying Ball[Q]"},
        {"cgangpzj",    "Cosmo Gang the Puzzle (Japan)"},
        {"cgangpzl",    "Cosmo Gang the Puzzle (US)"},
        {"cgangpzlj",   "Cosmo Gang the Puzzle (Japan)"},
        {"cgraplop",    "Cassette: Graplop (aka Cluster Buster) (set 1)"},
        {"cgraplop2",   "Graplop (DECO Cassette) (US) (Prototype?)"},
        {"cgraplopj",   "Graplop (DECO Cassette) (Japan)"},
        {"cgraplp2",    "Cassette: Graplop (aka Cluster Buster) (set 2)"},
        {"chainrec",    "Chain Reaction (World, Version 2.2)"},
        {"chaknpop",    "Chack'n Pop"},
        {"challeng",    "Challenger"},
        {"cham24",      "Chameleon 24"},
        {"chamburger",  "Hamburger (DECO Cassette) (Japan)"},
        {"chameleo",    "Chameleon"},
        {"champbas",    "Champion Baseball"},
        {"champbasj",   "Champion Base Ball (Japan set 1)"},
        {"champbasja",  "Champion Base Ball (Japan set 2)"},
        {"champbasjb",  "Champion Base Ball (Japan set 3)"},
        {"champbb2",    "Champion Baseball II"},
        {"champbb2a",   "Champion Baseball II (set 2)"},
        {"champbb2j",   "Champion Base Ball Part-2 (Japan)"},
        {"champbbj",    "Champion Baseball (Japan set 1)"},
        {"champbja",    "Champion Baseball (Japan set 2)"},
        {"champbwl",    "Championship Bowling"},
        {"champbwla",   "Championship Bowling (location test)"},
        {"champwr",     "Champion Wrestler (World)"},
        {"champwrj",    "Champion Wrestler (Japan)"},
        {"champwru",    "Champion Wrestler (US)"},
        {"chanbara",    "Chanbara (Japan)"},
        {"changela",    "Change Lanes"},
        {"changes",     "Changes"},
        {"changesa",    "Changes (EME license)"},
        {"chaoshea",    "Chaos Heat (V2.09O)"},
        {"chaosheaj",   "Chaos Heat (V2.08J)"},
        {"charlien",    "Charlie Ninja"},
        {"chasehq",     "Chase H.Q. (World)"},
        {"chasehqj",    "Chase H.Q. (Japan)"},
        {"chasehqju",   "Chase H.Q. (Japan, upright?)"},
        {"chasehqu",    "Chase H.Q. (US)"},
        {"chboxing",    "Champion Boxing"},
        {"checkmaj",    "Check Man (Japan)"},
        {"checkman",    "Check Man"},
        {"checkmanj",   "Check Man (Japan)"},
        {"checkmat",    "Checkmate"},
        {"cheekyms",    "Cheeky Mouse"},
        {"cheesech",    "Cheese Chase"},
        {"chelnov",     "Chelnov - Atomic Runner (World)"},
        {"chelnovj",    "Chelnov - Atomic Runner (Japan)"},
        {"chelnovjbl",  "Chelnov - Atomic Runner (Japan, bootleg with I8031, set 1)"},
        {"chelnovjbla", "Chelnov - Atomic Runner (Japan, bootleg with I8031, set 2)"},
        {"chelnovu",    "Chelnov - Atomic Runner (US)"},
        {"cheyenne",    "Cheyenne (version 1.0)"},
        {"chikij",      "Chiki Chiki Boys (Japan 900619)"},
        {"chiller",     "Chiller (version 3.0)"},
        {"chimerab",    "Chimera Beast (prototype)"},
        {"chimeraba",   "Chimera Beast (Japan, prototype, set 2)"},
        {"chinagat",    "China Gate (US)"},
        {"chinatwn",    "China Town (Japan)"},
        {"chinher2",    "Chinese Hero (older)"},
        {"chinhero",    "Chinese Hero"},
        {"chinhero2",   "Chinese Hero (older, set 1)"},
        {"chinhero3",   "Chinese Hero (older, set 2)"},
        {"chinherot",   "Chinese Heroe (Taito)"},
        {"chinmoku",    "Mahjong Chinmoku no Hentai (Japan 900511)"},
        {"chinsan",     "Ganbare Chinsan Ooshoubu (MC-8123A, 317-5012)"},
        {"chkun",       "Chance Kun (Japan)"},
        {"chloe",       "Chloe 280SE"},
        {"chocomk",     "Musapey's Choco Marker (Rev A) (GDL-0014A)"},
        {"chocovdr",    "Uchuu Daisakusen: Chocovader Contactee (Japan, CVC1 Ver.A)"},
        {"chokchok",    "Choky! Choky!"},
        {"choko",       "Janpai Puzzle Choukou (Japan 010820)"},
        {"choplift",    "Choplifter (8751 315-5151)"},
        {"chopliftbl",  "Choplifter (bootleg)"},
        {"chopliftu",   "Choplifter (unprotected)"},
        {"chopper",     "Chopper I (US set 1)"},
        {"choppera",    "Chopper I (US set 2)"},
        {"chopperb",    "Chopper I (US set 3)"},
        {"chplft",      "Choplifter"},
        {"chplftb",     "Choplifter (alternate)"},
        {"chplftbl",    "Choplifter (bootleg)"},
        {"chqflag",     "Chequered Flag"},
        {"chqflagj",    "Chequered Flag (Japan)"},
        {"chuckieegg",  "Chuckie Egg"},
        {"chukatai",    "Chuka Taisen (World)"},
        {"chukataij",   "Chuka Taisen (Japan) (P0-028-A PCB)"},
        {"chukataija",  "Chuka Taisen (Japan) (P0-025-A PCB)"},
        {"chukataiu",   "Chuka Taisen (US) (P0-028-A PCB)"},
        {"chukataj",    "Chuka Taisen (Japan)"},
        {"chukatau",    "Chuka Taisen (US)"},
        {"chwrestl",    "Champion Pro Wrestling"},
        {"chwy",        "Cassette: Highway Chase"},
        {"circus",      "Circus"},
        {"circusc",     "Circus Charlie"},
        {"circusc2",    "Circus Charlie (no level select)"},
        {"circusc3",    "Circus Charlie (level select, set 3)"},
        {"circusc4",    "Circus Charlie (no level select)"},
        {"circuscc",    "Circus Charlie (Centuri)"},
        {"circusce",    "Circus Charlie (Centuri, earlier)"},
        {"circusse",    "Circus (Sub-Electro bootleg)"},
        {"cischeat",    "Cisco Heat"},
        {"cityatta",    "City Attack (Petaco S.A., bootleg of Pleiads)"},
        {"citybmrj",    "City Bomber (Japan)"},
        {"citybomb",    "City Bomber (World)"},
        {"citybombj",   "City Bomber (Japan)"},
        {"citycon",     "City Connection (set 1)"},
        {"citycona",    "City Connection (set 2)"},
        {"citylove",    "City Love (Japan 860908)"},
        {"ckong",       "Crazy Kong (set 1)"},
        {"ckonga",      "Crazy Kong (set 2)"},
        {"ckongalc",    "Crazy Kong (Alca bootleg)"},
        {"ckongdks",    "Donkey Kong (Spanish bootleg of Crazy Kong)"},
        {"ckongg",      "Crazy Kong (bootleg on Galaxian hardware)"},
        {"ckonggx",     "Crazy Kong (bootleg on Galaxian hardware, encrypted, set 1)"},
        {"ckongjeu",    "Crazy Kong (Jeutel bootleg)"},
        {"ckongmc",     "Crazy Kong (bootleg on Moon Cresta hardware, set 1)"},
        {"ckongo",      "Crazy Kong (Orca bootleg)"},
        {"ckongpt2",    "Crazy Kong Part II (set 1)"},
        {"ckongpt2a",   "Crazy Kong Part II (set 2)"},
        {"ckongpt2b",   "Crazy Kong Part II (alternative levels)"},
        {"ckongpt2b2",  "Crazy Kong Part II (bootleg)"},
        {"ckongpt2j",   "Crazy Kong Part II (Japan)"},
        {"ckongpt2jeu", "Crazy Kong Part II (Jeutel bootleg)"},
        {"ckongpt2ss",  "Crazy Kong (SegaSA / Sonic bootleg)"},
        {"ckongs",      "Crazy Kong (Scramble hardware)"},
        {"clapapa",     "Cassette: Rootin' Tootin' (aka La.Pa.Pa)"},
        {"clapapa2",    "Cassette: Rootin' Tootin'"},
        {"claychal",    "Sega Clay Challenge"},
        {"claypign",    "Clay Pigeon (version 2.0)"},
        {"clayshoo",    "Clay Shoot"},
        {"clbowl",      "Coors Light Bowling"},
        {"cleoftp",     "Cleopatra Fortune Plus (GDL-0012)"},
        {"cleopatr",    "Cleopatra Fortune (Japan)"},
        {"cleopatro",   "Cleopatra Fortune (Ver 2.1O 1996/09/05, bootleg)"},
        {"cliffhgr",    "Cliff Hanger (set 1)"},
        {"cliffhgra",   "Cliff Hanger (set 2)"},
        {"cloak",       "Cloak and Dagger (rev 5)"},
        {"cloakfr",     "Cloak and Dagger (French)"},
        {"cloakgr",     "Cloak and Dagger (German)"},
        {"cloaksp",     "Cloak and Dagger (Spanish)"},
        {"clocknch",    "Cassette: Lock'n'Chase"},
        {"clocknchj",   "Lock'n'Chase (DECO Cassette) (Japan)"},
        {"cloud9",      "Cloud 9 (prototype)"},
        {"clowns",      "Clowns (rev. 2)"},
        {"clowns1",     "Clowns (rev. 1)"},
        {"clshroad",    "Clash-Road"},
        {"clshroadd",   "Clash-Road (Data East license)"},
        {"clshroads",   "Clash-Road (Status license)"},
        {"cltchitr",    "Clutch Hitter"},
        {"cltchitrd",   "Clutch Hitter (US) (bootleg of FD1094 317-0176 set)"},
        {"cltchitrj",   "Clutch Hitter (Japan) (FD1094 317-0175)"},
        {"cltchitrjd",  "Clutch Hitter (Japan) (bootleg of FD1094 317-0175 set)"},
        {"club90s",     "Mahjong CLUB 90's (set 1) (Japan 900919)"},
        {"club90sa",    "Mahjong CLUB 90's (set 2) (Japan 900919)"},
        {"clubk2k3",    "Club Kart: European Session (2003, Rev A)"},
        {"clubk2kf",    "Club Kart: European Session (2003, not protected)"},
        {"clubk2kp",    "Club Kart: European Session (2003, prototype, set 1)"},
        {"clubk2kpa",   "Club Kart: European Session (2003, prototype, set 2)"},
        {"clubkcyc",    "Club Kart for Cycraft (Rev A) (GDS-0029A)"},
        {"clubkcyco",   "Club Kart for Cycraft (GDS-0029)"},
        {"clubkprz",    "Club Kart Prize (Export, Japan, Rev A)"},
        {"clubkpzb",    "Club Kart Prize Version B (Export, Japan)"},
        {"clubkpzbp",   "Club Kart Prize Version B (prototype)"},
        {"clubkrt",     "Club Kart: European Session (Rev D)"},
        {"clubkrta",    "Club Kart: European Session (Rev A)"},
        {"clubkrtc",    "Club Kart: European Session (Rev C)"},
        {"clubkrtd",    "Club Kart: European Session (Rev D)"},
        {"clubkrte",    "Club Kart: European Session"},
        {"clubkrto",    "Club Kart: European Session"},
        {"clubpacm",    "Pacman Club / Club Lambada (Argentina)"},
        {"clubpacma",   "Pacman Club (Argentina)"},
        {"cluckypo",    "Cassette: Lucky Poker"},
        {"cluclu",      "Vs. Clu Clu Land"},
        {"cluedo",      "Cluedo (prod. 2D)"},
        {"cluedo2",     "Cluedo (prod. 2)"},
        {"cluedo2c",    "Cluedo (prod. 2C)"},
        {"cluedod",     "Cluedo (prod. 2D) (Protocol)"},
        {"cmanhat",     "Cassette: Manhattan"},
        {"cmehyou",     "Mahjong Circuit no Mehyou (Japan)"},
        {"cmissnx",     "Cassette: Mission-X"},
        {"cmmb162",     "Multipede (V1.00)"},
        {"cnbe",        "Codename - Blut Engel (2006-01-19)"},
        {"cnbe2018",    "Codename - Blut Engel (2018-09-05)"},
        {"cndi",        "Chip n Dale (FMV Demo)"},
        {"cndypuzl",    "Candy Puzzle (v1.0)"},
        {"cnebula",     "Nebula (DECO Cassette) (UK)"},
        {"cnights2",    "Cassette: Night Star (set 2)"},
        {"cnightst",    "Cassette: Night Star (set 1)"},
        {"cnightst2",   "Night Star (DECO Cassette) (US) (set 2)"},
        {"cninja",      "Caveman Ninja (World revision 3)"},
        {"cninja0",     "Caveman Ninja (World revision 0)"},
        {"cninja1",     "Caveman Ninja (World ver 1)"},
        {"cninjabl",    "Caveman Ninja (bootleg)"},
        {"cninjabl2",   "Tatakae Genshizin Joe & Mac (Japan, bootleg)"},
        {"cninjau",     "Caveman Ninja (US)"},
        {"cntsteer",    "Counter Steer (Japan)"},
        {"cobra",       "Cobra Command (Data East LD)"},
        {"cobracmj",    "Cobra-Command (Japan)"},
        {"cobracom",    "Cobra-Command (World revision 5)"},
        {"cobracoma",   "Cobra-Command (World/US revision 4)"},
        {"cobracomb",   "Cobra-Command (World/US)"},
        {"cobracomib",  "Cobra-Command (Italian bootleg)"},
        {"cobracomj",   "Cobra-Command (Japan)"},
        {"cobracomja",  "Cobra-Command (Japan?, set 2)"},
        {"cobracomjb",  "Cobra-Command (Japan, bootleg)"},
        {"cobram3",     "Cobra Command (M.A.C.H. 3 hardware, set 1)"},
        {"cobram3a",    "Cobra Command (M.A.C.H. 3 hardware, set 2)"},
        {"cobraseg",    "Cobra Command (Sega LaserDisc Hardware)"},
        {"cocoloco",    "Coco Loco (set 1)"},
        {"cocolocoa",   "Coco Loco (set 2)"},
        {"cocolocob",   "Coco Loco (set 3)"},
        {"code1d",      "Code One Dispatch (ver D)"},
        {"code1db",     "Code One Dispatch (ver B)"},
        {"colmns97",    "Columns 97"},
        {"colony7",     "Colony 7 (set 1)"},
        {"colony7a",    "Colony 7 (set 2)"},
        {"colt",        "Colt"},
        {"column2j",    "Columns II: The Voyage Through Time (Japan)"},
        {"columns",     "Columns (US)"},
        {"columns2",    "Columns II - The Voyage Through Time (Japan)"},
        {"columnsj",    "Columns (Japan)"},
        {"columnsn",    "Columns"},
        {"columnsu",    "Columns (US, cocktail, Rev A)"},
        {"combasc",     "Combat School (joystick)"},
        {"combascb",    "Combat School (bootleg)"},
        {"combascj",    "Combat School (Japan trackball)"},
        {"combasct",    "Combat School (trackball)"},
        {"combat",      "Combat (version 3.0)"},
        {"combatsc",    "Combat School (joystick)"},
        {"combatscb",   "Combat School (bootleg)"},
        {"combatscj",   "Combat School (Japan trackball)"},
        {"combatsct",   "Combat School (trackball)"},
        {"combh",       "Combat Hawk"},
        {"comebaby",    "Come On Baby"},
        {"comg903d",    "Cal Omega - System 903 Diag.PROM"},
        {"comg905d",    "Cal Omega - System 905 Diag.PROM"},
        {"commandj",    "Senjou no Ookami"},
        {"commando",    "Commando (World)"},
        {"commandob",   "Commando (bootleg set 1)"},
        {"commandob2",  "Commando (bootleg set 2)"},
        {"commandob3",  "Commando (bootleg set 3)"},
        {"commandoj",   "Senjou no Ookami"},
        {"commandou",   "Commando (US set 1)"},
        {"commandou2",  "Commando (US set 2)"},
        {"commandu",    "Commando (US)"},
        {"commandw",    "Command War - Super Special Battle & War Game (Prototype)"},
        {"commsega",    "Commando (Sega)"},
        {"comotion",    "Comotion"},
        {"comotionp",   "CoMotion (patent)"},
        {"compglfo",    "Competition Golf Final Round (old version)"},
        {"compgolf",    "Competition Golf Final Round (revision 3)"},
        {"compgolfo",   "Competition Golf Final Round (Japan, old version)"},
        {"complexx",    "Complex X"},
        {"condor",      "Condor"},
        {"condorn",     "Condor (S C Novar bootleg of Phoenix)"},
        {"condorva",    "Condor (Valadon Automation bootleg of Phoenix)"},
        {"confmiss",    "Confidential Mission (GDS-0001)"},
        {"congo",       "Congo Bongo (Rev C, 2 board stack)"},
        {"congoa",      "Congo Bongo (Rev C, 3 board stack)"},
        {"connect4",    "Connect 4"},
        {"conquer",     "Conquer"},
        {"conquest",    "Conquest (prototype)"},
        {"contcirc",    "Continental Circus (World)"},
        {"contcircj",   "Continental Circus (Japan)"},
        {"contcircu",   "Continental Circus (US set 1)"},
        {"contcircua",  "Continental Circus (US set 2)"},
        {"contcrcu",    "Continental Circus (US)"},
        {"contra",      "Contra (US)"},
        {"contra1",     "Contra (US / Asia, set 2)"},
        {"contrab",     "Contra (US bootleg)"},
        {"contrabj",    "Contra (Japan bootleg, set 1)"},
        {"contrabj1",   "Contra (Japan bootleg, set 2)"},
        {"contrae",     "Contra (US / Asia, set 3)"},
        {"contraj",     "Contra (Japan)"},
        {"contraj1",    "Contra (Japan, set 2)"},
        {"contrajb",    "Contra (Japan bootleg)"},
        {"cookbib",     "Cookie & Bibi"},
        {"cookbib2",    "Cookie & Bibi 2"},
        {"cookbib2a",   "Cookie & Bibi 2 (English, set 2)"},
        {"cookbib2b",   "Cookie & Bibi 2 (English, set 3)"},
        {"cookbib2c",   "Cookie & Bibi 2 (English / Korean)"},
        {"cookbib3",    "Cookie & Bibi 3"},
        {"cookbiba",    "Cookie & Bibi (set 2)"},
        {"cookrace",    "Cook Race"},
        {"coolmini",    "Cool Minigame Collection"},
        {"coolminii",   "Cool Minigame Collection (Italy)"},
        {"coolpool",    "Cool Pool"},
        {"coolridr",    "Cool Riders"},
        {"coozumou",    "Cassette: Oozumou - The Grand Sumo (Japan)"},
        {"cop01",       "Cop 01 (set 1)"},
        {"cop01a",      "Cop 01 (set 2)"},
        {"copsnrob",    "Cops'n Robbers"},
        {"coronatn",    "Coronation Street Quiz Game"},
        {"coronatnd",   "Coronation Street Quiz Game (Protocol)"},
        {"cosmccop",    "Cosmic Cop (World)"},
        {"cosmica",     "Cosmic Alien"},
        {"cosmica1",    "Cosmic Alien (first version)"},
        {"cosmica2",    "Cosmic Alien (older)"},
        {"cosmicg",     "Cosmic Guerilla"},
        {"cosmicin",    "Cosmic Invaders (bootleg of Space Invaders)"},
        {"cosmicm2",    "Cosmic Monsters II"},
        {"cosmicmo",    "Cosmic Monsters"},
        {"cosmo",       "Cosmo"},
        {"cosmogng",    "Cosmo Gang the Video (US)"},
        {"cosmogngj",   "Cosmo Gang the Video (Japan)"},
        {"cosmognj",    "Cosmo Gang the Video (Japan)"},
        {"cosmos",      "Cosmos"},
        {"cothello",    "Computer Othello"},
        {"cotton",      "Cotton (Japan)"},
        {"cotton2",     "Cotton 2"},
        {"cottona",     "Cotton"},
        {"cottonbm",    "Cotton Boomerang"},
        {"cottond",     "Cotton (set 4, World) (unprotected of FD1094 317-0181a set)"},
        {"cottong",     "Cotocoto Cottong"},
        {"cottonj",     "Cotton (set 2, Japan, Rev B) (FD1094 317-0179b)"},
        {"cottonja",    "Cotton (set 1, Japan, Rev A) (FD1094 317-0179a)"},
        {"cottonjad",   "Cotton (set 1, Japan, Rev A) (bootleg of FD1094 317-0179a set)"},
        {"cottonjd",    "Cotton (set 2, Japan, Rev B) (bootleg of FD1094 317-0179b set)"},
        {"cottonu",     "Cotton (set 3, US) (FD1094 317-0180)"},
        {"cottonud",    "Cotton (set 3, US) (bootleg of FD1094 317-0180 set)"},
        {"countrb2",    "Counter Run (bootleg set 2)"},
        {"countrnb",    "Counter Run (bootleg set 1)"},
        {"countrun",    "Counter Run"},
        {"countrunb",   "Counter Run (bootleg set 1)"},
        {"countrunb2",  "Counter Run (bootleg set 2)"},
        {"countrunb3",  "Counter Run (bootleg set 3)"},
        {"countryc",    "Country Club"},
        {"couple",      "The Couples (Set 1)"},
        {"couplei",     "The Couples (Set 3)"},
        {"couplep",     "The Couples (Set 2)"},
        {"cphd",        "Crouching Poney Hidden Dragon (DEMO)"},
        {"cppicf",      "Cassette: Peter Pepper's Ice Cream Factory (set 1)"},
        {"cppicf2",     "Cassette: Peter Pepper's Ice Cream Factory (set 2)"},
        {"cprobowl",    "Cassette: Pro Bowling"},
        {"cprogolf",    "Cassette: Pro Golf"},
        {"cprogolf18",  "18 Challenge Pro Golf (DECO Cassette) (Japan)"},
        {"cprogolfj",   "Tournament Pro Golf (DECO Cassette) (Japan)"},
        {"cprosocc",    "Cassette: Pro Soccer"},
        {"cps1demo",    "Chaos Demo (CPS-1)"},
        {"cps1frog",    "Frog Feast (CPS-1)"},
        {"cps3boot",    "CPS3 Multi-game bootleg for HD6417095 type SH2 (V4)"},
        {"cps3boota",   "CPS3 Multi-game bootleg for dead security cart (V5)"},
        {"cps3bootao",  "CPS3 Multi-game bootleg for dead security cart (older)"},
        {"cps3bootao2", "CPS3 Multi-game bootleg for dead security cart (oldest) (New Generation, 2nd Impact and 3rd Strike only)"},
        {"cps3booto",   "CPS3 Multi-game bootleg for HD6417095 type SH2 (older)"},
        {"cps3booto2",  "CPS3 Multi-game bootleg for HD6417095 type SH2 (oldest) (New Generation, 3rd Strike, JoJo's Venture, JoJo's Bizarre Adventure and Red Earth only)"},
        {"cps3bs32",    "Street Fighter III 2nd Impact: Giant Attack (USA 970930, bootleg for HD6417095 type SH2, V3)"},
        {"cps3bs32a",   "Street Fighter III 2nd Impact: Giant Attack (USA 970930, bootleg for HD6417095 type SH2, older)"},
        {"cpsoccer",    "Pro Soccer (DECO Cassette) (US)"},
        {"cpsoccerj",   "Pro Soccer (DECO Cassette) (Japan)"},
        {"cptennis",    "Cassette: Pro Tennis"},
        {"cptennisj",   "Pro Tennis (DECO Cassette) (Japan)"},
        {"cpzn1",       "ZN1"},
        {"cpzn2",       "ZN2"},
        {"crackndj",    "Crackin' DJ"},
        {"cracksht",    "Crackshot (version 2.0)"},
        {"crash",       "Crash"},
        {"crashh",      "Crash (Pac-Man)"},
        {"crashrd",     "Crash Road (bootleg of Space Chaser)"},
        {"crater",      "Crater Raider"},
        {"crazyblk",    "Crazy Blocks"},
        {"crazycop",    "Crazy Cop (Japan)"},
        {"crazyfgt",    "Crazy Fight"},
        {"crazym",      "Crazy Mazey"},
        {"crazywar",    "Crazy War"},
        {"crbalon2",    "Crazy Balloon (set 2)"},
        {"crbaloon",    "Crazy Balloon (set 1)"},
        {"crbaloon2",   "Crazy Balloon (set 2)"},
        {"crgolf",      "Crowns Golf (set 1)"},
        {"crgolfa",     "Crowns Golf (set 2)"},
        {"crgolfb",     "Champion Golf (bootleg Set 1)"},
        {"crgolfbt",    "Champion Golf (bootleg)"},
        {"crgolfc",     "Champion Golf"},
        {"crgolfhi",    "Crowns Golf in Hawaii"},
        {"crimec",      "Crime City (World)"},
        {"crimecj",     "Crime City (Japan)"},
        {"crimecu",     "Crime City (US)"},
        {"crimep2",     "Crime Patrol 2: Drug Wars v1.3"},
        {"crimep211",   "Crime Patrol 2: Drug Wars v1.1"},
        {"crimepat",    "Crime Patrol v1.4"},
        {"crimfght",    "Crime Fighters (US 4 players)"},
        {"crimfght2",   "Crime Fighters (World 2 Players)"},
        {"crimfghtj",   "Crime Fighters (Japan 2 Players)"},
        {"crimfghtu",   "Crime Fighters (US 4 Players)"},
        {"crimfgt2",    "Crime Fighters (World 2 Players)"},
        {"crimfgtj",    "Crime Fighters (Japan 2 Players)"},
        {"critcrsh",    "Critter Crusher (EA 951204 V1.000)"},
        {"crkdown",     "Crackdown"},
        {"crkdownj",    "Crack Down (Japan, Floppy Based, FD1094 317-0058-04b Rev A)"},
        {"crkdownu",    "Crack Down (US, Floppy Based, FD1094 317-0058-04d)"},
        {"crmaze",      "The Crystal Maze (v1.3)"},
        {"crmaze2",     "The New Crystal Maze Featuring Ocean Zone (v2.2)"},
        {"crmaze2a",    "The New Crystal Maze Featuring Ocean Zone (v0.1, AMLD)"},
        {"crmaze2d",    "The New Crystal Maze Featuring Ocean Zone (v2.2d)"},
        {"crmaze3",     "The Crystal Maze Team Challenge (v0.9)"},
        {"crmaze3a",    "The Crystal Maze Team Challenge (v1.2, AMLD)"},
        {"crmaze3d",    "The Crystal Maze Team Challenge (v0.9, Datapak)"},
        {"crmazea",     "The Crystal Maze (v0.1, AMLD)"},
        {"crmazed",     "The Crystal Maze (v1.3, Datapak)"},
        {"crockman",    "Crock-Man"},
        {"crockmnf",    "Crock-Man (Marti Colls bootleg of Rene Pierre Crock-Man)"},
        {"croquis",     "Croquis (Germany)"},
        {"croquisg",    "Croquis (Germany)"},
        {"crospang",    "Cross Pang"},
        {"crossbld",    "Cross Blades! (Japan)"},
        {"crossbow",    "Crossbow (version 2.0)"},
        {"crshrac2",    "Lethal Crash Race (set 2)"},
        {"crshrace",    "Lethal Crash Race (set 1)"},
        {"crshrace2",   "Lethal Crash Race / Bakuretsu Crash Race (set 2)"},
        {"crshrace2a",  "Lethal Crash Race / Bakuretsu Crash Race (set 2, alternate sound ROM)"},
        {"crswd2bl",    "Crossed Swords 2"},
        {"crsword",     "Crossed Swords"},
        {"crszone",     "Crisis Zone (CSZO3 Ver. B)"},
        {"cruisin",     "Cruisin"},
        {"crush",       "Crush Roller (Kural Samno)"},
        {"crush2",      "Crush Roller (Kural Esco - bootleg[Q])"},
        {"crush3",      "Crush Roller (Kural - bootleg[Q])"},
        {"crush4",      "Crush Roller (set 4)"},
        {"crush5",      "Crush Roller (set 5)"},
        {"crushbl",     "Crush Roller (bootleg set 1)"},
        {"crushbl2",    "Crush Roller (bootleg set 2)"},
        {"crushbl3",    "Crush Roller (bootleg set 3)"},
        {"crusherm",    "Crusher Makochan (Japan)"},
        {"crushrlf",    "Crush Roller (Famare SA PCB)"},
        {"crushs",      "Crush Roller (bootleg set 4)"},
        {"crusnexo",    "Cruis'n Exotica (version 2.4)"},
        {"crusnexoa",   "Cruis'n Exotica (version 2.0)"},
        {"crusnexob",   "Cruis'n Exotica (version 1.6)"},
        {"crusnu21",    "Cruis'n USA (rev L2.1)"},
        {"crusnu40",    "Cruis'n USA (rev L4.0)"},
        {"crusnusa",    "Cruis'n USA (rev L4.1)"},
        {"crusnusa11",  "Cruis'n USA (v1.1)"},
        {"crusnusa20",  "Cruis'n USA (v2.0)"},
        {"crusnusa21",  "Cruis'n USA (v2.1)"},
        {"crusnusa40",  "Cruis'n USA (v4.0)"},
        {"crusnusa41",  "Cruis'n USA (v4.1)"},
        {"crusnusa44",  "Cruis'n USA (v4.4)"},
        {"crusnw13",    "Cruis'n World (rev L1.3)"},
        {"crusnw20",    "Cruis'n World (rev L2.0)"},
        {"crusnwld",    "Cruis'n World (rev L2.3)"},
        {"crusnwld13",  "Cruis'n World (v1.3)"},
        {"crusnwld17",  "Cruis'n World (v1.7)"},
        {"crusnwld19",  "Cruis'n World (v1.9)"},
        {"crusnwld20",  "Cruis'n World (v2.0)"},
        {"crusnwld23",  "Cruis'n World (v2.3)"},
        {"crusnwld24",  "Cruis'n World (v2.4)"},
        {"cryptklr",    "Crypt Killer (ver. UAA)"},
        {"crysking",    "The Crystal of Kings"},
        {"crystal2",    "Crystal Gal 2 (Japan 860620)"},
        {"crystalg",    "Crystal Gal (Japan 860512)"},
        {"crzmon_7",    "Crazy Monkey (031110)"},
        {"crzmon_7a",   "Crazy Monkey (031110, backdoor set 1)"},
        {"crzmon_7b",   "Crazy Monkey (031110, backdoor set 2)"},
        {"crzmon_8",    "Crazy Monkey (050120)"},
        {"crzmon_8a",   "Crazy Monkey (050120, backdoor)"},
        {"crzrally",    "Crazy Rally"},
        {"crzrallya",   "Crazy Rally (set 2)"},
        {"crzrallyg",   "Crazy Rally (Gecas license)"},
        {"crzrallyrf",  "Crazy Rally (Recreativos Franco license)"},
        {"crzytaxi",    "Crazy Taxi"},
        {"csclub",      "Capcom Sports Club (Euro 971017)"},
        {"csclub1",     "Capcom Sports Club (Euro 970722)"},
        {"csclub1d",    "Capcom Sports Club (Europe 970722 Phoenix Edition) (bootleg)"},
        {"cscluba",     "Capcom Sports Club (Asia 970722)"},
        {"csclubh",     "Capcom Sports Club (Hispanic 970722)"},
        {"csclubj",     "Capcom Sports Club (Japan 970722)"},
        {"csclubjy",    "Capcom Sports Club (Japan 970722, yellow case)"},
        {"cscrtry",     "Cassette: Scrum Try (set 1)"},
        {"cscrtry2",    "Cassette: Scrum Try (set 2)"},
        {"csdtenis",    "Cassette: Super Doubles Tennis (Japan)"},
        {"cshift",      "Chicken Shift"},
        {"cshooter",    "Cross Shooter (not encrypted)"},
        {"cshootere",   "Cross Shooter (encrypted)"},
        {"cshootre",    "Cross Shooter (encrypted)"},
        {"csilver",     "Captain Silver (Japan)"},
        {"csilverj",    "Captain Silver (Japan, revision 2)"},
        {"csilverja",   "Captain Silver (Japan, revision 1)"},
        {"cskater",     "Cassette: Skater (Japan)"},
        {"csmash",      "Cosmic Smash (Rev A)"},
        {"csmasho",     "Cosmic Smash"},
        {"cspike",      "Cannon Spike / Gun Spike"},
        {"cspring1",    "Championship Sprint (German, rev 1)"},
        {"csprins1",    "Championship Sprint (Spanish, rev 1)"},
        {"csprint",     "Championship Sprint (rev 3)"},
        {"csprint1",    "Championship Sprint (rev 1)"},
        {"csprint2",    "Championship Sprint (rev 2)"},
        {"csprintf",    "Championship Sprint (French)"},
        {"csprintg",    "Championship Sprint (German, rev 2)"},
        {"csprintg1",   "Championship Sprint (German, rev 1)"},
        {"csprints",    "Championship Sprint (Spanish, rev 2)"},
        {"csprints1",   "Championship Sprint (Spanish, rev 1)"},
        {"cstlevna",    "Vs. Castlevania"},
        {"csuperas",    "Cassette: Super Astro Fighter"},
        {"csweetht",    "Cassette: Sweet Heart"},
        {"ct2k3sa",     "Crouching Tiger Hidden Dragon"},
        {"ct2k3sp",     "Crouching Tiger Hidden Dragon 2003 Super Plus (The King of Fighters 2001 bootleg)"},
        {"cterrani",    "Cassette: Terranean"},
        {"cthd2003",    "Crouching Tiger Hidden Dragon 2003 (The King of Fighters 2001 bootleg)"},
        {"cthd2k3a",    "Crouching Tiger Hidden Dragon 2003 (The King of Fighters 2001 bootleg, set 2)"},
        {"ctisland",    "Cassette: Treasure Island (set 1)"},
        {"ctisland2",   "Treasure Island (DECO Cassette) (US) (set 2)"},
        {"ctisland3",   "Treasure Island (DECO Cassette) (Europe?)"},
        {"ctislnd2",    "Cassette: Treasure Island (set 2)"},
        {"ctislnd3",    "Cassette: Treasure Island (set 3)"},
        {"ctomaday",    "Captain Tomaday"},
        {"ctornado",    "Cassette: Tornado"},
        {"ctower",      "The Tower (DECO Cassette) (Europe)"},
        {"ctribe",      "The Combatribes (US)"},
        {"ctribe1",     "The Combatribes (US Set 1?)"},
        {"ctribeb",     "The Combatribes (bootleg)"},
        {"ctribeb2",    "The Combatribes (bootleg set 2)"},
        {"ctribej",     "The Combatribes (Japan, rev 2)"},
        {"ctribeu1",    "The Combatribes (US, rev 1)"},
        {"ctribeua",    "The Combatribes (US, rev 2, set 2)"},
        {"ctrpllrp",    "Caterpillar Pacman Hack"},
        {"ctsttape",    "Cassette: Test Tape"},
        {"cubeqst",     "Cube Quest (01/04/84)"},
        {"cubeqsta",    "Cube Quest (12/30/83)"},
        {"cubybop",     "Cuby Bop (Location Test)"},
        {"cuebrckj",    "Cue Brick (World version D)"},
        {"cuebrick",    "Cue Brick (Japan)"},
        {"cuebrickj",   "Cue Brick (Japan)"},
        {"cultname",    "Seimei-Kantei-Meimei-Ki Cult Name"},
        {"cultures",    "Jibun wo Migaku Culture School Mahjong Hen"},
        {"cupfinal",    "Taito Cup Finals (World)"},
        {"cupsoc",      "Seibu Cup Soccer"},
        {"cupsoc2",     "Seibu Cup Soccer (set 2)"},
        {"cupsoca",     "Seibu Cup Soccer (set 2)"},
        {"cupsocbl",    "Seibu Cup Soccer (bootleg)"},
        {"cupsocs",     "Seibu Cup Soccer :Selection: (set 1)"},
        {"cupsocs2",    "Seibu Cup Soccer :Selection: (set 2)"},
        {"cupsocsb",    "Seibu Cup Soccer :Selection: (bootleg, set 1)"},
        {"cupsocsb2",   "Seibu Cup Soccer :Selection: (bootleg, set 2)"},
        {"curvebal",    "Curve Ball"},
        {"cutefght",    "Cute Fighter"},
        {"cutieq",      "Cutie Q"},
        {"cvs",         "CVS Bios"},
        {"cvs2",        "Capcom Vs. SNK 2: Mark Of The Millennium 2001 (USA) (GDL-0008)"},
        {"cvs2gd",      "Capcom Vs. SNK 2 Millionaire Fighting 2001 (Rev A) (GDL-0007A)"},
        {"cvs2mf",      "Capcom Vs. SNK 2: Millionaire Fighting 2001 (Japan, Rev A) (GDL-0007A)"},
        {"cvsgd",       "Capcom Vs. SNK: Millennium Fight 2000 Pro (Japan) (GDL-0004)"},
        {"cworld",      "Capcom World (Japan)"},
        {"cworld2j",    "Capcom World 2 (Japan 920611)"},
        {"cworld2ja",   "Adventure Quiz Capcom World 2 (Japan 920611, B-Board 90629B-3, no battery)"},
        {"cworld2jb",   "Adventure Quiz Capcom World 2 (Japan 920611, B-Board 91634B-2)"},
        {"cybattlr",    "Cybattler"},
        {"cyberb21",    "Cyberball 2072 (2 player, rev 1)"},
        {"cyberb22",    "Cyberball 2072 (2 player, rev 2)"},
        {"cyberb23",    "Cyberball 2072 (2 player, rev 3)"},
        {"cyberb2p",    "Cyberball 2072 (2 player, rev 4)"},
        {"cyberba2",    "Cyberball (rev 2)"},
        {"cyberbal",    "Cyberball (rev 4)"},
        {"cyberbal1",   "Cyberball (rev 1)"},
        {"cyberbal2",   "Cyberball (rev 2)"},
        {"cyberbal2p",  "Cyberball 2072 (2 player, rev 4)"},
        {"cyberbal2p1", "Cyberball 2072 (2 player, rev 1)"},
        {"cyberbal2p2", "Cyberball 2072 (2 player, rev 2)"},
        {"cyberbal2p3", "Cyberball 2072 (2 player, rev 3)"},
        {"cyberbalp",   "Cyberball (prototype)"},
        {"cyberbalt",   "Tournament Cyberball 2072 (rev 2)"},
        {"cyberbalt1",  "Tournament Cyberball 2072 (rev 1)"},
        {"cyberbap",    "Cyberball (prototype)"},
        {"cyberbt",     "Tournament Cyberball 2072 (rev 2)"},
        {"cyberbt1",    "Tournament Cyberball 2072 (rev 1)"},
        {"cyberlip",    "Cyber-Lip"},
        {"cybertnk",    "Cyber Tank (v1.4)"},
        {"cyborgforce", "Cyborg Force!"},
        {"cybots",      "Cyberbots: Fullmetal Madness (Euro 950424)"},
        {"cybotsj",     "Cyberbots: Fullmetal Madness (Japan 950420)"},
        {"cybotsjd",    "Cyberbots: Fullmetal Madness (Japan 950424) (decrypted bootleg)"},
        {"cybotsu",     "Cyberbots: Fullmetal Madness (USA 950424)"},
        {"cybotsud",    "Cyberbots: Fullmetal Madness (USA 950424 Phoenix Edition) (bootleg)"},
        {"cybrcomm",    "Cyber Commando (Rev. CY1, Japan)"},
        {"cybrcycc",    "Cyber Cycles (Rev. CB2 Ver.C)"},
        {"cybrcyccj",   "Cyber Cycles (Japan, CB1 Ver.C)"},
        {"cybsled",     "Cyber Sled"},
        {"cybsledj",    "Cyber Sled (Japan)"},
        {"cybstorm",    "Cyberstorm (prototype)"},
        {"cyclemb",     "Cycle Maabou (Japan)"},
        {"cyclshtg",    "Cycle Shooting"},
        {"cyclwarr",    "Cycle Warriors"},
        {"cyvern",      "Cyvern (Japan)"},
        {"cyvernj",     "Cyvern - The Dragon Weapons (Japan)"},
        {"czeroize",    "Cassette: Zeroize"},
};

const char *lookup_c(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_c(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
