#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"m4",           "M-4"},
        {"m660",         "Mission 660 (US)"},
        {"m660b",        "Mission 660 (bootleg)"},
        {"m660j",        "Mission 660 (Japan)"},
        {"m79amb",       "M79 Ambush"},
        {"mace",         "Mace - The Dark Age"},
        {"macea",        "Mace: The Dark Age (HDD 1.0a)"},
        {"mach3",        "M.A.C.H. 3"},
        {"mach3a",       "M.A.C.H. 3 (set 2)"},
        {"mach3b",       "M.A.C.H. 3 (set 3)"},
        {"mach9",        "Mach-9 (bootleg of Vulgus)"},
        {"macha",        "Monoshiri Quiz Oshaberi Macha (Japan)"},
        {"machbrkr",     "Mach Breakers (Japan)"},
        {"machbrkrj",    "Mach Breakers - Numan Athletics 2 (Japan, MB1)"},
        {"machomou",     "Macho Mouse"},
        {"machridj",     "Vs. Mach Rider (Japan, Fighting Course Version)"},
        {"machridr",     "Vs. Mach Rider (Endurance Course Version)"},
        {"macross",      "Super Spacefortress Macross - Chou-Jikuu Yousai Macross"},
        {"macross2",     "Super Spacefortress Macross II - Chou-Jikuu Yousai Macross II"},
        {"macross2g",    "Super Spacefortress Macross II / Chou-Jikuu Yousai Macross II (Gamest review build)"},
        {"macross2k",    "Macross II (Korea)"},
        {"macrossp",     "Macross Plus"},
        {"madalien",     "Mad Alien"},
        {"madaliena",    "Mad Alien (set 2)"},
        {"madalienb",    "Mad Alien (set 2, alt gfx)"},
        {"madball",      "Mad Ball V2.0"},
        {"madballn",     "Mad Ball V2.0 (With Nudity)"},
        {"madcrash",     "Mad Crasher"},
        {"madcrush",     "Mad Crusher (Japan)"},
        {"maddonna",     "Mad Donna (set 1)"},
        {"maddonnb",     "Mad Donna (set 2)"},
        {"madgear",      "Mad Gear (US)"},
        {"madgearj",     "Mad Gear (Japan)"},
        {"madmotor",     "Mad Motor"},
        {"madshark",     "Mad Shark"},
        {"madsharkbl",   "Mad Shark (bootleg)"},
        {"magdrop",      "Magical Drop (Japan, Version 1.1)"},
        {"magdrop2",     "Magical Drop II"},
        {"magdrop3",     "Magical Drop III"},
        {"magdropp",     "Magical Drop Plus 1 (Japan, Version 2.1)"},
        {"magerror",     "Magical Error wo Sagase"},
        {"magicbal",     "Magicball Fighting (Korea)"},
        {"magicbub",     "Magic Bubble"},
        {"magicbuba",    "Magic Bubble (Adult version, YS1302 PCB, set 1)"},
        {"magicbubb",    "Magic Bubble (Adult version, YS1302 PCB, set 2)"},
        {"magicbubc",    "Magic Bubble (Adult version, YS-0211 PCB)"},
        {"magipur",      "Magic Purple"},
        {"magix",        "Magix - Rock"},
        {"magixb",       "Magix / Rock (no copyright message)"},
        {"maglord",      "Magician Lord (set 1)"},
        {"maglordh",     "Magician Lord (set 2)"},
        {"magmax",       "Mag Max"},
        {"magmaxa",      "Mag Max (set 2)"},
        {"magspeed",     "Magical Speed"},
        {"magspot",      "Magical Spot"},
        {"magspot2",     "Magical Spot II"},
        {"magtruck",     "Magical Truck Adventure (Export)"},
        {"maguila",      "Up Maguila (bootleg of Donkey Kong Jr.)"},
        {"magworm",      "Magic Worm (bootleg of Centipede)"},
        {"mahmajn",      "Tokoro San no MahMahjan"},
        {"mahmajn2",     "Tokoro San no MahMahjan 2"},
        {"mahoudai",     "Mahou Daisakusen (Japan)"},
        {"mahretsu",     "Mahjong Kyoretsuden"},
        {"maiko",        "Maikobana (Japan 900802)"},
        {"mainev2p",     "The Main Event (2 Players ver. X)"},
        {"mainevt",      "The Main Event (4 Players ver. Y)"},
        {"mainevt2p",    "The Main Event (2 Players ver. X)"},
        {"mainevto",     "The Main Event (4 Players ver. F)"},
        {"mainsnk",      "Main Event (1984)"},
        {"majest12",     "Majestic Twelve - The Space Invaders Part IV (Japan)"},
        {"majest12j",    "Majestic Twelve - The Space Invaders Part IV (Japan)"},
        {"majest12u",    "Majestic Twelve - The Space Invaders Part IV (US, revised code, Rev 1)"},
        {"majest12ua",   "Majestic Twelve - The Space Invaders Part IV (US, revised code)"},
        {"majest12ub",   "Majestic Twelve - The Space Invaders Part IV (US, earlier code base)"},
        {"majs101b",     "Mahjong Studio 101 [BET] (Japan)"},
        {"majtitl2",     "Major Title 2 (World)"},
        {"majtitl2a",    "Major Title 2 (World, set 1, alt sound CPU)"},
        {"majtitl2b",    "Major Title 2 (World, set 2)"},
        {"majtitl2j",    "Major Title 2 (Japan)"},
        {"majtitle",     "Major Title (Japan)"},
        {"majtitlej",    "Major Title (Japan)"},
        {"majuu",        "Majuu no Ohkoku"},
        {"makaiden",     "Makai Densetsu (Japan)"},
        {"makaimuc",     "Makai-Mura (Japan Revision C)"},
        {"makaimug",     "Makai-Mura (Japan Revision G)"},
        {"makaimur",     "Makai-Mura (Japan)"},
        {"makaimurb",    "Makaimura (Japan Revision B)"},
        {"makaimurc",    "Makaimura (Japan Revision C)"},
        {"makaimurg",    "Makaimura (Japan Revision G)"},
        {"maketrax",     "Make Trax (set 1)"},
        {"maketrxb",     "Make Trax (set 2)"},
        {"makyosen",     "Makyou Senshi (Japan)"},
        {"maletmad",     "Mallet Madness (v2.1)"},
        {"malzak",       "Malzak"},
        {"mamonoro",     "Mamoru-kun wa Norowarete Shimatta! (Japan)"},
        {"mangchi",      "Mang-Chi"},
        {"manhatan",     "Manhattan 24 Bunsyo (Japan)"},
        {"maniach",      "Mania Challenge (set 1)"},
        {"maniach2",     "Mania Challenge (set 2)"},
        {"maniacsp",     "Maniac Square (prototype)"},
        {"maniacsq",     "Maniac Square (unprotected)"},
        {"maniacsqa",    "Maniac Square (protected, Version 1.0, Checksum CF2D)"},
        {"maniacsqs",    "Maniac Square (unprotected, Version 1.0, Checksum 66B1, 960419/1 PCB)"},
        {"maniacsqu",    "Maniac Square (unprotected, Version 1.0, Checksum BB73)"},
        {"manicpnc",     "Manic Panic Ghosts! (USA, Export)"},
        {"manxtt",       "Manx TT Superbike - DX/Twin (Revision D)"},
        {"manxtta",      "Manx TT Superbike - DX/Twin (Revision C, set 2)"},
        {"manxttc",      "Manx TT Superbike - DX/Twin (Revision C)"},
        {"manxttdx",     "Manx TT Superbike - DX"},
        {"manybloc",     "Many Block"},
        {"mappy",        "Mappy (US)"},
        {"mappyj",       "Mappy (Japan)"},
        {"marble",       "Marble Madness (set 1)"},
        {"marble2",      "Marble Madness (set 2)"},
        {"marble3",      "Marble Madness (set 3)"},
        {"marble4",      "Marble Madness (set 4)"},
        {"marble5",      "Marble Madness (set 5 - LSI Cartridge)"},
        {"marblmd2",     "Marble Madness II (prototype)"},
        {"marineb",      "Marine Boy"},
        {"marinedt",     "Marine Date"},
        {"mariner",      "Mariner"},
        {"mario",        "Mario Bros. (US, Revision G)"},
        {"mariobl",      "Mario Bros. (bootleg on Ambush Hardware, set 1)"},
        {"mariobla",     "Mario Bros. (bootleg on Ambush Hardware, set 2)"},
        {"marioe",       "Mario Bros. (US, Revision E)"},
        {"mariof",       "Mario Bros. (US, Revision F)"},
        {"marioj",       "Mario Bros. (Japan, Revision C)"},
        {"mariorou",     "Mario Roulette"},
        {"markham",      "Markham"},
        {"mars",         "Mars"},
        {"maruchan",     "Maru-Chan de Goo!"},
        {"marukin",      "Super Marukin-Ban"},
        {"marukodq",     "Chibi Marukochan Deluxe Quiz"},
        {"marvins",      "Marvin's Maze"},
        {"marvland",     "Marvel Land (US)"},
        {"marvlandup",   "Marvel Land (US, prototype)"},
        {"marvlanj",     "Marvel Land (Japan)"},
        {"masao",        "Masao"},
        {"mastboy",      "Master Boy (Spanish, rev A)"},
        {"mastboya",     "Master Boy (Spanish, rev A, hack?)"},
        {"mastboyi",     "Master Boy (Italian, rev A, set 1)"},
        {"mastboyia",    "Master Boy (Italian, rev A, set 2)"},
        {"mastboyo",     "Master Boy (1987, Z80 hardware, Covielsa, set 1)"},
        {"mastboyoa",    "Master Boy (1987, Z80 hardware, Covielsa, set 2)"},
        {"mastboyob",    "Master Boy (1987, Z80 hardware, Ichi-Funtel, set 1)"},
        {"mastboyoc",    "Master Boy (1987, Z80 hardware, Ichi-Funtel, set 2)"},
        {"masterw",      "Master of Weapon (World)"},
        {"masterwj",     "Master of Weapon (Japan)"},
        {"masterwu",     "Master of Weapon (US)"},
        {"mastfury",     "Master's Fury"},
        {"mastkin",      "The Masters of Kin"},
        {"matchit",      "Match It"},
        {"matchit2",     "Match It II"},
        {"matchitb",     "Match It (bootleg)"},
        {"matmania",     "Mat Mania"},
        {"matrim",       "Power Instinct Matrimelee"},
        {"matrimbl",     "Matrimelee / Shin Gouketsuji Ichizoku Toukon (bootleg)"},
        {"mausuke",      "Mausuke no Ojama the World"},
        {"maxf_102",     "Maximum Force v1.02"},
        {"maxf_ng",      "Maximum Force (No Gore version)"},
        {"maxforce",     "Maximum Force v1.05"},
        {"maxrpm",       "Max RPM"},
        {"maxspeed",     "Maximum Speed"},
        {"maya",         "Maya"},
        {"mayaa",        "Maya (set 2)"},
        {"mayab",        "Maya (set 3)"},
        {"mayac",        "Maya (set 4, clean)"},
        {"mayday",       "Mayday (set 1)"},
        {"maydaya",      "Mayday (set 2)"},
        {"maydayb",      "Mayday (set 3)"},
        {"mayhem",       "Mayhem 2002"},
        {"mayjisn2",     "Mayjinsen 2"},
        {"mayumi",       "Kikiippatsu Mayumi-chan (Japan)"},
        {"mazan",        "Mazan: Flash of the Blade (World, MAZ2 Ver.A)"},
        {"mazana",       "Mazan: Flash of the Blade (Asia, MAZ2 Ver.A)"},
        {"mazanj",       "Mazan: Flash of the Blade (Japan, MAZ1 Ver.A)"},
        {"mazanu",       "Mazan: Flash of the Blade (US, MAZ3 Ver.A)"},
        {"maze",         "Amazing Maze"},
        {"mazebl",       "Maze (Trog rev LA4 3/11/91 bootleg)"},
        {"mazeinv",      "Maze Invaders (prototype)"},
        {"mazerbla",     "Mazer Blazer"},
        {"mazinger",     "Mazinger Z"},
        {"mazingerj",    "Mazinger Z (Japan)"},
        {"mbaa",         "Melty Blood Actress Again Version A (Japan, Rev A)"},
        {"mbaaa",        "Melty Blood Actress Again Version A (Rev A)"},
        {"mbaao",        "Melty Blood Actress Again (Japan)"},
        {"mblkjack",     "Black Jack (Mirco)"},
        {"mbomberj",     "Muscle Bomber - The Body Explosion (Japan 930713)"},
        {"mbombrd",      "Muscle Bomber Duo - Ultimate Team Battle (World 931206)"},
        {"mbombrdj",     "Muscle Bomber Duo - Heat Up Warriors (Japan 931206)"},
        {"mbrush",       "Magic Brush"},
        {"mcatadv",      "Magical Cat Adventure"},
        {"mcatadvj",     "Magical Cat Adventure (Japan)"},
        {"mchampdx",     "Multi Champ Deluxe (ver. 0106, 06-01-2000)"},
        {"mchampdxa",    "Multi Champ Deluxe (ver. 1126, 26-11-1999)"},
        {"mchampdxb",    "Multi Champ Deluxe (ver. 1114, 14/11/1999)"},
        {"mcheonru",     "Ma Cheon Ru"},
        {"mcnpshnt",     "Mahjong Campus Hunting (Japan)"},
        {"mcontest",     "Miss Mahjong Contest (Japan)"},
        {"mcwars",       "Macro-Cosm Wars (bootleg of Galaxian)"},
        {"mdhorse",      "Derby Quiz My Dream Horse (MDH1-VER.A)"},
        {"mechatt",      "Mechanized Attack (World)"},
        {"mechattj",     "Mechanized Attack (Japan)"},
        {"mechattu",     "Mechanized Attack (US)"},
        {"mechattu1",    "Mechanized Attack (US, Version 1, Single Player)"},
        {"medlanes",     "Meadows Lanes"},
        {"megab",        "Mega Blast (World)"},
        {"megabj",       "Mega Blast (Japan)"},
        {"megablst",     "Mega Blast (World)"},
        {"megablstj",    "Mega Blast (Japan)"},
        {"megablstu",    "Mega Blast (US)"},
        {"megadon",      "Megadon"},
        {"megaforc",     "Mega Force"},
        {"megaforcu",    "Mega Force (US)"},
        {"megaman",      "Mega Man - The Power Battle (CPS1 Asia 951006)"},
        {"megaman2",     "Mega Man 2: The Power Fighters (USA 960708)"},
        {"megaman2a",    "Mega Man 2: The Power Fighters (Asia 960708)"},
        {"megaman2h",    "Mega Man 2: The Power Fighters (Hispanic 960712)"},
        {"megamana",     "Mega Man: The Power Battle (CPS1, Asia 951006)"},
        {"megamn2d",     "Mega Man 2: The Power Fighters (USA 960708 Phoenix Edition) (bootleg)"},
        {"megaphx",      "Mega Phoenix"},
        {"megaplay",     "MegaPlay: BIOS"},
        {"megat",        "Pit Boss Megatouch (9234-20-01 R0A)"},
        {"megat2",       "Pit Boss Megatouch II (9255-10-01 R0G, Standard version)"},
        {"megat2a",      "Pit Boss Megatouch II (9255-10-01 R0E, Standard version)"},
        {"megat2b",      "Pit Boss Megatouch II (9255-10-01 R0D, Standard version)"},
        {"megat2ca",     "Pit Boss Megatouch II (9255-10-06 R0G, California version)"},
        {"megat2caa",    "Pit Boss Megatouch II (9255-10-06 R0E, California version)"},
        {"megat2mn",     "Pit Boss Megatouch II (9255-10-02 R0G, Minnesota version)"},
        {"megat3",       "Megatouch III (9255-20-01 R0N, Standard version)"},
        {"megat3a",      "Megatouch III (9255-20-01 R0K, Standard version)"},
        {"megat3b",      "Megatouch III (9255-20-01 R0F, Standard version)"},
        {"megat3c",      "Megatouch III (9255-20-01 R0B, Standard version)"},
        {"megat3ca",     "Megatouch III (9255-20-06 R0N, California version)"},
        {"megat3caa",    "Megatouch III (9255-20-06 R0D, California version)"},
        {"megat3d",      "Megatouch III (9255-20-01 R0A, Standard version)"},
        {"megat3nj",     "Megatouch III (9255-20-07 R0G, New Jersey version)"},
        {"megat3te",     "Megatouch III Tournament Edition (9255-30-01 R0E, Standard version)"},
        {"megat3tg",     "Megatouch III Turnier Edition (9255-30-50 R0F, Bi-Lingual GER/ENG version)"},
        {"megat4",       "Megatouch IV (9255-40-01 R0E, Standard version)"},
        {"megat4a",      "Megatouch IV (9255-40-01 R0D, Standard version)"},
        {"megat4b",      "Megatouch IV (9255-40-01 R0B, Standard version)"},
        {"megat4c",      "Megatouch IV (9255-40-01 R0A, Standard version)"},
        {"megat4d",      "Megatouch IV (9255-40-01 R0, Standard version)"},
        {"megat4s",      "Super Megatouch IV (9255-41-01 R0G, Standard version)"},
        {"megat4sa",     "Super Megatouch IV (9255-41-01 R0E, Standard version)"},
        {"megat4sb",     "Super Megatouch IV (9255-41-01 R0C, Standard version)"},
        {"megat4smn",    "Super Megatouch IV (9255-41-02 R0C, Minnesota version)"},
        {"megat4snj",    "Super Megatouch IV (9255-41-07 R0G, New Jersey version)"},
        {"megat4st",     "Super Megatouch IV Tournament Edition (9255-51-01 R0B, Standard version)"},
        {"megat4stg",    "Super Megatouch IV Turnier Version (9255-51-50 R0A, Bi-Lingual GER/ENG version)"},
        {"megat4te",     "Megatouch IV Tournament Edition (9255-50-01 R0D, Standard version)"},
        {"megat4tea",    "Megatouch IV Tournament Edition (9255-50-01 R0A, Standard version)"},
        {"megat5",       "Megatouch 5 (9255-60-01 R0I, Standard version)"},
        {"megat5g",      "Megatouch 5 (9255-60-50 R0G, Bi-Lingual GER/ENG version)"},
        {"megat5nj",     "Megatouch 5 (9255-60-07 R0N, New Jersey version)"},
        {"megat5t",      "Megatouch 5 Tournament Edition (9255-70-01 R0C, Standard version)"},
        {"megat5tg",     "Megatouch 5 Turnier Version (9255-70-50 R0D, Bi-Lingual GER/ENG version)"},
        {"megat6",       "Megatouch 6 (9255-80-01 R0A, Standard version)"},
        {"megat7e",      "Megatouch 7 Encore Edition (9255-90-01 R00, Standard version)"},
        {"megatack",     "MegaTack"},
        {"megatacka",    "Megatack (set 2)"},
        {"megatech",     "MegaTech - Bios"},
        {"megaznik",     "Mega Zone (Kosuka)"},
        {"megazone",     "Mega Zone"},
        {"megazonea",    "Mega Zone (unknown program code 1)"},
        {"megazoneb",    "Mega Zone (unknown program code 2)"},
        {"megazoneh",    "Mega Zone (program code H)"},
        {"megazonei",    "Mega Zone (program code I)"},
        {"megazonej",    "Mega Zone (program code J)"},
        {"megrescu",     "Megumi Rescue"},
        {"meikyuh",      "Meikyuu Hunter G (Japan)"},
        {"meikyuhbl",    "Meikyuu Hunter G (Japan, bootleg)"},
        {"meltyb",       "Melty Blood Act Cadenza Version B2 (Japan) (GDL-0039A)"},
        {"meltyba",      "Melty Blood Act Cadenza Version B2 (GDL-0039A)"},
        {"meltybld",     "Melty Blood Act Cadenza Ver. A (Japan) (GDL-0028C)"},
        {"meltyblo",     "Melty Blood Act Cadenza (Japan) (GDL-0028)"},
        {"meltybo",      "Melty Blood Act Cadenza Version B (Japan) (GDL-0039)"},
        {"meosism",      "Meosis Magic (Japan)"},
        {"mercenario",   "Mercenario (bootleg of Commando)"},
        {"mercs",        "Mercs (World 900302)"},
        {"mercsj",       "Senjou no Ookami II (Japan 900302)"},
        {"mercsu",       "Mercs (US 900302)"},
        {"mercsua",      "Mercs (US 900608)"},
        {"mercsur1",     "Mercs (USA 900302)"},
        {"merlinmm",     "Merlins Money Maze"},
        {"mermaid",      "Mermaid"},
        {"metafox",      "Meta Fox"},
        {"metalb",       "Metal Black (World)"},
        {"metalbj",      "Metal Black (Japan)"},
        {"metamrph",     "Metamorphic Force (US ver UAA)"},
        {"metamrpha",    "Metamorphic Force (ver AAA)"},
        {"metamrphe",    "Metamorphic Force (ver EAA - alternate)"},
        {"metamrphj",    "Metamorphic Force (ver JAA)"},
        {"metamrphu",    "Metamorphic Force (ver UAA)"},
        {"metamrpj",     "Metamorphic Force (Japan ver JAA)"},
        {"meteor",       "Meteoroids"},
        {"meteora",      "Meteor (Alca bootleg of Moon Cresta)"},
        {"meteorbl",     "Meteor (bootleg of Asteroids)"},
        {"meteorho",     "Meteor (Hoei bootleg of Asteroids)"},
        {"meteorite",    "Meteorite (Proel bootleg of Asteroids)"},
        {"meteors",      "Meteors"},
        {"meteorts",     "Meteorites (VGG bootleg of Asteroids)"},
        {"metlclsh",     "Metal Clash (Japan)"},
        {"metlfrzr",     "Metal Freezer (Japan)"},
        {"metlhawk",     "Metal Hawk (Japan)"},
        {"metlhawkj",    "Metal Hawk (Japan, Rev F)"},
        {"metlsavr",     "Metal Saver"},
        {"metmqstr",     "Metamoqester"},
        {"metrocra",     "Metro-Cross (set 2)"},
        {"metrocrs",     "Metro-Cross (set 1)"},
        {"metrocrsa",    "Metro-Cross (set 2)"},
        {"mexico86",     "Mexico 86"},
        {"mf_achas",     "Astro Chase (Max-A-Flex)"},
        {"mf_bdash",     "Boulder Dash (Max-A-Flex)"},
        {"mf_brist",     "Bristles (Max-A-Flex)"},
        {"mf_flip",      "Flip & Flop (Max-A-Flex)"},
        {"mfunclub",     "Mahjong Fun Club - Idol Saizensen (Japan)"},
        {"mgakuen",      "Mahjong Gakuen"},
        {"mgakuen2",     "Mahjong Gakuen 2 Gakuen-chou no Fukushuu"},
        {"mgcldate",     "Magical Date (JAPAN) set 1"},
        {"mgcldtea",     "Magical Date (JAPAN) set 2"},
        {"mgcrystj",     "Magical Crystals (Japan)"},
        {"mgcrystl",     "Magical Crystals (World)"},
        {"mgcrystlj",    "Magical Crystals (Japan, 92/01/13)"},
        {"mgcrystlo",    "Magical Crystals (World, 91/12/10)"},
        {"mgmen89",      "Mahjong G-MEN'89 (Japan 890425)"},
        {"mhavoc",       "Major Havoc (rev 3)"},
        {"mhavoc2",      "Major Havoc (rev 2)"},
        {"mhavocp",      "Major Havoc (prototype)"},
        {"mhavocrv",     "Major Havoc (Return to Vax)"},
        {"mhgaiden",     "Mahjong Hourouki Gaiden (Japan)"},
        {"mia",          "M.I.A. - Missing in Action (version T)"},
        {"mia2",         "M.I.A. - Missing in Action (version S)"},
        {"miaj",         "M.I.A. - Missing in Action (Japan)"},
        {"micon2",       "Micon-Kit Part II"},
        {"midnrun",      "Midnight Run: Road Fighter 2 (EAA, Euro v1.11)"},
        {"midnruna",     "Midnight Run: Road Fighter 2 (AAA, Asia v1.10, older sound program)"},
        {"midnruna2",    "Midnight Run: Road Fighter 2 (AAA, Asia v1.10, newer sound program)"},
        {"midnrunj",     "Midnight Run: Road Fighter 2 (JAD, Japan v1.10)"},
        {"midres",       "Midnight Resistance (World)"},
        {"midres2",      "Midnight Resistance (World, set 2)"},
        {"midresb",      "Midnight Resistance (bootleg with 68705)"},
        {"midresbj",     "Midnight Resistance (joystick hack bootleg)"},
        {"midresj",      "Midnight Resistance (Japan)"},
        {"midresu",      "Midnight Resistance (US)"},
        {"miexchng",     "Money Puzzle Exchanger / Money Idol Exchanger"},
        {"mightguy",     "Mighty Guy"},
        {"mightybj",     "Vs. Mighty Bomb Jack (Japan)"},
        {"mikie",        "Mikie"},
        {"mikiehs",      "Mikie (High School Graffiti)"},
        {"mikiej",       "Shinnyuushain Tooru-kun"},
        {"mikiek",       "Shin-ip Sawon - Seok Dol-i"},
        {"millipdd",     "Millipede Dux (hack)"},
        {"milliped",     "Millipede"},
        {"millpac",      "Millpac (bootleg of Centipede)"},
        {"mimonkey",     "Mighty Monkey"},
        {"mimonsco",     "Mighty Monkey (bootleg on Super Cobra hardware)"},
        {"mimonscr",     "Mighty Monkey (bootleg on Scramble hardware)"},
        {"mimonscra",    "Mighty Monkey (Kaina Games, bootleg on Scramble hardware)"},
        {"minasan",      "Minnasanno Okagesamadesu"},
        {"minefld",      "Minefield"},
        {"minefldfe",    "Minefield (The Logicshop, bootleg)"},
        {"mineswpr",     "Minesweeper"},
        {"minferno",     "Inferno (S2650)"},
        {"minigol2",     "Mini Golf (set 2)"},
        {"minigolf",     "Mini Golf (set 1)"},
        {"minigolfa",    "Mini Golf (11/25/85)"},
        {"minigolfb",    "Mini Golf (10/8/85)"},
        {"minivadr",     "Minivader"},
        {"mirax",        "Mirax"},
        {"miraxa",       "Mirax (set 2)"},
        {"mirninja",     "Mirai Ninja (Japan)"},
        {"mirninjaa",    "Mirai Ninja (Japan, set 2)"},
        {"missb2",       "Miss Bubble 2"},
        {"missile",      "Missile Command (set 1)"},
        {"missile1",     "Missile Command (rev 1)"},
        {"missile2",     "Missile Command (set 2)"},
        {"missmw96",     "Miss Mister World '96 (Nude)"},
        {"missw02",      "Miss World 2002"},
        {"missw96",      "Miss World '96 Nude"},
        {"missw96a",     "Miss World '96 (Nude) (C-3000A PCB, set 2)"},
        {"missw96b",     "Miss World '96 (Nude) (C-3000A PCB, set 3)"},
        {"missw96c",     "Miss World '96 (Nude) (C-3000B PCB)"},
        {"mizubaku",     "Mizubaku Daibouken (Japan)"},
        {"mj4simai",     "Wakakusamonogatari Mahjong Yonshimai (Japan)"},
        {"mjanbari",     "Medal Mahjong Janjan Baribari [BET] (Japan)"},
        {"mjangels",     "Mahjong Angels - Comic Theater Vol.2 (Japan)"},
        {"mjcamera",     "Mahjong Camera Kozou (Japan 881109)"},
        {"mjclinic",     "Mahjong Clinic (Japan)"},
        {"mjderngr",     "Mahjong Derringer (Japan)"},
        {"mjdialq2",     "Mahjong Dial Q2 (Japan)"},
        {"mjdiplob",     "Mahjong Diplomat [BET] (Japan)"},
        {"mjegolf",      "Mahjong Erotica Golf (Japan)"},
        {"mjfocus",      "Mahjong Focus (Japan 890313)"},
        {"mjfocusm",     "Mahjong Focus [BET] (Japan 890510)"},
        {"mjfriday",     "Mahjong Friday (Japan)"},
        {"mjgottsu",     "Mahjong Gottsu ee-kanji (Japan)"},
        {"mjhokite",     "Mahjong Hourouki Okite (Japan)"},
        {"mjifb",        "Mahjong If [BET] (Japan)"},
        {"mjikaga",      "Mahjong Ikaga Desu ka (Japan)"},
        {"mjkinjas",     "Mahjong Kinjirareta Asobi (Japan)"},
        {"mjkjidai",     "Mahjong Kyou Jidai (Japan)"},
        {"mjkoiura",     "Mahjong Koi Uranai (Japan)"},
        {"mjkojink",     "Mahjong Kojinkyouju (Private Teacher) (Japan)"},
        {"mjlaman",      "Mahjong La Man (Japan)"},
        {"mjleague",     "Major League"},
        {"mjlstory",     "Mahjong Jikken Love Story (Japan)"},
        {"mjnanpaa",     "Mahjong Nanpa Story (Japan 890712)"},
        {"mjnanpas",     "Mahjong Nanpa Story (Japan 890713)"},
        {"mjnanpau",     "Mahjong Nanpa Story (Ura) (Japan 890805)"},
        {"mjnatsu",      "Mahjong Natsu Monogatari (Japan)"},
        {"mjnquesb",     "Mahjong Quest (No Nudity)"},
        {"mjnquest",     "Mahjong Quest (Japan)"},
        {"mjsikakb",     "Mahjong Shikaku (Japan 880722)"},
        {"mjsikaku",     "Mahjong Shikaku (Japan 880908)"},
        {"mjsister",     "Mahjong Sisters (Japan)"},
        {"mjuraden",     "Mahjong Uranai Densetsu (Japan)"},
        {"mjyougo",      "Mahjong-yougo no Kisotairyoku (Japan)"},
        {"mjyuugi",      "Mahjong Yuugi (Japan set 1)"},
        {"mjyuugia",     "Mahjong Yuugi (Japan set 2)"},
        {"mjzoomin",     "Mahjong Channel Zoom In"},
        {"mk",           "Mortal Kombat (rev 5.0 T-Unit 03-19-93)"},
        {"mk2",          "Mortal Kombat II (rev L3.1)"},
        {"mk2chal",      "Mortal Kombat II Challenger (hack)"},
        {"mk2p",         "Mortal Kombat II Plus (Beta 2)"},
        {"mk2r11",       "Mortal Kombat II (rev L1.1)"},
        {"mk2r14",       "Mortal Kombat II (rev L1.4)"},
        {"mk2r20",       "Mortal Kombat II (rev L2.0)"},
        {"mk2r21",       "Mortal Kombat II (rev L2.1)"},
        {"mk2r30",       "Mortal Kombat II (rev L3.0)"},
        {"mk2r31e",      "Mortal Kombat II (rev L3.1, European)"},
        {"mk2r32",       "Mortal Kombat II (rev L3.2 (European))"},
        {"mk2r32e",      "Mortal Kombat II (rev L3.2, European)"},
        {"mk2r42",       "Mortal Kombat II (rev L4.2, hack)"},
        {"mk2r91",       "Mortal Kombat II (rev L9.1, hack)"},
        {"mk3",          "Mortal Kombat 3 (rev 2.1)"},
        {"mk3mdb",       "Mortal Kombat 3 (bootleg of Mega Drive version)"},
        {"mk3p40",       "Mortal Kombat 3 (rev 1 chip label p4.0)"},
        {"mk3r10",       "Mortal Kombat 3 (rev 1.0)"},
        {"mk3r20",       "Mortal Kombat 3 (rev 2.0)"},
        {"mk4",          "Mortal Kombat 4 (version 3.0)"},
        {"mk4a",         "Mortal Kombat 4 (version 2.1)"},
        {"mk4b",         "Mortal Kombat 4 (version 1.0)"},
        {"mkeibaou",     "Mahjong Keibaou (Japan)"},
        {"mkla1",        "Mortal Kombat (rev 1.0 08-08-92)"},
        {"mkla2",        "Mortal Kombat (rev 2.0 08-18-92)"},
        {"mkla3",        "Mortal Kombat (rev 3.0 08-31-92)"},
        {"mkla3bl",      "Mortal Kombat (Victor bootleg of rev 3.0 08/31/92)"},
        {"mkla4",        "Mortal Kombat (rev 4.0 09-28-92)"},
        {"mknifty",      "Mortal Kombat (Nifty Kombo, hack)"},
        {"mknifty666",   "Mortal Kombat (Nifty Kombo 666, hack)"},
        {"mkprot4",      "Mortal Kombat (prototype, rev 4.0 07/14/92)"},
        {"mkprot8",      "Mortal Kombat (prototype, rev 8.0 07/21/92)"},
        {"mkprot9",      "Mortal Kombat (prototype, rev 9.0 07-28-92)"},
        {"mkr4",         "Mortal Kombat (rev 4.0 T-Unit 02-11-93)"},
        {"mktturbo",     "Mortal Kombat (Turbo Ninja T-Unit 03/19/93, hack)"},
        {"mkyawdim",     "Mortal Kombat (Yawdim bootleg, set 1)"},
        {"mkyawdim2",    "Mortal Kombat (Yawdim bootleg, set 2)"},
        {"mkyawdim3",    "Mortal Kombat (Yawdim bootleg, set 3)"},
        {"mkyawdim4",    "Mortal Kombat (Yawdim bootleg, set 4)"},
        {"mkyturbo",     "Mortal Kombat (Turbo 3.1 09/09/93, hack)"},
        {"mkyturboe",    "Mortal Kombat (Turbo 3.0 08/31/92, hack)"},
        {"mladyhtr",     "Mahjong THE LADY HUNTER (Japan 900509)"},
        {"mlander",      "Moon Lander (bootleg of Lunar Rescue)"},
        {"mlanding",     "Midnight Landing (Germany)"},
        {"mlandingj",    "Midnight Landing (Japan, rev 3)"},
        {"mltiwars",     "Multi Wars (bootleg of UniWar S)"},
        {"mmancp2u",     "Mega Man: The Power Battle (CPS2, USA 951006, SAMPLE Version)"},
        {"mmancp2ur1",   "Mega Man: The Power Battle (CPS2, USA 950926, SAMPLE Version)"},
        {"mmancp2ur2",   "Mega Man: The Power Battle (CPS2, USA 950925, SAMPLE Version)"},
        {"mmatrix",      "Mars Matrix: Hyper Solid Shooting (USA 000412)"},
        {"mmatrixa",     "Mars Matrix: Hyper Solid Shooting (Asia 000412)"},
        {"mmatrixd",     "Mars Matrix: Hyper Solid Shooting (USA 000412 Phoenix Edition) (bootleg)"},
        {"mmatrixj",     "Mars Matrix: Hyper Solid Shooting (Japan 000412)"},
        {"mmaulers",     "Monster Maulers (ver EAA)"},
        {"mmaze",        "Marchen Maze (Japan)"},
        {"mmaze2",       "Marchen Maze (Japan, hack?)"},
        {"mmcamera",     "Mahjong Camera Kozou [BET] (Japan 890509)"},
        {"mmehyou",      "Medal Mahjong Circuit no Mehyou [BET] (Japan)"},
        {"mmonkey",      "Minky Monkey"},
        {"mmonkeyj",     "Minky Monkey (Japan)"},
        {"mmpanic",      "Monkey Mole Panic (USA)"},
        {"mmpork",       "Muchi Muchi Pork! (2007/ 4/17 MASTER VER.)"},
        {"mnchmobl",     "Munch Mobile (US)"},
        {"mnight",       "Mutant Night"},
        {"mnightj",      "Mutant Night (Japan)"},
        {"mnrockman",    "Medal Network: Rockman EXE"},
        {"moegonta",     "Moeyo Gonta!! (Japan)"},
        {"mofflott",     "Maze of Flott (Japan)"},
        {"moguchan",     "Moguchan"},
        {"mogura",       "Mogura Desse"},
        {"mok",          "The Maze of the Kings (GDS-0022)"},
        {"mole",         "Mole Attack"},
        {"momoko",       "Momoko 120%"},
        {"momokob",      "Momoko 120% (bootleg)"},
        {"momokoe",      "Momoko 120% (English text)"},
        {"monkelf",      "Monky Elf (Korean bootleg of Avenging Spirit)"},
        {"monkeyba",     "Monkey Ball (GDS-0008)"},
        {"monkeyd",      "Monkey Donkey"},
        {"monoplcl",     "Monopoly Classic (JPM) (Version 5) (SYSTEM5 VIDEO)"},
        {"monoplcld",    "Monopoly Classic (JPM) (Version 5, Protocol) (SYSTEM5 VIDEO)"},
        {"monopldx",     "Monopoly Deluxe (JPM) (Version 6) (SYSTEM5 VIDEO)"},
        {"monopldxd",    "Monopoly Deluxe (JPM) (Version 6, Protocol) (SYSTEM5 VIDEO)"},
        {"monopoly",     "Monopoly (JPM) (Version 4H) (SYSTEM5 VIDEO)"},
        {"monopoly3",    "Monopoly (JPM) (Version 3) (SYSTEM5 VIDEO)"},
        {"monopoly4",    "Monopoly (JPM) (Version 4) (SYSTEM5 VIDEO)"},
        {"monopolyd",    "Monopoly (JPM) (Version 4H, Protocol) (SYSTEM5 VIDEO)"},
        {"monsterb",     "Monster Bash"},
        {"monsterz",     "Monster Zero (set 1)"},
        {"monsterza",    "Monster Zero (set 2)"},
        {"montecar",     "Monte Carlo"},
        {"monymony",     "Money Money"},
        {"monymony2",    "Money Money (set 2)"},
        {"moo",          "Wild West C.O.W.-Boys of Moo Mesa (World version EA)"},
        {"moobl",        "Wild West C.O.W.-Boys of Moo Mesa (bootleg version AA)"},
        {"moomesa",      "Wild West C.O.W.-Boys of Moo Mesa (ver EAB)"},
        {"moomesaaab",   "Wild West C.O.W.-Boys of Moo Mesa (ver AAB)"},
        {"moomesauab",   "Wild West C.O.W.-Boys of Moo Mesa (ver UAB)"},
        {"moomesauac",   "Wild West C.O.W.-Boys of Moo Mesa (ver UAC)"},
        {"moonal2",      "Moon Alien Part 2"},
        {"moonal2b",     "Moon Alien Part 2 (older version)"},
        {"moonaln",      "Moon Alien"},
        {"moonbase",     "Moon Base"},
        {"mooncmw",      "Moon War (bootleg of Moon Cresta)"},
        {"mooncptc",     "Moon Cresta (Petaco S.A. Spanish bootleg)"},
        {"mooncrecm",    "Moon Cresta (Centromatic Spanish bootleg)"},
        {"mooncreg",     "Moon Cresta (Electrogame S.A. Spanish bootleg, set 1)"},
        {"mooncreg2",    "Moon Cresta (Electrogame S.A. Spanish bootleg, set 2)"},
        {"mooncrgx",     "Moon Cresta (Galaxian hardware)"},
        {"mooncrs2",     "Moon Cresta (bootleg set 2)"},
        {"mooncrs3",     "Moon Cresta (bootleg set 3)"},
        {"mooncrs4",     "Moon Crest (bootleg of Moon Cresta)"},
        {"mooncrsa",     "Moon Cresta (Nichibutsu, old rev)"},
        {"mooncrsb",     "Moon Cresta (bootleg set 1)"},
        {"mooncrsg",     "Moon Cresta (Gremlin)"},
        {"mooncrsl",     "Cresta Mundo (Spanish bootleg of Moon Cresta)"},
        {"mooncrst",     "Moon Cresta (Nichibutsu)"},
        {"mooncrstg",    "Moon Cresta (Gremlin)"},
        {"mooncrsto",    "Moon Cresta (Nichibutsu, old rev)"},
        {"mooncrstso",   "Moon Cresta (SegaSA / Sonic)"},
        {"mooncrstu",    "Moon Cresta (Nichibutsu USA, encrypted)"},
        {"mooncrstuk",   "Moon Cresta (Nichibutsu UK)"},
        {"mooncrstuku",  "Moon Cresta (Nichibutsu UK, unencrypted)"},
        {"mooncrstuu",   "Moon Cresta (Nichibutsu USA, unencrypted)"},
        {"mooncrsu",     "Moon Cresta (Nichibutsu, unencrypted)"},
        {"moonqsr",      "Moon Quasar"},
        {"moonwalk",     "Michael Jackson's Moonwalker (Set 1)"},
        {"moonwar",      "Moonwar"},
        {"moonwara",     "Moonwar (older)"},
        {"moonwarp",     "Moon War (prototype on Frenzy hardware)"},
        {"moonwlka",     "Michael Jackson's Moonwalker (Set 2)"},
        {"moonwlkb",     "Michael Jackson's Moonwalker (bootleg)"},
        {"mooua",        "Wild West C.O.W.-Boys of Moo Mesa (US version UA)"},
        {"moremore",     "More More"},
        {"moremorp",     "More More Plus"},
        {"mortalr",      "Mortal Race"},
        {"mosaic",       "Mosaic"},
        {"mosaica",      "Mosaic (Fuuki)"},
        {"mosaicf2",     "Mosaic (F2 System)"},
        {"mosyougi",     "Syougi No Tatsujin - Master of Syougi"},
        {"motofren",     "Moto Frenzy"},
        {"motofrenft",   "Moto Frenzy (Field Test Version)"},
        {"motofrenmd",   "Moto Frenzy (Mini Deluxe)"},
        {"motofrenmf",   "Moto Frenzy (Mini Deluxe Field Test Version)"},
        {"motorace",     "MotoRace USA"},
        {"motoraid",     "Motor Raid - Twin"},
        {"motoraiddx",   "Motor Raid - Twin/DX"},
        {"motos",        "Motos"},
        {"mototour",     "MotoTour / Zippy Race (Tecfri license)"},
        {"mouja",        "Mouja (Japan)"},
        {"mouncrst",     "Moune Creste (Jeutel French bootleg of Moon Cresta)"},
        {"mouseatk",     "Mouse Attack"},
        {"mouser",       "Mouser"},
        {"mouserc",      "Mouser (Cosmos)"},
        {"mp_bio",       "Bio-Hazard Battle"},
        {"mp_col3",      "Columns III"},
        {"mp_gaxe2",     "Golden Axe II"},
        {"mp_shnb3",     "Shinobi III"},
        {"mp_soni2",     "Sonic The Hedgehog 2"},
        {"mp_sonic",     "Sonic The Hedgehog"},
        {"mp_sor2",      "Streets Of Rage II"},
        {"mp_twc",       "Tecmo World Cup"},
        {"mpang",        "Mighty! Pang (Euro 001010)"},
        {"mpanga",       "Mighty! Pang (Asia 001010)"},
        {"mpangj",       "Mighty! Pang (Japan 001011)"},
        {"mpangr1",      "Mighty! Pang (Euro 000925)"},
        {"mpangu",       "Mighty! Pang (USA 001010)"},
        {"mpatrol",      "Moon Patrol"},
        {"mpatrolw",     "Moon Patrol (Williams)"},
        {"mplanets",     "Mad Planets"},
        {"mplanetsuk",   "Mad Planets (UK)"},
        {"mplanuk",      "Mad Planets (UK)"},
        {"mpumpkin",     "Magical Pumpkin: Puroland de Daibouken (Japan 960712)"},
        {"mranger",      "Moon Ranger (bootleg of Moon Patrol)"},
        {"mrdig",        "Mr. Dig"},
        {"mrdo",         "Mr. Do!"},
        {"mrdobl",       "Mr. Do! (bootleg)"},
        {"mrdofabr",     "Mr. Do! (Fabremar bootleg)"},
        {"mrdofix",      "Mr. Do! (bugfixed)"},
        {"mrdot",        "Mr. Do! (Taito)"},
        {"mrdoy",        "Mr. Do! (prototype)"},
        {"mrdrillr",     "Mr Driller (DRI1-VER.A)"},
        {"mrdrillrj",    "Mr. Driller (Japan, DRI1/VER.A2)"},
        {"mrdrilr2",     "Mr Driller 2"},
        {"mrdrilr2j",    "Mr. Driller 2 (Japan, DR21 Ver.A)"},
        {"mrdrilr2u",    "Mr. Driller 2 (US, DR23 Ver.A)"},
        {"mrdrilrg",     "Mr. Driller G (Japan, DRG1 Ver.A)"},
        {"mrdu",         "Mr. Du!"},
        {"mrflea",       "The Amazing Adventures of Mr. F. Lea"},
        {"mrgoemon",     "Mr. Goemon (Japan)"},
        {"mrheli",       "Mr. HELI no Dai-Bouken"},
        {"mrjong",       "Mr. Jong (Japan)"},
        {"mrkicker",     "Mr. Kicker (F-E1-16-010 PCB)"},
        {"mrkougar",     "Mr. Kougar"},
        {"mrkougar2",    "Mr. Kougar (earlier)"},
        {"mrkougb",      "Mr. Kougar (bootleg)"},
        {"mrkougb2",     "Mr. Kougar (bootleg)"},
        {"mrkougr2",     "Mr. Kougar (earlier)"},
        {"mrlo",         "Mr. Lo!"},
        {"mrokumei",     "Mahjong Rokumeikan (Japan)"},
        {"mrsdyna",      "Mrs. Dynamite"},
        {"mrtnt",        "Mr. TNT"},
        {"mrviking",     "Mister Viking"},
        {"mrvikingj",    "Mister Viking (315-5041, Japan)"},
        {"mrvikngj",     "Mister Viking (Japan)"},
        {"ms4plus",      "Metal Slug 4 Plus (bootleg)"},
        {"ms5pcb",       "Metal Slug 5 (JAMMA PCB)"},
        {"ms5plus",      "Metal Slug 5 Plus (bootleg)"},
        {"msbingo",      "Miss Bingo"},
        {"mschamp",      "Ms. Pacman Champion Edition - Super Zola Pac Gal"},
        {"mschamps",     "Ms. Pacman Champion Edition / Super Zola-Puc Gal"},
        {"mscoutm",      "Mahjong Scout Man (Japan)"},
        {"msgogo",       "Mouse Shooter GoGo"},
        {"msgunda1",     "Mobile Suit Gundam (Japan)"},
        {"msgundam",     "Mobile Suit Gundam"},
        {"msgundam1",    "Mobile Suit Gundam (Japan)"},
        {"msgundamb",    "Mobile Suit Gundam (bootleg)"},
        {"msh",          "Marvel Super Heroes (Euro 951024)"},
        {"msha",         "Marvel Super Heroes (Asia 951024)"},
        {"mshb",         "Marvel Super Heroes (Brazil 951117)"},
        {"mshbr1",       "Marvel Super Heroes (Brazil 951024)"},
        {"msheartb",     "Ms. Pac-Man Heart Burn"},
        {"mshh",         "Marvel Super Heroes (Hispanic 951117)"},
        {"mshj",         "Marvel Super Heroes (Japan 951117)"},
        {"mshjr1",       "Marvel Super Heroes (Japan 951024)"},
        {"mshu",         "Marvel Super Heroes (USA 951024)"},
        {"mshud",        "Marvel Super Heroes (USA 951024 Phoenix Edition) (bootleg)"},
        {"mshuttle",     "Moon Shuttle (US[Q])"},
        {"mshuttle2",    "Moon Shuttle (US? set 2)"},
        {"mshuttlea",    "Moon Shuttle (US, version A)"},
        {"mshuttlej",    "Moon Shuttle (Japan set 1)"},
        {"mshuttlej2",   "Moon Shuttle (Japan set 2)"},
        {"mshuttlj",     "Moon Shuttle (Japan)"},
        {"mshvsf",       "Marvel Super Heroes Vs. Street Fighter (Euro 970625)"},
        {"mshvsfa",      "Marvel Super Heroes Vs. Street Fighter (Asia 970625)"},
        {"mshvsfa1",     "Marvel Super Heroes Vs. Street Fighter (Asia 970620)"},
        {"mshvsfb",      "Marvel Super Heroes Vs. Street Fighter (Brazil 970827)"},
        {"mshvsfb1",     "Marvel Super Heroes Vs. Street Fighter (Brazil 970625)"},
        {"mshvsfh",      "Marvel Super Heroes Vs. Street Fighter (Hispanic 970625)"},
        {"mshvsfj",      "Marvel Super Heroes Vs. Street Fighter (Japan 970707)"},
        {"mshvsfj1",     "Marvel Super Heroes Vs. Street Fighter (Japan 970702)"},
        {"mshvsfj2",     "Marvel Super Heroes Vs. Street Fighter (Japan 970625)"},
        {"mshvsfu",      "Marvel Super Heroes Vs. Street Fighter (USA 970827)"},
        {"mshvsfu1",     "Marvel Super Heroes Vs. Street Fighter (USA 970625)"},
        {"mshvsfu1d",    "Marvel Super Heroes Vs. Street Fighter (USA 970625 Phoenix Edition) (bootleg)"},
        {"msisaac",      "Metal Soldier Isaac II"},
        {"msjiken",      "Mahjong Satsujin Jiken (Japan 881017)"},
        {"mslider",      "Monster Slider (Japan)"},
        {"mslug",        "Metal Slug - Super Vehicle-001"},
        {"mslug2",       "Metal Slug 2 - Super Vehicle-001-II"},
        {"mslug2t",      "Metal Slug 2 - Turbo (Trap15, Hack)"},
        {"mslug3",       "Metal Slug 3"},
        {"mslug3a",      "Metal Slug 3 (NGM-2560, earlier)"},
        {"mslug3b6",     "Metal Slug 6 (bootleg of Metal Slug 3)"},
        {"mslug3h",      "Metal Slug 3 (NGH-2560)"},
        {"mslug3n",      "Metal Slug 3 (not encrypted)"},
        {"mslug4",       "Metal Slug 4"},
        {"mslug4h",      "Metal Slug 4 (NGH-2630)"},
        {"mslug5",       "Metal Slug 5"},
        {"mslug5b",      "Metal Slug 5 (bootleg)"},
        {"mslug5h",      "Metal Slug 5 (NGH-2680)"},
        {"mslug6",       "Metal Slug 6"},
        {"mslugx",       "Metal Slug X - Super Vehicle-001"},
        {"mspacii",      "Ms. Pac-Man II (Orca bootleg set 1)"},
        {"mspacii2",     "Ms. Pac-Man II (Orca bootleg set 2)"},
        {"mspackpls",    "Miss Packman Plus"},
        {"mspacmab",     "Ms. Pac-Man (bootleg)"},
        {"mspacmab2",    "Ms. Pac-Man (bootleg, set 2)"},
        {"mspacmab3",    "Ms. Pac-Man (bootleg, set 3)"},
        {"mspacmab4",    "Ms. Pac-Man (bootleg, set 4)"},
        {"mspacman",     "Ms. Pac-Man"},
        {"mspacmanbcc",  "Come-Cocos (Ms. Pac-Man) ('Made in Greece' Tecnausa bootleg)"},
        {"mspacmanbco",  "Come-Cocos (Ms. Pac-Man) (Cocamatic bootleg)"},
        {"mspacmanbg",   "Ms. Pac-Man ('Made in Greece' bootleg, set 1)"},
        {"mspacmanbg2",  "Ms. Pac-Man ('Made in Greece' bootleg, set 2)"},
        {"mspacmanbgc",  "Ms. Pac-Man ('Made in Greece' Enavi bootleg)"},
        {"mspacmanbgd",  "Miss Pukman ('Made in Greece' Datamat bootleg)"},
        {"mspacmanbgf",  "Mr Pac-Turbo ('Made in Greece' Fermin bootleg)"},
        {"mspacmanbhe",  "Come-Cocos (Ms. Pac-Man) ('Made in Greece' Herle SA bootleg)"},
        {"mspacmanbi",   "Ms. Pac-Man (Impeuropex bootleg)"},
        {"mspacmanblt",  "Come-Cocos (Ms. Pac-Man) ('Made in Greece' Triunvi bootleg, set 1)"},
        {"mspacmanblt2", "Come-Cocos (Ms. Pac-Man) ('Made in Greece' Triunvi bootleg, set 2)"},
        {"mspacmancr",   "Ms. Pac-Man (bootleg on Crush Roller Hardware)"},
        {"mspacmane",    "Ms. Pac-Man (Elmac bootleg, earlier)"},
        {"mspacmane2",   "Ms. Pac-Man (Elmac bootleg, later)"},
        {"mspacmanhnc",  "Super Ms. Pac-Man (turbo hack, NVC284/NVC285 hardware)"},
        {"mspacmanlai",  "Ms. Pac-Man (Leisure and Allied bootleg)"},
        {"mspacmat",     "Ms. Pac Attack"},
        {"mspacmbe",     "Ms. Pac-Man (bootleg, encrypted)"},
        {"mspacmbmc",    "Ms. Pac-Man (Marti Colls bootleg)"},
        {"mspacmbn",     "Ms. Pac-Man (Novatronic bootleg)"},
        {"mspacmnf",     "Ms. Pac-Man (speedup hack)"},
        {"mspacpls",     "Ms. Pac-Man Plus"},
        {"mspactwin",    "Ms. Pac-Man Twin (Argentina)"},
        {"mspactwina",   "Ms Pac Man Twin (Argentina, set 2)"},
        {"mspuzzle",     "Miss Puzzle"},
        {"mspuzzlea",    "Miss Puzzle (Nudes, less explicit)"},
        {"mspuzzleb",    "Miss Puzzle (Nudes, more explicit)"},
        {"mspuzzleg",    "Miss Puzzle (Clone of Gumbo)"},
        {"mstadium",     "Main Stadium (Japan)"},
        {"mstworld",     "Monsters World (bootleg of Super Pang)"},
        {"mstworld2",    "Monsters World 2 (bootleg of Super Pang)"},
        {"msword",       "Magic Sword - Heroic Fantasy (World 900725)"},
        {"mswordj",      "Magic Sword (Japan 900623)"},
        {"mswordr1",     "Magic Sword - Heroic Fantasy (World 900623)"},
        {"mswordu",      "Magic Sword - Heroic Fantasy (US 900725)"},
        {"mt_aftrb",     "MegaTech - Afterburner"},
        {"mt_astro",     "MegaTech - Astro Warrior"},
        {"mt_bbros",     "MegaTech - Bonanza Bros."},
        {"mt_beast",     "MegaTech - Altered Beast"},
        {"mt_eswat",     "MegaTech - E-Swat"},
        {"mt_fshrk",     "MegaTech - Fire Shark"},
        {"mt_gaxe",      "MegaTech - Golden Axe"},
        {"mt_gaxe2",     "MegaTech - Golden Axe 2"},
        {"mt_ggolf",     "MegaTech - Great Golf"},
        {"mt_gng",       "MegaTech - Ghouls and Ghosts"},
        {"mt_gsocr",     "MegaTech - Great Soccer"},
        {"mt_kcham",     "MegaTech - Kid Chameleon"},
        {"mt_lastb",     "MegaTech - Last Battle."},
        {"mt_mwalk",     "MegaTech - Moonwalker"},
        {"mt_mystd",     "MegaTech - Mystic Defender"},
        {"mt_parlg",     "MegaTech - Parlour Games"},
        {"mt_revsh",     "MegaTech - The Revenge Of Shinobi"},
        {"mt_shar2",     "MegaTech - Space Harrier 2."},
        {"mt_shnbi",     "MegaTech - Shinobi"},
        {"mt_smgp",      "MegaTech - Super Monaco Grand Prix"},
        {"mt_sonic",     "MegaTech - Sonic the Hedgehog"},
        {"mt_stbld",     "MegaTech - Super Thunder Blade"},
        {"mt_tetri",     "MegaTech - Tetris"},
        {"mt_tfor2",     "MegaTech - Thunder Force 2"},
        {"mt_tgolf",     "MegaTech - Arnold Palmer Tournament Golf"},
        {"mt_tlbba",     "MegaTech - Tommy Lasorda Baseball"},
        {"mt_wcsoc",     "MegaTech - World Cup Soccer"},
        {"mtkob2",       "Mushiking The King Of Beetle (2K3 2ND, World)"},
        {"mtlchamp",     "Martial Champion (Europe ver EAA)"},
        {"mtlchamp1",    "Martial Champion (ver EAA)"},
        {"mtlchampa",    "Martial Champion (ver AAA)"},
        {"mtlchampj",    "Martial Champion (ver JAA)"},
        {"mtlchampu",    "Martial Champion (ver UAE)"},
        {"mtlchampu1",   "Martial Champion (ver UAD)"},
        {"mtlchmpj",     "Martial Champion (Japan ver JAA)"},
        {"mtrap",        "Mouse Trap (version 5)"},
        {"mtrap2",       "Mouse Trap (version 2)"},
        {"mtrap3",       "Mouse Trap (version 3)"},
        {"mtrap4",       "Mouse Trap (version 4)"},
        {"mtrap4g",      "Mouse Trap (German, version 4)"},
        {"mtrapb",       "Mouse Trap (bootleg)"},
        {"mtrapb2",      "Mouse Trap (version 4, bootleg)"},
        {"mtwins",       "Mega Twins (World 900619)"},
        {"mtwinsb",      "Twins (bootleg of Mega Twins)"},
        {"mugsmash",     "Mug Smashers"},
        {"multchmp",     "Multi Champ (World, ver. 2.5)"},
        {"multchmpa",    "Multi Champ (World, older)"},
        {"multchmpk",    "Multi Champ (Korea)"},
        {"multi96",      "Multi Game '96 (Italy)"},
        {"multigam",     "Multi Game (set 1)"},
        {"multigm2",     "Multi Game 2"},
        {"multigm3",     "Multi Game III"},
        {"multigmb",     "Multi Game (set 2)"},
        {"multigmt",     "Multi Game (Tung Sheng Electronics)"},
        {"multiped",     "Multipede (Centipede/Millipede multigame kit)"},
        {"musclem",      "Muscle Master"},
        {"musclhit",     "Muscle Ranking Kinniku Banzuke Spray Hitter"},
        {"mushi2eo",     "Mushiking The King Of Beetles - Mushiking II / III / III+ (Ver. 1.001) (World)"},
        {"mushi2k4",     "Mushiking The King Of Beetles 2004 Second (Japan)"},
        {"mushi2k5",     "Mushiking The King Of Beetles 2005 First (Japan)"},
        {"mushi2k61",    "Mushiking The King Of Beetles 2006 First (Japan)"},
        {"mushi2k62",    "Mushiking The King Of Beetles 2006 Second (Japan)"},
        {"mushik2e",     "Mushiking The King Of Beetles - Mushiking II / III / III+ (Ver. 2.001) (World)"},
        {"mushik2k",     "Mushiking The King Of Beetles - Mushiking II / III / III+ (Ver. 1.000-) (Korea)"},
        {"mushik4e",     "Mushiking The King Of Beetles - Mushiking IV / V / VI (World)"},
        {"mushikc",      "Mushiking The King Of Beetle (2K3 2ND Ver. 1.000-, China)"},
        {"mushike",      "Mushiking The King Of Beetle (2K3 2ND Ver. 1.003-, World)"},
        {"mushikeo",     "Mushiking The King Of Beetle (2K3 2ND Ver. 1.002-, World)"},
        {"mushikep",     "Mushiking The King Of Beetle (MUSHIUSA '04 1ST, Prototype)"},
        {"mushikk",      "Mushiking The King Of Beetle (2K3 2ND Ver. 1.000-, Korea)"},
        {"mushisam",     "Mushihime-Sama (2004/10/12.MASTER VER.)"},
        {"mushisama",    "Mushihime-Sama (2004/10/12 MASTER VER.)"},
        {"mushisamb",    "Mushihime-Sama (2004/10/12 MASTER VER)"},
        {"mushitam",     "Puzzle! Mushihime-Tama (2005/09/09.MASTER VER)"},
        {"mushitama",    "Puzzle! Mushihime-Tama (2005/09/09 MASTER VER)"},
        {"musicbal",     "Music Ball"},
        {"mustache",     "Mustache Boy"},
        {"mustachei",    "Mustache Boy (Italy)"},
        {"mustang",      "US AAF Mustang (Japan)"},
        {"mustangb",     "US AAF Mustang (Bootleg)"},
        {"mustangb2",    "US AAF Mustang (TAB Austria bootleg)"},
        {"mustangb3",    "US AAF Mustang (Lettering bootleg)"},
        {"mustangs",     "US AAF Mustang (Seoul Trading)"},
        {"mutantf",      "Mutant Fighter (World Rev 4, EM-5)"},
        {"mutantf1",     "Heroes (World ver EM-1)"},
        {"mutantf2",     "Mutant Fighter (World ver EM-2)"},
        {"mutantf3",     "Mutant Fighter (World ver EM-3)"},
        {"mutantf4",     "Mutant Fighter (World ver EM-4)"},
        {"mutantfa",     "Mutant Fighter (World Rev 3, EM-4)"},
        {"mutnat",       "Mutation Nation"},
        {"mvp",          "MVP"},
        {"mvpd",         "MVP (set 2, US) (bootleg of FD1094 317-0143 set)"},
        {"mvpj",         "MVP (set 1, Japan) (FD1094 317-0142)"},
        {"mvpjd",        "MVP (set 1, Japan) (bootleg of FD1094 317-0142 set)"},
        {"mvsc",         "Marvel Vs. Capcom: Clash of Super Heroes (Euro 980123)"},
        {"mvsc2",        "Marvel Vs. Capcom 2: New Age of Heroes (Export, Korea, Rev A)"},
        {"mvsc2u",       "Marvel Vs. Capcom 2: New Age of Heroes (USA, Rev A)"},
        {"mvsca",        "Marvel Vs. Capcom: Clash of Super Heroes (Asia 980123)"},
        {"mvscar1",      "Marvel Vs. Capcom: Clash of Super Heroes (Asia 980112)"},
        {"mvscb",        "Marvel Vs. Capcom: Clash of Super Heroes (Brazil 980123)"},
        {"mvsch",        "Marvel Vs. Capcom: Clash of Super Heroes (Hispanic 980123)"},
        {"mvscj",        "Marvel Vs. Capcom: Clash of Super Heroes (Japan 980123)"},
        {"mvscjr1",      "Marvel Vs. Capcom: Clash of Super Heroes (Japan 980112)"},
        {"mvscjsing",    "Marvel Vs. Capcom: Clash of Super Heroes (Japan 980123) (Single PCB)"},
        {"mvscr1",       "Marvel Vs. Capcom: Clash of Super Heroes (Euro 980112)"},
        {"mvscu",        "Marvel Vs. Capcom: Clash of Super Heroes (USA 980123)"},
        {"mvscud",       "Marvel Vs. Capcom: Clash of Super Heroes (USA 980123 Phoenix Edition) (bootleg)"},
        {"mvscur1",      "Marvel Vs. Capcom: Clash of Super Heroes (USA 971222)"},
        {"mwalk",        "Michael Jackson's Moonwalker (World) (FD1094/8751 317-0159)"},
        {"mwalkbl",      "Michael Jackson's Moonwalker (bootleg)"},
        {"mwalkd",       "Michael Jackson's Moonwalker (World) (bootleg of FD1094/8751 317-0159 set)"},
        {"mwalkj",       "Michael Jackson's Moonwalker (Japan) (FD1094/8751 317-0157)"},
        {"mwalkjd",      "Michael Jackson's Moonwalker (Japan) (bootleg of FD1094/8751 317-0157 set)"},
        {"mwalku",       "Michael Jackson's Moonwalker (US) (FD1094/8751 317-0158)"},
        {"mwalkud",      "Michael Jackson's Moonwalker (US) (bootleg of FD1094/8751 317-0158 set)"},
        {"mwarr",        "Mighty Warriors"},
        {"mx5000",       "MX5000"},
        {"myangel",      "Kosodate Quiz My Angel (Japan)"},
        {"myangel2",     "Kosodate Quiz My Angel 2 (Japan)"},
        {"myangel3",     "Kosodate Quiz My Angel 3 (KQT1-VER.A)"},
        {"myfairld",     "Virtual Mahjong 2 - My Fair Lady"},
        {"myhero",       "My Hero (US)"},
        {"myherobl",     "My Hero (bootleg, 315-5132 encryption)"},
        {"myherok",      "My Hero (Korea)"},
        {"myqbert",      "Mello Yello Q*bert"},
        {"mysticm",      "Mystic Marathon"},
        {"mysticri",     "Mystic Riders (World)"},
        {"mysticrib",    "Mystic Riders (bootleg?)"},
        {"myststno",     "Mysterious Stones - Dr. Kick in Adventure"},
        {"mystston",     "Mysterious Stones - Dr. John's Adventure"},
        {"myststono",    "Mysterious Stones - Dr. Kick in Adventure"},
        {"myststonoi",   "Mysterious Stones - Dr. Kick in Adventure (Itisa PCB)"},
        {"mystwarr",     "Mystic Warriors (Europe ver EAA)"},
        {"mystwarra",    "Mystic Warriors (ver AAB)"},
        {"mystwarraa",   "Mystic Warriors (ver AAA)"},
        {"mystwarrj",    "Mystic Warriors (ver JAA)"},
        {"mystwarru",    "Mystic Warriors (ver UAA)"},
        {"mystwaru",     "Mystic Warriors (US ver UAA)"},
};

const char *lookup_m(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_m(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
