#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"a51mxr3k",     "Area 51 - Maximum Force Duo (R3000)"},
        {"a51mxr3ka",    "Area 51 / Maximum Force Duo (R3000, 2/02/98)"},
        {"aafb",         "All American Football (rev E)"},
        {"aafbb",        "All American Football (rev B)"},
        {"aafbc",        "All American Football (rev C)"},
        {"aafbd2p",      "All American Football (rev D, 2 Players)"},
        {"abaseb",       "Atari Baseball (set 1)"},
        {"abaseb2",      "Atari Baseball (set 2)"},
        {"abcop",        "A.B. Cop (World) (FD1094 317-0169b)"},
        {"abcopd",       "A.B. Cop (World) (bootleg of FD1094 317-0169b set)"},
        {"abcopj",       "A.B. Cop (Japan) (FD1094 317-0169b)"},
        {"abcopjd",      "A.B. Cop (Japan) (bootleg of FD1094 317-0169b set)"},
        {"ablast",       "Hong Tian Lei (A-Blast) (Japan)"},
        {"abscam",       "Abscam"},
        {"aburner",      "After Burner (Japan)"},
        {"aburner2",     "After Burner II"},
        {"aburner2g",    "After Burner II (German)"},
        {"acchi",        "Janken Game Acchi Muite Hoi! (Japan 1.3)"},
        {"ace",          "Ace"},
        {"aceattac",     "Ace Attacker"},
        {"aceattaca",    "Ace Attacker (Japan, System 16A, FD1094 317-0060)"},
        {"acedrive",     "Ace Driver: Racing Evolution (World, AD2)"},
        {"acedrvrw",     "Ace Driver (Rev. AD2, World)"},
        {"acitya",       "Atlantic City Action"},
        {"acpsx",        "Acclaim PSX"},
        {"acrobatm",     "Acrobat Mission"},
        {"acrobatmbl",   "Acrobat Mission (bootleg with Raiden sounds)"},
        {"actfanc1",     "Act-Fancer Cybernetick Hyper Weapon (World revision 1)"},
        {"actfancj",     "Act-Fancer Cybernetick Hyper Weapon (Japan revision 1)"},
        {"actfancr",     "Act-Fancer Cybernetick Hyper Weapon (World revision 2)"},
        {"actfancr1",    "Act-Fancer Cybernetick Hyper Weapon (World revision 1)"},
        {"actfancr2",    "Act-Fancer Cybernetick Hyper Weapon (World revision 2)"},
        {"actfancrj",    "Act-Fancer Cybernetick Hyper Weapon (Japan revision 1)"},
        {"actionhw",     "Action Hollywood"},
        {"ad2083",       "A. D. 2083"},
        {"adillor",      "Armadillo Racing (World, AM2 Ver.A)"},
        {"adillorj",     "Armadillo Racing (Japan, AM1 Ver.A)"},
        {"aerfboo2",     "Aero Fighters (bootleg, set 2)"},
        {"aerfboot",     "Aero Fighters (bootleg, set 1)"},
        {"aeroboto",     "Aeroboto"},
        {"aerofgt",      "Aero Fighters"},
        {"aerofgtb",     "Aero Fighters (Turbo Force hardware set 1)"},
        {"aerofgtc",     "Aero Fighters (Turbo Force hardware set 2)"},
        {"aerolitol",    "Aerolitos Espaciales (Spanish bootleg of Asteroids)"},
        {"aerolitos",    "Aerolitos (Spanish bootleg of Asteroids)"},
        {"afighter",     "Action Fighter (FD1089A 317-0018)"},
        {"afightera",    "Action Fighter (unprotected)"},
        {"afighterb",    "Action Fighter (unprotected, analog controls)"},
        {"afighterc",    "Action Fighter (FD1089B 317-unknown)"},
        {"afighterd",    "Action Fighter (FD1089B 317-unknown, analog controls)"},
        {"afightere",    "Action Fighter (System 16B, unprotected, analog controls)"},
        {"afighterf",    "Action Fighter (System 16B, FD1089B 317-unknown, analog controls)"},
        {"afighterg",    "Action Fighter (System 16B, FD1089B 317-unknown)"},
        {"afighterh",    "Action Fighter (System 16B, FD1089A 317-0018)"},
        {"agallet",      "Air Gallet"},
        {"agalleta",     "Air Gallet (older, Europe)"},
        {"agalletah",    "Air Gallet (older, Hong Kong)"},
        {"agalletaj",    "Akuu Gallet (older, Japan)"},
        {"agalletak",    "Air Gallet (older, Korea)"},
        {"agalletat",    "Air Gallet (older, Taiwan)"},
        {"agalletau",    "Air Gallet (older, USA)"},
        {"agalleth",     "Air Gallet (Hong Kong)"},
        {"agalletj",     "Akuu Gallet (Japan)"},
        {"agalletk",     "Air Gallet (Korea)"},
        {"agallett",     "Air Gallet (Taiwan)"},
        {"agalletu",     "Air Gallet (USA)"},
        {"agentx1",      "Agent X (prototype, rev 1)"},
        {"agentx2",      "Agent X (prototype, rev 2)"},
        {"agentx3",      "Agent X (prototype, rev 3)"},
        {"agentx4",      "Agent X (prototype, rev 4)"},
        {"agress",       "Agress - Missile Daisenryaku (Japan)"},
        {"agressb",      "Agress - Missile Daisenryaku (English bootleg)"},
        {"ainferno",     "Air Inferno (US)"},
        {"airass",       "Air Assault (World)"},
        {"airattck",     "Air Attack (set 1)"},
        {"airattcka",    "Air Attack (set 2)"},
        {"airbustj",     "Air Buster (Japan)"},
        {"airbustr",     "Air Buster"},
        {"airbustrb",    "Air Buster: Trouble Specialty Raid Unit (bootleg)"},
        {"airbustrj",    "Air Buster: Trouble Specialty Raid Unit (Japan)"},
        {"airco22b",     "Air Combat 22 (Rev. ACS1 Ver.B)"},
        {"aircombj",     "Air Combat (Japan)"},
        {"aircombu",     "Air Combat (US)"},
        {"airduel",      "Air Duel (Japan)"},
        {"airdueljm72",  "Air Duel (Japan, M72 hardware)"},
        {"airduelm72",   "Air Duel (World, M72 hardware)"},
        {"airduelu",     "Air Duel (US location test, M82 hardware)"},
        {"airrace",      "Air Race (prototype)"},
        {"airraid",      "Air Raid (encrypted)"},
        {"airwlkrs",     "Air Walkers"},
        {"airwolf",      "Airwolf"},
        {"airwolfa",     "Airwolf (US)"},
        {"ajax",         "Ajax"},
        {"ajaxj",        "Ajax (Japan)"},
        {"akamaru",      "Panel & Variety Akamaru Q Joushou Dont-R"},
        {"akazukin",     "Akazukin (Japan)"},
        {"akiss",        "Mahjong Angel Kiss"},
        {"akkaarrh",     "Akka Arrh (prototype)"},
        {"akkanvdr",     "Akkanvader (Japan)"},
        {"akumajou",     "Akuma-Jou Dracula (Japan version P)"},
        {"akumajoun",    "Akuma-Jou Dracula (Japan version N)"},
        {"aladmdb",      "Aladdin (bootleg of Japanese Megadrive version)"},
        {"alcon",        "Alcon"},
        {"alexkidd",     "Alex Kidd: The Lost Stars (set 2, unprotected)"},
        {"alexkidd1",    "Alex Kidd: The Lost Stars (set 1, FD1089A 317-0021)"},
        {"alibaba",      "Ali Baba and 40 Thieves"},
        {"alibabab",     "Mustafa and 40 Thieves (bootleg)"},
        {"alien3",       "Alien3: The Gun"},
        {"alien3j",      "Alien3: The Gun (Japan)"},
        {"alien3u",      "Alien3: The Gun (US, Rev A)"},
        {"alienar",      "Alien Arena"},
        {"alienaru",     "Alien Arena (Stargate upgrade)"},
        {"aliencha",     "Alien Challenge (World)"},
        {"alienchac",    "Alien Challenge (China)"},
        {"aliencr",      "Alien Crush (United Amusements PC Engine)"},
        {"alienfnt",     "Alien Front (Rev T)"},
        {"alienfnta",    "Alien Front (Rev A)"},
        {"alieninv",     "Alien Invasion Part II"},
        {"alieninvp2",   "Alien Invasion Part II"},
        {"aliens",       "Aliens (World set 1)"},
        {"aliens2",      "Aliens (World set 2)"},
        {"aliens3",      "Aliens (World set 3)"},
        {"aliens4",      "Aliens (World set 4)"},
        {"aliensa",      "Aliens (Asia)"},
        {"aliensec",     "Alien Sector"},
        {"aliensj",      "Aliens (Japan)"},
        {"aliensj2",     "Aliens (Japan set 2)"},
        {"aliensu",      "Aliens (US)"},
        {"aliensya",     "Alien Syndrome (set 2)"},
        {"aliensyb",     "Alien Syndrome (set 3)"},
        {"aliensyj",     "Alien Syndrome (Japan)"},
        {"aliensyn",     "Alien Syndrome (set 1)"},
        {"aliensyn2",    "Alien Syndrome (set 2, System 16A, FD1089A 317-0033)"},
        {"aliensyn3",    "Alien Syndrome (set 3, System 16B, FD1089A 317-0033)"},
        {"aliensyn5",    "Alien Syndrome (set 5, System 16A, FD1089B 317-0037)"},
        {"aliensyn7",    "Alien Syndrome (set 7, System 16B, MC-8123B 317-00xx)"},
        {"aliensynj",    "Alien Syndrome (set 6, Japan, new, System 16B, FD1089A 317-0033)"},
        {"aliensynjo",   "Alien Syndrome (set 1, Japan, old, System 16A, FD1089A 317-0033)"},
        {"aligator",     "Alligator Hunt"},
        {"aligators",    "Alligator Hunt (Spain, protected)"},
        {"aligatorun",   "Alligator Hunt (unprotected, set 1)"},
        {"aligatoruna",  "Alligator Hunt (unprotected, set 2)"},
        {"aligatun",     "Alligator Hunt (unprotected)"},
        {"alleymas",     "Alley Master"},
        {"alpha1v",      "Alpha One (Vision Electronics)"},
        {"alphaho",      "Alpha Fighter - Head On"},
        {"alpham2",      "Alpha Mission II / ASO II - Last Guardian"},
        {"alpham2p",     "Alpha Mission II Proto"},
        {"alphamis",     "Alpha Mission"},
        {"alphaona",     "Alpha One (prototype, 5 lives)"},
        {"alphaone",     "Alpha One (prototype, 3 lives)"},
        {"alphaonea",    "Alpha One (prototype, 5 lives)"},
        {"alphaxz",      "The Alphax Z (Japan)"},
        {"alpilot",      "Airline Pilots (World, Rev B)"},
        {"alpilota",     "Airline Pilots (Rev A)"},
        {"alpilotj",     "Airline Pilots (Japan, Rev A)"},
        {"alpiltdx",     "Airline Pilots (deluxe) (Rev B)"},
        {"alpine",       "Alpine Ski (set 1)"},
        {"alpinea",      "Alpine Ski (set 2)"},
        {"alpinerc",     "Alpine Racer (Rev. AR2 Ver.C)"},
        {"alpinerd",     "Alpine Racer (Rev. AR2 Ver.D)"},
        {"alpinerjc",    "Alpine Racer (Japan, AR1 Ver.C)"},
        {"alpines",      "Alpine Surfer (World, AF2 Ver.A, set 1)"},
        {"alpinesa",     "Alpine Surfer (World, AF2 Ver.A, set 2)"},
        {"alpinr2a",     "Alpine Racer 2 (World, ARS2 Ver.A)"},
        {"alpinr2b",     "Alpine Racer 2 (World, ARS2 Ver.B)"},
        {"altair",       "Altair"},
        {"altair2",      "Altair II"},
        {"altbeas2",     "Altered Beast (Version 2)"},
        {"altbeast",     "Altered Beast (Version 1)"},
        {"altbeast2",    "Altered Beast (set 2) (MC-8123B 317-0066)"},
        {"altbeast4",    "Altered Beast (set 4) (MC-8123B 317-0066)"},
        {"altbeast5",    "Altered Beast (set 5) (FD1094 317-0069)"},
        {"altbeast5d",   "Altered Beast (set 5) (bootleg of FD1094 317-0069 set)"},
        {"altbeast6",    "Altered Beast (set 6) (8751 317-0076)"},
        {"altbeastj",    "Juuouki (set 7, Japan) (8751 317-0077)"},
        {"altbeastj1",   "Juuouki (set 1, Japan) (FD1094 317-0065)"},
        {"altbeastj3",   "Juuouki (set 3, Japan) (FD1094 317-0068)"},
        {"altbeastj3d",  "Juuouki (set 3, Japan) (bootleg of FD1094 317-0068 set)"},
        {"amatelas",     "Sei Senshi Amatelass"},
        {"amazon",       "Soldier Girl Amazon"},
        {"amazont",      "Soldier Girl Amazon (Tecfri license)"},
        {"ambush",       "Ambush"},
        {"ambushh",      "Ambush (hack?)"},
        {"ambushj",      "Ambush (Japan)"},
        {"ambusht",      "Ambush (Tecfri)"},
        {"ambushv",      "Ambush (Volt Electronics)"},
        {"amerdart",     "AmeriDarts"},
        {"amerdart2",    "AmeriDarts (set 2)"},
        {"amerdart3",    "AmeriDarts (set 3)"},
        {"amerug",       "Amerug (Shoei bootleg of Atari Football)"},
        {"amidar",       "Amidar"},
        {"amidar1",      "Amidar (older)"},
        {"amidarb",      "Amidar (bootleg, set 1)"},
        {"amidarb2",     "Amidar (bootleg, set 2)"},
        {"amidaro",      "Amidar (Olympia)"},
        {"amidars",      "Amidar (Scramble hardware)"},
        {"amidaru",      "Amidar (Stern)"},
        {"amigo",        "Amigo"},
        {"amigo2",       "Amigo (bootleg of Amidar, set 2)"},
        {"amspdwy",      "American Speedway (set 1)"},
        {"amspdwya",     "American Speedway (set 2)"},
        {"androdun",     "Andro Dunos"},
        {"androidp",     "Android (prototype, later build)"},
        {"androidpo",    "Android (prototype, early build)"},
        {"andromed",     "Andromeda (Japan[Q])"},
        {"angelkds",     "Angel Kids (Japan)"},
        {"animaljr",     "Exciting Animal Land Jr. (USA, Canada, Mexico)"},
        {"animaljrj",    "Waiwai Animal Land Jr. (Japan)"},
        {"animaljrs",    "Animalandia Jr. (Spanish)"},
        {"anmlbskt",     "Animal Basket / Hustle Tamaire Kyousou (24 Jan 2005)"},
        {"anmlbskta",    "Animal Basket / Hustle Tamaire Kyousou (19 Jan 2005)"},
        {"anteater",     "Anteater"},
        {"anteaterg",    "Ameisenbaer (German)"},
        {"anteatergg",   "Ameisenbaer (German bootleg on Galaxian hardware)"},
        {"anteateruk",   "The Anteater (UK)"},
        {"aodk",         "Aggressors of Dark Kombat / Tsuukai GANGAN Koushinkyoku"},
        {"aof",          "Art of Fighting / Ryuuko no Ken"},
        {"aof2",         "Art of Fighting 2 / Ryuuko no Ken 2"},
        {"aof2a",        "Art of Fighting 2 (NGH-056)"},
        {"aof3",         "Art of Fighting 3 - The Path of the Warrior / Art of Fighting - Ryuuko no Ken Gaiden"},
        {"aof3k",        "Art of Fighting 3 - The Path of the Warrior (Korean release)"},
        {"aoh",          "Age Of Heroes - Silkroad 2 (v0.63 - 2001/02/07)"},
        {"apb",          "APB - All Points Bulletin (rev 7)"},
        {"apb1",         "APB - All Points Bulletin (rev 1)"},
        {"apb2",         "APB - All Points Bulletin (rev 2)"},
        {"apb3",         "APB - All Points Bulletin (rev 3)"},
        {"apb4",         "APB - All Points Bulletin (rev 4)"},
        {"apb5",         "APB - All Points Bulletin (rev 5)"},
        {"apb6",         "APB - All Points Bulletin (rev 6)"},
        {"apbf",         "APB - All Points Bulletin (French)"},
        {"apbg",         "APB - All Points Bulletin (German)"},
        {"aplarail",     "Attack Pla Rail (Japan, AP1/VER.A)"},
        {"aponow",       "Apocaljpse Now"},
        {"apparel",      "Apparel Night (Japan 860929)"},
        {"appoooh",      "Appoooh"},
        {"aquajack",     "Aqua Jack (World)"},
        {"aquajackj",    "Aqua Jack (Japan)"},
        {"aquajacku",    "Aqua Jack (US)"},
        {"aquajckj",     "Aqua Jack (Japan)"},
        {"aquajet",      "Aqua Jet (World, AJ2 Ver.B)"},
        {"aquario",      "Clockwork Aquario (prototype)"},
        {"aquarium",     "Aquarium (Japan)"},
        {"aquariumj",    "Aquarium (Japan)"},
        {"aquarush",     "Aqua Rush (AQ1-VER.A)"},
        {"ar_airh",      "SportTime Table Hockey (Arcadia, set 1, V 2.1)"},
        {"ar_airh2",     "SportTime Table Hockey (Arcadia, set 2)"},
        {"ar_argh",      "Aaargh (Arcadia)"},
        {"ar_blast",     "Blastaball (Arcadia, V 2.1)"},
        {"ar_bowl",      "SportTime Bowling (Arcadia, V 2.1)"},
        {"ar_dart",      "World Darts (Arcadia, set 1, V 2.1)"},
        {"ar_dlta",      "Delta Command (Arcadia)"},
        {"ar_fast",      "Magic Johnson's Fast Break (Arcadia, V 2.8)"},
        {"ar_fasta",     "Magic Johnson's Fast Break (Arcadia, V 2.7)"},
        {"ar_ldrb",      "Leader Board Golf (Arcadia, set 1, V 2.5)"},
        {"ar_ldrba",     "Leader Board Golf (Arcadia, set 2, V 2.4)"},
        {"ar_ldrbb",     "Leader Board Golf (Arcadia, set 3)"},
        {"ar_ninj",      "Ninja Mission (Arcadia, set 1, V 2.5)"},
        {"ar_ninj2",     "Ninja Mission (Arcadia, set 2)"},
        {"ar_pm",        "Pharaohs Match (Arcadia)"},
        {"ar_rdwr",      "RoadWars (Arcadia, V 2.3)"},
        {"ar_sdwr",      "Sidewinder (Arcadia, set 1, V 2.1)"},
        {"ar_sdwr2",     "Sidewinder (Arcadia, set 2)"},
        {"ar_socc",      "World Trophy Soccer (Arcadia, V 3.0)"},
        {"ar_sprg",      "Space Ranger (Arcadia, V 2.0)"},
        {"ar_xeon",      "Xenon (Arcadia, V 2.3)"},
        {"arabfgt",      "Arabian Fight"},
        {"arabfgtj",     "Arabian Fight (Japan)"},
        {"arabfgtu",     "Arabian Fight (US)"},
        {"arabiamj",     "Arabian Magic (Japan)"},
        {"arabiamu",     "Arabian Magic (US)"},
        {"arabian",      "Arabian"},
        {"arabiana",     "Arabian (Atari)"},
        {"arabianm",     "Arabian Magic (World)"},
        {"arabianmj",    "Arabian Magic (Ver 1.0J 1992/07/06)"},
        {"arabianmu",    "Arabian Magic (Ver 1.0A 1992/07/06)"},
        {"aracnis",      "Aracnis (bootleg of Scorpion on Moon Cresta hardware, set 1)"},
        {"arbalest",     "Arbalester"},
        {"arcadecl",     "Arcade Classics (prototype)"},
        {"arcadia",      "Waga Seishun no Arcadia"},
        {"arcadian",     "Arcadia (NMK)"},
        {"archriv2",     "Arch Rivals (rev 2.0)"},
        {"archrivl",     "Arch Rivals (rev 4.0)"},
        {"archrivla",    "Arch Rivals (rev 2.0 5/03/89)"},
        {"archrivlb",    "Arch Rivals (rev 2.0 5/03/89, 8-way joystick bootleg)"},
        {"area51",       "Area 51"},
        {"area51a",      "Area 51 (Atari Games license, Oct 25, 1995)"},
        {"area51mx",     "Area 51 - Maximum Force Duo v2.0"},
        {"area51t",      "Area 51 (Time Warner license, Oct 17, 1996)"},
        {"area51ta",     "Area 51 (Time Warner license, Nov 27, 1995)"},
        {"area88",       "Area 88 (Japan)"},
        {"area88r",      "Area 88 (Japan Resale Ver.)"},
        {"arescue",      "Air Rescue"},
        {"arescuej",     "Air Rescue (Japan)"},
        {"arescueu",     "Air Rescue (US)"},
        {"argus",        "Argus"},
        {"argusg",       "Argus (Gottlieb, prototype)"},
        {"arian",        "Arian Mission"},
        {"ark1ball",     "Arkanoid (bootleg with MCU, harder)"},
        {"arkangc",      "Arkanoid (Game Corporation bootleg)"},
        {"arkangc2",     "Arkanoid (Game Corporation bootleg, set 2)"},
        {"arkanoid",     "Arkanoid (World)"},
        {"arkanoidj",    "Arkanoid (Japan, newer)"},
        {"arkanoidja",   "Arkanoid (Japan, newer w/level select)"},
        {"arkanoidjb",   "Arkanoid (Japan, older)"},
        {"arkanoidjbl",  "Arkanoid (bootleg with MCU, set 1)"},
        {"arkanoidjbl2", "Arkanoid (bootleg with MCU, set 2)"},
        {"arkanoidpe",   "Arkanoid (Phoenix Electronics Co. license)"},
        {"arkanoidu",    "Arkanoid (US, newer)"},
        {"arkanoiduo",   "Arkanoid (US, older)"},
        {"arkarea",      "Ark Area"},
        {"arkatayt",     "Arkanoid (Tayto bootleg, Japanese)"},
        {"arkatour",     "Tournament Arkanoid (US)"},
        {"arkbl2",       "Arkanoid (Japanese bootleg Set 2)"},
        {"arkbl3",       "Arkanoid (Japanese bootleg Set 3)"},
        {"arkbloc2",     "Block (Game Corporation bootleg)"},
        {"arkbloc3",     "Block (Game Corporation bootleg, set 3)"},
        {"arkblock",     "Block (bootleg, Japanese)"},
        {"arkgcbl",      "Arkanoid (bootleg on Block hardware, set 1)"},
        {"arkgcbla",     "Arkanoid (bootleg on Block hardware, set 2)"},
        {"arknid2j",     "Arkanoid - Revenge of DOH (Japan)"},
        {"arknid2u",     "Arkanoid - Revenge of DOH (US)"},
        {"arknoid2",     "Arkanoid - Revenge of DOH (World)"},
        {"arknoid2b",    "Arkanoid - Revenge of DOH (Japan bootleg)"},
        {"arknoid2j",    "Arkanoid - Revenge of DOH (Japan)"},
        {"arknoid2u",    "Arkanoid - Revenge of DOH (US)"},
        {"arknoidj",     "Arkanoid (Japan, newer w/level select)"},
        {"arknoidu",     "Arkanoid (US)"},
        {"arknoiuo",     "Arkanoid (US, older)"},
        {"arkretrn",     "Arkanoid Returns (Japan)"},
        {"arkretrnj",    "Arkanoid Returns (Ver 2.02J 1997/02/10)"},
        {"arkretrnu",    "Arkanoid Returns (Ver 2.02A 1997/02/10)"},
        {"arktayt2",     "Arkanoid (Tayto bootleg, harder)"},
        {"arlingtn",     "Arlington Horse Racing (v1.21-D)"},
        {"arlingtna",    "Arlington Horse Racing (v1.21-D)"},
        {"armedf",       "Armed Formation"},
        {"armedff",      "Armed F (Fillmore license)"},
        {"armora",       "Armor Attack"},
        {"armorap",      "Armor Attack (prototype)"},
        {"armorar",      "Armor Attack (Rock-ola)"},
        {"armorca2",     "Armored Car (set 2)"},
        {"armorcar",     "Armored Car (set 1)"},
        {"armorcar2",    "Armored Car (set 2)"},
        {"armwar",       "Armored Warriors (Euro 941024)"},
        {"armwar1d",     "Armored Warriors (Europe 941011 Phoenix Edition) (bootleg)"},
        {"armwara",      "Armored Warriors (Asia 941024)"},
        {"armwarar1",    "Armored Warriors (Asia 940920)"},
        {"armwarb",      "Armored Warriors (Brazil 941024)"},
        {"armwarr1",     "Armored Warriors (Euro 941011)"},
        {"armwaru",      "Armored Warriors (USA 941024)"},
        {"armwaru1",     "Armored Warriors (USA 940920)"},
        {"armwrest",     "Arm Wrestling"},
        {"ashnojoe",     "Ashita no Joe (Japan)"},
        {"ashura",       "Ashura Blaster (Japan)"},
        {"ashuraj",      "Ashura Blaster (Japan)"},
        {"ashurau",      "Ashura Blaster (US)"},
        {"asideral",     "Ataque Sideral (Spanish bootleg of UniWar S)"},
        {"asndynmt",     "Asian Dynamite / Dynamite Deka EX"},
        {"asndynmto",    "Asian Dynamite / Dynamite Deka EX (older)"},
        {"aso",          "ASO - Armored Scrum Object"},
        {"assault",      "Assault"},
        {"assaultj",     "Assault (Japan)"},
        {"assaultp",     "Assault Plus (Japan)"},
        {"astdelu1",     "Asteroids Deluxe (rev 1)"},
        {"astdelux",     "Asteroids Deluxe (rev 2)"},
        {"astdelux1",    "Asteroids Deluxe (rev 1)"},
        {"astdelux2",    "Asteroids Deluxe (rev 2)"},
        {"asterix",      "Asterix (World ver. EAD)"},
        {"asterixaad",   "Asterix (ver AAD)"},
        {"asterixeaa",   "Asterix (ver EAA)"},
        {"asterixeac",   "Asterix (ver EAC)"},
        {"asterixj",     "Asterix (ver JAD)"},
        {"asterock",     "Asterock"},
        {"asterockv",    "Asterock (Videotron bootleg of Asteroids)"},
        {"asteroi1",     "Asteroids (rev 1)"},
        {"asteroib",     "Asteroids (bootleg on Lunar Lander hardware)"},
        {"asteroid",     "Asteroids (rev 2)"},
        {"asteroid1",    "Asteroids (rev 1)"},
        {"asteroid2",    "Asteroids (rev 2)"},
        {"asteroidb1",   "Asteroids (bootleg on Lunar Lander hardware, set 1)"},
        {"asteroidb2",   "Asteroids (bootleg on Lunar Lander hardware, set 2)"},
        {"astinvad",     "Astro Invader"},
        {"astorm",       "Alien Storm"},
        {"astorm2p",     "Alien Storm (2 Player)"},
        {"astorm3",      "Alien Storm (World, 3 Players) (FD1094 317-0148)"},
        {"astorm3d",     "Alien Storm (World, 3 Players) (bootleg of FD1094 317-0148 set)"},
        {"astormb2",     "Alien Storm (bootleg, set 2)"},
        {"astormbl",     "Alien Storm (bootleg)"},
        {"astormj",      "Alien Storm (Japan, 2 Players) (FD1094 317-0146)"},
        {"astormjd",     "Alien Storm (Japan, 2 Players) (bootleg of FD1094 317-0146 set)"},
        {"astormu",      "Alien Storm (US, 3 Players) (FD1094 317-0147)"},
        {"astormud",     "Alien Storm (US, 3 Players) (bootleg of FD1094 317-0147 set)"},
        {"astrass",      "Astra SuperStars"},
        {"astrians",     "Astrians (clone of Swarm)"},
        {"astroamb",     "Astro Ambush (Scramble bootleg on Galaxian hardware)"},
        {"astrob",       "Astro Blaster (version 3)"},
        {"astrob1",      "Astro Blaster (version 1)"},
        {"astrob2",      "Astro Blaster (version 2)"},
        {"astrob2a",     "Astro Blaster (version 2a)"},
        {"astrob2b",     "Astro Blaster (version 2b)"},
        {"astrobg",      "Astro Blaster (German)"},
        {"astrof",       "Astro Fighter (set 1)"},
        {"astrof2",      "Astro Fighter (set 2)"},
        {"astrof3",      "Astro Fighter (set 3)"},
        {"astrofl",      "Astro Flash (Japan)"},
        {"astropal",     "Astropal"},
        {"astrowar",     "Astro Wars"},
        {"astrxeaa",     "Asterix (World ver. EAA)"},
        {"astrxeac",     "Asterix (World ver. EAC)"},
        {"astyanax",     "The Astyanax"},
        {"astyanaxa",    "The Astyanax (mask ROM version)"},
        {"asuka",        "Asuka and Asuka (Japan)"},
        {"asukaj",       "Asuka & Asuka (Japan, rev 1)"},
        {"asukaja",      "Asuka & Asuka (Japan)"},
        {"asurabld",     "Asura Blade - Sword of Dynasty"},
        {"asurabus",     "Asura Buster - Eternal Warriors"},
        {"asurabusj",    "Asura Buster - Eternal Warriors (Japan, set 1)"},
        {"asurabusja",   "Asura Buster - Eternal Warriors (Japan, set 2)"},
        {"asurabusjr",   "Asura Buster - Eternal Warriors (Japan) (ARCADIA review build)"},
        {"asylum",       "Asylum (prototype)"},
        {"ataqandr",     "Ataque Androide - Moon Cresta (FAR S.A. Spanish bootleg)"},
        {"atarifb",      "Atari Football (revision 2)"},
        {"atarifb1",     "Atari Football (revision 1)"},
        {"atarifb2",     "Atari Football II"},
        {"atarifb4",     "Atari Football (4 players)"},
        {"ataxx",        "Ataxx (set 1)"},
        {"ataxxa",       "Ataxx (set 2)"},
        {"ataxxe",       "Ataxx (Europe)"},
        {"ataxxj",       "Ataxx (Japan)"},
        {"atehate",      "Athena no Hatena [Q]"},
        {"atetb3482",    "Tetris (bootleg set 6, with UM3482)"},
        {"atetb5205",    "Tetris (bootleg set 7, with OKI M5205)"},
        {"atetckt2",     "Tetris (Cocktail set 2)"},
        {"atetcktl",     "Tetris (Cocktail set 1)"},
        {"atetris",      "Tetris (set 1)"},
        {"atetrisa",     "Tetris (set 2)"},
        {"atetrisb",     "Tetris (bootleg)"},
        {"atetrisb2",    "Tetris (bootleg set 2)"},
        {"atetrisb3",    "Tetris (bootleg set 3)"},
        {"atetrisb4",    "Tetris (bootleg set 4)"},
        {"atetrisbp",    "Tetris (bartop, prototype)"},
        {"atetrisc",     "Tetris (cocktail set 1)"},
        {"atetrisc2",    "Tetris (cocktail set 2)"},
        {"athena",       "Athena"},
        {"athenab",      "Athena (bootleg)"},
        {"atlantis",     "Battle of Atlantis (set 1)"},
        {"atlantis2",    "Battle of Atlantis (set 2)"},
        {"atlantisb",    "Battle of Atlantis (bootleg)"},
        {"atlantol",     "Atlant Olimpic (Italian bootleg)"},
        {"atlants2",     "Battle of Atlantis (set 2)"},
        {"atombjt",      "Atom (bootleg of Bombjack Twin)"},
        {"atomboy",      "Atomic Boy"},
        {"atomboya",     "Atomic Boy (revision A)"},
        {"atomicp",      "Atomic Point (Korea)"},
        {"atompunk",     "New Atomic Punk - Global Quest (US)"},
        {"attackf",      "Attack (bootleg of Defender)"},
        {"attckufo",     "Attack UFO"},
        {"aurail",       "Aurail (set 3, US) (unprotected)"},
        {"aurail1",      "Aurail (set 2, World) (FD1089B 317-0168)"},
        {"aurail1d",     "Aurail (set 2, World) (unprotected of FD1089B 317-0168 set)"},
        {"aurailj",      "Aurail (set 1, Japan) (FD1089A 317-0167)"},
        {"aurailjd",     "Aurail (set 1, Japan) (unprotected of FD1089A 317-0167 set)"},
        {"ausfache",     "Akatsuki Blitzkampf Ausf. Achse (Japan)"},
        {"av2mj1bb",     "AV2Mahjong No.1 Bay Bridge no Seijo (Japan)"},
        {"av2mj2rg",     "AV2Mahjong No.2 Rouge no Kaori (Japan)"},
        {"avalnche",     "Avalanche"},
        {"avefenix",     "Ave Fenix (Electrogame, Spanish bootleg of Phoenix)"},
        {"avefenixl",    "Ave Fenix (Laguna, Spanish bootleg of Phoenix)"},
        {"avefenixrf",   "Ave Fenix (Recreativos Franco, Spanish bootleg of Phoenix)"},
        {"avenger2",     "Avengers (US set 2)"},
        {"avengers",     "Avengers (US set 1)"},
        {"avengersa",    "Avengers (US, rev. C)"},
        {"avengersb",    "Avengers (US, rev. A)"},
        {"avengersc",    "Avengers (US)"},
        {"avengrgs",     "Avengers In Galactic Storm (US/Europe 1.0)"},
        {"avengrgsj",    "Avengers In Galactic Storm (Japan 1.2)"},
        {"avsp",         "Alien vs. Predator (Euro 940520)"},
        {"avspa",        "Alien vs. Predator (Asia 940520)"},
        {"avspd",        "Alien vs. Predator (Europe 940520 Phoenix Edition) (bootleg)"},
        {"avsph",        "Alien vs. Predator (Hispanic 940520)"},
        {"avspirit",     "Avenging Spirit"},
        {"avspj",        "Alien vs. Predator (Japan 940520)"},
        {"avspu",        "Alien vs. Predator (USA 940520)"},
        {"aztarac",      "Aztarac"},
        {"azumanga",     "Azumanga Daioh Puzzle Bobble (GDL-0018)"},
        {"azurian",      "Azurian Attack"},
};

const char *lookup_a(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_a(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
