#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"g13jnr",       "Golgo 13: Juusei no Requiem (Japan, GLT1 VER.A)"},
        {"g13knd",       "Golgo 13 Kiseki no Dandou (Japan, GLS1/VER.A)"},
        {"ga2",          "Golden Axe - The Revenge of Death Adder (US)"},
        {"ga2j",         "Golden Axe - The Revenge of Death Adder (Japan)"},
        {"ga2u",         "Golden Axe: The Revenge of Death Adder (US, Rev A)"},
        {"gahaha",       "GAHAHA Ippatsudou (World, GID2 Ver.A)"},
        {"gahaha2",      "GAHAHA Ippatsudou 2 (Japan, GIS1 Ver.A)"},
        {"gaia",         "Gaia Crusaders"},
        {"gaialast",     "Gaia - The Last Choice of Earth"},
        {"gaiapols",     "Gaiapolis (Japan ver JAF)"},
        {"gaiapolsj",    "Gaiapolis (ver JAF)"},
        {"gaiapolsu",    "Gaiapolis (ver UAF)"},
        {"gaiden",       "Ninja Gaiden (US)"},
        {"gakupara",     "Quiz Gakuen Paradise (Japan)"},
        {"gakusai",      "Mahjong Gakuensai (Japan)"},
        {"gakusai2",     "Mahjong Gakuensai 2 (Japan)"},
        {"gal10ren",     "Mahjong Gal 10-renpatsu (Japan)"},
        {"galactic",     "Galactica - Batalha Espacial"},
        {"galactica2",   "Galactica-2 (bootleg of Moon Alien Part 2)"},
        {"galag88b",     "Galaga '88 (set 2)"},
        {"galag88j",     "Galaga '88 (Japan)"},
        {"galaga",       "Galaga (Namco rev. B)"},
        {"galaga3",      "Galaga 3 (rev. C)"},
        {"galaga3a",     "Galaga 3 (set 2)"},
        {"galaga3m",     "Galaga 3 (set 3)"},
        {"galaga88",     "Galaga '88 (set 1)"},
        {"galaga88a",    "Galaga '88 (02-03-88)"},
        {"galaga88j",    "Galaga '88 (Japan)"},
        {"galagamf",     "Galaga (Midway set 1 with fast shoot hack)"},
        {"galagamk",     "Galaga (Midway set 2)"},
        {"galagamw",     "Galaga (Midway set 1)"},
        {"galagao",      "Galaga (Namco)"},
        {"galaktron",    "Galaktron (Petaco S.A.)"},
        {"galap1",       "Space Invaders Galactica"},
        {"galap2",       "GX Part 2 (hack of Galaxian)"},
        {"galap4",       "Galaxian Part 4"},
        {"galapx",       "Galaxian Part X"},
        {"galartic",     "Galaxian (Artic System bootleg)"},
        {"galastrm",     "Galactic Storm (Japan)"},
        {"galaxbsf",     "Galaxian (bootleg, set 1)"},
        {"galaxbsf2",    "Galaxian (bootleg, set 3)"},
        {"galaxcirsa",   "Galaxian (Cirsa Spanish bootleg)"},
        {"galaxia",      "Galaxia (set 1)"},
        {"galaxiaa",     "Galaxia (set 2)"},
        {"galaxiab",     "Galaxia (set 3)"},
        {"galaxiac",     "Galaxia (set 4)"},
        {"galaxiaj",     "Galaxian (Namco set 2)"},
        {"galaxiamv",    "Diviertate Galaxia (Multivideo, Spanish bootleg of Galaxian)"},
        {"galaxian",     "Galaxian (Namco set 1)"},
        {"galaxiana",    "Galaxian (Namco set 2)"},
        {"galaxianbl",   "Galaxian (bootleg, set 2)"},
        {"galaxianbl2",  "Galaxian (bootleg, set 4)"},
        {"galaxianem",   "Galaxian (Electromar Spanish bootleg)"},
        {"galaxiani",    "Galaxian (Irem)"},
        {"galaxianiii",  "Galaxian III (bootleg of Galaxian)"},
        {"galaxianm",    "Galaxian (Midway set 1)"},
        {"galaxianmo",   "Galaxian (Midway set 2)"},
        {"galaxianrp",   "Galaxian (Rene Pierre bootleg)"},
        {"galaxiant",    "Galaxian (Taito)"},
        {"galaxrcgg",    "Galaxian Growing Galaxip / Galaxian Nave Creciente (Recreativos Covadonga Spanish bootleg)"},
        {"galaxrf",      "Galaxian (Recreativos Franco S.A. Spanish bootleg)"},
        {"galaxrfgg",    "Galaxian Growing Galaxip / Galaxian Nave Creciente (Recreativos Franco S.A. Spanish bootleg)"},
        {"galaxyfg",     "Galaxy Fight - Universal Warriors"},
        {"galaxygn",     "Galaxy Gunners"},
        {"galaxygnh",    "Galaxy Gunners (1990 year hack)"},
        {"galaxyx",      "Galaxy X (bootleg of Galaxian)"},
        {"galemp",       "Galaxy Empire (bootleg?)"},
        {"galgame",      "Galaxy Game"},
        {"galgame2",     "Galaxy Games StarPak 2"},
        {"galgame3",     "Galaxy Games StarPak 3"},
        {"galgame4",     "Galaxy Games StarPak 4"},
        {"galhustl",     "Gals Hustler"},
        {"galivan",      "Galivan - Cosmo Police (12-16-1985)"},
        {"galivan2",     "Galivan - Cosmo Police (12-11-1985)"},
        {"galivan3",     "Cosmo Police Galivan (12/11/1985)"},
        {"galkaika",     "Mahjong Gal no Kaika (Japan)"},
        {"galkamika",    "Kamikaze (Electrogame, Spanish bootleg of Galaxian)"},
        {"galkoku",      "Mahjong Gal no Kokuhaku (Japan)"},
        {"gallag",       "Gallag"},
        {"gallop",       "Gallop - Armed police Unit (Japan)"},
        {"gallopm72",    "Gallop - Armed Police Unit (Japan, M72 hardware)"},
        {"galmedes",     "Galmedes (Japan)"},
        {"galmidw",      "Galaxian (Midway)"},
        {"galmidwo",     "Galaxian (Midway, old rev)"},
        {"galmonst",     "Galaxy Monsters (Laguna S.A. Spanish bootleg of Space Invaders)"},
        {"galpandx",     "Gals Panic DX (Asia)"},
        {"galpani2",     "Gals Panic II (Japan[Q])"},
        {"galpani3",     "Gals Panic 3 (Euro)"},
        {"galpani3hk",   "Gals Panic 3 (Hong Kong)"},
        {"galpani3j",    "Gals Panic 3 (Japan)"},
        {"galpani3k",    "Gals Panic 3 (Korea)"},
        {"galpani4",     "Gals Panic 4 (Japan)"},
        {"galpanib",     "Gals Panic (set 2)"},
        {"galpanic",     "Gals Panic (set 1)"},
        {"galpanica",    "Gals Panic (unprotected)"},
        {"galpanicb",    "Gals Panic (ULA protected, set 1)"},
        {"galpanicc",    "Gals Panic (ULA protected, set 2)"},
        {"galpanis",     "Gals Panic S - Extra Edition (Japan)"},
        {"galpans2",     "Gals Panic S2 (Japan)"},
        {"galsnew",      "Gals Panic (Export, EXPRO-02 PCB)"},
        {"galsnewj",     "Gals Panic (Japan, EXPRO-02 PCB)"},
        {"galsnewk",     "Gals Panic (Korea, EXPRO-02 PCB)"},
        {"galsnewt",     "Gals Panic (Taiwan, EXPRO-02 PCB)"},
        {"galsnewu",     "Gals Panic (US, EXPRO-02 PCB)"},
        {"galspnbl",     "Gals Pinball"},
        {"galturbo",     "Galaxian Turbo"},
        {"galwars2",     "Galaxy Wars II (bootleg of Defender)"},
        {"galxwar2",     "Galaxy Wars (Universal set 2)"},
        {"galxwars",     "Galaxy Wars (Universal set 1)"},
        {"galxwart",     "Galaxy Wars (Taito[Q])"},
        {"gametngk",     "The Game Paradise - Master of Shooting! - Game Tengoku - The Game Paradise"},
        {"gamshara",     "Gamshara (20020912A / 10021 Ver.A)"},
        {"gamsharao",    "Gamshara (20020716A / 10021 Ver.A)"},
        {"ganbare",      "Ganbare! Marine Kun (Japan 2K0411)"},
        {"gangonta",     "Ganbare! Gonta!! 2 / Party Time: Gonta the Diver II (Japan Release)"},
        {"gangwarb",     "Gang Wars (bootleg)"},
        {"gangwars",     "Gang Wars (US)"},
        {"gangwarsb",    "Gang Wars (bootleg)"},
        {"gangwarsj",    "Gang Wars (Japan)"},
        {"gangwarsu",    "Gang Wars (US)"},
        {"ganjaja",      "Ganbare Jajamaru Saisho wa Goo / Ganbare Jajamaru Hop Step & Jump"},
        {"ganryu",       "Musashi Ganryuuki"},
        {"gaplus",       "Gaplus (rev. D)"},
        {"gaplusa",      "Gaplus (alternate hardware)"},
        {"gapluso",      "Gaplus (rev. B)"},
        {"gardia",       "Gardia"},
        {"gardiab",      "Gardia (bootleg)"},
        {"gardiaj",      "Gardia (Japan, 317-0006)"},
        {"garogun",      "Garogun Seroyang (Korea)"},
        {"garou",        "Garou - Mark of the Wolves (set 1)"},
        {"garoubl",      "Garou - Mark of the Wolves (bootleg)"},
        {"garouh",       "Garou - Mark of the Wolves (AES)"},
        {"garouha",      "Garou - Mark of the Wolves (NGH-2530)"},
        {"garouo",       "Garou - Mark of the Wolves (set 2)"},
        {"garoup",       "Garou - Mark of the Wolves (prototype)"},
        {"garuka",       "Garuka (Japan ver. W)"},
        {"garyoret",     "Garyo Retsuden (Japan)"},
        {"gatedom1",     "Gate of Doom (US revision 1)"},
        {"gatedoom",     "Gate of Doom (US revision 4)"},
        {"gatedoom1",    "Gate of Doom (US revision 1)"},
        {"gatsbee",      "Gatsbee"},
        {"gaun22p1",     "Gauntlet II (2 Players, rev 1)"},
        {"gaun22pg",     "Gauntlet II (2 Players, German)"},
        {"gaun2pg1",     "Gauntlet (2 Players, German, rev 1)"},
        {"gaun2pj2",     "Gauntlet (2 Players, Japanese, rev 2)"},
        {"gaun2pr3",     "Gauntlet (2 Players, rev 3)"},
        {"gaunt2",       "Gauntlet II"},
        {"gaunt22p",     "Gauntlet II (2 Players, rev 2)"},
        {"gaunt22p1",    "Gauntlet II (2 Players, rev 1)"},
        {"gaunt22pg",    "Gauntlet II (2 Players, German)"},
        {"gaunt2g",      "Gauntlet II (German)"},
        {"gaunt2p",      "Gauntlet (2 Players, rev 6)"},
        {"gaunt2pg",     "Gauntlet (2 Players, German, rev 4)"},
        {"gaunt2pj",     "Gauntlet (2 Players, Japanese, rev 5)"},
        {"gauntdl",      "Gauntlet Dark Legacy (version DL 2.52)"},
        {"gauntdl24",    "Gauntlet Dark Legacy (version DL 2.4)"},
        {"gauntg",       "Gauntlet (German, rev 10)"},
        {"gauntgr3",     "Gauntlet (German, rev 3)"},
        {"gauntgr6",     "Gauntlet (German, rev 6)"},
        {"gauntgr8",     "Gauntlet (German, rev 8)"},
        {"gauntj",       "Gauntlet (Japanese, rev 13)"},
        {"gauntj12",     "Gauntlet (Japanese, rev 12)"},
        {"gauntleg",     "Gauntlet Legends (version 1.6)"},
        {"gauntleg12",   "Gauntlet Legends (version 1.2)"},
        {"gauntlet",     "Gauntlet (rev 14)"},
        {"gauntlet2p",   "Gauntlet (2 Players, rev 6)"},
        {"gauntlet2pg",  "Gauntlet (2 Players, German, rev 4)"},
        {"gauntlet2pg1", "Gauntlet (2 Players, German, rev 1)"},
        {"gauntlet2pj",  "Gauntlet (2 Players, Japanese, rev 5)"},
        {"gauntlet2pj2", "Gauntlet (2 Players, Japanese, rev 2)"},
        {"gauntlet2pr3", "Gauntlet (2 Players, rev 3)"},
        {"gauntletg",    "Gauntlet (German, rev 10)"},
        {"gauntletgr3",  "Gauntlet (German, rev 3)"},
        {"gauntletgr6",  "Gauntlet (German, rev 6)"},
        {"gauntletgr8",  "Gauntlet (German, rev 8)"},
        {"gauntletj",    "Gauntlet (Japanese, rev 13)"},
        {"gauntletj12",  "Gauntlet (Japanese, rev 12)"},
        {"gauntletr1",   "Gauntlet (rev 1)"},
        {"gauntletr2",   "Gauntlet (rev 2)"},
        {"gauntletr4",   "Gauntlet (rev 4)"},
        {"gauntletr5",   "Gauntlet (rev 5)"},
        {"gauntletr7",   "Gauntlet (rev 7)"},
        {"gauntletr9",   "Gauntlet (rev 9)"},
        {"gauntlets",    "Gauntlet (Spanish, rev 15)"},
        {"gauntr1",      "Gauntlet (rev 1)"},
        {"gauntr2",      "Gauntlet (rev 2)"},
        {"gauntr4",      "Gauntlet (rev 4)"},
        {"gauntr5",      "Gauntlet (rev 5)"},
        {"gauntr7",      "Gauntlet (rev 7)"},
        {"gauntr9",      "Gauntlet (rev 9)"},
        {"gaunts",       "Gauntlet (Spanish, rev 15)"},
        {"gaxeduel",     "Golden Axe - The Duel"},
        {"gberet",       "Green Beret"},
        {"gberetb",      "Green Beret (bootleg)"},
        {"gblchmp",      "Global Champion (US)"},
        {"gbusters",     "Gang Busters"},
        {"gbustersa",    "Gang Busters (set 2)"},
        {"gcastle",      "Golden Castle (prototype?)"},
        {"gcpinbal",     "Grand Cross"},
        {"gdarius",      "G-Darius (JAPAN)"},
        {"gdarius2",     "G-Darius Ver.2 (JAPAN)"},
        {"gdfs",         "Mobile Suit Gundam Final Shooting (Japan)"},
        {"geebee",       "Gee Bee"},
        {"geebeea",      "Gee Bee (UK)"},
        {"geebeeb",      "Gee Bee (Europe)"},
        {"geebeeg",      "Gee Bee (Gremlin)"},
        {"gekiretu",     "Quiz Gekiretsu Scramble (Japan)"},
        {"gekiridn",     "Gekirindan (Ver 2.3O 1995/09/21)"},
        {"gekiridnj",    "Gekirindan (Ver 2.3J 1995/09/21)"},
        {"gekirido",     "Gekirindan (Japan)"},
        {"gemcrush",     "Gemcrush (Japan, prototype)"},
        {"gemini",       "Gemini Wing"},
        {"geminib",      "Gemini Wing (bootleg)"},
        {"geminij",      "Gemini Wing (Japan)"},
        {"genix",        "Genix Family"},
        {"genpeitd",     "Genpei ToumaDen"},
        {"gensitou",     "Genshi-Tou 1930's"},
        {"geostorm",     "Geostorm (Japan)"},
        {"geostorma",    "Geo Storm (Japan, 026 custom sound CPU)"},
        {"getbass",      "Get Bass: Sega Bass Fishing (Japan)"},
        {"getbassdx",    "Get Bass: Sega Bass Fishing Deluxe (Japan)"},
        {"getbassur",    "Get Bass: Sega Bass Fishing Upright (Japan)"},
        {"getstar",      "Guardian (US)"},
        {"getstarb",     "Get Star (bootleg)"},
        {"getstarb1",    "Get Star (bootleg set 1)"},
        {"getstarb2",    "Get Star (bootleg set 2)"},
        {"getstarj",     "Get Star (Japan)"},
        {"gfire2",       "Golden Fire II"},
        {"gforce2",      "Galaxy Force 2"},
        {"gforce2j",     "Galaxy Force 2 (Japan)"},
        {"gforce2ja",    "Galaxy Force 2 (Japan, Rev A)"},
        {"gforce2sd",    "Galaxy Force 2 (Super Deluxe unit)"},
        {"gghost",       "Goalie Ghost"},
        {"ggisuka",      "Guilty Gear Isuka"},
        {"ggoemon",      "Ganbare Goemon"},
        {"ggram2",       "Giant Gram: All Japan Pro Wrestling 2 (Japan)"},
        {"ggreats2",     "Golfing Greats 2 (ver JAC)"},
        {"gground",      "Gain Ground"},
        {"ggroundj",     "Gain Ground (Japan, 2 Players, Floppy Based, FD1094 317-0058-03b)"},
        {"ggx",          "Guilty Gear X"},
        {"ggx15",        "Guilty Gear X ver. 1.5"},
        {"ggxx",         "Guilty Gear XX (GDL-0011)"},
        {"ggxxac",       "Guilty Gear XX Accent Core (Japan) (GDL-0041)"},
        {"ggxxrl",       "Guilty Gear XX #Reload (Japan, Rev A) (GDL-0019A)"},
        {"ggxxrlo",      "Guilty Gear XX #Reload (Japan) (GDL-0019)"},
        {"ggxxsla",      "Guilty Gear XX Slash (Japan, Rev A) (GDL-0033A)"},
        {"ghlpanic",     "Ghoul Panic (World, OB2/VER.A)"},
        {"ghoshunt",     "Ghost Hunter"},
        {"ghostb",       "The Real Ghostbusters (US 2 Players)"},
        {"ghostb2a",     "The Real Ghostbusters (US 2 Players)"},
        {"ghostb3",      "The Real Ghostbusters (US 3 Players)"},
        {"ghostlop",     "Ghostlop (Prototype)"},
        {"ghostmun",     "Ghost Muncher"},
        {"ghouls",       "Ghouls'n Ghosts (World)"},
        {"ghoulsu",      "Ghouls'n Ghosts (US)"},
        {"ghox",         "Ghox (spinner)"},
        {"ghoxj",        "Ghox (joystick)"},
        {"ghoxjo",       "Ghox (joystick, older)"},
        {"ghunter",      "Gang Hunter (Spain)"},
        {"ghunters",     "Gang Hunter / Dead Angle (Spain)"},
        {"gigandes",     "Gigandes"},
        {"gigandesa",    "Gigandes (earlier)"},
        {"gigas",        "Gigas (MC-8123, 317-5002)"},
        {"gigasb",       "Gigas (bootleg)"},
        {"gigasm2",      "Gigas Mark II (MC-8123, 317-5002)"},
        {"gigasm2b",     "Gigas Mark II (bootleg)"},
        {"gigawing",     "Giga Wing (USA 990222)"},
        {"gigawinga",    "Giga Wing (Asia 990222)"},
        {"gigawingb",    "Giga Wing (Brazil 990222)"},
        {"gigawingd",    "Giga Wing (USA 990222 Phoenix Edition) (bootleg)"},
        {"gigawingh",    "Giga Wing (Hispanic 990222)"},
        {"gigawingj",    "Giga Wing (Japan 990223)"},
        {"gigawingjd",   "Giga Wing (Japan 990223 Phoenix Edition) (bootleg)"},
        {"gijoe",        "GI Joe (World)"},
        {"gijoea",       "G.I. Joe (Asia, AA)"},
        {"gijoeea",      "G.I. Joe (World, EB8, prototype?)"},
        {"gijoej",       "GI Joe (Japan)"},
        {"gijoeu",       "GI Joe (US)"},
        {"gijoeua",      "G.I. Joe (US, UAA)"},
        {"gimeabrk",     "Gimme A Break"},
        {"ginganin",     "Ginga NinkyouDen"},
        {"ginganina",    "Ginga Ninkyouden (set 2)"},
        {"ginkun",       "Ganbare Ginkun"},
        {"gionbana",     "Gionbana (Japan 890120)"},
        {"gjspace",      "GekiToride-Jong Space (10011 Ver.A)"},
        {"gladiatr",     "Gladiator (US)"},
        {"glass",        "Glass (Ver 1.1, Break Edition, Checksum 49D5E66B, Version 1994)"},
        {"glass10",      "Glass (Ver 1.0, Break Edition, Checksum C5513F3C)"},
        {"glass10a",     "Glass (Ver 1.0, Break Edition, Checksum D3864FDB)"},
        {"glasskr",      "Glass (Ver 1.1, Break Edition, Checksum D419AB69, Version 1994) (censored, unprotected)"},
        {"glfgreat",     "Golfing Greats"},
        {"glfgretj",     "Golfing Greats (Japan)"},
        {"gloc",         "G-LOC Air Battle (World)"},
        {"glocr360",     "G-LOC R360 (World)"},
        {"glocr360j",    "G-LOC R360 (Japan)"},
        {"glocu",        "G-LOC Air Battle (US)"},
        {"glprac2j",     "Gallop Racer 2 (JAPAN)"},
        {"glprac2l",     "Gallop Racer 2 Link HW (JAPAN)"},
        {"glpracr",      "Gallop Racer (JAPAN Ver 9.01.12)"},
        {"glpracr2",     "Gallop Racer 2 (USA)"},
        {"gmahou",       "Great Mahou Daisakusen (Japan 000121)"},
        {"gmgalax",      "Ghostmuncher Galaxian (bootleg)"},
        {"gmissile",     "Guided Missile"},
        {"gnbarich",     "Gunbarich"},
        {"gng",          "Ghosts'n Goblins (World[Q] set 1)"},
        {"gnga",         "Ghosts'n Goblins (World[Q] set 2)"},
        {"gngbl",        "Ghosts'n Goblins (bootleg with Cross)"},
        {"gngblita",     "Ghosts'n Goblins (Italian bootleg, harder)"},
        {"gngc",         "Ghosts'n Goblins (World? set 3)"},
        {"gngprot",      "Ghosts'n Goblins (prototype)"},
        {"gngt",         "Ghosts'n Goblins (US)"},
        {"goal92",       "Goal '92"},
        {"goalx3",       "Goal! Goal! Goal!"},
        {"gocowboy",     "Go Go Cowboy (English, prize)"},
        {"godzilla",     "Godzilla"},
        {"gogold",       "Go For The Gold (Japan)"},
        {"gogomile",     "Go Go! Mile Smile"},
        {"gogomileo",    "Susume! Mile Smile / Go Go! Mile Smile (older)"},
        {"gogomilj",     "Susume! Mile Smile (Japan)"},
        {"goindol",      "Goindol (World)"},
        {"goindolj",     "Goindol (Korea)"},
        {"goindolu",     "Goindol (US)"},
        {"gokuparo",     "Gokujyou Parodius (ver JAD)"},
        {"goldbug",      "Gold Bug"},
        {"goldmedb",     "Gold Medalist (bootleg)"},
        {"goldmedl",     "Gold Medalist"},
        {"goldmedla",    "Gold Medalist (set 2, Alpha68k III PCB)"},
        {"goldmedlb",    "Gold Medalist (bootleg, Alpha68k III PCB)"},
        {"goldnabl",     "Golden Axe (bootleg)"},
        {"goldnaxa",     "Golden Axe (set 6, US) (8751 317-123A)"},
        {"goldnaxb",     "Golden Axe (Version 2 317-0110)"},
        {"goldnaxc",     "Golden Axe (Version 2 317-0122)"},
        {"goldnaxe",     "Golden Axe (Version 1)"},
        {"goldnaxe1",    "Golden Axe (set 1, World) (FD1094 317-0110)"},
        {"goldnaxe1d",   "Golden Axe (set 1, World) (bootleg of FD1094 317-0110 set)"},
        {"goldnaxe2",    "Golden Axe (set 2, US) (8751 317-0112)"},
        {"goldnaxe3",    "Golden Axe (set 3, World) (FD1094 317-0120)"},
        {"goldnaxe3d",   "Golden Axe (set 3, World) (bootleg of FD1094 317-0120 set)"},
        {"goldnaxej",    "Golden Axe (set 4, Japan) (FD1094 317-0121)"},
        {"goldnaxejd",   "Golden Axe (set 4, Japan) (bootleg of FD1094 317-0121 set)"},
        {"goldnaxeu",    "Golden Axe (set 5, US) (FD1094 317-0122)"},
        {"goldnaxeud",   "Golden Axe (set 5, US) (bootleg of FD1094 317-0122 set)"},
        {"goldnaxj",     "Golden Axe (Version 1, Japan)"},
        {"golgo13",      "Golgo 13 (GLG1-VER.A)"},
        {"gollygho",     "Golly! Ghost!"},
        {"gomoku",       "Gomoku Narabe Renju"},
        {"gondo",        "Gondomania (US)"},
        {"gondou",       "Gondomania (US)"},
        {"goonies",      "Vs. The Goonies"},
        {"goori",        "Goori Goori"},
        {"gorf",         "Gorf"},
        {"gorfirec",     "Gorf (Spain, Irecsa license)"},
        {"gorfpgm1",     "Gorf (Program 1)"},
        {"gorfpgm1f",    "Gorf (program 1, with French language ROM)"},
        {"gorfpgm1g",    "Gorf (program 1, with German language ROM)"},
        {"gorkans",      "Gorkans"},
        {"gorodki",      "Gorodki"},
        {"gotcha",       "Got-cha"},
        {"gotya",        "Got-Ya (12-24-1981, prototype[Q])"},
        {"gowcaizr",     "Voltage Fighter - Gowcaizer / Choujin Gakuen Gowcaizer"},
        {"gpgolf",       "Golden Par Golf (Joystick, V1.1)"},
        {"gpgolfa",      "Golden Par Golf (Joystick, V1.0)"},
        {"gpilots",      "Ghost Pilots"},
        {"gpilotsh",     "Ghost Pilots (AES)"},
        {"gpilotsp",     "Ghost Pilots (prototype)"},
        {"gprider",      "GP Rider (World, FD1094 317-0163) (Twin setup)"},
        {"gpriderj",     "GP Rider (Japan, FD1094 317-0161) (Twin setup)"},
        {"gpriderjs",    "GP Rider (Japan, FD1094 317-0161)"},
        {"gpriders",     "GP Rider (World, FD1094 317-0163)"},
        {"gprideru",     "GP Rider (US, FD1094 317-0162) (Twin setup)"},
        {"gpriderus",    "GP Rider (US, FD1094 317-0162)"},
        {"gradius",      "Gradius"},
        {"gradius2",     "Gradius II - GOFER no Yabou (Japan New Ver.)"},
        {"gradius2a",    "Gradius II - GOFER no Yabou (Japan Old Ver.)"},
        {"gradius2b",    "Gradius II - GOFER no Yabou (Japan Older Ver.)"},
        {"gradius3",     "Gradius III (Japan)"},
        {"gradius3a",    "Gradius III (Asia)"},
        {"gradius3j",    "Gradius III (Japan, program code S)"},
        {"gradius3js",   "Gradius III (Japan, program code S, split)"},
        {"gradius4",     "Gradius IV: Fukkatsu (ver JAC)"},
        {"gradius4a",    "Gradius IV (ver AAC)"},
        {"gradius4aa",   "Gradius IV (ver AAA)"},
        {"gradius4ja",   "Gradius IV: Fukkatsu (ver JAA)"},
        {"gradius4u",    "Gradius IV (ver UAC)"},
        {"gradius4ua",   "Gradius IV (ver UAA)"},
        {"grainbow",     "SD Gundam Sangokushi Rainbow Tairiku Senki (Japan)"},
        {"grainbowk",    "SD Gundam Sangokushi Rainbow Tairiku Senki (Korea)"},
        {"grally",       "Gran Rally (Spanish bootleg of Pole Position II)"},
        {"gram2000",     "Giant Gram 2000"},
        {"grasspin",     "Grasspin"},
        {"gratia",       "Gratia - Second Earth (92047-01 version)"},
        {"gratiaa",      "Gratia - Second Earth (91022-10 version)"},
        {"gravitar",     "Gravitar (version 3)"},
        {"gravitar1",    "Gravitar (version 1)"},
        {"gravitar2",    "Gravitar (version 2)"},
        {"gravitr2",     "Gravitar (version 2)"},
        {"gravp",        "Gravitar (prototype)"},
        {"grchamp",      "Grand Champion"},
        {"grchampb",     "Grand Champion (set 3)"},
        {"grdforce",     "Guardian Force"},
        {"grdian",       "Guardian (US)"},
        {"grdians",      "Guardians - Denjin Makai II"},
        {"grdiansa",     "Guardians / Denjin Makai II (P0-113A PCB)"},
        {"grdiansbl",    "Guardians / Denjin Makai II (bootleg)"},
        {"grdius2a",     "Gradius II - GOFER no Yabou (Japan Old Ver.)"},
        {"grdius2b",     "Gradius II - GOFER no Yabou (Japan Older Ver.)"},
        {"grdius3a",     "Gradius III (Asia)"},
        {"grdius3e",     "Gradius III (World [Q])"},
        {"grdnstrm",     "Sen Jin - Guardian Storm (Korea)"},
        {"grdnstrmau",   "Guardian Storm (horizontal, Australia)"},
        {"grdnstrmg",    "Guardian Storm (Germany)"},
        {"grdnstrmj",    "Sen Jing - Guardian Storm (Japan)"},
        {"grdnstrmk",    "Jeon Sin - Guardian Storm (Korea)"},
        {"grdnstrmv",    "Guardian Storm (vertical)"},
        {"greatgun",     "Great Guns"},
        {"greatgur",     "Great Gurianos (bootleg?)"},
        {"greenber",     "Green Beret (Irem)"},
        {"grescue",      "Galaxy Rescue"},
        {"gridiron",     "Gridiron Fight"},
        {"gridlee",      "Gridlee"},
        {"griffon",      "Griffon (Videotron bootleg of Phoenix)"},
        {"grindsta",     "Grind Stormer (older set)"},
        {"grindstm",     "Grind Stormer"},
        {"grindstma",    "Grind Stormer (older set)"},
        {"grmatch",      "Grudge Match (Yankee Game Technology)"},
        {"grndtour",     "Grand Tour"},
        {"grobda",       "Grobda (New Ver.)"},
        {"grobda2",      "Grobda (Old Ver. set 1)"},
        {"grobda3",      "Grobda (Old Ver. set 2)"},
        {"groovef",      "Power Instinct 3 - Groove On Fight"},
        {"groundfx",     "Ground Effects - Super Ground Effects (Japan)"},
        {"growl",        "Growl (World)"},
        {"growla",       "Growl (World)"},
        {"growlp",       "Growl (World, prototype)"},
        {"growlu",       "Growl (US)"},
        {"grtwall",      "The Great Wall"},
        {"grudge",       "Grudge Match (prototype)"},
        {"grudgei",      "Grudge Match (v00.90, Italy, location test?)"},
        {"grudgep",      "Grudge Match (v00.80, prototype)"},
        {"gryzor",       "Gryzor"},
        {"gryzor1",      "Gryzor (set 2)"},
        {"gseeker",      "Grid Seeker - Project Stormhammer (World)"},
        {"gseekerj",     "Grid Seeker - Project Stormhammer (Japan)"},
        {"gseekeru",     "Grid Seeker - Project Stormhammer (US)"},
        {"gslgr94j",     "Great Sluggers '94 (Japan)"},
        {"gslgr94u",     "Great Sluggers '94"},
        {"gslugrsj",     "Great Sluggers (Japan)"},
        {"gstream",      "G-Stream G2020"},
        {"gstrik2",      "Grand Striker 2 (Japan)"},
        {"gstrik2j",     "Grand Striker 2 (Japan)"},
        {"gstriker",     "Grand Striker"},
        {"gsword",       "Great Swordsman"},
        {"gsword2",      "Great Swordsman (Japan?)"},
        {"gt103a1",      "Trivia (Unsorted question ROMs)"},
        {"gt103aa",      "Trivia (Version 1.03a, alt questions 1)"},
        {"gt103ab",      "Trivia (Version 1.03a, alt questions 2)"},
        {"gt103asx",     "Trivia (Version 1.03a, sex questions)"},
        {"gt103asxa",    "Trivia (Version 1.03a, sex questions, alt revision questions)"},
        {"gt2k",         "Golden Tee 2K (v1.00)"},
        {"gt2kp100",     "Golden Tee 2K (v1.00) (alt protection)"},
        {"gt2ks100",     "Golden Tee 2K (v1.00S)"},
        {"gt2kt500",     "Golden Tee 2K Tournament (v5.00)"},
        {"gt3d",         "Golden Tee 3D Golf (v1.93N)"},
        {"gt3dl19",      "Golden Tee 3D Golf (v1.9L)"},
        {"gt3dl191",     "Golden Tee 3D Golf (v1.91L)"},
        {"gt3dl192",     "Golden Tee 3D Golf (v1.92L)"},
        {"gt3ds192",     "Golden Tee 3D Golf (v1.92S)"},
        {"gt3dt211",     "Golden Tee 3D Golf Tournament (v2.11)"},
        {"gt3dt231",     "Golden Tee 3D Golf Tournament (v2.31)"},
        {"gt3dv14",      "Golden Tee 3D Golf (v1.4)"},
        {"gt3dv15",      "Golden Tee 3D Golf (v1.5)"},
        {"gt3dv16",      "Golden Tee 3D Golf (v1.6)"},
        {"gt3dv17",      "Golden Tee 3D Golf (v1.7)"},
        {"gt3dv18",      "Golden Tee 3D Golf (v1.8)"},
        {"gt507uk",      "Trivia (UK Version 5.07)"},
        {"gt97",         "Golden Tee '97 (v1.30)"},
        {"gt97s121",     "Golden Tee '97 (v1.21S)"},
        {"gt97t240",     "Golden Tee '97 Tournament (v2.40)"},
        {"gt97t243",     "Golden Tee '97 Tournament (v2.43)"},
        {"gt97v120",     "Golden Tee '97 (v1.20)"},
        {"gt97v121",     "Golden Tee '97 (v1.21)"},
        {"gt97v122",     "Golden Tee '97 (v1.22)"},
        {"gt98",         "Golden Tee '98 (v1.10)"},
        {"gt98c100",     "Golden Tee '98 (v1.00C)"},
        {"gt98s100",     "Golden Tee '98 (v1.00S)"},
        {"gt98t302",     "Golden Tee '98 Tournament (v3.02)"},
        {"gt98t303",     "Golden Tee '98 Tournament (v3.03)"},
        {"gt98v100",     "Golden Tee '98 (v1.00)"},
        {"gt99",         "Golden Tee '99 (v1.00)"},
        {"gt99s100",     "Golden Tee '99 (v1.00S)"},
        {"gt99t400",     "Golden Tee '99 Tournament (v4.00)"},
        {"gtclassc",     "Golden Tee Classic (v1.00)"},
        {"gtclasscp",    "Golden Tee Classic (v1.00) (alt protection)"},
        {"gtclasscs",    "Golden Tee Classic (v1.00S)"},
        {"gtdiamond",    "Golden Tee Diamond Edition Tournament (v3.05T ELC)"},
        {"gteikob2",     "Gingateikoku No Gyakushu (bootleg set 2)"},
        {"gteikokb",     "Gingateikoku No Gyakushu (bootleg set 1)"},
        {"gteikoku",     "Gingateikoku No Gyakushu"},
        {"gteikokub",    "Gingateikoku no Gyakushu (bootleg set 1)"},
        {"gteikokub2",   "Gingateikoku no Gyakushu (bootleg set 2)"},
        {"gteikokub3",   "Gingateikoku no Gyakushu (bootleg set 3)"},
        {"gtfore01",     "Golden Tee Fore! (v1.00.25)"},
        {"gtfore02",     "Golden Tee Fore! 2002 (v2.01.06)"},
        {"gtfore03",     "Golden Tee Fore! 2003 (v3.00.10)"},
        {"gtfore03a",    "Golden Tee Fore! 2003 (v3.00.09)"},
        {"gtfore04",     "Golden Tee Fore! 2004 Extra (v4.00.08)"},
        {"gtfore04a",    "Golden Tee Fore! 2004 (v4.00.00)"},
        {"gtfore05",     "Golden Tee Fore! 2005 Extra (v5.01.06)"},
        {"gtfore05a",    "Golden Tee Fore! 2005 Extra (v5.01.02)"},
        {"gtfore05b",    "Golden Tee Fore! 2005 Extra (v5.01.00)"},
        {"gtfore05c",    "Golden Tee Fore! 2005 Extra (v5.00.00)"},
        {"gtfore06",     "Golden Tee Fore! 2006 Complete (v6.00.01)"},
        {"gtg",          "Golden Tee Golf (Joystick, v3.1)"},
        {"gtg2",         "Golden Tee Golf II (Trackball, V2.2)"},
        {"gtg2j",        "Golden Tee Golf II (Joystick, V1.0)"},
        {"gtg2t",        "Golden Tee Golf II (Trackball, V1.1)"},
        {"gtgj31",       "Golden Tee Golf (Joystick, v3.1)"},
        {"gtgt10",       "Golden Tee Golf (Trackball, v1.0)"},
        {"gtgt20",       "Golden Tee Golf (Trackball, v2.0)"},
        {"gtgt21",       "Golden Tee Golf (Trackball, v2.1)"},
        {"gticlub",      "GTI Club: Rally Cote D'Azur (ver EAA)"},
        {"gticluba",     "GTI Club: Rally Cote D'Azur (ver AAA)"},
        {"gticlubj",     "GTI Club: Rally Cote D'Azur (ver JAA)"},
        {"gticlubu",     "GTI Club: Rally Cote D'Azur (ver UAA)"},
        {"gtmr",         "Great 1000 Miles Rally"},
        {"gtmr2",        "Mille Miglia 2 - Great 1000 Miles Rally"},
        {"gtmr2a",       "Mille Miglia 2: Great 1000 Miles Rally (95/04/04)"},
        {"gtmr2u",       "Great 1000 Miles Rally 2 USA (95/07/11)"},
        {"gtmr2ua",      "Great 1000 Miles Rally 2 USA (95/05/18)"},
        {"gtmra",        "1000 Miglia: Great 1000 Miles Rally (94/06/13)"},
        {"gtmrb",        "1000 Miglia: Great 1000 Miles Rally (94/05/26)"},
        {"gtmre",        "Great 1000 Miles Rally (Evolution Model)"},
        {"gtmro",        "1000 Miglia: Great 1000 Miles Rally (94/05/10)"},
        {"gtmrusa",      "Great 1000 Miles Rally (USA)"},
        {"gtroyal",      "Golden Tee Royal Edition Tournament (v4.02T EDM)"},
        {"gtsers1",      "Trivia (Questions Series 1)"},
        {"gtsers10",     "Trivia (Questions Series 10)"},
        {"gtsers11",     "Trivia (Questions Series 11)"},
        {"gtsers11a",    "Trivia (Questions Series 11, alt question ROM, set 1)"},
        {"gtsers11b",    "Trivia (Questions Series 11, alt question ROM, set 2)"},
        {"gtsers12",     "Trivia (Questions Series 12)"},
        {"gtsers12a",    "Trivia (Questions Series 12, alt question ROM)"},
        {"gtsers14",     "Trivia (Questions Series 14)"},
        {"gtsers14a",    "Trivia (Questions Series 14, alt question ROM)"},
        {"gtsers15",     "Trivia (Questions Series 15)"},
        {"gtsers18",     "Trivia (Questions Series 18)"},
        {"gtsers2",      "Trivia (Questions Series 2)"},
        {"gtsers3",      "Trivia (Questions Series 3)"},
        {"gtsers4",      "Trivia (Questions Series 4)"},
        {"gtsers5",      "Trivia (Questions Series 5)"},
        {"gtsers7",      "Trivia (Questions Series 7)"},
        {"gtsers7a",     "Trivia (Questions Series 7, alt question ROM)"},
        {"gtsers8",      "Trivia (Questions Series 8)"},
        {"gtsers8a",     "Trivia (Questions Series 8, alt question ROM)"},
        {"gtsers9",      "Trivia (Questions Series 9)"},
        {"gtsersa",      "Trivia (Alt revision questions set 1)"},
        {"gtsersb",      "Trivia (Alt revision questions set 2)"},
        {"gtsupreme",    "Golden Tee Supreme Edition Tournament (v5.10T ELC S)"},
        {"guab",         "Give us a Break"},
        {"guardian",     "Guardians of the Hood"},
        {"guiness",      "The Guiness (Japan)"},
        {"gulfstr2",     "Gulf Storm (Media Shoji)"},
        {"gulfstrm",     "Gulf Storm"},
        {"gulfstrma",    "Gulf Storm (set 2)"},
        {"gulfstrmb",    "Gulf Storm (set 3)"},
        {"gulfstrmk",    "Gulf Storm (Korea)"},
        {"gulfstrmm",    "Gulf Storm (Japan, Media Shoji license)"},
        {"gulfwar2",     "Gulf War II"},
        {"gulfwar2a",    "Gulf War II (set 2)"},
        {"gulunpa",      "Gulun.Pa! (Japan 931220 L Prototype)"},
        {"gumbo",        "Gumbo"},
        {"gunball",      "Gun Ball (Japan)"},
        {"gunbarl",      "Gunbarl (Japan, GNB4/VER.A)"},
        {"gunbarla",     "Gunbarl (Japan, GNB1/VER.A)"},
        {"gunbird",      "Gunbird (World)"},
        {"gunbird2",     "Gunbird 2"},
        {"gunbird2a",    "Gunbird 2 (set 2)"},
        {"gunbirdj",     "Gunbird (Japan)"},
        {"gunbirdk",     "Gunbird (Korea)"},
        {"gunblade",     "Gunblade NY (Revision A)"},
        {"gunbulet",     "Gun Bullet (Japan)"},
        {"gunbuletj",    "Gun Bullet (Japan, GN1)"},
        {"gunbuletw",    "Gun Bullet (World, GN3 Rev B)"},
        {"gunbustr",     "Gunbuster (Japan)"},
        {"gunbustrj",    "Gunbuster (Japan)"},
        {"gunbustru",    "Gunbuster (US)"},
        {"gundamex",     "Mobile Suit Gundam EX Revue"},
        {"gundeala",     "Gun Dealer (set 2)"},
        {"gundealr",     "Gun Dealer (set 1)"},
        {"gundealra",    "Gun Dealer (alt card set)"},
        {"gundealrbl",   "Gun Dealer (Yam! Yam!? hardware, set 1)"},
        {"gundealrbl2",  "Gun Dealer (Yam! Yam!? hardware, set 2)"},
        {"gundealrt",    "Gun Dealer (Japan)"},
        {"gundealt",     "Gun Dealer (Tecmo)"},
        {"gundhara",     "Gundhara"},
        {"gundharac",    "Gundhara (Chinese, bootleg?)"},
        {"gundl94",      "Gun Dealer '94"},
        {"gundmct",      "Mobile Suit Gundam: Federation Vs. Zeon"},
        {"gundmgd",      "Mobile Suit Gundam: Federation Vs. Zeon (GDL-0001)"},
        {"gundmxgd",     "Mobile Suit Gundam: Federation Vs. Zeon DX (USA, Japan) (GDL-0006)"},
        {"gunfight",     "Gun Fight"},
        {"gunfighto",    "Gun Fight (set 2)"},
        {"gunforc2",     "Gunforce 2 (US)"},
        {"gunforce",     "Gunforce - Battle Fire Engulfed Terror Island (World)"},
        {"gunforcej",    "Gunforce - Battle Fire Engulfed Terror Island (Japan)"},
        {"gunforceu",    "Gunforce - Battle Fire Engulfed Terror Island (US)"},
        {"gunforcj",     "Gunforce - Battle Fire Engulfed Terror Island (Japan)"},
        {"gunforcu",     "Gunforce - Battle Fire Engulfed Terror Island (US)"},
        {"gunfronj",     "Gun Frontier (Japan)"},
        {"gunfront",     "Gun and Frontier (World)"},
        {"gunfrontj",    "Gun Frontier (Japan)"},
        {"gunhohki",     "Gun Hohki (Japan)"},
        {"gunlock",      "Gunlock (World)"},
        {"gunlocko",     "Gunlock (Ver 2.0O 1993/12/15)"},
        {"gunmast",      "Gun Master"},
        {"gunnail",      "GunNail"},
        {"gunnailb",     "GunNail (bootleg)"},
        {"gunnailp",     "GunNail (location test)"},
        {"gunpey",       "Gunpey (Japan)"},
        {"gunsmoka",     "Gun.Smoke (US set 2)"},
        {"gunsmoke",     "Gun.Smoke (World)"},
        {"gunsmokeb",    "Gun.Smoke (World, 1985-11-15) (bootleg)"},
        {"gunsmokeg",    "Gun.Smoke (Germany, 1985-11-15, censored)"},
        {"gunsmokej",    "Gun.Smoke (Japan, 1985-11-15)"},
        {"gunsmokeu",    "Gun.Smoke (USA and Canada, 1986-04-08)"},
        {"gunsmokeua",   "Gun.Smoke (USA and Canada, 1986-01-20)"},
        {"gunsmokeub",   "Gun.Smoke (USA and Canada, 1985-11-15, set 1)"},
        {"gunsmokeuc",   "Gun.Smoke (USA and Canada, 1985-11-15, set 2)"},
        {"gunsmokj",     "Gun.Smoke (Japan)"},
        {"gunsmoku",     "Gun.Smoke (US set 1)"},
        {"gunsur2",      "Gun Survivor 2 Biohazard Code: Veronica (World, BHF2 Ver.E)"},
        {"gunsur2e",     "Gun Survivor 2 Biohazard Code: Veronica (BHF2 Ver. E)"},
        {"gunsur2j",     "Gun Survivor 2 Biohazard Code: Veronica (Japan, BHF1 Ver.E)"},
        {"gururin",      "Gururin"},
        {"gussun",       "Gussun Oyoyo (Japan)"},
        {"gutangtn",     "Guttang Gottong"},
        {"guts",         "Guts n' Glory (prototype)"},
        {"gutsn",        "Guts'n (Japan)"},
        {"guttangt",     "Guttang Gottong (bootleg on Galaxian hardware)"},
        {"guttangts3",   "Guttang Gottong (Sede 3 bootleg on Galaxian hardware)"},
        {"guwange",      "Guwange (Japan)"},
        {"guwanges",     "Guwange (Japan Special Ver 2000 7-7)"},
        {"guzzler",      "Guzzler"},
        {"guzzlers",     "Guzzler (Swimmer Conversion)"},
        {"gwar",         "Guerrilla War (US)"},
        {"gwara",        "Guerrilla War (Version 1)"},
        {"gwarab",       "Guerrilla War (Version 1, set 2)"},
        {"gwarb",        "Guerrilla War (joystick hack bootleg)"},
        {"gwarj",        "Guevara (Japan)"},
        {"gwarrior",     "Galactic Warriors"},
        {"gwing2",       "Giga Wing 2"},
        {"gypsyjug",     "Gypsy Juggler"},
        {"gyrodine",     "Gyrodine"},
        {"gyrodinet",    "Gyrodine (Taito Corporation license)"},
        {"gyruss",       "Gyruss (Konami)"},
        {"gyrussb",      "Gyruss (bootleg?)"},
        {"gyrussce",     "Gyruss (Centuri)"},
};

const char *lookup_g(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_g(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
