#include "lookup.h"
#include <string.h>

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"nam1975",        "NAM-1975"},
        {"namenayo",       "Namennayo (Japan)"},
        {"nametune",       "Name That Tune"},
        {"nametunea",      "Name That Tune (Bally, 3/23/86)"},
        {"naname",         "Naname de Magic! (Japan)"},
        {"narc",           "Narc (rev 7.00)"},
        {"narc1",          "Narc (rev 1.80)"},
        {"narc2",          "Narc (rev 2.00)"},
        {"narc3",          "Narc (rev 3.20)"},
        {"narc4",          "Narc (rev 4.00)"},
        {"narc6",          "Narc (rev 6.00)"},
        {"nastar",         "Nastar (World)"},
        {"nastarw",        "Nastar Warrior (US)"},
        {"natodef",        "NATO Defense"},
        {"natodefa",       "NATO Defense (alternate mazes)"},
        {"natsuiro",       "Natsuiro Mahjong (Japan)"},
        {"naughtya",       "Naughty Boy (bootleg)"},
        {"naughtyb",       "Naughty Boy"},
        {"naughtyba",      "Naughty Boy (bootleg, set 1)"},
        {"naughtybb",      "Naughty Boy (bootleg, set 2)"},
        {"naughtybc",      "Naughty Boy (Cinematronics)"},
        {"naughtyc",       "Naughty Boy (Cinematronics)"},
        {"navalone",       "Navarone"},
        {"navarone",       "Navarone"},
        {"nbaatw",         "NBA All The Way (ver EAB)"},
        {"nbaatwa",        "NBA All The Way (ver EAA)"},
        {"nbagold",        "SportStation: NBA Showtime NBA on NBC Gold Edition (ver 3.0, Feb 18 2000) / NFL Blitz 2000 Gold Edition"},
        {"nbahangt",       "NBA Hangtime (rev L1.1 04-16-96)"},
        {"nbahangtl11",    "NBA Hangtime (ver L1.1 4/16/96)"},
        {"nbahangtl12",    "NBA Hangtime (ver L1.2 8/29/96)"},
        {"nbahangtm11",    "NBA Hangtime (ver M1.1 4/16/96)"},
        {"nbahangtm12",    "NBA Hangtime (ver M1.2 8/29/96)"},
        {"nbahangtm13",    "NBA Hangtime (ver M1.3 10/10/96)"},
        {"nbajam",         "NBA Jam (rev 3.01 04-07-93)"},
        {"nbajamex",       "NBA Jam Extreme"},
        {"nbajamp1",       "NBA Jam (proto v 1.01 1/23/93)"},
        {"nbajamp2",       "NBA Jam (proto v 2.00 1/24/93)"},
        {"nbajamr1",       "NBA Jam (rev 1.00 2/1/93)"},
        {"nbajamr2",       "NBA Jam (rev 2.00 02-10-93)"},
        {"nbajamt1",       "NBA Jam TE (rev 1.0 01-17-94)"},
        {"nbajamt2",       "NBA Jam TE (rev 2.0 01-28-94)"},
        {"nbajamt3",       "NBA Jam TE (rev 3.0 03-04-94)"},
        {"nbajamte",       "NBA Jam TE (rev 4.0 03-23-94)"},
        {"nbajamte1",      "NBA Jam Tournament Edition (rev 1.00 1/17/94)"},
        {"nbajamte2",      "NBA Jam Tournament Edition (rev 2.1 2/06/94)"},
        {"nbajamte2a",     "NBA Jam Tournament Edition (rev 2.0 1/28/94)"},
        {"nbajamte3",      "NBA Jam Tournament Edition (rev 3.0 3/04/94)"},
        {"nbajamte3a",     "NBA Jam Tournament Edition (rev 3.0 2/26/94)"},
        {"nbajamte4",      "NBA Jam Tournament Edition (rev 4.0 3/03/94)"},
        {"nbajamten",      "NBA Jam Tournament Edition (Nani Edition, rev 5.2 8/11/95, prototype)"},
        {"nbajamtep2",     "NBA Jam Tournament Edition (proto 2.00 12/17/93)"},
        {"nbajamtr",       "NBA Jam TE Rewind ver 1.1"},
        {"nbamht",         "NBA Maximum Hangtime (rev 1.03 06/09/97)"},
        {"nbamht1",        "NBA Maximum Hangtime (rev 1.0 11/08/96)"},
        {"nbamhtl10",      "NBA Maximum Hangtime (ver L1.0 11/08/96)"},
        {"nbamhtm10",      "NBA Maximum Hangtime (ver M1.0 11/08/96)"},
        {"nbamhtp",        "NBA Maximum Hangtime (ver L0.9 10/30/96)"},
        {"nbanfl",         "SportStation: NBA Showtime NBA on NBC (ver 2.1, Sep 22 1999) / NFL Blitz 2000 Gold Edition (ver 1.5, Sep 22 1999)"},
        {"nbapbp",         "NBA Play By Play (ver UAB)"},
        {"nbapbpa",        "NBA Play By Play (ver AAB)"},
        {"nbapbpaa",       "NBA Play By Play (ver AAA)"},
        {"nbapbpj",        "NBA Play By Play (ver JAB)"},
        {"nbapbpja",       "NBA Play By Play (ver JAA)"},
        {"nbapbpua",       "NBA Play By Play (ver UAA)"},
        {"nbashowt",       "NBA Showtime NBA on NBC (ver 2.0, Apr 25 1999)"},
        {"nbbatman",       "Ninja Baseball Batman (US)"},
        {"nbbatmanu",      "Ninja Baseball Bat Man (US)"},
        {"ncombat",        "Ninja Combat"},
        {"ncombath",       "Ninja Combat (NGH-009)"},
        {"ncommand",       "Ninja Commando"},
        {"ncv1",           "Namco Classics Collection Vol.1"},
        {"ncv1j",          "Namco Classics Collection Vol.1 (Japan set 1)"},
        {"ncv1j2",         "Namco Classics Collection Vol.1 (Japan set 2)"},
        {"ncv2",           "Namco Classics Collection Vol.2"},
        {"ncv2j",          "Namco Classics Collection Vol.2 (Japan)"},
        {"nebulbee",       "Nebulous Bee"},
        {"nebulray",       "Nebulas Ray (World)"},
        {"nebulrayj",      "Nebulas Ray (Japan, NR1)"},
        {"nebulrayp",      "Nebulas Ray (prototype)"},
        {"nebulryj",       "Nebulas Ray (Japan)"},
        {"neckneck",       "Neck-n-Neck (v1.2)"},
        {"nekkyoku",       "Rettou Juudan Nekkyoku Janshi - Higashi Nippon Hen (Japan)"},
        {"nemesis",        "Nemesis"},
        {"nemesisuk",      "Nemesis (World?, ROM version)"},
        {"nemesuk",        "Nemesis (World[Q])"},
        {"nemo",           "Nemo (World 901130)"},
        {"nemoj",          "Nemo (Japan 901120)"},
        {"nemoja",         "Nemo (Japan 901120, 89625B-1 ROM board)"},
        {"nemor1",         "Nemo (World 901109)"},
        {"neobattl",       "SD Gundam Neo Battling (Japan)"},
        {"neobombe",       "Neo Bomberman"},
        {"neocup98",       "Neo-Geo Cup '98 - The Road to the Victory"},
        {"neodrift",       "Neo Drift Out - New Technology"},
        {"neogeo",         "Neo-Geo"},
        {"neomrdo",        "Neo Mr. Do!"},
        {"netmerc",        "Sega NetMerc"},
        {"nettoqc",        "Nettoh Quiz Champion (Japan)"},
        {"netwars",        "Net Wars"},
        {"newapunk",       "New Atomic Punk - Global Quest (US)"},
        {"newfant",        "New Fantasia"},
        {"newfanta",       "New Fantasia (1994 copyright)"},
        {"newpuc2",        "Newpuc2"},
        {"newpuc2b",       "Newpuc2 (set 2)"},
        {"newpuckx",       "New Puck-X"},
        {"news",           "News"},
        {"newsa",          "News (set 2)"},
        {"newsin7",        "New Sinbad 7"},
        {"newsin7a",       "New Sinbad 7 (set 2)"},
        {"newtangl",       "New Tropical Angel"},
        {"newxpang",       "New Cross Pang (set 1)"},
        {"newxpanga",      "New Cross Pang (set 2)"},
        {"nextfase",       "Next Fase (bootleg of Phoenix)"},
        {"ngbc",           "NeoGeo Battle Coliseum"},
        {"ngbcj",          "NeoGeo Battle Coliseum (Japan)"},
        {"ngpgal",         "Nekketsu Grand-Prix Gal (Japan)"},
        {"nhidctch",       "New Hidden Catch (World) / New Tul Lin Gu Lim Chat Ki '98 (Korea) (pcb ver 3.02)"},
        {"nibbler",        "Nibbler (set 1)"},
        {"nibbler6",       "Nibbler (rev 6)"},
        {"nibbler7",       "Nibbler (rev 7)"},
        {"nibbler8",       "Nibbler (rev 8)"},
        {"nibblera",       "Nibbler (set 2)"},
        {"nibblero",       "Nibbler (rev 8, Olympia)"},
        {"nibblerp",       "Nibbler (rev 6, Pioneer Balloon conversion)"},
        {"nicetsuk",       "Tsukkomi Yousei Gips Nice Tsukkomi (NTK1 Ver.A)"},
        {"nightstr",       "Night Striker (US)"},
        {"nightstrj",      "Night Striker (Japan)"},
        {"nightstru",      "Night Striker (US)"},
        {"ninclown",       "Ninja Clowns (08-27-91)"},
        {"ninja",          "Ninja (315-5102)"},
        {"ninjak",         "The Ninja Kids (World)"},
        {"ninjak2a",       "Ninja-Kid II (set 2)"},
        {"ninjak2b",       "Ninja-Kid II (set 3)"},
        {"ninjakd2",       "Ninja-Kid II (set 1)"},
        {"ninjakd2a",      "Ninja-Kid II / NinjaKun Ashura no Shou (set 2, bootleg?)"},
        {"ninjakd2b",      "Ninja-Kid II / NinjaKun Ashura no Shou (set 3, bootleg?)"},
        {"ninjakd2c",      "Ninja-Kid II / NinjaKun Ashura no Shou (set 4)"},
        {"ninjakj",        "The Ninja Kids (Japan)"},
        {"ninjaku",        "The Ninja Kids (US)"},
        {"ninjakun",       "Ninjakun Majou no Bouken"},
        {"ninjamas",       "Ninja Master's - Haoh-ninpo-cho"},
        {"ninjaslt",       "Ninja Assault (World, NJA2 Ver.A)"},
        {"ninjaslt1",      "Ninja Assault (NJA1 Ver. A)"},
        {"ninjaslt2",      "Ninja Assault (NJA2 Ver. A)"},
        {"ninjaslt4",      "Ninja Assault (NJA4 Ver. A)"},
        {"ninjaslta",      "Ninja Assault (Asia, NJA4 Ver.A)"},
        {"ninjasltj",      "Ninja Assault (Japan, NJA1 Ver.A)"},
        {"ninjasltu",      "Ninja Assault (US, NJA3 Ver.A)"},
        {"ninjaw",         "The Ninja Warriors (World)"},
        {"ninjaw1",        "The Ninja Warriors (World, earlier version)"},
        {"ninjawj",        "The Ninja Warriors (Japan)"},
        {"ninjawu",        "The Ninja Warriors (US, Romstar license)"},
        {"ninjemak",       "Ninja Emaki (US)"},
        {"nitd",           "Nightmare in the Dark"},
        {"nitdbl",         "Nightmare in the Dark (bootleg)"},
        {"nitedrvr",       "Night Driver"},
        {"nitrobal",       "Nitro Ball (US)"},
        {"nitrobala",      "Nitro Ball (World, set 2)"},
        {"nitrobalb",      "Nitro Ball (World, set 3)"},
        {"niyanpai",       "Niyanpai (Japan)"},
        {"nkdodge",        "Nekketsu Koukou Dodgeball Bu (Japan)"},
        {"nkdodgeb",       "Nekketsu Koukou Dodgeball Bu (Japan bootleg)"},
        {"nmaster",        "Oni - The Ninja Master (Japan)"},
        {"nmg5",           "Multi 5 / New Multi Game 5 (set 1)"},
        {"nmg5a",          "Multi 5 / New Multi Game 5 (set 2, censored)"},
        {"nmg5e",          "Multi 5 / New Multi Game 5 (set 3, earlier)"},
        {"nmouse",         "Naughty Mouse (set 1)"},
        {"nmouseb",        "Naughty Mouse (set 2)"},
        {"nmsengen",       "Nekketsu Mahjong Sengen! AFTER 5 (Japan)"},
        {"noahsark",       "Noah's Ark"},
        {"nob",            "Noboranka (Japan)"},
        {"nobb",           "Noboranka (Japan, bootleg)"},
        {"noboranb",       "Noboranka (Japan)"},
        {"nomnlnd",        "No Man's Land"},
        {"nomnlndg",       "No Man's Land (Gottlieb)"},
        {"nost",           "Nostradamus"},
        {"nostj",          "Nostradamus (Japan)"},
        {"nostk",          "Nostradamus (Korea)"},
        {"nostromo",       "Nostromo"},
        {"nouryoku",       "Nouryoku Koujou Iinkai"},
        {"nouryokup",      "Nouryoku Koujou Iinkai (prototype)"},
        {"nov2001u",       "Nova 2001 (US)"},
        {"nova2001",       "Nova 2001 (Japan)"},
        {"nova2001h",      "Nova 2001 (Japan, hack?)"},
        {"nova2001u",      "Nova 2001 (US)"},
        {"nprinces",       "Ninja Princess (64k Ver. bootleg[Q])"},
        {"nprincesb",      "Ninja Princess (315-5051?, 128k Ver. bootleg?)"},
        {"nprinceso",      "Ninja Princess (315-5098, 128k Ver.)"},
        {"nprincesu",      "Ninja Princess (64k Ver. not encrypted)"},
        {"nprincsb",       "Ninja Princess (128k Ver. bootleg[Q])"},
        {"nprincso",       "Ninja Princess (128k Ver.)"},
        {"nprincsu",       "Ninja Princess (64k Ver. not encrypted)"},
        {"nrallyx",        "New Rally X"},
        {"nratechu",       "Neratte Chu"},
        {"nslasher",       "Night Slashers (Korea Rev 1.3)"},
        {"nslasherj",      "Night Slashers (Japan Rev 1.2)"},
        {"nslashers",      "Night Slashers (Over Sea Rev 1.2)"},
        {"nslasheru",      "Night Slashers (US Rev 1.2)"},
        {"nspirit",        "Ninja Spirit"},
        {"nspiritj",       "Saigo no Nindou (Japan)"},
        {"nss",            "Nintendo Super System - BIOS"},
        {"nss_actr",       "Nintendo Super System - Act Raiser"},
        {"nss_adam",       "Nintendo Super System - The Addams Family"},
        {"nss_aten",       "Nintendo Super System - David Crane's Amazing Tennis"},
        {"nss_con3",       "Nintendo Super System - Contra 3 - The Alien Wars"},
        {"nss_fzer",       "Nintendo Super System - F-Zero"},
        {"nss_lwep",       "Nintendo Super System - Lethal Weapon"},
        {"nss_ncaa",       "Nintendo Super System - NCAA Basketball"},
        {"nss_rob3",       "Nintendo Super System - Robocop 3"},
        {"nss_skin",       "Nintendo Super System - Skins Game"},
        {"nss_smw",        "Nintendo Super System - Super Mario World"},
        {"nss_ssoc",       "Nintendo Super System - Super Soccer"},
        {"nss_sten",       "Nintendo Super System - Super Tennis"},
        {"nstocker",       "Night Stocker"},
        {"nstockera",      "Night Stocker (8/27/86)"},
        {"ntopstar",       "Mahjong Nerae! Top Star (Japan)"},
        {"numanath",       "Numan Athletics (World)"},
        {"numanathj",      "Numan Athletics (Japan)"},
        {"numanatj",       "Numan Athletics (Japan)"},
        {"numcrash",       "Number Crash"},
        {"nunchaku",       "Nunchackun"},
        {"nvs_machrider",  "Vs. Mach Rider (Endurance Course Version)"},
        {"nvs_machridera", "Vs. Mach Rider (Fighting Course Version, set MR4-1 A)"},
        {"nvs_mightybj",   "Vs. Mighty Bomb Jack (Japan)"},
        {"nvs_platoon",    "Vs. Platoon"},
        {"nwarr",          "Night Warriors: Darkstalkers' Revenge (Euro 950316)"},
        {"nwarra",         "Night Warriors: Darkstalkers' Revenge (Asia 950302)"},
        {"nwarrb",         "Night Warriors: Darkstalkers' Revenge (Brazil 950403)"},
        {"nwarrh",         "Night Warriors: Darkstalkers' Revenge (Hispanic 950403)"},
        {"nwarru",         "Night Warriors: Darkstalkers' Revenge (USA 950406)"},
        {"nwarrud",        "Night Warriors: Darkstalkers' Revenge (USA 950406 Phoenix Edition) (bootleg)"},
        {"nyanpani",       "Nyan Nyan Panic (Japan)"},
        {"nycaptor",       "N.Y. Captor"},
        {"nyny",           "New York New York"},
        {"nynyg",          "New York New York (Gottlieb)"},
        {"nzeroteam",      "New Zero Team (V33 SYSTEM TYPE_B hardware)"},
        {"nzeroteama",     "New Zero Team (V33 SYSTEM TYPE_B hardware, Zhongguo Shantou Yihuang license)"},
        {"nzeroteamb",     "New Zero Team (V33 SYSTEM TYPE_B hardware, Haoyunlai Trading Company license)"},
};

const char *lookup_n(const char *name) {
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_n(const char *value) {
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].value, value) == 0) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
