#include "lookup.h"
#include <string.h>

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"b2b",         "Bang Bang Busters"},
        {"backfire",    "Backfire!"},
        {"backfirea",   "Backfire! (Japan, set 2)"},
        {"backfirt",    "Back Fire (Tecmo)"},
        {"baddudes",    "Bad Dudes vs. Dragonninja (US)"},
        {"badlands",    "Bad Lands"},
        {"bagman",      "Bagman"},
        {"bagmanj",     "Bagman (Taito)"},
        {"bagmanm2",    "Bagman (bootleg on Moon Cresta hardware, set 2)"},
        {"bagmanm3",    "Bagman (bootleg on Moon Cresta hardware, set 3)"},
        {"bagmanmc",    "Bagman (Moon Cresta hardware)"},
        {"bagmans",     "Bagman (Stern set 1)"},
        {"bagmans2",    "Bagman (Stern set 2)"},
        {"bagmans4",    "Bagman (Stern Electronics, revision A4)"},
        {"bagnard",     "Le Bagnard"},
        {"bagnarda",    "Le Bagnard (set 2)"},
        {"bagnardi",    "Le Bagnard (Itisa, Spain)"},
        {"bagnardio",   "Le Bagnard (Itisa, Spain, older)"},
        {"bakatono",    "Bakatonosama Mahjong Manyuki"},
        {"bakubaku",    "Baku Baku Animal"},
        {"bakubrkr",    "Bakuretsu Breaker"},
        {"bakuhatu",    "Mahjong Bakuhatsu Junjouden (Japan)"},
        {"bakutotu",    "Bakutotsu Kijuutei"},
        {"balcube",     "Bal Cube"},
        {"ballbomb",    "Balloon Bomber"},
        {"ballboy",     "Ball Boy (2 players)"},
        {"ballboy3p",   "Ball Boy (3 players)"},
        {"ballbros",    "Balloon Brothers"},
        {"balonfgt",    "Vs. Balloon Fight"},
        {"baluba",      "Baluba-louk no Densetsu"},
        {"bananadr",    "Mahjong Banana Dream [BET] (Japan 891124)"},
        {"bandido",     "Bandido"},
        {"bang",        "Bang!"},
        {"bangball",    "Bang Bang Ball (v1.05)"},
        {"bangbead",    "Bang Bead"},
        {"bangj",       "Gun Gabacho (Japan)"},
        {"bankp",       "Bank Panic"},
        {"bankpt",      "Bank Panic (Tecfri bootleg)"},
        {"baracuda",    "Barracuda"},
        {"baraduka",    "Baraduke (set 2)"},
        {"baraduke",    "Baraduke (set 1)"},
        {"barek2ch",    "Bare Knuckle II (Chinese bootleg of Megadrive version)"},
        {"barek3mb",    "Bare Knuckle III (bootleg of Megadrive version)"},
        {"barekch",     "Bare Knuckle (Chinese bootleg of Mega Drive version)"},
        {"barricad",    "Barricade"},
        {"barrier",     "Barrier"},
        {"baryon",      "Baryon - Future Assault"},
        {"baryona",     "Baryon - Future Assault (set 2)"},
        {"basebal2",    "Baseball The Season II"},
        {"basketbal",   "Basket Ball (8-way joystick bootleg of Arch Rivals)"},
        {"bass",        "Sega Bass Fishing"},
        {"basschal",    "Sega Bass Fishing Challenge Version A"},
        {"basschalo",   "Sega Bass Fishing Challenge"},
        {"bassdx",      "Sega Bass Fishing Deluxe (USA)"},
        {"batcir",      "Battle Circuit (Euro 970319)"},
        {"batcira",     "Battle Circuit (Asia 970319)"},
        {"batcird",     "Battle Circuit (Europe 970319 Phoenix Edition) (bootleg)"},
        {"batcirj",     "Battle Circuit (Japan 970319)"},
        {"batlball",    "Battle Balls (Germany, newer)"},
        {"batlballa",   "Battle Balls (Hong Kong)"},
        {"batlballe",   "Battle Balls (Hong Kong, earlier)"},
        {"batlballo",   "Battle Balls (Germany, earlier)"},
        {"batlballpt",  "Battle Balls (Portugal)"},
        {"batlballu",   "Battle Balls (US)"},
        {"batlbubl",    "Battle Bubble (v2.00)"},
        {"batlzone",    "Battle Zone (bootleg of Mayday)"},
        {"batman",      "Batman"},
        {"batman2",     "Batman Part 2"},
        {"batmanfr",    "Batman Forever"},
        {"batrider",    "Armed Police Batrider (Japan, version B)"},
        {"batriderc",   "Armed Police Batrider (China) (Fri Feb 13 1998)"},
        {"batriderhk",  "Armed Police Batrider (Hong Kong) (Mon Dec 22 1997)"},
        {"batriderj",   "Armed Police Batrider (Japan, B version) (Fri Feb 13 1998)"},
        {"batriderja",  "Armed Police Batrider (Japan, older version) (Mon Dec 22 1997)"},
        {"batriderk",   "Armed Police Batrider (Korea) (Fri Feb 13 1998)"},
        {"batridert",   "Armed Police Batrider (Taiwan) (Mon Dec 22 1997)"},
        {"batrideru",   "Armed Police Batrider (USA) (Fri Feb 13 1998)"},
        {"batridra",    "Armed Police Batrider (Japan, version A)"},
        {"batridrk",    "Armed Police Batrider (Korea, version B)"},
        {"batsugun",    "Batsugun"},
        {"batsuguna",   "Batsugun (older, set 1)"},
        {"batsugunb",   "Batsugun (Korean PCB)"},
        {"batsugunbl",  "Batsugun (bootleg)"},
        {"batsugunc",   "Batsugun (older, set 2)"},
        {"batsugunsp",  "Batsugun - Special Version"},
        {"battlan2",    "Battle Lane! Vol. 5 (set 2)"},
        {"battlan3",    "Battle Lane! Vol. 5 (set 3)"},
        {"battlane",    "Battle Lane! Vol. 5 (set 1)"},
        {"battlane2",   "Battle Lane! Vol. 5 (set 2)"},
        {"battlane3",   "Battle Lane! Vol. 5 (set 3)"},
        {"battlcry",    "Battlecry"},
        {"battlcryc",   "Battlecry (Version C)"},
        {"battlcryp",   "Battlecry (Prototype)"},
        {"battleg",     "Battle Garegga - Type 2 (Denmark - China) (Tue Apr 2 1996)"},
        {"battlega",    "Battle Garegga (Europe - USA - Japan - Asia) (Sat Feb 3 1996)"},
        {"battlegb",    "Battle Garegga (Austria - Hong Kong) (Sat Mar 2 1996)"},
        {"battlera",    "Battle Rangers (World)"},
        {"battles",     "Battles"},
        {"battles2",    "Battles (set 2)"},
        {"battlex",     "Battle Cross"},
        {"battlntj",    "Battlantis (Japan)"},
        {"battlnts",    "Battlantis"},
        {"battlntsa",   "Battlantis (program code F)"},
        {"battlntsj",   "Battlantis (Japan, program code E)"},
        {"battroad",    "The Battle-Road"},
        {"batugnsp",    "Batsugun (Special Ver.)"},
        {"batwings",    "Battle Wings (alt)"},
        {"bayrouta",    "Bay Route (set 2)"},
        {"bayroute",    "Bay Route (set 1)"},
        {"bayrouted",   "Bay Route (set 3, World) (bootleg of FD1094 317-0116 set)"},
        {"bayroutej",   "Bay Route (set 2, Japan) (FD1094 317-0115)"},
        {"bayroutejd",  "Bay Route (set 2, Japan) (bootleg of FD1094 317-0115 set)"},
        {"bayrtbl1",    "Bay Route (bootleg set 1)"},
        {"bayrtbl2",    "Bay Route (bootleg set 2)"},
        {"bbakradu",    "Battle Bakraid - Unlimited version (Japan) (Tue Jun 8 1999)"},
        {"bbakraid",    "Battle Bakraid (Japan) (Wed Apr 7 1999)"},
        {"bbakraidc",   "Battle Bakraid - Unlimited Version (China) (Tue Jun 8 1999)"},
        {"bbakraidj",   "Battle Bakraid - Unlimited Version (Japan) (Tue Jun 8 1999)"},
        {"bbakraidja",  "Battle Bakraid (Japan) (Wed Apr 7 1999)"},
        {"bballoon",    "BnB Arcade"},
        {"bballs",      "Bouncing Balls"},
        {"bballsa",     "Bouncing Balls (Adult)"},
        {"bbbxing",     "Best Bout Boxing"},
        {"bbh",         "Big Buck Hunter (v1.00.14)"},
        {"bbh2sp",      "Big Buck Hunter II - Sportsman's Paradise (v2.02.11)"},
        {"bbh2spa",     "Big Buck Hunter II - Sportsman's Paradise (v2.02.09)"},
        {"bbh2spb",     "Big Buck Hunter II - Sportsman's Paradise (v2.02.08)"},
        {"bbhcotw",     "Big Buck Hunter Call of the Wild (v3.02.5)"},
        {"bbhsc",       "Big Buck Hunter - Shooter's Challenge (v1.60.01)"},
        {"bbhsca",      "Big Buck Hunter - Shooter's Challenge (v1.50.07)"},
        {"bbmanw",      "Bomber Man World (World)"},
        {"bbmanwj",     "Bomber Man World (Japan)"},
        {"bbmanwja",    "Bomber Man World (Japan, revised sound hardware)"},
        {"bbonk",       "Bigfoot Bonkers"},
        {"bbprot",      "Untitled Fighter 'BB' (prototype)"},
        {"bbredux",     "Bubble Bobble ('bootleg redux' hack for Bobble Bobble PCB)"},
        {"bbros",       "Buster Bros. (US)"},
        {"bbusters",    "Beast Busters (World [Q])"},
        {"bbustersj",   "Beast Busters (Japan, Version 2, 3 Player)"},
        {"bbustersja",  "Beast Busters (Japan, Version 2, 2 Player)"},
        {"bbustersu",   "Beast Busters (US, Version 3)"},
        {"bbustersua",  "Beast Busters (US, Version 2)"},
        {"bchopper",    "Battle Chopper"},
        {"bcrusher",    "Bone Crusher"},
        {"bcruzm12",    "Battle Cruiser M-12"},
        {"bcstry",      "B.C. Story (set 1)"},
        {"bcstrya",     "B.C. Story (set 2)"},
        {"bdrdown",     "Border Down (Rev A) (GDL-0023A)"},
        {"beachspi",    "Beach Spikers (GDS-0014)"},
        {"beaminv",     "Beam Invader"},
        {"beastf",      "Beastie Feastie"},
        {"beastfp",     "Beastie Feastie (Pac-Man conversion)"},
        {"beastrzb",    "Beastorizer (bootleg)"},
        {"beastrzr",    "Beastorizer"},
        {"beathead",    "BeatHead (prototype)"},
        {"beezer",      "Beezer (set 1)"},
        {"beezer1",     "Beezer (set 2)"},
        {"bel",         "Behind Enemy Lines"},
        {"benberob",    "Ben Bero Beh (Japan)"},
        {"berabohm",    "Beraboh Man (Japan version C)"},
        {"berabohmb",   "Chou Zetsurinjin Berabowman (Japan, Rev B)"},
        {"beraboho",    "Beraboh Man (Japan version B)"},
        {"berlwall",    "The Berlin Wall (set 1)"},
        {"berlwallk",   "The Berlin Wall (Korea)"},
        {"berlwallt",   "The Berlin Wall (bootleg?)"},
        {"berlwalt",    "The Berlin Wall (set 2)"},
        {"bermudaa",    "Bermuda Triangle (US older version)"},
        {"bermudao",    "Bermuda Triangle (Japan old version)"},
        {"bermudat",    "Bermuda Triangle (Japan)"},
        {"bermudata",   "Bermuda Triangle (World Wars) (US)"},
        {"bermudatj",   "Bermuda Triangle (Japan)"},
        {"berzerk",     "Berzerk (set 1)"},
        {"berzerk1",    "Berzerk (set 2)"},
        {"berzerka",    "Berzerk (revision RC31)"},
        {"berzerkb",    "Berzerk (revision RC28)"},
        {"berzerkf",    "Berzerk (French Speech, revision RC31)"},
        {"berzerkg",    "Berzerk (German Speech, revision RC32)"},
        {"berzerks",    "Berzerk (Spanish Speech, revision RC32)"},
        {"bestbest",    "Best Of Best"},
        {"bestleag",    "Best League (bootleg of Big Striker, Italian Serie A)"},
        {"bestleaw",    "Best League (bootleg of Big Striker, World Cup)"},
        {"bestri",      "Bestri (Korea, set 1)"},
        {"bestria",     "Bestri (Korea, set 2)"},
        {"bgaregga",    "Battle Garegga (Europe / USA / Japan / Asia) (Sat Feb 3 1996)"},
        {"bgareggabl",  "1945 Er Dai / 1945 Part-2 (Chinese hack of Battle Garegga)"},
        {"bgareggabla", "Leishen Chuan / Thunder Deity Biography (Chinese hack of Battle Garegga)"},
        {"bgareggablj", "Battle Garegga (Japan, bootleg) (Sat Feb 3 1996)"},
        {"bgareggacn",  "Battle Garegga - Type 2 (Denmark / China) (Tue Apr 2 1996)"},
        {"bgareggahk",  "Battle Garegga (Austria / Hong Kong) (Sat Feb 3 1996)"},
        {"bgareggak",   "Battle Garegga (Korea / Greece) (Wed Feb 7 1996)"},
        {"bgaregganv",  "Battle Garegga - New Version (Austria / Hong Kong) (Sat Mar 2 1996)"},
        {"bgareggat",   "Battle Garegga (location test) (Wed Jan 17 1996)"},
        {"bgareggat2",  "Battle Garegga - Type 2 (Europe / USA / Japan / Asia) (Sat Mar 2 1996)"},
        {"bgareggatw",  "Battle Garegga (Taiwan / Germany) (Thu Feb 1 1996)"},
        {"bigbang",     "Big Bang (9th Nov. 1993)"},
        {"bigbanga",    "Big Bang (9th Nov. 1993, set 2)"},
        {"bigbucks",    "Big Bucks"},
        {"bigevglf",    "Big Event Golf"},
        {"bigevglfj",   "Big Event Golf (Japan)"},
        {"bigfghtr",    "Tatakae! Big Fighter (Japan)"},
        {"bigfight",    "Big Fight - Big Trouble In The Atlantic Ocean"},
        {"bigfightj",   "Big Fight - Big Trouble In The Atlantic Ocean (Japan, rev F)"},
        {"bigjoke",     "The Big Joke (Version 0.00)"},
        {"bigkarnk",    "Big Karnak"},
        {"bigkong",     "Big Kong"},
        {"bigkonggx",   "Big Kong (bootleg of Crazy Kong on Galaxian hardware)"},
        {"bigprowr",    "The Big Pro Wrestling!"},
        {"bigprowra",   "The Big Pro Wrestling! (set 2)"},
        {"bigrun",      "Big Run (11th Rallye version)"},
        {"bigrunu",     "Big Run (11th Rallye version, US?)"},
        {"bigstrik",    "Big Striker"},
        {"bigstrkb",    "Big Striker (bootleg)"},
        {"bigstrkba",   "Big Striker (bootleg w/Italian teams)"},
        {"bigtwin",     "Big Twin"},
        {"bigtwinb",    "Big Twin (No Girls Conversion)"},
        {"bijokkog",    "Bijokko Gakuen (Japan 880116)"},
        {"bijokkoy",    "Bijokko Yume Monogatari (Japan 870925)"},
        {"bikkuri",     "Bikkuri Pro Wrestling (Japan 881221, Ver 1.05)"},
        {"bikkuric",    "Bikkuri Card (Japan)"},
        {"billiard",    "The Billiards"},
        {"billlist",    "Billard List"},
        {"bilyard",     "Billiard"},
        {"bioatack",    "Bio Attack"},
        {"biofreak",    "BioFreaks (prototype)"},
        {"biomtoy",     "Biomechanical Toy (unprotected)"},
        {"biomtoya",    "Biomechanical Toy (ver. 1.0.1884, checksum 3f316c70)"},
        {"biomtoyb",    "Biomechanical Toy (ver. 1.0.1878, checksum d84b28ff)"},
        {"biomtoyc",    "Biomechanical Toy (ver. 1.0.1870, checksum ba682195)"},
        {"bionicc",     "Bionic Commando (US set 1)"},
        {"bionicc1",    "Bionic Commando (US set 1)"},
        {"bionicc2",    "Bionic Commando (US set 2)"},
        {"bioniccbl",   "Bionic Commandos (bootleg, set 1)"},
        {"bioniccbl2",  "Bionic Commandos (bootleg, set 2)"},
        {"bioplayc",    "Bioplaything Cop (ver. 1.0.1823, checksum cd960fc9, prototype)"},
        {"bioship",     "Bio-ship Paladin"},
        {"birdiy",      "Birdiy"},
        {"birdtry",     "Birdie Try (Japan)"},
        {"birdtrya",    "Birdie Try (Japan, revision 2)"},
        {"birdtryb",    "Birdie Try (Japan, sample version)"},
        {"bishi",       "Bishi Bashi Championship Mini Game Senshuken (ver JAA, 3 Players)"},
        {"bjourney",    "Blue's Journey / Raguy"},
        {"bjourneyh",   "Blue's Journey / Raguy (ALH-001)"},
        {"bjtwin",      "Bomb Jack Twin"},
        {"bjtwina",     "Bombjack Twin (set 2)"},
        {"bjtwinp",     "Bombjack Twin (prototype? with adult pictures, set 1)"},
        {"bjtwinpa",    "Bombjack Twin (prototype? with adult pictures, set 2)"},
        {"bking",       "Birdie King"},
        {"bking2",      "Birdie King 2"},
        {"bking3",      "Birdie King 3"},
        {"bkrtmaq",     "Bakuretsu Quiz Ma-Q Dai Bouken (Japan)"},
        {"bktigerb",    "Black Tiger (bootleg)"},
        {"black",       "Czernyj Korabl (Arcade bootleg of ZX Spectrum 'Blackbeard')"},
        {"blackt96",    "Black Touch '96"},
        {"bladestl",    "Blades of Steel (version T)"},
        {"bladestle",   "Blades of Steel (version E, Trackball)"},
        {"bladestll",   "Blades of Steel (version L, Trackball)"},
        {"bladstle",    "Blades of Steel (version E)"},
        {"blandia",     "Blandia"},
        {"blandiap",    "Blandia (prototype)"},
        {"blasted",     "Blasted"},
        {"blaster",     "Blaster"},
        {"blasterkit",  "Blaster (conversion kit)"},
        {"blastero",    "Blaster (location test)"},
        {"blastkit",    "Blaster (kit)"},
        {"blasto",      "Blasto"},
        {"blastoff",    "Blast Off (Japan)"},
        {"blazeon",     "Blaze On (Japan)"},
        {"blazeonj",    "Blaze On (Japan)"},
        {"blazer",      "Blazer (Japan)"},
        {"blazlaz",     "Blazing Lazers (United Amusements PC Engine)"},
        {"blazstar",    "Blazing Star"},
        {"blckgalb",    "Block Gal (bootleg)"},
        {"blckout2",    "Block Out (set 2)"},
        {"blckoutj",    "Block Out (Japan)"},
        {"bldwolf",     "Bloody Wolf (US)"},
        {"bldwolfj",    "Narazumono Sentoubutai Bloody Wolf (Japan)"},
        {"blitz",       "NFL Blitz"},
        {"blitz2k",     "NFL Blitz 2000"},
        {"blitz99",     "NFL Blitz '99"},
        {"blitz99a",    "NFL Blitz '99 (ver 1.2, Aug 28 1998)"},
        {"blkbustr",    "BlockBuster"},
        {"blkdrgon",    "Black Dragon"},
        {"blkdrgonb",   "Black Dragon (bootleg)"},
        {"blkhearj",    "Black Heart (Japan)"},
        {"blkheart",    "Black Heart"},
        {"blkheartj",   "Black Heart (Japan)"},
        {"blkhole",     "Black Hole"},
        {"blkpnthr",    "Black Panther"},
        {"blktiger",    "Black Tiger"},
        {"blktigera",   "Black Tiger (older)"},
        {"blktigerb1",  "Black Tiger (bootleg set 1)"},
        {"blktigerb2",  "Black Tiger (bootleg set 2)"},
        {"blktigerb3",  "Black Tiger / Black Dragon (mixed bootleg?)"},
        {"blktouch",    "Black Touch (Korea)"},
        {"blmbycar",    "Blomby Car"},
        {"blmbycaru",   "Blomby Car (Version 1P0, not encrypted)"},
        {"blmbycau",    "Blomby Car (not encrypted)"},
        {"block",       "Block Block (World 911106 Joystick)"},
        {"block2",      "Block 2 (S.P.A. Co. bootleg)"},
        {"blocka",      "Block Block (World 910910)"},
        {"blockade",    "Blockade"},
        {"blockbl",     "Block Block (bootleg)"},
        {"blockcar",    "Block Carnival - Thunder and Lightning 2"},
        {"blockcarb",   "Block Carnival / Thunder & Lightning 2 (bootleg)"},
        {"blocken",     "Blocken (Japan)"},
        {"blockgal",    "Block Gal"},
        {"blockgalb",   "Block Gal (bootleg)"},
        {"blockhl",     "Block Hole"},
        {"blockj",      "Block Block (Japan 910910)"},
        {"blockout",    "Block Out (set 1)"},
        {"blockout2",   "Block Out (set 2)"},
        {"blockout3",   "Block Out (Europe and Oceania)"},
        {"blockoutj",   "Block Out (Japan)"},
        {"blockr1",     "Block Block (World 911106 Joystick)"},
        {"blockr2",     "Block Block (World 910910)"},
        {"blokpong",    "Block Pong-Pong"},
        {"bloodbro",    "Blood Bros."},
        {"bloodbroj",   "Blood Bros. (Japan, rev A)"},
        {"bloodbroja",  "Blood Bros. (Japan)"},
        {"bloodbrok",   "Blood Bros. (Korea)"},
        {"bloodbrou",   "Blood Bros. (US)"},
        {"bloods11",    "Blood Storm (v1.10)"},
        {"bloods21",    "Blood Storm (v2.10)"},
        {"bloods22",    "Blood Storm (v2.20)"},
        {"bloodstm",    "Blood Storm (v2.22)"},
        {"bloodstm104", "Blood Storm (v1.04)"},
        {"bloodstm110", "Blood Storm (v1.10)"},
        {"bloodstm210", "Blood Storm (v2.10)"},
        {"bloodstm220", "Blood Storm (v2.20)"},
        {"bloodstm221", "Blood Storm (v2.21)"},
        {"bloodwar",    "Blood Warrior"},
        {"bloxeed",     "Bloxeed"},
        {"bloxeeda",    "Bloxeed (Japan, earlier) (FD1094 317-0139)"},
        {"bloxeedc",    "Bloxeed (C System)"},
        {"bloxeedd",    "Bloxeed (Japan) (bootleg of FD1094 317-0139 set)"},
        {"bloxeedu",    "Bloxeed (US, C System, Rev A)"},
        {"blsthead",    "Blasteroids (with heads)"},
        {"blstroi2",    "Blasteroids (rev 2)"},
        {"blstroi3",    "Blasteroids (rev 3)"},
        {"blstroid",    "Blasteroids (rev 4)"},
        {"blstroid2",   "Blasteroids (rev 2)"},
        {"blstroid3",   "Blasteroids (rev 3)"},
        {"blstroidg",   "Blasteroids (German, rev 2)"},
        {"blstroidh",   "Blasteroids (with heads)"},
        {"blstroig",    "Blasteroids (German, rev 2)"},
        {"blswhstl",    "Bells and Whistles (Version L)"},
        {"blswhstla",   "Bells & Whistles (Asia, version M)"},
        {"bluehawk",    "Blue Hawk"},
        {"bluehawkn",   "Blue Hawk (Japan, NTC license)"},
        {"bluehawn",    "Blue Hawk (NTC)"},
        {"blueprnj",    "Blue Print (Jaleco)"},
        {"blueprnt",    "Blue Print (Midway)"},
        {"blueprntj",   "Blue Print (Jaleco)"},
        {"blueshrk",    "Blue Shark"},
        {"blueshrkmr",  "Blue Shark (Model Racing bootleg, set 1)"},
        {"blueshrkmr2", "Blue Shark (Model Racing bootleg, set 2)"},
        {"blzntrnd",    "Blazing Tornado"},
        {"bm1stmix",    "beatmania (ver JA-B)"},
        {"bm2ndmix",    "beatmania 2nd MIX (ver JA-B)"},
        {"bm2ndmxa",    "beatmania 2nd MIX (ver JA-A)"},
        {"bm3",         "Beatmania III"},
        {"bm36th",      "Beatmania III Append 6th Mix"},
        {"bm37th",      "Beatmania III Append 7th Mix"},
        {"bm3core",     "Beatmania III Append Core Remix"},
        {"bm3final",    "Beatmania III The Final"},
        {"bm3rdeaa",    "beatmania 3rd MIX (ver EA-A)"},
        {"bm3rdmix",    "beatmania 3rd MIX (ver JA-A)"},
        {"bm4thmix",    "beatmania 4th MIX (ver JA-A)"},
        {"bm5thmix",    "beatmania 5th MIX (ver JA-A)"},
        {"bm6thmix",    "beatmania 6th MIX (ver JA-A)"},
        {"bm7thmix",    "beatmania 7th MIX (ver JA-B)"},
        {"bmaster",     "Blade Master (World)"},
        {"bmcbowl",     "Konkyuu no Hoshi"},
        {"bmclubmx",    "beatmania Club MIX (ver JA-A)"},
        {"bmcmxaac",    "beatmania complete MIX (ver AA-C)"},
        {"bmcompm2",    "beatmania complete MIX 2 (ver JA-A)"},
        {"bmcompmx",    "beatmania complete MIX (ver JA-B)"},
        {"bmcompmxb",   "beatmania complete MIX (ver JA-B)"},
        {"bmcorerm",    "beatmania CORE REMIX (ver JA-A)"},
        {"bmdct",       "beatmania f. Dreams Come True (ver JA-A)"},
        {"bmfinal",     "beatmania THE FINAL (ver JA-A)"},
        {"bmxstunts",   "BMX Stunts"},
        {"bnglngby",    "Vs. Raid on Bungeling Bay (Japan)"},
        {"bnj",         "Bump 'n' Jump"},
        {"bnjm",        "Bump 'n' Jump (Midway)"},
        {"bnzabros",    "Bonanza Bros"},
        {"bnzabrosj",   "Bonanza Bros (Japan, Floppy DS3-5000-07b Based)"},
        {"boblbobl",    "Bobble Bobble"},
        {"boblcave",    "Bubble Bobble: Lost Cave V1.2 (for Bobble Bobble PCB)"},
        {"bodyslam",    "Body Slam"},
        {"bogeyman",    "Bogey Manor"},
        {"boggy84",     "Boggy '84"},
        {"boggy84b",    "Boggy '84 (bootleg, set 1)"},
        {"bombbee",     "Bomb Bee"},
        {"bomber",      "Bomber (bootleg of Scramble)"},
        {"bombjac2",    "Bomb Jack (set 2)"},
        {"bombjack",    "Bomb Jack (set 1)"},
        {"bombjack2",   "Bomb Jack (earlier)"},
        {"bombjackbl",  "Bomb Jack (bootleg)"},
        {"bombjackt",   "Bomb Jack (Tecfri, Spain)"},
        {"bombkick",    "Bomb Kick"},
        {"bombkicka",   "Bomb Kick (set 2)"},
        {"bomblord",    "Bomber Lord (bootleg)"},
        {"bombrman",    "Bomberman (Japan)"},
        {"bombsa",      "Bombs Away (prototype)"},
        {"bongo",       "Bongo"},
        {"bongog",      "Bongo (Galaxian hardware)"},
        {"bonkadv",     "Bonk's Adventure"},
        {"bonzeadu",    "Bonze Adventure (US)"},
        {"bonzeadv",    "Bonze Adventure (World)"},
        {"bonzeadvo",   "Bonze Adventure (World)"},
        {"bonzeadvp",   "Bonze Adventure (World, prototype, newer)"},
        {"bonzeadvp2",  "Bonze Adventure (World, prototype, older)"},
        {"bonzeadvu",   "Bonze Adventure (US, rev 1)"},
        {"boobhack",    "Booby Kids (Italian manufactured graphic hack / bootleg of Kid no Hore Hore Daisakusen (bootleg))"},
        {"boogwing",    "Boogie Wings (Euro v1.5)"},
        {"boogwinga",   "Boogie Wings (Asia v1.5)"},
        {"boogwingu",   "Boogie Wings (USA v1.7, 92.12.14)"},
        {"boomrang",    "Boomer Rang'r - Genesis"},
        {"boomranga",   "Boomer Rang'r / Genesis (set 2)"},
        {"boonggab",    "Boong-Ga Boong-Ga (Spank'em!)"},
        {"bootcamp",    "Boot Camp"},
        {"boothill",    "Boot Hill"},
        {"borench",     "Borench"},
        {"borencha",    "Borench (set 2)"},
        {"borenchj",    "Borench (Japan)"},
        {"borntofi",    "Born To Fight"},
        {"borntofia",   "Born To Fight (set 2)"},
        {"borntofiv",   "Born To Fight (Vifico license)"},
        {"bosco",       "Bosconian (new version)"},
        {"bosco1",      "Bosconian - Star Destroyer (version 1, newer)"},
        {"bosco1o",     "Bosconian - Star Destroyer (version 1, older)"},
        {"bosco3",      "Bosconian - Star Destroyer (version 3)"},
        {"boscomd",     "Bosconian (Midway, new version)"},
        {"boscomdo",    "Bosconian (Midway, old version)"},
        {"boscoo",      "Bosconian (old version)"},
        {"boscoo2",     "Bosconian (older version)"},
        {"botanic",     "Botanic (English / Spanish, set 1)"},
        {"botanic2",    "Botanic (English / Spanish, Bagman conversion)"},
        {"botanicf",    "Botanic (French)"},
        {"botss",       "Battle of the Solar System (rev. 1.1a 7/23/92)"},
        {"botss11",     "Battle of the Solar System (rev. 1.1 3/24/92)"},
        {"bottom9",     "Bottom of the Ninth (version T)"},
        {"bottom9n",    "Bottom of the Ninth (version N)"},
        {"bouldash",    "Boulder Dash - Boulder Dash Part 2 (World)"},
        {"bouldashj",   "Boulder Dash / Boulder Dash Part 2 (Japan)"},
        {"bouldshj",    "Boulder Dash - Boulder Dash Part 2 (Japan)"},
        {"bounty",      "The Bounty"},
        {"bowler",      "4 Player Bowling Alley"},
        {"bowlrama",    "Bowl-O-Rama"},
        {"bowmen",      "Bowmen"},
        {"boxer",       "Boxer (prototype)"},
        {"boxingb",     "Boxing Bugs"},
        {"boxyboy",     "Boxy Boy (US)"},
        {"boxyboya",    "Boxy Boy (SB?)"},
        {"bradley",     "Bradley Trainer"},
        {"brain",       "Brain"},
        {"brapboys",    "B.Rap Boys (World)"},
        {"brapboysj",   "B.Rap Boys Special (Japan)"},
        {"brapboysp",   "B.Rap Boys Special (World, newer)"},
        {"brapboysp2",  "B.Rap Boys Special (World, older)"},
        {"brapboyspj",  "B.Rap Boys Special (Japan)"},
        {"brapboyspu",  "B.Rap Boys Special (US)"},
        {"brdrlinb",    "Borderline (bootleg)"},
        {"brdrline",    "Borderline"},
        {"brdrlinet",   "Borderline (Tranquillizer Gun conversion)"},
        {"brdrlins",    "Borderline (Sidam bootleg)"},
        {"breakers",    "Breakers"},
        {"breakout",    "Breakout"},
        {"breakrev",    "Breakers Revenge"},
        {"breywood",    "Breywood (Japan revision 2)"},
        {"brickyrd",    "Brickyard"},
        {"brickzn",     "Brick Zone (v5.0)"},
        {"brickzn11",   "Brick Zone (v1.1, Spinner)"},
        {"brickzn3",    "Brick Zone (v3.0)"},
        {"brickznv4",   "Brick Zone (v4.0, Spinner)"},
        {"brickznv5",   "Brick Zone (v5.0, Joystick)"},
        {"brival",      "Burning Rival (Japan)"},
        {"brivalj",     "Burning Rival (Japan)"},
        {"brix",        "Brix"},
        {"brixian",     "Brixian"},
        {"brkball",     "Break Ball"},
        {"brkblast",    "Brick Blast (bootleg of Wall Crash)"},
        {"brkthru",     "Break Thru (US)"},
        {"brkthrubl",   "Break Thru (bootleg)"},
        {"brkthruj",    "Kyohkoh-Toppa (Japan)"},
        {"brkthrut",    "Break Thru (Tecfri license)"},
        {"brningfh",    "Burning Fight (AES)"},
        {"brningfp",    "Burning Fight (proto older)"},
        {"brnngfpa",    "Burning Fight (prototype)"},
        {"brod",        "Brodjaga (Arcade bootleg of ZX Spectrum 'Inspector Gadget and the Circus of Fear')"},
        {"bronx",       "Bronx"},
        {"brubber",     "Burnin' Rubber"},
        {"brutforc",    "Brute Force"},
        {"brvblade",    "Brave Blade (JAPAN)"},
        {"bs4thmix",    "beatstage 4th MIX (ver KA-A)"},
        {"bscompmx",    "beatstage complete MIX (ver KA-B)"},
        {"bsebman",     "Bomberman (Version 6.6)"},
        {"bshark",      "Battle Shark (US)"},
        {"bsharkj",     "Battle Shark (Japan)"},
        {"bsharkjjs",   "Battle Shark (Japan, Joystick)"},
        {"bsharku",     "Battle Shark (US)"},
        {"bsktball",    "Basketball"},
        {"bssoccer",    "Back Street Soccer"},
        {"bssoccera",   "Back Street Soccer (KRB-0032A PCB)"},
        {"bstars",      "Baseball Stars Professional"},
        {"bstars2",     "Baseball Stars 2"},
        {"bstarsh",     "Baseball Stars Professional (AES)"},
        {"btime",       "Burger Time (Data East set 1)"},
        {"btime2",      "Burger Time (Data East set 2)"},
        {"btime3",      "Burger Time (Data East USA)"},
        {"btimem",      "Burger Time (Midway)"},
        {"btlecity",    "Vs. Battle City"},
        {"btlfield",    "Battle Field (Japan)"},
        {"btlfieldb",   "Battle Field (bootleg)"},
        {"btlkroad",    "Battle K-Road"},
        {"btlkroadk",   "Battle K-Road (Korea)"},
        {"btoads",      "Battle Toads"},
        {"bub68705",    "Bubble Bobble (bootleg with 68705)"},
        {"bubblem",     "Bubble Memories - The Story Of Bubble Bobble 3 (World)"},
        {"bubblemj",    "Bubble Memories - The Story Of Bubble Bobble 3 (Japan)"},
        {"bubblemu",    "Bubble Memories: The Story Of Bubble Bobble III (Ver 2.5A 1996/02/21)"},
        {"bubbles",     "Bubbles"},
        {"bubblesp",    "Bubbles (prototype version)"},
        {"bubblesr",    "Bubbles (Solid Red label)"},
        {"bubbletr",    "Bubble Trouble - Golly! Ghost! 2 (World, Rev B)"},
        {"bubbletrj",   "Bubble Trouble - Golly! Ghost! 2 (Japan, Rev C)"},
        {"bubbobr1",    "Bubble Bobble (US)"},
        {"bubl2000",    "Bubble 2000"},
        {"bubl2000a",   "Bubble 2000 V1.2"},
        {"bublbob1",    "Bubble Bobble (older)"},
        {"bublbob2",    "Bubble Bobble 2 (World)"},
        {"bublbob2o",   "Bubble Bobble II (Ver 2.5O 1994/10/05)"},
        {"bublbob2p",   "Bubble Bobble 2 (prototype)"},
        {"bublbobl",    "Bubble Bobble"},
        {"bublbobl1",   "Bubble Bobble (Japan, Ver 0.0)"},
        {"bublboblb",   "Bubble Bobble (for Bobble Bobble PCB)"},
        {"bublboblp",   "Bubble Bobble (prototype on Tokio hardware)"},
        {"bublboblr",   "Bubble Bobble (US, Ver 5.1)"},
        {"bublboblr1",  "Bubble Bobble (US, Ver 1.0)"},
        {"bublboblu",   "Bubble Bobble (Ultra Version)(USA)"},
        {"bublbobr",    "Bubble Bobble (US with mode select)"},
        {"bublbust",    "Bubble Buster (USA, B-System)"},
        {"bublcave",    "Bubble Bobble: Lost Cave V1.2"},
        {"bublcave10",  "Bubble Bobble: Lost Cave V1.0"},
        {"bublcave11",  "Bubble Bobble: Lost Cave V1.1"},
        {"bublpong",    "Bubble Pong Pong"},
        {"bubsympe",    "Bubble Symphony (Europe)"},
        {"bubsymph",    "Bubble Symphony (Japan)"},
        {"bubsymphe",   "Bubble Symphony (Ver 2.5O 1994/10/05)"},
        {"bubsymphj",   "Bubble Symphony (Ver 2.5J 1994/10/05)"},
        {"bubsymphu",   "Bubble Symphony (Ver 2.5A 1994/10/05)"},
        {"bubsympu",    "Bubble Symphony (US)"},
        {"bucaner",     "Buccaneer (set 1)"},
        {"bucanera",    "Buccaneer (set 2)"},
        {"buccanrs",    "Buccaneers (set 1)"},
        {"buccanrsa",   "Buccaneers (set 2)"},
        {"buccanrsb",   "Buccaneers (set 3, harder)"},
        {"buckrog",     "Buck Rogers - Planet of Zoom"},
        {"buckrogn",    "Buck Rogers - Planet of Zoom (not encrypted)"},
        {"bucky",       "Bucky O'Hare (World version EA)"},
        {"buckyaa",     "Bucky O'Hare (ver AA)"},
        {"buckyaab",    "Bucky O'Hare (ver AAB)"},
        {"buckyea",     "Bucky O'Hare (ver EA)"},
        {"buckyjaa",    "Bucky O'Hare (ver JAA)"},
        {"buckyua",     "Bucky O'Hare (US version UA)"},
        {"buckyuab",    "Bucky O'Hare (ver UAB)"},
        {"buggyboy",    "Buggy Boy/Speed Buggy (cockpit, rev. D)"},
        {"buggyboyb",   "Buggy Boy/Speed Buggy (cockpit, rev. B)"},
        {"buggyboyjr",  "Buggy Boy Junior/Speed Buggy (upright)"},
        {"buggychl",    "Buggy Challenge"},
        {"buggychlt",   "Buggy Challenge (Tecfri)"},
        {"buggycht",    "Buggy Challenge (Tecfri)"},
        {"bullet",      "Bullet (FD1094 317-0041)"},
        {"bulletd",     "Bullet (unprotected of FD1094 317-0041 set)"},
        {"bullfgt",     "Bullfight"},
        {"bullfgtr",    "Bull Fighter"},
        {"buraiken",    "Hissatsu Buraiken (Japan)"},
        {"buraikenb",   "Hissatsu Buraiken (Japan, bootleg)"},
        {"burgkids",    "Burger Kids (Japan)"},
        {"burglarx",    "Burglar X"},
        {"burnforc",    "Burning Force (Japan)"},
        {"burnforco",   "Burning Force (Japan, old version)"},
        {"burningf",    "Burning Fight (set 1)"},
        {"burningfh",   "Burning Fight (NGH-018, US)"},
        {"burningfp",   "Burning Fight (prototype, older)"},
        {"burningfpa",  "Burning Fight (prototype, near final, ver 23.3, 910326)"},
        {"burningfpb",  "Burning Fight (prototype, newer, V07)"},
        {"burningh",    "Burning Fight (set 2)"},
        {"butasan",     "Butasan (Japan)"},
        {"butasanj",    "Butasan (Japan, Japanese)"},
        {"buttobi",     "Buttobi Striker"},
        {"buzzard",     "Buzzard"},
        {"bwcasino",    "Boardwalk Casino"},
        {"bwidow",      "Black Widow"},
        {"bwing",       "B-Wings (Japan)"},
        {"bwings",      "Battle Wings"},
        {"bwingsa",     "B-Wings (Alt Ver.?)"},
        {"bwingso",     "B-Wings (Japan old Ver.)"},
        {"bygone",      "Bygone (prototype)"},
        {"bzone",       "Battle Zone (set 1)"},
        {"bzone2",      "Battle Zone (set 2)"},
        {"bzonea",      "Battle Zone (rev 1)"},
        {"bzonec",      "Battle Zone (cocktail)"},
};

const char *lookup_b(const char *name) {
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_b(const char *value) {
    for (size_t i = 0; i < sizeof(lookup_table) / sizeof(lookup_table[0]); i++) {
        if (strcmp(lookup_table[i].value, value) == 0) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
