#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"labyrunk",    "Labyrinth Runner (World Ver. K)"},
        {"labyrunr",    "Labyrinth Runner (Japan)"},
        {"labyrunrk",   "Labyrinth Runner (World Ver. K)"},
        {"ladybug",     "Lady Bug"},
        {"ladybugb",    "Lady Bug (bootleg)"},
        {"ladybugb2",   "Coccinelle (bootleg of Lady Bug)"},
        {"ladybugg",    "Ladybug (bootleg on Galaxian hardware)"},
        {"ladyfrog",    "Lady Frog"},
        {"ladygolf",    "Vs. Stroke and Match Golf (Ladies Version)"},
        {"ladygolfe",   "Vs. Stroke & Match Golf (Ladies Version, set LG4 E)"},
        {"ladykill",    "Lady Killer"},
        {"ladymstr",    "Lady Master of Kung Fu (rev 1)"},
        {"ladymstra",   "Lady Master of Kung Fu"},
        {"lagirl",      "LA Girl"},
        {"lagunar",     "Laguna Racer"},
        {"lamachin",    "L.A. Machineguns (Japan)"},
        {"landbrk",     "Land Breaker"},
        {"landbrka",    "Land Breaker (World) / Miss Tang Ja Ru Gi (Korea) (pcb ver 3.03) (AT89c52 protected)"},
        {"landbrkb",    "Land Breaker (World) / Miss Tang Ja Ru Gi (Korea) (pcb ver 1.0) (AT89c52 protected)"},
        {"landgear",    "Landing Gear (Ver 4.2 O)"},
        {"landgeara",   "Landing Gear (Ver 3.1 O)"},
        {"landgearj",   "Landing Gear (Ver 4.2 J)"},
        {"landgearja",  "Landing Gear (Ver 3.0 J)"},
        {"landmakr",    "Land Maker (Japan)"},
        {"landmakrj",   "Land Maker (Ver 2.01J 1998/06/01)"},
        {"landmakrp",   "Land Maker (Ver 2.02O 1998/06/02, prototype)"},
        {"landmkrp",    "Land Maker (World Prototype)"},
        {"lans2004",    "Lansquenet 2004 (bootleg of Shock Troopers - 2nd Squad)"},
        {"laser",       "Laser"},
        {"laserbas",    "Laser Base (set 1)"},
        {"laserbasa",   "Laser Base (set 2)"},
        {"laserbat",    "Laser Battle"},
        {"lasso",       "Lasso"},
        {"lastapos",    "The Last Apostle Puppetshow"},
        {"lastblad",    "Last Blade / Bakumatsu Roman - Gekka no Kenshi, The (set 1)"},
        {"lastbladh",   "The Last Blade / Bakumatsu Roman - Gekka no Kenshi (NGH-2340)"},
        {"lastbld2",    "Last Blade 2 / Bakumatsu Roman - Dai Ni Maku Gekka no Kenshi, The"},
        {"lastblda",    "Last Blade / Bakumatsu Roman - Gekka no Kenshi, The (set 2)"},
        {"lastbrnx",    "Last Bronx (Export, Revision A)"},
        {"lastbrnxj",   "Last Bronx: Tokyo Bangaichi (Japan, Revision A)"},
        {"lastbrnxu",   "Last Bronx (USA, Revision A)"},
        {"lastday",     "The Last Day (set 1)"},
        {"lastdaya",    "The Last Day (set 2)"},
        {"lastduel",    "Last Duel (US set 1)"},
        {"lastduelb",   "Last Duel (bootleg)"},
        {"lastduelj",   "Last Duel (Japan)"},
        {"lastduelo",   "Last Duel (US Old Ver.)"},
        {"lastfero",    "Last Fortress - Toride (Erotic)"},
        {"lastfort",    "Last Fortress - Toride"},
        {"lastforte",   "Last Fortress - Toride (China, Rev C)"},
        {"lastfortea",  "Last Fortress - Toride (China, Rev A)"},
        {"lastfortg",   "Last Fortress - Toride (Germany)"},
        {"lastfortj",   "Last Fortress - Toride (Japan, VG460 PCB)"},
        {"lastfortk",   "Last Fortress - Toride (Korea)"},
        {"lasthope",    "Last Hope"},
        {"lastkm",      "Last KM (ver 1.0.0275, checksum 13bff751, prototype)"},
        {"lastmisn",    "Last Mission (US revision 6)"},
        {"lastmisnj",   "Last Mission (Japan)"},
        {"lastmisnu5",  "Last Mission (US revision 5)"},
        {"lastmisnu6",  "Last Mission (US revision 6)"},
        {"lastmsnj",    "Last Mission (Japan)"},
        {"lastmsno",    "Last Mission (US revision 5)"},
        {"lastsold",    "The Last Soldier (Korean release of The Last Blade)"},
        {"laststar",    "The Last Starfighter (prototype)"},
        {"lastsurv",    "Last Survivor (Japan) (FD1094 317-0083)"},
        {"lastsurvd",   "Last Survivor (Japan) (bootleg of FD1094 317-0083 set)"},
        {"lazarian",    "Lazarian"},
        {"lazercmd",    "Lazer Command"},
        {"lbgrande",    "Libero Grande (World, LG2/VER.A)"},
        {"lbowling",    "League Bowling"},
        {"ldrun",       "Lode Runner (set 1)"},
        {"ldrun2",      "Lode Runner II - The Bungeling Strikes Back"},
        {"ldrun3",      "Lode Runner III - The Golden Labyrinth"},
        {"ldrun3j",     "Lode Runner III - Majin no Fukkatsu (Japan)"},
        {"ldrun3jp",    "Lode Runner III - Majin No Fukkatsu"},
        {"ldrun4",      "Lode Runner IV - Teikoku Karano Dasshutsu"},
        {"ldruna",      "Lode Runner (set 2)"},
        {"le2",         "Lethal Enforcers II - Gun Fighters (ver EAA)"},
        {"le2u",        "Lethal Enforcers II - Gun Fighters (ver UAA)"},
        {"leadang",     "Lead Angle (Japan)"},
        {"leaguemn",    "Yakyuu Kakutou League-Man (Japan)"},
        {"leaguemna",   "Yakyuu Kakutou League-Man (Japan, set 2)"},
        {"leds2011",    "Led Storm Rally 2011 (World)"},
        {"leds2011p",   "Led Storm Rally 2011 (US, prototype 12)"},
        {"leds2011u",   "Led Storm Rally 2011 (US)"},
        {"ledstorm",    "Led Storm (US)"},
        {"legend",      "Legend"},
        {"legendb",     "Legion (bootleg of Legend)"},
        {"legendoh",    "Legend of Heroes"},
        {"legendos",    "Legend of Success Joe / Ashitano Joe Densetsu"},
        {"legendsb",    "Legend (SNES bootleg)"},
        {"legion",      "Legion - Spinner-87 (World ver 2.03)"},
        {"legionj",     "Chouji Meikyuu Legion (Japan ver 1.05, set 1)"},
        {"legionj2",    "Chouji Meikyuu Legion (Japan ver 1.05, set 2)"},
        {"legionjb",    "Chouji Meikyuu Legion (Japan ver 1.05, bootleg set 1)"},
        {"legionjb2",   "Chouji Meikyuu Legion (Japan ver 1.05, bootleg set 2)"},
        {"legionna",    "Legionnaire (World)"},
        {"legionnaj",   "Legionnaire (Japan)"},
        {"legionnau",   "Legionnaire (US)"},
        {"legionnu",    "Legionnaire (US)"},
        {"legiono",     "Chouji Meikyuu Legion (Japan bootleg ver 1.05)"},
        {"legofair",    "Koukuu Kihei Monogatari - The Legend of Air Cavalry (Japan)"},
        {"lemans24",    "Le Mans 24 (Japan, Revision B)"},
        {"lemmings",    "Lemmings (US Prototype)"},
        {"lemnangl",    "Mahjong Lemon Angel (Japan)"},
        {"lependu",     "Le Pendu (Bilingue, Version 04)"},
        {"leprechn",    "Leprechaun"},
        {"leprechna",   "Leprechaun (set 2)"},
        {"lespendu",    "Le Super Pendu (V1, words set #1)"},
        {"lespenduj",   "Le Super Pendu (V1, words set #2)"},
        {"lethalen",    "Lethal Enforcers (ver UAE)"},
        {"lethaleneaa", "Lethal Enforcers (ver EAA, 09/09/92 09:44)"},
        {"lethaleneab", "Lethal Enforcers (ver EAB, 10/14/92 19:53)"},
        {"lethalenead", "Lethal Enforcers (ver EAD, 11/11/92 10:52)"},
        {"lethaleneae", "Lethal Enforcers (ver EAE, 11/19/92 16:24)"},
        {"lethalenj",   "Lethal Enforcers (ver JAD, 12/04/92 17:16)"},
        {"lethalenua",  "Lethal Enforcers (ver UAA, 08/17/92 21:38)"},
        {"lethalenub",  "Lethal Enforcers (ver UAB, 09/01/92 11:12)"},
        {"lethalenux",  "Lethal Enforcers (ver unknown, US, 08/06/92 15:11, hacked/proto?)"},
        {"lethalj",     "Lethal Justice"},
        {"lethalth",    "Lethal Thunder (World)"},
        {"levers",      "Levers"},
        {"lghost",      "Laser Ghost"},
        {"lghostd",     "Laser Ghost (World) (bootleg of FD1094 317-0166 set)"},
        {"lghostj",     "Laser Ghost (Japan) (FD1094 317-0164)"},
        {"lghostu",     "Laser Ghost (US) (FD1094 317-0165)"},
        {"lghostud",    "Laser Ghost (US) (bootleg of FD1094 317-0165 set)"},
        {"lgtnfght",    "Lightning Fighters (US)"},
        {"lgtnfghta",   "Lightning Fighters (Asia)"},
        {"lgtnfghtu",   "Lightning Fighters (US)"},
        {"liberat2",    "Liberator (set 2)"},
        {"liberatb",    "Liberation (bootleg)"},
        {"liberate",    "Liberation"},
        {"liberateb",   "Liberation (bootleg)"},
        {"liberatr",    "Liberator (set 1)"},
        {"liberatrp",   "Liberator (prototype)"},
        {"liblrabl",    "Libble Rabble"},
        {"lifefrce",    "Lifeforce (US)"},
        {"lifefrcej",   "Lifeforce (Japan)"},
        {"lifefrcj",    "Lifeforce (Japan)"},
        {"lightbr",     "Light Bringer (Japan)"},
        {"lightbrj",    "Light Bringer (Ver 2.1J 1994/02/18)"},
        {"linkypip",    "Linky Pipe"},
        {"liquidk",     "Liquid Kids (World)"},
        {"liquidku",    "Liquid Kids (US)"},
        {"lithero",     "Little Hero"},
        {"littlerb",    "Little Robin"},
        {"livequiz",    "Live Quiz Show"},
        {"lizwiz",      "Lizard Wizard"},
        {"lkage",       "The Legend of Kage"},
        {"lkagea",      "The Legend of Kage (rev 1)"},
        {"lkageb",      "The Legend of Kage (bootleg set 1)"},
        {"lkageb2",     "The Legend of Kage (bootleg set 2)"},
        {"lkageb3",     "The Legend of Kage (bootleg set 3)"},
        {"lkagebl1",    "The Legend of Kage (bootleg set 1)"},
        {"lkagebl2",    "The Legend of Kage (bootleg set 2)"},
        {"lkagebl3",    "The Legend of Kage (bootleg set 3)"},
        {"lkagebl4",    "The Legend of Kage (bootleg set 4)"},
        {"lkagem",      "The Legend of Kage (rev 2, MSM5232 sound)"},
        {"llander",     "Lunar Lander (rev 2)"},
        {"llander1",    "Lunar Lander (rev 1)"},
        {"llandert",    "Lunar Lander (screen test)"},
        {"lnc",         "Lock'n'Chase"},
        {"lockload",    "Locked 'n Loaded (US)"},
        {"lockon",      "Lock-On (rev. E)"},
        {"lockonc",     "Lock-On (rev. C)"},
        {"lockonph",    "Lock On (Philko)"},
        {"locoboot",    "Loco-Motion (bootleg)"},
        {"locomotn",    "Loco-Motion"},
        {"loderdfa",    "Lode Runner - The Dig Fight (ver. A)"},
        {"loderndf",    "Lode Runner - The Dig Fight (ver. B)"},
        {"loderndfa",   "Lode Runner - The Dig Fight (ver. A)"},
        {"loffire",     "Line of Fire"},
        {"loffired",    "Line of Fire / Bakudan Yarou (World) (bootleg of FD1094 317-0136 set)"},
        {"loffirej",    "Line of Fire / Bakudan Yarou (Japan) (FD1094 317-0134)"},
        {"loffirejd",   "Line of Fire / Bakudan Yarou (Japan) (bootleg of FD1094 317-0134 set)"},
        {"loffireu",    "Line of Fire / Bakudan Yarou (US) (FD1094 317-0135)"},
        {"loffireud",   "Line of Fire / Bakudan Yarou (US) (bootleg of FD1094 317-0135 set)"},
        {"logger",      "Logger"},
        {"loggerr2",    "Logger (Rev.2)"},
        {"logicpr2",    "Logic Pro 2 (Japan)"},
        {"logicpro",    "Logic Pro (Japan)"},
        {"loht",        "Legend of Hero Tonma"},
        {"lohtb2",      "Legend of Hero Tonma (Japan, bootleg with i8751)"},
        {"lohtb3",      "Legend of Hero Tonma (World, bootleg with i8751)"},
        {"lohtj",       "Legend of Hero Tonma (Japan)"},
        {"lomakai",     "Legend of Makai (World)"},
        {"looper",      "Looper"},
        {"looping",     "Looping (set 1)"},
        {"loopinga",    "Looping (set 2)"},
        {"loopingv",    "Looping (Venture Line license, set 1)"},
        {"loopingva",   "Looping (Venture Line license, set 2)"},
        {"lordgun",     "Lord of Gun (World)"},
        {"lordgunu",    "Lord of Gun (USA)"},
        {"lordofk",     "The Lord of King (Japan)"},
        {"lordofkb",    "The Lord of King (bootleg, not protected)"},
        {"lordofkbp",   "The Lord of King (bootleg, protected)"},
        {"losttmbh",    "Lost Tomb (hard)"},
        {"losttomb",    "Lost Tomb (easy)"},
        {"losttombh",   "Lost Tomb (hard)"},
        {"lostwrld",    "Lost Worlds (Japan)"},
        {"lostwrldo",   "Lost Worlds (Japan Old Ver.)"},
        {"lostwsga",    "The Lost World: Jurassic Park (Japan, Revision A)"},
        {"lostwsgo",    "The Lost World (older)"},
        {"lostwsgp",    "The Lost World: Jurassic Park (location test)"},
        {"lotlot",      "Lot Lot"},
        {"lottofun",    "Lotto Fun"},
        {"loverboy",    "Lover Boy"},
        {"lrescue",     "Lunar Rescue"},
        {"lresort",     "Last Resort"},
        {"lresortp",    "Last Resort (prototype)"},
        {"lsasquad",    "Land Sea Air Squad - Riku Kai Kuu Saizensen"},
        {"lstduela",    "Last Duel (US set 2)"},
        {"lstduelb",    "Last Duel (bootleg)"},
        {"ltcasin2",    "Little Casino 2"},
        {"ltcasin2b",   "Little Casino II (v17.0)"},
        {"ltcasino",    "Little Casino"},
        {"ltcasinoa",   "Little Casino (set 2)"},
        {"ltswords",    "Lightning Swords (World)"},
        {"luckboom",    "Lucky Boom"},
        {"luckboomh",   "Lucky Boom (Hard Times hardware)"},
        {"luckycoin",   "Lucky Coin (Jun 24 2002)"},
        {"luckywld",    "Lucky and Wild"},
        {"luckywldj",   "Lucky & Wild (Japan)"},
        {"lufykzku",    "Otakara Itadaki Luffy Kaizoku-Dan! (Japan, v1.02)"},
        {"lunarba1",    "Lunar Battle (prototype, earlier)"},
        {"lunarbat",    "Lunar Battle (prototype, later)"},
        {"lupin3",      "Lupin III"},
        {"lupinsho",    "Lupin The Third - The Shooting (Rev A) (GDS-0018A)"},
        {"lupinshoo",   "Lupin The Third - The Shooting (GDS-0018)"},
        {"luplup",      "Lup Lup Puzzle / Zhuan Zhuan Puzzle (version 3.0 / 990128)"},
        {"luplup10",    "Lup Lup Puzzle / Zhuan Zhuan Puzzle (version 1.05 / 981214)"},
        {"luplup29",    "Lup Lup Puzzle / Zhuan Zhuan Puzzle (version 2.9 / 990108)"},
        {"luptype",     "Lupin The Third - The Typing (Rev A) (GDS-0021A)"},
        {"lvgirl94",    "Las Vegas Girl (Girl '94)"},
        {"lwings",      "Legendary Wings (US set 1)"},
        {"lwings2",     "Legendary Wings (US set 2)"},
        {"lwingsa",     "Legendary Wings (US)"},
        {"lwingsb",     "Legendary Wings (bootleg)"},
        {"lwingsj",     "Ares no Tsubasa (Japan, rev. B)"},
        {"lwingsja",    "Ares no Tsubasa (Japan, rev. A)"},
        {"lwingsjp",    "Ares no Tsubasa (Japan)"},
};

const char *lookup_l(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_l(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
