#!/bin/sh

set -eu

HERE=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
OUT="${1:-$HERE/common/thirdparty.h}"

EXTERNAL_VERSION() {
	sed -n 's/^VERSION="\([^"]*\)".*/\1/p' "$HERE/external/$1.sh" | head -1
}

MACRO_VERSION() {
	FILE=$1
	shift

	OUT_VER=""

	for MACRO in "$@"; do
		PART=$(sed -n "s/^#define[[:space:]]*${MACRO}[[:space:]]*\([0-9][0-9]*\).*/\1/p" "$FILE" | head -1)
		[ -n "$PART" ] || return 0
		OUT_VER="${OUT_VER:+$OUT_VER.}$PART"
	done

	printf '%s' "$OUT_VER"
}

STRING_VERSION() {
	sed -n "s/^#define[[:space:]]*$2[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$1" | head -1
}

ROWS=$(
	printf '%s\t%s\n' "FFmpeg" "$(EXTERNAL_VERSION ffmpeg)"
	printf '%s\t%s\n' "json.c" ""
	printf '%s\t%s\n' "libarchive" "$(EXTERNAL_VERSION libarchive)"
	printf '%s\t%s\n' "LVGL" "$(MACRO_VERSION "$HERE/lvgl/lvgl.h" LVGL_VERSION_MAJOR LVGL_VERSION_MINOR LVGL_VERSION_PATCH)"
	printf '%s\t%s\n' "minic" ""
	printf '%s\t%s\n' "miniz" "$(STRING_VERSION "$HERE/common/miniz/miniz.h" MZ_VERSION)"
	printf '%s\t%s\n' "Mojibake" "$(EXTERNAL_VERSION mojibake)"
	printf '%s\t%s\n' "OpenSSL" "$(EXTERNAL_VERSION openssl)"
	printf '%s\t%s\n' "PlutoSVG" "$(MACRO_VERSION "$HERE/plutosvg/source/plutosvg.h" PLUTOSVG_VERSION_MAJOR PLUTOSVG_VERSION_MINOR PLUTOSVG_VERSION_MICRO)"
	printf '%s\t%s\n' "PlutoVG" "$(MACRO_VERSION "$HERE/plutosvg/plutovg/include/plutovg.h" PLUTOVG_VERSION_MAJOR PLUTOVG_VERSION_MINOR PLUTOVG_VERSION_MICRO)"
	printf '%s\t%s\n' "rcheevos" "$(EXTERNAL_VERSION rcheevos)"
	printf '%s\t%s\n' "stb_image_write" "1.16"
	printf '%s\t%s\n' "stb_rect_pack" "1.01"
	printf '%s\t%s\n' "stb_truetype" "1.26"
	printf '%s\t%s\n' "xxHash" "$(MACRO_VERSION "$HERE/common/xxhash/xxhash.h" XXH_VERSION_MAJOR XXH_VERSION_MINOR XXH_VERSION_RELEASE)"
)

{
	echo "#pragma once"
	echo
	echo "// Generated by gen_thirdparty.sh - do not edit"
	echo
	echo "struct third_party_lib {"
	echo "    const char *name;"
	echo "    const char *version;"
	echo "};"
	echo
	echo "static const struct third_party_lib third_party_libs[] = {"

	printf '%s\n' "$ROWS" | LC_ALL=C sort -f | while IFS="$(printf '\t')" read -r NAME VERSION; do
		[ -n "$NAME" ] || continue
		[ -n "$VERSION" ] || VERSION="-"
		printf '    {"%s", "%s"},\n' "$NAME" "$VERSION"
	done

	echo "};"
} >"$OUT.tmp"

if [ -f "$OUT" ] && cmp -s "$OUT" "$OUT.tmp"; then
	rm -f "$OUT.tmp"
	exit 0
fi

mv "$OUT.tmp" "$OUT"
printf 'Wrote %s\n' "$OUT"
