// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxapp

#ifndef _MUXAPP_UI_H
#define _MUXAPP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrApp
void ui_screen_init(lv_obj_t * ui_screen);
extern lv_obj_t * ui_lblAppMessage;

void ui_init(lv_obj_t * ui_screen);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
