// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxrtc

#ifndef _MUXRTC_UI_H
#define _MUXRTC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrRTC
void ui_screen_init(lv_obj_t * ui_pnlContent);
extern lv_obj_t * ui_pnlYear;
extern lv_obj_t * ui_pnlMonth;
extern lv_obj_t * ui_pnlDay;
extern lv_obj_t * ui_pnlHour;
extern lv_obj_t * ui_pnlMinute;
extern lv_obj_t * ui_pnlNotation;
extern lv_obj_t * ui_pnlTimezone;
extern lv_obj_t * ui_lblYear;
extern lv_obj_t * ui_lblMonth;
extern lv_obj_t * ui_lblDay;
extern lv_obj_t * ui_lblHour;
extern lv_obj_t * ui_lblMinute;
extern lv_obj_t * ui_lblNotation;
extern lv_obj_t * ui_lblTimezone;
extern lv_obj_t * ui_icoYear;
extern lv_obj_t * ui_icoMonth;
extern lv_obj_t * ui_icoDay;
extern lv_obj_t * ui_icoHour;
extern lv_obj_t * ui_icoMinute;
extern lv_obj_t * ui_icoNotation;
extern lv_obj_t * ui_icoTimezone;
extern lv_obj_t * ui_lblYearValue;
extern lv_obj_t * ui_lblMonthValue;
extern lv_obj_t * ui_lblDayValue;
extern lv_obj_t * ui_lblHourValue;
extern lv_obj_t * ui_lblMinuteValue;
extern lv_obj_t * ui_lblNotationValue;
extern lv_obj_t * ui_lblTimezoneValue;

void ui_init(lv_obj_t * ui_pnlContent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
