// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxrtc

#include "ui.h"

void ui_scrRTC_screen_init(void)
{
    ui_scrRTC = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrRTC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrRTC, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrRTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrRTC, &ui_font_NotoSans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlWall = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlWall, 640);
    lv_obj_set_height(ui_pnlWall, 480);
    lv_obj_set_align(ui_pnlWall, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlWall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlWall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlWall, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlWall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWall = lv_img_create(ui_pnlWall);
    lv_img_set_src(ui_imgWall, &ui_img_nothing_png);
    lv_obj_set_width(ui_imgWall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgWall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWall, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlBox = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlBox, 640);
    lv_obj_set_height(ui_pnlBox, 400);
    lv_obj_set_align(ui_pnlBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlBox, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBox = lv_img_create(ui_pnlBox);
    lv_img_set_src(ui_imgBox, &ui_img_nothing_png);
    lv_obj_set_width(ui_imgBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBox, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgBox, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlHeader = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlHeader, 640);
    lv_obj_set_height(ui_pnlHeader, 42);
    lv_obj_set_align(ui_pnlHeader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHeader, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHeader, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDatetime = lv_label_create(ui_pnlHeader);
    lv_obj_set_height(ui_lblDatetime, 42);
    lv_obj_set_width(ui_lblDatetime, LV_SIZE_CONTENT);   /// 1
    lv_label_set_long_mode(ui_lblDatetime, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblDatetime, "");
    lv_obj_add_flag(ui_lblDatetime, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblDatetime, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDatetime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblDatetime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblDatetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblDatetime, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblDatetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTitle = lv_label_create(ui_pnlHeader);
    lv_obj_set_width(ui_lblTitle, 630);
    lv_obj_set_height(ui_lblTitle, 42);
    lv_obj_set_align(ui_lblTitle, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_lblTitle, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblTitle, "DATE AND TIME");
    lv_obj_add_flag(ui_lblTitle, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblTitle, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTitle, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conGlyphs = lv_obj_create(ui_pnlHeader);
    lv_obj_remove_style_all(ui_conGlyphs);
    lv_obj_set_width(ui_conGlyphs, 110);
    lv_obj_set_height(ui_conGlyphs, 42);
    lv_obj_set_align(ui_conGlyphs, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_conGlyphs, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_conGlyphs, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_conGlyphs, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_conGlyphs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_conGlyphs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_conGlyphs, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_conGlyphs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_conGlyphs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_staBluetooth = lv_label_create(ui_conGlyphs);
    lv_obj_set_width(ui_staBluetooth, 20);
    lv_obj_set_height(ui_staBluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_staBluetooth, -220);
    lv_obj_set_y(ui_staBluetooth, -205);
    lv_label_set_text(ui_staBluetooth, "");
    lv_obj_set_style_text_color(ui_staBluetooth, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_staBluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_staBluetooth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_staBluetooth, &ui_font_AwesomeBrand, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_staBluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_staBluetooth, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_staBluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_staBluetooth, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_staNetwork = lv_label_create(ui_conGlyphs);
    lv_obj_set_width(ui_staNetwork, 30);
    lv_obj_set_height(ui_staNetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_staNetwork, -220);
    lv_obj_set_y(ui_staNetwork, -205);
    lv_label_set_text(ui_staNetwork, "");
    lv_obj_set_style_text_color(ui_staNetwork, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_staNetwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_staNetwork, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_staNetwork, &ui_font_Awesome, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_staNetwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_staNetwork, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_staNetwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_staNetwork, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_staCapacity = lv_label_create(ui_conGlyphs);
    lv_obj_set_width(ui_staCapacity, 35);
    lv_obj_set_height(ui_staCapacity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_staCapacity, -220);
    lv_obj_set_y(ui_staCapacity, -205);
    lv_label_set_text(ui_staCapacity, "");
    lv_obj_set_style_text_color(ui_staCapacity, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_staCapacity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_staCapacity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_staCapacity, &ui_font_AwesomeBig, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_staCapacity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_staCapacity, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_staCapacity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_staCapacity, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlContent = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlContent, 640);
    lv_obj_set_height(ui_pnlContent, 400);
    lv_obj_set_x(ui_pnlContent, 0);
    lv_obj_set_y(ui_pnlContent, 34);
    lv_obj_set_align(ui_pnlContent, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlContent, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_pnlContent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_pnlContent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlContent, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlContent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlContent, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblYear = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblYear, 640);
    lv_obj_set_height(ui_lblYear, 28);
    lv_obj_set_x(ui_lblYear, 100);
    lv_obj_set_y(ui_lblYear, -70);
    lv_obj_set_align(ui_lblYear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblYear, "Year");
    lv_obj_set_style_text_color(ui_lblYear, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblYear, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblYear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblYear, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblYear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblYear, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblYear, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblYear, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblYear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblYear, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblYear, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblYear, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblYear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblYear, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblYear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblYear, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblYear, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblYear, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblYear, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblYear, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblYear, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblMonth = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblMonth, 640);
    lv_obj_set_height(ui_lblMonth, 28);
    lv_obj_set_x(ui_lblMonth, 100);
    lv_obj_set_y(ui_lblMonth, -70);
    lv_obj_set_align(ui_lblMonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMonth, "Month");
    lv_obj_set_style_text_color(ui_lblMonth, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblMonth, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblMonth, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblMonth, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblMonth, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblMonth, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblMonth, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblMonth, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblMonth, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMonth, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblMonth, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblMonth, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblMonth, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblMonth, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblMonth, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblMonth, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblDay = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblDay, 640);
    lv_obj_set_height(ui_lblDay, 28);
    lv_obj_set_x(ui_lblDay, 100);
    lv_obj_set_y(ui_lblDay, -70);
    lv_obj_set_align(ui_lblDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDay, "Day");
    lv_obj_set_style_text_color(ui_lblDay, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblDay, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblDay, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblDay, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblDay, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblDay, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblDay, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblDay, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblDay, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblDay, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblDay, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblDay, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblDay, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblDay, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblDay, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblDay, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblHour = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblHour, 640);
    lv_obj_set_height(ui_lblHour, 28);
    lv_obj_set_x(ui_lblHour, 100);
    lv_obj_set_y(ui_lblHour, -70);
    lv_obj_set_align(ui_lblHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHour, "Hour");
    lv_obj_set_style_text_color(ui_lblHour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblHour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblHour, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblHour, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblHour, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblHour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblHour, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblHour, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblHour, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblHour, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblHour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblHour, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblHour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblHour, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblHour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblHour, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblMinute = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblMinute, 640);
    lv_obj_set_height(ui_lblMinute, 28);
    lv_obj_set_x(ui_lblMinute, 100);
    lv_obj_set_y(ui_lblMinute, -70);
    lv_obj_set_align(ui_lblMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMinute, "Minute");
    lv_obj_set_style_text_color(ui_lblMinute, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblMinute, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblMinute, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblMinute, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblMinute, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblMinute, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblMinute, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblMinute, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblMinute, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMinute, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblMinute, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblMinute, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblMinute, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblMinute, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblMinute, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblMinute, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblNotation = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblNotation, 640);
    lv_obj_set_height(ui_lblNotation, 28);
    lv_obj_set_x(ui_lblNotation, 100);
    lv_obj_set_y(ui_lblNotation, -70);
    lv_obj_set_align(ui_lblNotation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNotation, "Time Notation");
    lv_obj_set_style_text_color(ui_lblNotation, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNotation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblNotation, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblNotation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblNotation, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblNotation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblNotation, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblNotation, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblNotation, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblNotation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblNotation, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblNotation, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNotation, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNotation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNotation, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNotation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblNotation, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblNotation, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblNotation, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblNotation, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblNotation, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblNotation, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblTimezone = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblTimezone, 640);
    lv_obj_set_height(ui_lblTimezone, 28);
    lv_obj_set_x(ui_lblTimezone, 100);
    lv_obj_set_y(ui_lblTimezone, -70);
    lv_obj_set_align(ui_lblTimezone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTimezone, "Set Timezone");
    lv_obj_set_style_text_color(ui_lblTimezone, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimezone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblTimezone, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblTimezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblTimezone, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblTimezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblTimezone, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblTimezone, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblTimezone, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblTimezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblTimezone, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblTimezone, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTimezone, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTimezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTimezone, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTimezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblTimezone, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblTimezone, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblTimezone, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblTimezone, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblTimezone, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblTimezone, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_pnlGlyph = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlGlyph, 640);
    lv_obj_set_height(ui_pnlGlyph, 400);
    lv_obj_set_x(ui_pnlGlyph, 0);
    lv_obj_set_y(ui_pnlGlyph, 34);
    lv_obj_set_align(ui_pnlGlyph, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlGlyph, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_pnlGlyph, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_pnlGlyph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlGlyph, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlGlyph, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlGlyph, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pnlGlyph, &ui_font_AwesomeSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icoYear = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoYear, 32);
    lv_obj_set_height(ui_icoYear, 28);
    lv_obj_set_x(ui_icoYear, 100);
    lv_obj_set_y(ui_icoYear, -70);
    lv_obj_set_align(ui_icoYear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoYear, "");
    lv_obj_set_style_text_color(ui_icoYear, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoYear, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoYear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoYear, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoYear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoYear, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoYear, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoMonth = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoMonth, 32);
    lv_obj_set_height(ui_icoMonth, 28);
    lv_obj_set_x(ui_icoMonth, 100);
    lv_obj_set_y(ui_icoMonth, -70);
    lv_obj_set_align(ui_icoMonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoMonth, "");
    lv_obj_set_style_text_color(ui_icoMonth, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoMonth, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoMonth, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoMonth, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoMonth, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoDay = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoDay, 32);
    lv_obj_set_height(ui_icoDay, 28);
    lv_obj_set_x(ui_icoDay, 100);
    lv_obj_set_y(ui_icoDay, -70);
    lv_obj_set_align(ui_icoDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoDay, "");
    lv_obj_set_style_text_color(ui_icoDay, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoDay, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoDay, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoDay, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoDay, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoHour = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoHour, 32);
    lv_obj_set_height(ui_icoHour, 28);
    lv_obj_set_x(ui_icoHour, 100);
    lv_obj_set_y(ui_icoHour, -70);
    lv_obj_set_align(ui_icoHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoHour, "");
    lv_obj_set_style_text_color(ui_icoHour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoHour, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoHour, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoHour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoHour, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoMinute = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoMinute, 32);
    lv_obj_set_height(ui_icoMinute, 28);
    lv_obj_set_x(ui_icoMinute, 100);
    lv_obj_set_y(ui_icoMinute, -70);
    lv_obj_set_align(ui_icoMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoMinute, "");
    lv_obj_set_style_text_color(ui_icoMinute, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoMinute, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoMinute, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoMinute, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoMinute, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoNotation = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoNotation, 32);
    lv_obj_set_height(ui_icoNotation, 28);
    lv_obj_set_x(ui_icoNotation, 100);
    lv_obj_set_y(ui_icoNotation, -70);
    lv_obj_set_align(ui_icoNotation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoNotation, "");
    lv_obj_set_style_text_color(ui_icoNotation, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoNotation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoNotation, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoNotation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoNotation, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoNotation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoNotation, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoNotation, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoTimezone = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoTimezone, 32);
    lv_obj_set_height(ui_icoTimezone, 28);
    lv_obj_set_x(ui_icoTimezone, 100);
    lv_obj_set_y(ui_icoTimezone, -70);
    lv_obj_set_align(ui_icoTimezone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoTimezone, "");
    lv_obj_set_style_text_color(ui_icoTimezone, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoTimezone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoTimezone, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoTimezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoTimezone, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoTimezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoTimezone, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoTimezone, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_pnlHighlight = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlHighlight, 640);
    lv_obj_set_height(ui_pnlHighlight, 400);
    lv_obj_set_x(ui_pnlHighlight, 0);
    lv_obj_set_y(ui_pnlHighlight, 34);
    lv_obj_set_align(ui_pnlHighlight, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlHighlight, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_pnlHighlight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_pnlHighlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlHighlight, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlHighlight, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlHighlight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblYearValue = lv_label_create(ui_pnlHighlight);
    lv_obj_set_width(ui_lblYearValue, 640);
    lv_obj_set_height(ui_lblYearValue, 28);
    lv_obj_set_x(ui_lblYearValue, 100);
    lv_obj_set_y(ui_lblYearValue, -70);
    lv_obj_set_align(ui_lblYearValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblYearValue, "");
    lv_obj_set_style_text_color(ui_lblYearValue, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblYearValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblYearValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblYearValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblYearValue, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblYearValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblYearValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblYearValue, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblYearValue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblMonthValue = lv_label_create(ui_pnlHighlight);
    lv_obj_set_width(ui_lblMonthValue, 640);
    lv_obj_set_height(ui_lblMonthValue, 28);
    lv_obj_set_x(ui_lblMonthValue, 100);
    lv_obj_set_y(ui_lblMonthValue, -70);
    lv_obj_set_align(ui_lblMonthValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMonthValue, "");
    lv_obj_set_style_text_color(ui_lblMonthValue, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMonthValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblMonthValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblMonthValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMonthValue, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMonthValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMonthValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblMonthValue, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblMonthValue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblDayValue = lv_label_create(ui_pnlHighlight);
    lv_obj_set_width(ui_lblDayValue, 640);
    lv_obj_set_height(ui_lblDayValue, 28);
    lv_obj_set_x(ui_lblDayValue, 100);
    lv_obj_set_y(ui_lblDayValue, -70);
    lv_obj_set_align(ui_lblDayValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDayValue, "");
    lv_obj_set_style_text_color(ui_lblDayValue, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDayValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblDayValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblDayValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblDayValue, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblDayValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblDayValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblDayValue, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblDayValue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblHourValue = lv_label_create(ui_pnlHighlight);
    lv_obj_set_width(ui_lblHourValue, 640);
    lv_obj_set_height(ui_lblHourValue, 28);
    lv_obj_set_x(ui_lblHourValue, 100);
    lv_obj_set_y(ui_lblHourValue, -70);
    lv_obj_set_align(ui_lblHourValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHourValue, "");
    lv_obj_set_style_text_color(ui_lblHourValue, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHourValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblHourValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblHourValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblHourValue, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblHourValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblHourValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblHourValue, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblHourValue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblMinuteValue = lv_label_create(ui_pnlHighlight);
    lv_obj_set_width(ui_lblMinuteValue, 640);
    lv_obj_set_height(ui_lblMinuteValue, 28);
    lv_obj_set_x(ui_lblMinuteValue, 100);
    lv_obj_set_y(ui_lblMinuteValue, -70);
    lv_obj_set_align(ui_lblMinuteValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMinuteValue, "");
    lv_obj_set_style_text_color(ui_lblMinuteValue, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMinuteValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblMinuteValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblMinuteValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMinuteValue, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMinuteValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMinuteValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblMinuteValue, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblMinuteValue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblNotationValue = lv_label_create(ui_pnlHighlight);
    lv_obj_set_width(ui_lblNotationValue, 640);
    lv_obj_set_height(ui_lblNotationValue, 28);
    lv_obj_set_x(ui_lblNotationValue, 100);
    lv_obj_set_y(ui_lblNotationValue, -70);
    lv_obj_set_align(ui_lblNotationValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNotationValue, "");
    lv_obj_set_style_text_color(ui_lblNotationValue, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNotationValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblNotationValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNotationValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNotationValue, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNotationValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNotationValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblNotationValue, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblNotationValue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblTimezoneValue = lv_label_create(ui_pnlHighlight);
    lv_obj_set_width(ui_lblTimezoneValue, 640);
    lv_obj_set_height(ui_lblTimezoneValue, 28);
    lv_obj_set_x(ui_lblTimezoneValue, 100);
    lv_obj_set_y(ui_lblTimezoneValue, -70);
    lv_obj_set_align(ui_lblTimezoneValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTimezoneValue, "");
    lv_obj_set_style_text_color(ui_lblTimezoneValue, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimezoneValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTimezoneValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTimezoneValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTimezoneValue, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTimezoneValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTimezoneValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblTimezoneValue, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblTimezoneValue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_pnlFooter = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlFooter, 640);
    lv_obj_set_height(ui_pnlFooter, 42);
    lv_obj_set_align(ui_pnlFooter, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlFooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlFooter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlFooter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlFooter, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlFooter, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlFooter, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlFooter, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavAGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavAGlyph, 25);
    lv_obj_set_height(ui_lblNavAGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavAGlyph, -220);
    lv_obj_set_y(ui_lblNavAGlyph, -205);
    lv_obj_set_align(ui_lblNavAGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavAGlyph, "⇓");
    lv_label_set_recolor(ui_lblNavAGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavAGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavAGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavAGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavA = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavA, -220);
    lv_obj_set_y(ui_lblNavA, -205);
    lv_obj_set_align(ui_lblNavA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavA, "");
    lv_label_set_recolor(ui_lblNavA, "true");
    lv_obj_set_style_text_color(ui_lblNavA, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavA, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavBGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavBGlyph, 25);
    lv_obj_set_height(ui_lblNavBGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavBGlyph, -220);
    lv_obj_set_y(ui_lblNavBGlyph, -205);
    lv_obj_set_align(ui_lblNavBGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavBGlyph, "⇒");
    lv_label_set_recolor(ui_lblNavBGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavBGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavBGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavBGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavB = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavB, -220);
    lv_obj_set_y(ui_lblNavB, -205);
    lv_obj_set_align(ui_lblNavB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavB, "");
    lv_label_set_recolor(ui_lblNavB, "true");
    lv_obj_set_style_text_color(ui_lblNavB, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavB, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavCGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavCGlyph, 25);
    lv_obj_set_height(ui_lblNavCGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavCGlyph, -220);
    lv_obj_set_y(ui_lblNavCGlyph, -205);
    lv_obj_set_align(ui_lblNavCGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavCGlyph, "⇫");
    lv_label_set_recolor(ui_lblNavCGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavCGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavCGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavCGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavC = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavC, -220);
    lv_obj_set_y(ui_lblNavC, -205);
    lv_obj_set_align(ui_lblNavC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavC, "");
    lv_label_set_recolor(ui_lblNavC, "true");
    lv_obj_set_style_text_color(ui_lblNavC, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavC, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavXGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavXGlyph, 25);
    lv_obj_set_height(ui_lblNavXGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavXGlyph, -220);
    lv_obj_set_y(ui_lblNavXGlyph, -205);
    lv_obj_set_align(ui_lblNavXGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavXGlyph, "⇣");
    lv_label_set_recolor(ui_lblNavXGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavXGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavXGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavXGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavX = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavX, -220);
    lv_obj_set_y(ui_lblNavX, -205);
    lv_obj_set_align(ui_lblNavX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavX, "");
    lv_label_set_recolor(ui_lblNavX, "true");
    lv_obj_set_style_text_color(ui_lblNavX, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavX, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavYGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavYGlyph, 25);
    lv_obj_set_height(ui_lblNavYGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavYGlyph, -220);
    lv_obj_set_y(ui_lblNavYGlyph, -205);
    lv_obj_set_align(ui_lblNavYGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavYGlyph, "⇑");
    lv_label_set_recolor(ui_lblNavYGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavYGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavYGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavYGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavY = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavY, -220);
    lv_obj_set_y(ui_lblNavY, -205);
    lv_obj_set_align(ui_lblNavY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavY, "");
    lv_label_set_recolor(ui_lblNavY, "true");
    lv_obj_set_style_text_color(ui_lblNavY, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavY, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavZGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavZGlyph, 25);
    lv_obj_set_height(ui_lblNavZGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavZGlyph, -220);
    lv_obj_set_y(ui_lblNavZGlyph, -205);
    lv_obj_set_align(ui_lblNavZGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavZGlyph, "⇬");
    lv_label_set_recolor(ui_lblNavZGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavZGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavZGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavZGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavZ = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavZ, -220);
    lv_obj_set_y(ui_lblNavZ, -205);
    lv_obj_set_align(ui_lblNavZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavZ, "");
    lv_label_set_recolor(ui_lblNavZ, "true");
    lv_obj_set_style_text_color(ui_lblNavZ, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavZ, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavMenuGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavMenuGlyph, 27);
    lv_obj_set_height(ui_lblNavMenuGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavMenuGlyph, -220);
    lv_obj_set_y(ui_lblNavMenuGlyph, -205);
    lv_obj_set_align(ui_lblNavMenuGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavMenuGlyph, "⇥");
    lv_label_set_recolor(ui_lblNavMenuGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavMenuGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavMenuGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavMenuGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavMenu = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavMenu, -220);
    lv_obj_set_y(ui_lblNavMenu, -205);
    lv_obj_set_align(ui_lblNavMenu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavMenu, "");
    lv_label_set_recolor(ui_lblNavMenu, "true");
    lv_obj_set_style_text_color(ui_lblNavMenu, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavMenu, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlMessage = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlMessage, 615);
    lv_obj_set_height(ui_pnlMessage, 42);
    lv_obj_set_x(ui_pnlMessage, 0);
    lv_obj_set_y(ui_pnlMessage, -47);
    lv_obj_set_align(ui_pnlMessage, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlMessage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlMessage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlMessage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlMessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlMessage, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlMessage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlMessage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlMessage, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMessage = lv_label_create(ui_pnlMessage);
    lv_obj_set_width(ui_lblMessage, 600);
    lv_obj_set_height(ui_lblMessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMessage, -220);
    lv_obj_set_y(ui_lblMessage, -205);
    lv_obj_set_align(ui_lblMessage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMessage, "");
    lv_label_set_recolor(ui_lblMessage, "true");
    lv_obj_set_style_text_color(ui_lblMessage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblMessage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMessage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMessage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlHelp = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlHelp, 640);
    lv_obj_set_height(ui_pnlHelp, 480);
    lv_obj_set_align(ui_pnlHelp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlHelp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlHelp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHelp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHelp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHelp, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHelp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHelp, 155, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlHelpMessage = lv_obj_create(ui_pnlHelp);
    lv_obj_set_width(ui_pnlHelpMessage, 550);
    lv_obj_set_height(ui_pnlHelpMessage, 385);
    lv_obj_set_align(ui_pnlHelpMessage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pnlHelpMessage, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_pnlHelpMessage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlHelpMessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHelpMessage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHelpMessage, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHelpMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHelpMessage, lv_color_hex(0xF8E008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHelpMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlHelpMessage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlHelpMessage, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlHelpMessage, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlHelpMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHelpHeader = lv_label_create(ui_pnlHelpMessage);
    lv_obj_set_width(ui_lblHelpHeader, 515);
    lv_obj_set_height(ui_lblHelpHeader, 22);
    lv_obj_set_align(ui_lblHelpHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHelpHeader, "%helpheader%");
    lv_obj_set_style_text_color(ui_lblHelpHeader, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHelpHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHelpContent = lv_label_create(ui_pnlHelpMessage);
    lv_obj_set_width(ui_lblHelpContent, 515);
    lv_obj_set_height(ui_lblHelpContent, 308);
    lv_obj_set_align(ui_lblHelpContent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHelpContent, "%helpcontext%");
    lv_obj_set_style_text_color(ui_lblHelpContent, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHelpContent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlProgress = lv_obj_create(ui_scrRTC);
    lv_obj_set_width(ui_pnlProgress, 615);
    lv_obj_set_height(ui_pnlProgress, 42);
    lv_obj_set_x(ui_pnlProgress, 0);
    lv_obj_set_y(ui_pnlProgress, -47);
    lv_obj_set_align(ui_pnlProgress, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlProgress, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlProgress, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlProgress, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlProgress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlProgress, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlProgress, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlProgress, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlProgress, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icoProgress = lv_label_create(ui_pnlProgress);
    lv_obj_set_width(ui_icoProgress, 18);
    lv_obj_set_height(ui_icoProgress, 28);
    lv_obj_set_x(ui_icoProgress, -220);
    lv_obj_set_y(ui_icoProgress, -205);
    lv_obj_set_align(ui_icoProgress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoProgress, "");
    lv_label_set_recolor(ui_icoProgress, "true");
    lv_obj_set_style_text_color(ui_icoProgress, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_icoProgress, &ui_font_AwesomeSmall, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoProgress, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barProgress = lv_bar_create(ui_pnlProgress);
    lv_bar_set_value(ui_barProgress, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barProgress, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barProgress, 550);
    lv_obj_set_height(ui_barProgress, 16);
    lv_obj_set_align(ui_barProgress, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barProgress, lv_color_hex(0x7E730C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barProgress, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barProgress, lv_color_hex(0xF7E318), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barProgress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
