#include "ui_muxsysinfo.h"

lv_obj_t *ui_pnlVersion;
lv_obj_t *ui_pnlDevice;
lv_obj_t *ui_pnlKernel;
lv_obj_t *ui_pnlUptime;
lv_obj_t *ui_pnlCPU;
lv_obj_t *ui_pnlSpeed;
lv_obj_t *ui_pnlGovernor;
lv_obj_t *ui_pnlMemory;
lv_obj_t *ui_pnlTemp;
lv_obj_t *ui_pnlCapacity;
lv_obj_t *ui_pnlVoltage;

lv_obj_t *ui_lblVersion;
lv_obj_t *ui_lblDevice;
lv_obj_t *ui_lblKernel;
lv_obj_t *ui_lblUptime;
lv_obj_t *ui_lblCPU;
lv_obj_t *ui_lblSpeed;
lv_obj_t *ui_lblGovernor;
lv_obj_t *ui_lblMemory;
lv_obj_t *ui_lblTemp;
lv_obj_t *ui_lblCapacity;
lv_obj_t *ui_lblVoltage;

lv_obj_t *ui_icoVersion;
lv_obj_t *ui_icoDevice;
lv_obj_t *ui_icoKernel;
lv_obj_t *ui_icoUptime;
lv_obj_t *ui_icoCPU;
lv_obj_t *ui_icoSpeed;
lv_obj_t *ui_icoGovernor;
lv_obj_t *ui_icoMemory;
lv_obj_t *ui_icoTemp;
lv_obj_t *ui_icoCapacity;
lv_obj_t *ui_icoVoltage;

lv_obj_t *ui_lblVersionValue;
lv_obj_t *ui_lblDeviceValue;
lv_obj_t *ui_lblKernelValue;
lv_obj_t *ui_lblUptimeValue;
lv_obj_t *ui_lblCPUValue;
lv_obj_t *ui_lblSpeedValue;
lv_obj_t *ui_lblGovernorValue;
lv_obj_t *ui_lblMemoryValue;
lv_obj_t *ui_lblTempValue;
lv_obj_t *ui_lblCapacityValue;
lv_obj_t *ui_lblVoltageValue;

void init_muxsysinfo(lv_obj_t *ui_pnlContent) {
    ui_pnlVersion = lv_obj_create(ui_pnlContent);
    ui_pnlDevice = lv_obj_create(ui_pnlContent);
    ui_pnlKernel = lv_obj_create(ui_pnlContent);
    ui_pnlUptime = lv_obj_create(ui_pnlContent);
    ui_pnlCPU = lv_obj_create(ui_pnlContent);
    ui_pnlSpeed = lv_obj_create(ui_pnlContent);
    ui_pnlGovernor = lv_obj_create(ui_pnlContent);
    ui_pnlMemory = lv_obj_create(ui_pnlContent);
    ui_pnlTemp = lv_obj_create(ui_pnlContent);
    ui_pnlCapacity = lv_obj_create(ui_pnlContent);
    ui_pnlVoltage = lv_obj_create(ui_pnlContent);

    ui_lblVersion = lv_label_create(ui_pnlVersion);
    lv_label_set_text(ui_lblVersion, "");
    ui_lblDevice = lv_label_create(ui_pnlDevice);
    lv_label_set_text(ui_lblDevice, "");
    ui_lblKernel = lv_label_create(ui_pnlKernel);
    lv_label_set_text(ui_lblKernel, "");
    ui_lblUptime = lv_label_create(ui_pnlUptime);
    lv_label_set_text(ui_lblUptime, "");
    ui_lblCPU = lv_label_create(ui_pnlCPU);
    lv_label_set_text(ui_lblCPU, "");
    ui_lblSpeed = lv_label_create(ui_pnlSpeed);
    lv_label_set_text(ui_lblSpeed, "");
    ui_lblGovernor = lv_label_create(ui_pnlGovernor);
    lv_label_set_text(ui_lblGovernor, "");
    ui_lblMemory = lv_label_create(ui_pnlMemory);
    lv_label_set_text(ui_lblMemory, "");
    ui_lblTemp = lv_label_create(ui_pnlTemp);
    lv_label_set_text(ui_lblTemp, "");
    ui_lblCapacity = lv_label_create(ui_pnlCapacity);
    lv_label_set_text(ui_lblCapacity, "");
    ui_lblVoltage = lv_label_create(ui_pnlVoltage);
    lv_label_set_text(ui_lblVoltage, "");

    ui_icoVersion = lv_img_create(ui_pnlVersion);
    ui_icoDevice = lv_img_create(ui_pnlDevice);
    ui_icoKernel = lv_img_create(ui_pnlKernel);
    ui_icoUptime = lv_img_create(ui_pnlUptime);
    ui_icoCPU = lv_img_create(ui_pnlCPU);
    ui_icoSpeed = lv_img_create(ui_pnlSpeed);
    ui_icoGovernor = lv_img_create(ui_pnlGovernor);
    ui_icoMemory = lv_img_create(ui_pnlMemory);
    ui_icoTemp = lv_img_create(ui_pnlTemp);
    ui_icoCapacity = lv_img_create(ui_pnlCapacity);
    ui_icoVoltage = lv_img_create(ui_pnlVoltage);

    ui_lblVersionValue = lv_label_create(ui_pnlVersion);
    lv_label_set_text(ui_lblVersionValue, "");
    ui_lblDeviceValue = lv_label_create(ui_pnlDevice);
    lv_label_set_text(ui_lblDeviceValue, "");
    ui_lblKernelValue = lv_label_create(ui_pnlKernel);
    lv_label_set_text(ui_lblKernelValue, "");
    ui_lblUptimeValue = lv_label_create(ui_pnlUptime);
    lv_label_set_text(ui_lblUptimeValue, "");
    ui_lblCPUValue = lv_label_create(ui_pnlCPU);
    lv_label_set_text(ui_lblCPUValue, "");
    ui_lblSpeedValue = lv_label_create(ui_pnlSpeed);
    lv_label_set_text(ui_lblSpeedValue, "");
    ui_lblGovernorValue = lv_label_create(ui_pnlGovernor);
    lv_label_set_text(ui_lblGovernorValue, "");
    ui_lblMemoryValue = lv_label_create(ui_pnlMemory);
    lv_label_set_text(ui_lblMemoryValue, "");
    ui_lblTempValue = lv_label_create(ui_pnlTemp);
    lv_label_set_text(ui_lblTempValue, "");
    ui_lblCapacityValue = lv_label_create(ui_pnlCapacity);
    lv_label_set_text(ui_lblCapacityValue, "");
    ui_lblVoltageValue = lv_label_create(ui_pnlVoltage);
    lv_label_set_text(ui_lblVoltageValue, "");
}
