#include "ui_muxstorage.h"

lv_obj_t *ui_pnlBIOS_storage;
lv_obj_t *ui_pnlCatalogue_storage;
lv_obj_t *ui_pnlName_storage;
lv_obj_t *ui_pnlRetroArch_storage;
lv_obj_t *ui_pnlConfig_storage;
lv_obj_t *ui_pnlCore_storage;
lv_obj_t *ui_pnlCollection_storage_storage;
lv_obj_t *ui_pnlHistory_storage;
lv_obj_t *ui_pnlMusic_storage;
lv_obj_t *ui_pnlSave_storage;
lv_obj_t *ui_pnlScreenshot_storage;
lv_obj_t *ui_pnlTheme_storage;
lv_obj_t *ui_pnlCatalogue_storagePackage;
lv_obj_t *ui_pnlConfig_storagePackage;
lv_obj_t *ui_pnlLanguage_storage;
lv_obj_t *ui_pnlNetwork_storage;
lv_obj_t *ui_pnlSyncthing_storage_storage;
lv_obj_t *ui_pnlUserInit_storage;

lv_obj_t *ui_lblBIOS_storage;
lv_obj_t *ui_lblCatalogue_storage;
lv_obj_t *ui_lblName_storage;
lv_obj_t *ui_lblRetroArch_storage;
lv_obj_t *ui_lblConfig_storage;
lv_obj_t *ui_lblCore_storage;
lv_obj_t *ui_lblCollection_storage_storage;
lv_obj_t *ui_lblHistory_storage;
lv_obj_t *ui_lblMusic_storage;
lv_obj_t *ui_lblSave_storage;
lv_obj_t *ui_lblScreenshot_storage;
lv_obj_t *ui_lblTheme_storage;
lv_obj_t *ui_lblCatalogue_storagePackage;
lv_obj_t *ui_lblConfig_storagePackage;
lv_obj_t *ui_lblLanguage_storage;
lv_obj_t *ui_lblNetwork_storage;
lv_obj_t *ui_lblSyncthing_storage_storage;
lv_obj_t *ui_lblUserInit_storage;

lv_obj_t *ui_icoBIOS_storage;
lv_obj_t *ui_icoCatalogue_storage;
lv_obj_t *ui_icoName_storage;
lv_obj_t *ui_icoRetroArch_storage;
lv_obj_t *ui_icoConfig_storage;
lv_obj_t *ui_icoCore_storage;
lv_obj_t *ui_icoCollection_storage_storage;
lv_obj_t *ui_icoHistory_storage;
lv_obj_t *ui_icoMusic_storage;
lv_obj_t *ui_icoSave_storage;
lv_obj_t *ui_icoScreenshot_storage;
lv_obj_t *ui_icoTheme_storage;
lv_obj_t *ui_icoCatalogue_storagePackage;
lv_obj_t *ui_icoConfig_storagePackage;
lv_obj_t *ui_icoLanguage_storage;
lv_obj_t *ui_icoNetwork_storage;
lv_obj_t *ui_icoSyncthing_storage_storage;
lv_obj_t *ui_icoUserInit_storage;

lv_obj_t *ui_lblBIOSValue_storage;
lv_obj_t *ui_lblCatalogueValue_storage;
lv_obj_t *ui_lblNameValue_storage;
lv_obj_t *ui_lblRetroArchValue_storage;
lv_obj_t *ui_lblConfigValue_storage;
lv_obj_t *ui_lblCoreValue_storage;
lv_obj_t *ui_lblCollection_storageValue_storage;
lv_obj_t *ui_lblHistoryValue_storage;
lv_obj_t *ui_lblMusicValue_storage;
lv_obj_t *ui_lblSaveValue_storage;
lv_obj_t *ui_lblScreenshotValue_storage;
lv_obj_t *ui_lblThemeValue_storage;
lv_obj_t *ui_lblCataloguePackageValue_storage;
lv_obj_t *ui_lblConfigPackageValue_storage;
lv_obj_t *ui_lblLanguageValue_storage;
lv_obj_t *ui_lblNetworkValue_storage;
lv_obj_t *ui_lblSyncthingValue_storage_storage;
lv_obj_t *ui_lblUserInitValue_storage;

void init_muxstorage(lv_obj_t *ui_pnlContent) {
    ui_pnlBIOS_storage = lv_obj_create(ui_pnlContent);
    ui_pnlCatalogue_storage = lv_obj_create(ui_pnlContent);
    ui_pnlName_storage = lv_obj_create(ui_pnlContent);
    ui_pnlRetroArch_storage = lv_obj_create(ui_pnlContent);
    ui_pnlConfig_storage = lv_obj_create(ui_pnlContent);
    ui_pnlCore_storage = lv_obj_create(ui_pnlContent);
    ui_pnlCollection_storage_storage = lv_obj_create(ui_pnlContent);
    ui_pnlHistory_storage = lv_obj_create(ui_pnlContent);
    ui_pnlMusic_storage = lv_obj_create(ui_pnlContent);
    ui_pnlSave_storage = lv_obj_create(ui_pnlContent);
    ui_pnlScreenshot_storage = lv_obj_create(ui_pnlContent);
    ui_pnlTheme_storage = lv_obj_create(ui_pnlContent);
    ui_pnlCatalogue_storagePackage = lv_obj_create(ui_pnlContent);
    ui_pnlConfig_storagePackage = lv_obj_create(ui_pnlContent);
    ui_pnlLanguage_storage = lv_obj_create(ui_pnlContent);
    ui_pnlNetwork_storage = lv_obj_create(ui_pnlContent);
    ui_pnlSyncthing_storage_storage = lv_obj_create(ui_pnlContent);
    ui_pnlUserInit_storage = lv_obj_create(ui_pnlContent);

    ui_lblBIOS_storage = lv_label_create(ui_pnlBIOS_storage);
    lv_label_set_text(ui_lblBIOS_storage, "");
    ui_lblCatalogue_storage = lv_label_create(ui_pnlCatalogue_storage);
    lv_label_set_text(ui_lblCatalogue_storage, "");
    ui_lblName_storage = lv_label_create(ui_pnlName_storage);
    lv_label_set_text(ui_lblName_storage, "");
    ui_lblRetroArch_storage = lv_label_create(ui_pnlRetroArch_storage);
    lv_label_set_text(ui_lblRetroArch_storage, "");
    ui_lblConfig_storage = lv_label_create(ui_pnlConfig_storage);
    lv_label_set_text(ui_lblConfig_storage, "");
    ui_lblCore_storage = lv_label_create(ui_pnlCore_storage);
    lv_label_set_text(ui_lblCore_storage, "");
    ui_lblCollection_storage_storage = lv_label_create(ui_pnlCollection_storage_storage);
    lv_label_set_text(ui_lblCollection_storage_storage, "");
    ui_lblHistory_storage = lv_label_create(ui_pnlHistory_storage);
    lv_label_set_text(ui_lblHistory_storage, "");
    ui_lblMusic_storage = lv_label_create(ui_pnlMusic_storage);
    lv_label_set_text(ui_lblMusic_storage, "");
    ui_lblSave_storage = lv_label_create(ui_pnlSave_storage);
    lv_label_set_text(ui_lblSave_storage, "");
    ui_lblScreenshot_storage = lv_label_create(ui_pnlScreenshot_storage);
    lv_label_set_text(ui_lblScreenshot_storage, "");
    ui_lblTheme_storage = lv_label_create(ui_pnlTheme_storage);
    lv_label_set_text(ui_lblTheme_storage, "");
    ui_lblCatalogue_storagePackage = lv_label_create(ui_pnlCatalogue_storagePackage);
    lv_label_set_text(ui_lblCatalogue_storagePackage, "");
    ui_lblConfig_storagePackage = lv_label_create(ui_pnlConfig_storagePackage);
    lv_label_set_text(ui_lblConfig_storagePackage, "");
    ui_lblLanguage_storage = lv_label_create(ui_pnlLanguage_storage);
    lv_label_set_text(ui_lblLanguage_storage, "");
    ui_lblNetwork_storage = lv_label_create(ui_pnlNetwork_storage);
    lv_label_set_text(ui_lblNetwork_storage, "");
    ui_lblSyncthing_storage_storage = lv_label_create(ui_pnlSyncthing_storage_storage);
    lv_label_set_text(ui_lblSyncthing_storage_storage, "");
    ui_lblUserInit_storage = lv_label_create(ui_pnlUserInit_storage);
    lv_label_set_text(ui_lblUserInit_storage, "");

    ui_icoBIOS_storage = lv_img_create(ui_pnlBIOS_storage);
    ui_icoCatalogue_storage = lv_img_create(ui_pnlCatalogue_storage);
    ui_icoName_storage = lv_img_create(ui_pnlName_storage);
    ui_icoRetroArch_storage = lv_img_create(ui_pnlRetroArch_storage);
    ui_icoConfig_storage = lv_img_create(ui_pnlConfig_storage);
    ui_icoCore_storage = lv_img_create(ui_pnlCore_storage);
    ui_icoCollection_storage_storage = lv_img_create(ui_pnlCollection_storage_storage);
    ui_icoHistory_storage = lv_img_create(ui_pnlHistory_storage);
    ui_icoMusic_storage = lv_img_create(ui_pnlMusic_storage);
    ui_icoSave_storage = lv_img_create(ui_pnlSave_storage);
    ui_icoScreenshot_storage = lv_img_create(ui_pnlScreenshot_storage);
    ui_icoTheme_storage = lv_img_create(ui_pnlTheme_storage);
    ui_icoCatalogue_storagePackage = lv_img_create(ui_pnlCatalogue_storagePackage);
    ui_icoConfig_storagePackage = lv_img_create(ui_pnlConfig_storagePackage);
    ui_icoLanguage_storage = lv_img_create(ui_pnlLanguage_storage);
    ui_icoNetwork_storage = lv_img_create(ui_pnlNetwork_storage);
    ui_icoSyncthing_storage_storage = lv_img_create(ui_pnlSyncthing_storage_storage);
    ui_icoUserInit_storage = lv_img_create(ui_pnlUserInit_storage);

    ui_lblBIOSValue_storage = lv_label_create(ui_pnlBIOS_storage);
    lv_label_set_text(ui_lblBIOSValue_storage, "");
    ui_lblCatalogueValue_storage = lv_label_create(ui_pnlCatalogue_storage);
    lv_label_set_text(ui_lblCatalogueValue_storage, "");
    ui_lblNameValue_storage = lv_label_create(ui_pnlName_storage);
    lv_label_set_text(ui_lblNameValue_storage, "");
    ui_lblRetroArchValue_storage = lv_label_create(ui_pnlRetroArch_storage);
    lv_label_set_text(ui_lblRetroArchValue_storage, "");
    ui_lblConfigValue_storage = lv_label_create(ui_pnlConfig_storage);
    lv_label_set_text(ui_lblConfigValue_storage, "");
    ui_lblCoreValue_storage = lv_label_create(ui_pnlCore_storage);
    lv_label_set_text(ui_lblCoreValue_storage, "");
    ui_lblCollection_storageValue_storage = lv_label_create(ui_pnlCollection_storage_storage);
    lv_label_set_text(ui_lblCollection_storageValue_storage, "");
    ui_lblHistoryValue_storage = lv_label_create(ui_pnlHistory_storage);
    lv_label_set_text(ui_lblHistoryValue_storage, "");
    ui_lblMusicValue_storage = lv_label_create(ui_pnlMusic_storage);
    lv_label_set_text(ui_lblMusicValue_storage, "");
    ui_lblSaveValue_storage = lv_label_create(ui_pnlSave_storage);
    lv_label_set_text(ui_lblSaveValue_storage, "");
    ui_lblScreenshotValue_storage = lv_label_create(ui_pnlScreenshot_storage);
    lv_label_set_text(ui_lblScreenshotValue_storage, "");
    ui_lblThemeValue_storage = lv_label_create(ui_pnlTheme_storage);
    lv_label_set_text(ui_lblThemeValue_storage, "");
    ui_lblCataloguePackageValue_storage = lv_label_create(ui_pnlCatalogue_storagePackage);
    lv_label_set_text(ui_lblCataloguePackageValue_storage, "");
    ui_lblConfigPackageValue_storage = lv_label_create(ui_pnlConfig_storagePackage);
    lv_label_set_text(ui_lblConfigPackageValue_storage, "");
    ui_lblLanguageValue_storage = lv_label_create(ui_pnlLanguage_storage);
    lv_label_set_text(ui_lblLanguageValue_storage, "");
    ui_lblNetworkValue_storage = lv_label_create(ui_pnlNetwork_storage);
    lv_label_set_text(ui_lblNetworkValue_storage, "");
    ui_lblSyncthingValue_storage_storage = lv_label_create(ui_pnlSyncthing_storage_storage);
    lv_label_set_text(ui_lblSyncthingValue_storage_storage, "");
    ui_lblUserInitValue_storage = lv_label_create(ui_pnlUserInit_storage);
    lv_label_set_text(ui_lblUserInitValue_storage, "");
}
