#include "ui_muxtweakadv.h"

lv_obj_t *ui_pnlAccelerate;
lv_obj_t *ui_pnlSwap;
lv_obj_t *ui_pnlThermal;
lv_obj_t *ui_pnlFont;
lv_obj_t *ui_pnlVolume;
lv_obj_t *ui_pnlBrightness;
lv_obj_t *ui_pnlOffset;
lv_obj_t *ui_pnlPasscode;
lv_obj_t *ui_pnlLED;
lv_obj_t *ui_pnlTheme;
lv_obj_t *ui_pnlRetroWait;
lv_obj_t *ui_pnlState;
lv_obj_t *ui_pnlVerbose;
lv_obj_t *ui_pnlRumble;
lv_obj_t *ui_pnlUserInit;
lv_obj_t *ui_pnlDPADSwap;
lv_obj_t *ui_pnlOverdrive;
lv_obj_t *ui_pnlSwapfile;
lv_obj_t *ui_pnlCardMode;

lv_obj_t *ui_lblAccelerate;
lv_obj_t *ui_lblSwap;
lv_obj_t *ui_lblThermal;
lv_obj_t *ui_lblFont;
lv_obj_t *ui_lblVolume;
lv_obj_t *ui_lblBrightness;
lv_obj_t *ui_lblOffset;
lv_obj_t *ui_lblPasscode;
lv_obj_t *ui_lblLED;
lv_obj_t *ui_lblTheme;
lv_obj_t *ui_lblRetroWait;
lv_obj_t *ui_lblState;
lv_obj_t *ui_lblVerbose;
lv_obj_t *ui_lblRumble;
lv_obj_t *ui_lblUserInit;
lv_obj_t *ui_lblDPADSwap;
lv_obj_t *ui_lblOverdrive;
lv_obj_t *ui_lblSwapfile;
lv_obj_t *ui_lblCardMode;

lv_obj_t *ui_icoAccelerate;
lv_obj_t *ui_icoSwap;
lv_obj_t *ui_icoThermal;
lv_obj_t *ui_icoFont;
lv_obj_t *ui_icoVolume;
lv_obj_t *ui_icoBrightness;
lv_obj_t *ui_icoOffset;
lv_obj_t *ui_icoPasscode;
lv_obj_t *ui_icoLED;
lv_obj_t *ui_icoTheme;
lv_obj_t *ui_icoRetroWait;
lv_obj_t *ui_icoState;
lv_obj_t *ui_icoVerbose;
lv_obj_t *ui_icoRumble;
lv_obj_t *ui_icoUserInit;
lv_obj_t *ui_icoDPADSwap;
lv_obj_t *ui_icoOverdrive;
lv_obj_t *ui_icoSwapfile;
lv_obj_t *ui_icoCardMode;

lv_obj_t *ui_droAccelerate;
lv_obj_t *ui_droSwap;
lv_obj_t *ui_droThermal;
lv_obj_t *ui_droFont;
lv_obj_t *ui_droVolume;
lv_obj_t *ui_droBrightness;
lv_obj_t *ui_droOffset;
lv_obj_t *ui_droPasscode;
lv_obj_t *ui_droLED;
lv_obj_t *ui_droTheme;
lv_obj_t *ui_droRetroWait;
lv_obj_t *ui_droState;
lv_obj_t *ui_droVerbose;
lv_obj_t *ui_droRumble;
lv_obj_t *ui_droUserInit;
lv_obj_t *ui_droDPADSwap;
lv_obj_t *ui_droOverdrive;
lv_obj_t *ui_droSwapfile;
lv_obj_t *ui_droCardMode;

void init_mux(lv_obj_t *ui_pnlContent) {
    ui_pnlAccelerate = lv_obj_create(ui_pnlContent);
    ui_pnlSwap = lv_obj_create(ui_pnlContent);
    ui_pnlThermal = lv_obj_create(ui_pnlContent);
    ui_pnlFont = lv_obj_create(ui_pnlContent);
    ui_pnlVolume = lv_obj_create(ui_pnlContent);
    ui_pnlBrightness = lv_obj_create(ui_pnlContent);
    ui_pnlOffset = lv_obj_create(ui_pnlContent);
    ui_pnlPasscode = lv_obj_create(ui_pnlContent);
    ui_pnlLED = lv_obj_create(ui_pnlContent);
    ui_pnlTheme = lv_obj_create(ui_pnlContent);
    ui_pnlRetroWait = lv_obj_create(ui_pnlContent);
    ui_pnlState = lv_obj_create(ui_pnlContent);
    ui_pnlVerbose = lv_obj_create(ui_pnlContent);
    ui_pnlRumble = lv_obj_create(ui_pnlContent);
    ui_pnlUserInit = lv_obj_create(ui_pnlContent);
    ui_pnlDPADSwap = lv_obj_create(ui_pnlContent);
    ui_pnlOverdrive = lv_obj_create(ui_pnlContent);
    ui_pnlSwapfile = lv_obj_create(ui_pnlContent);
    ui_pnlCardMode = lv_obj_create(ui_pnlContent);

    ui_lblAccelerate = lv_label_create(ui_pnlAccelerate);
    ui_lblSwap = lv_label_create(ui_pnlSwap);
    ui_lblThermal = lv_label_create(ui_pnlThermal);
    ui_lblFont = lv_label_create(ui_pnlFont);
    ui_lblVolume = lv_label_create(ui_pnlVolume);
    ui_lblBrightness = lv_label_create(ui_pnlBrightness);
    ui_lblOffset = lv_label_create(ui_pnlOffset);
    ui_lblPasscode = lv_label_create(ui_pnlPasscode);
    ui_lblLED = lv_label_create(ui_pnlLED);
    ui_lblTheme = lv_label_create(ui_pnlTheme);
    ui_lblRetroWait = lv_label_create(ui_pnlRetroWait);
    ui_lblState = lv_label_create(ui_pnlState);
    ui_lblVerbose = lv_label_create(ui_pnlVerbose);
    ui_lblRumble = lv_label_create(ui_pnlRumble);
    ui_lblUserInit = lv_label_create(ui_pnlUserInit);
    ui_lblDPADSwap = lv_label_create(ui_pnlDPADSwap);
    ui_lblOverdrive = lv_label_create(ui_pnlOverdrive);
    ui_lblSwapfile = lv_label_create(ui_pnlSwapfile);
    ui_lblCardMode = lv_label_create(ui_pnlCardMode);

    ui_icoAccelerate = lv_img_create(ui_pnlAccelerate);
    ui_icoSwap = lv_img_create(ui_pnlSwap);
    ui_icoThermal = lv_img_create(ui_pnlThermal);
    ui_icoFont = lv_img_create(ui_pnlFont);
    ui_icoVolume = lv_img_create(ui_pnlVolume);
    ui_icoBrightness = lv_img_create(ui_pnlBrightness);
    ui_icoOffset = lv_img_create(ui_pnlOffset);
    ui_icoPasscode = lv_img_create(ui_pnlPasscode);
    ui_icoLED = lv_img_create(ui_pnlLED);
    ui_icoTheme = lv_img_create(ui_pnlTheme);
    ui_icoRetroWait = lv_img_create(ui_pnlRetroWait);
    ui_icoState = lv_img_create(ui_pnlState);
    ui_icoVerbose = lv_img_create(ui_pnlVerbose);
    ui_icoRumble = lv_img_create(ui_pnlRumble);
    ui_icoUserInit = lv_img_create(ui_pnlUserInit);
    ui_icoDPADSwap = lv_img_create(ui_pnlDPADSwap);
    ui_icoOverdrive = lv_img_create(ui_pnlOverdrive);
    ui_icoSwapfile = lv_img_create(ui_pnlSwapfile);
    ui_icoCardMode = lv_img_create(ui_pnlCardMode);

    ui_droAccelerate = lv_dropdown_create(ui_pnlAccelerate);
    ui_droSwap = lv_dropdown_create(ui_pnlSwap);
    ui_droThermal = lv_dropdown_create(ui_pnlThermal);
    ui_droFont = lv_dropdown_create(ui_pnlFont);
    ui_droVolume = lv_dropdown_create(ui_pnlVolume);
    ui_droBrightness = lv_dropdown_create(ui_pnlBrightness);
    ui_droOffset = lv_dropdown_create(ui_pnlOffset);
    ui_droPasscode = lv_dropdown_create(ui_pnlPasscode);
    ui_droLED = lv_dropdown_create(ui_pnlLED);
    ui_droTheme = lv_dropdown_create(ui_pnlTheme);
    ui_droRetroWait = lv_dropdown_create(ui_pnlRetroWait);
    ui_droState = lv_dropdown_create(ui_pnlState);
    ui_droVerbose = lv_dropdown_create(ui_pnlVerbose);
    ui_droRumble = lv_dropdown_create(ui_pnlRumble);
    ui_droUserInit = lv_dropdown_create(ui_pnlUserInit);
    ui_droDPADSwap = lv_dropdown_create(ui_pnlDPADSwap);
    ui_droOverdrive = lv_dropdown_create(ui_pnlOverdrive);
    ui_droSwapfile = lv_dropdown_create(ui_pnlSwapfile);
    ui_droCardMode = lv_dropdown_create(ui_pnlCardMode);
}
