#include "ui_muxtweakadv.h"

lv_obj_t *ui_pnlAccelerate;
lv_obj_t *ui_pnlSwap;
lv_obj_t *ui_pnlThermal;
lv_obj_t *ui_pnlVolume;
lv_obj_t *ui_pnlBrightness;
lv_obj_t *ui_pnlOffset;
lv_obj_t *ui_pnlPasscode;
lv_obj_t *ui_pnlLED;
lv_obj_t *ui_pnlTheme;
lv_obj_t *ui_pnlRetroWait;
lv_obj_t *ui_pnlState;
lv_obj_t *ui_pnlVerbose;
lv_obj_t *ui_pnlRumble;
lv_obj_t *ui_pnlUserInit;
lv_obj_t *ui_pnlDPADSwap;
lv_obj_t *ui_pnlOverdrive;
lv_obj_t *ui_pnlSwapfile;
lv_obj_t *ui_pnlZramfile;
lv_obj_t *ui_pnlCardMode;

lv_obj_t *ui_lblAccelerate;
lv_obj_t *ui_lblSwap;
lv_obj_t *ui_lblThermal;
lv_obj_t *ui_lblVolume;
lv_obj_t *ui_lblBrightness;
lv_obj_t *ui_lblOffset;
lv_obj_t *ui_lblPasscode;
lv_obj_t *ui_lblLED;
lv_obj_t *ui_lblTheme;
lv_obj_t *ui_lblRetroWait;
lv_obj_t *ui_lblState;
lv_obj_t *ui_lblVerbose;
lv_obj_t *ui_lblRumble;
lv_obj_t *ui_lblUserInit;
lv_obj_t *ui_lblDPADSwap;
lv_obj_t *ui_lblOverdrive;
lv_obj_t *ui_lblSwapfile;
lv_obj_t *ui_lblZramfile;
lv_obj_t *ui_lblCardMode;

lv_obj_t *ui_icoAccelerate;
lv_obj_t *ui_icoSwap;
lv_obj_t *ui_icoThermal;
lv_obj_t *ui_icoVolume;
lv_obj_t *ui_icoBrightness;
lv_obj_t *ui_icoOffset;
lv_obj_t *ui_icoPasscode;
lv_obj_t *ui_icoLED;
lv_obj_t *ui_icoTheme;
lv_obj_t *ui_icoRetroWait;
lv_obj_t *ui_icoState;
lv_obj_t *ui_icoVerbose;
lv_obj_t *ui_icoRumble;
lv_obj_t *ui_icoUserInit;
lv_obj_t *ui_icoDPADSwap;
lv_obj_t *ui_icoOverdrive;
lv_obj_t *ui_icoSwapfile;
lv_obj_t *ui_icoZramfile;
lv_obj_t *ui_icoCardMode;

lv_obj_t *ui_droAccelerate;
lv_obj_t *ui_droSwap;
lv_obj_t *ui_droThermal;
lv_obj_t *ui_droVolume;
lv_obj_t *ui_droBrightness;
lv_obj_t *ui_droOffset;
lv_obj_t *ui_droPasscode;
lv_obj_t *ui_droLED;
lv_obj_t *ui_droTheme;
lv_obj_t *ui_droRetroWait;
lv_obj_t *ui_droState;
lv_obj_t *ui_droVerbose;
lv_obj_t *ui_droRumble;
lv_obj_t *ui_droUserInit;
lv_obj_t *ui_droDPADSwap;
lv_obj_t *ui_droOverdrive;
lv_obj_t *ui_droSwapfile;
lv_obj_t *ui_droZramfile;
lv_obj_t *ui_droCardMode;

void init_mux(lv_obj_t *ui_pnlContent) {
    ui_pnlSwap = lv_obj_create(ui_pnlContent);
    ui_pnlOverdrive = lv_obj_create(ui_pnlContent);
    ui_pnlOffset = lv_obj_create(ui_pnlContent);
    ui_pnlBrightness = lv_obj_create(ui_pnlContent);
    ui_pnlRumble = lv_obj_create(ui_pnlContent);
    ui_pnlCardMode = lv_obj_create(ui_pnlContent);
    ui_pnlDPADSwap = lv_obj_create(ui_pnlContent);
    ui_pnlLED = lv_obj_create(ui_pnlContent);
    ui_pnlAccelerate = lv_obj_create(ui_pnlContent);
    ui_pnlThermal = lv_obj_create(ui_pnlContent);
    ui_pnlPasscode = lv_obj_create(ui_pnlContent);
    ui_pnlTheme = lv_obj_create(ui_pnlContent);
    ui_pnlRetroWait = lv_obj_create(ui_pnlContent);
    ui_pnlState = lv_obj_create(ui_pnlContent);
    ui_pnlSwapfile = lv_obj_create(ui_pnlContent);
    ui_pnlZramfile = lv_obj_create(ui_pnlContent);
    ui_pnlUserInit = lv_obj_create(ui_pnlContent);
    ui_pnlVerbose = lv_obj_create(ui_pnlContent);
    ui_pnlVolume = lv_obj_create(ui_pnlContent);

    ui_lblAccelerate = lv_label_create(ui_pnlAccelerate);
    lv_label_set_text(ui_lblAccelerate, "");
    ui_lblSwap = lv_label_create(ui_pnlSwap);
    lv_label_set_text(ui_lblSwap, "");
    ui_lblThermal = lv_label_create(ui_pnlThermal);
    lv_label_set_text(ui_lblThermal, "");
    ui_lblVolume = lv_label_create(ui_pnlVolume);
    lv_label_set_text(ui_lblVolume, "");
    ui_lblBrightness = lv_label_create(ui_pnlBrightness);
    lv_label_set_text(ui_lblBrightness, "");
    ui_lblOffset = lv_label_create(ui_pnlOffset);
    lv_label_set_text(ui_lblOffset, "");
    ui_lblPasscode = lv_label_create(ui_pnlPasscode);
    lv_label_set_text(ui_lblPasscode, "");
    ui_lblLED = lv_label_create(ui_pnlLED);
    lv_label_set_text(ui_lblLED, "");
    ui_lblTheme = lv_label_create(ui_pnlTheme);
    lv_label_set_text(ui_lblTheme, "");
    ui_lblRetroWait = lv_label_create(ui_pnlRetroWait);
    lv_label_set_text(ui_lblRetroWait, "");
    ui_lblState = lv_label_create(ui_pnlState);
    lv_label_set_text(ui_lblState, "");
    ui_lblVerbose = lv_label_create(ui_pnlVerbose);
    lv_label_set_text(ui_lblVerbose, "");
    ui_lblRumble = lv_label_create(ui_pnlRumble);
    lv_label_set_text(ui_lblRumble, "");
    ui_lblUserInit = lv_label_create(ui_pnlUserInit);
    lv_label_set_text(ui_lblUserInit, "");
    ui_lblDPADSwap = lv_label_create(ui_pnlDPADSwap);
    lv_label_set_text(ui_lblDPADSwap, "");
    ui_lblOverdrive = lv_label_create(ui_pnlOverdrive);
    lv_label_set_text(ui_lblOverdrive, "");
    ui_lblSwapfile = lv_label_create(ui_pnlSwapfile);
    lv_label_set_text(ui_lblSwapfile, "");
    ui_lblZramfile = lv_label_create(ui_pnlZramfile);
    lv_label_set_text(ui_lblZramfile, "");
    ui_lblCardMode = lv_label_create(ui_pnlCardMode);
    lv_label_set_text(ui_lblCardMode, "");

    ui_icoAccelerate = lv_img_create(ui_pnlAccelerate);
    ui_icoSwap = lv_img_create(ui_pnlSwap);
    ui_icoThermal = lv_img_create(ui_pnlThermal);
    ui_icoVolume = lv_img_create(ui_pnlVolume);
    ui_icoBrightness = lv_img_create(ui_pnlBrightness);
    ui_icoOffset = lv_img_create(ui_pnlOffset);
    ui_icoPasscode = lv_img_create(ui_pnlPasscode);
    ui_icoLED = lv_img_create(ui_pnlLED);
    ui_icoTheme = lv_img_create(ui_pnlTheme);
    ui_icoRetroWait = lv_img_create(ui_pnlRetroWait);
    ui_icoState = lv_img_create(ui_pnlState);
    ui_icoVerbose = lv_img_create(ui_pnlVerbose);
    ui_icoRumble = lv_img_create(ui_pnlRumble);
    ui_icoUserInit = lv_img_create(ui_pnlUserInit);
    ui_icoDPADSwap = lv_img_create(ui_pnlDPADSwap);
    ui_icoOverdrive = lv_img_create(ui_pnlOverdrive);
    ui_icoSwapfile = lv_img_create(ui_pnlSwapfile);
    ui_icoZramfile = lv_img_create(ui_pnlZramfile);
    ui_icoCardMode = lv_img_create(ui_pnlCardMode);

    ui_droAccelerate = lv_dropdown_create(ui_pnlAccelerate);
    lv_dropdown_clear_options(ui_droAccelerate);
    lv_obj_set_style_text_opa(ui_droAccelerate, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droSwap = lv_dropdown_create(ui_pnlSwap);
    lv_dropdown_clear_options(ui_droSwap);
    lv_obj_set_style_text_opa(ui_droSwap, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droThermal = lv_dropdown_create(ui_pnlThermal);
    lv_dropdown_clear_options(ui_droThermal);
    lv_obj_set_style_text_opa(ui_droThermal, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droVolume = lv_dropdown_create(ui_pnlVolume);
    lv_dropdown_clear_options(ui_droVolume);
    lv_obj_set_style_text_opa(ui_droVolume, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droBrightness = lv_dropdown_create(ui_pnlBrightness);
    lv_dropdown_clear_options(ui_droBrightness);
    lv_obj_set_style_text_opa(ui_droBrightness, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droOffset = lv_dropdown_create(ui_pnlOffset);
    lv_dropdown_clear_options(ui_droOffset);
    lv_obj_set_style_text_opa(ui_droOffset, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droPasscode = lv_dropdown_create(ui_pnlPasscode);
    lv_dropdown_clear_options(ui_droPasscode);
    lv_obj_set_style_text_opa(ui_droPasscode, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droLED = lv_dropdown_create(ui_pnlLED);
    lv_dropdown_clear_options(ui_droLED);
    lv_obj_set_style_text_opa(ui_droLED, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droTheme = lv_dropdown_create(ui_pnlTheme);
    lv_dropdown_clear_options(ui_droTheme);
    lv_obj_set_style_text_opa(ui_droTheme, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droRetroWait = lv_dropdown_create(ui_pnlRetroWait);
    lv_dropdown_clear_options(ui_droRetroWait);
    lv_obj_set_style_text_opa(ui_droRetroWait, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droState = lv_dropdown_create(ui_pnlState);
    lv_dropdown_clear_options(ui_droState);
    lv_obj_set_style_text_opa(ui_droState, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droVerbose = lv_dropdown_create(ui_pnlVerbose);
    lv_dropdown_clear_options(ui_droVerbose);
    lv_obj_set_style_text_opa(ui_droVerbose, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droRumble = lv_dropdown_create(ui_pnlRumble);
    lv_dropdown_clear_options(ui_droRumble);
    lv_obj_set_style_text_opa(ui_droRumble, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droUserInit = lv_dropdown_create(ui_pnlUserInit);
    lv_dropdown_clear_options(ui_droUserInit);
    lv_obj_set_style_text_opa(ui_droUserInit, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droDPADSwap = lv_dropdown_create(ui_pnlDPADSwap);
    lv_dropdown_clear_options(ui_droDPADSwap);
    lv_obj_set_style_text_opa(ui_droDPADSwap, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droOverdrive = lv_dropdown_create(ui_pnlOverdrive);
    lv_dropdown_clear_options(ui_droOverdrive);
    lv_obj_set_style_text_opa(ui_droOverdrive, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droSwapfile = lv_dropdown_create(ui_pnlSwapfile);
    lv_dropdown_clear_options(ui_droSwapfile);
    lv_obj_set_style_text_opa(ui_droSwapfile, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droZramfile = lv_dropdown_create(ui_pnlZramfile);
    lv_dropdown_clear_options(ui_droZramfile);
    lv_obj_set_style_text_opa(ui_droZramfile, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droCardMode = lv_dropdown_create(ui_pnlCardMode);
    lv_dropdown_clear_options(ui_droCardMode);
    lv_obj_set_style_text_opa(ui_droCardMode, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
}
