#include "ui_muxcustom.h"

lv_obj_t *ui_pnlBackgroundAnimation;
lv_obj_t *ui_pnlBGM;
lv_obj_t *ui_pnlBlackFade;
lv_obj_t *ui_pnlBoxArt;
lv_obj_t *ui_pnlBoxArtAlign;
lv_obj_t *ui_pnlLaunchSplash;
lv_obj_t *ui_pnlFont;
lv_obj_t *ui_pnlTheme;
lv_obj_t *ui_pnlThemeResolution;
lv_obj_t *ui_pnlThemeAlternate;
lv_obj_t *ui_pnlSound;
lv_obj_t *ui_pnlChime;
lv_obj_t *ui_pnlCatalogue;
lv_obj_t *ui_pnlConfig;

lv_obj_t *ui_lblBackgroundAnimation;
lv_obj_t *ui_lblBGM;
lv_obj_t *ui_lblBlackFade;
lv_obj_t *ui_lblBoxArt;
lv_obj_t *ui_lblBoxArtAlign;
lv_obj_t *ui_lblLaunchSplash;
lv_obj_t *ui_lblFont;
lv_obj_t *ui_lblTheme;
lv_obj_t *ui_lblThemeResolution;
lv_obj_t *ui_lblThemeAlternate;
lv_obj_t *ui_lblSound;
lv_obj_t *ui_lblChime;
lv_obj_t *ui_lblCatalogue;
lv_obj_t *ui_lblConfig;

lv_obj_t *ui_icoBackgroundAnimation;
lv_obj_t *ui_icoBGM;
lv_obj_t *ui_icoBlackFade;
lv_obj_t *ui_icoBoxArt;
lv_obj_t *ui_icoBoxArtAlign;
lv_obj_t *ui_icoLaunchSplash;
lv_obj_t *ui_icoFont;
lv_obj_t *ui_icoTheme;
lv_obj_t *ui_icoThemeResolution;
lv_obj_t *ui_icoThemeAlternate;
lv_obj_t *ui_icoSound;
lv_obj_t *ui_icoChime;
lv_obj_t *ui_icoCatalogue;
lv_obj_t *ui_icoConfig;

lv_obj_t *ui_droBackgroundAnimation;
lv_obj_t *ui_droBGM;
lv_obj_t *ui_droBlackFade;
lv_obj_t *ui_droBoxArt;
lv_obj_t *ui_droBoxArtAlign;
lv_obj_t *ui_droLaunchSplash;
lv_obj_t *ui_droFont;
lv_obj_t *ui_droTheme;
lv_obj_t *ui_droThemeResolution;
lv_obj_t *ui_droThemeAlternate;
lv_obj_t *ui_droSound;
lv_obj_t *ui_droChime;
lv_obj_t *ui_droCatalogue;
lv_obj_t *ui_droConfig;

void init_muxcustom(lv_obj_t *ui_pnlContent) {
    ui_pnlCatalogue = lv_obj_create(ui_pnlContent);
    ui_pnlConfig = lv_obj_create(ui_pnlContent);
    ui_pnlTheme = lv_obj_create(ui_pnlContent);
    ui_pnlThemeResolution = lv_obj_create(ui_pnlContent);
    ui_pnlThemeAlternate = lv_obj_create(ui_pnlContent);
    ui_pnlBackgroundAnimation = lv_obj_create(ui_pnlContent);
    ui_pnlBGM = lv_obj_create(ui_pnlContent);
    ui_pnlBlackFade = lv_obj_create(ui_pnlContent);
    ui_pnlBoxArt = lv_obj_create(ui_pnlContent);
    ui_pnlBoxArtAlign = lv_obj_create(ui_pnlContent);
    ui_pnlLaunchSplash = lv_obj_create(ui_pnlContent);
    ui_pnlFont = lv_obj_create(ui_pnlContent);
    ui_pnlSound = lv_obj_create(ui_pnlContent);
    ui_pnlChime = lv_obj_create(ui_pnlContent);

    ui_lblBackgroundAnimation = lv_label_create(ui_pnlBackgroundAnimation);
    lv_label_set_text(ui_lblBackgroundAnimation, "");
    ui_lblBGM = lv_label_create(ui_pnlBGM);
    lv_label_set_text(ui_lblBGM, "");
    ui_lblBlackFade = lv_label_create(ui_pnlBlackFade);
    lv_label_set_text(ui_lblBlackFade, "");
    ui_lblBoxArt = lv_label_create(ui_pnlBoxArt);
    lv_label_set_text(ui_lblBoxArt, "");
    ui_lblBoxArtAlign = lv_label_create(ui_pnlBoxArtAlign);
    lv_label_set_text(ui_lblBoxArtAlign, "");
    ui_lblLaunchSplash = lv_label_create(ui_pnlLaunchSplash);
    lv_label_set_text(ui_lblLaunchSplash, "");
    ui_lblFont = lv_label_create(ui_pnlFont);
    lv_label_set_text(ui_lblFont, "");
    ui_lblTheme = lv_label_create(ui_pnlTheme);
    lv_label_set_text(ui_lblTheme, "");
    ui_lblThemeResolution = lv_label_create(ui_pnlThemeResolution);
    lv_label_set_text(ui_lblThemeResolution, "");
    ui_lblThemeAlternate = lv_label_create(ui_pnlThemeAlternate);
    lv_label_set_text(ui_lblThemeAlternate, "");
    ui_lblSound = lv_label_create(ui_pnlSound);
    lv_label_set_text(ui_lblSound, "");
    ui_lblChime = lv_label_create(ui_pnlChime);
    lv_label_set_text(ui_lblChime, "");
    ui_lblCatalogue = lv_label_create(ui_pnlCatalogue);
    lv_label_set_text(ui_lblCatalogue, "");
    ui_lblConfig = lv_label_create(ui_pnlConfig);
    lv_label_set_text(ui_lblConfig, "");

    ui_icoBackgroundAnimation = lv_img_create(ui_pnlBackgroundAnimation);
    ui_icoBGM = lv_img_create(ui_pnlBGM);
    ui_icoBlackFade = lv_img_create(ui_pnlBlackFade);
    ui_icoBoxArt = lv_img_create(ui_pnlBoxArt);
    ui_icoBoxArtAlign = lv_img_create(ui_pnlBoxArtAlign);
    ui_icoLaunchSplash = lv_img_create(ui_pnlLaunchSplash);
    ui_icoFont = lv_img_create(ui_pnlFont);
    ui_icoTheme = lv_img_create(ui_pnlTheme);
    ui_icoThemeResolution = lv_img_create(ui_pnlThemeResolution);
    ui_icoThemeAlternate = lv_img_create(ui_pnlThemeAlternate);
    ui_icoSound = lv_img_create(ui_pnlSound);
    ui_icoChime = lv_img_create(ui_pnlChime);
    ui_icoCatalogue = lv_img_create(ui_pnlCatalogue);
    ui_icoConfig = lv_img_create(ui_pnlConfig);

    ui_droBackgroundAnimation = lv_dropdown_create(ui_pnlBackgroundAnimation);
    lv_dropdown_clear_options(ui_droBackgroundAnimation);
    lv_obj_set_style_text_opa(ui_droBackgroundAnimation, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droBGM = lv_dropdown_create(ui_pnlBGM);
    lv_dropdown_clear_options(ui_droBGM);
    lv_obj_set_style_text_opa(ui_droBGM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droBlackFade = lv_dropdown_create(ui_pnlBlackFade);
    lv_dropdown_clear_options(ui_droBlackFade);
    lv_obj_set_style_text_opa(ui_droBlackFade, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droBoxArt = lv_dropdown_create(ui_pnlBoxArt);
    lv_dropdown_clear_options(ui_droBoxArt);
    lv_obj_set_style_text_opa(ui_droBoxArt, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droBoxArtAlign = lv_dropdown_create(ui_pnlBoxArtAlign);
    lv_dropdown_clear_options(ui_droBoxArtAlign);
    lv_obj_set_style_text_opa(ui_droBoxArtAlign, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droLaunchSplash = lv_dropdown_create(ui_pnlLaunchSplash);
    lv_dropdown_clear_options(ui_droLaunchSplash);
    lv_obj_set_style_text_opa(ui_droLaunchSplash, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droFont = lv_dropdown_create(ui_pnlFont);
    lv_dropdown_clear_options(ui_droFont);
    lv_obj_set_style_text_opa(ui_droFont, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droTheme = lv_dropdown_create(ui_pnlTheme);
    lv_dropdown_clear_options(ui_droTheme);
    lv_obj_set_style_text_opa(ui_droTheme, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droThemeResolution = lv_dropdown_create(ui_pnlThemeResolution);
    lv_dropdown_clear_options(ui_droThemeResolution);
    lv_obj_set_style_text_opa(ui_droThemeResolution, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droThemeAlternate = lv_dropdown_create(ui_pnlThemeAlternate);
    lv_dropdown_clear_options(ui_droThemeAlternate);
    lv_obj_set_style_text_opa(ui_droThemeAlternate, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droSound = lv_dropdown_create(ui_pnlSound);
    lv_dropdown_clear_options(ui_droSound);
    lv_obj_set_style_text_opa(ui_droSound, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droChime = lv_dropdown_create(ui_pnlChime);
    lv_dropdown_clear_options(ui_droChime);
    lv_obj_set_style_text_opa(ui_droChime, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droCatalogue = lv_dropdown_create(ui_pnlCatalogue);
    lv_dropdown_clear_options(ui_droCatalogue);
    lv_obj_set_style_text_opa(ui_droCatalogue, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_droConfig = lv_dropdown_create(ui_pnlConfig);
    lv_dropdown_clear_options(ui_droConfig);
    lv_obj_set_style_text_opa(ui_droConfig, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
}
