#include "ui_muxstorage.h"

lv_obj_t *ui_pnlBIOS;
lv_obj_t *ui_pnlCatalogue;
lv_obj_t *ui_pnlName;
lv_obj_t *ui_pnlRetroArch;
lv_obj_t *ui_pnlConfig;
lv_obj_t *ui_pnlCore;
lv_obj_t *ui_pnlCollection;
lv_obj_t *ui_pnlHistory;
lv_obj_t *ui_pnlMusic;
lv_obj_t *ui_pnlSave;
lv_obj_t *ui_pnlScreenshot;
lv_obj_t *ui_pnlTheme;
lv_obj_t *ui_pnlCataloguePackage;
lv_obj_t *ui_pnlConfigPackage;
lv_obj_t *ui_pnlLanguage;
lv_obj_t *ui_pnlNetwork;
lv_obj_t *ui_pnlSyncthing_storage;
lv_obj_t *ui_pnlUserInit;

lv_obj_t *ui_lblBIOS;
lv_obj_t *ui_lblCatalogue;
lv_obj_t *ui_lblName;
lv_obj_t *ui_lblRetroArch;
lv_obj_t *ui_lblConfig;
lv_obj_t *ui_lblCore;
lv_obj_t *ui_lblCollection;
lv_obj_t *ui_lblHistory;
lv_obj_t *ui_lblMusic;
lv_obj_t *ui_lblSave;
lv_obj_t *ui_lblScreenshot;
lv_obj_t *ui_lblTheme;
lv_obj_t *ui_lblCataloguePackage;
lv_obj_t *ui_lblConfigPackage;
lv_obj_t *ui_lblLanguage;
lv_obj_t *ui_lblNetwork;
lv_obj_t *ui_lblSyncthing_storage;
lv_obj_t *ui_lblUserInit;

lv_obj_t *ui_icoBIOS;
lv_obj_t *ui_icoCatalogue;
lv_obj_t *ui_icoName;
lv_obj_t *ui_icoRetroArch;
lv_obj_t *ui_icoConfig;
lv_obj_t *ui_icoCore;
lv_obj_t *ui_icoCollection;
lv_obj_t *ui_icoHistory;
lv_obj_t *ui_icoMusic;
lv_obj_t *ui_icoSave;
lv_obj_t *ui_icoScreenshot;
lv_obj_t *ui_icoTheme;
lv_obj_t *ui_icoCataloguePackage;
lv_obj_t *ui_icoConfigPackage;
lv_obj_t *ui_icoLanguage;
lv_obj_t *ui_icoNetwork;
lv_obj_t *ui_icoSyncthing_storage;
lv_obj_t *ui_icoUserInit;

lv_obj_t *ui_lblBIOSValue;
lv_obj_t *ui_lblCatalogueValue;
lv_obj_t *ui_lblNameValue;
lv_obj_t *ui_lblRetroArchValue;
lv_obj_t *ui_lblConfigValue;
lv_obj_t *ui_lblCoreValue;
lv_obj_t *ui_lblCollectionValue;
lv_obj_t *ui_lblHistoryValue;
lv_obj_t *ui_lblMusicValue;
lv_obj_t *ui_lblSaveValue;
lv_obj_t *ui_lblScreenshotValue;
lv_obj_t *ui_lblThemeValue;
lv_obj_t *ui_lblCataloguePackageValue;
lv_obj_t *ui_lblConfigPackageValue;
lv_obj_t *ui_lblLanguageValue;
lv_obj_t *ui_lblNetworkValue;
lv_obj_t *ui_lblSyncthingValue_storage;
lv_obj_t *ui_lblUserInitValue;

void init_muxstorage(lv_obj_t *ui_pnlContent) {
    ui_pnlBIOS = lv_obj_create(ui_pnlContent);
    ui_pnlCatalogue = lv_obj_create(ui_pnlContent);
    ui_pnlName = lv_obj_create(ui_pnlContent);
    ui_pnlRetroArch = lv_obj_create(ui_pnlContent);
    ui_pnlConfig = lv_obj_create(ui_pnlContent);
    ui_pnlCore = lv_obj_create(ui_pnlContent);
    ui_pnlCollection = lv_obj_create(ui_pnlContent);
    ui_pnlHistory = lv_obj_create(ui_pnlContent);
    ui_pnlMusic = lv_obj_create(ui_pnlContent);
    ui_pnlSave = lv_obj_create(ui_pnlContent);
    ui_pnlScreenshot = lv_obj_create(ui_pnlContent);
    ui_pnlTheme = lv_obj_create(ui_pnlContent);
    ui_pnlCataloguePackage = lv_obj_create(ui_pnlContent);
    ui_pnlConfigPackage = lv_obj_create(ui_pnlContent);
    ui_pnlLanguage = lv_obj_create(ui_pnlContent);
    ui_pnlNetwork = lv_obj_create(ui_pnlContent);
    ui_pnlSyncthing_storage = lv_obj_create(ui_pnlContent);
    ui_pnlUserInit = lv_obj_create(ui_pnlContent);

    ui_lblBIOS = lv_label_create(ui_pnlBIOS);
    lv_label_set_text(ui_lblBIOS, "");
    ui_lblCatalogue = lv_label_create(ui_pnlCatalogue);
    lv_label_set_text(ui_lblCatalogue, "");
    ui_lblName = lv_label_create(ui_pnlName);
    lv_label_set_text(ui_lblName, "");
    ui_lblRetroArch = lv_label_create(ui_pnlRetroArch);
    lv_label_set_text(ui_lblRetroArch, "");
    ui_lblConfig = lv_label_create(ui_pnlConfig);
    lv_label_set_text(ui_lblConfig, "");
    ui_lblCore = lv_label_create(ui_pnlCore);
    lv_label_set_text(ui_lblCore, "");
    ui_lblCollection = lv_label_create(ui_pnlCollection);
    lv_label_set_text(ui_lblCollection, "");
    ui_lblHistory = lv_label_create(ui_pnlHistory);
    lv_label_set_text(ui_lblHistory, "");
    ui_lblMusic = lv_label_create(ui_pnlMusic);
    lv_label_set_text(ui_lblMusic, "");
    ui_lblSave = lv_label_create(ui_pnlSave);
    lv_label_set_text(ui_lblSave, "");
    ui_lblScreenshot = lv_label_create(ui_pnlScreenshot);
    lv_label_set_text(ui_lblScreenshot, "");
    ui_lblTheme = lv_label_create(ui_pnlTheme);
    lv_label_set_text(ui_lblTheme, "");
    ui_lblCataloguePackage = lv_label_create(ui_pnlCataloguePackage);
    lv_label_set_text(ui_lblCataloguePackage, "");
    ui_lblConfigPackage = lv_label_create(ui_pnlConfigPackage);
    lv_label_set_text(ui_lblConfigPackage, "");
    ui_lblLanguage = lv_label_create(ui_pnlLanguage);
    lv_label_set_text(ui_lblLanguage, "");
    ui_lblNetwork = lv_label_create(ui_pnlNetwork);
    lv_label_set_text(ui_lblNetwork, "");
    ui_lblSyncthing_storage = lv_label_create(ui_pnlSyncthing_storage);
    lv_label_set_text(ui_lblSyncthing_storage, "");
    ui_lblUserInit = lv_label_create(ui_pnlUserInit);
    lv_label_set_text(ui_lblUserInit, "");

    ui_icoBIOS = lv_img_create(ui_pnlBIOS);
    ui_icoCatalogue = lv_img_create(ui_pnlCatalogue);
    ui_icoName = lv_img_create(ui_pnlName);
    ui_icoRetroArch = lv_img_create(ui_pnlRetroArch);
    ui_icoConfig = lv_img_create(ui_pnlConfig);
    ui_icoCore = lv_img_create(ui_pnlCore);
    ui_icoCollection = lv_img_create(ui_pnlCollection);
    ui_icoHistory = lv_img_create(ui_pnlHistory);
    ui_icoMusic = lv_img_create(ui_pnlMusic);
    ui_icoSave = lv_img_create(ui_pnlSave);
    ui_icoScreenshot = lv_img_create(ui_pnlScreenshot);
    ui_icoTheme = lv_img_create(ui_pnlTheme);
    ui_icoCataloguePackage = lv_img_create(ui_pnlCataloguePackage);
    ui_icoConfigPackage = lv_img_create(ui_pnlConfigPackage);
    ui_icoLanguage = lv_img_create(ui_pnlLanguage);
    ui_icoNetwork = lv_img_create(ui_pnlNetwork);
    ui_icoSyncthing_storage = lv_img_create(ui_pnlSyncthing_storage);
    ui_icoUserInit = lv_img_create(ui_pnlUserInit);

    ui_lblBIOSValue = lv_label_create(ui_pnlBIOS);
    lv_label_set_text(ui_lblBIOSValue, "");
    ui_lblCatalogueValue = lv_label_create(ui_pnlCatalogue);
    lv_label_set_text(ui_lblCatalogueValue, "");
    ui_lblNameValue = lv_label_create(ui_pnlName);
    lv_label_set_text(ui_lblNameValue, "");
    ui_lblRetroArchValue = lv_label_create(ui_pnlRetroArch);
    lv_label_set_text(ui_lblRetroArchValue, "");
    ui_lblConfigValue = lv_label_create(ui_pnlConfig);
    lv_label_set_text(ui_lblConfigValue, "");
    ui_lblCoreValue = lv_label_create(ui_pnlCore);
    lv_label_set_text(ui_lblCoreValue, "");
    ui_lblCollectionValue = lv_label_create(ui_pnlCollection);
    lv_label_set_text(ui_lblCollectionValue, "");
    ui_lblHistoryValue = lv_label_create(ui_pnlHistory);
    lv_label_set_text(ui_lblHistoryValue, "");
    ui_lblMusicValue = lv_label_create(ui_pnlMusic);
    lv_label_set_text(ui_lblMusicValue, "");
    ui_lblSaveValue = lv_label_create(ui_pnlSave);
    lv_label_set_text(ui_lblSaveValue, "");
    ui_lblScreenshotValue = lv_label_create(ui_pnlScreenshot);
    lv_label_set_text(ui_lblScreenshotValue, "");
    ui_lblThemeValue = lv_label_create(ui_pnlTheme);
    lv_label_set_text(ui_lblThemeValue, "");
    ui_lblCataloguePackageValue = lv_label_create(ui_pnlCataloguePackage);
    lv_label_set_text(ui_lblCataloguePackageValue, "");
    ui_lblConfigPackageValue = lv_label_create(ui_pnlConfigPackage);
    lv_label_set_text(ui_lblConfigPackageValue, "");
    ui_lblLanguageValue = lv_label_create(ui_pnlLanguage);
    lv_label_set_text(ui_lblLanguageValue, "");
    ui_lblNetworkValue = lv_label_create(ui_pnlNetwork);
    lv_label_set_text(ui_lblNetworkValue, "");
    ui_lblSyncthingValue_storage = lv_label_create(ui_pnlSyncthing_storage);
    lv_label_set_text(ui_lblSyncthingValue_storage, "");
    ui_lblUserInitValue = lv_label_create(ui_pnlUserInit);
    lv_label_set_text(ui_lblUserInitValue, "");
}
