#include "coredef.h"

static const struct coredef_option options[] = {
    {.key = "ppsspp_cpu_core", .value = "JIT"},
    {.key = "ppsspp_fast_memory", .value = "enabled"},
    {.key = "ppsspp_ignore_bad_memory_access", .value = "enabled"},
    {.key = "ppsspp_io_timing_method", .value = "Fast"},
    {.key = "ppsspp_force_lag_sync", .value = "disabled"},
    {.key = "ppsspp_locked_cpu_speed", .value = "disabled"},
    {.key = "ppsspp_cache_iso", .value = "disabled"},
    {.key = "ppsspp_cheats", .value = "disabled"},
    {.key = "ppsspp_psp_model", .value = "psp_2000_3000"},
    {.key = "ppsspp_internal_resolution", .value = "960x544"},
    {.key = "ppsspp_pickles_output_upscaler", .value = "Sharp Bilinear"},
    {.key = "ppsspp_software_rendering", .value = "disabled"},
    {.key = "ppsspp_mulitsample_level", .value = "Disabled"},
    {.key = "ppsspp_frameskip", .value = "1"},
    {.key = "ppsspp_frameskiptype", .value = "Number of frames"},
    {.key = "ppsspp_auto_frameskip", .value = "enabled"},
    {.key = "ppsspp_frame_duplication", .value = "enabled"},
    {.key = "ppsspp_detect_vsync_swap_interval", .value = "disabled"},
    {.key = "ppsspp_inflight_frames", .value = "Up to 2"},
    {.key = "ppsspp_skip_buffer_effects", .value = "disabled"},
    {.key = "ppsspp_disable_range_culling", .value = "disabled"},
    {.key = "ppsspp_skip_gpu_readbacks", .value = "enabled"},
    {.key = "ppsspp_lazy_texture_caching", .value = "enabled"},
    {.key = "ppsspp_spline_quality", .value = "Low"},
    {.key = "ppsspp_gpu_hardware_transform", .value = "enabled"},
    {.key = "ppsspp_software_skinning", .value = "disabled"},
    {.key = "ppsspp_hardware_tesselation", .value = "disabled"},
    {.key = "ppsspp_lower_resolution_for_effects", .value = "Aggressive"},
    {.key = "ppsspp_texture_scaling_level", .value = "disabled"},
    {.key = "ppsspp_texture_deposterize", .value = "disabled"},
    {.key = "ppsspp_texture_anisotropic_filtering", .value = "disabled"},
    {.key = "ppsspp_texture_filtering", .value = "Auto"},
    {.key = "ppsspp_smart_2d_texture_filtering", .value = "disabled"},
    {.key = "ppsspp_texture_replacement", .value = "disabled"},
};

COREDEF_CORE(ppsspp, "ppsspp", options);
