#include <stdlib.h>
#include <common/content/core/retroarch.h>

const struct ra_core_name ra_core_names[] = {
    // Arcade
    {"mame", "MAME Current", "MAME 2015"},
    {"mame078plus", "MAME .78 Plus", "MAME 2003 (0.78)"},
    {"mame0139", "MAME .139", "MAME 2010"},
    {"mame2000", "MAME 2000", "MAME 2000"},
    {"mame2003", "MAME 2003", "MAME 2003"},
    {"mame2003_plus", "MAME 2003 Plus", "MAME 2003-Plus"},
    {"mame2003_midway", "MAME 2003 Midway", "MAME 2003"},
    {"mame2010", "MAME 2010", "MAME 2010"},
    {"km_mame2003_xtreme_amped", "MAME 2003 Xtreme", "MAME 2003-Plus"},
    {"fbneo", "FBNeo", "FinalBurn Neo"},
    {"km_fbneo_xtreme_amped", "FBNeo Xtreme", "FinalBurn Neo"},
    {"fbalpha2012", "FBA 2012", "FB Alpha 2012"},
    {"fbalpha2012_cps1", "FBA CPS-1", "FB Alpha 2012"},
    {"fbalpha2012_cps2", "FBA CPS-2", "FB Alpha 2012"},
    {"fbalpha2012_cps3", "FBA CPS-3", "FB Alpha 2012"},
    {"fbalpha2012_neogeo", "FBA Neo Geo", "FB Alpha 2012 Neo Geo"},

    // Nintendo
    {"nestopia", "Nestopia", "Nestopia"},
    {"fceumm", "FCEUmm", "FCEUmm"},
    {"quicknes", "QuickNES", "QuickNES"},
    {"mesen", "Mesen", "Mesen"},
    {"mesen-s", "Mesen-S", "Mesen"},
    {"snes9x", "Snes9x", "Snes9x"},
    {"snes9x2002", "Snes9x 2002", "Snes9x 2002"},
    {"snes9x2005", "Snes9x 2005", "Snes9x 2005"},
    {"snes9x2005_plus", "Snes9x 2005+", "Snes9x 2005 Plus"},
    {"snes9x2010", "Snes9x 2010", "Snes9x 2010"},
    {"snes9x_next", "Snes9x Next", "Snes9x"},
    {"bsnes", "BSNES", "bnes"},
    {"bsnes2014_performance", "BSNES 2014", "bnes"},
    {"bsnes_cplusplus98", "BSNES C++98", "bnes"},
    {"bsnes_mercury_performance", "BSNES Mercury", "bnes"},
    {"chimerasnes", "ChimeraSNES", "ChimeraSNES"},
    {"mednafen_supafaust", "Beetle Supafaust", "Supafaust"},
    {"mupen64plus_next", "Mupen64+ Next", "Mupen64Plus-Next"},

    // Game Boy / GBA
    {"gambatte", "Gambatte", "Gambatte"},
    {"gearboy", "GearBoy", "Gearboy"},
    {"sameboy", "SameBoy", "SameBoy"},
    {"mgba", "mGBA", "mGBA"},
    {"mgba_rumble", "mGBA Rumble", "mGBA"},
    {"gpsp", "GpSP", "gpSP"},
    {"vbam", "VBA M", "VBA-M"},
    {"vba_next", "VBA Next", "VBA Next"},
    {"DoubleCherryGB", "Double Cherry", "Gambatte"},
    {"fixgb", "FixGB", "Gambatte"},
    {"tgbdual", "TGB Dual", "Gambatte"},
    {"mednafen_gba", "Beetle GBA", "Beetle GBA"},
    {"mednafen_vb", "Beetle VB", "Beetle VB"},

    // SEGA
    {"genesis_plus_gx", "Gen Plus GX", "Genesis Plus GX"},
    {"genesis_plus_gx_wide", "Gen Plus GX Wide", "Genesis Plus GX Wide"},
    {"genesis_plus_gx_expanded", "Gen Plus GX Exp.", "Genesis Plus GX"},
    {"picodrive", "PicoDrive", "PicoDrive"},
    {"gearsystem", "GearSystem", "Gearsystem"},
    {"smsplus", "SMS Plus GX", "SMS Plus GX"},
    {"yabause", "Yabause", "Yabause"},
    {"yabasanshiro", "YabaSanshiro", "YabaSanshiro"},
    {"mednafen_saturn", "Beetle Saturn", "Beetle Saturn"},
    {"flycast", "Flycast", "Flycast"},
    {"flycastvl", "Flycast VL", "Flycast"},
    {"flycast-xtreme", "Flycast Xtreme", "Flycast Xtreme"},
    {"morpheuscast", "MorpheusCast", "MorpheusCast Xtreme Acc"},

    // Sony
    {"duckstation", "DuckStation", "DuckStation"},
    {"pcsx_rearmed", "PCSX ReARMed", "PCSX-ReARMed"},
    {"swanstation", "SwanStation", "SwanStation"},
    {"ppsspp", "PPSSPP", "PPSSPP"},
    {"mednafen_psx", "Beetle PSX", "DuckStation"},

    // Atari
    {"stella", "Stella", "Stella"},
    {"stella2014", "Stella 2014", "Stella 2014"},
    {"mednafen_lynx", "Beetle Lynx", "Beetle Lynx"},
    {"handy", "Handy", "Handy"},
    {"a5200", "Atari 5200", "a5200"},
    {"atari800", "Atari 800", "Atari800"},
    {"prosystem", "ProSystem", "ProSystem"},
    {"virtualjaguar", "Virtual Jaguar", "Virtual Jaguar"},

    // Computers
    {"cap32", "Caprice32", "cap32"},
    {"crocods", "CrocoDS", "crocods"},
    {"hatari", "Hatari", "Hatari"},
    {"hatarib", "HatariB", "hatariB"},
    {"bluemsx", "blueMSX", "blueMSX"},
    {"fmsx", "fMSX", "fMSX"},
    {"px68k", "PX68k", "PX68K"},
    {"x1", "Sharp X1", "x1"},
    {"quasi88", "Quasi88", "QUASI88"},
    {"np2kai", "Neko II Kai", "Neko Project II kai"},
    {"nekop2", "Neko II", "Neko Project II kai"},
    {"vice_x64", "VICE x64", "VICE x64"},
    {"vice_x64sc", "VICE x64SC", "VICE x64sc"},
    {"vice_xscpu64", "VICE xSCPU64", "VICE xscpu64"},
    {"vice_x128", "VICE x128", "VICE x128"},
    {"vice_xpet", "VICE xPET", "VICE xpet"},
    {"vice_xvic", "VICE xVIC", "VICE xvic"},
    {"vice_xcbm2", "VICE xCBM-II", "VICE xcbm2"},
    {"vice_xcbm5x0", "VICE xCBM-5x0", "VICE xcbm5x0"},
    {"puae", "PUAE", "PUAE"},
    {"puae2021", "PUAE 2021", "PUAE"},
    {"uae4arm", "UAE4ARM", "uae4arm"},
    {"km_puae_xtreme_amped_2k24", "PUAE Xtreme", "PUAE"},

    // DOS / PC
    {"dosbox_pure", "DOSBox Pure", "DOSBox-pure"},
    {"dosbox_svn", "DOSBox SVN", "DOSBox-svn"},

    // Misc
    {"scummvm", "ScummVM", "ScummVM"},
    {"prboom", "PrBoom", "PrBoom"},
    {"ecwolf", "ECWolf", "ecwolf"},
    {"nxengine", "NXEngine", "NXEngine"},
    {"tic80", "TIC-80", "TIC-80"},
    {"lutro", "Lutro", "lutro"},
    {"freeintv", "FreeIntv", "FreeIntv"},
    {"o2em", "O2EM", "O2EM"},
    {"vecx", "VecX", "VecX"},
    {"pokemini", "PokeMini", "PokeMini"},
    {"opera", "Opera", "Opera"},
    {"vircon32", "Vircon32", "Vircon32"},
    {"uzem", "Uzem", "Uzem"},
    {"potator", "Potator", "Potator"},
    {"wasm4", "WASM-4", "WASM-4"},
    {"fake08", "Fake-08", "fake-08"},
    {"retro8", "Retro8", "retro-8"},
    {"neocd", "NeoCD", "NeoCD"},
    {"race", "RACE", "RACE"},
    {"geolith", "Geolith", "Geolith"},
    {"mednafen_wswan", "Beetle WonderSwan", "Beetle WonderSwan"},
    {"mednafen_ngp", "Beetle NeoPop", "Beetle NeoPop"},
    {"mednafen_pce", "Beetle PCE", "Beetle PCE"},
    {"mednafen_pce_fast", "Beetle PCE Fast", "Beetle PCE Fast"},
    {"mednafen_supergrafx", "Beetle SuperGrafx", "Beetle SuperGrafx"},
    {"same_cdi", "SameCD-i", "SAME_CDI"},
    {"easyrpg", "EasyRPG", "EasyRPG Player"},
    {"onscripter", "ONScripter", "ONScripter"},
    {"onsyuri", "ONS Yuri", "ONScripter"},
    {"numero", "Numero", "Numero"},
    {"lowresnx", "LowRes NX", "LowRes NX"},
    {"dice", "DICE", "DICE"},
    {"freechaf", "FreeChaF", "FreeChaF"},
    {"galaksija", "Galaksija", "Galaksija"},
    {"jaxe", "JAXE", "JAXE"},
    {"chailove", "ChaiLove", "ChaiLove"},
    {"ardens", "Ardens", "Ardens"},
    {"arduous", "Arduous", "Arduous"},
    {"libgametank", "GameTank", "Game Tank"},
    {"vemulator", "VeMUlator", "VeMUlator"},
    {"sameduck", "SameDuck", "SameDuck"},
    {"tyrquake", "TyrQuake", "TyrQuake"},
    {"vitaquake2", "VitaQuake II", "VitaQuakeII"},

    // Cores that ship without an entry above. Display names are the curated ones from the
    // system assignments. The third value is RetroArch's own core name, confirmed against
    // the core binary where it could be; the rest repeat the display name, as most of the
    // entries above already do.
    {"2048", "2048", "2048"},
    {"81", "EightyOne", "EightyOne"},
    {"amiberry", "Amiberry Libretro", "Amiberry Libretro"},
    {"bennugd", "BennuGD", "BennuGD"},
    {"bk", "BK", "BK"},
    {"bnes", "BNES", "BNES"},
    {"bsnes-jg", "bsnes-jg", "bsnes-jg"},
    {"cannonball", "Cannonball", "Cannonball"},
    {"daphne", "Daphne", "Daphne"},
    {"desmume2015", "DeSmuME 2015", "DeSmuME 2015"},
    {"dirksimple", "DirkSimple", "DirkSimple"},
    {"dosbox_core", "DOSBox-core", "DOSBox-core"},
    {"emuscv", "EmuSCV", "EmuSCV"},
    {"emux_chip8", "Emux CHIP-8", "Emux CHIP-8"},
    {"emux_gb", "Emux GB", "Emux GB"},
    {"emux_nes", "Emux NES", "Emux NES"},
    {"emux_sms", "Emux SMS", "Emux SMS"},
    {"ep128emu_core", "ep128emu", "ep128emu"},
    {"fbalpha", "FB Alpha", "FB Alpha"},
    {"fceunext", "FCEUNext", "FCEUNext"},
    {"freej2me", "FreeJ2ME - RetroArch", "FreeJ2ME - RetroArch"},
    {"frodo", "Frodo", "Frodo"},
    {"fuse", "Fuse", "Fuse"},
    {"gearcoleco", "Gearcoleco", "Gearcoleco"},
    {"geargrafx", "Geargrafx", "Geargrafx"},
    {"gme", "Game Music Emu", "Game Music Emu"},
    {"gw", "Handheld Electronic", "Handheld Electronic"},
    {"km_ludicrousn64_2k22_xtreme_amped", "Ludicrous N64 2k22 Xtreme Amped", "Ludicrous N64 2k22 Xtreme Amped"},
    {"km_morpheuscast_xtreme", "MorpheusCast Xtreme", "MorpheusCast Xtreme"},
    {"mednafen_pcfx", "Beetle PC-FX", "Beetle PC-FX"},
    {"melonds", "melonDS", "melonDS"},
    {"melondsds", "melonDS-DS", "melonDS DS"},
    {"minivmac", "Mini vMac", "Mini vMac"},
    {"mu", "Mu", "Mu"},
    {"mupen64plus", "Mupen64Plus", "Mupen64Plus"},
    {"openlara", "OpenLara", "OpenLara"},
    {"parallel_n64", "ParaLLel N64", "ParaLLel N64"},
    {"pcfx", "PC-FX", "PC-FX"},
    {"pocketcdg", "PocketCDG", "PocketCDG"},
    {"pocketsnes", "PocketSNES", "PocketSNES"},
    {"press_f", "Press F", "Press F"},
    {"puzzlescript", "PuzzleScript", "PuzzleScript"},
    {"superbroswar", "Super Mario War", "Super Mario War"},
    {"theodore", "Theodore", "Theodore"},
    {"uw8", "MicroW8", "MicroW8"},
    {"vb", "VB", "VB"},
    {"vice_x64dtv", "VICE x64 DTV", "VICE x64 DTV"},
    {"vice_xplus4", "VICE xplus4", "VICE xplus4"},
    {"vitaquake2-rogue", "VitaQuake2 - Rogue Mission Pack", "VitaQuake2 - Rogue Mission Pack"},
    {"vitaquake2-xatrix", "VitaQuake2 - Xatrix Mission Pack", "VitaQuake2 - Xatrix Mission Pack"},
    {"vitaquake2-zaero", "VitaQuake2 - Zaero Mission Pack", "VitaQuake2 - Zaero Mission Pack"},
    {"zc210", "Zelda Classic 2.10", "Zelda Classic 2.10"},
    {"zc250x", "Zelda Classic 2.50x", "Zelda Classic 2.50x"},

    {NULL, NULL, NULL}
};
