// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxplore

#ifndef _MUXPLORE_UI_H
#define _MUXPLORE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "../../common/theme.h"

extern lv_obj_t * ui_lblCounter;
void ui_init(lv_obj_t * ui_screen, struct theme_config *theme);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
