// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxcredits

#ifndef _MUXCREDITS_UI_H
#define _MUXCREDITS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void animScroll_Animation(lv_obj_t * TargetObject, int delay);
void animFade_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_scrCredits
void ui_scrCredits_screen_init(void);
extern lv_obj_t * ui_scrCredits;
extern lv_obj_t * ui_conCredits;
extern lv_obj_t * ui_conStart;
extern lv_obj_t * ui_lblStartTitle;
extern lv_obj_t * ui_lblStartMessage;
extern lv_obj_t * ui_conScroll;
extern lv_obj_t * ui_lblOfficialTitle;
extern lv_obj_t * ui_lblCommanderTitle;
extern lv_obj_t * ui_lblCommanderPeople;
extern lv_obj_t * ui_lblEnforcerTitle;
extern lv_obj_t * ui_lblEnforcerPeople;
extern lv_obj_t * ui_lblWizardTitle;
extern lv_obj_t * ui_lblWizardLeft;
extern lv_obj_t * ui_lblWizardRight;
extern lv_obj_t * ui_lblHeroTitle;
extern lv_obj_t * ui_lblHeroLeft;
extern lv_obj_t * ui_lblHeroRight;
extern lv_obj_t * ui_lblKnightTitle;
extern lv_obj_t * ui_lblKnightLeft;
extern lv_obj_t * ui_lblKnightRight;
extern lv_obj_t * ui_conKofi;
extern lv_obj_t * ui_lblKofiTitle;
extern lv_obj_t * ui_lblKofiMessageOne;
extern lv_obj_t * ui_lblKofiMessageTwo;
extern lv_obj_t * ui_imgKofi;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_muoskofi_png);    // assets/muoskofi.png
LV_IMG_DECLARE(ui_img_nothing_png);    // assets/nothing.png


LV_FONT_DECLARE(ui_font_Awesome);
LV_FONT_DECLARE(ui_font_AwesomeBig);
LV_FONT_DECLARE(ui_font_AwesomeBrand);
LV_FONT_DECLARE(ui_font_AwesomeBrandSmall);
LV_FONT_DECLARE(ui_font_AwesomeSmall);
LV_FONT_DECLARE(ui_font_Gamepad);
LV_FONT_DECLARE(ui_font_GamepadNav);
LV_FONT_DECLARE(ui_font_JGS_Ascii);
LV_FONT_DECLARE(ui_font_NotoSans);
LV_FONT_DECLARE(ui_font_NotoSansBig);
LV_FONT_DECLARE(ui_font_NotoSansSmall);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
