// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxnetwork

#ifndef _MUXNETWORK_UI_H
#define _MUXNETWORK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrNetwork
void ui_scrNetwork_screen_init(void);
extern lv_obj_t * ui_scrNetwork;
extern lv_obj_t * ui_pnlWall;
extern lv_obj_t * ui_imgWall;
extern lv_obj_t * ui_pnlBox;
extern lv_obj_t * ui_imgBox;
extern lv_obj_t * ui_pnlHeader;
extern lv_obj_t * ui_lblDatetime;
extern lv_obj_t * ui_lblTitle;
extern lv_obj_t * ui_conGlyphs;
extern lv_obj_t * ui_staBluetooth;
extern lv_obj_t * ui_staNetwork;
extern lv_obj_t * ui_staCapacity;
extern lv_obj_t * ui_pnlContent;
extern lv_obj_t * ui_lblEnable;
extern lv_obj_t * ui_lblIdentifier;
extern lv_obj_t * ui_lblPassword;
extern lv_obj_t * ui_lblType;
extern lv_obj_t * ui_lblAddress;
extern lv_obj_t * ui_lblSubnet;
extern lv_obj_t * ui_lblGateway;
extern lv_obj_t * ui_lblDNS;
extern lv_obj_t * ui_lblConnect;
extern lv_obj_t * ui_lblBlankOne;
extern lv_obj_t * ui_lblBlankTwo;
extern lv_obj_t * ui_lblBlankThree;
extern lv_obj_t * ui_lblBlankFour;
extern lv_obj_t * ui_lblBlankFive;
extern lv_obj_t * ui_lblBlankSix;
extern lv_obj_t * ui_lblBlankSeven;
extern lv_obj_t * ui_lblStatus;
extern lv_obj_t * ui_pnlGlyph;
extern lv_obj_t * ui_icoEnable;
extern lv_obj_t * ui_icoIdentifier;
extern lv_obj_t * ui_icoPassword;
extern lv_obj_t * ui_icoType;
extern lv_obj_t * ui_icoAddress;
extern lv_obj_t * ui_icoSubnet;
extern lv_obj_t * ui_icoGateway;
extern lv_obj_t * ui_icoDNS;
extern lv_obj_t * ui_icoConnect;
extern lv_obj_t * ui_icoBlankOne;
extern lv_obj_t * ui_icoBlankTwo;
extern lv_obj_t * ui_icoBlankThree;
extern lv_obj_t * ui_icoBlankFour;
extern lv_obj_t * ui_icoBlankFive;
extern lv_obj_t * ui_icoBlankSix;
extern lv_obj_t * ui_icoBlankSeven;
extern lv_obj_t * ui_icoStatus;
extern lv_obj_t * ui_pnlHighlight;
extern lv_obj_t * ui_lblEnableValue;
extern lv_obj_t * ui_lblIdentifierValue;
extern lv_obj_t * ui_lblPasswordValue;
extern lv_obj_t * ui_lblTypeValue;
extern lv_obj_t * ui_lblAddressValue;
extern lv_obj_t * ui_lblSubnetValue;
extern lv_obj_t * ui_lblGatewayValue;
extern lv_obj_t * ui_lblDNSValue;
extern lv_obj_t * ui_lblConnectValue;
extern lv_obj_t * ui_lblBlankOneValue;
extern lv_obj_t * ui_lblBlankTwoValue;
extern lv_obj_t * ui_lblBlankThreeValue;
extern lv_obj_t * ui_lblBlankFourValue;
extern lv_obj_t * ui_lblBlankFiveValue;
extern lv_obj_t * ui_lblBlankSixValue;
extern lv_obj_t * ui_lblBlankSevenValue;
extern lv_obj_t * ui_lblStatusValue;
extern lv_obj_t * ui_pnlFooter;
extern lv_obj_t * ui_lblNavAGlyph;
extern lv_obj_t * ui_lblNavA;
extern lv_obj_t * ui_lblNavBGlyph;
extern lv_obj_t * ui_lblNavB;
extern lv_obj_t * ui_lblNavCGlyph;
extern lv_obj_t * ui_lblNavC;
extern lv_obj_t * ui_lblNavXGlyph;
extern lv_obj_t * ui_lblNavX;
extern lv_obj_t * ui_lblNavYGlyph;
extern lv_obj_t * ui_lblNavY;
extern lv_obj_t * ui_lblNavZGlyph;
extern lv_obj_t * ui_lblNavZ;
extern lv_obj_t * ui_lblNavMenuGlyph;
extern lv_obj_t * ui_lblNavMenu;
extern lv_obj_t * ui_pnlMessage;
extern lv_obj_t * ui_lblMessage;
extern lv_obj_t * ui_pnlEntry;
extern lv_obj_t * ui_txtEntry;
extern lv_obj_t * ui_pnlHelp;
extern lv_obj_t * ui_pnlHelpMessage;
extern lv_obj_t * ui_lblHelpHeader;
extern lv_obj_t * ui_lblHelpContent;
extern lv_obj_t * ui_pnlProgress;
extern lv_obj_t * ui_icoProgress;
extern lv_obj_t * ui_barProgress;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_nothing_png);    // assets/nothing.png
LV_IMG_DECLARE(ui_img_muoskofi_png);    // assets/muoskofi.png


LV_FONT_DECLARE(ui_font_Awesome);
LV_FONT_DECLARE(ui_font_AwesomeBig);
LV_FONT_DECLARE(ui_font_AwesomeBrand);
LV_FONT_DECLARE(ui_font_AwesomeBrandSmall);
LV_FONT_DECLARE(ui_font_AwesomeSmall);
LV_FONT_DECLARE(ui_font_Gamepad);
LV_FONT_DECLARE(ui_font_GamepadNav);
LV_FONT_DECLARE(ui_font_NotoSans);
LV_FONT_DECLARE(ui_font_NotoSansBig);
LV_FONT_DECLARE(ui_font_NotoSansSmall);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
