#pragma once

#define MUOS_CONTRACT_VERSION       "1"
#define MUOS_OPT_PATH               "/opt/muos/"
#define MUOS_RUN_PATH               "/run/muos/"
#define MUOS_SAFE_QUIT              "/run/muos/safe_quit"
#define MUOS_IDLE_STATE             "/run/muos/idle_state"
#define MUOS_NOTIFY_DROP            "/run/muos/notify"
#define MUOS_WAKE_CPU_GOV           "/run/muos/wake_cpu_gov"
#define MUOS_ACTION_FILE            "/run/muos/action"
#define MUOS_APPLICATION_FILE       "/run/muos/application"
#define MUOS_GOVERNOR_FILE          "/run/muos/governor"
#define MUOS_CONTROLLER_FILE        "/run/muos/controller"
#define MUOS_FILTER_FILE            "/run/muos/filter"
#define MUOS_RETROARCH_FILE         "/run/muos/retroarch"
#define MUOS_CONTENT_FILE           "/run/muos/content"
#define MUOS_AUTO_CORE_FILE         "/run/muos/auto_core"
#define MUOS_AUTO_GOVERNOR_FILE     "/run/muos/auto_governor"
#define MUOS_AUTO_RETROARCH_FILE    "/run/muos/auto_retroarch"
#define MUOS_SHADER_FILE            "/run/muos/shader"
#define MUOS_OVERLAY_FILE           "/run/muos/overlay"
#define MUOS_OVERLAY_OPTIONS_FILE   "/run/muos/overlay_options"
#define MUOS_PICKLES_SAVE_READY     "/run/muos/muxretro_save_ready"
#define MUOS_PICKLES_SUSPEND_SIGNAL "USR1"
#define MUOS_PICKLES_RESUME_SIGNAL  "USR2"
#define MUOS_SETTING_ACTIVITY       "settings/advanced/activity"
#define MUOS_MUXRETRO_CLI_VERSION   "1"
#define MUOS_TASK_PROTOCOL_VERSION  "1"
