#pragma once

#include <stddef.h>
#include "options.h"

extern struct mux_lang lang;

extern char *disabled_enabled[];
extern char *excluded_included[];
extern char *allowed_restricted[];
extern char *hidden_visible[];
extern char *toggle_icon_visible[];
extern char *battery_display[];
extern char *debug_log_mode[];
extern char *scroll_speed[];

struct mux_lang {
    struct {
        char no_joy_general[MAX_BUFFER_SIZE];
        char no_joy_power[MAX_BUFFER_SIZE];
        char no_joy_volume[MAX_BUFFER_SIZE];
        char no_joy_extra[MAX_BUFFER_SIZE];
        char fail_allocate_mem[MAX_BUFFER_SIZE];
        char fail_dup_string[MAX_BUFFER_SIZE];
        char fail_dir_open[MAX_BUFFER_SIZE];
        char fail_file_open[MAX_BUFFER_SIZE];
        char fail_file_write[MAX_BUFFER_SIZE];
        char fail_file_read[MAX_BUFFER_SIZE];
        char fail_fork[MAX_BUFFER_SIZE];
        char fail_run_command[MAX_BUFFER_SIZE];
        char fail_read_command[MAX_BUFFER_SIZE];
        char fail_close_command[MAX_BUFFER_SIZE];
        char fail_delete_file[MAX_BUFFER_SIZE];
        char fail_create_file[MAX_BUFFER_SIZE];
        char fail_stat[MAX_BUFFER_SIZE];
        char fail_proc_part[MAX_BUFFER_SIZE];
        char fail_int16_length[MAX_BUFFER_SIZE];
    } system;

    struct {
        char add[MAX_BUFFER_SIZE];
        char add_collect[MAX_BUFFER_SIZE];
        char allowed[MAX_BUFFER_SIZE];
        char back[MAX_BUFFER_SIZE];
        char backspace[MAX_BUFFER_SIZE];
        char cannot_delete_active_theme[MAX_BUFFER_SIZE];
        char change[MAX_BUFFER_SIZE];
        char channel[MAX_BUFFER_SIZE];
        char check[MAX_BUFFER_SIZE];
        char clear[MAX_BUFFER_SIZE];
        char close[MAX_BUFFER_SIZE];
        char confirm[MAX_BUFFER_SIZE];
        char collect[MAX_BUFFER_SIZE];
        char content[MAX_BUFFER_SIZE];
        char details[MAX_BUFFER_SIZE];
        char directory[MAX_BUFFER_SIZE];
        char disabled[MAX_BUFFER_SIZE];
        char download[MAX_BUFFER_SIZE];
        char edit[MAX_BUFFER_SIZE];
        char output[MAX_BUFFER_SIZE];
        char enabled[MAX_BUFFER_SIZE];
        char excluded[MAX_BUFFER_SIZE];
        char extract[MAX_BUFFER_SIZE];
        char extracting_archive[MAX_BUFFER_SIZE];
        char filter[MAX_BUFFER_SIZE];
        char forget[MAX_BUFFER_SIZE];
        char hidden[MAX_BUFFER_SIZE];
        char hold_remove[MAX_BUFFER_SIZE];
        char hold_reset[MAX_BUFFER_SIZE];
        char included[MAX_BUFFER_SIZE];
        char info[MAX_BUFFER_SIZE];
        char install[MAX_BUFFER_SIZE];
        char kiosk_disable[MAX_BUFFER_SIZE];
        char launch[MAX_BUFFER_SIZE];
        char loading[MAX_BUFFER_SIZE];
        char load[MAX_BUFFER_SIZE];
        char migrate[MAX_BUFFER_SIZE];
        char need_connect[MAX_BUFFER_SIZE];
        char invalid_time[MAX_BUFFER_SIZE];
        char new[MAX_BUFFER_SIZE];
        char noglyph[MAX_BUFFER_SIZE];
        char not_connected[MAX_BUFFER_SIZE];
        char no_help[MAX_BUFFER_SIZE];
        char no_info[MAX_BUFFER_SIZE];
        char no_load[MAX_BUFFER_SIZE];
        char no_slideshow_image[MAX_BUFFER_SIZE];
        char offline[MAX_BUFFER_SIZE];
        char online[MAX_BUFFER_SIZE];
        char open[MAX_BUFFER_SIZE];
        char option[MAX_BUFFER_SIZE];
        char preview[MAX_BUFFER_SIZE];
        char previous[MAX_BUFFER_SIZE];
        char read[MAX_BUFFER_SIZE];
        char rebooting[MAX_BUFFER_SIZE];
        char recursive[MAX_BUFFER_SIZE];
        char refresh[MAX_BUFFER_SIZE];
        char refresh_run[MAX_BUFFER_SIZE];
        char remove[MAX_BUFFER_SIZE];
        char remove_fail[MAX_BUFFER_SIZE];
        char rescan[MAX_BUFFER_SIZE];
        char reset[MAX_BUFFER_SIZE];
        char restore[MAX_BUFFER_SIZE];
        char restricted[MAX_BUFFER_SIZE];
        char save[MAX_BUFFER_SIZE];
        char saving[MAX_BUFFER_SIZE];
        char scan[MAX_BUFFER_SIZE];
        char scroll[MAX_BUFFER_SIZE];
        char select[MAX_BUFFER_SIZE];
        char set[MAX_BUFFER_SIZE];
        char shutting_down[MAX_BUFFER_SIZE];
        char space[MAX_BUFFER_SIZE];
        char storage[MAX_BUFFER_SIZE];
        char switch_image[MAX_BUFFER_SIZE];
        char switch_info[MAX_BUFFER_SIZE];
        char sync[MAX_BUFFER_SIZE];
        char toggle_all[MAX_BUFFER_SIZE];
        char top[MAX_BUFFER_SIZE];
        char type[MAX_BUFFER_SIZE];
        char unknown[MAX_BUFFER_SIZE];
        char user_defined[MAX_BUFFER_SIZE];
        char use[MAX_BUFFER_SIZE];
        char visible[MAX_BUFFER_SIZE];
        char sunday[MAX_BUFFER_SIZE];
        char monday[MAX_BUFFER_SIZE];
        char tuesday[MAX_BUFFER_SIZE];
        char wednesday[MAX_BUFFER_SIZE];
        char thursday[MAX_BUFFER_SIZE];
        char friday[MAX_BUFFER_SIZE];
        char saturday[MAX_BUFFER_SIZE];
        char cancel[MAX_BUFFER_SIZE];
        char understand[MAX_BUFFER_SIZE];
        char warning[MAX_BUFFER_SIZE];
        char skip_confirm[MAX_BUFFER_SIZE];
        char unsafe_archive[MAX_BUFFER_SIZE];
        char clean[MAX_BUFFER_SIZE];
        char discard[MAX_BUFFER_SIZE];
        char assign_desc[MAX_BUFFER_SIZE];
        char modified[MAX_BUFFER_SIZE];
        char icon_only[MAX_BUFFER_SIZE];
        char text_only[MAX_BUFFER_SIZE];
        char text_icon[MAX_BUFFER_SIZE];
        char standard[MAX_BUFFER_SIZE];
        char verbose[MAX_BUFFER_SIZE];
        char slow[MAX_BUFFER_SIZE];
        char medium[MAX_BUFFER_SIZE];
        char fast[MAX_BUFFER_SIZE];
        char low[MAX_BUFFER_SIZE];
        char high[MAX_BUFFER_SIZE];
        char minimal[MAX_BUFFER_SIZE];
        char maximum[MAX_BUFFER_SIZE];
        char horizontal[MAX_BUFFER_SIZE];
        char vertical[MAX_BUFFER_SIZE];
        char up[MAX_BUFFER_SIZE];
        char down[MAX_BUFFER_SIZE];
        char left[MAX_BUFFER_SIZE];
        char right[MAX_BUFFER_SIZE];
        char all[MAX_BUFFER_SIZE];
        char ludicrous[MAX_BUFFER_SIZE];
        char unsaved[MAX_BUFFER_SIZE];
        char crash_title[MAX_BUFFER_SIZE];
        char crash_message[MAX_BUFFER_SIZE];
        char crash_module[MAX_BUFFER_SIZE];
        char crash_fault[MAX_BUFFER_SIZE];
        char random[MAX_BUFFER_SIZE];
        char power_loss_title[MAX_BUFFER_SIZE];
        char power_loss_message[MAX_BUFFER_SIZE];
    } generic;

    struct {
        char title[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char info[MAX_BUFFER_SIZE];
        char launch[MAX_BUFFER_SIZE];
        char time[MAX_BUFFER_SIZE];
        char html[MAX_BUFFER_SIZE];
        char unique[MAX_BUFFER_SIZE];
        char export_success[MAX_BUFFER_SIZE];
        char export_error[MAX_BUFFER_SIZE];
        char removed[MAX_BUFFER_SIZE];
        struct {
            char name[MAX_BUFFER_SIZE];
            char core[MAX_BUFFER_SIZE];
            char launch[MAX_BUFFER_SIZE];
            char device[MAX_BUFFER_SIZE];
            char mode[MAX_BUFFER_SIZE];
            char played[MAX_BUFFER_SIZE];
            char average[MAX_BUFFER_SIZE];
            char total[MAX_BUFFER_SIZE];
            char last[MAX_BUFFER_SIZE];
        } detail;
        struct {
            char nav[MAX_BUFFER_SIZE];
            char top_time[MAX_BUFFER_SIZE];
            char top_launch[MAX_BUFFER_SIZE];
            char core[MAX_BUFFER_SIZE];
            char device[MAX_BUFFER_SIZE];
            char mode[MAX_BUFFER_SIZE];
            char launch[MAX_BUFFER_SIZE];
            char total[MAX_BUFFER_SIZE];
            char average[MAX_BUFFER_SIZE];
            char oldest[MAX_BUFFER_SIZE];
            char longest[MAX_BUFFER_SIZE];
            char overall[MAX_BUFFER_SIZE];
            char unique_play[MAX_BUFFER_SIZE];
            char unique_core[MAX_BUFFER_SIZE];
            char active_time[MAX_BUFFER_SIZE];
            char favourite_day[MAX_BUFFER_SIZE];
        } global;
        struct {
            struct {
                char label[MAX_BUFFER_SIZE];
                char one[MAX_BUFFER_SIZE];
                char sampler[MAX_BUFFER_SIZE];
                char burst[MAX_BUFFER_SIZE];
                char lng[MAX_BUFFER_SIZE];
                char completionist[MAX_BUFFER_SIZE];
                char abandoned[MAX_BUFFER_SIZE];
                char marathoner[MAX_BUFFER_SIZE];
                char returner[MAX_BUFFER_SIZE];
                char on_off[MAX_BUFFER_SIZE];
                char weekend[MAX_BUFFER_SIZE];
                char comfort[MAX_BUFFER_SIZE];
                char regular[MAX_BUFFER_SIZE];
            } local;
            struct {
                char label[MAX_BUFFER_SIZE];
                char casual[MAX_BUFFER_SIZE];
                char core[MAX_BUFFER_SIZE];
                char explorer[MAX_BUFFER_SIZE];
                char binger[MAX_BUFFER_SIZE];
                char completionist[MAX_BUFFER_SIZE];
                char power[MAX_BUFFER_SIZE];
                char collector[MAX_BUFFER_SIZE];
                char specialist[MAX_BUFFER_SIZE];
                char nomad[MAX_BUFFER_SIZE];
                char routine[MAX_BUFFER_SIZE];
                char habitual[MAX_BUFFER_SIZE];
                char window[MAX_BUFFER_SIZE];
            } global;
        } style;
    } muxactivity;

    struct {
        char load_app[MAX_BUFFER_SIZE];
        char no_app[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
        char archive[MAX_BUFFER_SIZE];
        char task[MAX_BUFFER_SIZE];
    } muxapp;

    struct {
        char title[MAX_BUFFER_SIZE];
        char name[MAX_BUFFER_SIZE];
        char governor[MAX_BUFFER_SIZE];
        char control[MAX_BUFFER_SIZE];
        struct {
            char governor[MAX_BUFFER_SIZE];
            char control[MAX_BUFFER_SIZE];
        } help;
    } muxappcon;

    struct {
        char help[MAX_BUFFER_SIZE];
        char installed[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
    } muxarchive;

    struct {
        char dir[MAX_BUFFER_SIZE];
        char file[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
        char core_down[MAX_BUFFER_SIZE];
        char misconfigured[MAX_BUFFER_SIZE];
    } muxassign;

    struct {
        char title[MAX_BUFFER_SIZE];
        char apps[MAX_BUFFER_SIZE];
        char bios[MAX_BUFFER_SIZE];
        char catalogue[MAX_BUFFER_SIZE];
        char cheats[MAX_BUFFER_SIZE];
        char collection[MAX_BUFFER_SIZE];
        char config[MAX_BUFFER_SIZE];
        char content[MAX_BUFFER_SIZE];
        char history[MAX_BUFFER_SIZE];
        char init[MAX_BUFFER_SIZE];
        char music[MAX_BUFFER_SIZE];
        char name[MAX_BUFFER_SIZE];
        char network[MAX_BUFFER_SIZE];
        char overlays[MAX_BUFFER_SIZE];
        char override[MAX_BUFFER_SIZE];
        char package[MAX_BUFFER_SIZE];
        char save[MAX_BUFFER_SIZE];
        char screenshot[MAX_BUFFER_SIZE];
        char shaders[MAX_BUFFER_SIZE];
        char syncthing[MAX_BUFFER_SIZE];
        char theme[MAX_BUFFER_SIZE];
        char track[MAX_BUFFER_SIZE];
        char target[MAX_BUFFER_SIZE];
        char merge[MAX_BUFFER_SIZE];
        char start[MAX_BUFFER_SIZE];
        struct {
            char apps[MAX_BUFFER_SIZE];
            char bios[MAX_BUFFER_SIZE];
            char catalogue[MAX_BUFFER_SIZE];
            char cheats[MAX_BUFFER_SIZE];
            char collection[MAX_BUFFER_SIZE];
            char config[MAX_BUFFER_SIZE];
            char content[MAX_BUFFER_SIZE];
            char history[MAX_BUFFER_SIZE];
            char init[MAX_BUFFER_SIZE];
            char music[MAX_BUFFER_SIZE];
            char name[MAX_BUFFER_SIZE];
            char network[MAX_BUFFER_SIZE];
            char overlays[MAX_BUFFER_SIZE];
            char override[MAX_BUFFER_SIZE];
            char package[MAX_BUFFER_SIZE];
            char save[MAX_BUFFER_SIZE];
            char screenshot[MAX_BUFFER_SIZE];
            char shaders[MAX_BUFFER_SIZE];
            char syncthing[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
            char track[MAX_BUFFER_SIZE];
            char target[MAX_BUFFER_SIZE];
            char merge[MAX_BUFFER_SIZE];
            char start[MAX_BUFFER_SIZE];
        } help;
    } muxbackup;

    struct {
        char title[MAX_BUFFER_SIZE];
        char capacity[MAX_BUFFER_SIZE];
        char voltage[MAX_BUFFER_SIZE];
        char status[MAX_BUFFER_SIZE];
        char health[MAX_BUFFER_SIZE];
        char design_cap[MAX_BUFFER_SIZE];
        char last_charged[MAX_BUFFER_SIZE];
        char time_on_battery[MAX_BUFFER_SIZE];
        char battery_used[MAX_BUFFER_SIZE];
        char charger[MAX_BUFFER_SIZE];
        struct {
            char capacity[MAX_BUFFER_SIZE];
            char voltage[MAX_BUFFER_SIZE];
            char status[MAX_BUFFER_SIZE];
            char health[MAX_BUFFER_SIZE];
            char design_cap[MAX_BUFFER_SIZE];
            char last_charged[MAX_BUFFER_SIZE];
            char time_on_battery[MAX_BUFFER_SIZE];
            char battery_used[MAX_BUFFER_SIZE];
            char charger[MAX_BUFFER_SIZE];
        } help;
    } muxbatinfo;

    struct {
        char boot[MAX_BUFFER_SIZE];
        char capacity[MAX_BUFFER_SIZE];
        char start[MAX_BUFFER_SIZE];
        char voltage[MAX_BUFFER_SIZE];
    } muxcharge;

    struct {
        char title[MAX_BUFFER_SIZE];
        char reference[MAX_BUFFER_SIZE];
        char stratum[MAX_BUFFER_SIZE];
        char ref_time[MAX_BUFFER_SIZE];
        char system_time[MAX_BUFFER_SIZE];
        char last_offset[MAX_BUFFER_SIZE];
        char rms_offset[MAX_BUFFER_SIZE];
        char frequency[MAX_BUFFER_SIZE];
        char root_delay[MAX_BUFFER_SIZE];
        char root_disp[MAX_BUFFER_SIZE];
        char update_int[MAX_BUFFER_SIZE];
        char leap[MAX_BUFFER_SIZE];
        struct {
            char reference[MAX_BUFFER_SIZE];
            char stratum[MAX_BUFFER_SIZE];
            char ref_time[MAX_BUFFER_SIZE];
            char system_time[MAX_BUFFER_SIZE];
            char last_offset[MAX_BUFFER_SIZE];
            char rms_offset[MAX_BUFFER_SIZE];
            char frequency[MAX_BUFFER_SIZE];
            char root_delay[MAX_BUFFER_SIZE];
            char root_disp[MAX_BUFFER_SIZE];
            char update_int[MAX_BUFFER_SIZE];
            char leap[MAX_BUFFER_SIZE];
        } help;
    } muxchrony;

    struct {
        char title[MAX_BUFFER_SIZE];
        char schedule[MAX_BUFFER_SIZE];
        char sunrise_temp[MAX_BUFFER_SIZE];
        char sunset_temp[MAX_BUFFER_SIZE];
        char sunrise_time[MAX_BUFFER_SIZE];
        char sunset_time[MAX_BUFFER_SIZE];
        char temperature[MAX_BUFFER_SIZE];
        char invalid_time[MAX_BUFFER_SIZE];
        struct {
            char schedule[MAX_BUFFER_SIZE];
            char sunrise_temp[MAX_BUFFER_SIZE];
            char sunset_temp[MAX_BUFFER_SIZE];
            char sunrise_time[MAX_BUFFER_SIZE];
            char sunset_time[MAX_BUFFER_SIZE];
            char temperature[MAX_BUFFER_SIZE];
        } help;
    } muxdistemp;

    struct {
        char title[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
    } muxcolfilter;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        struct {
            char remove_file[MAX_BUFFER_SIZE];
            char remove_dir[MAX_BUFFER_SIZE];
            char load[MAX_BUFFER_SIZE];
        } error;
    } muxcollect;

    struct {
        char connect[MAX_BUFFER_SIZE];
        char custom[MAX_BUFFER_SIZE];
        char general[MAX_BUFFER_SIZE];
        char language[MAX_BUFFER_SIZE];
        char storage[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
        char power[MAX_BUFFER_SIZE];
        char interface[MAX_BUFFER_SIZE];
        char backup[MAX_BUFFER_SIZE];
        struct {
            char connect[MAX_BUFFER_SIZE];
            char custom[MAX_BUFFER_SIZE];
            char general[MAX_BUFFER_SIZE];
            char language[MAX_BUFFER_SIZE];
            char storage[MAX_BUFFER_SIZE];
            char power[MAX_BUFFER_SIZE];
            char interface[MAX_BUFFER_SIZE];
            char backup[MAX_BUFFER_SIZE];
        } help;
    } muxconfig;

    struct {
        char title[MAX_BUFFER_SIZE];
        char bluetooth[MAX_BUFFER_SIZE];
        char net_adv[MAX_BUFFER_SIZE];
        char proxy[MAX_BUFFER_SIZE];
        char services[MAX_BUFFER_SIZE];
        char network[MAX_BUFFER_SIZE];
        struct {
            char bluetooth[MAX_BUFFER_SIZE];
            char net_adv[MAX_BUFFER_SIZE];
            char proxy[MAX_BUFFER_SIZE];
            char services[MAX_BUFFER_SIZE];
            char network[MAX_BUFFER_SIZE];
        } help;
    } muxconnect;

    struct {
        char title[MAX_BUFFER_SIZE];
        char enabled[MAX_BUFFER_SIZE];
        char type[MAX_BUFFER_SIZE];
        char server[MAX_BUFFER_SIZE];
        char noproxy[MAX_BUFFER_SIZE];
        char test[MAX_BUFFER_SIZE];
        char http[MAX_BUFFER_SIZE];
        char https[MAX_BUFFER_SIZE];
        char socks5[MAX_BUFFER_SIZE];
        char testing[MAX_BUFFER_SIZE];
        char test_ok[MAX_BUFFER_SIZE];
        char test_fail[MAX_BUFFER_SIZE];
        char no_server[MAX_BUFFER_SIZE];
        char saved[MAX_BUFFER_SIZE];
        char reboot[MAX_BUFFER_SIZE];
        struct {
            char enabled[MAX_BUFFER_SIZE];
            char type[MAX_BUFFER_SIZE];
            char server[MAX_BUFFER_SIZE];
            char no_proxy[MAX_BUFFER_SIZE];
            char test[MAX_BUFFER_SIZE];
        } help;
    } muxnetproxy;

    struct {
        char title[MAX_BUFFER_SIZE];
        char auto_connect[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char loading[MAX_BUFFER_SIZE];
        char forget[MAX_BUFFER_SIZE];
        char connect[MAX_BUFFER_SIZE];
        char disconnect[MAX_BUFFER_SIZE];
        char connected[MAX_BUFFER_SIZE];
        char disconnected[MAX_BUFFER_SIZE];
        char forget_confirm[MAX_BUFFER_SIZE];
        struct {
            char auto_connect[MAX_BUFFER_SIZE];
        } help;
    } muxbtall;

    struct {
        char title[MAX_BUFFER_SIZE];
        char scan[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char info[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char connect[MAX_BUFFER_SIZE];
        char disconnect[MAX_BUFFER_SIZE];
    } muxbtcon;

    struct {
        char title[MAX_BUFFER_SIZE];
        char friendly_name[MAX_BUFFER_SIZE];
        char type[MAX_BUFFER_SIZE];
        char battery[MAX_BUFFER_SIZE];
        char address[MAX_BUFFER_SIZE];
        char status[MAX_BUFFER_SIZE];
        char connected[MAX_BUFFER_SIZE];
        char disconnected[MAX_BUFFER_SIZE];
        char connect[MAX_BUFFER_SIZE];
        char disconnect[MAX_BUFFER_SIZE];
        char connecting[MAX_BUFFER_SIZE];
        char disconnecting[MAX_BUFFER_SIZE];
        char connect_failed[MAX_BUFFER_SIZE];
        char disconnect_failed[MAX_BUFFER_SIZE];
        char forget[MAX_BUFFER_SIZE];
        char forget_confirm[MAX_BUFFER_SIZE];
        struct {
            char audio_headset[MAX_BUFFER_SIZE];
            char audio_headphones[MAX_BUFFER_SIZE];
            char audio_speaker[MAX_BUFFER_SIZE];
            char audio_microphone[MAX_BUFFER_SIZE];
            char audio_card[MAX_BUFFER_SIZE];
            char input_gamepad[MAX_BUFFER_SIZE];
            char input_keyboard[MAX_BUFFER_SIZE];
            char input_mouse[MAX_BUFFER_SIZE];
            char input_combo[MAX_BUFFER_SIZE];
            char input_remote[MAX_BUFFER_SIZE];
            char phone[MAX_BUFFER_SIZE];
            char computer[MAX_BUFFER_SIZE];
            char network[MAX_BUFFER_SIZE];
            char unknown[MAX_BUFFER_SIZE];
        } type_name;
        struct {
            char friendly_name[MAX_BUFFER_SIZE];
            char type[MAX_BUFFER_SIZE];
            char battery[MAX_BUFFER_SIZE];
            char address[MAX_BUFFER_SIZE];
            char status[MAX_BUFFER_SIZE];
            char forget[MAX_BUFFER_SIZE];
        } help;
    } muxbtdev;

    struct {
        char title[MAX_BUFFER_SIZE];
        char shuffle[MAX_BUFFER_SIZE];
        char full_width[MAX_BUFFER_SIZE];
        char launch_splash[MAX_BUFFER_SIZE];
        char grid_mode[MAX_BUFFER_SIZE];
        char grid_mode_art[MAX_BUFFER_SIZE];
        struct {
            char title[MAX_BUFFER_SIZE];
            char behind[MAX_BUFFER_SIZE];
            char front[MAX_BUFFER_SIZE];
            char fs_behind[MAX_BUFFER_SIZE];
            char fs_front[MAX_BUFFER_SIZE];
            char original[MAX_BUFFER_SIZE];
            char scale[MAX_BUFFER_SIZE];
            char padding[MAX_BUFFER_SIZE];
            char placeholder[MAX_BUFFER_SIZE];
            struct {
                char title[MAX_BUFFER_SIZE];
                char b_left[MAX_BUFFER_SIZE];
                char b_mid[MAX_BUFFER_SIZE];
                char b_right[MAX_BUFFER_SIZE];
                char m_left[MAX_BUFFER_SIZE];
                char m_mid[MAX_BUFFER_SIZE];
                char m_right[MAX_BUFFER_SIZE];
                char t_left[MAX_BUFFER_SIZE];
                char t_mid[MAX_BUFFER_SIZE];
                char t_right[MAX_BUFFER_SIZE];
            } align;
            struct {
                char title[MAX_BUFFER_SIZE];
                char fade_in[MAX_BUFFER_SIZE];
                char slide_right[MAX_BUFFER_SIZE];
                char slide_left[MAX_BUFFER_SIZE];
                char slide_up[MAX_BUFFER_SIZE];
                char slide_down[MAX_BUFFER_SIZE];
                char bounce_right[MAX_BUFFER_SIZE];
                char bounce_left[MAX_BUFFER_SIZE];
                char bounce_up[MAX_BUFFER_SIZE];
                char bounce_down[MAX_BUFFER_SIZE];
                char shoot_right[MAX_BUFFER_SIZE];
                char shoot_left[MAX_BUFFER_SIZE];
                char shoot_up[MAX_BUFFER_SIZE];
                char shoot_down[MAX_BUFFER_SIZE];
            } transition;
        } box_art;
        struct {
            char title[MAX_BUFFER_SIZE];
            char press_a[MAX_BUFFER_SIZE];
            char hold_a[MAX_BUFFER_SIZE];
            char load_state[MAX_BUFFER_SIZE];
            char start_fresh[MAX_BUFFER_SIZE];
        } launch_swap;
        struct {
            char title[MAX_BUFFER_SIZE];
            char delay_3[MAX_BUFFER_SIZE];
            char delay_5[MAX_BUFFER_SIZE];
            char delay_10[MAX_BUFFER_SIZE];
        } video_preview;
        struct {
            char launch_swap[MAX_BUFFER_SIZE];
            char shuffle[MAX_BUFFER_SIZE];
            char box_art_image[MAX_BUFFER_SIZE];
            char box_art_align[MAX_BUFFER_SIZE];
            char full_width[MAX_BUFFER_SIZE];
            char launch_splash[MAX_BUFFER_SIZE];
            char grid_mode[MAX_BUFFER_SIZE];
            char grid_mode_art[MAX_BUFFER_SIZE];
            char box_art_scale[MAX_BUFFER_SIZE];
            char box_art_padding[MAX_BUFFER_SIZE];
            char box_art_placeholder[MAX_BUFFER_SIZE];
            char box_art_transition[MAX_BUFFER_SIZE];
            char video_preview[MAX_BUFFER_SIZE];
        } help;
    } muxcontent;

    struct {
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
    } muxcontrol;

    struct {
        char catalogue[MAX_BUFFER_SIZE];
        char config[MAX_BUFFER_SIZE];
        char gridmodecontent[MAX_BUFFER_SIZE];
        char theme[MAX_BUFFER_SIZE];
        char themeopt[MAX_BUFFER_SIZE];
        char themeresolution[MAX_BUFFER_SIZE];
        char themescaling[MAX_BUFFER_SIZE];
        char screen[MAX_BUFFER_SIZE];
        char themealternate[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
        char videowallpaper[MAX_BUFFER_SIZE];
        char backgroundscale[MAX_BUFFER_SIZE];
        char blackfade[MAX_BUFFER_SIZE];
        char launchsplash[MAX_BUFFER_SIZE];
        char shuffle[MAX_BUFFER_SIZE];
        char chime[MAX_BUFFER_SIZE];
        char contentwidth[MAX_BUFFER_SIZE];
        char content[MAX_BUFFER_SIZE];
        struct {
            char title[MAX_BUFFER_SIZE];
            char behind[MAX_BUFFER_SIZE];
            char front[MAX_BUFFER_SIZE];
            char hide_grid_mode[MAX_BUFFER_SIZE];
            char fs_behind[MAX_BUFFER_SIZE];
            char fs_front[MAX_BUFFER_SIZE];
            struct {
                char title[MAX_BUFFER_SIZE];
                char b_left[MAX_BUFFER_SIZE];
                char b_mid[MAX_BUFFER_SIZE];
                char b_right[MAX_BUFFER_SIZE];
                char m_left[MAX_BUFFER_SIZE];
                char m_mid[MAX_BUFFER_SIZE];
                char m_right[MAX_BUFFER_SIZE];
                char t_left[MAX_BUFFER_SIZE];
                char t_mid[MAX_BUFFER_SIZE];
                char t_right[MAX_BUFFER_SIZE];
            } align;
        } box_art;
        struct {
            char title[MAX_BUFFER_SIZE];
            char lang[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
        } font;
        struct {
            char title[MAX_BUFFER_SIZE];
            char volume[MAX_BUFFER_SIZE];
            char set[MAX_BUFFER_SIZE];
            char global[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
        } music;
        struct {
            char title[MAX_BUFFER_SIZE];
            char volume[MAX_BUFFER_SIZE];
            char set[MAX_BUFFER_SIZE];
            char global[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
        } sound;
        struct {
            char title[MAX_BUFFER_SIZE];
            char press_a[MAX_BUFFER_SIZE];
            char hold_a[MAX_BUFFER_SIZE];
            char load_state[MAX_BUFFER_SIZE];
            char start_fresh[MAX_BUFFER_SIZE];
        } launch_swap;
        struct {
            char no_scale[MAX_BUFFER_SIZE];
            char scale[MAX_BUFFER_SIZE];
            char stretch[MAX_BUFFER_SIZE];
        } scaling;
        struct {
            char catalogue[MAX_BUFFER_SIZE];
            char config[MAX_BUFFER_SIZE];
            char gridmodecontent[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
            char theme_opt[MAX_BUFFER_SIZE];
            char theme_scaling[MAX_BUFFER_SIZE];
            char theme_resolution[MAX_BUFFER_SIZE];
            char theme_alternate[MAX_BUFFER_SIZE];
            char video_wallpaper[MAX_BUFFER_SIZE];
            char background_scale[MAX_BUFFER_SIZE];
            char boxartimage[MAX_BUFFER_SIZE];
            char boxartalign[MAX_BUFFER_SIZE];
            char boxarthide[MAX_BUFFER_SIZE];
            char contentwidth[MAX_BUFFER_SIZE];
            char black_fade[MAX_BUFFER_SIZE];
            char launchsplash[MAX_BUFFER_SIZE];
            char shuffle[MAX_BUFFER_SIZE];
            char launchswap[MAX_BUFFER_SIZE];
            char font[MAX_BUFFER_SIZE];
            char music[MAX_BUFFER_SIZE];
            char music_volume[MAX_BUFFER_SIZE];
            char sound[MAX_BUFFER_SIZE];
            char sound_volume[MAX_BUFFER_SIZE];
            char chime[MAX_BUFFER_SIZE];
            char content_options[MAX_BUFFER_SIZE];
        } help;
    } muxcustom;

    struct {
        char title[MAX_BUFFER_SIZE];
        char type[MAX_BUFFER_SIZE];
        char name[MAX_BUFFER_SIZE];
        char list_size[MAX_BUFFER_SIZE];
        char header_size[MAX_BUFFER_SIZE];
        char footer_size[MAX_BUFFER_SIZE];
        char panel_size[MAX_BUFFER_SIZE];
        char size_default[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        struct {
            char language[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
            char internal[MAX_BUFFER_SIZE];
        } type_options;
        struct {
            char type[MAX_BUFFER_SIZE];
            char name[MAX_BUFFER_SIZE];
            char list_size[MAX_BUFFER_SIZE];
            char header_size[MAX_BUFFER_SIZE];
            char footer_size[MAX_BUFFER_SIZE];
            char panel_size[MAX_BUFFER_SIZE];
        } help;
    } muxfont;

    struct {
        char title[MAX_BUFFER_SIZE];
        char vmswap[MAX_BUFFER_SIZE];
        char dirtyratio[MAX_BUFFER_SIZE];
        char dirtyback[MAX_BUFFER_SIZE];
        char cachepressure[MAX_BUFFER_SIZE];
        char nomerge[MAX_BUFFER_SIZE];
        char nrrequests[MAX_BUFFER_SIZE];
        char readahead[MAX_BUFFER_SIZE];
        char pagecluster[MAX_BUFFER_SIZE];
        char timeslice[MAX_BUFFER_SIZE];
        char iostats[MAX_BUFFER_SIZE];
        char idleflush[MAX_BUFFER_SIZE];
        char childfirst[MAX_BUFFER_SIZE];
        char tunescale[MAX_BUFFER_SIZE];
        char cardmode[MAX_BUFFER_SIZE];
        char state[MAX_BUFFER_SIZE];
        char warn[MAX_BUFFER_SIZE];
        struct {
            char vm_swap[MAX_BUFFER_SIZE];
            char dirty_ratio[MAX_BUFFER_SIZE];
            char dirty_back[MAX_BUFFER_SIZE];
            char cache_pressure[MAX_BUFFER_SIZE];
            char no_merge[MAX_BUFFER_SIZE];
            char nr_requests[MAX_BUFFER_SIZE];
            char read_ahead[MAX_BUFFER_SIZE];
            char page_cluster[MAX_BUFFER_SIZE];
            char time_slice[MAX_BUFFER_SIZE];
            char io_stats[MAX_BUFFER_SIZE];
            char idle_flush[MAX_BUFFER_SIZE];
            char child_first[MAX_BUFFER_SIZE];
            char tune_scale[MAX_BUFFER_SIZE];
            char card_mode[MAX_BUFFER_SIZE];
            char state[MAX_BUFFER_SIZE];
        } help;
    } muxdanger;

    struct {
        char title[MAX_BUFFER_SIZE];
        char hasbluetooth[MAX_BUFFER_SIZE];
        char hasrgb[MAX_BUFFER_SIZE];
        char hasdebugfs[MAX_BUFFER_SIZE];
        char hashdmi[MAX_BUFFER_SIZE];
        char haslid[MAX_BUFFER_SIZE];
        char hasnetwork[MAX_BUFFER_SIZE];
        char hasportmaster[MAX_BUFFER_SIZE];
        struct {
            char has_bluetooth[MAX_BUFFER_SIZE];
            char has_rgb[MAX_BUFFER_SIZE];
            char has_debugfs[MAX_BUFFER_SIZE];
            char has_hdmi[MAX_BUFFER_SIZE];
            char has_lid[MAX_BUFFER_SIZE];
            char has_network[MAX_BUFFER_SIZE];
            char has_portmaster[MAX_BUFFER_SIZE];
        } help;
    } muxdevice;

    struct {
        char error_get_data[MAX_BUFFER_SIZE];
        char archive_removed[MAX_BUFFER_SIZE];
        struct {
            char archive[MAX_BUFFER_SIZE];
            char data[MAX_BUFFER_SIZE];
        } down;
        struct {
            char app[MAX_BUFFER_SIZE];
            char core[MAX_BUFFER_SIZE];
        } title;
    } muxdownload;

    struct {
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
    } muxgov;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        struct {
            char no_core[MAX_BUFFER_SIZE];
        } error;
    } muxhistory;

    struct {
        char title[MAX_BUFFER_SIZE];
        char resolution[MAX_BUFFER_SIZE];
        struct {
            char depth[MAX_BUFFER_SIZE];
            char space[MAX_BUFFER_SIZE];
            struct {
                char title[MAX_BUFFER_SIZE];
                char full[MAX_BUFFER_SIZE];
                char limited[MAX_BUFFER_SIZE];
            } range;
        } colour;
        struct {
            char title[MAX_BUFFER_SIZE];
            char over[MAX_BUFFER_SIZE];
            char under[MAX_BUFFER_SIZE];
        } scan_scale;
        struct {
            char resolution[MAX_BUFFER_SIZE];
            char space[MAX_BUFFER_SIZE];
            char depth[MAX_BUFFER_SIZE];
            char range[MAX_BUFFER_SIZE];
            char scan[MAX_BUFFER_SIZE];
        } help;
    } muxhdmi;

    struct {
        char title[MAX_BUFFER_SIZE];
        char news[MAX_BUFFER_SIZE];
        char sysinfo[MAX_BUFFER_SIZE];
        char batinfo[MAX_BUFFER_SIZE];
        char netinfo[MAX_BUFFER_SIZE];
        char activity[MAX_BUFFER_SIZE];
        char screenshot[MAX_BUFFER_SIZE];
        char space[MAX_BUFFER_SIZE];
        char tester[MAX_BUFFER_SIZE];
        char chrony[MAX_BUFFER_SIZE];
        char credit[MAX_BUFFER_SIZE];
        struct {
            char news[MAX_BUFFER_SIZE];
            char sys_info[MAX_BUFFER_SIZE];
            char bat_info[MAX_BUFFER_SIZE];
            char net_info[MAX_BUFFER_SIZE];
            char activity[MAX_BUFFER_SIZE];
            char screenshot[MAX_BUFFER_SIZE];
            char space[MAX_BUFFER_SIZE];
            char tester[MAX_BUFFER_SIZE];
            char chrony[MAX_BUFFER_SIZE];
            char credit[MAX_BUFFER_SIZE];
        } help;
    } muxinfo;

    struct {
        char title[MAX_BUFFER_SIZE];
        char rtc[MAX_BUFFER_SIZE];
        char language[MAX_BUFFER_SIZE];
        char install[MAX_BUFFER_SIZE];
        char shutdown[MAX_BUFFER_SIZE];
        struct {
            char rtc[MAX_BUFFER_SIZE];
            char language[MAX_BUFFER_SIZE];
            char install[MAX_BUFFER_SIZE];
            char shutdown[MAX_BUFFER_SIZE];
        } abbr;
        struct {
            char rtc[MAX_BUFFER_SIZE];
            char language[MAX_BUFFER_SIZE];
            char install[MAX_BUFFER_SIZE];
            char shutdown[MAX_BUFFER_SIZE];
        } help;
    } muxinstall;

    struct {
        char title[MAX_BUFFER_SIZE];
        char enable[MAX_BUFFER_SIZE];
        char message[MAX_BUFFER_SIZE];
        char archive[MAX_BUFFER_SIZE];
        char task[MAX_BUFFER_SIZE];
        char custom[MAX_BUFFER_SIZE];
        char language[MAX_BUFFER_SIZE];
        char network[MAX_BUFFER_SIZE];
        char storage[MAX_BUFFER_SIZE];
        char backup[MAX_BUFFER_SIZE];
        char netadv[MAX_BUFFER_SIZE];
        char webserv[MAX_BUFFER_SIZE];
        char core[MAX_BUFFER_SIZE];
        char governor[MAX_BUFFER_SIZE];
        char control[MAX_BUFFER_SIZE];
        char option[MAX_BUFFER_SIZE];
        char retroarch[MAX_BUFFER_SIZE];
        char search[MAX_BUFFER_SIZE];
        char tag[MAX_BUFFER_SIZE];
        char colfilter[MAX_BUFFER_SIZE];
        char shader[MAX_BUFFER_SIZE];
        char remconfig[MAX_BUFFER_SIZE];
        char catalogue[MAX_BUFFER_SIZE];
        char raconfig[MAX_BUFFER_SIZE];
        char theme[MAX_BUFFER_SIZE];
        char themedown[MAX_BUFFER_SIZE];
        char clock[MAX_BUFFER_SIZE];
        char timezone[MAX_BUFFER_SIZE];
        char apps[MAX_BUFFER_SIZE];
        char config[MAX_BUFFER_SIZE];
        char explore[MAX_BUFFER_SIZE];
        char info[MAX_BUFFER_SIZE];
        char rgb[MAX_BUFFER_SIZE];
        char advanced[MAX_BUFFER_SIZE];
        char general[MAX_BUFFER_SIZE];
        char hdmi[MAX_BUFFER_SIZE];
        char power[MAX_BUFFER_SIZE];
        char visual[MAX_BUFFER_SIZE];
        char overlay[MAX_BUFFER_SIZE];
        struct {
            char main[MAX_BUFFER_SIZE];
            char add_content[MAX_BUFFER_SIZE];
            char new_dir[MAX_BUFFER_SIZE];
            char remove[MAX_BUFFER_SIZE];
            char access[MAX_BUFFER_SIZE];
        } collection;
        struct {
            char main[MAX_BUFFER_SIZE];
            char remove[MAX_BUFFER_SIZE];
        } history;
        struct {
            char enable[MAX_BUFFER_SIZE];
            char message[MAX_BUFFER_SIZE];
            char archive[MAX_BUFFER_SIZE];
            char task[MAX_BUFFER_SIZE];
            char custom[MAX_BUFFER_SIZE];
            char language[MAX_BUFFER_SIZE];
            char network[MAX_BUFFER_SIZE];
            char storage[MAX_BUFFER_SIZE];
            char backup[MAX_BUFFER_SIZE];
            char net_adv[MAX_BUFFER_SIZE];
            char web_serv[MAX_BUFFER_SIZE];
            char core[MAX_BUFFER_SIZE];
            char governor[MAX_BUFFER_SIZE];
            char control[MAX_BUFFER_SIZE];
            char option[MAX_BUFFER_SIZE];
            char retro_arch[MAX_BUFFER_SIZE];
            char search[MAX_BUFFER_SIZE];
            char tag[MAX_BUFFER_SIZE];
            char col_filter[MAX_BUFFER_SIZE];
            char shader[MAX_BUFFER_SIZE];
            char rem_config[MAX_BUFFER_SIZE];
            char catalogue[MAX_BUFFER_SIZE];
            char ra_config[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
            char theme_down[MAX_BUFFER_SIZE];
            char clock[MAX_BUFFER_SIZE];
            char timezone[MAX_BUFFER_SIZE];
            char apps[MAX_BUFFER_SIZE];
            char config[MAX_BUFFER_SIZE];
            char explore[MAX_BUFFER_SIZE];
            char info[MAX_BUFFER_SIZE];
            char rgb[MAX_BUFFER_SIZE];
            char advanced[MAX_BUFFER_SIZE];
            char general[MAX_BUFFER_SIZE];
            char hdmi[MAX_BUFFER_SIZE];
            char power[MAX_BUFFER_SIZE];
            char visual[MAX_BUFFER_SIZE];
            char overlay[MAX_BUFFER_SIZE];
            char collect_mod[MAX_BUFFER_SIZE];
            char collect_add[MAX_BUFFER_SIZE];
            char collect_new[MAX_BUFFER_SIZE];
            char collect_rem[MAX_BUFFER_SIZE];
            char collect_acc[MAX_BUFFER_SIZE];
            char history_mod[MAX_BUFFER_SIZE];
            char history_rem[MAX_BUFFER_SIZE];
        } help;
    } muxkiosk;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char save[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char downloading[MAX_BUFFER_SIZE];
        char error_get_data[MAX_BUFFER_SIZE];
    } muxlanguage;

    struct {
        char title[MAX_BUFFER_SIZE];
        char apps[MAX_BUFFER_SIZE];
        char config[MAX_BUFFER_SIZE];
        char info[MAX_BUFFER_SIZE];
        char collection[MAX_BUFFER_SIZE];
        char history[MAX_BUFFER_SIZE];
        char explore[MAX_BUFFER_SIZE];
        char shutdown[MAX_BUFFER_SIZE];
        char reboot[MAX_BUFFER_SIZE];
        char confirm_reboot[MAX_BUFFER_SIZE];
        char confirm_shutdown[MAX_BUFFER_SIZE];
        struct {
            char app[MAX_BUFFER_SIZE];
            char config[MAX_BUFFER_SIZE];
            char info[MAX_BUFFER_SIZE];
            char collection[MAX_BUFFER_SIZE];
            char history[MAX_BUFFER_SIZE];
            char explore[MAX_BUFFER_SIZE];
            char shutdown[MAX_BUFFER_SIZE];
            char reboot[MAX_BUFFER_SIZE];
        } abbr;
        struct {
            char error[MAX_BUFFER_SIZE];
            char process[MAX_BUFFER_SIZE];
        } kiosk;
        struct {
            char apps[MAX_BUFFER_SIZE];
            char config[MAX_BUFFER_SIZE];
            char info[MAX_BUFFER_SIZE];
            char collection[MAX_BUFFER_SIZE];
            char history[MAX_BUFFER_SIZE];
            char explore[MAX_BUFFER_SIZE];
            char shutdown[MAX_BUFFER_SIZE];
            char reboot[MAX_BUFFER_SIZE];
        } help;
    } muxlaunch;

    struct {
        char title[MAX_BUFFER_SIZE];
        char system_dns[MAX_BUFFER_SIZE];
        char monitor[MAX_BUFFER_SIZE];
        char boot[MAX_BUFFER_SIZE];
        char wake[MAX_BUFFER_SIZE];
        char compat[MAX_BUFFER_SIZE];
        char asyncload[MAX_BUFFER_SIZE];
        char conretry[MAX_BUFFER_SIZE];
        char wait[MAX_BUFFER_SIZE];
        char modretry[MAX_BUFFER_SIZE];
        struct {
            char def[MAX_BUFFER_SIZE];
            char cloudflare[MAX_BUFFER_SIZE];
            char google[MAX_BUFFER_SIZE];
            char quad9[MAX_BUFFER_SIZE];
        } dns_name;
        struct {
            char system_dns[MAX_BUFFER_SIZE];
            char monitor[MAX_BUFFER_SIZE];
            char boot[MAX_BUFFER_SIZE];
            char wake[MAX_BUFFER_SIZE];
            char compat[MAX_BUFFER_SIZE];
            char async_load[MAX_BUFFER_SIZE];
            char con_retry[MAX_BUFFER_SIZE];
            char wait[MAX_BUFFER_SIZE];
            char mod_retry[MAX_BUFFER_SIZE];
        } help;
    } muxnetadv;

    struct {
        char title[MAX_BUFFER_SIZE];
        char hostname[MAX_BUFFER_SIZE];
        char mac[MAX_BUFFER_SIZE];
        char ip[MAX_BUFFER_SIZE];
        char ssid[MAX_BUFFER_SIZE];
        char gateway[MAX_BUFFER_SIZE];
        char dns[MAX_BUFFER_SIZE];
        char signal[MAX_BUFFER_SIZE];
        char channel[MAX_BUFFER_SIZE];
        char actraffic[MAX_BUFFER_SIZE];
        char tptraffic[MAX_BUFFER_SIZE];
        struct {
            char hostname[MAX_BUFFER_SIZE];
            char mac[MAX_BUFFER_SIZE];
            char ip[MAX_BUFFER_SIZE];
            char ssid[MAX_BUFFER_SIZE];
            char gateway[MAX_BUFFER_SIZE];
            char dns[MAX_BUFFER_SIZE];
            char signal[MAX_BUFFER_SIZE];
            char channel[MAX_BUFFER_SIZE];
            char ac_traffic[MAX_BUFFER_SIZE];
            char tp_traffic[MAX_BUFFER_SIZE];
        } help;
        struct {
            char edit[MAX_BUFFER_SIZE];
            char change[MAX_BUFFER_SIZE];
        } error;
        struct {
            char host[MAX_BUFFER_SIZE];
            char mac[MAX_BUFFER_SIZE];
        } save;
        struct {
            char success[MAX_BUFFER_SIZE];
            char fail[MAX_BUFFER_SIZE];
        } report;
    } muxnetinfo;

    struct {
        char title[MAX_BUFFER_SIZE];
        char connect[MAX_BUFFER_SIZE];
        char disconnect[MAX_BUFFER_SIZE];
        char connected[MAX_BUFFER_SIZE];
        char not_connected[MAX_BUFFER_SIZE];
        char deny_modify[MAX_BUFFER_SIZE];
        char deny_forget[MAX_BUFFER_SIZE];
        char save[MAX_BUFFER_SIZE];
        char dhcp[MAX_BUFFER_SIZE];
        char statc[MAX_BUFFER_SIZE];
        char subnet[MAX_BUFFER_SIZE];
        char profiles[MAX_BUFFER_SIZE];
        char connect_try[MAX_BUFFER_SIZE];
        char connect_deny[MAX_BUFFER_SIZE];
        char password[MAX_BUFFER_SIZE];
        char no_password[MAX_BUFFER_SIZE];
        char dns[MAX_BUFFER_SIZE];
        char address[MAX_BUFFER_SIZE];
        char encrypt_password[MAX_BUFFER_SIZE];
        char gateway[MAX_BUFFER_SIZE];
        char identifier[MAX_BUFFER_SIZE];
        char profile_name[MAX_BUFFER_SIZE];
        char priority[MAX_BUFFER_SIZE];
        char disabled[MAX_BUFFER_SIZE];
        char type[MAX_BUFFER_SIZE];
        char check[MAX_BUFFER_SIZE];
        char forget[MAX_BUFFER_SIZE];
        char forget_confirm[MAX_BUFFER_SIZE];
        struct {
            char associating[MAX_BUFFER_SIZE];
            char authenticating[MAX_BUFFER_SIZE];
            char waiting_ip[MAX_BUFFER_SIZE];
            char validating[MAX_BUFFER_SIZE];
            char invalid_password[MAX_BUFFER_SIZE];
            char ap_not_found[MAX_BUFFER_SIZE];
            char auth_timeout[MAX_BUFFER_SIZE];
            char dhcp_failed[MAX_BUFFER_SIZE];
            char link_timeout[MAX_BUFFER_SIZE];
            char wpa_start_failed[MAX_BUFFER_SIZE];
        } status;
        struct {
            char type[MAX_BUFFER_SIZE];
            char password[MAX_BUFFER_SIZE];
            char identifier[MAX_BUFFER_SIZE];
            char profile_name[MAX_BUFFER_SIZE];
            char priority[MAX_BUFFER_SIZE];
            char gateway[MAX_BUFFER_SIZE];
            char subnet[MAX_BUFFER_SIZE];
            char dns[MAX_BUFFER_SIZE];
            char address[MAX_BUFFER_SIZE];
            char connect[MAX_BUFFER_SIZE];
        } help;
    } muxnetprofile;

    struct {
        char title[MAX_BUFFER_SIZE];
        char scan[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
    } muxnetscan;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char connected[MAX_BUFFER_SIZE];
        char autom[MAX_BUFFER_SIZE];
        char manual[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
    } muxnetwork;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char download[MAX_BUFFER_SIZE];
        char error[MAX_BUFFER_SIZE];
        char open[MAX_BUFFER_SIZE];
    } muxnews;

    struct {
        char title_main[MAX_BUFFER_SIZE];
        char title_info[MAX_BUFFER_SIZE];
        char name[MAX_BUFFER_SIZE];
        char time[MAX_BUFFER_SIZE];
        char launch[MAX_BUFFER_SIZE];
        char current[MAX_BUFFER_SIZE];
        char core[MAX_BUFFER_SIZE];
        char governor[MAX_BUFFER_SIZE];
        char control[MAX_BUFFER_SIZE];
        char tag[MAX_BUFFER_SIZE];
        char retroarch[MAX_BUFFER_SIZE];
        char colfilter[MAX_BUFFER_SIZE];
        char shader[MAX_BUFFER_SIZE];
        char overlay[MAX_BUFFER_SIZE];
        char remconfig[MAX_BUFFER_SIZE];
        char remcontent[MAX_BUFFER_SIZE];
        char remdir[MAX_BUFFER_SIZE];
        char remcore[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char dflt[MAX_BUFFER_SIZE];
        char modified[MAX_BUFFER_SIZE];
        char not_assigned[MAX_BUFFER_SIZE];
        char storage[MAX_BUFFER_SIZE];
        char folder[MAX_BUFFER_SIZE];
        char primary[MAX_BUFFER_SIZE];
        char secondary[MAX_BUFFER_SIZE];
        char external[MAX_BUFFER_SIZE];
        struct {
            char core[MAX_BUFFER_SIZE];
            char governor[MAX_BUFFER_SIZE];
            char control[MAX_BUFFER_SIZE];
            char tag[MAX_BUFFER_SIZE];
            char retro_arch[MAX_BUFFER_SIZE];
            char col_filter[MAX_BUFFER_SIZE];
            char shader[MAX_BUFFER_SIZE];
            char overlay[MAX_BUFFER_SIZE];
            char rem_config[MAX_BUFFER_SIZE];
            char storage[MAX_BUFFER_SIZE];
            char folder[MAX_BUFFER_SIZE];
            char name[MAX_BUFFER_SIZE];
            char time[MAX_BUFFER_SIZE];
            char launch[MAX_BUFFER_SIZE];
        } help;
    } muxoption;

    struct {
        char title[MAX_BUFFER_SIZE];
        struct {
            struct {
                char left[MAX_BUFFER_SIZE];
                char middle[MAX_BUFFER_SIZE];
                char right[MAX_BUFFER_SIZE];
            } top;
            struct {
                char left[MAX_BUFFER_SIZE];
                char middle[MAX_BUFFER_SIZE];
                char right[MAX_BUFFER_SIZE];
            } centre;
            struct {
                char left[MAX_BUFFER_SIZE];
                char middle[MAX_BUFFER_SIZE];
                char right[MAX_BUFFER_SIZE];
            } bottom;
        } anchor;
        struct {
            char original[MAX_BUFFER_SIZE];
            char fit[MAX_BUFFER_SIZE];
            char stretch[MAX_BUFFER_SIZE];
        } scale;
        char genalpha[MAX_BUFFER_SIZE];
        char genanchor[MAX_BUFFER_SIZE];
        char genscale[MAX_BUFFER_SIZE];
        char batalpha[MAX_BUFFER_SIZE];
        char batanchor[MAX_BUFFER_SIZE];
        char batscale[MAX_BUFFER_SIZE];
        char volalpha[MAX_BUFFER_SIZE];
        char volanchor[MAX_BUFFER_SIZE];
        char volscale[MAX_BUFFER_SIZE];
        char brialpha[MAX_BUFFER_SIZE];
        char brianchor[MAX_BUFFER_SIZE];
        char briscale[MAX_BUFFER_SIZE];
        struct {
            char gen_alpha[MAX_BUFFER_SIZE];
            char gen_anchor[MAX_BUFFER_SIZE];
            char gen_scale[MAX_BUFFER_SIZE];
            char bat_alpha[MAX_BUFFER_SIZE];
            char bat_anchor[MAX_BUFFER_SIZE];
            char bat_scale[MAX_BUFFER_SIZE];
            char vol_alpha[MAX_BUFFER_SIZE];
            char vol_anchor[MAX_BUFFER_SIZE];
            char vol_scale[MAX_BUFFER_SIZE];
            char bri_alpha[MAX_BUFFER_SIZE];
            char bri_anchor[MAX_BUFFER_SIZE];
            char bri_scale[MAX_BUFFER_SIZE];
        } help;
    } muxoverlay;

    struct {
        char title[MAX_BUFFER_SIZE];
        char shutdown[MAX_BUFFER_SIZE];
    } muxpass;

    struct {
        char title[MAX_BUFFER_SIZE];
        char bootcode[MAX_BUFFER_SIZE];
        char bootmsg[MAX_BUFFER_SIZE];
        char launchcode[MAX_BUFFER_SIZE];
        char launchmsg[MAX_BUFFER_SIZE];
        char settingcode[MAX_BUFFER_SIZE];
        char settingmsg[MAX_BUFFER_SIZE];
        char safetycode[MAX_BUFFER_SIZE];
        char saved[MAX_BUFFER_SIZE];
        char invalid[MAX_BUFFER_SIZE];
        struct {
            char boot_code[MAX_BUFFER_SIZE];
            char boot_msg[MAX_BUFFER_SIZE];
            char launch_code[MAX_BUFFER_SIZE];
            char launch_msg[MAX_BUFFER_SIZE];
            char setting_code[MAX_BUFFER_SIZE];
            char setting_msg[MAX_BUFFER_SIZE];
            char safety_code[MAX_BUFFER_SIZE];
        } help;
    } muxpasscfg;

    struct {
        char custom[MAX_BUFFER_SIZE];
        char catalogue[MAX_BUFFER_SIZE];
        char config[MAX_BUFFER_SIZE];
        char theme[MAX_BUFFER_SIZE];
        char theme_down[MAX_BUFFER_SIZE];
        char invalid_ver[MAX_BUFFER_SIZE];
        char invalid_res[MAX_BUFFER_SIZE];
        char protected[MAX_BUFFER_SIZE];
        struct {
            char credit[MAX_BUFFER_SIZE];
            char custom[MAX_BUFFER_SIZE];
            char catalogue[MAX_BUFFER_SIZE];
            char config[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
        } none;
    } muxpicker;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        struct {
            char no_folder[MAX_BUFFER_SIZE];
            char no_core[MAX_BUFFER_SIZE];
            char general[MAX_BUFFER_SIZE];
        } error;
    } muxplore;

    struct {
        char title[MAX_BUFFER_SIZE];
        char low_battery[MAX_BUFFER_SIZE];
        struct {
            struct {
                char title[MAX_BUFFER_SIZE];
                char dvd[MAX_BUFFER_SIZE];
                char star[MAX_BUFFER_SIZE];
                char matrix[MAX_BUFFER_SIZE];
                char firefly[MAX_BUFFER_SIZE];
                char pulse[MAX_BUFFER_SIZE];
                char trace[MAX_BUFFER_SIZE];
                char constellation[MAX_BUFFER_SIZE];
                char mystify[MAX_BUFFER_SIZE];
                char maze[MAX_BUFFER_SIZE];
                char blockfall[MAX_BUFFER_SIZE];
                char datetime[MAX_BUFFER_SIZE];
                char video[MAX_BUFFER_SIZE];
                char slideshow[MAX_BUFFER_SIZE];
                char boxart[MAX_BUFFER_SIZE];
                char bsod[MAX_BUFFER_SIZE];
            } type;
            struct {
                char title[MAX_BUFFER_SIZE];
                char crawl[MAX_BUFFER_SIZE];
                char cruise[MAX_BUFFER_SIZE];
                char fast[MAX_BUFFER_SIZE];
                char turbo[MAX_BUFFER_SIZE];
            } speed;
        } saver;
        struct {
            char error[MAX_BUFFER_SIZE];
            char display[MAX_BUFFER_SIZE];
            char sleep[MAX_BUFFER_SIZE];
            char mute[MAX_BUFFER_SIZE];
            char t10_s[MAX_BUFFER_SIZE];
            char t30_s[MAX_BUFFER_SIZE];
            char t60_s[MAX_BUFFER_SIZE];
            char t2_m[MAX_BUFFER_SIZE];
            char t5_m[MAX_BUFFER_SIZE];
            char t10_m[MAX_BUFFER_SIZE];
            char t15_m[MAX_BUFFER_SIZE];
            char t30_m[MAX_BUFFER_SIZE];
        } idle;
        struct {
            char title[MAX_BUFFER_SIZE];
            char instant[MAX_BUFFER_SIZE];
            char suspend[MAX_BUFFER_SIZE];
            char t10_s[MAX_BUFFER_SIZE];
            char t30_s[MAX_BUFFER_SIZE];
            char t60_s[MAX_BUFFER_SIZE];
            char t2_m[MAX_BUFFER_SIZE];
            char t5_m[MAX_BUFFER_SIZE];
            char t10_m[MAX_BUFFER_SIZE];
            char t15_m[MAX_BUFFER_SIZE];
            char t30_m[MAX_BUFFER_SIZE];
            char t60_m[MAX_BUFFER_SIZE];
        } sleep;
        struct {
            char dflt[MAX_BUFFER_SIZE];
            char idle[MAX_BUFFER_SIZE];
        } gov;
        struct {
            char shutdown[MAX_BUFFER_SIZE];
            char battery[MAX_BUFFER_SIZE];
            char idle_sleep[MAX_BUFFER_SIZE];
            char idle_display[MAX_BUFFER_SIZE];
            char idle_mute[MAX_BUFFER_SIZE];
            char gov_idle[MAX_BUFFER_SIZE];
            char gov_default[MAX_BUFFER_SIZE];
            char saver_type[MAX_BUFFER_SIZE];
            char saver_speed[MAX_BUFFER_SIZE];
        } help;
    } muxpower;

    struct {
        char title[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
    } muxraopt;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char waiting[MAX_BUFFER_SIZE];
        char saved[MAX_BUFFER_SIZE];
        char already_used[MAX_BUFFER_SIZE];
        char core_missing[MAX_BUFFER_SIZE];
        char input_label[MAX_BUFFER_SIZE];
        char layout_label[MAX_BUFFER_SIZE];
        char layout_retro[MAX_BUFFER_SIZE];
        char layout_modern[MAX_BUFFER_SIZE];
    } muxremap;

    struct {
        char title[MAX_BUFFER_SIZE];
        char resume[MAX_BUFFER_SIZE];
        char game_state[MAX_BUFFER_SIZE];
        char core_options[MAX_BUFFER_SIZE];
        char disc_control[MAX_BUFFER_SIZE];
        char hotkeys[MAX_BUFFER_SIZE];
        char cheats[MAX_BUFFER_SIZE];
        char patches[MAX_BUFFER_SIZE];
        char settings[MAX_BUFFER_SIZE];
        char display[MAX_BUFFER_SIZE];
        char information[MAX_BUFFER_SIZE];
        char restart[MAX_BUFFER_SIZE];
        char quit[MAX_BUFFER_SIZE];
        struct {
            char none_found[MAX_BUFFER_SIZE];
            char delete[MAX_BUFFER_SIZE];
            char load_title[MAX_BUFFER_SIZE];
            char load_desc[MAX_BUFFER_SIZE];
            char delete_title[MAX_BUFFER_SIZE];
            char delete_desc[MAX_BUFFER_SIZE];
            char auto_save[MAX_BUFFER_SIZE];
            char quick_save[MAX_BUFFER_SIZE];
            char state[MAX_BUFFER_SIZE];
            char list[MAX_BUFFER_SIZE];
            char load_failed[MAX_BUFFER_SIZE];
            char not_supported[MAX_BUFFER_SIZE];
        } gamestate;
        struct {
            char options_title[MAX_BUFFER_SIZE];
            char options_desc[MAX_BUFFER_SIZE];
            char settings_title[MAX_BUFFER_SIZE];
            char settings_desc[MAX_BUFFER_SIZE];
            char hotkeys_title[MAX_BUFFER_SIZE];
            char hotkeys_desc[MAX_BUFFER_SIZE];
            char display_title[MAX_BUFFER_SIZE];
            char display_desc[MAX_BUFFER_SIZE];
            char viewport_title[MAX_BUFFER_SIZE];
            char viewport_desc[MAX_BUFFER_SIZE];
            char video_title[MAX_BUFFER_SIZE];
            char video_desc[MAX_BUFFER_SIZE];
            char sound_title[MAX_BUFFER_SIZE];
            char sound_desc[MAX_BUFFER_SIZE];
            char input_title[MAX_BUFFER_SIZE];
            char input_desc[MAX_BUFFER_SIZE];
            char performance_title[MAX_BUFFER_SIZE];
            char performance_desc[MAX_BUFFER_SIZE];
            char hud_title[MAX_BUFFER_SIZE];
            char hud_desc[MAX_BUFFER_SIZE];
            char storage_title[MAX_BUFFER_SIZE];
            char storage_desc[MAX_BUFFER_SIZE];
            char content_save[MAX_BUFFER_SIZE];
            char core_save[MAX_BUFFER_SIZE];
            char directory_save[MAX_BUFFER_SIZE];
        } save;
        struct {
            char swap[MAX_BUFFER_SIZE];
            char inserted[MAX_BUFFER_SIZE];
            char disc[MAX_BUFFER_SIZE];
            char eject[MAX_BUFFER_SIZE];
            char insert[MAX_BUFFER_SIZE];
            char ejected[MAX_BUFFER_SIZE];
            char eject_first[MAX_BUFFER_SIZE];
        } diskcontrol;
        struct {
            char scaling_mode[MAX_BUFFER_SIZE];
            char rotate[MAX_BUFFER_SIZE];
            char mirrored[MAX_BUFFER_SIZE];
            char full_height[MAX_BUFFER_SIZE];
            char full_width[MAX_BUFFER_SIZE];
            char fit_screen[MAX_BUFFER_SIZE];
            char texture_filter[MAX_BUFFER_SIZE];
            char shimmer_fix[MAX_BUFFER_SIZE];
            char run_ahead[MAX_BUFFER_SIZE];
            char run_ahead_failed[MAX_BUFFER_SIZE];
            char controller_type[MAX_BUFFER_SIZE];
            char controller_digital[MAX_BUFFER_SIZE];
            char controller_analog[MAX_BUFFER_SIZE];
            char rumble[MAX_BUFFER_SIZE];
            char volume[MAX_BUFFER_SIZE];
            char show_fps[MAX_BUFFER_SIZE];
            char border_colour[MAX_BUFFER_SIZE];
            char aspect_ratio[MAX_BUFFER_SIZE];
            char aspect_ratio_mode[MAX_BUFFER_SIZE];
            char ratio_4_3[MAX_BUFFER_SIZE];
            char ratio_8_7[MAX_BUFFER_SIZE];
            char ratio_16_9[MAX_BUFFER_SIZE];
            char ratio_16_10[MAX_BUFFER_SIZE];
            char pixel_perfect[MAX_BUFFER_SIZE];
            char integer_mode[MAX_BUFFER_SIZE];
            char integer_scale[MAX_BUFFER_SIZE];
            char stretch[MAX_BUFFER_SIZE];
            char nearest[MAX_BUFFER_SIZE];
            char smooth[MAX_BUFFER_SIZE];
            char scale2_x[MAX_BUFFER_SIZE];
            char scale3_x[MAX_BUFFER_SIZE];
            char sharp_bilinear[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
            char black[MAX_BUFFER_SIZE];
            char dark_grey[MAX_BUFFER_SIZE];
            char white[MAX_BUFFER_SIZE];
            char sample_rate[MAX_BUFFER_SIZE];
            char auto_rate[MAX_BUFFER_SIZE];
            char fps_limit[MAX_BUFFER_SIZE];
            char fps_60[MAX_BUFFER_SIZE];
            char fps_50[MAX_BUFFER_SIZE];
            char fps_none[MAX_BUFFER_SIZE];
            char header_visibility[MAX_BUFFER_SIZE];
            char header_none[MAX_BUFFER_SIZE];
            char header_clock[MAX_BUFFER_SIZE];
            char header_battery[MAX_BUFFER_SIZE];
            char header_both[MAX_BUFFER_SIZE];
            char sram_flush[MAX_BUFFER_SIZE];
            char sram_backup[MAX_BUFFER_SIZE];
            char auto_save[MAX_BUFFER_SIZE];
            char auto_save_idle[MAX_BUFFER_SIZE];
            char auto_save_quit[MAX_BUFFER_SIZE];
            char auto_save_idle_quit[MAX_BUFFER_SIZE];
            char overlay_pattern_mode[MAX_BUFFER_SIZE];
            char overlay_catalogue_mode[MAX_BUFFER_SIZE];
            char frame_delay[MAX_BUFFER_SIZE];
            char analog_deadzone[MAX_BUFFER_SIZE];
            char analog_anti_deadzone[MAX_BUFFER_SIZE];
            char analog_sensitivity[MAX_BUFFER_SIZE];
            char analog_invert_y[MAX_BUFFER_SIZE];
            char audio_latency[MAX_BUFFER_SIZE];
            char audio_latency_low[MAX_BUFFER_SIZE];
            char audio_latency_balanced[MAX_BUFFER_SIZE];
            char audio_latency_compat[MAX_BUFFER_SIZE];
            char audio_period[MAX_BUFFER_SIZE];
            char gpu_hard_sync[MAX_BUFFER_SIZE];
            char category_video[MAX_BUFFER_SIZE];
            char category_sound[MAX_BUFFER_SIZE];
            char category_input[MAX_BUFFER_SIZE];
            char category_performance[MAX_BUFFER_SIZE];
            char category_hud[MAX_BUFFER_SIZE];
            char category_storage[MAX_BUFFER_SIZE];
        } settings_screen;
        struct {
            char fast_forward[MAX_BUFFER_SIZE];
            char slow_motion[MAX_BUFFER_SIZE];
            char quick_save[MAX_BUFFER_SIZE];
            char quick_load[MAX_BUFFER_SIZE];
            char ff_speed[MAX_BUFFER_SIZE];
            char slowmo_speed[MAX_BUFFER_SIZE];
            char no_quicksave[MAX_BUFFER_SIZE];
            char toggle_fps[MAX_BUFFER_SIZE];
            char toggle_header[MAX_BUFFER_SIZE];
            char toggle_controller[MAX_BUFFER_SIZE];
            char ff_glyph[MAX_BUFFER_SIZE];
            char slowmo_glyph[MAX_BUFFER_SIZE];
            char manual[MAX_BUFFER_SIZE];
        } hotkeys_screen;
        struct {
            char miscellaneous[MAX_BUFFER_SIZE];
        } options_screen;
        struct {
            char no_cheats[MAX_BUFFER_SIZE];
        } cheats_screen;
        struct {
            char restart_required[MAX_BUFFER_SIZE];
        } patches_screen;
        struct {
            char not_found[MAX_BUFFER_SIZE];
            char wrap[MAX_BUFFER_SIZE];
        } manual_screen;
        struct {
            char brightness[MAX_BUFFER_SIZE];
            char contrast[MAX_BUFFER_SIZE];
            char saturation[MAX_BUFFER_SIZE];
            char hue_shift[MAX_BUFFER_SIZE];
            char gamma[MAX_BUFFER_SIZE];
            char filter[MAX_BUFFER_SIZE];
            char shaders[MAX_BUFFER_SIZE];
            char overlay[MAX_BUFFER_SIZE];
            char overlay_pattern[MAX_BUFFER_SIZE];
            char overlay_opacity[MAX_BUFFER_SIZE];
            char viewport[MAX_BUFFER_SIZE];
        } display_screen;
        struct {
            char offset_x[MAX_BUFFER_SIZE];
            char offset_y[MAX_BUFFER_SIZE];
            char zoom[MAX_BUFFER_SIZE];
            char crop_top[MAX_BUFFER_SIZE];
            char crop_bottom[MAX_BUFFER_SIZE];
            char crop_left[MAX_BUFFER_SIZE];
            char crop_right[MAX_BUFFER_SIZE];
            char centre_crop[MAX_BUFFER_SIZE];
            char reset[MAX_BUFFER_SIZE];
        } viewport_screen;
        struct {
            char checkerboard_1[MAX_BUFFER_SIZE];
            char checkerboard_4[MAX_BUFFER_SIZE];
            char diagonal_1[MAX_BUFFER_SIZE];
            char diagonal_2[MAX_BUFFER_SIZE];
            char diagonal_4[MAX_BUFFER_SIZE];
            char lattice_1[MAX_BUFFER_SIZE];
            char lattice_4[MAX_BUFFER_SIZE];
            char horizontal_1[MAX_BUFFER_SIZE];
            char horizontal_2[MAX_BUFFER_SIZE];
            char horizontal_4[MAX_BUFFER_SIZE];
            char vertical_1[MAX_BUFFER_SIZE];
            char vertical_2[MAX_BUFFER_SIZE];
            char vertical_4[MAX_BUFFER_SIZE];
        } overlay_screen;
        struct {
            char core_name[MAX_BUFFER_SIZE];
            char core_version[MAX_BUFFER_SIZE];
            char content_hash[MAX_BUFFER_SIZE];
            char loaded_via[MAX_BUFFER_SIZE];
            char active_patches[MAX_BUFFER_SIZE];
            char patches_none[MAX_BUFFER_SIZE];
            char loaded_patches_toast[MAX_BUFFER_SIZE];
            char calculating[MAX_BUFFER_SIZE];
            char resolution[MAX_BUFFER_SIZE];
            char display_output[MAX_BUFFER_SIZE];
            char target_fps[MAX_BUFFER_SIZE];
            char audio_output[MAX_BUFFER_SIZE];
            char rumble_support[MAX_BUFFER_SIZE];
            char disc_count[MAX_BUFFER_SIZE];
            char direct[MAX_BUFFER_SIZE];
            char vfs_stream[MAX_BUFFER_SIZE];
            char extracted[MAX_BUFFER_SIZE];
            char stereo[MAX_BUFFER_SIZE];
            char mono[MAX_BUFFER_SIZE];
            char system_bios[MAX_BUFFER_SIZE];
            char bios_valid[MAX_BUFFER_SIZE];
            char bios_missing[MAX_BUFFER_SIZE];
            char bios_optional[MAX_BUFFER_SIZE];
            char bios_required[MAX_BUFFER_SIZE];
        } information_screen;
    } muxretro;

    struct {
        char title[MAX_BUFFER_SIZE];
        char mode[MAX_BUFFER_SIZE];
        char bright[MAX_BUFFER_SIZE];
        char speed[MAX_BUFFER_SIZE];
        char breath_speed[MAX_BUFFER_SIZE];
        char colourl[MAX_BUFFER_SIZE];
        char colourr[MAX_BUFFER_SIZE];
        char colourm[MAX_BUFFER_SIZE];
        char colourf1[MAX_BUFFER_SIZE];
        char colourf2[MAX_BUFFER_SIZE];
        char combo[MAX_BUFFER_SIZE];
        char backend[MAX_BUFFER_SIZE];
        char same_as_l[MAX_BUFFER_SIZE];
        struct {
            char off[MAX_BUFFER_SIZE];
            char statc[MAX_BUFFER_SIZE];
            char breathing[MAX_BUFFER_SIZE];
            char colour_cycle[MAX_BUFFER_SIZE];
            char rainbow[MAX_BUFFER_SIZE];
            char stick_follow[MAX_BUFFER_SIZE];
            char preset_combo[MAX_BUFFER_SIZE];
            char theme_supplied[MAX_BUFFER_SIZE];
        } mode_name;
        struct {
            char fast[MAX_BUFFER_SIZE];
            char medium[MAX_BUFFER_SIZE];
            char slow[MAX_BUFFER_SIZE];
        } breath_speed_name;
        struct {
            char primary[MAX_BUFFER_SIZE];
            char secondary[MAX_BUFFER_SIZE];
            char single[MAX_BUFFER_SIZE];
            char both[MAX_BUFFER_SIZE];
        } stick;
        struct {
            char autom[MAX_BUFFER_SIZE];
            char sysfs[MAX_BUFFER_SIZE];
            char serial[MAX_BUFFER_SIZE];
            char joypad[MAX_BUFFER_SIZE];
        } backend_name;
        struct {
            char mode[MAX_BUFFER_SIZE];
            char bright[MAX_BUFFER_SIZE];
            char breath_speed[MAX_BUFFER_SIZE];
            char colour_l[MAX_BUFFER_SIZE];
            char colour_r[MAX_BUFFER_SIZE];
            char colour_m[MAX_BUFFER_SIZE];
            char colour_f1[MAX_BUFFER_SIZE];
            char colour_f2[MAX_BUFFER_SIZE];
            char combo[MAX_BUFFER_SIZE];
            char backend[MAX_BUFFER_SIZE];
        } help;
    } muxrgb;

    struct {
        char title[MAX_BUFFER_SIZE];
        char day[MAX_BUFFER_SIZE];
        char month[MAX_BUFFER_SIZE];
        char year[MAX_BUFFER_SIZE];
        char hour[MAX_BUFFER_SIZE];
        char minute[MAX_BUFFER_SIZE];
        char timezone[MAX_BUFFER_SIZE];
        char notation[MAX_BUFFER_SIZE];
        char f_12_hr[MAX_BUFFER_SIZE];
        char f_24_hr[MAX_BUFFER_SIZE];
        char f_dd_mm_12[MAX_BUFFER_SIZE];
        char f_dd_mm_24[MAX_BUFFER_SIZE];
        char f_mm_dd_12[MAX_BUFFER_SIZE];
        char f_mm_dd_24[MAX_BUFFER_SIZE];
        char f_custom[MAX_BUFFER_SIZE];
        char custom[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
    } muxrtc;

    struct {
        char title[MAX_BUFFER_SIZE];
        char global[MAX_BUFFER_SIZE];
        char local[MAX_BUFFER_SIZE];
        char lookup[MAX_BUFFER_SIZE];
        char search[MAX_BUFFER_SIZE];
        char error[MAX_BUFFER_SIZE];
        struct {
            char search_global[MAX_BUFFER_SIZE];
            char search_local[MAX_BUFFER_SIZE];
            char lookup[MAX_BUFFER_SIZE];
        } help;
    } muxsearch;

    struct {
        char title[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
    } muxshader;

    struct {
        char title[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
    } muxshot;

    struct {
        char title[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
        char primary[MAX_BUFFER_SIZE];
        char secondary[MAX_BUFFER_SIZE];
        char external[MAX_BUFFER_SIZE];
        char system[MAX_BUFFER_SIZE];
        struct {
            char filesystem[MAX_BUFFER_SIZE];
            char quality_check[MAX_BUFFER_SIZE];
            char manufacturer[MAX_BUFFER_SIZE];
            char model[MAX_BUFFER_SIZE];
            char date[MAX_BUFFER_SIZE];
        } detail;
        struct {
            char genuine[MAX_BUFFER_SIZE];
            char likely_genuine[MAX_BUFFER_SIZE];
            char suspicious[MAX_BUFFER_SIZE];
            char suspected_fake[MAX_BUFFER_SIZE];
            char fake[MAX_BUFFER_SIZE];
            char trash[MAX_BUFFER_SIZE];
        } quality;
    } muxspace;

    struct {
        char title[MAX_BUFFER_SIZE];
        char apps[MAX_BUFFER_SIZE];
        char bios[MAX_BUFFER_SIZE];
        char catalogue[MAX_BUFFER_SIZE];
        char collection[MAX_BUFFER_SIZE];
        char history[MAX_BUFFER_SIZE];
        char init[MAX_BUFFER_SIZE];
        char music[MAX_BUFFER_SIZE];
        char name[MAX_BUFFER_SIZE];
        char network[MAX_BUFFER_SIZE];
        char package[MAX_BUFFER_SIZE];
        char save[MAX_BUFFER_SIZE];
        char screenshot[MAX_BUFFER_SIZE];
        char syncthing[MAX_BUFFER_SIZE];
        char theme[MAX_BUFFER_SIZE];
        char track[MAX_BUFFER_SIZE];
        struct {
            char apps[MAX_BUFFER_SIZE];
            char bios[MAX_BUFFER_SIZE];
            char catalogue[MAX_BUFFER_SIZE];
            char collection[MAX_BUFFER_SIZE];
            char history[MAX_BUFFER_SIZE];
            char init[MAX_BUFFER_SIZE];
            char music[MAX_BUFFER_SIZE];
            char name[MAX_BUFFER_SIZE];
            char network[MAX_BUFFER_SIZE];
            char package[MAX_BUFFER_SIZE];
            char save[MAX_BUFFER_SIZE];
            char screenshot[MAX_BUFFER_SIZE];
            char syncthing[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
            char track[MAX_BUFFER_SIZE];
        } help;
    } muxstorage;

    struct {
        char title[MAX_BUFFER_SIZE];
        char day[MAX_BUFFER_SIZE];
        char hour[MAX_BUFFER_SIZE];
        char minute[MAX_BUFFER_SIZE];
        char version[MAX_BUFFER_SIZE];
        char build[MAX_BUFFER_SIZE];
        char device[MAX_BUFFER_SIZE];
        char kernel[MAX_BUFFER_SIZE];
        char arch[MAX_BUFFER_SIZE];
        char uptime[MAX_BUFFER_SIZE];
        char boot_time[MAX_BUFFER_SIZE];
        char load_avg[MAX_BUFFER_SIZE];
        struct {
            char info[MAX_BUFFER_SIZE];
            char drop[MAX_BUFFER_SIZE];
        } memory;
        char swap[MAX_BUFFER_SIZE];
        char temp[MAX_BUFFER_SIZE];
        char reload[MAX_BUFFER_SIZE];
        char reload_run[MAX_BUFFER_SIZE];
        struct {
            char info[MAX_BUFFER_SIZE];
            char speed[MAX_BUFFER_SIZE];
            char governor[MAX_BUFFER_SIZE];
        } cpu;
        char warn[MAX_BUFFER_SIZE];
        struct {
            char version[MAX_BUFFER_SIZE];
            char build[MAX_BUFFER_SIZE];
            char device[MAX_BUFFER_SIZE];
            char kernel[MAX_BUFFER_SIZE];
            char arch[MAX_BUFFER_SIZE];
            char uptime[MAX_BUFFER_SIZE];
            char boot_time[MAX_BUFFER_SIZE];
            char load_avg[MAX_BUFFER_SIZE];
            char memory[MAX_BUFFER_SIZE];
            char swap[MAX_BUFFER_SIZE];
            char temp[MAX_BUFFER_SIZE];
            char service[MAX_BUFFER_SIZE];
            char reload[MAX_BUFFER_SIZE];
            char cpu[MAX_BUFFER_SIZE];
            char speed[MAX_BUFFER_SIZE];
            char governor[MAX_BUFFER_SIZE];
        } help;
    } muxsysinfo;

    struct {
        char help[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char title[MAX_BUFFER_SIZE];
    } muxtag;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
    } muxtask;

    struct {
        char title[MAX_BUFFER_SIZE];
        char quit[MAX_BUFFER_SIZE];
        char quit_alt[MAX_BUFFER_SIZE];
    } muxtester;

    struct {
        char title[MAX_BUFFER_SIZE];
        char theme_down[MAX_BUFFER_SIZE];
        char invalid_ver[MAX_BUFFER_SIZE];
        char invalid_res[MAX_BUFFER_SIZE];
        char protected_theme[MAX_BUFFER_SIZE];
        char no_credit[MAX_BUFFER_SIZE];
    } muxtheme;

    struct {
        char title[MAX_BUFFER_SIZE];
        char theme_removed[MAX_BUFFER_SIZE];
        char theme_extracting[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char download[MAX_BUFFER_SIZE];
        struct {
            char theme[MAX_BUFFER_SIZE];
            char data[MAX_BUFFER_SIZE];
            char preview[MAX_BUFFER_SIZE];
        } down;
        char remove[MAX_BUFFER_SIZE];
        char error_get_data[MAX_BUFFER_SIZE];
        char no_credit[MAX_BUFFER_SIZE];
    } muxthemedown;

    struct {
        char title[MAX_BUFFER_SIZE];
        char grid[MAX_BUFFER_SIZE];
        char hdmi[MAX_BUFFER_SIZE];
        char language[MAX_BUFFER_SIZE];
        char lookup[MAX_BUFFER_SIZE];
        char all_themes[MAX_BUFFER_SIZE];
        struct {
            char device[MAX_BUFFER_SIZE];
            char all[MAX_BUFFER_SIZE];
        } compat;
        struct {
            char all_themes[MAX_BUFFER_SIZE];
            char grid[MAX_BUFFER_SIZE];
            char hdmi[MAX_BUFFER_SIZE];
            char language[MAX_BUFFER_SIZE];
            char lookup[MAX_BUFFER_SIZE];
        } help;
    } muxthemefilter;

    struct {
        char title[MAX_BUFFER_SIZE];
        char header_height[MAX_BUFFER_SIZE];
        char footer_height[MAX_BUFFER_SIZE];
        char content_item_count[MAX_BUFFER_SIZE];
        char glyph_list[MAX_BUFFER_SIZE];
        char glyph_footer[MAX_BUFFER_SIZE];
        char glyph_header[MAX_BUFFER_SIZE];
        char glyph_grid[MAX_BUFFER_SIZE];
        char size_default[MAX_BUFFER_SIZE];
        char glyph_auto[MAX_BUFFER_SIZE];
        char glyph_native[MAX_BUFFER_SIZE];
        char label_width[MAX_BUFFER_SIZE];
        struct {
            char header_height[MAX_BUFFER_SIZE];
            char footer_height[MAX_BUFFER_SIZE];
            char content_item_count[MAX_BUFFER_SIZE];
            char glyph_list[MAX_BUFFER_SIZE];
            char glyph_footer[MAX_BUFFER_SIZE];
            char glyph_header[MAX_BUFFER_SIZE];
            char glyph_grid[MAX_BUFFER_SIZE];
            char label_width[MAX_BUFFER_SIZE];
        } help;
    } muxthemeopt;

    struct {
        char title[MAX_BUFFER_SIZE];
        char none[MAX_BUFFER_SIZE];
        char save[MAX_BUFFER_SIZE];
        char help[MAX_BUFFER_SIZE];
    } muxtimezone;

    struct {
        char title[MAX_BUFFER_SIZE];
        char accelerate[MAX_BUFFER_SIZE];
        char repeatdelay[MAX_BUFFER_SIZE];
        char thermal[MAX_BUFFER_SIZE];
        char led[MAX_BUFFER_SIZE];
        char randomtheme[MAX_BUFFER_SIZE];
        char retrowait[MAX_BUFFER_SIZE];
        char retrofree[MAX_BUFFER_SIZE];
        char retrocache[MAX_BUFFER_SIZE];
        char activity[MAX_BUFFER_SIZE];
        char verbose[MAX_BUFFER_SIZE];
        char debuglog[MAX_BUFFER_SIZE];
        char userinit[MAX_BUFFER_SIZE];
        char dpadswap[MAX_BUFFER_SIZE];
        char overdrive[MAX_BUFFER_SIZE];
        char swapfile[MAX_BUFFER_SIZE];
        char zramfile[MAX_BUFFER_SIZE];
        char lidswitch[MAX_BUFFER_SIZE];
        char dispsuspend[MAX_BUFFER_SIZE];
        char stageoverlay[MAX_BUFFER_SIZE];
        char secondpart[MAX_BUFFER_SIZE];
        char usbpart[MAX_BUFFER_SIZE];
        char incbright[MAX_BUFFER_SIZE];
        char incvolume[MAX_BUFFER_SIZE];
        char maxgpu[MAX_BUFFER_SIZE];
        char doublebuffer[MAX_BUFFER_SIZE];
        char audioready[MAX_BUFFER_SIZE];
        char audioswap[MAX_BUFFER_SIZE];
        char audiosuspend[MAX_BUFFER_SIZE];
        char btscantimeout[MAX_BUFFER_SIZE];
        char seconds[MAX_BUFFER_SIZE];
        char trustmodify[MAX_BUFFER_SIZE];
        char trustpower[MAX_BUFFER_SIZE];
        char trustremove[MAX_BUFFER_SIZE];
        char usbfunction[MAX_BUFFER_SIZE];
        char box_art_pad_div[MAX_BUFFER_SIZE];
        char adb[MAX_BUFFER_SIZE];
        char mtp[MAX_BUFFER_SIZE];
        struct {
            char title[MAX_BUFFER_SIZE];
            char dpad[MAX_BUFFER_SIZE];
            char ls[MAX_BUFFER_SIZE];
            char rs[MAX_BUFFER_SIZE];
            char dpad_ls[MAX_BUFFER_SIZE];
            char dpad_rs[MAX_BUFFER_SIZE];
            char dpad_ls_rs[MAX_BUFFER_SIZE];
            char ls_rs[MAX_BUFFER_SIZE];
        } sticknav;
        struct {
            char title[MAX_BUFFER_SIZE];
            char silent[MAX_BUFFER_SIZE];
            char soft[MAX_BUFFER_SIZE];
            char loud[MAX_BUFFER_SIZE];
        } volume;
        struct {
            char title[MAX_BUFFER_SIZE];
            char low[MAX_BUFFER_SIZE];
            char medium[MAX_BUFFER_SIZE];
            char high[MAX_BUFFER_SIZE];
        } brightness;
        struct {
            char title[MAX_BUFFER_SIZE];
            char st[MAX_BUFFER_SIZE];
            char sh[MAX_BUFFER_SIZE];
            char sl[MAX_BUFFER_SIZE];
            char stsh[MAX_BUFFER_SIZE];
            char stsl[MAX_BUFFER_SIZE];
            char shsl[MAX_BUFFER_SIZE];
        } rumble;
        struct {
            char accelerate[MAX_BUFFER_SIZE];
            char repeat_delay[MAX_BUFFER_SIZE];
            char thermal[MAX_BUFFER_SIZE];
            char led[MAX_BUFFER_SIZE];
            char random_theme[MAX_BUFFER_SIZE];
            char retro_wait[MAX_BUFFER_SIZE];
            char retro_free[MAX_BUFFER_SIZE];
            char retro_cache[MAX_BUFFER_SIZE];
            char activity[MAX_BUFFER_SIZE];
            char verbose[MAX_BUFFER_SIZE];
            char debug_log[MAX_BUFFER_SIZE];
            char user_init[MAX_BUFFER_SIZE];
            char dpad_swap[MAX_BUFFER_SIZE];
            char overdrive[MAX_BUFFER_SIZE];
            char swapfile[MAX_BUFFER_SIZE];
            char zramfile[MAX_BUFFER_SIZE];
            char lid_switch[MAX_BUFFER_SIZE];
            char rumble[MAX_BUFFER_SIZE];
            char brightness[MAX_BUFFER_SIZE];
            char volume[MAX_BUFFER_SIZE];
            char stick_nav[MAX_BUFFER_SIZE];
            char disp_suspend[MAX_BUFFER_SIZE];
            char stage_overlay[MAX_BUFFER_SIZE];
            char second_part[MAX_BUFFER_SIZE];
            char usb_part[MAX_BUFFER_SIZE];
            char inc_bright[MAX_BUFFER_SIZE];
            char inc_volume[MAX_BUFFER_SIZE];
            char max_gpu[MAX_BUFFER_SIZE];
            char double_buffer[MAX_BUFFER_SIZE];
            char audio_ready[MAX_BUFFER_SIZE];
            char audio_swap[MAX_BUFFER_SIZE];
            char audio_suspend[MAX_BUFFER_SIZE];
            char bt_scan_timeout[MAX_BUFFER_SIZE];
            char trust_modify[MAX_BUFFER_SIZE];
            char trust_power[MAX_BUFFER_SIZE];
            char trust_remove[MAX_BUFFER_SIZE];
            char usb_function[MAX_BUFFER_SIZE];
            char box_art_pad_div[MAX_BUFFER_SIZE];
        } help;
    } muxtweakadv;

    struct {
        char title[MAX_BUFFER_SIZE];
        char rtc[MAX_BUFFER_SIZE];
        char brightness[MAX_BUFFER_SIZE];
        char brightness_set[MAX_BUFFER_SIZE];
        char volume[MAX_BUFFER_SIZE];
        char volume_set[MAX_BUFFER_SIZE];
        char hdmi[MAX_BUFFER_SIZE];
        char advanced[MAX_BUFFER_SIZE];
        char rgb[MAX_BUFFER_SIZE];
        char hkdpad[MAX_BUFFER_SIZE];
        char hkshot[MAX_BUFFER_SIZE];
        char audiosink[MAX_BUFFER_SIZE];
        struct {
            char title[MAX_BUFFER_SIZE];
            char menu[MAX_BUFFER_SIZE];
            char explore[MAX_BUFFER_SIZE];
            char collection[MAX_BUFFER_SIZE];
            char history[MAX_BUFFER_SIZE];
            char last[MAX_BUFFER_SIZE];
            char resume[MAX_BUFFER_SIZE];
        } startup;
        char inputremap[MAX_BUFFER_SIZE];
        char passcode[MAX_BUFFER_SIZE];
        char displaytemp[MAX_BUFFER_SIZE];
        char warn[MAX_BUFFER_SIZE];
        char warn_danger[MAX_BUFFER_SIZE];
        struct {
            char title[MAX_BUFFER_SIZE];
            char rtc[MAX_BUFFER_SIZE];
            char startup[MAX_BUFFER_SIZE];
            char brightness[MAX_BUFFER_SIZE];
            char volume[MAX_BUFFER_SIZE];
            char hdmi[MAX_BUFFER_SIZE];
            char advanced[MAX_BUFFER_SIZE];
            char rgb[MAX_BUFFER_SIZE];
            char hk_dpad[MAX_BUFFER_SIZE];
            char hk_shot[MAX_BUFFER_SIZE];
            char audio_sink[MAX_BUFFER_SIZE];
            char input_remap[MAX_BUFFER_SIZE];
            char pass_code[MAX_BUFFER_SIZE];
            char display_temp[MAX_BUFFER_SIZE];
        } help;
    } muxtweakgen;

    struct {
        char title[MAX_BUFFER_SIZE];
        char dflt[MAX_BUFFER_SIZE];
        char collection[MAX_BUFFER_SIZE];
        char history[MAX_BUFFER_SIZE];
        char abandoned[MAX_BUFFER_SIZE];
        char alternate[MAX_BUFFER_SIZE];
        char backlog[MAX_BUFFER_SIZE];
        char complected[MAX_BUFFER_SIZE];
        char completed[MAX_BUFFER_SIZE];
        char cursed[MAX_BUFFER_SIZE];
        char experimental[MAX_BUFFER_SIZE];
        char homebrew[MAX_BUFFER_SIZE];
        char inprogress[MAX_BUFFER_SIZE];
        char patched[MAX_BUFFER_SIZE];
        char replay[MAX_BUFFER_SIZE];
        char romhack[MAX_BUFFER_SIZE];
        char translated[MAX_BUFFER_SIZE];
        struct {
            char dflt[MAX_BUFFER_SIZE];
            char collection[MAX_BUFFER_SIZE];
            char history[MAX_BUFFER_SIZE];
            char tag[MAX_BUFFER_SIZE];
        } help;
    } muxsort;

    struct {
        char title[MAX_BUFFER_SIZE];
        char sort[MAX_BUFFER_SIZE];
        char battery[MAX_BUFFER_SIZE];
        char clock[MAX_BUFFER_SIZE];
        char network[MAX_BUFFER_SIZE];
        char bluetooth[MAX_BUFFER_SIZE];
        char headertitle[MAX_BUFFER_SIZE];
        char dialoguetransition[MAX_BUFFER_SIZE];
        char dash[MAX_BUFFER_SIZE];
        char friendlyfolder[MAX_BUFFER_SIZE];
        char thetitleformat[MAX_BUFFER_SIZE];
        char titleincluderootdrive[MAX_BUFFER_SIZE];
        char folderitemcount[MAX_BUFFER_SIZE];
        char displayemptyfolder[MAX_BUFFER_SIZE];
        char menucounterfolder[MAX_BUFFER_SIZE];
        char menucounterfile[MAX_BUFFER_SIZE];
        char hidden[MAX_BUFFER_SIZE];
        char contentcollect[MAX_BUFFER_SIZE];
        char contenthistory[MAX_BUFFER_SIZE];
        char mixedcontent[MAX_BUFFER_SIZE];
        char forwardhistory[MAX_BUFFER_SIZE];
        char namescroll[MAX_BUFFER_SIZE];
        char labelscrollspeed[MAX_BUFFER_SIZE];
        char listglyph[MAX_BUFFER_SIZE];
        char selectionanimation[MAX_BUFFER_SIZE];
        char selectionstyle[MAX_BUFFER_SIZE];
        char rendershadows[MAX_BUFFER_SIZE];
        struct {
            char disabled[MAX_BUFFER_SIZE];
            char continuous[MAX_BUFFER_SIZE];
            char bounce[MAX_BUFFER_SIZE];
        } scroll_mode;
        struct {
            char fade_in[MAX_BUFFER_SIZE];
            char slide_right[MAX_BUFFER_SIZE];
            char slide_left[MAX_BUFFER_SIZE];
            char slide_up[MAX_BUFFER_SIZE];
            char slide_down[MAX_BUFFER_SIZE];
            char bounce_right[MAX_BUFFER_SIZE];
            char bounce_left[MAX_BUFFER_SIZE];
            char bounce_up[MAX_BUFFER_SIZE];
            char bounce_down[MAX_BUFFER_SIZE];
            char shoot_right[MAX_BUFFER_SIZE];
            char shoot_left[MAX_BUFFER_SIZE];
            char shoot_up[MAX_BUFFER_SIZE];
            char shoot_down[MAX_BUFFER_SIZE];
        } transition;
        struct {
            char image[MAX_BUFFER_SIZE];
            char transparency[MAX_BUFFER_SIZE];
            char theme[MAX_BUFFER_SIZE];
            struct {
                char t1[MAX_BUFFER_SIZE];
                char t4[MAX_BUFFER_SIZE];
            } checkerboard;
            struct {
                char t1[MAX_BUFFER_SIZE];
                char t2[MAX_BUFFER_SIZE];
                char t4[MAX_BUFFER_SIZE];
            } diagonal;
            struct {
                char t1[MAX_BUFFER_SIZE];
                char t4[MAX_BUFFER_SIZE];
            } lattice;
            struct {
                char t1[MAX_BUFFER_SIZE];
                char t2[MAX_BUFFER_SIZE];
                char t4[MAX_BUFFER_SIZE];
            } horizontal;
            struct {
                char t1[MAX_BUFFER_SIZE];
                char t2[MAX_BUFFER_SIZE];
                char t4[MAX_BUFFER_SIZE];
            } vertical;
        } overlay;
        struct {
            char title[MAX_BUFFER_SIZE];
            char full[MAX_BUFFER_SIZE];
            char rem_sq[MAX_BUFFER_SIZE];
            char rem_pa[MAX_BUFFER_SIZE];
            char rem_sqpa[MAX_BUFFER_SIZE];
        } name;
        struct {
            char sort[MAX_BUFFER_SIZE];
            char battery[MAX_BUFFER_SIZE];
            char clock[MAX_BUFFER_SIZE];
            char network[MAX_BUFFER_SIZE];
            char bluetooth[MAX_BUFFER_SIZE];
            char header_title[MAX_BUFFER_SIZE];
            char dialogue_transition[MAX_BUFFER_SIZE];
            char dash[MAX_BUFFER_SIZE];
            char friendly_folder[MAX_BUFFER_SIZE];
            char the_title_format[MAX_BUFFER_SIZE];
            char title_include_root_drive[MAX_BUFFER_SIZE];
            char folder_item_count[MAX_BUFFER_SIZE];
            char display_empty_folder[MAX_BUFFER_SIZE];
            char menu_counter_folder[MAX_BUFFER_SIZE];
            char menu_counter_file[MAX_BUFFER_SIZE];
            char name[MAX_BUFFER_SIZE];
            char hidden[MAX_BUFFER_SIZE];
            char content_collect[MAX_BUFFER_SIZE];
            char content_history[MAX_BUFFER_SIZE];
            char mixed_content[MAX_BUFFER_SIZE];
            char forward_history[MAX_BUFFER_SIZE];
            char name_scroll[MAX_BUFFER_SIZE];
            char label_scroll_speed[MAX_BUFFER_SIZE];
            char list_glyph[MAX_BUFFER_SIZE];
            char selection_animation[MAX_BUFFER_SIZE];
            char selection_style[MAX_BUFFER_SIZE];
            char render_shadows[MAX_BUFFER_SIZE];
            char overlay_image[MAX_BUFFER_SIZE];
            char overlay_transparency[MAX_BUFFER_SIZE];
        } help;
    } muxvisual;

    struct {
        char title[MAX_BUFFER_SIZE];
        char ttyd[MAX_BUFFER_SIZE];
        char syncthing[MAX_BUFFER_SIZE];
        char sshd[MAX_BUFFER_SIZE];
        char sftpgo[MAX_BUFFER_SIZE];
        char tailscaled[MAX_BUFFER_SIZE];
        struct {
            char ttyd[MAX_BUFFER_SIZE];
            char syncthing[MAX_BUFFER_SIZE];
            char sshd[MAX_BUFFER_SIZE];
            char sftp_go[MAX_BUFFER_SIZE];
            char tailscaled[MAX_BUFFER_SIZE];
        } help;
    } muxwebserv;
};

void load_lang(struct mux_lang *lang);

void common_var_init(void);

void load_language_file(const char *module);

char *translate_generic(char *key);

char *translate_help(char *key);

char *translate_specific(char *key);

void fill_generic(const char *key, char *field, size_t size);

void fill_specific(const char *key, char *field, size_t size);
