#pragma once

#include "options.h"

extern struct mux_lang lang;

struct mux_lang {
    struct {
        char NO_JOY_GENERAL[MAX_BUFFER_SIZE];
        char NO_JOY_POWER[MAX_BUFFER_SIZE];
        char NO_JOY_VOLUME[MAX_BUFFER_SIZE];
        char NO_JOY_EXTRA[MAX_BUFFER_SIZE];
        char FAIL_ALLOCATE_MEM[MAX_BUFFER_SIZE];
        char FAIL_DUP_STRING[MAX_BUFFER_SIZE];
        char FAIL_DIR_OPEN[MAX_BUFFER_SIZE];
        char FAIL_FILE_OPEN[MAX_BUFFER_SIZE];
        char FAIL_FILE_WRITE[MAX_BUFFER_SIZE];
        char FAIL_FILE_READ[MAX_BUFFER_SIZE];
        char FAIL_FORK[MAX_BUFFER_SIZE];
        char FAIL_RUN_COMMAND[MAX_BUFFER_SIZE];
        char FAIL_READ_COMMAND[MAX_BUFFER_SIZE];
        char FAIL_CLOSE_COMMAND[MAX_BUFFER_SIZE];
        char FAIL_DELETE_FILE[MAX_BUFFER_SIZE];
        char FAIL_CREATE_FILE[MAX_BUFFER_SIZE];
        char FAIL_STAT[MAX_BUFFER_SIZE];
        char FAIL_PROC_PART[MAX_BUFFER_SIZE];
        char FAIL_INT16_LENGTH[MAX_BUFFER_SIZE];
    } SYSTEM;

    struct {
        char ADD[MAX_BUFFER_SIZE];
        char ADD_COLLECT[MAX_BUFFER_SIZE];
        char ALLOWED[MAX_BUFFER_SIZE];
        char BACK[MAX_BUFFER_SIZE];
        char CANNOT_DELETE_ACTIVE_THEME[MAX_BUFFER_SIZE];
        char CHANGE[MAX_BUFFER_SIZE];
        char CHANNEL[MAX_BUFFER_SIZE];
        char CHECK[MAX_BUFFER_SIZE];
        char CLEAR[MAX_BUFFER_SIZE];
        char CLOSE[MAX_BUFFER_SIZE];
        char COLLECT[MAX_BUFFER_SIZE];
        char CONTENT[MAX_BUFFER_SIZE];
        char DIRECTORY[MAX_BUFFER_SIZE];
        char DISABLED[MAX_BUFFER_SIZE];
        char DOWNLOAD[MAX_BUFFER_SIZE];
        char EDIT[MAX_BUFFER_SIZE];
        char ENABLED[MAX_BUFFER_SIZE];
        char EXCLUDED[MAX_BUFFER_SIZE];
        char EXTRACT[MAX_BUFFER_SIZE];
        char EXTRACTING_ARCHIVE[MAX_BUFFER_SIZE];
        char FILTER[MAX_BUFFER_SIZE];
        char HIDDEN[MAX_BUFFER_SIZE];
        char HOLD_REMOVE[MAX_BUFFER_SIZE];
        char HOLD_RESET[MAX_BUFFER_SIZE];
        char INCLUDED[MAX_BUFFER_SIZE];
        char INFO[MAX_BUFFER_SIZE];
        char INSTALL[MAX_BUFFER_SIZE];
        char KIOSK_DISABLE[MAX_BUFFER_SIZE];
        char LAUNCH[MAX_BUFFER_SIZE];
        char LOADING[MAX_BUFFER_SIZE];
        char LOAD[MAX_BUFFER_SIZE];
        char MIGRATE[MAX_BUFFER_SIZE];
        char NEED_CONNECT[MAX_BUFFER_SIZE];
        char INVALID_TIME[MAX_BUFFER_SIZE];
        char NEW[MAX_BUFFER_SIZE];
        char NOGLYPH[MAX_BUFFER_SIZE];
        char NOT_CONNECTED[MAX_BUFFER_SIZE];
        char NO_HELP[MAX_BUFFER_SIZE];
        char NO_INFO[MAX_BUFFER_SIZE];
        char NO_LOAD[MAX_BUFFER_SIZE];
        char OFFLINE[MAX_BUFFER_SIZE];
        char ONLINE[MAX_BUFFER_SIZE];
        char OPEN[MAX_BUFFER_SIZE];
        char OPTION[MAX_BUFFER_SIZE];
        char PREVIOUS[MAX_BUFFER_SIZE];
        char READ[MAX_BUFFER_SIZE];
        char REBOOTING[MAX_BUFFER_SIZE];
        char RECURSIVE[MAX_BUFFER_SIZE];
        char REFRESH[MAX_BUFFER_SIZE];
        char REFRESH_RUN[MAX_BUFFER_SIZE];
        char REMOVE[MAX_BUFFER_SIZE];
        char REMOVE_FAIL[MAX_BUFFER_SIZE];
        char RESCAN[MAX_BUFFER_SIZE];
        char RESET[MAX_BUFFER_SIZE];
        char RESTORE[MAX_BUFFER_SIZE];
        char RESTRICTED[MAX_BUFFER_SIZE];
        char SAVE[MAX_BUFFER_SIZE];
        char SAVING[MAX_BUFFER_SIZE];
        char SCROLL[MAX_BUFFER_SIZE];
        char SELECT[MAX_BUFFER_SIZE];
        char SET[MAX_BUFFER_SIZE];
        char SHUTTING_DOWN[MAX_BUFFER_SIZE];
        char SWITCH_IMAGE[MAX_BUFFER_SIZE];
        char SWITCH_INFO[MAX_BUFFER_SIZE];
        char SYNC[MAX_BUFFER_SIZE];
        char TOGGLE_ALL[MAX_BUFFER_SIZE];
        char TOP[MAX_BUFFER_SIZE];
        char UNKNOWN[MAX_BUFFER_SIZE];
        char USER_DEFINED[MAX_BUFFER_SIZE];
        char USE[MAX_BUFFER_SIZE];
        char VISIBLE[MAX_BUFFER_SIZE];
        char SUNDAY[MAX_BUFFER_SIZE];
        char MONDAY[MAX_BUFFER_SIZE];
        char TUESDAY[MAX_BUFFER_SIZE];
        char WEDNESDAY[MAX_BUFFER_SIZE];
        char THURSDAY[MAX_BUFFER_SIZE];
        char FRIDAY[MAX_BUFFER_SIZE];
        char SATURDAY[MAX_BUFFER_SIZE];
        char CLEAN[MAX_BUFFER_SIZE];
        char MODIFIED[MAX_BUFFER_SIZE];
    } GENERIC;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char INFO[MAX_BUFFER_SIZE];
        char LAUNCH[MAX_BUFFER_SIZE];
        char TIME[MAX_BUFFER_SIZE];
        char HTML[MAX_BUFFER_SIZE];
        char UNIQUE[MAX_BUFFER_SIZE];
        struct {
            char NAME[MAX_BUFFER_SIZE];
            char CORE[MAX_BUFFER_SIZE];
            char LAUNCH[MAX_BUFFER_SIZE];
            char DEVICE[MAX_BUFFER_SIZE];
            char MODE[MAX_BUFFER_SIZE];
            char PLAYED[MAX_BUFFER_SIZE];
            char AVERAGE[MAX_BUFFER_SIZE];
            char TOTAL[MAX_BUFFER_SIZE];
            char LAST[MAX_BUFFER_SIZE];
        } DETAIL;
        struct {
            char NAV[MAX_BUFFER_SIZE];
            char TOP_TIME[MAX_BUFFER_SIZE];
            char TOP_LAUNCH[MAX_BUFFER_SIZE];
            char CORE[MAX_BUFFER_SIZE];
            char DEVICE[MAX_BUFFER_SIZE];
            char MODE[MAX_BUFFER_SIZE];
            char LAUNCH[MAX_BUFFER_SIZE];
            char TOTAL[MAX_BUFFER_SIZE];
            char AVERAGE[MAX_BUFFER_SIZE];
            char OLDEST[MAX_BUFFER_SIZE];
            char LONGEST[MAX_BUFFER_SIZE];
            char OVERALL[MAX_BUFFER_SIZE];
            char UNIQUE_PLAY[MAX_BUFFER_SIZE];
            char UNIQUE_CORE[MAX_BUFFER_SIZE];
            char ACTIVE_TIME[MAX_BUFFER_SIZE];
            char FAVOURITE_DAY[MAX_BUFFER_SIZE];
        } GLOBAL;
        struct {
            struct {
                char LABEL[MAX_BUFFER_SIZE];
                char ONE[MAX_BUFFER_SIZE];
                char SAMPLER[MAX_BUFFER_SIZE];
                char BURST[MAX_BUFFER_SIZE];
                char LONG[MAX_BUFFER_SIZE];
                char COMPLETIONIST[MAX_BUFFER_SIZE];
                char ABANDONED[MAX_BUFFER_SIZE];
                char MARATHONER[MAX_BUFFER_SIZE];
                char RETURNER[MAX_BUFFER_SIZE];
                char ON_OFF[MAX_BUFFER_SIZE];
                char WEEKEND[MAX_BUFFER_SIZE];
                char COMFORT[MAX_BUFFER_SIZE];
                char REGULAR[MAX_BUFFER_SIZE];
            } LOCAL;
            struct {
                char LABEL[MAX_BUFFER_SIZE];
                char CASUAL[MAX_BUFFER_SIZE];
                char CORE[MAX_BUFFER_SIZE];
                char EXPLORER[MAX_BUFFER_SIZE];
                char BINGER[MAX_BUFFER_SIZE];
                char COMPLETIONIST[MAX_BUFFER_SIZE];
                char POWER[MAX_BUFFER_SIZE];
                char COLLECTOR[MAX_BUFFER_SIZE];
                char SPECIALIST[MAX_BUFFER_SIZE];
                char NOMAD[MAX_BUFFER_SIZE];
                char ROUTINE[MAX_BUFFER_SIZE];
                char HABITUAL[MAX_BUFFER_SIZE];
                char WINDOW[MAX_BUFFER_SIZE];
            } GLOBAL;
        } STYLE;
    } MUXACTIVITY;

    struct {
        char LOAD_APP[MAX_BUFFER_SIZE];
        char NO_APP[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
        char ARCHIVE[MAX_BUFFER_SIZE];
        char TASK[MAX_BUFFER_SIZE];
    } MUXAPP;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NAME[MAX_BUFFER_SIZE];
        char GOVERNOR[MAX_BUFFER_SIZE];
        char CONTROL[MAX_BUFFER_SIZE];
        struct {
            char GOVERNOR[MAX_BUFFER_SIZE];
            char CONTROL[MAX_BUFFER_SIZE];
        } HELP;
    } MUXAPPCON;

    struct {
        char HELP[MAX_BUFFER_SIZE];
        char INSTALLED[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
    } MUXARCHIVE;

    struct {
        char DIR[MAX_BUFFER_SIZE];
        char FILE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
        char CORE_DOWN[MAX_BUFFER_SIZE];
    } MUXASSIGN;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char APPS[MAX_BUFFER_SIZE];
        char BIOS[MAX_BUFFER_SIZE];
        char CATALOGUE[MAX_BUFFER_SIZE];
        char CHEATS[MAX_BUFFER_SIZE];
        char COLLECTION[MAX_BUFFER_SIZE];
        char CONFIG[MAX_BUFFER_SIZE];
        char CONTENT[MAX_BUFFER_SIZE];
        char HISTORY[MAX_BUFFER_SIZE];
        char INIT[MAX_BUFFER_SIZE];
        char MUSIC[MAX_BUFFER_SIZE];;
        char NAME[MAX_BUFFER_SIZE];
        char NETWORK[MAX_BUFFER_SIZE];
        char OVERLAYS[MAX_BUFFER_SIZE];
        char OVERRIDE[MAX_BUFFER_SIZE];
        char PACKAGE[MAX_BUFFER_SIZE];
        char SAVE[MAX_BUFFER_SIZE];
        char SCREENSHOT[MAX_BUFFER_SIZE];
        char SHADERS[MAX_BUFFER_SIZE];
        char SYNCTHING[MAX_BUFFER_SIZE];
        char THEME[MAX_BUFFER_SIZE];
        char TRACK[MAX_BUFFER_SIZE];
        char TARGET[MAX_BUFFER_SIZE];
        char MERGE[MAX_BUFFER_SIZE];
        char START[MAX_BUFFER_SIZE];
        struct {
            char APPS[MAX_BUFFER_SIZE];
            char BIOS[MAX_BUFFER_SIZE];
            char CATALOGUE[MAX_BUFFER_SIZE];
            char CHEATS[MAX_BUFFER_SIZE];
            char COLLECTION[MAX_BUFFER_SIZE];
            char CONFIG[MAX_BUFFER_SIZE];
            char CONTENT[MAX_BUFFER_SIZE];
            char HISTORY[MAX_BUFFER_SIZE];
            char INIT[MAX_BUFFER_SIZE];
            char MUSIC[MAX_BUFFER_SIZE];;
            char NAME[MAX_BUFFER_SIZE];
            char NETWORK[MAX_BUFFER_SIZE];
            char OVERLAYS[MAX_BUFFER_SIZE];
            char OVERRIDE[MAX_BUFFER_SIZE];
            char PACKAGE[MAX_BUFFER_SIZE];
            char SAVE[MAX_BUFFER_SIZE];
            char SCREENSHOT[MAX_BUFFER_SIZE];
            char SHADERS[MAX_BUFFER_SIZE];
            char SYNCTHING[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
            char TRACK[MAX_BUFFER_SIZE];
            char TARGET[MAX_BUFFER_SIZE];
            char MERGE[MAX_BUFFER_SIZE];
            char START[MAX_BUFFER_SIZE];
        } HELP;
    } MUXBACKUP;

    struct {
        char BOOT[MAX_BUFFER_SIZE];
        char CAPACITY[MAX_BUFFER_SIZE];
        char START[MAX_BUFFER_SIZE];
        char VOLTAGE[MAX_BUFFER_SIZE];
    } MUXCHARGE;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char REFERENCE[MAX_BUFFER_SIZE];
        char STRATUM[MAX_BUFFER_SIZE];
        char REFTIME[MAX_BUFFER_SIZE];
        char SYSTEMTIME[MAX_BUFFER_SIZE];
        char LASTOFFSET[MAX_BUFFER_SIZE];
        char RMSOFFSET[MAX_BUFFER_SIZE];
        char FREQUENCY[MAX_BUFFER_SIZE];
        char ROOTDELAY[MAX_BUFFER_SIZE];
        char ROOTDISP[MAX_BUFFER_SIZE];
        char UPDATEINT[MAX_BUFFER_SIZE];
        char LEAP[MAX_BUFFER_SIZE];
        struct {
            char REFERENCE[MAX_BUFFER_SIZE];
            char STRATUM[MAX_BUFFER_SIZE];
            char REFTIME[MAX_BUFFER_SIZE];
            char SYSTEMTIME[MAX_BUFFER_SIZE];
            char LASTOFFSET[MAX_BUFFER_SIZE];
            char RMSOFFSET[MAX_BUFFER_SIZE];
            char FREQUENCY[MAX_BUFFER_SIZE];
            char ROOTDELAY[MAX_BUFFER_SIZE];
            char ROOTDISP[MAX_BUFFER_SIZE];
            char UPDATEINT[MAX_BUFFER_SIZE];
            char LEAP[MAX_BUFFER_SIZE];
        } HELP;
    } MUXCHRONY;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char TEMPERATURE[MAX_BUFFER_SIZE];
        char BRIGHTNESS[MAX_BUFFER_SIZE];
        char CONTRAST[MAX_BUFFER_SIZE];
        char SATURATION[MAX_BUFFER_SIZE];
        char HUESHIFT[MAX_BUFFER_SIZE];
        char GAMMA[MAX_BUFFER_SIZE];
        struct {
            char TEMPERATURE[MAX_BUFFER_SIZE];
            char BRIGHTNESS[MAX_BUFFER_SIZE];
            char CONTRAST[MAX_BUFFER_SIZE];
            char SATURATION[MAX_BUFFER_SIZE];
            char HUESHIFT[MAX_BUFFER_SIZE];
            char GAMMA[MAX_BUFFER_SIZE];
        } HELP;
    } MUXCOLADJUST;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
    } MUXCOLFILTER;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        struct {
            char REMOVE_FILE[MAX_BUFFER_SIZE];
            char REMOVE_DIR[MAX_BUFFER_SIZE];
            char LOAD[MAX_BUFFER_SIZE];
        } ERROR;
    } MUXCOLLECT;

    struct {
        char CONNECT[MAX_BUFFER_SIZE];
        char CUSTOM[MAX_BUFFER_SIZE];
        char GENERAL[MAX_BUFFER_SIZE];
        char LANGUAGE[MAX_BUFFER_SIZE];
        char STORAGE[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
        char POWER[MAX_BUFFER_SIZE];
        char INTERFACE[MAX_BUFFER_SIZE];
        char COLOUR[MAX_BUFFER_SIZE];
        char OVERLAY[MAX_BUFFER_SIZE];
        char BACKUP[MAX_BUFFER_SIZE];
        struct {
            char CONNECT[MAX_BUFFER_SIZE];
            char CUSTOM[MAX_BUFFER_SIZE];
            char GENERAL[MAX_BUFFER_SIZE];
            char LANGUAGE[MAX_BUFFER_SIZE];
            char STORAGE[MAX_BUFFER_SIZE];
            char POWER[MAX_BUFFER_SIZE];
            char INTERFACE[MAX_BUFFER_SIZE];
            char COLOUR[MAX_BUFFER_SIZE];
            char OVERLAY[MAX_BUFFER_SIZE];
            char BACKUP[MAX_BUFFER_SIZE];
        } HELP;
    } MUXCONFIG;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char BLUETOOTH[MAX_BUFFER_SIZE];
        char NETADV[MAX_BUFFER_SIZE];
        char SERVICES[MAX_BUFFER_SIZE];
        char USBFUNCTION[MAX_BUFFER_SIZE];
        char NETWORK[MAX_BUFFER_SIZE];
        char ADB[MAX_BUFFER_SIZE];
        char MTP[MAX_BUFFER_SIZE];
        struct {
            char BLUETOOTH[MAX_BUFFER_SIZE];
            char NETADV[MAX_BUFFER_SIZE];
            char SERVICES[MAX_BUFFER_SIZE];
            char USBFUNCTION[MAX_BUFFER_SIZE];
            char NETWORK[MAX_BUFFER_SIZE];
        } HELP;
    } MUXCONNECT;

    struct {
        char HELP[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
    } MUXCONTROL;

    struct {
        char CATALOGUE[MAX_BUFFER_SIZE];
        char CONFIG[MAX_BUFFER_SIZE];
        char GRIDMODECONTENT[MAX_BUFFER_SIZE];
        char THEME[MAX_BUFFER_SIZE];
        char THEMERESOLUTION[MAX_BUFFER_SIZE];
        char THEMESCALING[MAX_BUFFER_SIZE];
        char SCREEN[MAX_BUFFER_SIZE];
        char THEMEALTERNATE[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
        char ANIMATION[MAX_BUFFER_SIZE];
        char BLACKFADE[MAX_BUFFER_SIZE];
        char LAUNCHSPLASH[MAX_BUFFER_SIZE];
        char SHUFFLE[MAX_BUFFER_SIZE];
        char CHIME[MAX_BUFFER_SIZE];
        char CONTENTWIDTH[MAX_BUFFER_SIZE];
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char BEHIND[MAX_BUFFER_SIZE];
            char FRONT[MAX_BUFFER_SIZE];
            char HIDE_GRID_MODE[MAX_BUFFER_SIZE];
            char FS_BEHIND[MAX_BUFFER_SIZE];
            char FS_FRONT[MAX_BUFFER_SIZE];
            struct {
                char TITLE[MAX_BUFFER_SIZE];
                char B_LEFT[MAX_BUFFER_SIZE];
                char B_MID[MAX_BUFFER_SIZE];
                char B_RIGHT[MAX_BUFFER_SIZE];
                char M_LEFT[MAX_BUFFER_SIZE];
                char M_MID[MAX_BUFFER_SIZE];
                char M_RIGHT[MAX_BUFFER_SIZE];
                char T_LEFT[MAX_BUFFER_SIZE];
                char T_MID[MAX_BUFFER_SIZE];
                char T_RIGHT[MAX_BUFFER_SIZE];
            } ALIGN;
        } BOX_ART;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char LANG[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
        } FONT;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char VOLUME[MAX_BUFFER_SIZE];
            char SET[MAX_BUFFER_SIZE];
            char GLOBAL[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
        } MUSIC;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char VOLUME[MAX_BUFFER_SIZE];
            char SET[MAX_BUFFER_SIZE];
            char GLOBAL[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
        } SOUND;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char PRESS_A[MAX_BUFFER_SIZE];
            char HOLD_A[MAX_BUFFER_SIZE];
            char LOAD_STATE[MAX_BUFFER_SIZE];
            char START_FRESH[MAX_BUFFER_SIZE];
        } LAUNCH_SWAP;
        struct {
            char NO_SCALE[MAX_BUFFER_SIZE];
            char SCALE[MAX_BUFFER_SIZE];
            char STRETCH[MAX_BUFFER_SIZE];
        } SCALING;
        struct {
            char CATALOGUE[MAX_BUFFER_SIZE];
            char CONFIG[MAX_BUFFER_SIZE];
            char GRIDMODECONTENT[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
            char THEMESCALING[MAX_BUFFER_SIZE];
            char THEMERESOLUTION[MAX_BUFFER_SIZE];
            char THEMEALTERNATE[MAX_BUFFER_SIZE];
            char ANIMATION[MAX_BUFFER_SIZE];
            char BOXARTIMAGE[MAX_BUFFER_SIZE];
            char BOXARTALIGN[MAX_BUFFER_SIZE];
            char BOXARTHIDE[MAX_BUFFER_SIZE];
            char CONTENTWIDTH[MAX_BUFFER_SIZE];
            char BLACKFADE[MAX_BUFFER_SIZE];
            char LAUNCHSPLASH[MAX_BUFFER_SIZE];
            char SHUFFLE[MAX_BUFFER_SIZE];
            char LAUNCHSWAP[MAX_BUFFER_SIZE];
            char FONT[MAX_BUFFER_SIZE];
            char MUSIC[MAX_BUFFER_SIZE];
            char MUSICVOLUME[MAX_BUFFER_SIZE];
            char SOUND[MAX_BUFFER_SIZE];
            char SOUNDVOLUME[MAX_BUFFER_SIZE];
            char CHIME[MAX_BUFFER_SIZE];
        } HELP;
    } MUXCUSTOM;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char VMSWAP[MAX_BUFFER_SIZE];
        char DIRTYRATIO[MAX_BUFFER_SIZE];
        char DIRTYBACK[MAX_BUFFER_SIZE];
        char CACHEPRESSURE[MAX_BUFFER_SIZE];
        char NOMERGE[MAX_BUFFER_SIZE];
        char NRREQUESTS[MAX_BUFFER_SIZE];
        char READAHEAD[MAX_BUFFER_SIZE];
        char PAGECLUSTER[MAX_BUFFER_SIZE];
        char TIMESLICE[MAX_BUFFER_SIZE];
        char IOSTATS[MAX_BUFFER_SIZE];
        char IDLEFLUSH[MAX_BUFFER_SIZE];
        char CHILDFIRST[MAX_BUFFER_SIZE];
        char TUNESCALE[MAX_BUFFER_SIZE];
        char CARDMODE[MAX_BUFFER_SIZE];
        char STATE[MAX_BUFFER_SIZE];
        struct {
            char VMSWAP[MAX_BUFFER_SIZE];
            char DIRTYRATIO[MAX_BUFFER_SIZE];
            char DIRTYBACK[MAX_BUFFER_SIZE];
            char CACHEPRESSURE[MAX_BUFFER_SIZE];
            char NOMERGE[MAX_BUFFER_SIZE];
            char NRREQUESTS[MAX_BUFFER_SIZE];
            char READAHEAD[MAX_BUFFER_SIZE];
            char PAGECLUSTER[MAX_BUFFER_SIZE];
            char TIMESLICE[MAX_BUFFER_SIZE];
            char IOSTATS[MAX_BUFFER_SIZE];
            char IDLEFLUSH[MAX_BUFFER_SIZE];
            char CHILDFIRST[MAX_BUFFER_SIZE];
            char TUNESCALE[MAX_BUFFER_SIZE];
            char CARDMODE[MAX_BUFFER_SIZE];
            char STATE[MAX_BUFFER_SIZE];
        } HELP;
    } MUXDANGER;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char HASBLUETOOTH[MAX_BUFFER_SIZE];
        char HASRGB[MAX_BUFFER_SIZE];
        char HASDEBUGFS[MAX_BUFFER_SIZE];
        char HASHDMI[MAX_BUFFER_SIZE];
        char HASLID[MAX_BUFFER_SIZE];
        char HASNETWORK[MAX_BUFFER_SIZE];
        char HASPORTMASTER[MAX_BUFFER_SIZE];
        struct {
            char HASBLUETOOTH[MAX_BUFFER_SIZE];
            char HASRGB[MAX_BUFFER_SIZE];
            char HASDEBUGFS[MAX_BUFFER_SIZE];
            char HASHDMI[MAX_BUFFER_SIZE];
            char HASLID[MAX_BUFFER_SIZE];
            char HASNETWORK[MAX_BUFFER_SIZE];
            char HASPORTMASTER[MAX_BUFFER_SIZE];
        } HELP;
    } MUXDEVICE;

    struct {
        char ERROR_GET_DATA[MAX_BUFFER_SIZE];
        char ARCHIVE_REMOVED[MAX_BUFFER_SIZE];
        struct {
            char ARCHIVE[MAX_BUFFER_SIZE];
            char DATA[MAX_BUFFER_SIZE];
        } DOWN;
        struct {
            char APP[MAX_BUFFER_SIZE];
            char CORE[MAX_BUFFER_SIZE];
        } TITLE;
    } MUXDOWNLOAD;

    struct {
        char HELP[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
    } MUXGOV;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char REMOVE[MAX_BUFFER_SIZE];
        struct {
            char REMOVE[MAX_BUFFER_SIZE];
            char LOAD[MAX_BUFFER_SIZE];
        } ERROR;
    } MUXHISTORY;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char RESOLUTION[MAX_BUFFER_SIZE];
        struct {
            char DEPTH[MAX_BUFFER_SIZE];
            char SPACE[MAX_BUFFER_SIZE];
            struct {
                char TITLE[MAX_BUFFER_SIZE];
                char FULL[MAX_BUFFER_SIZE];
                char LIMITED[MAX_BUFFER_SIZE];
            } RANGE;
        } COLOUR;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char EXTERNAL[MAX_BUFFER_SIZE];
            char INTERNAL[MAX_BUFFER_SIZE];
        } AUDIO_OUTPUT;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char OVER[MAX_BUFFER_SIZE];
            char UNDER[MAX_BUFFER_SIZE];
        } SCAN_SCALE;
        struct {
            char RESOLUTION[MAX_BUFFER_SIZE];
            char SPACE[MAX_BUFFER_SIZE];
            char DEPTH[MAX_BUFFER_SIZE];
            char RANGE[MAX_BUFFER_SIZE];
            char SCAN[MAX_BUFFER_SIZE];
            char AUDIO[MAX_BUFFER_SIZE];
        } HELP;
    } MUXHDMI;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NEWS[MAX_BUFFER_SIZE];
        char SYSINFO[MAX_BUFFER_SIZE];
        char NETINFO[MAX_BUFFER_SIZE];
        char ACTIVITY[MAX_BUFFER_SIZE];
        char SCREENSHOT[MAX_BUFFER_SIZE];
        char SPACE[MAX_BUFFER_SIZE];
        char TESTER[MAX_BUFFER_SIZE];
        char CHRONY[MAX_BUFFER_SIZE];
        char CREDIT[MAX_BUFFER_SIZE];
        struct {
            char NEWS[MAX_BUFFER_SIZE];
            char SYSINFO[MAX_BUFFER_SIZE];
            char NETINFO[MAX_BUFFER_SIZE];
            char ACTIVITY[MAX_BUFFER_SIZE];
            char SCREENSHOT[MAX_BUFFER_SIZE];
            char SPACE[MAX_BUFFER_SIZE];
            char TESTER[MAX_BUFFER_SIZE];
            char CHRONY[MAX_BUFFER_SIZE];
            char CREDIT[MAX_BUFFER_SIZE];
        } HELP;
    } MUXINFO;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char RTC[MAX_BUFFER_SIZE];
        char LANGUAGE[MAX_BUFFER_SIZE];
        char INSTALL[MAX_BUFFER_SIZE];
        char SHUTDOWN[MAX_BUFFER_SIZE];
        struct {
            char RTC[MAX_BUFFER_SIZE];
            char LANGUAGE[MAX_BUFFER_SIZE];
            char INSTALL[MAX_BUFFER_SIZE];
            char SHUTDOWN[MAX_BUFFER_SIZE];
        } SHORT;
        struct {
            char RTC[MAX_BUFFER_SIZE];
            char LANGUAGE[MAX_BUFFER_SIZE];
            char INSTALL[MAX_BUFFER_SIZE];
            char SHUTDOWN[MAX_BUFFER_SIZE];
        } HELP;
    } MUXINSTALL;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char ENABLE[MAX_BUFFER_SIZE];
        char MESSAGE[MAX_BUFFER_SIZE];
        char ARCHIVE[MAX_BUFFER_SIZE];
        char TASK[MAX_BUFFER_SIZE];
        char CUSTOM[MAX_BUFFER_SIZE];
        char LANGUAGE[MAX_BUFFER_SIZE];
        char NETWORK[MAX_BUFFER_SIZE];
        char STORAGE[MAX_BUFFER_SIZE];
        char BACKUP[MAX_BUFFER_SIZE];
        char NETADV[MAX_BUFFER_SIZE];
        char WEBSERV[MAX_BUFFER_SIZE];
        char CORE[MAX_BUFFER_SIZE];
        char GOVERNOR[MAX_BUFFER_SIZE];
        char CONTROL[MAX_BUFFER_SIZE];
        char OPTION[MAX_BUFFER_SIZE];
        char RETROARCH[MAX_BUFFER_SIZE];
        char SEARCH[MAX_BUFFER_SIZE];
        char TAG[MAX_BUFFER_SIZE];
        char COLFILTER[MAX_BUFFER_SIZE];
        char REMCONFIG[MAX_BUFFER_SIZE];
        char CATALOGUE[MAX_BUFFER_SIZE];
        char RACONFIG[MAX_BUFFER_SIZE];
        char THEME[MAX_BUFFER_SIZE];
        char THEMEDOWN[MAX_BUFFER_SIZE];
        char CLOCK[MAX_BUFFER_SIZE];
        char TIMEZONE[MAX_BUFFER_SIZE];
        char APPS[MAX_BUFFER_SIZE];
        char CONFIG[MAX_BUFFER_SIZE];
        char EXPLORE[MAX_BUFFER_SIZE];
        char INFO[MAX_BUFFER_SIZE];
        char ADVANCED[MAX_BUFFER_SIZE];
        char GENERAL[MAX_BUFFER_SIZE];
        char HDMI[MAX_BUFFER_SIZE];
        char POWER[MAX_BUFFER_SIZE];
        char VISUAL[MAX_BUFFER_SIZE];
        char OVERLAY[MAX_BUFFER_SIZE];
        char COLOUR[MAX_BUFFER_SIZE];
        struct {
            char MAIN[MAX_BUFFER_SIZE];
            char ADD_CONTENT[MAX_BUFFER_SIZE];
            char NEW_DIR[MAX_BUFFER_SIZE];
            char REMOVE[MAX_BUFFER_SIZE];
            char ACCESS[MAX_BUFFER_SIZE];
        } COLLECTION;
        struct {
            char MAIN[MAX_BUFFER_SIZE];
            char REMOVE[MAX_BUFFER_SIZE];
        } HISTORY;
        struct {
            char ENABLE[MAX_BUFFER_SIZE];
            char MESSAGE[MAX_BUFFER_SIZE];
            char ARCHIVE[MAX_BUFFER_SIZE];
            char TASK[MAX_BUFFER_SIZE];
            char CUSTOM[MAX_BUFFER_SIZE];
            char LANGUAGE[MAX_BUFFER_SIZE];
            char NETWORK[MAX_BUFFER_SIZE];
            char STORAGE[MAX_BUFFER_SIZE];
            char BACKUP[MAX_BUFFER_SIZE];
            char NETADV[MAX_BUFFER_SIZE];
            char WEBSERV[MAX_BUFFER_SIZE];
            char CORE[MAX_BUFFER_SIZE];
            char GOVERNOR[MAX_BUFFER_SIZE];
            char CONTROL[MAX_BUFFER_SIZE];
            char OPTION[MAX_BUFFER_SIZE];
            char RETROARCH[MAX_BUFFER_SIZE];
            char SEARCH[MAX_BUFFER_SIZE];
            char TAG[MAX_BUFFER_SIZE];
            char COLFILTER[MAX_BUFFER_SIZE];
            char REMCONFIG[MAX_BUFFER_SIZE];
            char CATALOGUE[MAX_BUFFER_SIZE];
            char RACONFIG[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
            char THEMEDOWN[MAX_BUFFER_SIZE];
            char CLOCK[MAX_BUFFER_SIZE];
            char TIMEZONE[MAX_BUFFER_SIZE];
            char APPS[MAX_BUFFER_SIZE];
            char CONFIG[MAX_BUFFER_SIZE];
            char EXPLORE[MAX_BUFFER_SIZE];
            char INFO[MAX_BUFFER_SIZE];
            char ADVANCED[MAX_BUFFER_SIZE];
            char GENERAL[MAX_BUFFER_SIZE];
            char HDMI[MAX_BUFFER_SIZE];
            char POWER[MAX_BUFFER_SIZE];
            char VISUAL[MAX_BUFFER_SIZE];
            char OVERLAY[MAX_BUFFER_SIZE];
            char COLOUR[MAX_BUFFER_SIZE];
            char COLLECTMOD[MAX_BUFFER_SIZE];
            char COLLECTADD[MAX_BUFFER_SIZE];
            char COLLECTNEW[MAX_BUFFER_SIZE];
            char COLLECTREM[MAX_BUFFER_SIZE];
            char COLLECTACC[MAX_BUFFER_SIZE];
            char HISTORYMOD[MAX_BUFFER_SIZE];
            char HISTORYREM[MAX_BUFFER_SIZE];
        } HELP;
    } MUXKIOSK;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char SAVE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
        char DOWNLOADING[MAX_BUFFER_SIZE];
        char ERROR_GET_DATA[MAX_BUFFER_SIZE];
    } MUXLANGUAGE;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char APPS[MAX_BUFFER_SIZE];
        char CONFIG[MAX_BUFFER_SIZE];
        char INFO[MAX_BUFFER_SIZE];
        char COLLECTION[MAX_BUFFER_SIZE];
        char HISTORY[MAX_BUFFER_SIZE];
        char EXPLORE[MAX_BUFFER_SIZE];
        char SHUTDOWN[MAX_BUFFER_SIZE];
        char REBOOT[MAX_BUFFER_SIZE];
        struct {
            char APP[MAX_BUFFER_SIZE];
            char CONFIG[MAX_BUFFER_SIZE];
            char INFO[MAX_BUFFER_SIZE];
            char COLLECTION[MAX_BUFFER_SIZE];
            char HISTORY[MAX_BUFFER_SIZE];
            char EXPLORE[MAX_BUFFER_SIZE];
            char SHUTDOWN[MAX_BUFFER_SIZE];
            char REBOOT[MAX_BUFFER_SIZE];
        } SHORT;
        struct {
            char ERROR[MAX_BUFFER_SIZE];
            char PROCESS[MAX_BUFFER_SIZE];
        } KIOSK;
        struct {
            char APPS[MAX_BUFFER_SIZE];
            char CONFIG[MAX_BUFFER_SIZE];
            char INFO[MAX_BUFFER_SIZE];
            char COLLECTION[MAX_BUFFER_SIZE];
            char HISTORY[MAX_BUFFER_SIZE];
            char EXPLORE[MAX_BUFFER_SIZE];
            char SHUTDOWN[MAX_BUFFER_SIZE];
            char REBOOT[MAX_BUFFER_SIZE];
        } HELP;
    } MUXLAUNCH;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char MONITOR[MAX_BUFFER_SIZE];
        char BOOT[MAX_BUFFER_SIZE];
        char WAKE[MAX_BUFFER_SIZE];
        char COMPAT[MAX_BUFFER_SIZE];
        char ASYNCLOAD[MAX_BUFFER_SIZE];
        char CONRETRY[MAX_BUFFER_SIZE];
        char WAIT[MAX_BUFFER_SIZE];
        char MODRETRY[MAX_BUFFER_SIZE];
        struct {
            char MONITOR[MAX_BUFFER_SIZE];
            char BOOT[MAX_BUFFER_SIZE];
            char WAKE[MAX_BUFFER_SIZE];
            char COMPAT[MAX_BUFFER_SIZE];
            char ASYNCLOAD[MAX_BUFFER_SIZE];
            char CONRETRY[MAX_BUFFER_SIZE];
            char WAIT[MAX_BUFFER_SIZE];
            char MODRETRY[MAX_BUFFER_SIZE];
        } HELP;
    } MUXNETADV;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char HOSTNAME[MAX_BUFFER_SIZE];
        char MAC[MAX_BUFFER_SIZE];
        char IP[MAX_BUFFER_SIZE];
        char SSID[MAX_BUFFER_SIZE];
        char GATEWAY[MAX_BUFFER_SIZE];
        char DNS[MAX_BUFFER_SIZE];
        char SIGNAL[MAX_BUFFER_SIZE];
        char CHANNEL[MAX_BUFFER_SIZE];
        char ACTRAFFIC[MAX_BUFFER_SIZE];
        char TPTRAFFIC[MAX_BUFFER_SIZE];
        struct {
            char HOSTNAME[MAX_BUFFER_SIZE];
            char MAC[MAX_BUFFER_SIZE];
            char IP[MAX_BUFFER_SIZE];
            char SSID[MAX_BUFFER_SIZE];
            char GATEWAY[MAX_BUFFER_SIZE];
            char DNS[MAX_BUFFER_SIZE];
            char SIGNAL[MAX_BUFFER_SIZE];
            char CHANNEL[MAX_BUFFER_SIZE];
            char ACTRAFFIC[MAX_BUFFER_SIZE];
            char TPTRAFFIC[MAX_BUFFER_SIZE];
        } HELP;
        struct {
            char EDIT[MAX_BUFFER_SIZE];
            char CHANGE[MAX_BUFFER_SIZE];
        } ERROR;
        struct {
            char HOST[MAX_BUFFER_SIZE];
            char MAC[MAX_BUFFER_SIZE];
        } SAVE;
    } MUXNETINFO;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char LOAD[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
        char INVALID_SSID[MAX_BUFFER_SIZE];
        char INVALID_NETWORK[MAX_BUFFER_SIZE];
    } MUXNETPROFILE;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char SCAN[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
    } MUXNETSCAN;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char CONNECT[MAX_BUFFER_SIZE];
        char DISCONNECT[MAX_BUFFER_SIZE];
        char CONNECTED[MAX_BUFFER_SIZE];
        char NOT_CONNECTED[MAX_BUFFER_SIZE];
        char DENY_MODIFY[MAX_BUFFER_SIZE];
        char SAVE[MAX_BUFFER_SIZE];
        char DHCP[MAX_BUFFER_SIZE];
        char STATIC[MAX_BUFFER_SIZE];
        char SCAN[MAX_BUFFER_SIZE];
        char SUBNET[MAX_BUFFER_SIZE];
        char PROFILES[MAX_BUFFER_SIZE];
        char CONNECT_TRY[MAX_BUFFER_SIZE];
        char PASSWORD[MAX_BUFFER_SIZE];
        char NO_PASSWORD[MAX_BUFFER_SIZE];
        char DNS[MAX_BUFFER_SIZE];
        char ADDRESS[MAX_BUFFER_SIZE];
        char ENCRYPT_PASSWORD[MAX_BUFFER_SIZE];
        char GATEWAY[MAX_BUFFER_SIZE];
        char HIDDEN[MAX_BUFFER_SIZE];
        char IDENTIFIER[MAX_BUFFER_SIZE];
        char DISABLED[MAX_BUFFER_SIZE];
        char TYPE[MAX_BUFFER_SIZE];
        char CHECK[MAX_BUFFER_SIZE];
        struct {
            char ASSOCIATING[MAX_BUFFER_SIZE];
            char AUTHENTICATING[MAX_BUFFER_SIZE];
            char WAITING_IP[MAX_BUFFER_SIZE];
            char VALIDATING[MAX_BUFFER_SIZE];
            char INVALID_PASSWORD[MAX_BUFFER_SIZE];
            char AP_NOT_FOUND[MAX_BUFFER_SIZE];
            char AUTH_TIMEOUT[MAX_BUFFER_SIZE];
            char DHCP_FAILED[MAX_BUFFER_SIZE];
            char LINK_TIMEOUT[MAX_BUFFER_SIZE];
            char WPA_START_FAILED[MAX_BUFFER_SIZE];
        } STATUS;
        struct {
            char TYPE[MAX_BUFFER_SIZE];
            char HIDDEN[MAX_BUFFER_SIZE];
            char PASSWORD[MAX_BUFFER_SIZE];
            char IDENTIFIER[MAX_BUFFER_SIZE];
            char GATEWAY[MAX_BUFFER_SIZE];
            char SUBNET[MAX_BUFFER_SIZE];
            char DNS[MAX_BUFFER_SIZE];
            char ADDRESS[MAX_BUFFER_SIZE];
            char CONNECT[MAX_BUFFER_SIZE];
        } HELP;
    } MUXNETWORK;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char DOWNLOAD[MAX_BUFFER_SIZE];
        char ERROR[MAX_BUFFER_SIZE];
        char OPEN[MAX_BUFFER_SIZE];
    } MUXNEWS;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char SEARCH[MAX_BUFFER_SIZE];
        char NAME[MAX_BUFFER_SIZE];
        char TIME[MAX_BUFFER_SIZE];
        char LAUNCH[MAX_BUFFER_SIZE];
        char CURRENT[MAX_BUFFER_SIZE];
        char CORE[MAX_BUFFER_SIZE];
        char GOVERNOR[MAX_BUFFER_SIZE];
        char CONTROL[MAX_BUFFER_SIZE];
        char TAG[MAX_BUFFER_SIZE];
        char RETROARCH[MAX_BUFFER_SIZE];
        char COLFILTER[MAX_BUFFER_SIZE];
        char REMCONFIG[MAX_BUFFER_SIZE];
        char REMCONTENT[MAX_BUFFER_SIZE];
        char REMDIR[MAX_BUFFER_SIZE];
        char REMCORE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char NOT_ASSIGNED[MAX_BUFFER_SIZE];
        struct {
            char CORE[MAX_BUFFER_SIZE];
            char GOVERNOR[MAX_BUFFER_SIZE];
            char CONTROL[MAX_BUFFER_SIZE];
            char TAG[MAX_BUFFER_SIZE];
            char RETROARCH[MAX_BUFFER_SIZE];
            char COLFILTER[MAX_BUFFER_SIZE];
            char REMCONFIG[MAX_BUFFER_SIZE];
            char SEARCH[MAX_BUFFER_SIZE];
        } HELP;
    } MUXOPTION;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        struct {
            struct {
                char LEFT[MAX_BUFFER_SIZE];
                char MIDDLE[MAX_BUFFER_SIZE];
                char RIGHT[MAX_BUFFER_SIZE];
            } TOP;
            struct {
                char LEFT[MAX_BUFFER_SIZE];
                char MIDDLE[MAX_BUFFER_SIZE];
                char RIGHT[MAX_BUFFER_SIZE];
            } CENTRE;
            struct {
                char LEFT[MAX_BUFFER_SIZE];
                char MIDDLE[MAX_BUFFER_SIZE];
                char RIGHT[MAX_BUFFER_SIZE];
            } BOTTOM;
        } ANCHOR;
        struct {
            char ORIGINAL[MAX_BUFFER_SIZE];
            char FIT[MAX_BUFFER_SIZE];
            char STRETCH[MAX_BUFFER_SIZE];
        } SCALE;
        char GENALPHA[MAX_BUFFER_SIZE];
        char GENANCHOR[MAX_BUFFER_SIZE];
        char GENSCALE[MAX_BUFFER_SIZE];
        char BATALPHA[MAX_BUFFER_SIZE];
        char BATANCHOR[MAX_BUFFER_SIZE];
        char BATSCALE[MAX_BUFFER_SIZE];
        char VOLALPHA[MAX_BUFFER_SIZE];
        char VOLANCHOR[MAX_BUFFER_SIZE];
        char VOLSCALE[MAX_BUFFER_SIZE];
        char BRIALPHA[MAX_BUFFER_SIZE];
        char BRIANCHOR[MAX_BUFFER_SIZE];
        char BRISCALE[MAX_BUFFER_SIZE];
        struct {
            char GENALPHA[MAX_BUFFER_SIZE];
            char GENANCHOR[MAX_BUFFER_SIZE];
            char GENSCALE[MAX_BUFFER_SIZE];
            char BATALPHA[MAX_BUFFER_SIZE];
            char BATANCHOR[MAX_BUFFER_SIZE];
            char BATSCALE[MAX_BUFFER_SIZE];
            char VOLALPHA[MAX_BUFFER_SIZE];
            char VOLANCHOR[MAX_BUFFER_SIZE];
            char VOLSCALE[MAX_BUFFER_SIZE];
            char BRIALPHA[MAX_BUFFER_SIZE];
            char BRIANCHOR[MAX_BUFFER_SIZE];
            char BRISCALE[MAX_BUFFER_SIZE];
        } HELP;
    } MUXOVERLAY;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
    } MUXPASS;

    struct {
        char CUSTOM[MAX_BUFFER_SIZE];
        char CATALOGUE[MAX_BUFFER_SIZE];
        char CONFIG[MAX_BUFFER_SIZE];
        char THEME[MAX_BUFFER_SIZE];
        char THEME_DOWN[MAX_BUFFER_SIZE];
        char INVALID_VER[MAX_BUFFER_SIZE];
        char INVALID_RES[MAX_BUFFER_SIZE];
        char PROTECTED[MAX_BUFFER_SIZE];
        struct {
            char CREDIT[MAX_BUFFER_SIZE];
            char CUSTOM[MAX_BUFFER_SIZE];
            char CATALOGUE[MAX_BUFFER_SIZE];
            char CONFIG[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
        } NONE;
    } MUXPICKER;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        struct {
            char NO_FOLDER[MAX_BUFFER_SIZE];
            char NO_CORE[MAX_BUFFER_SIZE];
            char GENERAL[MAX_BUFFER_SIZE];
        } ERROR;
    } MUXPLORE;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char LOW_BATTERY[MAX_BUFFER_SIZE];
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char s30[MAX_BUFFER_SIZE];
            char s60[MAX_BUFFER_SIZE];
            char s90[MAX_BUFFER_SIZE];
            char s120[MAX_BUFFER_SIZE];
            char s240[MAX_BUFFER_SIZE];
        } SCREENSAVER;
        struct {
            char ERROR[MAX_BUFFER_SIZE];
            char DISPLAY[MAX_BUFFER_SIZE];
            char SLEEP[MAX_BUFFER_SIZE];
            char MUTE[MAX_BUFFER_SIZE];
            char t10s[MAX_BUFFER_SIZE];
            char t30s[MAX_BUFFER_SIZE];
            char t60s[MAX_BUFFER_SIZE];
            char t2m[MAX_BUFFER_SIZE];
            char t5m[MAX_BUFFER_SIZE];
            char t10m[MAX_BUFFER_SIZE];
            char t15m[MAX_BUFFER_SIZE];
            char t30m[MAX_BUFFER_SIZE];
        } IDLE;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char INSTANT[MAX_BUFFER_SIZE];
            char SUSPEND[MAX_BUFFER_SIZE];
            char t10s[MAX_BUFFER_SIZE];
            char t30s[MAX_BUFFER_SIZE];
            char t60s[MAX_BUFFER_SIZE];
            char t2m[MAX_BUFFER_SIZE];
            char t5m[MAX_BUFFER_SIZE];
            char t10m[MAX_BUFFER_SIZE];
            char t15m[MAX_BUFFER_SIZE];
            char t30m[MAX_BUFFER_SIZE];
            char t60m[MAX_BUFFER_SIZE];
        } SLEEP;
        struct {
            char DEFAULT[MAX_BUFFER_SIZE];
            char IDLE[MAX_BUFFER_SIZE];
        } GOV;
        struct {
            char SHUTDOWN[MAX_BUFFER_SIZE];
            char BATTERY[MAX_BUFFER_SIZE];
            char IDLESLEEP[MAX_BUFFER_SIZE];
            char IDLEDISPLAY[MAX_BUFFER_SIZE];
            char IDLEMUTE[MAX_BUFFER_SIZE];
            char GOVIDLE[MAX_BUFFER_SIZE];
            char GOVDEFAULT[MAX_BUFFER_SIZE];
            char SCREENSAVER[MAX_BUFFER_SIZE];
        } HELP;
    } MUXPOWER;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
    } MUXRAOPT;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char DAY[MAX_BUFFER_SIZE];
        char MONTH[MAX_BUFFER_SIZE];
        char YEAR[MAX_BUFFER_SIZE];
        char HOUR[MAX_BUFFER_SIZE];
        char MINUTE[MAX_BUFFER_SIZE];
        char TIMEZONE[MAX_BUFFER_SIZE];
        char NOTATION[MAX_BUFFER_SIZE];
        char F_12HR[MAX_BUFFER_SIZE];
        char F_24HR[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
    } MUXRTC;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char GLOBAL[MAX_BUFFER_SIZE];
        char LOCAL[MAX_BUFFER_SIZE];
        char LOOKUP[MAX_BUFFER_SIZE];
        char SEARCH[MAX_BUFFER_SIZE];
        char ERROR[MAX_BUFFER_SIZE];
        struct {
            char SEARCHGLOBAL[MAX_BUFFER_SIZE];
            char SEARCHLOCAL[MAX_BUFFER_SIZE];
            char LOOKUP[MAX_BUFFER_SIZE];
        } HELP;
    } MUXSEARCH;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
    } MUXSHOT;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
        char PRIMARY[MAX_BUFFER_SIZE];
        char SECONDARY[MAX_BUFFER_SIZE];
        char EXTERNAL[MAX_BUFFER_SIZE];
        char SYSTEM[MAX_BUFFER_SIZE];
    } MUXSPACE;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char APPS[MAX_BUFFER_SIZE];
        char BIOS[MAX_BUFFER_SIZE];
        char CATALOGUE[MAX_BUFFER_SIZE];
        char COLLECTION[MAX_BUFFER_SIZE];
        char HISTORY[MAX_BUFFER_SIZE];
        char INIT[MAX_BUFFER_SIZE];
        char MUSIC[MAX_BUFFER_SIZE];;
        char NAME[MAX_BUFFER_SIZE];;
        char NETWORK[MAX_BUFFER_SIZE];
        char PACKAGE[MAX_BUFFER_SIZE];
        char SAVE[MAX_BUFFER_SIZE];
        char SCREENSHOT[MAX_BUFFER_SIZE];
        char SYNCTHING[MAX_BUFFER_SIZE];
        char THEME[MAX_BUFFER_SIZE];
        char TRACK[MAX_BUFFER_SIZE];
        struct {
            char APPS[MAX_BUFFER_SIZE];
            char BIOS[MAX_BUFFER_SIZE];
            char CATALOGUE[MAX_BUFFER_SIZE];
            char COLLECTION[MAX_BUFFER_SIZE];
            char HISTORY[MAX_BUFFER_SIZE];
            char INIT[MAX_BUFFER_SIZE];
            char MUSIC[MAX_BUFFER_SIZE];;
            char NAME[MAX_BUFFER_SIZE];;
            char NETWORK[MAX_BUFFER_SIZE];
            char PACKAGE[MAX_BUFFER_SIZE];
            char SAVE[MAX_BUFFER_SIZE];
            char SCREENSHOT[MAX_BUFFER_SIZE];
            char SYNCTHING[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
            char TRACK[MAX_BUFFER_SIZE];
        } HELP;
    } MUXSTORAGE;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char VERSION[MAX_BUFFER_SIZE];
        char BUILD[MAX_BUFFER_SIZE];
        char DEVICE[MAX_BUFFER_SIZE];
        char KERNEL[MAX_BUFFER_SIZE];
        char UPTIME[MAX_BUFFER_SIZE];
        struct {
            char INFO[MAX_BUFFER_SIZE];
            char DROP[MAX_BUFFER_SIZE];
        } MEMORY;
        char TEMP[MAX_BUFFER_SIZE];
        char CAPACITY[MAX_BUFFER_SIZE];
        char VOLTAGE[MAX_BUFFER_SIZE];
        char CHARGER[MAX_BUFFER_SIZE];
        char RELOAD[MAX_BUFFER_SIZE];
        char RELOAD_RUN[MAX_BUFFER_SIZE];
        struct {
            char INFO[MAX_BUFFER_SIZE];
            char SPEED[MAX_BUFFER_SIZE];
            char GOVERNOR[MAX_BUFFER_SIZE];
        } CPU;
        struct {
            char VERSION[MAX_BUFFER_SIZE];
            char BUILD[MAX_BUFFER_SIZE];
            char DEVICE[MAX_BUFFER_SIZE];
            char KERNEL[MAX_BUFFER_SIZE];
            char UPTIME[MAX_BUFFER_SIZE];
            char MEMORY[MAX_BUFFER_SIZE];
            char TEMP[MAX_BUFFER_SIZE];
            char SERVICE[MAX_BUFFER_SIZE];
            char CAPACITY[MAX_BUFFER_SIZE];
            char VOLTAGE[MAX_BUFFER_SIZE];
            char CHARGER[MAX_BUFFER_SIZE];
            char RELOAD[MAX_BUFFER_SIZE];
            char CPU[MAX_BUFFER_SIZE];
            char SPEED[MAX_BUFFER_SIZE];
            char GOVERNOR[MAX_BUFFER_SIZE];
        } HELP;
    } MUXSYSINFO;

    struct {
        char HELP[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char TITLE[MAX_BUFFER_SIZE];
    } MUXTAG;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
    } MUXTASK;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char ANY[MAX_BUFFER_SIZE];
        char QUIT[MAX_BUFFER_SIZE];
        char QUIT_ALT[MAX_BUFFER_SIZE];
    } MUXTESTER;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char THEME_REMOVED[MAX_BUFFER_SIZE];
        char THEME_EXTRACTING[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char DOWNLOAD[MAX_BUFFER_SIZE];
        struct {
            char THEME[MAX_BUFFER_SIZE];
            char DATA[MAX_BUFFER_SIZE];
            char PREVIEW[MAX_BUFFER_SIZE];
        } DOWN;
        char REMOVE[MAX_BUFFER_SIZE];
        char ERROR_GET_DATA[MAX_BUFFER_SIZE];
    } MUXTHEMEDOWN;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char GRID[MAX_BUFFER_SIZE];
        char HDMI[MAX_BUFFER_SIZE];
        char LANGUAGE[MAX_BUFFER_SIZE];
        char LOOKUP[MAX_BUFFER_SIZE];
        char ALLTHEMES[MAX_BUFFER_SIZE];
        struct {
            char DEVICE[MAX_BUFFER_SIZE];
            char ALL[MAX_BUFFER_SIZE];
        } COMPAT;
        struct {
            char ALLTHEMES[MAX_BUFFER_SIZE];
            char GRID[MAX_BUFFER_SIZE];
            char HDMI[MAX_BUFFER_SIZE];
            char LANGUAGE[MAX_BUFFER_SIZE];
            char LOOKUP[MAX_BUFFER_SIZE];
        } HELP;
    } MUXTHEMEFILTER;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char NONE[MAX_BUFFER_SIZE];
        char SAVE[MAX_BUFFER_SIZE];
        char HELP[MAX_BUFFER_SIZE];
    } MUXTIMEZONE;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char ACCELERATE[MAX_BUFFER_SIZE];
        char REPEATDELAY[MAX_BUFFER_SIZE];
        char THERMAL[MAX_BUFFER_SIZE];
        char OFFSET[MAX_BUFFER_SIZE];
        char PASSCODE[MAX_BUFFER_SIZE];
        char LED[MAX_BUFFER_SIZE];
        char RANDOMTHEME[MAX_BUFFER_SIZE];
        char RETROWAIT[MAX_BUFFER_SIZE];
        char RETROFREE[MAX_BUFFER_SIZE];
        char RETROCACHE[MAX_BUFFER_SIZE];
        char ACTIVITY[MAX_BUFFER_SIZE];
        char VERBOSE[MAX_BUFFER_SIZE];
        char USERINIT[MAX_BUFFER_SIZE];
        char DPADSWAP[MAX_BUFFER_SIZE];
        char OVERDRIVE[MAX_BUFFER_SIZE];
        char SWAPFILE[MAX_BUFFER_SIZE];
        char ZRAMFILE[MAX_BUFFER_SIZE];
        char LIDSWITCH[MAX_BUFFER_SIZE];
        char DISPSUSPEND[MAX_BUFFER_SIZE];
        char SECONDPART[MAX_BUFFER_SIZE];
        char USBPART[MAX_BUFFER_SIZE];
        char INCBRIGHT[MAX_BUFFER_SIZE];
        char INCVOLUME[MAX_BUFFER_SIZE];
        char MAXGPU[MAX_BUFFER_SIZE];
        char AUDIOREADY[MAX_BUFFER_SIZE];
        char AUDIOSWAP[MAX_BUFFER_SIZE];
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char RETRO[MAX_BUFFER_SIZE];
            char MODERN[MAX_BUFFER_SIZE];
        } SWAP;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char DPAD[MAX_BUFFER_SIZE];
            char LS[MAX_BUFFER_SIZE];
            char RS[MAX_BUFFER_SIZE];
            char DPAD_LS[MAX_BUFFER_SIZE];
            char DPAD_RS[MAX_BUFFER_SIZE];
            char DPAD_LS_RS[MAX_BUFFER_SIZE];
            char LS_RS[MAX_BUFFER_SIZE];
        } STICKNAV;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char SILENT[MAX_BUFFER_SIZE];
            char SOFT[MAX_BUFFER_SIZE];
            char LOUD[MAX_BUFFER_SIZE];
        } VOLUME;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char LOW[MAX_BUFFER_SIZE];
            char MEDIUM[MAX_BUFFER_SIZE];
            char HIGH[MAX_BUFFER_SIZE];
        } BRIGHTNESS;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char ST[MAX_BUFFER_SIZE];
            char SH[MAX_BUFFER_SIZE];
            char SL[MAX_BUFFER_SIZE];
            char STSH[MAX_BUFFER_SIZE];
            char STSL[MAX_BUFFER_SIZE];
            char SHSL[MAX_BUFFER_SIZE];
        } RUMBLE;
        struct {
            char ACCELERATE[MAX_BUFFER_SIZE];
            char REPEATDELAY[MAX_BUFFER_SIZE];
            char THERMAL[MAX_BUFFER_SIZE];
            char OFFSET[MAX_BUFFER_SIZE];
            char PASSCODE[MAX_BUFFER_SIZE];
            char LED[MAX_BUFFER_SIZE];
            char RANDOMTHEME[MAX_BUFFER_SIZE];
            char RETROWAIT[MAX_BUFFER_SIZE];
            char RETROFREE[MAX_BUFFER_SIZE];
            char RETROCACHE[MAX_BUFFER_SIZE];
            char ACTIVITY[MAX_BUFFER_SIZE];
            char VERBOSE[MAX_BUFFER_SIZE];
            char USERINIT[MAX_BUFFER_SIZE];
            char DPADSWAP[MAX_BUFFER_SIZE];
            char OVERDRIVE[MAX_BUFFER_SIZE];
            char SWAPFILE[MAX_BUFFER_SIZE];
            char ZRAMFILE[MAX_BUFFER_SIZE];
            char LIDSWITCH[MAX_BUFFER_SIZE];
            char RUMBLE[MAX_BUFFER_SIZE];
            char BRIGHTNESS[MAX_BUFFER_SIZE];
            char VOLUME[MAX_BUFFER_SIZE];
            char SWAP[MAX_BUFFER_SIZE];
            char STICKNAV[MAX_BUFFER_SIZE];
            char DISPSUSPEND[MAX_BUFFER_SIZE];
            char SECONDPART[MAX_BUFFER_SIZE];
            char USBPART[MAX_BUFFER_SIZE];
            char INCBRIGHT[MAX_BUFFER_SIZE];
            char INCVOLUME[MAX_BUFFER_SIZE];
            char MAXGPU[MAX_BUFFER_SIZE];
            char AUDIOREADY[MAX_BUFFER_SIZE];
            char AUDIOSWAP[MAX_BUFFER_SIZE];
        } HELP;
    } MUXTWEAKADV;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char RTC[MAX_BUFFER_SIZE];
        char BRIGHTNESS[MAX_BUFFER_SIZE];
        char BRIGHTNESS_SET[MAX_BUFFER_SIZE];
        char VOLUME[MAX_BUFFER_SIZE];
        char VOLUME_SET[MAX_BUFFER_SIZE];
        char HDMI[MAX_BUFFER_SIZE];
        char ADVANCED[MAX_BUFFER_SIZE];
        char RGB[MAX_BUFFER_SIZE];
        char HKDPAD[MAX_BUFFER_SIZE];
        char HKSHOT[MAX_BUFFER_SIZE];
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char MENU[MAX_BUFFER_SIZE];
            char EXPLORE[MAX_BUFFER_SIZE];
            char COLLECTION[MAX_BUFFER_SIZE];
            char HISTORY[MAX_BUFFER_SIZE];
            char LAST[MAX_BUFFER_SIZE];
            char RESUME[MAX_BUFFER_SIZE];
        } STARTUP;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char RTC[MAX_BUFFER_SIZE];
            char STARTUP[MAX_BUFFER_SIZE];
            char BRIGHTNESS[MAX_BUFFER_SIZE];
            char VOLUME[MAX_BUFFER_SIZE];
            char HDMI[MAX_BUFFER_SIZE];
            char ADVANCED[MAX_BUFFER_SIZE];
            char RGB[MAX_BUFFER_SIZE];
            char HKDPAD[MAX_BUFFER_SIZE];
            char HKSHOT[MAX_BUFFER_SIZE];
        } HELP;
    } MUXTWEAKGEN;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char DEFAULT[MAX_BUFFER_SIZE];
        char COLLECTION[MAX_BUFFER_SIZE];
        char HISTORY[MAX_BUFFER_SIZE];
        char ABANDONED[MAX_BUFFER_SIZE];
        char ALTERNATE[MAX_BUFFER_SIZE];
        char BACKLOG[MAX_BUFFER_SIZE];
        char COMPLECTED[MAX_BUFFER_SIZE];
        char COMPLETED[MAX_BUFFER_SIZE];
        char CURSED[MAX_BUFFER_SIZE];
        char EXPERIMENTAL[MAX_BUFFER_SIZE];
        char HOMEBREW[MAX_BUFFER_SIZE];
        char INPROGRESS[MAX_BUFFER_SIZE];
        char PATCHED[MAX_BUFFER_SIZE];
        char REPLAY[MAX_BUFFER_SIZE];
        char ROMHACK[MAX_BUFFER_SIZE];
        char TRANSLATED[MAX_BUFFER_SIZE];
        struct {
            char DEFAULT[MAX_BUFFER_SIZE];
            char COLLECTION[MAX_BUFFER_SIZE];
            char HISTORY[MAX_BUFFER_SIZE];
            char TAG[MAX_BUFFER_SIZE];
        } HELP;
    } MUXSORT;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char SORT[MAX_BUFFER_SIZE];
        char BATTERY[MAX_BUFFER_SIZE];
        char CLOCK[MAX_BUFFER_SIZE];
        char NETWORK[MAX_BUFFER_SIZE];
        char DASH[MAX_BUFFER_SIZE];
        char FRIENDLYFOLDER[MAX_BUFFER_SIZE];
        char THETITLEFORMAT[MAX_BUFFER_SIZE];
        char TITLEINCLUDEROOTDRIVE[MAX_BUFFER_SIZE];
        char FOLDERITEMCOUNT[MAX_BUFFER_SIZE];
        char DISPLAYEMPTYFOLDER[MAX_BUFFER_SIZE];
        char MENUCOUNTERFOLDER[MAX_BUFFER_SIZE];
        char MENUCOUNTERFILE[MAX_BUFFER_SIZE];
        char HIDDEN[MAX_BUFFER_SIZE];
        char CONTENTCOLLECT[MAX_BUFFER_SIZE];
        char CONTENTHISTORY[MAX_BUFFER_SIZE];
        char MIXEDCONTENT[MAX_BUFFER_SIZE];
        struct {
            char IMAGE[MAX_BUFFER_SIZE];
            char TRANSPARENCY[MAX_BUFFER_SIZE];
            char THEME[MAX_BUFFER_SIZE];
            struct {
                char T1[MAX_BUFFER_SIZE];
                char T4[MAX_BUFFER_SIZE];
            } CHECKERBOARD;
            struct {
                char T1[MAX_BUFFER_SIZE];
                char T2[MAX_BUFFER_SIZE];
                char T4[MAX_BUFFER_SIZE];
            } DIAGONAL;
            struct {
                char T1[MAX_BUFFER_SIZE];
                char T4[MAX_BUFFER_SIZE];
            } LATTICE;
            struct {
                char T1[MAX_BUFFER_SIZE];
                char T2[MAX_BUFFER_SIZE];
                char T4[MAX_BUFFER_SIZE];
            } HORIZONTAL;
            struct {
                char T1[MAX_BUFFER_SIZE];
                char T2[MAX_BUFFER_SIZE];
                char T4[MAX_BUFFER_SIZE];
            } VERTICAL;
        } OVERLAY;
        struct {
            char TITLE[MAX_BUFFER_SIZE];
            char FULL[MAX_BUFFER_SIZE];
            char REM_SQ[MAX_BUFFER_SIZE];
            char REM_PA[MAX_BUFFER_SIZE];
            char REM_SQPA[MAX_BUFFER_SIZE];
        } NAME;
        struct {
            char SORT[MAX_BUFFER_SIZE];
            char BATTERY[MAX_BUFFER_SIZE];
            char CLOCK[MAX_BUFFER_SIZE];
            char NETWORK[MAX_BUFFER_SIZE];
            char DASH[MAX_BUFFER_SIZE];
            char FRIENDLYFOLDER[MAX_BUFFER_SIZE];
            char THETITLEFORMAT[MAX_BUFFER_SIZE];
            char TITLEINCLUDEROOTDRIVE[MAX_BUFFER_SIZE];
            char FOLDERITEMCOUNT[MAX_BUFFER_SIZE];
            char DISPLAYEMPTYFOLDER[MAX_BUFFER_SIZE];
            char MENUCOUNTERFOLDER[MAX_BUFFER_SIZE];
            char MENUCOUNTERFILE[MAX_BUFFER_SIZE];
            char NAME[MAX_BUFFER_SIZE];
            char HIDDEN[MAX_BUFFER_SIZE];
            char CONTENTCOLLECT[MAX_BUFFER_SIZE];
            char CONTENTHISTORY[MAX_BUFFER_SIZE];
            char MIXEDCONTENT[MAX_BUFFER_SIZE];
            char OVERLAYIMAGE[MAX_BUFFER_SIZE];
            char OVERLAYTRANSPARENCY[MAX_BUFFER_SIZE];
        } HELP;
    } MUXVISUAL;

    struct {
        char TITLE[MAX_BUFFER_SIZE];
        char TTYD[MAX_BUFFER_SIZE];
        char SYNCTHING[MAX_BUFFER_SIZE];
        char SSHD[MAX_BUFFER_SIZE];
        char SFTPGO[MAX_BUFFER_SIZE];
        char TAILSCALED[MAX_BUFFER_SIZE];
        struct {
            char TTYD[MAX_BUFFER_SIZE];
            char SYNCTHING[MAX_BUFFER_SIZE];
            char SSHD[MAX_BUFFER_SIZE];
            char SFTPGO[MAX_BUFFER_SIZE];
            char TAILSCALED[MAX_BUFFER_SIZE];
        } HELP;
    } MUXWEBSERV;
};

void load_lang(struct mux_lang *lang);
