// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxvisual

#ifndef _MUXVISUAL_UI_H
#define _MUXVISUAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrVisual
void ui_screen_init(lv_obj_t * ui_pnlContent);
extern lv_obj_t * ui_pnlBattery;
extern lv_obj_t * ui_pnlNetwork;
extern lv_obj_t * ui_pnlBluetooth;
extern lv_obj_t * ui_pnlClock;
extern lv_obj_t * ui_pnlBoxArt;
extern lv_obj_t * ui_pnlName;
extern lv_obj_t * ui_pnlDash;
extern lv_obj_t * ui_pnlMenuCounterFolder;
extern lv_obj_t * ui_pnlMenuCounterFile;
extern lv_obj_t * ui_lblBattery;
extern lv_obj_t * ui_lblNetwork;
extern lv_obj_t * ui_lblBluetooth;
extern lv_obj_t * ui_lblClock;
extern lv_obj_t * ui_lblBoxArt;
extern lv_obj_t * ui_lblName;
extern lv_obj_t * ui_lblDash;
extern lv_obj_t * ui_lblMenuCounterFolder;
extern lv_obj_t * ui_lblMenuCounterFile;
extern lv_obj_t * ui_icoBattery;
extern lv_obj_t * ui_icoNetwork;
extern lv_obj_t * ui_icoBluetooth;
extern lv_obj_t * ui_icoClock;
extern lv_obj_t * ui_icoBoxArt;
extern lv_obj_t * ui_icoName;
extern lv_obj_t * ui_icoDash;
extern lv_obj_t * ui_icoMenuCounterFolder;
extern lv_obj_t * ui_icoMenuCounterFile;
extern lv_obj_t * ui_droBattery;
extern lv_obj_t * ui_droNetwork;
extern lv_obj_t * ui_droBluetooth;
extern lv_obj_t * ui_droClock;
extern lv_obj_t * ui_droBoxArt;
extern lv_obj_t * ui_droName;
extern lv_obj_t * ui_droDash;
extern lv_obj_t * ui_droMenuCounterFolder;
extern lv_obj_t * ui_droMenuCounterFile;

void ui_init(lv_obj_t * ui_pnlContent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
