// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxtweakgen

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrTweakGeneral
void ui_screen_init(lv_obj_t * ui_pnlContent);
lv_obj_t * ui_pnlHidden;
lv_obj_t * ui_pnlBGM;
lv_obj_t * ui_pnlSound;
lv_obj_t * ui_pnlStartup;
lv_obj_t * ui_pnlColour;
lv_obj_t * ui_pnlBrightness;
lv_obj_t * ui_pnlHDMI;
lv_obj_t * ui_pnlShutdown;
lv_obj_t * ui_pnlLanguage;
lv_obj_t * ui_pnlInterface;
lv_obj_t * ui_pnlStorage;
lv_obj_t * ui_pnlAdvanced;
lv_obj_t * ui_lblHidden;
lv_obj_t * ui_lblBGM;
lv_obj_t * ui_lblSound;
lv_obj_t * ui_lblStartup;
lv_obj_t * ui_lblColour;
lv_obj_t * ui_lblBrightness;
lv_obj_t * ui_lblHDMI;
lv_obj_t * ui_lblShutdown;
lv_obj_t * ui_lblLanguage;
lv_obj_t * ui_lblInterface;
lv_obj_t * ui_lblStorage;
lv_obj_t * ui_lblAdvanced;
lv_obj_t * ui_icoHidden;
lv_obj_t * ui_icoBGM;
lv_obj_t * ui_icoSound;
lv_obj_t * ui_icoStartup;
lv_obj_t * ui_icoColour;
lv_obj_t * ui_icoBrightness;
lv_obj_t * ui_icoHDMI;
lv_obj_t * ui_icoShutdown;
lv_obj_t * ui_icoLanguage;
lv_obj_t * ui_icoInterface;
lv_obj_t * ui_icoStorage;
lv_obj_t * ui_icoAdvanced;
lv_obj_t * ui_droHidden;
lv_obj_t * ui_droBGM;
lv_obj_t * ui_droSound;
lv_obj_t * ui_droStartup;
lv_obj_t * ui_droColour;
lv_obj_t * ui_droBrightness;
lv_obj_t * ui_droHDMI;
lv_obj_t * ui_droShutdown;
lv_obj_t * ui_droLanguage;
lv_obj_t * ui_droInterface;
lv_obj_t * ui_droStorage;
lv_obj_t * ui_droAdvanced;

void ui_init(lv_obj_t * ui_pnlContent)
{
    ui_screen_init(ui_pnlContent);
}
