// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxtweakgen

#ifndef _MUXTWEAKGEN_UI_H
#define _MUXTWEAKGEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrTweakGeneral
void ui_screen_init(lv_obj_t * ui_pnlContent);
extern lv_obj_t * ui_pnlHidden;
extern lv_obj_t * ui_pnlBGM;
extern lv_obj_t * ui_pnlSound;
extern lv_obj_t * ui_pnlStartup;
extern lv_obj_t * ui_pnlColour;
extern lv_obj_t * ui_pnlBrightness;
extern lv_obj_t * ui_pnlHDMI;
extern lv_obj_t * ui_pnlShutdown;
extern lv_obj_t * ui_pnlInterface;
extern lv_obj_t * ui_pnlStorage;
extern lv_obj_t * ui_pnlAdvanced;
extern lv_obj_t * ui_lblHidden;
extern lv_obj_t * ui_lblBGM;
extern lv_obj_t * ui_lblSound;
extern lv_obj_t * ui_lblStartup;
extern lv_obj_t * ui_lblColour;
extern lv_obj_t * ui_lblBrightness;
extern lv_obj_t * ui_lblHDMI;
extern lv_obj_t * ui_lblShutdown;
extern lv_obj_t * ui_lblInterface;
extern lv_obj_t * ui_lblStorage;
extern lv_obj_t * ui_lblAdvanced;
extern lv_obj_t * ui_icoHidden;
extern lv_obj_t * ui_icoBGM;
extern lv_obj_t * ui_icoSound;
extern lv_obj_t * ui_icoStartup;
extern lv_obj_t * ui_icoColour;
extern lv_obj_t * ui_icoBrightness;
extern lv_obj_t * ui_icoHDMI;
extern lv_obj_t * ui_icoShutdown;
extern lv_obj_t * ui_icoInterface;
extern lv_obj_t * ui_icoStorage;
extern lv_obj_t * ui_icoAdvanced;
extern lv_obj_t * ui_droHidden;
extern lv_obj_t * ui_droBGM;
extern lv_obj_t * ui_droSound;
extern lv_obj_t * ui_droStartup;
extern lv_obj_t * ui_droColour;
extern lv_obj_t * ui_droBrightness;
extern lv_obj_t * ui_droHDMI;
extern lv_obj_t * ui_droShutdown;
extern lv_obj_t * ui_droInterface;
extern lv_obj_t * ui_droStorage;
extern lv_obj_t * ui_droAdvanced;

void ui_init(lv_obj_t * ui_pnlContent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
