// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxtweakgen

#include "ui.h"

void ui_scrTweakGeneral_screen_init(void)
{
    ui_scrTweakGeneral = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrTweakGeneral, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrTweakGeneral, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrTweakGeneral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrTweakGeneral, &ui_font_NotoSans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlWall = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlWall, 640);
    lv_obj_set_height(ui_pnlWall, 480);
    lv_obj_set_align(ui_pnlWall, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlWall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlWall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlWall, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlWall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlWall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWall = lv_img_create(ui_pnlWall);
    lv_img_set_src(ui_imgWall, &ui_img_nothing_png);
    lv_obj_set_width(ui_imgWall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgWall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWall, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlBox = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlBox, 640);
    lv_obj_set_height(ui_pnlBox, 400);
    lv_obj_set_align(ui_pnlBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlBox, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBox = lv_img_create(ui_pnlBox);
    lv_img_set_src(ui_imgBox, &ui_img_nothing_png);
    lv_obj_set_width(ui_imgBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBox, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgBox, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlHeader = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlHeader, 640);
    lv_obj_set_height(ui_pnlHeader, 42);
    lv_obj_set_align(ui_pnlHeader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHeader, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHeader, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDatetime = lv_label_create(ui_pnlHeader);
    lv_obj_set_height(ui_lblDatetime, 42);
    lv_obj_set_width(ui_lblDatetime, LV_SIZE_CONTENT);   /// 1
    lv_label_set_long_mode(ui_lblDatetime, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblDatetime, "");
    lv_obj_add_flag(ui_lblDatetime, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblDatetime, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDatetime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblDatetime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblDatetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblDatetime, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblDatetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTitle = lv_label_create(ui_pnlHeader);
    lv_obj_set_width(ui_lblTitle, 630);
    lv_obj_set_height(ui_lblTitle, 42);
    lv_obj_set_align(ui_lblTitle, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_lblTitle, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblTitle, "GENERAL SETTINGS");
    lv_obj_add_flag(ui_lblTitle, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblTitle, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTitle, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conGlyphs = lv_obj_create(ui_pnlHeader);
    lv_obj_remove_style_all(ui_conGlyphs);
    lv_obj_set_width(ui_conGlyphs, 110);
    lv_obj_set_height(ui_conGlyphs, 42);
    lv_obj_set_align(ui_conGlyphs, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_conGlyphs, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_conGlyphs, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_conGlyphs, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_conGlyphs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_conGlyphs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_conGlyphs, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_conGlyphs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_conGlyphs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_staBluetooth = lv_label_create(ui_conGlyphs);
    lv_obj_set_width(ui_staBluetooth, 20);
    lv_obj_set_height(ui_staBluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_staBluetooth, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_staBluetooth, "");
    lv_obj_set_style_text_color(ui_staBluetooth, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_staBluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_staBluetooth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_staBluetooth, &ui_font_AwesomeBrand, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_staBluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_staBluetooth, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_staBluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_staBluetooth, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_staNetwork = lv_label_create(ui_conGlyphs);
    lv_obj_set_width(ui_staNetwork, 30);
    lv_obj_set_height(ui_staNetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_staNetwork, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_staNetwork, "");
    lv_obj_set_style_text_color(ui_staNetwork, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_staNetwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_staNetwork, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_staNetwork, &ui_font_Awesome, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_staNetwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_staNetwork, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_staNetwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_staNetwork, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_staCapacity = lv_label_create(ui_conGlyphs);
    lv_obj_set_width(ui_staCapacity, 35);
    lv_obj_set_height(ui_staCapacity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_staCapacity, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_staCapacity, "");
    lv_obj_set_style_text_color(ui_staCapacity, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_staCapacity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_staCapacity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_staCapacity, &ui_font_AwesomeBig, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_staCapacity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_staCapacity, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_staCapacity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_staCapacity, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlContent = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlContent, 640);
    lv_obj_set_height(ui_pnlContent, 400);
    lv_obj_set_x(ui_pnlContent, 0);
    lv_obj_set_y(ui_pnlContent, 34);
    lv_obj_set_align(ui_pnlContent, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlContent, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_pnlContent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_pnlContent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlContent, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlContent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlContent, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHidden = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblHidden, 640);
    lv_obj_set_height(ui_lblHidden, 28);
    lv_obj_set_align(ui_lblHidden, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHidden, "Show Hidden Content");
    lv_obj_set_style_text_color(ui_lblHidden, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHidden, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblHidden, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblHidden, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblHidden, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblHidden, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblHidden, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblHidden, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblHidden, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblHidden, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblHidden, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblHidden, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblHidden, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblHidden, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblHidden, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblHidden, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblHidden, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblBGM = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblBGM, 640);
    lv_obj_set_height(ui_lblBGM, 28);
    lv_obj_set_align(ui_lblBGM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBGM, "Background Music");
    lv_obj_set_style_text_color(ui_lblBGM, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBGM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBGM, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblBGM, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblBGM, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblBGM, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblBGM, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblBGM, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblBGM, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblBGM, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblBGM, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblBGM, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblBGM, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblBGM, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblBGM, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblBGM, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblBGM, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblStartup = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblStartup, 640);
    lv_obj_set_height(ui_lblStartup, 28);
    lv_obj_set_x(ui_lblStartup, 100);
    lv_obj_set_y(ui_lblStartup, -70);
    lv_obj_set_align(ui_lblStartup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblStartup, "Device Startup");
    lv_obj_set_style_text_color(ui_lblStartup, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblStartup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblStartup, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblStartup, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblStartup, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblStartup, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblStartup, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblStartup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblStartup, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblStartup, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblStartup, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblStartup, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblStartup, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblStartup, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblStartup, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblStartup, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblStartup, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblColour = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblColour, 640);
    lv_obj_set_height(ui_lblColour, 28);
    lv_obj_set_x(ui_lblColour, 100);
    lv_obj_set_y(ui_lblColour, -70);
    lv_obj_set_align(ui_lblColour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblColour, "Colour Temperature");
    lv_obj_set_style_text_color(ui_lblColour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblColour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblColour, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblColour, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblColour, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblColour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblColour, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblColour, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblColour, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblColour, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblColour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblColour, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblColour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblColour, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblColour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblColour, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblBrightness = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblBrightness, 640);
    lv_obj_set_height(ui_lblBrightness, 28);
    lv_obj_set_x(ui_lblBrightness, 100);
    lv_obj_set_y(ui_lblBrightness, -70);
    lv_obj_set_align(ui_lblBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBrightness, "Brightness");
    lv_obj_set_style_text_color(ui_lblBrightness, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBrightness, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblBrightness, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblBrightness, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblBrightness, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblBrightness, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblBrightness, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblBrightness, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblBrightness, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblBrightness, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblBrightness, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblBrightness, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblBrightness, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblBrightness, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblBrightness, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblBrightness, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblHDMI = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblHDMI, 640);
    lv_obj_set_height(ui_lblHDMI, 28);
    lv_obj_set_x(ui_lblHDMI, 100);
    lv_obj_set_y(ui_lblHDMI, -70);
    lv_obj_set_align(ui_lblHDMI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHDMI, "HDMI Output");
    lv_obj_set_style_text_color(ui_lblHDMI, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHDMI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblHDMI, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblHDMI, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblHDMI, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblHDMI, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblHDMI, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblHDMI, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblHDMI, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblHDMI, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblHDMI, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblHDMI, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblHDMI, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblHDMI, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblHDMI, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblHDMI, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblHDMI, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblShutdown = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblShutdown, 640);
    lv_obj_set_height(ui_lblShutdown, 28);
    lv_obj_set_x(ui_lblShutdown, 100);
    lv_obj_set_y(ui_lblShutdown, -70);
    lv_obj_set_align(ui_lblShutdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblShutdown, "Sleep Function");
    lv_obj_set_style_text_color(ui_lblShutdown, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblShutdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblShutdown, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblShutdown, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblShutdown, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblShutdown, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblShutdown, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblShutdown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblShutdown, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblShutdown, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblShutdown, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblShutdown, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblShutdown, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblShutdown, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblShutdown, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblShutdown, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblShutdown, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblInterface = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblInterface, 640);
    lv_obj_set_height(ui_lblInterface, 28);
    lv_obj_set_x(ui_lblInterface, 100);
    lv_obj_set_y(ui_lblInterface, -70);
    lv_obj_set_align(ui_lblInterface, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInterface, "Interface Options");
    lv_obj_set_style_text_color(ui_lblInterface, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInterface, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInterface, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblInterface, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblInterface, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblInterface, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblInterface, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblInterface, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblInterface, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblInterface, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblInterface, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblInterface, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblInterface, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblInterface, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblInterface, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblInterface, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblInterface, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblStorage = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblStorage, 640);
    lv_obj_set_height(ui_lblStorage, 28);
    lv_obj_set_x(ui_lblStorage, 100);
    lv_obj_set_y(ui_lblStorage, -70);
    lv_obj_set_align(ui_lblStorage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblStorage, "Storage Preference");
    lv_obj_set_style_text_color(ui_lblStorage, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblStorage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblStorage, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblStorage, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblStorage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblStorage, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblStorage, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblStorage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblStorage, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblStorage, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblStorage, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblStorage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblStorage, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblStorage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblStorage, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblStorage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblStorage, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_lblAdvanced = lv_label_create(ui_pnlContent);
    lv_obj_set_width(ui_lblAdvanced, 640);
    lv_obj_set_height(ui_lblAdvanced, 28);
    lv_obj_set_x(ui_lblAdvanced, 100);
    lv_obj_set_y(ui_lblAdvanced, -70);
    lv_obj_set_align(ui_lblAdvanced, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAdvanced, "Advanced Settings");
    lv_obj_set_style_text_color(ui_lblAdvanced, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblAdvanced, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_lblAdvanced, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_lblAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_lblAdvanced, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_lblAdvanced, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblAdvanced, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblAdvanced, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblAdvanced, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblAdvanced, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblAdvanced, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblAdvanced, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lblAdvanced, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_lblAdvanced, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_lblAdvanced, 25, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_lblAdvanced, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_lblAdvanced, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_pnlGlyph = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlGlyph, 640);
    lv_obj_set_height(ui_pnlGlyph, 400);
    lv_obj_set_x(ui_pnlGlyph, 0);
    lv_obj_set_y(ui_pnlGlyph, 34);
    lv_obj_set_align(ui_pnlGlyph, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlGlyph, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_pnlGlyph, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_pnlGlyph, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_pnlGlyph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlGlyph, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlGlyph, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlGlyph, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pnlGlyph, &ui_font_AwesomeSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icoHidden = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoHidden, 640);
    lv_obj_set_height(ui_icoHidden, 28);
    lv_obj_set_align(ui_icoHidden, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoHidden, "");
    lv_obj_set_style_text_color(ui_icoHidden, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoHidden, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoHidden, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoHidden, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoHidden, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoHidden, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoBGM = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoBGM, 640);
    lv_obj_set_height(ui_icoBGM, 28);
    lv_obj_set_align(ui_icoBGM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoBGM, "");
    lv_obj_set_style_text_color(ui_icoBGM, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoBGM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoBGM, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoBGM, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoBGM, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoBGM, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoStartup = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoStartup, 640);
    lv_obj_set_height(ui_icoStartup, 28);
    lv_obj_set_x(ui_icoStartup, 100);
    lv_obj_set_y(ui_icoStartup, -70);
    lv_obj_set_align(ui_icoStartup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoStartup, "");
    lv_obj_set_style_text_color(ui_icoStartup, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoStartup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoStartup, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoStartup, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoStartup, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoStartup, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoColour = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoColour, 640);
    lv_obj_set_height(ui_icoColour, 28);
    lv_obj_set_x(ui_icoColour, 100);
    lv_obj_set_y(ui_icoColour, -70);
    lv_obj_set_align(ui_icoColour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoColour, "");
    lv_obj_set_style_text_color(ui_icoColour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoColour, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoColour, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoColour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoColour, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoBrightness = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoBrightness, 640);
    lv_obj_set_height(ui_icoBrightness, 28);
    lv_obj_set_x(ui_icoBrightness, 100);
    lv_obj_set_y(ui_icoBrightness, -70);
    lv_obj_set_align(ui_icoBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoBrightness, "");
    lv_obj_set_style_text_color(ui_icoBrightness, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoBrightness, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoBrightness, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoBrightness, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoBrightness, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoHDMI = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoHDMI, 640);
    lv_obj_set_height(ui_icoHDMI, 28);
    lv_obj_set_x(ui_icoHDMI, 100);
    lv_obj_set_y(ui_icoHDMI, -70);
    lv_obj_set_align(ui_icoHDMI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoHDMI, "");
    lv_obj_set_style_text_color(ui_icoHDMI, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoHDMI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoHDMI, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoHDMI, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoHDMI, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoHDMI, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoShutdown = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoShutdown, 640);
    lv_obj_set_height(ui_icoShutdown, 28);
    lv_obj_set_x(ui_icoShutdown, 100);
    lv_obj_set_y(ui_icoShutdown, -70);
    lv_obj_set_align(ui_icoShutdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoShutdown, "");
    lv_obj_set_style_text_color(ui_icoShutdown, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoShutdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoShutdown, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoShutdown, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoShutdown, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoShutdown, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoInterface = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoInterface, 640);
    lv_obj_set_height(ui_icoInterface, 28);
    lv_obj_set_x(ui_icoInterface, 100);
    lv_obj_set_y(ui_icoInterface, -70);
    lv_obj_set_align(ui_icoInterface, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoInterface, "");
    lv_obj_set_style_text_color(ui_icoInterface, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoInterface, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoInterface, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoInterface, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoInterface, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoInterface, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoStorage = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoStorage, 640);
    lv_obj_set_height(ui_icoStorage, 28);
    lv_obj_set_x(ui_icoStorage, 100);
    lv_obj_set_y(ui_icoStorage, -70);
    lv_obj_set_align(ui_icoStorage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoStorage, "");
    lv_obj_set_style_text_color(ui_icoStorage, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoStorage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoStorage, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoStorage, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoStorage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoStorage, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_icoAdvanced = lv_label_create(ui_pnlGlyph);
    lv_obj_set_width(ui_icoAdvanced, 640);
    lv_obj_set_height(ui_icoAdvanced, 28);
    lv_obj_set_x(ui_icoAdvanced, 100);
    lv_obj_set_y(ui_icoAdvanced, -70);
    lv_obj_set_align(ui_icoAdvanced, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoAdvanced, "");
    lv_obj_set_style_text_color(ui_icoAdvanced, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoAdvanced, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoAdvanced, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_icoAdvanced, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_icoAdvanced, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_pnlHighlight = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlHighlight, 640);
    lv_obj_set_height(ui_pnlHighlight, 400);
    lv_obj_set_x(ui_pnlHighlight, 0);
    lv_obj_set_y(ui_pnlHighlight, 34);
    lv_obj_set_align(ui_pnlHighlight, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pnlHighlight, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_pnlHighlight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_pnlHighlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlHighlight, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlHighlight, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlHighlight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlHighlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_droHidden = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droHidden, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droHidden, "Disabled\nEnabled");
    lv_dropdown_set_selected_highlight(ui_droHidden, false);
    lv_obj_set_width(ui_droHidden, 640);
    lv_obj_set_height(ui_droHidden, 28);
    lv_obj_set_align(ui_droHidden, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droHidden, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droHidden, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droHidden, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droHidden, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droHidden, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droHidden, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droHidden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droHidden, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droHidden, 255, LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_border_width(ui_droHidden, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_text_color(ui_droHidden, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droHidden, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_droHidden), lv_color_hex(0x02080D),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_droHidden), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_droHidden), lv_color_hex(0xF8E008),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_droHidden), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_droHidden), lv_color_hex(0xF8E008),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_droHidden), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_droBGM = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droBGM, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droBGM, "Disabled\nEnabled");
    lv_dropdown_set_selected_highlight(ui_droBGM, false);
    lv_obj_set_width(ui_droBGM, 640);
    lv_obj_set_height(ui_droBGM, 28);
    lv_obj_set_align(ui_droBGM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droBGM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droBGM, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droBGM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droBGM, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droBGM, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droBGM, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droBGM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droBGM, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droBGM, 255, LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_border_width(ui_droBGM, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_text_color(ui_droBGM, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droBGM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_droBGM), lv_color_hex(0x02080D),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_droBGM), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_droBGM), lv_color_hex(0xF8E008),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_droBGM), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_droBGM), lv_color_hex(0xF8E008),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_droBGM), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_droStartup = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droStartup, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droStartup, "Main Menu\nContent Explorer\nFavourites\nHistory\nLast Game\nResume Game");
    lv_dropdown_set_selected_highlight(ui_droStartup, false);
    lv_obj_set_width(ui_droStartup, 640);
    lv_obj_set_height(ui_droStartup, 28);
    lv_obj_set_x(ui_droStartup, 100);
    lv_obj_set_y(ui_droStartup, -30);
    lv_obj_set_align(ui_droStartup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droStartup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droStartup, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droStartup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droStartup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droStartup, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droStartup, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droStartup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droStartup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droStartup, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droStartup, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droStartup, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droStartup, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_droStartup), lv_color_hex(0x000000),
                                  LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_droStartup), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    ui_droColour = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droColour, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droColour,
                            "Deep Arctic (-256)\nIcy Chill (-224)\nFrosty Breeze (-192)\nCool Glacier (-160)\nArctic Frost (-128)\nWinter Sky (-96)\nFrostbite Blue (-64)\nArctic Blue (-32)\nNeutral White (0)\nDaylight White (32)\nWarm White (64)\nSoft Ivory (96)\nCandlelight Yellow (128)\nWarm Glow (160)\nSunset Orange (192)\nAmber Flame (224)\nDeep Ember (256)");
    lv_dropdown_set_selected_highlight(ui_droColour, false);
    lv_obj_set_width(ui_droColour, 640);
    lv_obj_set_height(ui_droColour, 28);
    lv_obj_set_x(ui_droColour, 100);
    lv_obj_set_y(ui_droColour, -30);
    lv_obj_set_align(ui_droColour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droColour, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droColour, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droColour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droColour, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droColour, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droColour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droColour, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droColour, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droColour, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droColour, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_droBrightness = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droBrightness, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droBrightness,
                            "1%\n2%\n3%\n4%\n5%\n6%\n7%\n8%\n9%\n10%\n11%\n12%\n13%\n14%\n15%\n16%\n17%\n18%\n19%\n20%\n21%\n22%\n23%\n24%\n25%\n26%\n27%\n28%\n29%\n30%\n31%\n32%\n33%\n34%\n35%\n36%\n37%\n38%\n39%\n40%\n41%\n42%\n43%\n44%\n45%\n46%\n47%\n48%\n49%\n50%\n51%\n52%\n53%\n54%\n55%\n56%\n57%\n58%\n59%\n60%\n61%\n62%\n63%\n64%\n65%\n66%\n67%\n68%\n69%\n70%\n71%\n72%\n73%\n74%\n75%\n76%\n77%\n78%\n79%\n80%\n81%\n82%\n83%\n84%\n85%\n86%\n87%\n88%\n89%\n90%\n91%\n92%\n93%\n94%\n95%\n96%\n97%\n98%\n99%\n100%");
    lv_dropdown_set_selected_highlight(ui_droBrightness, false);
    lv_obj_set_width(ui_droBrightness, 640);
    lv_obj_set_height(ui_droBrightness, 28);
    lv_obj_set_x(ui_droBrightness, 100);
    lv_obj_set_y(ui_droBrightness, -30);
    lv_obj_set_align(ui_droBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droBrightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droBrightness, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droBrightness, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droBrightness, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droBrightness, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droBrightness, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droBrightness, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droBrightness, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_droHDMI = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droHDMI, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droHDMI,
                            "Disabled\n480i\n576i\n480p\n576p\n720p + 50hz\n720p + 60hz\n1080i + 50hz\n1080i + 60hz\n1080p + 24hz\n1080p + 50hz\n1080p + 60hz");
    lv_dropdown_set_selected_highlight(ui_droHDMI, false);
    lv_obj_set_width(ui_droHDMI, 640);
    lv_obj_set_height(ui_droHDMI, 28);
    lv_obj_set_x(ui_droHDMI, 100);
    lv_obj_set_y(ui_droHDMI, -30);
    lv_obj_set_align(ui_droHDMI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droHDMI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droHDMI, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droHDMI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droHDMI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droHDMI, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droHDMI, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droHDMI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droHDMI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droHDMI, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droHDMI, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droHDMI, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droHDMI, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_droShutdown = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droShutdown, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droShutdown,
                            "Disabled\nSleep Suspend\nInstant Shutdown\nSleep 10s + Shutdown\nSleep 30s + Shutdown\nSleep 60s + Shutdown\nSleep 2m + Shutdown\nSleep 5m + Shutdown\nSleep 10m + Shutdown\nSleep 30m + Shutdown\nSleep 60m + Shutdown");
    lv_dropdown_set_selected_highlight(ui_droShutdown, false);
    lv_obj_set_width(ui_droShutdown, 640);
    lv_obj_set_height(ui_droShutdown, 28);
    lv_obj_set_x(ui_droShutdown, 100);
    lv_obj_set_y(ui_droShutdown, -30);
    lv_obj_set_align(ui_droShutdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droShutdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droShutdown, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droShutdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droShutdown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droShutdown, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droShutdown, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droShutdown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droShutdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droShutdown, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droShutdown, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droShutdown, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droShutdown, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_droInterface = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droInterface, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droInterface, "");
    lv_dropdown_set_selected_highlight(ui_droInterface, false);
    lv_obj_set_width(ui_droInterface, 640);
    lv_obj_set_height(ui_droInterface, 28);
    lv_obj_set_x(ui_droInterface, 100);
    lv_obj_set_y(ui_droInterface, -30);
    lv_obj_set_align(ui_droInterface, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droInterface, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droInterface, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droInterface, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droInterface, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droInterface, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droInterface, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droInterface, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droInterface, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droInterface, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droInterface, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droInterface, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droInterface, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_droStorage = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droStorage, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droStorage, "");
    lv_dropdown_set_selected_highlight(ui_droStorage, false);
    lv_obj_set_width(ui_droStorage, 640);
    lv_obj_set_height(ui_droStorage, 28);
    lv_obj_set_x(ui_droStorage, 100);
    lv_obj_set_y(ui_droStorage, -30);
    lv_obj_set_align(ui_droStorage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droStorage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droStorage, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droStorage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droStorage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droStorage, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droStorage, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droStorage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droStorage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droStorage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droStorage, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droStorage, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droStorage, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_droAdvanced = lv_dropdown_create(ui_pnlHighlight);
    lv_dropdown_set_dir(ui_droAdvanced, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_droAdvanced, "");
    lv_dropdown_set_selected_highlight(ui_droAdvanced, false);
    lv_obj_set_width(ui_droAdvanced, 640);
    lv_obj_set_height(ui_droAdvanced, 28);
    lv_obj_set_x(ui_droAdvanced, 100);
    lv_obj_set_y(ui_droAdvanced, -30);
    lv_obj_set_align(ui_droAdvanced, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droAdvanced, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droAdvanced, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_droAdvanced, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droAdvanced, lv_color_hex(0x403A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_droAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_droAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_droAdvanced, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_droAdvanced, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_droAdvanced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_droAdvanced, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_text_opa(ui_droAdvanced, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(ui_droAdvanced, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droAdvanced, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_pnlFooter = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlFooter, 640);
    lv_obj_set_height(ui_pnlFooter, 42);
    lv_obj_set_align(ui_pnlFooter, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlFooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlFooter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlFooter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlFooter, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlFooter, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnlFooter, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnlFooter, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavAGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavAGlyph, 25);
    lv_obj_set_height(ui_lblNavAGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavAGlyph, -197);
    lv_obj_set_y(ui_lblNavAGlyph, -208);
    lv_obj_set_align(ui_lblNavAGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavAGlyph, "⇓");
    lv_label_set_recolor(ui_lblNavAGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavAGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavAGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavAGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavAGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavA = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavA, -197);
    lv_obj_set_y(ui_lblNavA, -208);
    lv_obj_set_align(ui_lblNavA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavA, "");
    lv_label_set_recolor(ui_lblNavA, "true");
    lv_obj_set_style_text_color(ui_lblNavA, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavA, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavBGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavBGlyph, 25);
    lv_obj_set_height(ui_lblNavBGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavBGlyph, -197);
    lv_obj_set_y(ui_lblNavBGlyph, -208);
    lv_obj_set_align(ui_lblNavBGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavBGlyph, "⇒");
    lv_label_set_recolor(ui_lblNavBGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavBGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavBGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavBGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavBGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavB = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavB, -197);
    lv_obj_set_y(ui_lblNavB, -208);
    lv_obj_set_align(ui_lblNavB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavB, "");
    lv_label_set_recolor(ui_lblNavB, "true");
    lv_obj_set_style_text_color(ui_lblNavB, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavB, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavCGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavCGlyph, 25);
    lv_obj_set_height(ui_lblNavCGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavCGlyph, -197);
    lv_obj_set_y(ui_lblNavCGlyph, -208);
    lv_obj_set_align(ui_lblNavCGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavCGlyph, "⇫");
    lv_label_set_recolor(ui_lblNavCGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavCGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavCGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavCGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavCGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavC = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavC, -197);
    lv_obj_set_y(ui_lblNavC, -208);
    lv_obj_set_align(ui_lblNavC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavC, "");
    lv_label_set_recolor(ui_lblNavC, "true");
    lv_obj_set_style_text_color(ui_lblNavC, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavC, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavXGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavXGlyph, 25);
    lv_obj_set_height(ui_lblNavXGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavXGlyph, -197);
    lv_obj_set_y(ui_lblNavXGlyph, -208);
    lv_obj_set_align(ui_lblNavXGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavXGlyph, "⇣");
    lv_label_set_recolor(ui_lblNavXGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavXGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavXGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavXGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavXGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavX = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavX, -197);
    lv_obj_set_y(ui_lblNavX, -208);
    lv_obj_set_align(ui_lblNavX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavX, "");
    lv_label_set_recolor(ui_lblNavX, "true");
    lv_obj_set_style_text_color(ui_lblNavX, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavX, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavYGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavYGlyph, 25);
    lv_obj_set_height(ui_lblNavYGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavYGlyph, -197);
    lv_obj_set_y(ui_lblNavYGlyph, -208);
    lv_obj_set_align(ui_lblNavYGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavYGlyph, "⇑");
    lv_label_set_recolor(ui_lblNavYGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavYGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavYGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavYGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavYGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavY = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavY, -197);
    lv_obj_set_y(ui_lblNavY, -208);
    lv_obj_set_align(ui_lblNavY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavY, "");
    lv_label_set_recolor(ui_lblNavY, "true");
    lv_obj_set_style_text_color(ui_lblNavY, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavY, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavZGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavZGlyph, 25);
    lv_obj_set_height(ui_lblNavZGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavZGlyph, -197);
    lv_obj_set_y(ui_lblNavZGlyph, -208);
    lv_obj_set_align(ui_lblNavZGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavZGlyph, "⇬");
    lv_label_set_recolor(ui_lblNavZGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavZGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavZGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavZGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavZGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavZ = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavZ, -197);
    lv_obj_set_y(ui_lblNavZ, -208);
    lv_obj_set_align(ui_lblNavZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavZ, "");
    lv_label_set_recolor(ui_lblNavZ, "true");
    lv_obj_set_style_text_color(ui_lblNavZ, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavZ, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavMenuGlyph = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavMenuGlyph, 27);
    lv_obj_set_height(ui_lblNavMenuGlyph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavMenuGlyph, -197);
    lv_obj_set_y(ui_lblNavMenuGlyph, -208);
    lv_obj_set_align(ui_lblNavMenuGlyph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavMenuGlyph, "⇥");
    lv_label_set_recolor(ui_lblNavMenuGlyph, "true");
    lv_obj_set_style_text_color(ui_lblNavMenuGlyph, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNavMenuGlyph, &ui_font_GamepadNav, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavMenuGlyph, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavMenuGlyph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNavMenu = lv_label_create(ui_pnlFooter);
    lv_obj_set_width(ui_lblNavMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNavMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNavMenu, -197);
    lv_obj_set_y(ui_lblNavMenu, -208);
    lv_obj_set_align(ui_lblNavMenu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNavMenu, "");
    lv_label_set_recolor(ui_lblNavMenu, "true");
    lv_obj_set_style_text_color(ui_lblNavMenu, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNavMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblNavMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblNavMenu, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblNavMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblNavMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlMessage = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlMessage, 615);
    lv_obj_set_height(ui_pnlMessage, 42);
    lv_obj_set_x(ui_pnlMessage, 0);
    lv_obj_set_y(ui_pnlMessage, -47);
    lv_obj_set_align(ui_pnlMessage, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlMessage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlMessage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlMessage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlMessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlMessage, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlMessage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlMessage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlMessage, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMessage = lv_label_create(ui_pnlMessage);
    lv_obj_set_width(ui_lblMessage, 600);
    lv_obj_set_height(ui_lblMessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMessage, -197);
    lv_obj_set_y(ui_lblMessage, -208);
    lv_obj_set_align(ui_lblMessage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMessage, "");
    lv_label_set_recolor(ui_lblMessage, "true");
    lv_obj_set_style_text_color(ui_lblMessage, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblMessage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMessage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMessage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlHelp = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlHelp, 640);
    lv_obj_set_height(ui_pnlHelp, 480);
    lv_obj_set_align(ui_pnlHelp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlHelp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlHelp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHelp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHelp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHelp, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHelp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHelp, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlHelp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlHelpMessage = lv_obj_create(ui_pnlHelp);
    lv_obj_set_width(ui_pnlHelpMessage, 550);
    lv_obj_set_height(ui_pnlHelpMessage, 385);
    lv_obj_set_align(ui_pnlHelpMessage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pnlHelpMessage, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_pnlHelpMessage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlHelpMessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlHelpMessage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlHelpMessage, lv_color_hex(0x0D0803), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHelpMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlHelpMessage, lv_color_hex(0xF8E008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlHelpMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlHelpMessage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlHelpMessage, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_pnlHelpMessage, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_pnlHelpMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHelpHeader = lv_label_create(ui_pnlHelpMessage);
    lv_obj_set_width(ui_lblHelpHeader, 515);
    lv_obj_set_height(ui_lblHelpHeader, 22);
    lv_obj_set_align(ui_lblHelpHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHelpHeader, "%helpheader%");
    lv_obj_set_style_text_color(ui_lblHelpHeader, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHelpHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHelpContent = lv_label_create(ui_pnlHelpMessage);
    lv_obj_set_width(ui_lblHelpContent, 515);
    lv_obj_set_height(ui_lblHelpContent, 308);
    lv_obj_set_align(ui_lblHelpContent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHelpContent, "%helpcontext%");
    lv_obj_set_style_text_color(ui_lblHelpContent, lv_color_hex(0xA5B2B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHelpContent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlProgressBrightness = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlProgressBrightness, 615);
    lv_obj_set_height(ui_pnlProgressBrightness, 42);
    lv_obj_set_x(ui_pnlProgressBrightness, 0);
    lv_obj_set_y(ui_pnlProgressBrightness, -47);
    lv_obj_set_align(ui_pnlProgressBrightness, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlProgressBrightness, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlProgressBrightness, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlProgressBrightness, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlProgressBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlProgressBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlProgressBrightness, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlProgressBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlProgressBrightness, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlProgressBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlProgressBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlProgressBrightness, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icoProgressBrightness = lv_label_create(ui_pnlProgressBrightness);
    lv_obj_set_width(ui_icoProgressBrightness, 18);
    lv_obj_set_height(ui_icoProgressBrightness, 28);
    lv_obj_set_x(ui_icoProgressBrightness, -197);
    lv_obj_set_y(ui_icoProgressBrightness, -208);
    lv_obj_set_align(ui_icoProgressBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoProgressBrightness, "");
    lv_label_set_recolor(ui_icoProgressBrightness, "true");
    lv_obj_set_style_text_color(ui_icoProgressBrightness, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoProgressBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_icoProgressBrightness, &ui_font_AwesomeSmall, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoProgressBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoProgressBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoProgressBrightness, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoProgressBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barProgressBrightness = lv_bar_create(ui_pnlProgressBrightness);
    lv_bar_set_value(ui_barProgressBrightness, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barProgressBrightness, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barProgressBrightness, 550);
    lv_obj_set_height(ui_barProgressBrightness, 16);
    lv_obj_set_align(ui_barProgressBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barProgressBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barProgressBrightness, lv_color_hex(0x7E730C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barProgressBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barProgressBrightness, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barProgressBrightness, lv_color_hex(0xF7E318), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barProgressBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_pnlProgressVolume = lv_obj_create(ui_scrTweakGeneral);
    lv_obj_set_width(ui_pnlProgressVolume, 615);
    lv_obj_set_height(ui_pnlProgressVolume, 42);
    lv_obj_set_x(ui_pnlProgressVolume, 0);
    lv_obj_set_y(ui_pnlProgressVolume, -47);
    lv_obj_set_align(ui_pnlProgressVolume, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlProgressVolume, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlProgressVolume, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlProgressVolume, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlProgressVolume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlProgressVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlProgressVolume, lv_color_hex(0x100808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlProgressVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlProgressVolume, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlProgressVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlProgressVolume, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlProgressVolume, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icoProgressVolume = lv_label_create(ui_pnlProgressVolume);
    lv_obj_set_width(ui_icoProgressVolume, 18);
    lv_obj_set_height(ui_icoProgressVolume, 28);
    lv_obj_set_x(ui_icoProgressVolume, -197);
    lv_obj_set_y(ui_icoProgressVolume, -208);
    lv_obj_set_align(ui_icoProgressVolume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icoProgressVolume, "");
    lv_label_set_recolor(ui_icoProgressVolume, "true");
    lv_obj_set_style_text_color(ui_icoProgressVolume, lv_color_hex(0xF7E318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icoProgressVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_icoProgressVolume, &ui_font_AwesomeSmall, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_icoProgressVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_icoProgressVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_icoProgressVolume, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_icoProgressVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barProgressVolume = lv_bar_create(ui_pnlProgressVolume);
    lv_bar_set_value(ui_barProgressVolume, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barProgressVolume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barProgressVolume, 550);
    lv_obj_set_height(ui_barProgressVolume, 16);
    lv_obj_set_align(ui_barProgressVolume, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barProgressVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barProgressVolume, lv_color_hex(0x7E730C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barProgressVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barProgressVolume, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barProgressVolume, lv_color_hex(0xF7E318), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barProgressVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
