#include "ui.h"

void ui_screen_init(lv_obj_t *ui_pnlContent);

lv_obj_t *ui_pnlAccelerate;
lv_obj_t *ui_pnlSwap;
lv_obj_t *ui_pnlThermal;
lv_obj_t *ui_pnlFont;
lv_obj_t *ui_pnlVolume;
lv_obj_t *ui_pnlBrightness;
lv_obj_t *ui_pnlOffset;
lv_obj_t *ui_pnlPasscode;
lv_obj_t *ui_pnlLED;
lv_obj_t *ui_pnlTheme;
lv_obj_t *ui_pnlRetroWait;
lv_obj_t *ui_pnlUSBFunction;
lv_obj_t *ui_pnlState;
lv_obj_t *ui_pnlVerbose;
lv_obj_t *ui_pnlHDMIOutput;
lv_obj_t *ui_pnlStorage;
lv_obj_t *ui_lblAccelerate;
lv_obj_t *ui_lblSwap;
lv_obj_t *ui_lblThermal;
lv_obj_t *ui_lblFont;
lv_obj_t *ui_lblVolume;
lv_obj_t *ui_lblBrightness;
lv_obj_t *ui_lblOffset;
lv_obj_t *ui_lblPasscode;
lv_obj_t *ui_lblLED;
lv_obj_t *ui_lblTheme;
lv_obj_t *ui_lblRetroWait;
lv_obj_t *ui_lblUSBFunction;
lv_obj_t *ui_lblState;
lv_obj_t *ui_lblVerbose;
lv_obj_t *ui_lblHDMIOutput;
lv_obj_t *ui_lblStorage;
lv_obj_t *ui_icoAccelerate;
lv_obj_t *ui_icoSwap;
lv_obj_t *ui_icoThermal;
lv_obj_t *ui_icoFont;
lv_obj_t *ui_icoVolume;
lv_obj_t *ui_icoBrightness;
lv_obj_t *ui_icoOffset;
lv_obj_t *ui_icoPasscode;
lv_obj_t *ui_icoLED;
lv_obj_t *ui_icoTheme;
lv_obj_t *ui_icoRetroWait;
lv_obj_t *ui_icoUSBFunction;
lv_obj_t *ui_icoState;
lv_obj_t *ui_icoVerbose;
lv_obj_t *ui_icoHDMIOutput;
lv_obj_t *ui_icoStorage;
lv_obj_t *ui_droAccelerate;
lv_obj_t *ui_droSwap;
lv_obj_t *ui_droThermal;
lv_obj_t *ui_droFont;
lv_obj_t *ui_droVolume;
lv_obj_t *ui_droBrightness;
lv_obj_t *ui_droOffset;
lv_obj_t *ui_droPasscode;
lv_obj_t *ui_droLED;
lv_obj_t *ui_droTheme;
lv_obj_t *ui_droRetroWait;
lv_obj_t *ui_droUSBFunction;
lv_obj_t *ui_droState;
lv_obj_t *ui_droVerbose;
lv_obj_t *ui_droHDMIOutput;
lv_obj_t *ui_droStorage;

void ui_init(lv_obj_t *ui_pnlContent) {
    ui_screen_init(ui_pnlContent);
}
