// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: muxtweakadv

#ifndef _MUXTWEAKADV_UI_H
#define _MUXTWEAKADV_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrTweakAdvanced
void ui_screen_init(lv_obj_t * ui_pnlContent);
extern lv_obj_t * ui_pnlAccelerate;
extern lv_obj_t * ui_pnlSwap;
extern lv_obj_t * ui_pnlThermal;
extern lv_obj_t * ui_pnlFont;
extern lv_obj_t * ui_pnlVolume;
extern lv_obj_t * ui_pnlBrightness;
extern lv_obj_t * ui_pnlOffset;
extern lv_obj_t * ui_pnlPasscode;
extern lv_obj_t * ui_pnlLED;
extern lv_obj_t * ui_pnlTheme;
extern lv_obj_t * ui_pnlRetroWait;
extern lv_obj_t * ui_pnlAndroid;
extern lv_obj_t * ui_pnlState;
extern lv_obj_t * ui_pnlVerbose;
extern lv_obj_t * ui_lblAccelerate;
extern lv_obj_t * ui_lblSwap;
extern lv_obj_t * ui_lblThermal;
extern lv_obj_t * ui_lblFont;
extern lv_obj_t * ui_lblVolume;
extern lv_obj_t * ui_lblBrightness;
extern lv_obj_t * ui_lblOffset;
extern lv_obj_t * ui_lblPasscode;
extern lv_obj_t * ui_lblLED;
extern lv_obj_t * ui_lblTheme;
extern lv_obj_t * ui_lblRetroWait;
extern lv_obj_t * ui_lblAndroid;
extern lv_obj_t * ui_lblState;
extern lv_obj_t * ui_lblVerbose;
extern lv_obj_t * ui_icoAccelerate;
extern lv_obj_t * ui_icoSwap;
extern lv_obj_t * ui_icoThermal;
extern lv_obj_t * ui_icoFont;
extern lv_obj_t * ui_icoVolume;
extern lv_obj_t * ui_icoBrightness;
extern lv_obj_t * ui_icoOffset;
extern lv_obj_t * ui_icoPasscode;
extern lv_obj_t * ui_icoLED;
extern lv_obj_t * ui_icoTheme;
extern lv_obj_t * ui_icoRetroWait;
extern lv_obj_t * ui_icoAndroid;
extern lv_obj_t * ui_icoState;
extern lv_obj_t * ui_icoVerbose;
extern lv_obj_t * ui_droAccelerate;
extern lv_obj_t * ui_droSwap;
extern lv_obj_t * ui_droThermal;
extern lv_obj_t * ui_droFont;
extern lv_obj_t * ui_droVolume;
extern lv_obj_t * ui_droBrightness;
extern lv_obj_t * ui_droOffset;
extern lv_obj_t * ui_droPasscode;
extern lv_obj_t * ui_droLED;
extern lv_obj_t * ui_droTheme;
extern lv_obj_t * ui_droRetroWait;
extern lv_obj_t * ui_droAndroid;
extern lv_obj_t * ui_droState;
extern lv_obj_t * ui_droVerbose;

void ui_init(lv_obj_t * ui_pnlContent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
